### ISSUE TITLE
list type fields drag and drop sorting bug

### ISSUE THREAD

**Issue by phideas** [getgrav/grav-plugin-admin#1002]
created a custom modular page with list items in blueprint.

when dragging list item, all the items below are dragged too.
please take a look at [Screenshot](http://imgur.com/a/I3oBJ)
to see the weird behavior.

it would be nice if anybode could replicate and confirm.

**Comment by chriseaton** [comment]
I can confirm I experience this as well. It can become unwieldy when lots of items are added.

**Comment by rhukster** [comment]
This is a known UI bug.  If you collapse all the sections, dragging works fine.

**Comment by phideas** [comment]
Thanks for the response. Actually you can see in the screnshot that all the sections are collapsed and the dragging is still buggy.

**Comment by rhukster** [comment]
Hmm.. only buggy for me when i tried it expanded.  It's only Chrome right? This is actually a bug with the draggables library we are using. We're going to check if its been updated and sorted.

**Comment by w00fz** [comment]
I think when we were looking at yours, Andy, was also collapsed.

I know this issue and yes when the item is collapsed, if you try to drag the ghost that follows the mouse is expanded and looks broken.
If you drag an expanded item no problem.
This is a chrome rendering issue relative to overflow hidden and drag and drop.

**Comment by phideas** [comment]
Checked in Chrome and FF. You are right. Only Chrome is affected. In Firefox tha dragging works correctly.

**Comment by w00fz** [comment]
Thanks for confirming that, I know worked around the rendering bug and it will work the same in Chrome.
