### ISSUE TITLE
Integrate `child_type` to New Page modal

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav-plugin-admin#1008]
The `child_type:` frontmatter option is an admin-specific option that you can set via the Overrides, and the intention is to all you to set a default child type in the parent page.  For example, in `blog.md` you could set this `item` and then when creating a new page under blog, it should automatically be set to `item`. 

Currently this is being overridden by the new page modal.  The new page modal is forcing a type to be set and is not taking into account the parent type.  When the parent field is changed in this new page modal, the `Page::childType()` should be checked (or this should be checked while building the parent select), and then the value of the template should be changed according if a value is found for that parent.

**Comment by w00fz** [comment]
This is now implemented in the feature and can be tested/merged.
