### ISSUE TITLE
Editor Image Download?

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#1010]
It should be possible to download images in editor. At the moment you can only upload, insert or delete.
![editor](https://cloud.githubusercontent.com/assets/12480617/23697065/90e38808-03e6-11e7-9f0d-e3298dbaf64b.png)

**Comment by rhukster** [comment]
Yah, would be a nice feature.

**Comment by rhukster** [comment]
Available in 1.3.0-RC
