### ISSUE TITLE
Admin View --> Editing Pages --> Tooltip is on wrong places

### ISSUE THREAD

**Issue by bees4ever** [getgrav/grav-plugin-admin#1011]
Dear Grav Team,

I noticed a bug, while editing a page, that the tooltip which wants to guide me where I made a missconfiguration is popping up on the left upper corner of my browser window:

<img width="663" alt="bildschirmfoto 2017-03-07 um 16 07 36" src="https://cloud.githubusercontent.com/assets/21102167/23662773/e5007b12-0350-11e7-9170-ef5e63ce6b57.png">

So I could not see right were I have to fill in the missing information.

I clicked on "Pages"  --> "Advanced" 

<img width="828" alt="bildschirmfoto 2017-03-07 um 16 13 28" src="https://cloud.githubusercontent.com/assets/21102167/23662974/7feef1da-0351-11e7-84c4-de3808548cf0.png">

And switched the template:

<img width="504" alt="bildschirmfoto 2017-03-07 um 16 16 46" src="https://cloud.githubusercontent.com/assets/21102167/23662989/895ff6ce-0351-11e7-83e0-23ed1a5f9a20.png">

_Thank you_

**Comment by w00fz** [comment]
Hey there,
the tooltip you are showing in the screenshot is native of Firefox and it shows when a field is required but not filled.
However, there is no required field in the Pages so I'm not able to recreate this issue.

Could you please tell us step-by-step how to recreate the issue?

Thanks.

**Comment by bees4ever** [comment]
Hi,
Thanks for your fast relply!
But I am sorry, I can't find the issue again. :) You can close the issue! 

If I ever will find it again I will inform you!

Thanks
