### ISSUE TITLE
Add media box not showing in page edit

### ISSUE THREAD

**Issue by risoul** [getgrav/grav-plugin-admin#1013]
I installed the Twenty Skeleton
Grav v1.1.17 - Admin v1.2.14

When editing pages, media box is not showing and I got the message "NOTE: You cannot add media files until you save the page. Just click 'Save' on top" even after saving.

**Comment by rhukster** [comment]
This logic has been modified for the next release.  The media should show as long as the folder exists.  This will require an update to Grav v1.1.18
