### ISSUE TITLE
Add custom field to edit page form

### ISSUE THREAD

**Issue by GittiHab** [getgrav/grav-plugin-admin#1014]
Hello,

I might have missed it somewhere. I am trying to create a plugin which requires adding a custom field to the edit page (the page you are on, when you edit pages). A short glimpse in the code (both PHP and Twig-Template) doesn't make it look that intuitive. Is there a simple way how this can be done?

If this is not possible I would like to propose a hook/event where plugins can register own tabs and fields for the edit page inside the PHP-classes and the template should already support them so that multiple Plugins can register new custom fields easily without influencing other plugins.

**Comment by paulhibbitts** [comment]
@GittiHab Yes, this is possible and is described here: https://learn.getgrav.org/forms/blueprints/example-page-blueprint#in-a-plugin

My Hypothesis plugin also does this, and you can see it's code at https://github.com/hibbitts-design/grav-plugin-hypothesis/blob/master/hypothesis.php

Hope the above helps.

**Comment by GittiHab** [comment]
@paulhibbitts Great, thanks! That's exactly what I was looking for.
