### ISSUE TITLE
Base theme templates not shown when extending theme

### ISSUE THREAD

**Issue by akoebbe** [getgrav/grav-plugin-admin#102]
If I create a theme with antimatter as the base theme. I do not see the uncustomized antimatter templates when creating and editing pages. I only see the templates I've customized.

**Comment by rhukster** [comment]
Still some work needed to properly support inherited themes.

**Comment by rhukster** [comment]
I'm not able to replicate this.. it seems to be working fine:

![2015-09-03-21-qkznd](https://cloud.githubusercontent.com/assets/1084697/9676238/dbfc11ca-5285-11e5-8983-9c617f77562c.png)

**Comment by rhukster** [comment]
![2015-09-03-21-fqhj2](https://cloud.githubusercontent.com/assets/1084697/9676257/2d200200-5286-11e5-9b16-69982b7c8fe6.png)

Here's my folder structure.

**Comment by rhukster** [comment]
Actually now i've pasted this i do see some missing (formdata, modular, snipcart), so something is going on.  I'll dig into it.

**Comment by rhukster** [comment]
Not sure if you are up to testing this or not, but this fixes for me:

https://github.com/getgrav/grav/commit/8fdac33219a88568c0e3000a99cecbaca28a510a

**Comment by akoebbe** [comment]
I'll try to check it out this weekend. Thasks!

**Comment by akoebbe** [comment]
Cherry picked it in and it solves the problem of the page listing. But I'm seeing that the blueprints are inheriting...

<img width="862" alt="edit_blog" src="https://cloud.githubusercontent.com/assets/1044465/9699620/4afe75f2-53af-11e5-9532-af6a0066e1c9.png">

Is this an admn issue?

**Comment by rhukster** [comment]
didn't notice that, but yah, looks like an issue still.

**Comment by rhukster** [comment]
Ok just tested again, and works fine.  I think you have not fully cherry picked all that is required.  Perhaps just wait for the next release (next week).

Reopen if its still an issue.
