### ISSUE TITLE
Hide some templates in Admin Panel

### ISSUE THREAD

**Issue by tilb** [getgrav/grav-plugin-admin#1020]
Is there a way to hide certain templates in the Admin Panel? When the user wants to add a new page, she needs to pick a template. There are quite some templates she never needs to pick, so I was wondering if I could improve the UX by hiding these. Is this possible?

original forumpost [here](https://getgrav.org/forum#!/general:hide-some-templates-in-admi)

**Comment by david-szabo97** [comment]
Hi there,

I have this done on my local version. I will make it into a PR and I'll create a plugin for it.
I have added two new events: 'onPageTypes' and 'onModularPageTypes', the types are passed as reference so you can do whatever you want with it, thus filtering in this case.

@rhukster Any idea for the event names or they will be fine?

**Comment by butchewing** [comment]
I was wondering about this very thing. The Gantry plugin adds a few templates that I love, but sometimes want to hide. I was thinking about creating the same template name in my /custom directory. Then, we could add a special tag (not sure what) to tell the Admin panel to not display it in the dropdown.

**Comment by jimblue** [comment]
This probably have something to do with this two options in admin:

![screen shot 2018-03-22 at 16 31 45](https://user-images.githubusercontent.com/10623367/37780215-958efa8a-2dee-11e8-980b-9924185798bd.png)

Sadly I can't make this options work. (I've try with page **folder_name/title/slug/template**)

**Comment by david-szabo97** [comment]
Hi @jimblue 

Can you tell me what would you like to achieve?
Describe your situation so I can help you  :) 

Cheers,
David

**Comment by jimblue** [comment]
Hi @david-szabo97 

I'm trying to hide some pages from admin page list.

Thanks :)

**Comment by david-szabo97** [comment]
@jimblue 

You misunderstood the functionality of my PR.
This configuration hides page templates, not pages from the page list.

![image](https://user-images.githubusercontent.com/2256104/37831484-f632e1e6-2ea5-11e8-8ba7-78057e5b93c3.png)

**Comment by Al-Demon** [comment]
Hi! is this feature in any place?... I want something like that to facilitate my users.

**Comment by jimblue** [comment]
hum ok @david-szabo97 ! thanks

**Comment by david-szabo97** [comment]
@Al-Demon 
Hi!
Which feature do you mean? Hiding page templates feature is available in Grav.
See https://github.com/getgrav/grav-plugin-admin/pull/1105

**Comment by Al-Demon** [comment]
HI! yes, I see is available but... I can't know how its works... Where
I have to put the code:
I tried in system and I can't find in the visual version plugin admin
either... Sorry maybe I'm lost
hide_page_types:  - taxonomy  - error
hide_modular_page_types:  - modular/front

**Comment by david-szabo97** [comment]
@Al-Demon 
You just need to open the Admin's plugin configuration. You will find it at the end.
See this comment: https://github.com/getgrav/grav-plugin-admin/issues/1020#issuecomment-375349973

**Comment by Al-Demon** [comment]
thanks a lot... now I found it... In admin/plugins/admin panel ...

**Comment by david-szabo97** [comment]
@rhukster 

Can we close this issue?
It's implemented via #1105

**Comment by nerikh** [comment]
The admin-panel settings that allow to hide templates only works for the modal related to the main "Add Page" button of the admin-panel.  However, the page templates are still visible in the "Advanced" tab "Page Template" field.  Was this considered and deliberately omitted from the hide function?

**Comment by bobbwal** [comment]
This doesn't seem to work for me. It doesn't do anything, unless I'm misunderstanding.

**Comment by carlamiapeer** [comment]
My theme extends Quark theme. No trouble hiding page templates, but hiding modular page templates created by Quark doesn't seem to work. 
Any help is much appreciated!
