### ISSUE TITLE
Error when trying to create modular

### ISSUE THREAD

**Issue by akoebbe** [getgrav/grav-plugin-admin#103]
When I try to create a modular section to a modular page i'm getting the following error...

```rename(/src/grav/user/pages/01.home,/src/grav/user/pages/01.home/01.home): Invalid argument```

Here's a quick screencap

![add-modular](https://cloud.githubusercontent.com/assets/1044465/9484791/765d37e2-4b76-11e5-81ec-d08b012a128f.gif)

Am I doing something wrong?

**Comment by rhukster** [comment]
Is this with an overriden/parent theme?

**Comment by akoebbe** [comment]
Yes. I'm using antimatter as the base theme.

**Comment by rhukster** [comment]
Ok again, this is probably related to the fact that the admin doesn't have support for this yet.  We've not tested it at all.

**Comment by akoebbe** [comment]
Understood. It would appear I'm in very uncharted territory. Do you want me to keep reporting bugs on subtheme admin issues, or just wait for it to get tested?

**Comment by flaviocopes** [comment]
@akoebbe I cannot recreate the problem. Can you zip up your user folder, put it on dropbox (or similar) and send me the link via Gitter PM? (faster way to recreate the issue)

**Comment by dawidxt** [comment]
@akoebbe what app did You use to create this animate gif ? 
it will be very helpful in the future.

**Comment by akoebbe** [comment]
@flaviocopes I'll get you the zip file shortly.

@dawidxt I used LICEcap, http://www.cockos.com/licecap/. It's very basic, but very handy.

**Comment by dawidxt** [comment]
thank You, and You're right, it will be very handy :)

**Comment by flaviocopes** [comment]
@akoebbe I cannot recreate the problem, even with your `user` folder! Strange! What's your setup (e.g. Windows vs Mac, which LAMP stack?)

**Comment by akoebbe** [comment]
@flaviocopes  Hmm... I'm doing a Ubunutu vagrant box on a Mac. Nginx, PHP-FPM and NFS'd the code from metal to vm. Don't waste your time on this. It must be an environment issue. I'll figure it out.

**Comment by rhukster** [comment]
My other fix for #102 resolves this one for me also.

**Comment by akoebbe** [comment]
Cool. I'll check this out as well.

**Comment by akoebbe** [comment]
Not sure if this is related to the blueprint inheritance or something else, but now I don't have any modules  templates to choose from in my overridden theme, even with the parent modular template files copied in to the overridden theme.

**Comment by rhukster** [comment]
In my testing yesterday i had all the overridden modular templates, but i'll test this again too.

**Comment by rhukster** [comment]
tested again, and it's fine on my side.  Should be sorted when you test with the proper release next week. 

Please reopen if this continues to be an issue after that.  Thanks!
