### ISSUE TITLE
Overlap between tabs and language/expert controls

### ISSUE THREAD

**Issue by jmorel** [getgrav/grav-plugin-admin#1032]
When editing a page, if there are too many tabs (or if tabs content is too long) there's an overlap of the tabs themselves by the language and expert/normal controls.

<img width="968" alt="screen shot 2017-03-19 at 14 36 54" src="https://cloud.githubusercontent.com/assets/1270900/24081311/a77a4484-0cb1-11e7-9b32-bbad265e132f.png">

**Comment by rhukster** [comment]
This is solved in 1.3.0.  You can check out the RC by setting your GPM level to "Testing" in system config and checking for updates.
