### ISSUE TITLE
Tabs Style issue [1.3.0-rc.3]

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav-plugin-admin#1036]
Great feature with flex. In theme blueprint i found style issue when tab label on 2 lines

![capture d ecran 2017-03-23 a 15 33 25](https://cloud.githubusercontent.com/assets/3842190/24252648/5658db8a-0fde-11e7-89ac-2d7979f30964.png)

i think it's a css rule
````
.form-tabs .tabs-nav a {
height: 3.5em;
}
````

`height: inherit;` looks good

![capture d ecran 2017-03-23 a 15 40 55](https://cloud.githubusercontent.com/assets/3842190/24252957/435ad2b2-0fdf-11e7-91d3-c228f3c15f45.png)

**Comment by rhukster** [comment]
I have a better solution:

<img width="1118" alt="2017-03-23 at 12 32 pm" src="https://cloud.githubusercontent.com/assets/1084697/24264085/db8bb68e-0fc4-11e7-9e72-672746b42a77.png">

BTW, try this in our config:

```
    tabs:
      type: tabs
      active: 1
      class: subtle
```

The `subtle` class should improve things visually for you :)

<img width="1128" alt="2017-03-23 at 12 35 pm" src="https://cloud.githubusercontent.com/assets/1084697/24264171/29ce6ecc-0fc5-11e7-9586-802d22b05d6f.png">

**Comment by dimitrilongo** [comment]
thank you
