### ISSUE TITLE
Title of page when creating a new tab using config blueprints

### ISSUE THREAD

**Issue by ramono** [getgrav/grav-plugin-admin#1039]
After following this tutorial: https://learn.getgrav.org/cookbook/admin-recipes

I successfully managed to create a new tab in the configuration section with a working form.

The problem is the page title (*Configuration - Name of tab*), as Grav is looking for `PLUGIN_ADMIN.NAME_OF_TAB` to show in the top title, and the tab was created by the user (which is most always going to be the case), Grav can't find the value of this new tab to show the translated name in the top title so it literally shows `PLUGIN_ADMIN.NAME_OF_TAB` instead.

I am able to create the entry in my own language file in `/user/languages/en.yaml` but then I have to copy all values of the original language file of the admin plugin as Grav takes it as a full translation.

Is there a way to use the same custom blueprint file to define the title of the page? Or to get the page title from the name of the file (as it does with the tab name)?

Thanks

**Comment by rhukster** [comment]
i'll dig into this when I get back from vaca.

**Comment by david-szabo97** [comment]
@ramono 
The language files aren't merged as far as I know. So whenever you use `PLUGIN_ADMIN` in your own language file it overrides the whole object.

Maybe you should try to avoid using the `PLUGIN_ADMIN` namespace, that's the plugin's namespace anyway. What I usually do is use a project prefix, for example, if your website is `MyWebsite` then just use `MW_PLUGIN_ADMIN.NAME_OF_TAB`

**Comment by flaviocopes** [comment]
The language merging is a known issue at the moment. I fixed the issue you mentioned, now the file name is used all over if no translation is found.
