### ISSUE TITLE
Save button not working in admin/pages/* in IE 11

### ISSUE THREAD

**Issue by kevinkub** [getgrav/grav-plugin-admin#104]
Hi there,

it is not possible to save a page in Internet Explorer 11. It works on any other page and the button is the only one not working (as far as I can tell). It does not Trigger an error in the developer console and nothing happens (besides the :active effect), so I guess the JavaScript Event might simply not be able to be attached to the button. However I was not able to find the bug on my own, but I can offer you to have a look at it, if you tell me which files are involved in the saving process.

**Comment by flaviocopes** [comment]
Currently untested in IE, only Chrome/Firefox. Added the `browser` label for further testing.

**Comment by 810** [comment]
Still not working. any progress on this?
