### ISSUE TITLE
RTL Markdown page content

### ISSUE THREAD

**Issue by rimagahwa** [getgrav/grav-plugin-admin#1040]
I'm writing a blog page via the admin panel. I have been using Grav for over a month now.
yesterday I wanted to write a new blog , after I finished writing I noticed that I'm having several issues in how the page looks in my browser vs the preview in the admin panel.

**Admin Panel Preview**
![screenshot-rimaworks is-great net-2017-03-25-20-27-38](https://cloud.githubusercontent.com/assets/13506835/24324561/ae33e5f4-1199-11e7-81b7-66bf279d2be2.png)

**Actual page on Chrome**
![screenshot-rimaworks is-great net-2017-03-25-20-28-06](https://cloud.githubusercontent.com/assets/13506835/24324557/a8721d5c-1199-11e7-9588-2d2560cafd50.png)

so I'm having problems with the styling. I'm using Arabic language which is written right to left. I had to change the Grav template snipps by adding `<dir="auto">` so it would display starting from the right in Arabic , and starting from the left if Arabic.

I tried adding a `<div>` to force the `<dir="ltr">` just to see if there's a problem with the attribute but nothing changed. 

I should also mention that writing Arabic content in the panel is difficult ,I assume it is cause by the Markdown.

here's the page http://rimaworks.is-great.net/ar/blog/android-multilang

Any suggestions ?

**Comment by rhukster** [comment]
think the editor needs to be initialized with `rtlLayout: true`

https://github.com/codemirror/CodeMirror/pull/2244/files

**Comment by rhukster** [comment]
@w00fz what's the best way to configure options for codemirror?

**Comment by rimagahwa** [comment]
I tried code mirror  with this example  https://github.com/codemirror/CodeMirror/pull/2244/files , still did not fix the problem. even the element's tag shows up in my page.

![screenshot-rimaworks is-great net-2017-05-20-11-47-37](https://cloud.githubusercontent.com/assets/13506835/26274412/303f7052-3d52-11e7-9d03-d15d0b77d3a1.png)

please do update me on how I can fix this, otherwise I have to change to another CMS even though I really like Grav. this just looks ugly.

**Comment by jadoux** [comment]
I like when you guys close it without the simplest of explanation, we in the Middle East are craving for a flatfile CMS that works for our RTL requirements, and obviously it's not on your radar
