### ISSUE TITLE
Editing Twig Templates in admin?

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#1041]
When you're on the road and want to change theme design and need to login, sometimes ssh/ftp ports are blocked by firewalls and the only way is admin. (if I don't wanna use external tools like eXtplorer)
Any plans for accessing/editing twip templates in admin? Or is this going to be a feature of admin pro?

**Comment by rhukster** [comment]
It's our thought that  editing twig templates is something that a 'developer' does, during the development phase of the site.  The admin is first and foremost intended for end-users to maintain and create content after the site is created.

So it's not really a priority to have these kinds of development features in the admin plugin.
