### ISSUE TITLE
can't copy page Copying page failed on error: Undefined index: folder

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav-plugin-admin#1042]
Since update i can't copy page anymore

`Copying page failed on error: Undefined index: folder`

from console 3 errors:
`Uncaught ReferenceError: Invalid left-hand side in assignment`
`Uncaught TypeError: Cannot read property 'notifications' of undefined`
`Uncaught Error: No URL provided.`

Grav v1.2.0-rc.3 - Admin v1.3.0-rc.3

**Comment by rhukster** [comment]
Hmm thought this was working. I'll look at it later today.
