### ISSUE TITLE
Direct Install Bug Windows

### ISSUE THREAD

**Issue by DamirPecnik** [getgrav/grav-plugin-admin#1043]
I am trying to install grav-theme-rt_versla_v1.1.2.zip using a direct install but its not working for me i get a error message!

Windows 10, Chrome!

Whoops\Exception\ErrorException thrown with message "Undefined index: file_path"

Stacktrace:
#17 Whoops\Exception\ErrorException in F:\Projects\webthemer\user\plugins\admin\classes\admincontroller.php:2170
#16 Whoops\Run:handleError in F:\Projects\webthemer\user\plugins\admin\classes\admincontroller.php:2170
#15 Grav\Plugin\Admin\AdminController:taskDirectInstall in F:\Projects\webthemer\user\plugins\admin\classes\adminbasecontroller.php:102
#14 call_user_func in F:\Projects\webthemer\user\plugins\admin\classes\adminbasecontroller.php:102
#13 Grav\Plugin\Admin\AdminBaseController:execute in F:\Projects\webthemer\user\plugins\admin\admin.php:328
#12 Grav\Plugin\AdminPlugin:initializeController in F:\Projects\webthemer\user\plugins\admin\admin.php:375
#11 Grav\Plugin\AdminPlugin:onPagesInitialized in F:\Projects\webthemer\vendor\symfony\event-dispatcher\EventDispatcher.php:184
#10 call_user_func in F:\Projects\webthemer\vendor\symfony\event-dispatcher\EventDispatcher.php:184
#9 Symfony\Component\EventDispatcher\EventDispatcher:doDispatch in F:\Projects\webthemer\vendor\symfony\event-dispatcher\EventDispatcher.php:46
#8 Symfony\Component\EventDispatcher\EventDispatcher:dispatch in F:\Projects\webthemer\vendor\rockettheme\toolbox\Event\src\EventDispatcher.php:23
#7 RocketTheme\Toolbox\Event\EventDispatcher:dispatch in F:\Projects\webthemer\system\src\Grav\Common\Grav.php:277
#6 Grav\Common\Grav:fireEvent in F:\Projects\webthemer\system\src\Grav\Common\Processors\PagesProcessor.php:24
#5 Grav\Common\Processors\PagesProcessor:process in F:\Projects\webthemer\system\src\Grav\Common\Grav.php:126
#4 Grav\Common\Grav:Grav\Common\{closure} in F:\Projects\webthemer\system\src\Grav\Common\Grav.php:368
#3 Grav\Common\Grav:Grav\Common\{closure} in F:\Projects\webthemer\system\src\Grav\Common\Grav.php:344
#2 call_user_func_array in F:\Projects\webthemer\system\src\Grav\Common\Grav.php:344
#1 Grav\Common\Grav:__call in F:\Projects\webthemer\system\src\Grav\Common\Grav.php:127
#0 Grav\Common\Grav:process in F:\Projects\webthemer\index.php:52

![2017-03-31 21 15 16](https://cloud.githubusercontent.com/assets/10489911/24565819/28aa7a84-1657-11e7-94ec-5a53765b7fec.jpg)

**Comment by rhukster** [comment]
Ok turns out this is not a windows-only bug, but a legit one that snuck through after adding the URL type.
