### ISSUE TITLE
Direct Install / Choose File, File Types

### ISSUE THREAD

**Issue by DamirPecnik** [getgrav/grav-plugin-admin#1044]
When i would like to upload the file in Windows usually or all the time i will get the All Files selected in drop-down in Windows Popup Window but here i get custom file so i know plenty of people will say that they don't see zip files and will not notice this.

![2017-03-31 21 12 00](https://cloud.githubusercontent.com/assets/10489911/24565952/c0fbbd66-1657-11e7-840c-11685a817ec4.jpg)

**Comment by w00fz** [comment]
Thing is we don't really allow All files, only .zip files. The field is set to purposely only allow to select .zip files. That's the only supported format to install a package.

**Comment by rhukster** [comment]
Yah tested on Mac/Chrome and it only shows ZIP files which is intended.
