### ISSUE TITLE
admin.settings permission option doesn't appear to change anything

### ISSUE THREAD

**Issue by RyanMPierson** [getgrav/grav-plugin-admin#1045]
I'm having a hard time finding what the `admin.settings` permission setting changes. The settings it would appear to change are covered by `admin.configuration_site` and `admin.plugins`. Does this setting still affect anything?

**Comment by flaviocopes** [comment]
I think it's still around in some bits but does not really affect anything, going to check.

**Comment by mahagr** [comment]
Confirmed that it doesn't do anything. It has been removed from Admin 1.10.
