### ISSUE TITLE
Links to README files are sometimes broken

### ISSUE THREAD

**Issue by jpfleury** [getgrav/grav-plugin-admin#105]
In plugin info displayed on the page `/admin/plugins`, there's a link *Readme*. It seems that *grav-plugin-admin* takes for granted that a plugin always has a branch *develop*:

    {% set readme_link = plugin.readme ?: plugin.homepage ~ '/blob/develop/README.md' %}

[[see file plugin-data.html.twig](https://github.com/getgrav/grav-plugin-admin/blob/4295a5daba7c15a085f96e55fa6733f006f4dae0/themes/grav/templates/partials/plugin-data.html.twig#L56)]

However, it's not always the case, so README links are sometimes broken. See for example *grav-plugin-blog* or *grav-plugin-embed*.

**Comment by jpfleury** [comment]
See also README files for themes:

    {% set readme_link = theme.readme ?: theme.homepage ~ '/blob/develop/README.md' %}

[[see file themes-details.html.twig](https://github.com/getgrav/grav-plugin-admin/blob/4295a5daba7c15a085f96e55fa6733f006f4dae0/themes/grav/templates/partials/themes-details.html.twig#L89)]

**Comment by rhukster** [comment]
Yes, we recommend using 'GitFlow' in our developer documentation.  With GitFlow, you always use the develop branch as your main developmental branch, as such 'usually' your README.md should be in that branch.  The only alternative is for us to support a README.md URL in the blueprints.  We can do that in a future release.

**Comment by w00fz** [comment]
Plugins have been falling back to `master` for a few releases now and with this fix themes are too.
You should note that what you reported being bad links are simply fallbacks from the admin plugin.

The developer of either the theme or the plugin can change the link to the `readme` however likes by adding the `readme: <link>` entry in the blueprint.

Example:
```
name: Antimatter
version: 1.8.0
readme: https://getgrav.org
```

What admin does is to just fallback to the branch (which is master now), in case a readme is not provided.
