### ISSUE TITLE
Mobile Fail on Latest update

### ISSUE THREAD

**Issue by quenquen** [getgrav/grav-plugin-admin#1057]
After the latest plugin update, **Mobile view on pages** is buggy! Normal / Expert buttons stays on top of the Tabs on most of the screen resolutions, and when clicked one of the tabs, nothing happens!

Tried managing pages on different devices (BlackBrry Passport, Z10, Moto G, Galazy Tab, etc).

**Comment by rhukster** [comment]
I'll be looking at this tomorrow
