### ISSUE TITLE
Question regarding the page request order

### ISSUE THREAD

**Issue by geschke** [getgrav/grav-plugin-admin#1058]
Hello!

I tried to understand the login process of the admin plugin. I think, I'm some steps further than some hours ago, but I didn't understand the following code (line 395 and below in admin.php, "Replace page service with admin"):

```php
     // If the page cannot be found in other plugins, try looking in admin plugin itself.
            if (file_exists(__DIR__ . "/pages/admin/{$self->template}.md")) {
                $page->init(new \SplFileInfo(__DIR__ . "/pages/admin/{$self->template}.md"));
                $page->slug(basename($self->template));
                return $page;
            }


            // Allows pages added by plugins in admin
            $plugins = $this->grav['plugins'];
            $locator = $this->grav['locator'];
            foreach ($plugins as $plugin) {
                $path = $locator->findResource("user://plugins/{$plugin->name}/admin/pages/{$self->template}.md");
                if ($path) {
                    $page->init(new \SplFileInfo($path));
                    $page->slug(basename($self->template));
                    return $page;
                }
            }
```

At first there is a lookup of the page (i.e. template file) in the admin plugin. This works, so if e.g. a file named "dashboard.md" is found, it will be displayed. 

In the second part there is a loop which checks all plugins for a matching template file. This works, too, but only if the previous snippet didn't find a matching file in the admin plugin itself. 

So I'm a little bit confused, maybe because of the comments. The first says "_If the page cannot be found in other plugins, try looking in admin plugin itself._". But the lookup in the admin plugin was placed before the lookup in other plugins. So it's not possible to replace an existing page file by a template file in another plugin. Maybe this should not be done, but then the comment is confusing. 
If the plugins are searched before the admin path lookup, then it works as described, so maybe the order of the above snippets has to be switched?

Kind regards and Thanks in advance,
   Ralf

**Comment by flaviocopes** [comment]
Yes, by checking the history seems it was switched previously in https://github.com/getgrav/grav-plugin-admin/commit/76bd584832c70c892b9e67a2824aab1e22a12366 but the comment was not updated. 

I think the reason was to avoid plugins to overwrite Admin's pages, but I'm not sure as there is no issue linked. Updated the comments.
