### ISSUE TITLE
Modular Content moving to root when saving since v1.3.2

### ISSUE THREAD

**Issue by carlu93** [getgrav/grav-plugin-admin#1059]
Since the newest update, there's a serious problem with the admin plugin.
as soon as i save some modular page/content the module gets moved outside the parent to the ROOT of the grav pages folder. Unfortunately i have no screenshot, because i already moved back to v1.3.1, but this happened to every module i saved.

**Comment by flaviocopes** [comment]
I'm not able to replicate. Which browser are you using? Can you also try clearing the browser cache?

**Comment by axel-rank** [comment]
I cannot replicate too. Using latest Grav + Admin + Cleared Browser Cache (Firefox 52.0.2).

**Comment by paulhibbitts** [comment]
I also updated to latest version and running with MAMP + Chrome I was able to save modular pages a-ok.

**Comment by OleVik** [comment]
Could this be because the type of template changed inadvertently? One thing I noticed with Grav + Admin, from source, last night was that the field-select for template would jump back to Default from Modular on occasion, but I haven't tested whether it occurs beyond my out-of-date Chrome.

**Comment by carlu93** [comment]
The Problem @OleVik mentioned happened to me too! I'm using Chrome V58

**Comment by rhukster** [comment]
Hmm.. i did 'fix' an issue yesterday to return `default` from the task: getChildType (which is called every time you change parent) if the value was not set. 

Could this be the issue?

**Comment by rhukster** [comment]
Ok, I think this might need a little JS work to fix. It's resetting to `default` now every time you change parent (or move).  I guess it was expecting an error before.

**Comment by rhukster** [comment]
Ok, looked into it a little more.  Seems this getChildType always returns `default` even if it's not set.  My fix was to address an issue when the method was called with a bad rawroute (ie when typing in the parents select field).  

But seems this is a fundamental new thing that changes behavior since Grav 1.1.17.  We'll look into how best to sort it.

**Comment by carlu93** [comment]
Great! Thanks. I'll test the fix as soon as it's out.

**Comment by flaviocopes** [comment]
Ok I can replicate the change of the page template. Looking into it. 
But I still cannot replicate the original issue reported, which is - moving the page folder to root after saving.
