### ISSUE TITLE
Adding new page in Edge

### ISSUE THREAD

**Issue by vorticalbox** [getgrav/grav-plugin-admin#1061]
The button to create a new page does not work I'm edge. Tested on windows phone and desktop.

**Comment by rhukster** [comment]
Works fine for me...

![2017-04-20 at 5 27 pm](https://cloud.githubusercontent.com/assets/1084697/25256539/a769bfa0-25ee-11e7-8a0e-446fbd153369.jpg)

**Comment by vorticalbox** [comment]
When you you click continue it doesn't move on to the next page.

**Comment by rhukster** [comment]
For me continue works just fine in Edge on Windows 10.

**Comment by rhukster** [comment]
Of course it might be related to some other fixes I've made.. This is with latest develop branch.  Please try that.

**Comment by vorticalbox** [comment]
will do next chance I get. ty.

**Comment by TomOne** [comment]
I can reproduce this problem on Edge v14, tested with the current stable admin plugin as well as with the develop branch.

The continue button in the add page menu only works when *Parent page* is set to `/ (root)`, but fails on other parent pages.

**Comment by TomOne** [comment]
I could narrow down the problem: as soon as there’s a `required` select created with the selectize library in a form, Edge doesn’t let the form submit.

I’ve created an issue at selectize/selectize.js/issues/1319 for this. Maybe the Selectize library can provide a workaround for this.

**Comment by TomOne** [comment]
I’ve created a pull request at selectize/selectize.js/pull/1320 to fix this and tested it with the Grav admin plugin: works perfectly with MS Edge.

I hope this gets merged and a new version with the fix gets released, so the Grav admin plugin can use it and this issue can be closed.
