### ISSUE TITLE
Weird editor and markdown field appearance

### ISSUE THREAD

**Issue by Sommerregen** [getgrav/grav-plugin-admin#1063]
When using the `editor` or `markdown` field in custom blueprints, both fields, have serious styling issues and are almost impossible to use. See

![view](https://cloud.githubusercontent.com/assets/9073307/24974679/4825b8ea-1fc3-11e7-8338-9149d261f1a1.png)

The blueprint to get the above result reads:

![blueprint](https://cloud.githubusercontent.com/assets/9073307/24974783/b5a13bba-1fc3-11e7-8994-6955f8c53a3e.png)

Tested with **Grav v1.2.0** and **Grav Admin Plugin v1.3.1** on *Firefox 50.1.0*.

**Comment by rhukster** [comment]
Could you please test with latest?

**Comment by Sommerregen** [comment]
Done (**Grav v1.2.2** with **Admin Panel v1.3.3**)... same issue.

**Comment by flaviocopes** [comment]
I see them 100% fine, unless the editor has both codemirror.lineNumbers && codemirror.styleActiveLine enabled, and in this case it's just a small sidebar UI issue, not how you see it:

![schermata 2017-04-14 alle 14 11 28](https://cloud.githubusercontent.com/assets/11783388/25042952/68f03cda-211c-11e7-85f6-fce8e20053b8.png)

Can you make sure no other plugin is interfering on the CSS, or maybe there is a JS issue?

**Comment by Sommerregen** [comment]
Can confirm. Must be on my end. Thanks for the additional fix with the gutters. Now it works 👍
