### ISSUE TITLE
Admin Charts Constantly Updating

### ISSUE THREAD

**Issue by chryton** [getgrav/grav-plugin-admin#1064]
It appears that the interval is not being cleared upon completion of the cart update and it is causing divs to be constantly updated: http://rocketgoatin.space/jetsam/N51TyVJ2ja/

**Comment by rhukster** [comment]
@flaviocopes you mind looking at this one?

**Comment by flaviocopes** [comment]
Checking

**Comment by flaviocopes** [comment]
I don't know how we missed this performance issue. I tracked the problem down to https://github.com/getgrav/grav-plugin-admin/commit/8bd7f8d6667642154bf430fb2b4dcbdfef8a6096, which is fixing this issue https://github.com/getgrav/grav-plugin-admin/issues/753.

So there is this loop:

```js

// Sidebar auto-refresh
global.setInterval(() => {
    contentScrollbar.update();
    sidebar.scroller.update();
    Object.keys(Dashboard.Chart.Instances).forEach((chart) => {
        Dashboard.Chart.Instances[chart].chart.update();
    });
}, 150);
```

The charts refresh every 150ms. This is a comparison of doing the interval every 150ms, then every 2s, then every 10s:

![schermata 2017-04-14 alle 15 41 08](https://cloud.githubusercontent.com/assets/11783388/25044798/d4150124-2128-11e7-8c5a-bbca78e5fa55.png)

Quite a deal. I am unsure how to fix this problem while avoiding the original problem to come up again. We can start by relaxing the graph refresh interval to 2s, so the graphs are refreshed upon various UI changes, but not as much frequently, but we need to figure out a better way to detect those changes.

**Comment by flaviocopes** [comment]
Actually, I'm testing removing the JS altogether and I don't think we need those chart refreshes any more. Seems some recent CSS change is already fixing the issue mentioned in https://github.com/getgrav/grav-plugin-admin/issues/753. I'm going to remove that JS in a PR so you can test as well.

**Comment by flaviocopes** [comment]
I have pushed a fix in develop, which removes the JS refresh of the graphs. Is anyone able to replicate the issues listed in https://github.com/getgrav/grav-plugin-admin/issues/753? I could not with Chrome / Firefox
