### ISSUE TITLE
Better slug transliteration

### ISSUE THREAD

**Issue by jpfleury** [getgrav/grav-plugin-admin#107]
When creating a new page, the folder name is automatically generated (unless we set it manually) from the page title:

    folder = $(this).val().toLowerCase().replace(/\s/g, '-').replace(/[^a-z0-9_\-]/g, '');

[[see file `pages-all.js`](https://github.com/getgrav/grav-plugin-admin/blob/cb0e8e98c2917a1c85dd127efbdfd9362244505e/themes/grav/js/pages-all.js#L157)]

then the folder name is used (by default) for the slug ([see function `slug`](https://github.com/getgrav/grav/blob/19a4480b966c418526d6b51d2a09b912e4bf9c6a/system/src/Grav/Common/Page/Page.php#L1165)).

The regex is very basic and the result looks sometimes pretty bad. Example with a French title: *L'été étoilé* => *lt-toil*. Expected result is *l-ete-etoile*. The [jQuery plugin Slugify](http://madflow.github.io/jquery-slugify/) gives this result.

**Comment by dimayakovlev** [comment]
Yes, transliteration needs improvement. Cyrillic characters from page title must be transliterated.

**Comment by rhukster** [comment]
Ok added. Thanks.
