### ISSUE TITLE
Admin route resets on update

### ISSUE THREAD

**Issue by rimagahwa** [getgrav/grav-plugin-admin#1070]
I have noticed that everytime the Admin plugin updates the default page route  ( configurable ), is reset . Which is annoying because I need to change it every time I do an update.
the route is configured in this file  user/plugins/admin/admin.yaml

Could you please fix this?
Thank you

**Comment by axel-rank** [comment]
you have to copy and edit the admin.yaml in user/**config**/plugins
default plugin folder gets overridden on every update.

**Comment by rimagahwa** [comment]
Yeah I know . I'm saying it is annoying..

**Comment by axel-rank** [comment]
If you want custom plugin settings you have to edit your plugin.yaml file in user/config/plugins
And you only have to **do it once**. **This file doesn't get overriden on updates.**

**Comment by rimagahwa** [comment]
Really? That's what I needed . Thank You

**Comment by axel-rank** [comment]
And if your using admin panel you can go to plugins--> admin panel and change the setting there.
