### ISSUE TITLE
Editing pages save to /ROOT

### ISSUE THREAD

**Issue by motionbug** [getgrav/grav-plugin-admin#1072]
Admin plugin v1.3.3 editing pages will save to root and not to folder... have to manually edit each page and also select parent folder from ROOT to have the page save it right place.

**Comment by motionbug** [comment]
<img width="530" alt="screenshot 2017-04-18 10 31 06" src="https://cloud.githubusercontent.com/assets/36737/25121489/28e5f4f0-2422-11e7-9453-24ac14c695fb.png">
Fresh edit... ROOT is selected

**Comment by redrohX** [comment]
I just noticed the same issue happening on my Grav install with v1.3.3. When creating a new page and selecting the proper Parent, after saving the page the parent resets to `/(Root)`. 
What I expect to happen is that the Parent is the directory I selected from the list.

**Comment by redrohX** [comment]
I think this might be a bit bigger than I initially thought. I've had to roll back to admin 1.3.1, where it seems the issue doesn't occur. For some pages it doesn't show the proper parent directory. So when you edit one of these pages and save, it automatically adds to page to the root directory. Which makes handling content with small team a disaster right now.

I've uninstalled 1.3.3 and installed 1.3.1. For 1.3.3 it said `/(Root)` incorrectly, while at 1.3.1 it correctly shows the proper parent directory. Whatever happens, it seems this was introduced at 1.3.2 (I also tried this version before 1.3.1).

**Comment by rhukster** [comment]
Can you test with the latest develop branch from github? Pretty sure this is fixed just not released yet.

**Comment by redrohX** [comment]
@rhukster I've tested with the develop branch and it seems to be fixed indeed. The parent page/directory doesn't reset after saving.
 One thing might

**Comment by redrohX** [comment]
@rhukster I tested the develop branch and it seems to be fixed indeed. The parent page doesn't reset after saving. 

One thing I did notice is that after adding a new page with a preferred parent, adding another page doesn't automatically select the same parent page anymore (it does keep the same template selected). It used to be the case that the same parent was automatically selected.

![Adding a second page](http://i.imgur.com/DUakeFS.png)

**Comment by rhukster** [comment]
@flaviocopes you mind looking at this one, as i think you added that feature?

**Comment by flaviocopes** [comment]
The select had this in the blueprint (https://github.com/getgrav/grav-plugin-admin/blob/e1250e74178b8c429a4699b1fe5e9ccbd23d59ec/blueprints/admin/pages/new.yaml#L35)

```
data-default@: '\Grav\Plugin\Admin\Admin::getLastPageRoute'		
```

We can move this into https://github.com/getgrav/grav-plugin-admin/blob/7abf4b146155bd75b39cf68459d25f234d4af405/themes/grav/templates/forms/fields/parents/parents.html.twig#L4 perhaps?

**Comment by rhukster** [comment]
ah! that was it.. let me try

**Comment by rhukster** [comment]
Ok should be sorted now with https://github.com/getgrav/grav-plugin-admin/commit/da5f91c33ca8779841404d32ca4f7ff654bb3af7

**Comment by motionbug** [comment]
Just want to say thanks and you ROCK! Cheers
