### ISSUE TITLE
Editor Fullscreen --> no scrollbar anymore!

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#1077]
Latest Grav (1.2.3) Latest Admin (1.4.1):
Going to fullscreen view --> there's no scrollbar. Can't see/edit full article/content anymore!
Firefox 53.0

**Comment by OleVik** [comment]
Are there any errors in the Console of your DevTools? (Press F12 or ctrl+shift+i).

**Comment by axel-rank** [comment]
admin 1.3.3:
![admin_1 3 3](https://cloud.githubusercontent.com/assets/12480617/25227094/96fe7038-25c7-11e7-9c95-31f291cc9b5b.png)

admin 1.4.1:
![admin_1 4 1](https://cloud.githubusercontent.com/assets/12480617/25227117/abdd303e-25c7-11e7-88c8-cd42a1a1fcbb.png)

**Comment by OleVik** [comment]
Specifically, what (if any) errors are thrown into the "Console/Konsole"-tab of the inspector after a refresh?

**Comment by axel-rank** [comment]
If you refresh when you're in fullscreen view the editor goes back to normal view.
I can see no errors in Konsole Tab.
Another issue maybe related to th scrollbar: add function doesn't show options in fullscreen
normal view:
![editor1](https://cloud.githubusercontent.com/assets/12480617/25232566/1b4acbc0-25dc-11e7-9811-e3875680cfeb.png)

fullscreen:
![editor2](https://cloud.githubusercontent.com/assets/12480617/25232577/2581d656-25dc-11e7-84c8-e93ecb949957.png)

**Comment by OleVik** [comment]
Are there any errors if you: Open the page, open developer tools, refresh, then open fullscreen? If necessary, subsequently close fullscreen then view the Console/Konsole and note any errors there.

**Comment by axel-rank** [comment]
Yes, here it is:

![message](https://cloud.githubusercontent.com/assets/12480617/25234828/8dd3cffa-25e3-11e7-930c-004a9ba4d854.png)

**Comment by OleVik** [comment]
Could you copy that as text or translate it? My German is not up to scratch, but it has something to do with Mozilla's `ScrollLinkedEffects` ([more details](http://stackoverflow.com/a/37100516/603387)).

**Comment by axel-rank** [comment]
![editor](https://cloud.githubusercontent.com/assets/12480617/25238623/330f4f9e-25ee-11e7-8ada-d500dc43dc81.png)

**Comment by rhukster** [comment]
Looks like a z-index issue for that dropdown. Should be fixable.

**Comment by rhukster** [comment]
Fixed the dropdown and the scrollbar.

![2017-04-20 at 5 12 pm](https://cloud.githubusercontent.com/assets/1084697/25256230/86c54d70-25ec-11e7-8930-73a488023843.jpg)
