### ISSUE TITLE
Parent dropdown always shows wrong folder

### ISSUE THREAD

**Issue by jmavra** [getgrav/grav-plugin-admin#1078]
I am trying to edit pages on the root but every time i save it keeps reseting the Parent dropdown to a folder I have. If I click save again it moves the page!

![image](https://cloud.githubusercontent.com/assets/16673957/25257043/23349496-262d-11e7-96c8-612f9ec30d1a.png)

**Comment by rhukster** [comment]
Do you have other pages with the same `services` slug?

**Comment by jmavra** [comment]
nope as you can see in the above image the only other page I have is contact

**Comment by rhukster** [comment]
I'm unable to replicate this. Are you all updated with latest grav and admin?

If so can you zip up your user folder and send me a link to download t?

**Comment by CoDanny** [comment]
This happens to me too. Pages with parent /root set the parent to themselves.

**Comment by rhukster** [comment]
As I said can I please get a zip of the user directory where this happens as it works fine for me.

**Comment by CoDanny** [comment]
@rhukster how can I send this to you in private?

**Comment by rhukster** [comment]
Sure email to me rhuk at getgrav.org

**Comment by rhukster** [comment]
Ok you should have a temp fix. I have a better fix coming in a mo.

**Comment by rhukster** [comment]
ok this last fix will be in next release.

**Comment by jmavra** [comment]
Thanks, this fix also fixed the issue for me after I applied it.
