### ISSUE TITLE
Issue with links to frontend for pages

### ISSUE THREAD

**Issue by dimayakovlev** [getgrav/grav-plugin-admin#108]
Admin 0.4.2.
![Bad anchor](https://cloud.githubusercontent.com/assets/8279974/9516496/a2a16864-4cb1-11e5-9a2e-f73d94a25b2b.png)
For example for root page Photos link anchor is `//photos`.

**Comment by flaviocopes** [comment]
@dimayakovlev is this with multilanguage, or without it?

**Comment by dimayakovlev** [comment]
@flaviocopes It is without multilanguage. I have not tried multilanguage.

**Comment by rhukster** [comment]
Fixed in develop.  Will need a grav update also as I added a new `|ltrim` and |rtrim` twig filter to make this easier.
