### ISSUE TITLE
`show_modular` not working any more on the `pages` field

### ISSUE THREAD

**Issue by flaviocopes** [getgrav/grav-plugin-admin#1080]
This commit removed it, in https://github.com/getgrav/grav-plugin-admin/commit/c48b664cfbc131bab0ffa6328f0f6f897cb17f41

Was this intended, or simply forgotten in the new implementation?

**Comment by rhukster** [comment]
Ya missed it.  Should still be an option.

**Comment by rhukster** [comment]
Fixed with latest Grav and Admin develop branches

**Comment by rhukster** [comment]
BTW, `show_all` overrides this and shows every page.. so you need `show_all=false` and `show_modular=false` to actually hide modular pages.
