### ISSUE TITLE
regex - new admin fields?

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#1082]
![admin](https://cloud.githubusercontent.com/assets/12480617/25286232/586ee662-26bd-11e7-9a9e-ce8645eac58c.png)

Regex? Username, Password? For what?

**Comment by rhukster** [comment]
For controlling the format of accepted username/password.  The default for password is 8+ chars, with at least 1 upper, 1 digit, etc.

**Comment by rhukster** [comment]
BTW, hovering over the label provides some help :)

**Comment by axel-rank** [comment]
yes, hovered help text isn't translated yet, though my english is not too bad I didn't understand the sense of this setting (especially Regex) at once... ;-)
But now I do.
