### ISSUE TITLE
Error message "Failed: Cannot set page parent to self" on home page

### ISSUE THREAD

**Issue by jonnykrueger** [getgrav/grav-plugin-admin#1084]
Hi there,

I'm using Grav v1.2.3 with Admin v1.4.1. I reinstalled Grav completely together with the admin plugin, inorder to eliminate the possibility that it broke during update...

When I want to save the home page, having blueprint form with the option to select pages, I receive the mentioned error messsage. Reason: The home page sets itself as parent automatically, which fails.

Here is the process:

1. I change the parent of "home" manually to / (root). I save afterwards.
2. The validation check, whether home's parent is set to itself or not, is surpassed, but the change to / (root) isn't saved.
3. If I recheck the parent setting, it's back to "--> home", causing this error message.

More information:
- I use a modular page as home page called "homepage.md" / "homepage.html.twig" / "homepage.yaml".

Do you have any suggestion? Is it a known bug?

Best Regards
Jonny from Germany :)

**Comment by carlu93** [comment]
Download the latest ZIP https://github.com/getgrav/grav-plugin-admin/archive/develop.zip and overwrite the plugin. After that log out and back in again.
That fixed it in my case! :)

**Comment by jmavra** [comment]
This is a dupe of https://github.com/getgrav/grav-plugin-admin/issues/1078 I think

**Comment by jonnykrueger** [comment]
Yes, you're right. Thanks for the info! :)
