### ISSUE TITLE
Broken automatic Markdown code for responsive images

### ISSUE THREAD

**Issue by jpfleury** [getgrav/grav-plugin-admin#109]
Say we add an image named `image@3x.jpg` by uploading it in the Page Media area. When the image is uploaded, we put the cursor over it and click *Insert*. The Markdown code inserted in the textarea is the following:

    ![](image@3x.jpg)

Save the page and display it.

**Result:** the image doesn't appear. The HTML code for the image is:

    <p><img src="image@3x.jpg" alt="" /></p>

We must go again in the admin section to edit the page, delete the Markdown code for this image and click again on *Insert*. This time the Markdown code added is:

    ![](image.jpg)

and the image will be displayed.

**Comment by rhukster** [comment]
Yah I think responsive images will require special logic that is currently not there.

**Comment by flaviocopes** [comment]
I could not find a way to changing the displayed filename during upload (without changing the Dropzone.js code). For now after upload the media file is still listed as  `image@3x.jpg`, for example, if it's uploaded like this. But when inserted in the page, it's inserted as `image.jpg`
