### ISSUE TITLE
Changes detected?

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#1091]
Latest Admin/Grav Develop:
Going to configuration -> system and site tab:
If I click any other tab:

![message](https://cloud.githubusercontent.com/assets/12480617/25420277/a5c46750-2a57-11e7-9a4a-4ffc8eecd0e7.png)

But I did not do or change anything.

**Comment by rhukster** [comment]
Yes this is an issue that came about after i merged PR https://github.com/getgrav/grav-plugin-admin/pull/1083

i've now reverted this until @Sommerregen can sort.
