### ISSUE TITLE
TypeError when saving a top-level page without route field.

### ISSUE THREAD

**Issue by tomzmtl** [getgrav/grav-plugin-admin#1094]
Grav `1.2.4`
Admin Panel `1.4.2`

Saving a page with a custom blueprint.

**[Update]**: This is exclusively happening on pages at the top of the page hierarchy.
Pages that are children of other pages are saving successfully.

```
Argument 1 passed to Grav\Common\Page\Page::move() must be an instance of
Grav\Common\Page\Page, null given, called in
[...]/user/plugins/admin/classes/admincontroller.php on line 498
```

**Comment by tomzmtl** [comment]
Turns out I previously removed the `route` field from the blueprint because it was buggy a couple versions ago.
Now the original issue seems to have been fixed, and putting back that field fixes the issue.

There is still this bug whenever there is no `route` field in a top-level page.
Whether this is by design or not I don't know (I would think it's not).
Keeping that issue open so you guys can acknowledge it. Feel free to close whenever.

**Comment by rhukster** [comment]
Route is required for every page. it's part of the core `default.html.twig` blueprint. There are somethings in that you just can't remove as Grav is expecting them to be valid on-save. 

Glad you got it sorted.
