### ISSUE TITLE
Feature Request - Ability in Configuration to set default values for New Page wizard.

### ISSUE THREAD

**Issue by Duke3D** [getgrav/grav-plugin-admin#1097]
Depending on the active template and intention of the website, similar to the way Visible can infer the correct setting for blog pages v. numbered pages, it would be helpful if an Admin user setting up a site could set as a default the page template and page parent that a new page should be created under as the 90% use case.  
e.g. For a blog site, give the admin the ability to set the default page template to be "item" or "blog" (whatever applies) and the default Parent as "/ (blog) Blog."   While Grav as distributed doesn't want to be opinionated, the site designer installing a template and initial content does want to be opinionated in that page creation defaults should be adapted to minimize the chance that the occasional user will make errors when adding content according to how that site is organized.

**Comment by rhukster** [comment]
We have the ability for a parent to set 'child templates' this way you can set `blog` page to set it's children to `item` for example:

![2017-04-28 at 12 50 pm](https://cloud.githubusercontent.com/assets/1084697/25542818/5a199daa-2c11-11e7-8098-fe342560689b.jpg)

I think this is a pretty elegant solution.

**Comment by paulhibbitts** [comment]
I've also added a note about this (awesome!) recent feature here: https://github.com/getgrav/grav-learn/pull/423/files

**Comment by olivierdalang** [comment]
@rhukster this solves the problem only partially, as the user still has to find the right parent page in a maze of dozens of pages/posts/technical pages...

I think it would be nice if the admin plugin would allow to create simple buttons like "add blog post", "add regular page", etc., that would preconfigure the template AND the parent. Choosing any custom combination between template and parent should anyway be considered as "advanced".

**Comment by flaviocopes** [comment]
A recent PR made by @david-szabo97 allows to add such buttons: https://github.com/getgrav/grav-plugin-admin/pull/1104

Available in the Admin plugin testing releases.
