### ISSUE TITLE
Numeric password

### ISSUE THREAD

**Issue by symac** [getgrav/grav-plugin-admin#11]
Setting a password containing only digits in the admin.yaml file won't allow login.

**Comment by flaviocopes** [comment]
I cannot recreate, what was the content of the password field you entered in admin.yaml? I tried with `password: '1111'`, it works

**Comment by symac** [comment]
@flaviocopes I am not a yaml expert and had just replaced password with my password so it was looking like:
```password: 111```
I assume it is not the correct way of setting a string containing only digits in yaml syntax, but if there is any way to go around that would be nice to newcomers (as according to a discussion gitter I am not the only one who encountered this issue)

**Comment by flaviocopes** [comment]
You're right, setting it as a number does not work. `password: 111` does not work, `password: '111'` works.

**Comment by rhukster** [comment]
BTW, there are some built in rules for 'changing' password via the admin.  Currently this is hardcoded, but we can maybe have it configurable later.  1 upper, 1 digit + at least 8 chars (i think!)
