### ISSUE TITLE
Wrong thumbnail dimensions in the Page Media area after uploading an image

### ISSUE THREAD

**Issue by jpfleury** [getgrav/grav-plugin-admin#110]
After uploading an image in the Page Media area, the thumbnail displayed has wrong dimensions:

![before](https://cloud.githubusercontent.com/assets/687082/9518526/503d2fc6-4c85-11e5-9681-c4024af17c3e.png)

We must refresh the page to have a thumbnail correctly displayed:

![after](https://cloud.githubusercontent.com/assets/687082/9518525/503a579c-4c85-11e5-9b86-2de09764fb0d.png)

**Comment by rhukster** [comment]
The initial thumbnail is generated by javascript and is therefore pretty rough.  On subsequent reload the thumbnail is generated with PHP and is therefore accurate.   I'm not sure we can do much with the js generated thumb, but looks like flavio is going to look at it.
