### ISSUE TITLE
Saving in wrong locale when multiple tabs opened

### ISSUE THREAD

**Issue by akeif** [getgrav/grav-plugin-admin#1100]
**How to reproduce**

* Open a page in two different tabs.
* Change the locale in a tab.
* Return to the other tab.
* Save.

**Bug diagnostic**

In the following case, we opened two tabs in 'EN' then switched one to 'FR'. Then saved.
<pre>
Psy Shell v0.8.3 (PHP 7.1.4-1+deb.sury.org~xenial+1 — cli-server) by Justin Hileman
>>> $obj->language()
=> "en"
>>> $_POST
=> [
     "task" => "save",
     "data" => [
       "frontmatter" => "title: Home",
       "content" => "Francais",
       "ordering" => "1",
       "folder" => "home",
       "route" => "/",
       "name" => "default",
       "order" => "",
       "blueprint" => "",
     ],
     "admin-nonce" => "5b72290e3598f3d87aa9327ebba28943",
   ]
>>> 
</pre>

**Comment by akeif** [comment]
@dctremblay and I are currently investigating.

@rhukster Do you have any tips to guide us on this one?

**Comment by dctremblay** [comment]
I made a simple 1 line bugfix, hope this could help. PR : #1101

**Comment by rhukster** [comment]
@akeif can you confirm if @dctremblay PR fixes your issue???

**Comment by akeif** [comment]
I'll take a look when I have a sec.

**Comment by akeif** [comment]
@rhukster I just tested the fix and it's working fine!

Good job @dctremblay :)

**Comment by dctremblay** [comment]
@rhukster @akeif awww yeahhh !

**Comment by dctremblay** [comment]
@akeif I changed slightly the PR, feel free to re-test it.

**Comment by rhukster** [comment]
PR merged.
