### ISSUE TITLE
Again: overlay of Add-Page button in full-size editor 

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#1103]
After install of latest admin develop:
overlay of Add-Page button in full-size editor #1077 is back!
Firefox 53.0

**Comment by rhukster** [comment]
Can you test with latest develop version? I fixed some z-index issues.

**Comment by axel-rank** [comment]
Did install 40 minutes ago...it's latest i guess?

**Comment by rhukster** [comment]
yah, that's latest.. weird i just tested some fixes yesterday!

**Comment by rhukster** [comment]
UGG.. it is back.. must of been that fullscreen PR i accepted.. i'll look again.

**Comment by rhukster** [comment]
No, was my z-index fix for mobile nav... i'll find a comprimise

**Comment by rhukster** [comment]
Ok, try develop again, should be sorted now

**Comment by axel-rank** [comment]
still there, develop already updated?

**Comment by rhukster** [comment]
Yah was  a merge error on push.  now fixed and pushed..

**Comment by axel-rank** [comment]
Ok, working again.
