### ISSUE TITLE
Direct Install by uploading Error

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#1107]
Downloaded Grav 1.2.4 zip
In admin -> Tools -> Direct Install option 1: Install a zip package by uploading it
Install fails:

![message](https://cloud.githubusercontent.com/assets/12480617/25772358/532b1a4c-3269-11e7-8838-680b8fd1337d.png)

If I choose option 2: Install a zip package from a remote location
Working

**Comment by flaviocopes** [comment]
What's your PHP `upload_max_filesize` value? Lower than the file you're trying to upload? Look in Configuration -> Info

**Comment by axel-rank** [comment]
Ok, it's only 2M. Grav is 4,1MB
