### ISSUE TITLE
Gantry 5 - 403 Error while saving

### ISSUE THREAD

**Issue by flyceo** [getgrav/grav-plugin-admin#1108]
When I try to save settings in Gantry 5 everytime I get an error message: "403 Forbidden"
All permissions are set correctly. The used webserver is lighttpd.

I already found solutions for other webservers  ([Gantry #1453](https://github.com/gantry/gantry5/issues/1748), [Gantry #1748](https://github.com/gantry/gantry5/issues/1748)) but not lighttpd. By the way the configuration file for lighttpd shipped with grav doesn't work correctly. The security settings prevent grav updates and image uploads with the 403 error. Commenting out these lines solve the update and image problem, but not the issue with Gantry 5. 

![image](https://cloud.githubusercontent.com/assets/28514022/25784992/c635f0e4-3376-11e7-8ddd-8a3df360fffe.png)

**Comment by flaviocopes** [comment]
The issue is in the Lighttpd config. See https://github.com/getgrav/grav-plugin-admin/issues/893 and in particular this comment https://github.com/getgrav/grav-plugin-admin/issues/893#issuecomment-286404311
