### ISSUE TITLE
Language toggle button in admin top bar visible also in fullscreen mode

### ISSUE THREAD

**Issue by Torn3** [getgrav/grav-plugin-admin#1110]
Reporting what I think is a little bug. 
Language toggle button in admin top bar visible also in text-edit-fullscreen mode. In Chrome and IE
Does not disturb me, I just wanted to let you know.

Look at the SV-language button in enclosed scrennshots. 
![sv_bug_z_01](https://cloud.githubusercontent.com/assets/18717358/25804602/6765f040-33f4-11e7-823a-50da16614cc8.JPG)
![sv_bug_z_02](https://cloud.githubusercontent.com/assets/18717358/25804603/676da786-33f4-11e7-98e8-f88e166430bf.JPG)

**Comment by eidecker** [comment]
Latest Firefox (53) shows the same behaviour.
