### ISSUE TITLE
Padding-left in the editor might be too large

### ISSUE THREAD

**Issue by paulmassen** [getgrav/grav-plugin-admin#1111]
![image](https://cloud.githubusercontent.com/assets/12809352/25861459/182d36cc-34e5-11e7-96be-1ba894983431.png)

On the editor, the 15px left padding can let the user think there is a space on the left. 
This can be confusing when writing indentation-sensitive text such as yaml.

Also, wouldn't it be useful for the editor to expand to fit the frontmatter content when switching to Expert mode? I think codemirror provide this option.

Hope it helps, 

Paul

**Comment by rhukster** [comment]
I think this was there purely for cosmetic purposes, but I agree it could be an issue.

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-admin/commit/6903d42cc67be550db28db26df21fc9932d96a31

Fixed.
