### ISSUE TITLE
Media Routing problem using PHP Built-in Web Server

### ISSUE THREAD

**Issue by ricardo118** [getgrav/grav-plugin-admin#1119]
I've tested this issue across 3 different windows machines, using the latest php 7. 

When launching a localhost via this command:
`C:\php\php.exe -S localhost:80 -t C:\projects\core C:\projects\core\system\router.php`

Everything works as expected, except when viewing media already uploaded in Admin.js. See picture below:
![](http://i.imgur.com/5DZ4nxB.png)

With the console showing the following error:
`Failed to load resource: net::ERR_NAME_NOT_RESOLVED`

This is due to the path of the image having an extra slash. By manually removing it, the issue is solved
`<img data-dz-thumbnail="" alt="263.jpg" src="\/images/a/4/7/b/3/a47b3570310dd103daf2e3682493d5d389fd289d-263.jpeg">`

**Comment by rhukster** [comment]
I shall take a look as i've been working on media thumbnails and stuff this week.

**Comment by OleVik** [comment]
I can replicate this with PHP 7.0.7 on a fresh Grav v1.2.3 + Admin v1.4.1. As Ricardo pointed out, the problem is the backwards-slash at the beginning of the src-attribute, seemingly escaping the following forward-slash. To quote myself from Slack:

> Regardless of whether CropZoom is used ([line 1524](https://github.com/getgrav/grav-plugin-admin/blob/173429d892f63958abe81ce6195712a7f57f82e1/classes/admincontroller.php#L1524)), it returns as `src="\/images/...."`. Its easy to trim, of course, but I expect it deeper down has to do with Windows-paths, which of course by default use backwards-slashes. So it could easily have to do with using DIRECTORY_SEPARATOR unnecessarily, as PHP for at least a few major versions have supported forwards-slashes.

Thus, I suspect it is a remainder from path-interpretation of the system as a whole, which somewhere has not trimmed the final slash of the installation-path, or concatenates a `DIRECTORY_SEPARATOR` unnecessarily.

**Comment by rhukster** [comment]
Can you test if your XHR request for `listMedia` call has the extra slash?

**Comment by OleVik** [comment]
It is emanating from the Media-iteration, within the method rather than any encoding happening later. As a quick and dirty test, doing this:

```
$url = $medium->cropZoom(200, 150)->url();
$url = ltrim($url, '\\');
$media_list[$name] = ['url' => $url, 'size' => $medium->get('size')];
```
resolves it from within the loop.

**Comment by rhukster** [comment]
This should be solved via Ole's PR.
