### ISSUE TITLE
Single quotes around title may be confusing

### ISSUE THREAD

**Issue by jpfleury** [getgrav/grav-plugin-admin#112]
If the title already contains an apostrophe, the single quoting is kind of confusing:

![before](https://cloud.githubusercontent.com/assets/687082/9518836/16aa3986-4c88-11e5-8e6f-b8ab929fe300.png)

A possibility would be to apply a style to the title instead of quoting it. Mock-up:

![after](https://cloud.githubusercontent.com/assets/687082/9518849/2d0d92ae-4c88-11e5-942e-7cd4d70ea16b.png)

**Comment by rhukster** [comment]
A good solution, i'll make this minor change.

**Comment by rhukster** [comment]
Fixed in develop
