### ISSUE TITLE
Can't use <a>-block in markdown Extra

### ISSUE THREAD

**Issue by Dollique** [getgrav/grav-plugin-admin#1126]
As it seems that nobody has a solution for my question on the forum about how to correctly create an < a >-block with Markdown Extra, I post it here as an issue.

This is the [forum post](https://getgrav.org/forum#!/general:markdown-extra-html-a-b).

**Short description of the problem:**
No matter how I try to implement <a> as a block element when Markdown Extra is set to on, I always get very strange results with <p>-tags wrapping parts of my html or the < a >-tag appearing twice etc.

**The example**
(Removed because I can't show the code including Markdown in github as it will be automatically changed....)

**Comment by rhukster** [comment]
Replied in the forum. This is really a limitation in Parsedown's "markdown extra" support. I try to avoid it as it usually causes more problems than it solves.
