### ISSUE TITLE
[First time launching Gravy] Register admin form does not give clues about what's wrong with wrong email

### ISSUE THREAD

**Issue by BoQsc** [getgrav/grav-plugin-admin#1129]
I did type "admin@localhost" and registration form didn't give any clues about what's wrong with it.
A thing I thought about: maybe the password isn't matching before I arrive at a conclusion that email was incorrectly typed.

**Comment by flaviocopes** [comment]
Thanks for reporting, there is HTML frontend validation in the form, but `admin@localhost` passes that. It does not pass the server-side validation, but the error message does not appear. Looking to improve that.
