### ISSUE TITLE
File uploads don't convert spaces

### ISSUE THREAD

**Issue by andregoldstein** [getgrav/grav-plugin-admin#113]
On uploading media to a page, would be useful if filenames with spaces etc get resolved so that images work correctly in the front-end.

**Comment by flaviocopes** [comment]
Image names are not urlencoded when uploaded, they're stored with their original name in the filesystem.

When clicking 'Insert' from the Page Media, images are correctly inserted in the page url encoded (e.g. image named `760x 2.jpg` is inserted as `![](760x%202.jpg)`
