### ISSUE TITLE
Error 404 on :getUpdates, :getnewsfeed, and :getNotifications upon deployment

### ISSUE THREAD

**Issue by lguariento** [getgrav/grav-plugin-admin#1133]
Hello, I have a problem: I just deployed my grav website. Locally everything works fine. The front-end works fine too remotely. The admin works fine, except I get a curious error 404 when updating/checking for new feeds/etc. The inspector shows that `/admin/ajax.json/task:getnewsfeed`, `/admin/update.json/task:getUpdates`, and `/admin/notifications.json/task:getNotifications` are not fetched. Any idea? I’ve cleared the cache, substituted all the relevant folders with ‘fresh’ ones, and the error still persists.

**Comment by lguariento** [comment]
Hello, problem solved - it was related to the name of the Grav's subfolder, which apparently contained 'forbidden' characters.

**Comment by flaviocopes** [comment]
@lguariento how was it named?

**Comment by lguariento** [comment]
7LzC&11jy7VM0f8IzfEo - it was meant to be as difficult a path as possible, as you can see (temporary, of course!).

**Comment by rhukster** [comment]
& was undoubtedly the problem.

**Comment by lguariento** [comment]
Yep, indeed, I figured that out :)
