### ISSUE TITLE
Centering markdown with/(out) links. [test](test.com) 

### ISSUE THREAD

**Issue by Cordoha** [getgrav/grav-plugin-admin#1134]
I've yet to find out a way to center content with a URL. I've had to use html, unsure if the tags are deprecated or not, but it worked.

 ``` I've tried using <center>[tags](test.example)</center>, but the results do not link up the text. ```
``` I've used <p style="text-align: center;"><a href="test.example">Tags</a></p> as the markup, just unsure if it is deprecated at this point.```

**Comment by rhukster** [comment]
There is no built in support in markdown for this. My suggestion is to use the shortcode-core plugin which had a center shortcode.
