### ISSUE TITLE
[Admin CSS] Small problem in dashboard media queries 

### ISSUE THREAD

**Issue by paulmassen** [getgrav/grav-plugin-admin#1138]
Very small problem, but when screen width is between 765 and 875, the buttons stacks as below, with one outside the box.

![image](https://user-images.githubusercontent.com/12809352/27230709-74b0cd4e-52b0-11e7-988f-67f3875364fa.png)

**Comment by OleVik** [comment]
Is this only on the French translation, or the default English one as well?

**Comment by paulmassen** [comment]
you are right, it's in french only indeed! closing this
