### ISSUE TITLE
In reverse proxy configurations with https, login attempts to redirect to http

### ISSUE THREAD

**Issue by jaygorrell** [getgrav/grav-plugin-admin#1139]
Hey there, we have a reverse proxy configuration where Grav itself is running over http port 8080 behind a Kong proxy. Kong handles serving over https and the ssl termination. 

With this setup, login itself works fine but it is followed up with a redirect to /admin over http, which fails to load in this setup. If I attempt to go to https again, I am already logged in so I know this is a redirect server-side after getting through.

My initial reaction is that the login.html.twig file should use `uri.url(false)` instead of `uri.url` so exclude the hostname that Grav thinks is correct. It's either that or Grav should factor reverse proxy configuration into `uri.url` values. I'm new to Grav so I'm unsure where the correct fix is but modifying the login twig file does seem to fix my issue. If that is acceptable, I can submit the PR.

**Comment by flaviocopes** [comment]
Could this be the same issue as https://github.com/getgrav/grav-plugin-sitemap/issues/46#issuecomment-309077473 ?

**Comment by jaygorrell** [comment]
Only categorically, I believe. In this case, login specifically supports a `redirect` parameter on the login form. I think there are two solutions here:
1. Respect reverse proxy configuration on the back-end when handling relative URLs (or whatever is causing it to drop the current protocol from the URL).
2. Change the form redirect to include the protocol by passing `false` to `uri.url` here: https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/templates/partials/login.html.twig#L19

It's probably worth noting, this problem doesn't occur when you have a custom base url set for Grav.

**Comment by herrbischoff** [comment]
I experience the same issue, using h2o as a reverse SSL proxy in front of Nginx serving Grav. The simplest solution would be

> Change the form redirect to include the protocol by passing false to uri.url here
