### ISSUE TITLE
Filename displayed twice for PDF added in the Page Media area 

### ISSUE THREAD

**Issue by jpfleury** [getgrav/grav-plugin-admin#114]
When we add a PDF file in the Page Media area, it looks OK right after uploading it:

![before-refreshing](https://cloud.githubusercontent.com/assets/687082/9518979/1bca77cc-4c89-11e5-93ae-e7e2a4ac711c.png)

However, as soon as we save the page, refresh it or close the admin and open it again, the filename is displayed twice:

![after-refreshing](https://cloud.githubusercontent.com/assets/687082/9518995/3b19f0b2-4c89-11e5-9933-6b0586a71359.png)

**Comment by jpfleury** [comment]
Actually, the problem occurs with other data media types, like txt.

**Comment by rhukster** [comment]
Another media related issue.  Looks like Flavio is on the ball.

**Comment by flaviocopes** [comment]
Fixed in d82bd9a88d83bfc75cd41f3bba1b393e0e86e3dd
