### ISSUE TITLE
Latest admin develop --> php fatal error Uncought InvalidArgumentException...

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#1141]
Just installed latest admin plugin develop branch:
Error message in terminal:

![error](https://user-images.githubusercontent.com/12480617/27263852-d4239afe-5472-11e7-85fe-94ea2fe70b5c.png)

**Comment by flaviocopes** [comment]
Is the Admin plugin enabled in `user/config/plugins/admin.yaml`?

**Comment by axel-rank** [comment]
Yes, sure.
I installed latest admin-develop on my testsite via admin-plugin.

**Comment by flaviocopes** [comment]
I was able to reproduce it, thanks for reporting!

**Comment by flaviocopes** [comment]
Fixed!
