### ISSUE TITLE
Unable to upload media files

### ISSUE THREAD

**Issue by adrian5** [getgrav/grav-plugin-admin#1142]
I've looked at other reports here, but they all appear to be closed as solved half a year ago.

My situation is that I can upload images to the page (their thumbnail will show with a green checkmark), but they don't appear to get saved into the page's folder.

In Firefox I can see the following error in the console log:

```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data[Learn More]  admin.min.js:5:26549
	value http://mysite/user/plugins/admin/themes/grav/js/admin.min.js:5:26549
	bound value self-hosted:918:17
	Grav</</</n</e.prototype.emit http://mysite/user/plugins/admin/themes/grav/js/vendor.min.js:15:13403
	Grav</</</t</t.prototype._finished http://mysite/user/plugins/admin/themes/grav/js/vendor.min.js:16:9428
	Grav</</</t</t.prototype.uploadFiles/w.onload</< http://mysite/user/plugins/admin/themes/grav/js/vendor.min.js:16:8146
```

Though I'm not sure if that's the show stopper. I get no UI notifications or Grav error logs, and the Admin Panel seems to be under the impression that the file exists. If I "delete" the file, I get `File not found: file.jpg`.

The folder has 775 permissions and is owned by the same process that runs PHP, so pretty ideal permission-wise. Hope you guys can help me out.

**Comment by flaviocopes** [comment]
Can you check the browser dev tools Network panel, and check what's the response of the uploading AJAX request?

Should be this, when successful: 

![screen shot 2017-06-19 at 13 54 44](https://user-images.githubusercontent.com/11783388/27283937-e2f4eea0-54f6-11e7-96f2-cdf1b5cf853c.png)

![screen shot 2017-06-19 at 13 54 28](https://user-images.githubusercontent.com/11783388/27283942-e824ffd2-54f6-11e7-8f57-42a18e93c0da.png)

**Comment by adrian5** [comment]
Yes, that was informative. On my local machine, I had restricted PHP access for Grav via `php_admin_value[open_basedir] = /srv/www/mysite.com` and the AJAX response reported that Grav failed to access _/tmp_. Duh!

Appending `:/tmp` to the `open_basedir` path solved the problem!
