### ISSUE TITLE
Call to undefined method Grav\Plugin\AdminPlugin::shouldLoadAdditionalFilesInBackground

### ISSUE THREAD

**Issue by benface** [getgrav/grav-plugin-admin#1145]
After updating to v1.5.0-rc.3, I am getting this on every page of the admin panel:

<img width="325" alt="screen shot 2017-06-23 at 11 07 54 am" src="https://user-images.githubusercontent.com/1059139/27488220-417289dc-5804-11e7-9456-e85a9fc3a683.png">

```
Fatal error:  Uncaught Error: Call to undefined method Grav\Plugin\AdminPlugin::shouldLoadAdditionalFilesInBackground
```

Removing this block of code fixes it: https://github.com/getgrav/grav-plugin-admin/blob/develop/admin.php#L528

**Comment by OleVik** [comment]
A quick search reveals that the problem is where the method is called from: Its not in Grav\Plugin\AdminPlugin, but in [Grav\Plugin\Admin\Admin](https://github.com/getgrav/grav-plugin-admin/blob/9060e02c558dfa5b8001705f0b23194a2baba99b/classes/admin.php#L1521-L1528).

**Comment by rhukster** [comment]
Please try the fix in develop:

```
            if ($this->admin->shouldLoadAdditionalFilesInBackground()) {
                $this->admin->loadAdditionalFilesInBackground();
            }
```
