### ISSUE TITLE
Custom Add Page button not working with TwigExtensions

### ISSUE THREAD

**Issue by sojimaxi** [getgrav/grav-plugin-admin#1149]
@david-szabo97 @rhukster @flaviocopes 
Related #1104 , #1066 
This feature is working great but I seem to have noticed something important. The bar buttons or dropdown don't get created if a TwigExtension is added to your plugin or theme. I don't know if it just me or anyone else has experience this issue.
I tested it both for plugin and theme and the both produced the same result.
Here is a sample plugin to illustrate my code

```php
namespace Grav\Plugin;
class SojiPlugin extends Plugin
{
....
    public static function getSubscribedEvents()
    {
        return [
            'onPluginsInitialized' => [['setup', 100000],['onPluginsInitialized', 0]],    
        ];
    }
    /**
     * Initialize configuration.
     */
    public function onPluginsInitialized()
    {
     
        $this->enable([
            'onTwigExtensions'           => ['onTwigExtensions', 0],

        ]);
    }

....
    /**
     * Add the Widgets Twig Extensions
     */
    public function onTwigExtensions()
    {
        require_once(__DIR__ . '/twig/SojiTwigExtension.php');
        /* @var Twig $twig */
        $twig = $this->grav['twig'];
        $twig->twig->addExtension(new \SojiTwigExtension());
    }
....
}
```
I created a simple Twig Extension
````php
class SojiTwigExtension extends Twig_Extension {
    public function getName()
    {
        return 'Soji Text'; // TODO: Change the autogenerated stub
    }

}
````
And if i comment out the `addExtension` part everything works and the buttons are created but otherwise the buttons are not created but the their system is functional.
I have attached the sample plugin [soji.zip](https://github.com/getgrav/grav-plugin-admin/files/1111929/soji.zip) to this issue

**Comment by flaviocopes** [comment]
I don't have issues with that plugin. The dropdown is correctly rendered.
I don't see how that could interfere, as Twig extensions have nothing to do with that functionality. Maybe something else is going on. You mention Bar buttons, you mean you don't see any button on the top bar?

**Comment by sojimaxi** [comment]
No I see the default button i just can't see the ones I created. I am currently doing other test to find out if the problem lies elsewhere, will update my result soon.

**Comment by sojimaxi** [comment]
@flaviocopes I have seen why you can't recreate the problem but i was able to figure it out. The stable Admin Plugin is 1.4.2 and the current bundled grav-admin is 1.5.0-rc when i use the 1.5.0-rc version the problem goes away but when i use the 1.4.2 version the problem persist. The problem lies within the core Admin Plugin can't see why though.
