### ISSUE TITLE
Data media type added from the Page Media area is converted into invalid HTML code

### ISSUE THREAD

**Issue by jpfleury** [getgrav/grav-plugin-admin#115]
For example, if we add a PDF file in the Page Media area, then put the cursor over it and click *Insert*, the following Markdown code is added in the textarea:

    ![](Formulaire%20web.pdf)

If we save the page and display it, the resulting HTML code is invalid (p inside a p):

    <p><p style="">Formulaire web.pdf</p></p>

It would be useful if the resulting HTML code was a link:

    <p><a href="/mon-article/Formulaire%20web.pdf">Formulaire web.pdf</a></p>

**Comment by rhukster** [comment]
Somewhat related to #113.

**Comment by flaviocopes** [comment]
I pushed a commit right now that solves this problem. If the media file is an image, it puts it in an image tag. Otherwise (like in the case of a PDF) it's linked.
