### ISSUE TITLE
Multilevel-field leafs

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav-plugin-admin#1150]
Starting with a sample of:

```
styles:
  - background: "#0B110D"
  - background: "#2C4D56"
```

Renders fine:

![image](https://user-images.githubusercontent.com/974717/27704910-6ffff822-5d0c-11e7-982d-9e428558ca3a.png)

But adding a sibling to background in the first item (0), with key `color` and value `red`, and `color` with `blue` for the second item (1) creates a third item (2) with 2->color->blue on saving. Adding top-level items seems to work well, but siblings are created as new top-level items rather than siblings.

Also, a JS-alert tells me "Warning: if you save now, the top elements without children will be removed, because it's invalid YAML" every time I scroll.

**Comment by rhukster** [comment]
I'm having another issue:

![2017-06-29 at 5 17 pm](https://user-images.githubusercontent.com/1084697/27714577-e92f338e-5cee-11e7-9460-188637a1d3a1.jpg)

I have this in `media.yaml`, but i cannot change `filters2` back to `filters`.  On save it reverts back to `filters2`

**Comment by flaviocopes** [comment]
Replicated both

**Comment by flaviocopes** [comment]
@OleVik issue is caused by having an array as a top-level item (first level):

```
content:
    - background: '#0B110D'
    - background: '#2C4D56'
```

Adding a value in the middle fixes things:

```
content:
    test:
        - background: '#0B110D'
        - background: '#2C4D56'
```

This is how the UI for array should render:

![screen shot 2017-06-30 at 17 15 50](https://user-images.githubusercontent.com/11783388/27742199-0979f6c8-5db8-11e7-9569-cf72c7feb28f.png)

The index value (0, 1, 2..) should not show up, but rather it's handled by the field. If you add a sibling to a single item, it creates an array internally. 

Fixing this case.

**Comment by OleVik** [comment]
Testing with:
```
styles:
  test:
    - background: "#0B110D"
      color: red
    - background: "#2C4D56"
```

Renders as:
![image](https://user-images.githubusercontent.com/974717/27765593-f9ce3ea6-5eb5-11e7-933e-964bc490e937.png)

Thus, though styles.test contains two arrays - and are parsed as such - they are indistinguishable in the field. Further, the field does not appear to handle multiple key-value pairs in an array. Adding a `color: blue` alongside the `background: "#2C4D56"` of course adds a new array, there is no way to add it as a sibling. The same occurs when adding a top-level leaf with a pair of children, `background` and `color`. This is the yield:

```
styles:
  test:
    -
      background: '#0B110D'
      color: red
    -
      background: '#2C4D56'
    -
      color: blue
  two:
    -
      background: cyan
    -
      color: green
```

Is it intended that each array is a single key-value pair? If so, this runs contrary to YAML which allows arrays to have multiple such pairs.

Lastly, the aforementioned JS-alert persists when I add a top-level leaf and remove it again, it keeps popping up.

**Comment by flaviocopes** [comment]
> Adding a color: blue alongside the background: "#2C4D56" of course adds a new array, there is no way to add it as a sibling

Right, I think there should be another way to visualize an array item, like how a fieldset works inside a form, with "+" and "-" buttons as well, that contains subfields.

**Comment by OleVik** [comment]
Maybe go for slightly more illustrative buttons? Ie., for child `->`, for sibling `|_>`, and for entire nodes `+` and `-`.

**Comment by paulmassen** [comment]
I did a few try myself and I think a layout like this could be nice, what do you think:
![image](https://user-images.githubusercontent.com/12809352/30060468-c3fa262a-9243-11e7-9b81-8281af5d1a38.png)

I changed the icon for fa-level-down. and I think we could add the plus button on the left, as it adds a field at the same level.
The main change is that I made the key:value on the same rows. If the user clicks on add children, it will hide the value field and displays instead a new nested key value pair.

I think it can help visualize the global structure as it match the resulting yaml.

Let me know what you think.
