### ISSUE TITLE
Page order is wrong when more than hundred child

### ISSUE THREAD

**Issue by headonkeyboard** [getgrav/grav-plugin-admin#1151]
I have a problem on page ordering when I have more than hundred child with numeric prefix :

![capture du 2017-06-30 13-36-24](https://user-images.githubusercontent.com/837567/27733974-215f1fee-5d99-11e7-8d3b-b8058f9cf0a4.png)

**Comment by karfau** [comment]
Good catch!

In case you are familiar with shell or some other tool to rename lots of diretories by pattern, you can add the zero in front of all folders with two digit numbers. As long as you do not resort using the admin panel the numbers will not change.

But of course this doesn't fix the problem in general.

Best Christian

**Comment by headonkeyboard** [comment]
Thank you @karfau for this tips but that's not for me but for my client...

**Comment by flaviocopes** [comment]
This should be fixed in the latest Admin 1.5.0 RC release: 

![screen shot 2017-07-04 at 14 46 19](https://user-images.githubusercontent.com/11783388/27830763-2ed3b202-60c8-11e7-96a0-d2c103c8f49a.png)
