### ISSUE TITLE
Range field in Firefox

### ISSUE THREAD

**Issue by w00fz** [getgrav/grav-plugin-admin#1153]
The rangetouch field doesn't look quite right in Firefox. 
The js module has been updated to latest version with the hope that would solve it but it didn't. Probably just simple styling.

![rangetouch](https://user-images.githubusercontent.com/11734/28043263-f0db55e6-6585-11e7-9836-2c53a98cdf7e.png)

**Comment by rhukster** [comment]
Actually this is a bug in the system blueprint.

**Comment by rhukster** [comment]
Fixed in repo
