### ISSUE TITLE
toggle field of a list is switch to false when new item is added

### ISSUE THREAD

**Issue by tranduyhung** [getgrav/grav-plugin-admin#1154]
I have a blueprint like this

            header.products:
              type: list
              label: Products
              style: vertical
              fields:
                .name:
                  type: text
                  label: Name
                .description:
                  type: editor
                  label: Description
                .featured:
                  type: toggle
                  label:  Feature this product?
                  highlight: 1
                  default: 0
                  options:
                      1: 'Yes'
                      0: 'No'
                  validate:
                      type: bool

I add a new item and set the toggle field to 1, then click "Add Item" at the bottom of the list to create a new item, after that all the toggle fields in the list are switched from 1 to 0.

My Admin plugin's version is 1.4.2. I didn't see this problem before.

**Comment by rhukster** [comment]
Confirmed. @w00fz i know this one was fixed before, but somehow the behavior has been reverted. To test just drop this YAML into the top of `user/themes/antimatter/bluerprints/item.yaml` and then edit a blog item page.

**Comment by w00fz** [comment]
Should be sorted now. I had to revert the original fix. 🤔
