### ISSUE TITLE
TypeError for attached json file

### ISSUE THREAD

**Issue by tomceek** [getgrav/grav-plugin-admin#1156]
Just attached JSON file to the page (via Page media) and got this error:

`Fetch Failed: 
Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
at Function.keys ()
at http://www.xxx/user/plugins/admin/themes/grav/js/admin.min.js?3d05d80838:5:19999
at http://www.xxx/user/plugins/admin/themes/grav/js/admin.min.js?3d05d80838:4:24799
at`

Grav v1.3.0-rc.5/Admin Panel  v1.5.0-rc.4

Other file types woks fine.

Any help?

**Comment by flaviocopes** [comment]
Uhm.. I can't replicate this problem. Can you please go in the network panel of the browser dev tools, and after you upload the file check what is the response for the request?

**Comment by tomceek** [comment]
Upload is working fine. File sits in the folder, it generates thumbnail instantly after upload.
But when I open page for edit (refresh after uploading the file), I got that error mentioned above.

More info from Network panel:
![capture](https://user-images.githubusercontent.com/30144585/28215559-282040b4-68b7-11e7-9aa5-77aab4396442.PNG)

**Comment by tomceek** [comment]
any update on bug fix?

**Comment by rhukster** [comment]
This is because of a missing JSON thumbnail in the Grav core.. Will be fixed in next release.
