### ISSUE TITLE
Mediapicker inside a list field fills all newly created entry

### ISSUE THREAD

**Issue by paulmassen** [getgrav/grav-plugin-admin#1157]
Hi,

Found a small bug when using the new mediapicker field inside a list.
Basically, when mediapicker is used inside a list field, all newly created items have their fields filled. 
Here is a gif that will explain it better:
![mediapicker](https://user-images.githubusercontent.com/12809352/28180362-30b9b488-6805-11e7-8327-53193d9bca64.gif)

**Comment by paulmassen** [comment]
It looks like unique_identifier is the same on all newly created elements of a list

**Comment by rhukster** [comment]
Lists are always problematic for fields due to their dynamic nature. I'm sure @w00fz can work his magic on this one too :)

**Comment by w00fz** [comment]
This is fixed now.

Cheers
