### ISSUE TITLE
You can't unset an existing file field (ex: image) without deleting the actual file on the server

### ISSUE THREAD

**Issue by hdwebpros** [getgrav/grav-plugin-admin#1158]
If you have a file field, let's say a hero image, and you want to change it out, you're forced to delete it. So if that media is on another page, it would be deleted there too.

**Comment by flaviocopes** [comment]
It's kind of problematic determining the perfect default behavior for this field. On one hand, directly removing the file is bad if it's cross-referenced in other pages. On the other hand, you'd not want "dead" files laying around even if removed.

I think the default is ok, as there are other fields that allow to just select an already-existing file (`filepicker` https://learn.getgrav.org/forms/blueprints/fields-available#the-filepicker-field), but worth discussing if there is a better way to do this.

**Comment by hdwebpros** [comment]
I don't recommend having the only option for the file field to be to remove it completely. Deleting a file shouldn't really be in a page editing format, but if it is insisted, perhaps 2 buttons should be there per file. (1 for remove, 1 for delete)

Filepicker doesn't allow the user to add a file, so that wouldn't work. If it had the capability to add a file, then it would be sufficient for this.

Either of those 2 suggested solutions would at least give site admins / users the ability to change files from the GUI.

**Comment by hdwebpros** [comment]
Created PR https://github.com/getgrav/grav-plugin-admin/pull/1366
