### ISSUE TITLE
Video drag-n-drop missing exclamation mark before link.

### ISSUE THREAD

**Issue by laurathomas** [getgrav/grav-plugin-admin#1160]
Hi there,
Not sure if this is occurring just for me, but when I either drag and drop or 'quick add' a video via the plus icon from the hover menu, the autolink is missing a leading exclamation mark. More of an annoyance than anything else, I can easily add one myself and could also look for the culprit locally and fix. But might be an idea to fix for everyone so as not to have this issue all the time.
Has anyone else noticed this?

**Comment by rhukster** [comment]
I think this was because when we started, videos didn't output properly with the image tag.  This has since been fixed. I agree that it now should output with the `![]()` syntax to render the video field.
