### ISSUE TITLE
Velocidad

### ISSUE THREAD

**Issue by decuerdas** [getgrav/grav-plugin-admin#1161]
Hola, soy nuevo usando Grav, pero extremadamente novato, y una de las cosas que noto es que el desarrollo de las acciones del panel de administrador es sumamente lento.

Mi server web es apache2 no se si eso tenga algo que ver.
Mi sistema operativo Debian Jessie

**Comment by OleVik** [comment]
It's difficult for most of the contributors to offer any help in languages other than English.

**Comment by flaviocopes** [comment]
If it's a local installation, try disabling Google Fonts in the Admin plugin settings.
