### ISSUE TITLE
Page order is wrongly inverted after updating Grav (v1.3) and Admin plugin (v1.5)

### ISSUE THREAD

**Issue by snoopython** [getgrav/grav-plugin-admin#1162]
Hello, I have noticed that the page order (configured by `Default order direction` in the system configuration) is wrongly inverted after updateing Grav (v1.2.4 -> v1.3.0) and Admin plugin (v1.4.2 -> v1.5.0).

For example, if I configured `Default order direction` as `Ascending`, folders with numeric prefix should be ordered ascending, but now they are ordered descending (and vice versa).
This is not occured with my another Grav site whose Grav and Admin plugin are not updated yet.

Although it is not critical for me, I would like to know whether it is a bug or not, and how to fix it if not a bug.

Thank you.

**Comment by flaviocopes** [comment]
Thanks for reporting, looking into.

Linked issue on the forum about ordering: 

https://discourse.getgrav.org/t/after-update-new-version-1-3-0-order-of-pages-has-changed/4125/1

**Comment by erdinctogulga** [comment]
+1 the ordering has changed last update and cannot be fix. the admin page gave the same order itself

**Comment by flaviocopes** [comment]
Replicated,  Linux + Intl only issue

**Comment by flaviocopes** [comment]
This light PR seems to fix the issue for me, can you confirm? https://github.com/getgrav/grav/pull/1571/files

**Comment by hugoaf** [comment]
worked for me, thanks Flavio.

**Comment by Asnivor** [comment]
@flaviocopes confirmed - fix works.

**Comment by snoopython** [comment]
@flaviocopes yes, fix works for my environment, thank you!

**Comment by flaviocopes** [comment]
Thanks for testing!

**Comment by fuunnx** [comment]
Same issue, but the fix works  👌

**Comment by flaviocopes** [comment]
Fix shipped in 1.5.1 🚢
