### ISSUE TITLE
Home page 

### ISSUE THREAD

**Issue by arabdivers** [getgrav/grav-plugin-admin#1165]
Dears ,,,

home page  in the admin site change to the third row ,, i can not move it to the same place like before this page should be the first row  ,, this happened after the last update https://www.arabdivers.jo/admin/pages

Regards.
Obada

**Comment by arabdivers** [comment]
![capture1](https://user-images.githubusercontent.com/30256453/28369029-fc800c28-6c9e-11e7-8cef-b5f6ea66a01f.JPG)

**Comment by flaviocopes** [comment]
Known bug https://github.com/getgrav/grav-plugin-admin/issues/1162, fixed in `develop`, update coming!
