### ISSUE TITLE
Restriciting access to the admin panel by src IP addresses.

### ISSUE THREAD

**Issue by elico** [getgrav/grav-plugin-admin#1166]
The Grav system is great but I do not understand how I can restrict access to the admin panel.
I want to restrict access to the admin panel and it's login by a src ip addresses.
Is such feature implemented?
For now what I am doing is enabling or disabling the admin user from an external script that runs on the same server and it's access is restricted by .htaccess rules.
What are my options?

**Comment by flaviocopes** [comment]
I replied on the forum a similar question: https://discourse.getgrav.org/t/security-for-admin-login-lock-after-set-number-of-tries/4140/2

Admin does not implement IP restrictions, but you can rely on the Apache htaccess/htpasswd protection.

**Comment by elico** [comment]
@flaviocopes thanks!
the idea's in the link are pretty good.

**Comment by elico** [comment]
@flaviocopes I tried to find the right rules in .htaccess to block access to the admin panel.
Can you please give me some pointers or example? I didn't managed to find the right way to block per src ip a specific path.
I managed to block access to a specific path but not by IP.

**Comment by elico** [comment]
@flaviocopes OK I found the right solution for me.
I am hosting the grav system under /grav and the admin panel is at /grav/admin
So I added the next to the .htaccess file of grav(before anything else)
```
AuthType Basic
AuthName "Password Protected"
AuthUserFile "/var/www/.admin-htpasswd"

SetEnvIf REQUEST_URI "^/grav/(admin)" PROTECTED

Deny from all
Satisfy any
Allow from env=!PROTECTED

Require valid-user
```
And it works like a charm, now I can host the admin panel on the same machine as the site and allow access using regular apache methods.
