### ISSUE TITLE
Unable to find one of the following templates: "partials/page-revisions.html.twig", "empty.html.twig" in "pages.html.twig" at line 367.   

### ISSUE THREAD

**Issue by xTrinky** [getgrav/grav-plugin-admin#1169]
What the title says guys :/ cant find the solution

this issue is on add page with everything at default

**Comment by flaviocopes** [comment]
I cannot replicate for some reason, but try applying this change, it's a small edit: https://github.com/getgrav/grav-plugin-admin/pull/1170/files. Does it fix the problem?

**Comment by xTrinky** [comment]
unfortuntely no now i have this error : "Unexpected token "name" of value "ignore" ("end of statement block" expected)."

**Comment by xTrinky** [comment]
EDIT : its working :O lol how?
will i have any kind of problem with this change?

**Comment by flaviocopes** [comment]
I made 2 commits, one right after I posted (I got the syntax wrong). I didn't think you were that fast! 

No problem with this change, I'll merge it for the next release.

**Comment by flaviocopes** [comment]
Merged with https://github.com/getgrav/grav-plugin-admin/pull/1171
