### ISSUE TITLE
Design is broken by language

### ISSUE THREAD

**Issue by Unrealno1** [getgrav/grav-plugin-admin#117]
I translated the language file in Japanese.
Admin Design is broken because the character width is different in Japanese.
e.g. no, expert

![pages-option](https://cloud.githubusercontent.com/assets/6733318/9550569/18efb6e8-4de7-11e5-8875-b7e88fc20661.png)

**Comment by rhukster** [comment]
Is it possible to provide us a fill list/screenshots of places you are having issues? That would help immensely!  Cheers.

**Comment by Unrealno1** [comment]
Sure!
I found a issue of DEFAULT_ORDERING. That's all for now.
![configuration](https://cloud.githubusercontent.com/assets/6733318/9558909/6360559a-4e26-11e5-8bd0-678e5ce89d1b.png)

**Comment by dimayakovlev** [comment]
@rhukster Look at the Grav Admin title. Mixed of latin and non latin character looking same (I showed you example with cyrillic). Used fonts must be replaced by default with something universal, what supports different scripts.

**Comment by Vivalldi** [comment]
@Unrealno1 can you send a zip of your site (the one with asian characters) to vivalldi@users.noreply.github.com

I want to test by adding some css fixes and then possibly pushing

**Comment by Vivalldi** [comment]
Sorry. My no reply isn't working. Just go ahead and send it to vivalldi1998@gmail.com

**Comment by Vivalldi** [comment]
http://i.imgur.com/9vjcyqT.png

@Unrealno1 I am not finding anything. All styling seems to be normal (though I don't know japanese. If you can find examples of issues please get a screenshot of them. I believe you had noticed those issue before we updated admin (we fixed some CSS z-layer issues)

**Comment by Unrealno1** [comment]
@Vivalldi Sorry, DEFAULT_ORDERING had been fixed.
Thank you.
However, toggle label(e.g. no, expert, short) has not yet been fixed.
![site settings - 2015-09-16 16-49-51](https://cloud.githubusercontent.com/assets/6733318/9899338/20e68c26-5c94-11e5-8e4a-c412ca0e9e02.png)
By deleting ".switch-toggle input + label { width: 50%; }" in _toggle-Switches.scss, it is fixed.
If there is no problem, Could you delete this?

**Comment by Vivalldi** [comment]
@Unrealno1 no. I will take a look at a better solution. Though it may take a while as I will need to do a little bit of restructuring.

**Comment by Unrealno1** [comment]
Thank you for your consideration!
