### ISSUE TITLE
'onAdminCreatePageFrontmatter' emits too few header information

### ISSUE THREAD

**Issue by THoenig** [getgrav/grav-plugin-admin#1172]
Hi there.

I'd like to modify/create several fields on page creation with help of a custom page creation modal. As far as I can see, only 'title' and (if exists) 'visible' are getting emitted with the event in [Admin::getPage](https://github.com/getgrav/grav-plugin-admin/blob/develop/classes/admin.php#L1396)

Custom fields are simply ignored. Is this by intention, and if yes, why? From my point of view it makes very little sense as it is now.

**Comment by rhukster** [comment]
Please check out my comments.
