### ISSUE TITLE
"Fetch Failed" Error when uploading certain media files

### ISSUE THREAD

**Issue by Linouth** [getgrav/grav-plugin-admin#1173]
Uploading certain image files seems to trigger a "Fetch Failed" error without any description. After having uploaded the 'corrupt' file the page won't render correctly anymore and I can't remove the image through the admin panel either. Only through ftp.
Most images upload without any problems. 
Since it only happens with specific files I don't think it has anything to do with mod_security (As suggested on the wiki)

Example of an image causing the error: 
![snow](https://user-images.githubusercontent.com/10274397/28485209-35d34f78-6e78-11e7-9698-224fc2a819fd.jpg)

I am running Grav v1.3.1 with Admin v1.5.1 
I can provide more images causing this error, if needed.

**Comment by SliinQ** [comment]
On further inspection this seems to be fairly similar to #1109, however the request to `admin/media/blog.json/task:listmedia` returns 200 OK instead of a server error.

**Comment by rhukster** [comment]
When i try to upload your file i get: 

<img width="783" alt="2017-07-25 at 7 18 pm" src="https://user-images.githubusercontent.com/1084697/28600262-28837f70-716e-11e7-8263-7fb5a48d81d9.png">

After changing the default value (1000000) to 3000000 bytes, it worked fine:

<img width="788" alt="2017-07-25 at 7 21 pm" src="https://user-images.githubusercontent.com/1084697/28600332-96035034-716e-11e7-9966-edab3d5257ab.png">

Could it be you are having the same problem, but not receiving the error?

**Comment by SliinQ** [comment]
No, upload_limit is set to unlimited (0). Actually it seems like it has nothing to do with uploading the file, when downloading the uploaded file through FTP the file is identical to the original. So when uploading the image with FTP and then visiting the page in the admin panel causes the same error.

I feel like it is something with fetching larger image files. If I open the image (2MB) in paint and resize it to 50% (1MB) it works just fine. 
However this image is 1572KB and works fine:
![mod-img_3552 jpg](https://user-images.githubusercontent.com/10274397/28627477-3c2284b8-7222-11e7-9864-24aa9025bdda.jpg)
While this image is smaller, 1528KB, and causes the error:
![catering 3_orig](https://user-images.githubusercontent.com/10274397/28627512-548b78c0-7222-11e7-8032-53ccc535601f.jpg)

**Comment by flaviocopes** [comment]
I'm not getting any error with those 3 images. I think it's an environment issue, but I don't have a ready suggestion on what the specific issue might be.

As @rhukster couldn't replicate as well, can you try on another server to confirm if it's environment-specific as we think?
