### ISSUE TITLE
admin editor toolbar code button

### ISSUE THREAD

**Issue by kristoferus75** [getgrav/grav-plugin-admin#1176]
Hi !

I use the markdown editor in the admin tool but what i miss is a code button in the toolbar !

this code button is sure a very useful addition ! 

My doku site have a lot of parts of code lines and this funktion would be in this case very nice !

kind regards 

kristoferus75

**Comment by paulmassen** [comment]
Added in the Editor Buttons Plugin in case it might help
https://github.com/getgrav/grav-plugin-editor-buttons/pull/26

**Comment by rhukster** [comment]
Will be available in next release of editor buttons.. Thanks @paulmassen !
