### ISSUE TITLE
Cant move pages in grav-admin

### ISSUE THREAD

**Issue by pahdom1** [getgrav/grav-plugin-admin#1177]
Was installed a clean rtfm sceleton (https://github.com/getgrav/grav-skeleton-rtfm-site) with the following plugins:
Admin Panel v1.5.1
Anchors v1.5.1
Breadcrumbs v1.5.0
Email v2.6.0
Error v1.6.0
Form v2.8.0
Highlight v1.3.1
Login v2.3.2
Problems v1.4.7
SimpleSearch v1.1

We have that tree (see attachment (tree.png))
For example:
When we try to transfer "backulainstall" into "HOWTOS" - > "Windows" we got an message about success but nothing more.
tree
![tree](https://user-images.githubusercontent.com/25930605/28642148-0f16add6-725a-11e7-85c3-c09f47bad00d.PNG)

**Comment by rhukster** [comment]
I can't replicate with a PURE RTFM skeleton + admin plugin.  I'm thinking it's got something to do with those cyrillic characters. Can you confirm this is not a problem with a pure non-cyrillic version of RTFM skeleton?

**Comment by pahdom1** [comment]
I was created a new tree in root chapter.  So i was succsess moved test pages with cyrillic and non-kirillic symbols into sub and parent chapters
![test](https://user-images.githubusercontent.com/25930605/28744068-1ff118ee-7462-11e7-9134-efe280c2fed8.PNG)

**Comment by illycz** [comment]
I have the same problem within clean instalation.
I create test page inside home and now is impossible move it back to root in admin panel.
Panel says Successfully saved but parent settings is still home not root...

**Comment by pahdom1** [comment]
@rhukster How can i help with this problem? Maybe i can give some helpfull info abuot configuration for you?. We need to fix this problem cause this a big black hole at our work.

**Comment by rhukster** [comment]
Probably the best way is to create a zip of your site and send it along to me (via our slack chat), so i can try to replicate it.

**Comment by mahagr** [comment]
The old implementation has been replaced with a new one in Admin 1.10, closing the issue.
