### ISSUE TITLE
Ordering of modular sections in admin/pages

### ISSUE THREAD

**Issue by drnasin** [getgrav/grav-plugin-admin#1181]
How the hell can you get sections in modular page to be displayed in admin the same ordering they are set in .md file (custom ordering)? I tried using

admin:
    children_display_order: collection

in modular.md but that doesn't help. 

Any other suggestions maybe before I start hacking twig and php :D

**Comment by drnasin** [comment]
Found it: https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/templates/pages.html.twig#L59

Should be:

`{% set pcol = page.children().order(page.header.content.order.by, page.header.content.order.dir|default('asc'), page.header.content.order.custom) %}`

Now my modular sections are displayed in admin/pages honoring the custom order from the  modular.md file...

not sure if it would be also smart to add the check for page.header.content.order.custom or is that handled in order function?

Let me know if I should do a pull request...

**Comment by rhukster** [comment]
Yes a pull request would be appreciated.

**Comment by drnasin** [comment]
ai ai sir! :) pull request created @rhukster

**Comment by rhukster** [comment]
PR merged. Cheers!
