### ISSUE TITLE
Blueprint extending template w/o making a template

### ISSUE THREAD

**Issue by tlflow** [getgrav/grav-plugin-admin#1184]
I'm following the Example Page Blueprints [here](https://learn.getgrav.org/forms/blueprints/example-page-blueprint) and trying to replicate the code after "This will instead add a new tab, called Gallery, with some fields in it." 

I'm able to activate the new blueprint in the admin and everything works fine but to get it to work I have to create a gallery.html.twig file. Without it, I get an error saying that Grav's looking for "gallery.html.twig". I'm confused because in the start of the gallery.yaml it has:

``
<pre>
title: Gallery
'@extends':   
    type: default   
    context: blueprints://pages
</pre>
``
Shouldn't this be extending the default template so that I don't have to create the gallery.html.twig?

**Comment by rhukster** [comment]
This is expected.  

There is a direct correlation between the page content file (`foo.md`), the blueprint for that page (`foo.yaml`), and the Twig template that renders it (`foo.html.twig`). 

If you create a new page type `bar.md`, and you want to add some custom fields or something, you need to create a `bar.yaml` blueprint file.  Whether you extend another blueprint makes no difference.  And this new custom page needs to have a matching `bar.html.twig` template to render it.  You can also extend the `default.html.twig` template of your theme, or not, the choice is yours, but it has nothing to do with how you built the blueprint (extended or not).

Hope that explains it :)
