### ISSUE TITLE
Error function transliterator_transliterate

### ISSUE THREAD

**Issue by dylerb** [getgrav/grav-plugin-admin#1186]
This error appears when I enabled Auto SEO 1.2.5 plugin.

> E_ERROR - Call to undefined function Grav\Plugin\transliterator_transliterate()

**Comment by david-szabo97** [comment]
@dylerb 
This issue is related to the Auto SEO plugin.
You can get around this by PHP `Intl` extension.

**Comment by rhukster** [comment]
I believe this issue should be raised on the autoseo plugin's issues page rather than here.
