### ISSUE TITLE
issue: saving multilanguage page with template setting

### ISSUE THREAD

**Issue by cord** [getgrav/grav-plugin-admin#119]
template is set to
`template: docs`

before:
`default.de.md`
`default.en.md`

after saving the en version:
`default.de.md`
`docs.en.md`

so the file was renamed matching the template. 
It is no longer possible to switch between languages

**Comment by rhukster** [comment]
Looks like save should use `$page->folder().$lang.'.md'` rather than $page->template()

**Comment by rhukster** [comment]
Just looked at this and it's a bit more complicated than I originally thought. I'll take it on though as it's a similar situation to the 'visible' one I resolved already.

**Comment by rhukster** [comment]
Should be resolved with #42510b6

**Comment by rhukster** [comment]
BTW, requires Grav update also due to changes in blueprints
