### ISSUE TITLE
How to hook into admin dashboard login?

### ISSUE THREAD

**Issue by raimaj** [getgrav/grav-plugin-admin#1190]
I would like to hook into the admin dashboard login form processing, I've tried both:

-  onFormProcessed
- onTask.login.login

But none of them seem to be fired. Any suggestions?

**Comment by raimaj** [comment]
Managed to do it copying code from the admin plugin:

```
public function onPagesInitialized() {
        $task = !empty($post['task']) ? $post['task'] : $this->uri->param('task');       
        if ($task == 'login') { code... }
```

Still wonder why the admin dashboard login form does not fire the normal form submit or login form hooks.

**Comment by rhukster** [comment]
Admin has it's own login handling because it was actually started before the login plugin was created.  We have grand plans to unify things, but frankly it might not happen until a Grav 2.0 release.
