### ISSUE TITLE
Style breaks when "Add page" in Japanese

### ISSUE THREAD

**Issue by mfmfneko** [getgrav/grav-plugin-admin#1198]
Style breaks when "Add page" **in Japanese**.

1. Visit http://yoursite.com/admin/pages
2. Click "Add page" button
3. Problems occurred (Image below)
![](https://user-images.githubusercontent.com/9716543/29402929-b2fa8148-8371-11e7-8714-590789bf2564.png)

✔️ Latest Version (Grav v1.3.2 | Admin v1.5.2)
❌ Firefox Developer Edition (56.0b3 (64bit))
❌ Microsoft Edge (40.15063.0.0)

**Comment by rhukster** [comment]
We really will need to enhance/modify our current toggle field solution before we can solve this because right now, each toggle button has to be the same size, and that size is somewhat hardcoded. We need one that is more flexible for each tab button.

**Comment by rhukster** [comment]
OK, i completely revamped the toggle switch so that its much more flexible now.

![2017-08-24 at 3.05 PM.png](https://shipusercontent.com/5c693feefa50ef87a7bc01d8917f93bf/2017-08-24%20at%203.05%20PM.png)
