### ISSUE TITLE
.inline css in iconpicker.css file hides inline labels in some form items

### ISSUE THREAD

**Issue by madhaze** [getgrav/grav-plugin-admin#1199]
It looks like the `.inline` css is hiding unexpected things elsewhere that is using that same class.
https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/css/iconpicker.css#L82

Inline labels used for radio buttons are now hidden due to the above css.  This needs to be refactored to not use such a generic class or something to avoid other things getting hidden that also use the `.inline` class.

![screenshot 2017-08-18 11 52 30](https://user-images.githubusercontent.com/457172/29473333-44fb8e26-840c-11e7-894a-2ab666796983.png)

**Comment by rhukster** [comment]
Fixed in develop branch. Please test to confirm.

**Comment by madhaze** [comment]
@rhukster Thanks for the quick fix.  I downloaded and tested. 
- No longer seeing the .inline items hidden.  
- I didn't test anything with iconpicker.  I haven't used that not sure what to test on that end. 
👍

**Comment by rhukster** [comment]
Great, will be in the next release.
