### ISSUE TITLE
Problem with HTML Entities

### ISSUE THREAD

**Issue by dimayakovlev** [getgrav/grav-plugin-admin#120]
Example

Step 1. Type this code and save page
![Step 1](https://cloud.githubusercontent.com/assets/8279974/9556777/06999a4c-4de0-11e5-82bb-0357a7cc64cb.png)

Step 2. Page successfully saved
![Step 2](https://cloud.githubusercontent.com/assets/8279974/9556855/621d0b42-4de0-11e5-9886-9245c05597d2.png)

If I will save page again, those HTML entities shall be saved as reserved characters.

**Comment by rhukster** [comment]
Can replicate this...

**Comment by rhukster** [comment]
Fixed in develop
