### ISSUE TITLE
Named collection unwanted changes

### ISSUE THREAD

**Issue by buitermark** [getgrav/grav-plugin-admin#1201]
When a named asset was added through system.yaml like this:

> uikit:
> - ‘system://assets/uikit/uikit.min.css’
> - ‘system://assets/uikit/uikit.min.js’
> - ‘system://assets/uikit/uikit-icons.min.js’

it's correctly presented as 

> - uikit[0]	system://assets/uikit/uikit.min.css
> - uikit[1]	system://assets/uikit/uikit.min.js
> - uikit[2]	system://assets/uikit/uikit-icons.min.js

but after only a save in the plugin it's left unusable as 

> uikit[0		system://assets/uikit/uikit.min.css
> uikit[1		system://assets/uikit/uikit.min.js
> uikit[2		system://assets/uikit/uikit-icons.min.js

So the closing brackets are removed, and leave it unusable after that.

Mentioned this here:  
https://discourse.getgrav.org/t/asset-collections-in-system-yaml-bug/4377

**Comment by rhukster** [comment]
Confirmed, this needs to be updated to support an arbitrary list of assets per name, not just a single one.  We have a field that should be able to handle this, but i'm not sure it's quite ready for primetime.  I will do some testing.

**Comment by rhukster** [comment]
Ok multilevel seems to work ok.. See this commit for an easy fix on your side.

https://github.com/getgrav/grav/commit/04690ce20639b0518faa3399d6f77ee35be0ff89
