### ISSUE TITLE
Twig Error After Update

### ISSUE THREAD

**Issue by chryton** [getgrav/grav-plugin-admin#1202]
Seeing this error when we try to access the admin after updating to Grav Admin 1.5.2 and Grav 1.3.2: http://i.rocktc.de/tMHG12/5y3EDXLe

Tried re-installing the admin plugins manually to no avail.

**Comment by rhukster** [comment]
I can't replicate this i'm afraid.  I just installed the latest 1.5.2 core and 1.3.2 admin plugin and can login just fine.  What other plugins do you have? Also do you have something custom in your user account yaml?

**Comment by TTiger** [comment]
Seems like having a file in user/accounts that isn't readable by the webuser will cause this.  I found a  username.yml file that was owned by root.  Once I corrected the permissions on that file it fixed the issue.

**Comment by chryton** [comment]
Thanks for the help everyone!
