### ISSUE TITLE
How to customize the grav plugins twig files 

### ISSUE THREAD

**Issue by geogeorgejoseph** [getgrav/grav-plugin-admin#1204]
I need to make some changes in "user/plugins/admin/themes/grav/templates/partials/logo.html.twig" and i need to keep that changes while updating that particular plugin.Can you suggest a solution for this?

**Comment by BTBTravis** [comment]
Have you read the section of the docs on [extending the admin?](https://learn.getgrav.org/admin-panel/extending#understanding-admin-themes)? I believe all you have to do is make a simple plugin that is called on _onAdminTwigTemplatePaths_ to overriding the path to the template non-destructively.

**Comment by geogeorgejoseph** [comment]
can you add example to overwrite themes/grav/templates/partial/logo.html.twig

**Comment by OleVik** [comment]
The Docs-page BTBTravis linked to explains how to do this. An example would be the [AdminIdenticons](https://github.com/OleVik/grav-plugin-adminidenticons)-plugin, which overrides some templates within Admin.

**Comment by geogeorgejoseph** [comment]
thanks.
