### ISSUE TITLE
Blog image is showing up in our dashboard but not on the forward facing site.

### ISSUE THREAD

**Issue by kyledraper** [getgrav/grav-plugin-admin#1205]
When I log into our blog, I can see the image for each blog post. But on the front of our website, a bunch of our blogs are showing error for the image.

Here's a link to one of them.
https://www.agentimpress.me/blog/how-to-go-facebook-live
https://www.agentimpress.me/admin/pages/blog/how-to-go-facebook-live

Please let me know how to fix this. Thanks!

**Comment by rhukster** [comment]
it's not something i can really troubleshoot with you here as an issue because I will need information about your server and perhaps access to your admin.  Please PM hop on our slack channel: https://chat.getgrav.org/ and I can dig into it there.
