### ISSUE TITLE
security issues

### ISSUE THREAD

**Issue by vanilla-thunder** [getgrav/grav-plugin-admin#1206]
hi!
recently i saw a notification about new version on grav website and wanted to log into admin panel to update grav.
I could not remember my passwort, so i clicked on "forgot" and while i was typing in my username, the update notification appeared above the input field and asked me if i wanted to update. Actually, i could update grad without logging in. This might be concidered to be nice, when some random people update my cms for me, but i still do not want people to do that.

Anyway, i wanted to restore my password. I typed in my username, hit the button and... suddenly i was logged in into admin interface and got an error "Cannot reset password. This site is not configured to send emails". So actually, admin panel logged me in because it could not send me an email. This is not how it works.

**Comment by rhukster** [comment]
Hmm.. yah that doesn't sound right!  I'll take a look at these issues.. Thanks for reporting.

**Comment by rhukster** [comment]
Ok i've tried to replicate and cannot with latest versions. 

1. The upgrade message does not show on the login page
2. If email plugin is disabled, a runtime error is thrown saying a required plugin is not available, so it never gets to that "Cannot reset password. This site is not configured to send emails" message.

After you upgrade, see if you can replicate the issue by changing the version in `system/defines.php` which will trigger the message.

**Comment by vanilla-thunder** [comment]
unfortunately, i don't know my version before update. I Installed grav+admin package about one month ago, maybe a bit more.
I installed 1.3.0 and 1.3.1 releases from github, they seem to be fine, no update notifications on login screen, When trying to restore password, it says "this site is not configured to send emails" when i enter the correct username, but it says "we sent you instructions" when i enter some random usernames, that do not exist. This also happens in the newest 1.3.2 release with admin 1.5.2.
This way you could figure out admin username and brutforce his password.

Does the admin login uses cookies or local storage? I was trying to log in from the same pc and browser, where i installed grav for the first time. Maybe some of them were expired, but i still was logged in.
I'm glad these strange problems can not be reproduced. 

Thank you!
