### ISSUE TITLE
Custom login.

### ISSUE THREAD

**Issue by Niko9911** [getgrav/grav-plugin-admin#1210]
I need to integrate Grav to already existing system. I will login users via JSON api. I can get all required info via JSON API also. (I know, small bottleneck, but I can deal with it.)

I can't find following functions.

- Where admin checks if admin is authenticated?
- Where admin finds information about users?

**Comment by Niko9911** [comment]
At this moment it would be best if somebody can point be function witch check if session is active.

**Comment by mahagr** [comment]
You need a custom version of login plugin, which is currently under development:

https://github.com/getgrav/grav-plugin-login/tree/feature/login_events

It will be released soon, but it still needs some extra testing.

Read the readme to see the new events which you can use to hook into the login API.

**Comment by raimaj** [comment]
This is how I solved it: https://github.com/getgrav/grav-plugin-admin/issues/1190

**Comment by Niko9911** [comment]
@raimaj thank you!

**Comment by Niko9911** [comment]
Looks like saying f u if you close cases without asking... So F u then.

**Comment by rhukster** [comment]
The answer is that it really needs to wait until login_events branch is finalized and merged into the main develop branch of login plugin. Other than that you can use the example @raimaj gave with the #1190 issue.  

No need to be rude.. You just need to read what was said.
