### ISSUE TITLE
Duplicate form id #blueprints on the same page in the admin panel

### ISSUE THREAD

**Issue by TomOne** [getgrav/grav-plugin-admin#1216]
In the admin panel there are sometimes multiple forms with the same id `#blueprints` on the same page, which is not allowed by the HTML standard. For example, there are 4 forms with the same `#blueprints` id on editing pages, e.g. /admin/pages/home. This can lead to problems, especially with JavaScript.

For instance it causes the language switcher in MS Edge (fixed in my pull request #1213) to break randomly because the form attribute polyfill uses id selectors for forms in JavaScript.

I’ve noticed that the Twig partials for the forms support a `form_id` variable, so it should be enough to just pass unique ids to `form_id` when including the partials, right?

**Comment by rhukster** [comment]
Yes, that's basically the solution.  I've fixed the pages.html.twig to ensure that the modals each use a custom `form_id`.  If you find any more please let me know or fix them yourself in a PR and i'll merge it.  Cheers.
