### ISSUE TITLE
Cannot scroll to bottom of markdown editor in Edge/IE/Firefox

### ISSUE THREAD

**Issue by TomOne** [getgrav/grav-plugin-admin#1217]
In the markdown editor window it’s not possible to scroll to the bottom of the editor content in Edge v15, IE11 and Firefox. The scrollbar stops where the last line of the editor content is only partially visible and doesn’t let scroll any further.

Here’s a GIF to show the behavior:

![markdown-editor-edge-ie-scrolling-issue](https://user-images.githubusercontent.com/4357973/30063194-2a1d35e6-924e-11e7-97d7-a1892914c3ae.gif)

As you can see, clicking on the arrow of the scrollbar, the scrollbar briefly jumps down to the button, but then jumps back to the position where it’s stuck.

This issue could come from CodeMirror itself, but the [demo with scrollbars](https://codemirror.net/demo/simplescrollbars.html) works fine in Edge/IE.

It’s probably a CSS or JS issue. I’ll investigate this problem.

**Comment by TomOne** [comment]
I noticed that Firefox is affected too, not only MS browsers. It has to do with different scrollbar heights in browsers, see #1219.

**Comment by rhukster** [comment]
I've merged this solution. If we find a better one, we'll switch to that. thanks.
