### ISSUE TITLE
Put focus on textarea when creating a page

### ISSUE THREAD

**Issue by jpfleury** [getgrav/grav-plugin-admin#122]
- Click on *Add Page*.
- Fill the popup form.
- Click on *Continue*.

The creation form (url `/admin/pages/title`) appears:

![capture d ecran_2015-08-29_03-44-33](https://cloud.githubusercontent.com/assets/687082/9560983/83f074b4-4e00-11e5-9634-f7f2ded863bf.png)

There's no focus on any field. It would be useful to automatically put the focus on the textarea, so we could start entering text without having to click on the textarea first (or selecting it with the TAB key).

**Comment by flaviocopes** [comment]
Agree, maybe it's better to put the focus on the `title`, then with the `tab` button we go to the editor.

**Comment by flaviocopes** [comment]
@rhukster what you think, good idea?

**Comment by rhukster** [comment]
Yah good idea
