### ISSUE TITLE
Mediapicker - Stored value for media in a modular page

### ISSUE THREAD

**Issue by paulmassen** [getgrav/grav-plugin-admin#1220]
Hi!
I'm enjoying these days the excellent mediapicker field. However, I'm having trouble accessing images when these images are selected from a module inside a modular page.
The value is stored with a format such as `/home/_slider/slide01.jpg`
and browsing www.example.com/home/_slider/slide01.jpg can not access the image. 

A correct path to this image would be www.example.com/user/pages/02.accueil/01._slider/slide01.jpg

Of course, it's possible to do some regex to get the path without the image name, then use ->folder to get the folder name for this url, and then add the extracted image name, but it's a lot of trouble just for an image.
Therefore, could it be possible to store the value with the folder name to manipulate these images easily? 

Thanks!

Paul

**Comment by rhukster** [comment]
This is because modular pages are not routable, and the path: `/home/_slider/slide01.jpg` is the Grav 'route' to the image, not the direct path.. If you were to manipulate the image or use a media method so that it is cached, it would create a reference to the `/images/` folder and it would work.

**Comment by rhukster** [comment]
alternatively you could set the modular page to be `routable: true` and it should work too, although I don't think this is a viable solution as that means that modular page would be reachable directly.

**Comment by rhukster** [comment]
OH another way, is to get the basename of the image path: `/home/_slider`, find the page, then access the media:

```
{{ page.find('/home/_slider').media['slide01.jpg'].url }}
```

**Comment by paulmassen** [comment]
Thanks a lot @rhukster that's a very good idea indeed.
In case it helps someone, here is a regex for grabbing the path without the image name with $1 and get the image name with $3.
`$pattern = '~((\/[^\/]+)+)\/([^\/]+)~';`

**Comment by rhukster** [comment]
BTW I added `basename` and `dirname` twig filters in develop to make this simpler.
