### ISSUE TITLE
filepicker field doesn't work in 1.6.0

### ISSUE THREAD

**Issue by tranduyhung** [getgrav/grav-plugin-admin#1226]
After updating the plugin from 1.5.2 to 1.6.0, filepicker form fields don't work any more.

* The field only shows the selected file, it doesn't show the other files in the folder.
* After page is loaded, there is a red notification on the top right corner of the page saying "Fetched Failed:"
* The AJAX call to get files in folder (eg http://site.com/admin/themes/my-theme.json/task:getFilesInFolder) returns an empty response.

**Comment by rhukster** [comment]
I can't replicate this.. The `filepicker` field seems to work fine for me with no errors:

![2017-09-20 at 3 06 pm](https://user-images.githubusercontent.com/1084697/30667582-446865ba-9e15-11e7-92ac-61503ed25d11.png)

What does your blueprint look like? Did you update the form plugin as well as admin? What about Grav version?

**Comment by tranduyhung** [comment]
Thank you for your reply! I have just found out that the problem is actually from a file in the folder. If there is a broken image in folder, the AJAX response is empty. The designer did something wrong and the image was broken while saving. This problem only happens on Linux, not on Mac. I will reopen or open a new ticket if we find more information.
