### ISSUE TITLE
Color palette option in grav editor

### ISSUE THREAD

**Issue by geogeorgejoseph** [getgrav/grav-plugin-admin#1227]
I need to change the colour of the some text from grav editor.Can you add a option for color change in grav editor?

**Comment by axel-rank** [comment]
There is already a plugin:
https://github.com/getgrav/grav-plugin-markdown-color

**Comment by geogeorgejoseph** [comment]
Is it possible to change the text color from the page editor
![edit appendices fp2020](https://user-images.githubusercontent.com/25584016/30845035-1c5758fe-a281-11e7-95e1-fc259d09e7b3.png)
?

**Comment by w00fz** [comment]
The plugin @axel-rank mentioned above should allow you to use the shot codes in the editor as well.

**Comment by geogeorgejoseph** [comment]
If we take drupal,  the editor have one option to change the color of the text without using any other shot codes.Is it possible to add that feature in the grav editor section?

**Comment by axel-rank** [comment]
Very soon there's TinyMCE Editor available in GRAV!
https://github.com/getgrav/grav/issues/1666
https://github.com/newbthenewbd/grav-plugin-tinymce-editor
Your problems should be solved.
