### ISSUE TITLE
error with fallback image (RTFM skeleton)

### ISSUE THREAD

**Issue by frumbert** [getgrav/grav-plugin-admin#1228]
Now, after getting a few hundred pages in to the system, we are adding new images and now seeing the error not being able to find:

    (url)/public/images/f/a/l/l/b/fallback.jpg

Tried: clearing image cache, all cache, updating grav, 

Noticed there's errors appearing (Fetch Failed: Cannot convert undefined or null to object) when the page loads to be edited in the admin panel - but can't really tell what it is since the text is white, the background is white, the border is red, and the damn thing fades off the screen before I can read it anyway. ~~Are these error screens logged anywhere?~~  oops, `logs`, like it tell me *facepalm*. Looks like the back end errors are logged, but these javascript front end ones? what about those? This screen is what I am on about ...

<img width="586" alt="screen shot 2017-09-21 at 4 59 16 pm" src="https://user-images.githubusercontent.com/592257/30685576-b5f1f38e-9ef8-11e7-992c-3c639fd8bfbf.png">

/edit

I enabled full logging to find out what the deal is - it's in`/public/vendor/gregwar/image/Gregwar/Image/Image.php` getCacheFallback(). Incidentally I went to grav settings and disabled cache, but it still occurs.

    copy(/var/www/html/guide.mydomain.com/public/images/f/a/l/l/b/fallback.jpg): failed to open stream: No such file or directory"

That's right, that folder does not exist. Is it some kind of internal route or some code hint? Can it be fixed? Is it caused by uploading images to a page that break somehow? I tried removing the links to the images and saving the pages (no fix) or even cutting everything from the page so it's empty (no client-facing error now, but there is still the red error box in the interface, but there's no content, so , no, not a fix!) 

What now?

(Linux 4.8.6-x86_64-linode78 #1 SMP Tue Nov 1 14:51:21 EDT 2016 x86_64, apache 2.4.25, php 5.6)

**Comment by rhukster** [comment]
It probably is a memory issue.  Please check your `php.ini` and increase your PHP memory allocation.

**Comment by frumbert** [comment]
really?

    root@prodbox:/etc/php/5.6/apache2# cat php.ini | grep memory_limit
    memory_limit = 256M

**Comment by rhukster** [comment]
It really depends if you have a lot of content, and many images that are being processed.  If you raise that to 512M and the issue goes away, then that's the issue.  If it makes no difference, then something else going on.

**Comment by frumbert** [comment]
Doubling it doesn't help (restarted apache, etc). I've noticed with this particular page if I upload images they appear to upload and I'm told they save. I then add them to the content, save, and after it reloads the images are not shown on the editor again. If I nav into the `user/pages/...` folder sure enough they aren't appearing there either. Uploads to this box do work; php's limit is 128mb and I've tested it; permissions appear correct; nothing is appearing in the grav.log file (should it?)

**Comment by rhukster** [comment]
It's really an error thrown out of the Gregwar library.  So if it's not memory it could be an issue with a particular image file.  There might be an error in the system's PHP error log with more details, have you looked there?

**Comment by frumbert** [comment]
The file resolved after a while and for no known reason. I suspected it was the image, but not sure.

However, I've just installed a new grav, _from a skeleton_, and on a completely different box, and it threw exactly the same error when first starting. php memory limit 512M ..

**Comment by frumbert** [comment]
I now get the error on intermittently on pages that do not have any media.

![screen shot 2017-12-11 at 9 36 21 pm](https://user-images.githubusercontent.com/592257/33827368-3683e022-debc-11e7-887b-c869f388dc4c.png)

on disk, the folder simply contains the markdown of the page

<img width="722" alt="screen shot 2017-12-11 at 9 43 12 pm" src="https://user-images.githubusercontent.com/592257/33827414-6174b0b8-debc-11e7-9c19-e6305fee4033.png">

So I don't see how the Gregwar library can be involved.

The error text (hard to copy) reads:

```
Drop your files here or click in this area
 Found an issue? Please report it on GitHub.
Grav v1.3.10 - Admin v1.6.7 - was made with  by RocketTheme.
Fetch Failed: 
Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
at Function.keys ()
at https://guide.coursesuite.ninja/user/plugins/admin/themes/grav/js/admin.min.js?6055e5c33a:5:24264
at https://guide.coursesuite.ninja/user/plugins/admin/themes/grav/js/admin.min.js?6055e5c33a:4:27913
at
copy(/var/www/html/guide.coursesuite.ninja/public/images/f/a/l/l/b/fallback.jpg): failed to open stream: No such file or directory
```

I have
 Admin Panel  v1.6.7
 Anchors  v1.5.2
 Breadcrumbs  v1.5.1
 Email  v2.7.1
 Error  v1.6.0
 Form  v2.11.0
 Highlight  v1.4.0
 Login  v2.5.0
 Markdown Notices  v1.0.0
 Problems  v1.4.7
 SimpleSearch  v1.13.0

Php memory limit is 512M
root@prodbox:/etc/php/5.6/apache2# apache2 -v
Server version: Apache/2.4.25 (Debian)
Server built:   2017-09-19T18:58:57
root@prodbox:/etc/php/5.6/apache2# php -v
PHP 5.6.31-4+ubuntu17.10.1+deb.sury.org+4 (cli)

**Comment by mahagr** [comment]
I believe this to be fixed.
