### ISSUE TITLE
Tags containing apostrophe don't work

### ISSUE THREAD

**Issue by jpfleury** [getgrav/grav-plugin-admin#123]
When creating a page, put *l'été* as tag. Save the page and display it. The tag is saved and is listed (using the blog skeleton), but when we click on it to display all pages with this tag (url `/tag:l'été`), no pages are listed.

I didn't test if the problem occurs with other characters or if it also occurs with other taxonomies.

**Comment by flaviocopes** [comment]
@rhukster this PR https://github.com/getgrav/grav/pull/288 fixes the problem. Do you think it's good to go?
