### ISSUE TITLE
Statistics Widget html issue

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#1234]
After upgrade to Admin 1.6.1/Grav 1.3.4

![bildschirmfoto_2017-09-30_09-54-07](https://user-images.githubusercontent.com/12480617/31043933-821c7db2-a5c5-11e7-97f8-0d4bea85e395.png)
Cleared All grav/browser Caches.

**Comment by rhukster** [comment]
Could well be something related to the language file, can you try another language?

**Comment by rhukster** [comment]
Actually I can recreate, looking at it

**Comment by w00fz** [comment]
This issue is caused by chartist not allowing HTML in labels anymore (https://github.com/gionkunz/chartist-js/issues/937). I worked around the issue for the moment by redrawing the labels once a chart gets drawn.

**Comment by rhukster** [comment]
Thanks @w00fz !
