### ISSUE TITLE
No Login On Localhost after Upgrade! Invalid Security Token!

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#1235]
Since Admin 1.6.1/1.6.2  it is not possible to login in Admin on localhost anymore.
Message: Invalid Security Token

![bildschirmfoto zu 2017-10-01 12-43-01](https://user-images.githubusercontent.com/12480617/31053835-2d0ad832-a6a6-11e7-8cd5-3cddaf70469c.png)

**Login is working on livesite.
It's only an issue on localhost!**
Cleared all caches. Restarted browser, system. Not working!

**Comment by axel-rank** [comment]
Seems to be not an admin issue. Seems to be an **issue with GRAV 1.3.4**
I checked with my backup and installed only the Grav update. Can't login in admin on localhost anymore.

**Comment by axel-rank** [comment]
Ok, I found the cause:
**https://github.com/getgrav/grav/pull/1656**
After removing
ini_set('session.cookie_secure', $secure);
ini_set('session.cookie_httponly', $httponly);
local login is working again

**Comment by axel-rank** [comment]
Update:
For a working login on localhost in my theme/system setup in GRAV 1.3.4 I have to **set session secure to false** in system.yaml
Don't need to delete
ini_set('session.cookie_secure', $secure);
ini_set('session.cookie_httponly', $httponly);
in  system/src/Grav/Common/Session.php anymore

**Comment by rhukster** [comment]
Yah, the secure option was broken for session cookie.  It was supposed to be setting the cookie to HTTPS, which it was not prior to this release if you had that option for `session.secure: true`.  Which means this option should only be set if you have HTTPS enabled on your server (defaut is `false`). 

So there are scenarios where people had set this to `secure: true` and it worked accidentally.  There's a note in the docs (that has been there BTW) to only use that setting if you have https enabled, but it's not super clear.  I'll add a note to the docs under invalid security token.

**Comment by rhukster** [comment]
Added to it's own page now: https://learn.getgrav.org/troubleshooting/invalid-security-token

**Comment by rhukster** [comment]
![2017-10-01 at 10 01 am](https://user-images.githubusercontent.com/1084697/31056493-920ea1bc-a68f-11e7-91ea-520af46a4e05.png) BTW, has been in tooltip too :)
