### ISSUE TITLE
Unable to upload large files on slow internet connections

### ISSUE THREAD

**Issue by jackmu95** [getgrav/grav-plugin-admin#1238]
Currently its not possible to upload large files (e.g. PDFs) on slow internet connections.
When the upload takes longer then 30 seconds, it just aborts.

This is due the default `timeout` option set by [Dropzone](http://www.dropzonejs.com/#config-timeout).
To work around it you can just set the `timeout` option to `0` which disables the timeout completely.

**Comment by pieplu** [comment]
I found this bug too. I hope it will be fixed soon :)
