### ISSUE TITLE
Admin's login.md doesn't seem to be overriding the login plugin

### ISSUE THREAD

**Issue by akoebbe** [getgrav/grav-plugin-admin#124]
I was noticing that the `autofocus: true` in pages/admin/login.md doesn't seem working and after a little bit of investigation it seems like admin's login.md isn't being used at all. Is it possible the login.md isn't overriding the login plugin's md?

**Comment by rhukster** [comment]
Quite possible.. i will investigate.

**Comment by flaviocopes** [comment]
Yes, what happens is that the Form plugin's login.md is used in the admin too. 
We can just drop the admin-side login.md file, since it's not picked up at all.

**Comment by rhukster** [comment]
Fixed this to use admin login page
