### ISSUE TITLE
Doesn’t working with Japanese language

### ISSUE THREAD

**Issue by volcani** [getgrav/grav-plugin-admin#1246]
Hi.
I tried Grab for my personal website, but now I found some error.

On iOS, I can’t write with Japanese language.
On android chrome and other PC browser, 403 error appears when I save date.
I have checked server setting, but nothing changes.

Thank you for checking.

**Comment by rhukster** [comment]
Was it text specifically or the folder name?  I've just commited a fix to address multibyte folder names that were causing an issue.
