### ISSUE TITLE
While uploading image file to page media shows some error and redirecting to login page.

### ISSUE THREAD

**Issue by geogeorgejoseph** [getgrav/grav-plugin-admin#1247]
While uploading image file to page media shows some error and redirecting to login page.

![issue png png image 1440 x 900 pixels scaled 83](https://user-images.githubusercontent.com/25584016/31703122-86f77770-b3ca-11e7-8b5d-6a5fa992202c.png)

**Comment by rhukster** [comment]
That's a weird one. I think it's something related to your hosting provider.  is that image actually being generated by your webserver? can you inspect it and see that's an actual image?
