### ISSUE TITLE
Duplicate labels in languages.yaml

### ISSUE THREAD

**Issue by Unrealno1** [getgrav/grav-plugin-admin#125]
I found duplicate labels in languages.yaml.

ADD_ACCOUNT
CHECK_FOR_UPDATES
DATE
DEFAULT
ORDER
SITE
TITLE
VERSION

If you use a different meaning, please set a prefix.
I want to divide "TITLE", because user "TITLE" is a different word with page "TITLE" in Japanese.

**Comment by flaviocopes** [comment]
Thanks for finding those duplicates! If you need to add a different string, tell me where it's used and I'll add it.
