### ISSUE TITLE
All Frontmatter deleted in Expert Mode

### ISSUE THREAD

**Issue by twwd** [getgrav/grav-plugin-admin#1252]
With the latest Grav Release v1.3.8 and latest Admin Panel v1.6.5, I have the follwing problem:
Whenever I save a page in Export mode, all Frontmatter (including title etc.) is deleted and replaced with
`media_order: ''`

The bug does not occur if I use Admin Panel in Version v1.6.4 (with the latest Grav).

**Comment by rhukster** [comment]
I'm actually aware of this, we will get a fix out ASAP. Might be a few hours, as I need @w00fz to help with the JS bits he did for this.

**Comment by diegovogel** [comment]
Ran into this today as well. Thought I had screwed up my Grav installation, then figured out it was the Admin plugin update after some testing. Good to know there's a fix in the works.

**Comment by w00fz** [comment]
This is sorted now!

**Comment by w00fz** [comment]
⬆️ no pun intended 🙃

**Comment by rhukster** [comment]
Also released and packages rebuilt.

**Comment by diegovogel** [comment]
Thanks for the quick work guys!

**Comment by twwd** [comment]
Wow, that was fast! Thanks 👍

**Comment by btopro** [comment]
great work thank you so much!

**Comment by Mesh0815** [comment]
Hi, actually i am running admin plugin v1.6.7 with latest official grav 1.3.10 , but the error (media_order: '' after saving) mentioned above is still existing.

**Comment by cniweb** [comment]
I have also the problem: Grav v1.3.10 - Admin v1.6.7!
