### ISSUE TITLE
[Suggestion] Template preview on the template selection field

### ISSUE THREAD

**Issue by paulmassen** [getgrav/grav-plugin-admin#1255]
Hi!

I think it could be a great feature to add the possibility to display a preview of how the template will be rendered in the admin. 

A theme designer could therefore associate an image to a template by giving the screenshot the same name as the template and it could be displayed just like in a filepicker field with preview_images enabled.

It could be very useful, especially when we have some themes with variations of a page layout and it could make the process of page creation more friendly for non.-dev grav users.

Let me know if you think this is a good idea, or if it is already planned for Admin Pro.

Thanks!
Paul

**Comment by rhukster** [comment]
That does sound amazing, but to be honest dynamic preview is going to be all but impossible.  Static preview images are about the only possibility and for it to be even something worth doing, we would need to have a bunch of theme updates to support it.  I don't really think this is going to happen.
