### ISSUE TITLE
"Invalid AJAX response" When using Built-in PHP Webserver (Windows)

### ISSUE THREAD

**Issue by colinwilson** [getgrav/grav-plugin-admin#1258]
Windows: `8.1`
Grav: `1.3.8`
```
PHP 7.1.11 (cli) (built: Oct 25 2017 20:54:15) ( NTS MSVC14 (
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```
Seeing "Invalid AJAX response" errors when using the built-in PHP webserver.
`> php -S localhost:8000 system/router.php`

![2017-11-04 04_13_28-](https://user-images.githubusercontent.com/12916656/32402204-c773b972-c116-11e7-9d17-3387e6acdc01.png)

**Comment by rhukster** [comment]
Just FYI, this does appear to be windows-specific as things are working fine on my mac.  I need to setup a VM to test this on windows. Unless others can provide insight?

**Comment by rhukster** [comment]
i've been able to replicate this.. now i need to work out what's going on

**Comment by mahagr** [comment]
Fixed in latest CI of Grav.

**Comment by rhukster** [comment]
Can you please test?

**Comment by colinwilson** [comment]
Thanks. Resolves the error. The notifications and news feeds sections also load properly now.

**Comment by llaville** [comment]
Hello

Thanks for this fixe. I've just begin to learn and start with Grav, but it seems really cool :-)
Just one remark. All skeletons should be impacted by this specific Windows behavior. An Important notice must be added in troubleshooting guide of https://github.com/getgrav/grav-learn
Or alternatively fix all skeletons. Example with https://github.com/getgrav/grav-skeleton-blog-site

Laurent

**Comment by rhukster** [comment]
New releases and builds of all skeletons coming soon.
