### ISSUE TITLE
Unable to create page via admin

### ISSUE THREAD

**Issue by mufac** [getgrav/grav-plugin-admin#126]
I think this change:

https://github.com/getgrav/grav-plugin-admin/commit/e2e1076e8e55679108a72a1f3f435906d5ee7c00

May have caused a regression. I'm getting:

Whoops\Exception\ErrorException thrown with message "Undefined index: type"

Stacktrace:
#13 Whoops\Exception\ErrorException in /var/www/grav/user/plugins/admin/classes/admin.php:586
#12 Whoops\Run:handleError in /var/www/grav/user/plugins/admin/classes/admin.php:586
#11 Grav\Plugin\Admin:getPage in /var/www/grav/user/plugins/admin/classes/admin.php:233
#10 Grav\Plugin\Admin:page in /var/www/grav/user/plugins/admin/admin.php:224
#9 Grav\Plugin\AdminPlugin:onTwigSiteVariables in <#unknown>:0
#8 call_user_func in /var/www/grav/vendor/symfony/event-dispatcher/EventDispatcher.php:164
#7 Symfony\Component\EventDispatcher\EventDispatcher:doDispatch in /var/www/grav/vendor/symfony/event-dispatcher/EventDispatcher.php:53
#6 Symfony\Component\EventDispatcher\EventDispatcher:dispatch in /var/www/grav/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php:23
#5 RocketTheme\Toolbox\Event\EventDispatcher:dispatch in /var/www/grav/system/src/Grav/Common/Grav.php:370
#4 Grav\Common\Grav:fireEvent in /var/www/grav/system/src/Grav/Common/Twig/Twig.php:303
#3 Grav\Common\Twig\Twig:processSite in /var/www/grav/system/src/Grav/Common/Grav.php:143
#2 Grav\Common\Grav:Grav\Common\{closure} in /var/www/grav/vendor/pimple/pimple/src/Pimple/Container.php:112
#1 Pimple\Container:offsetGet in /var/www/grav/system/src/Grav/Common/Grav.php:231
#0 Grav\Common\Grav:process in /var/www/grav/index.php:31

When I create a new page via the admin plugin.

Occurred with fresh clone of Grav on commit c4a51c2c9f9824a33e10957707c8e6eb0035f76f (current develop HEAD). Grav admin version v0.4.2 (commit c4a51c2c9f9824a33e10957707c8e6eb0035f76f) installed via gpm.

**Comment by rhukster** [comment]
What display template/page name were you using when you tried this? Definitely is related to this commit, but if your on latest Grav and latest Admin plugin, it should work fine for you as it does for me.

**Comment by rhukster** [comment]
Oh!, your running Grav from github, but admin from GPM.  You need to update with admin from github also.  There are changes that need to be synced between the two.

**Comment by mufac** [comment]
Ah my mistake. Sorry for the noise.
