### ISSUE TITLE
Set Expanded Pages View As Default?

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#1260]
Hi,
would be great to have an option to set expanded pages view to be default when clicking on pages menu in admin.

**Comment by rhukster** [comment]
I'll add this to the 'enhancements' list, but it's a little low down on the list of things to get fixed/sorted/improved :)

**Comment by axel-rank** [comment]
Yes, It's not really very important. And the page view stays expanded even if you log out and in again.
It only resets to closed when you close your browser. Anyway I thought it would be great to have the option just like the option to set normal and expert view as default. Thank you.

**Comment by mahagr** [comment]
Grav 1.10 has a new implementation, closing the issue.
