### ISSUE TITLE
CSS Pipeline fails with Google remote fonts enabled in Gantry 5 admin

### ISSUE THREAD

**Issue by marktaylor46** [getgrav/grav-plugin-admin#1261]
Steps to reproduce:
1. Load Clean rocketlauncer installation of GRAV//Gantry5/Helium
2. Go to Gantry 5 admin > base outline > styles and change any font to "ABeeZee" (Google font).
3. Go to GRAV configuration and enable "CSS Pipeline"
4. Go to Frontend and you will see that site is broken.

If you change font back to local font everything is then ok again.

![2017-11-07_14-39-31](https://user-images.githubusercontent.com/11683218/32499361-47e01bcc-c3ca-11e7-8d17-39329008efb7.png)

Forum topic: http://www.rockettheme.com/forum/grav-general-questions/273038-grav-granty5-based-themes-remote-font-css-pipeline-breaks-css

**Comment by rhukster** [comment]
Assigned @mahagr to take a look.

**Comment by buikdaanser** [comment]
Any update on this annoying bug?
Thanks.

**Comment by mahagr** [comment]
No update yet, I've been super busy elsewhere.

**Comment by mahagr** [comment]
It only happens in production mode. If I turn Gantry to development mode, it works just fine.

**Comment by marktaylor46** [comment]
Still needs fixing though - you will be in production mode on a live site.

**Comment by mahagr** [comment]
Fix is in https://github.com/getgrav/grav/pull/1763
