### ISSUE TITLE
[FR] [Paid] More Detailed Page Management

### ISSUE THREAD

**Issue by artofthesmart** [getgrav/grav-plugin-admin#1265]
Right now we have a tree-like viewer for Pages.  That's a solid start, but I'd like something with more heft so I can manage dozens-to-hundreds of pages as my site grows.

At least the ability to sort by date published, alphabetically by slug/title, or by page type.

At best, it'd be something more modular where I can add columns to the tree view based on the metadata I have about pages.  Like the ones above, but it could also include tags, categories, etc from the YAML section of the page.  :)

**Comment by rhukster** [comment]
does the "paid" mean your willing to sponsor the development of this feature?

**Comment by artofthesmart** [comment]
Oh, sorry, just that it's a feature that I'd love to see in the admin plugin if one comes up someday and that I'd be willing to pay for it as part of a paid plugin version.  :)

**Comment by krzysztofgal** [comment]
I`d also anticipate that kind of pages management, with pagination.

The same issue is with page editor and ordering. Maybe can we add setting to admin plugin to not show/use this feature.

**Comment by mahagr** [comment]
Admin 1.10 has a new page management.
