### ISSUE TITLE
[FR] [Paid] Spell Check in Page Editor

### ISSUE THREAD

**Issue by artofthesmart** [getgrav/grav-plugin-admin#1266]
Right now the admin plugin uses a WYSIWYG editor for pages, but it doesn't allow the browser's native spell-checker to work properly.  Leaves you in a bit of a lurch.

Would be nice to alter the editor to allow that to work properly.

**Comment by rhukster** [comment]
It's a limitation of the editor we use (CodeMirror), as it's not using a standard HTML field that supports spell check, and a JS solution would require a HUGE dictionary database in potentially every language.

**Comment by rhukster** [comment]
BTW, this could be solved with an alternate editor.

**Comment by dcrobertson01** [comment]
Can we disable the wysiwyg editor? I'd take a spell check over wysiwyg any day.

**Comment by artofthesmart** [comment]
I've had some success with just editing stuff directly in -gulp- SSH.  Vim has spellcheck that does well enough and I've been meaning to learn how to use it.  ;)

**Comment by amoliski** [comment]
Would this plugin be reasonable to use?

https://github.com/sparksuite/codemirror-spell-checker

**Comment by MattDelmarter** [comment]
Has anyone managed to integrate this plugin with Grav? If so, any tips on how to do this?

**Comment by RomainLWiz** [comment]
Do you have any news or have you started the project since the last return ?

**Comment by artofthesmart** [comment]
I feel like it would probably be done as a build of CM with the spell checker included, and that comes with all the same baggage as other Grav includes (e.g. security reviews).  There's also the matter of size: the owner of CM didn't want to bundle the spellcheck by default because it's so large ([sauce](https://github.com/codemirror/CodeMirror/issues/1017#issuecomment-12590414)).  Typo.js (and the CM Spell Checker link above) add ~750kb and that's _just_ for en-us.  Not commenting if that's a sufficient reason not to do it, just relaying info into this thread.  :)

**Comment by RomainLWiz** [comment]
> Would this plugin be reasonable to use?
> 
> https://github.com/sparksuite/codemirror-spell-checker


What one has managed to implement ?

**Comment by Rolf-Smit** [comment]
So what I did to "solve" the problem, was to add: `'spellcheck': 'true', 'inputStyle': 'contenteditable',` to `user/plugins/admin/themes/grav/templates/forms/fields/codemirror/codemirror.html.twig` and to `user/plugins/admin/themes/grav/templates/forms/fields/editor/editor.html.twig` and on at least Firefox this works perfectly (at least for my needs). I'm not a website guru, so don't take my word for it. But it seems to be working fine, something to consider to implement in the next version of Admin?

**Comment by mahagr** [comment]
CC @w00fz @rhukster

**Comment by w00fz** [comment]
With [NextGen Editor](https://getgrav.org/premium/nextgen-editor) available as a better WYSIWYM solution, it's not really worth for us putting time in trying to get an older Editor like CodeMirror, spellcheck compatible.

The honest truth is any type of spellchecking for WYSIWYG editors, require a JS implementation that is accompanied by a dictionary that is available in multiple languages and maintained by the vendor. This is not something we want to deal with and the reason we went with a complete different approach with the WYSIWYM NextGen Editor which uses modern technology and ties to your system and browser for the spellchecking functionality and more.

**Comment by symgryph** [comment]
What does your 'editor.html.twig' look like? I saw it in the first file , codemirror, but don't know where ot put the statements referenced in the editor.html.twig?
