### ISSUE TITLE
Create widgets button shows more than one times

### ISSUE THREAD

**Issue by geogeorgejoseph** [getgrav/grav-plugin-admin#1268]
Create widgets button shows more than one times
![screenshots1](https://user-images.githubusercontent.com/25584016/32774379-19668c58-c952-11e7-805d-0ce6f37cd051.png)
![screenshots2](https://user-images.githubusercontent.com/25584016/32774380-199c3ea2-c952-11e7-8c6f-4e4bc2e296f5.png)

**Comment by rhukster** [comment]
How did you add this button?
