### ISSUE TITLE
Internal server error shown in notepad-skeleton on clear all cache

### ISSUE THREAD

**Issue by siren386** [getgrav/grav-plugin-admin#127]
The "clear assets" (and because of this) the "clear all" gives an internal server error on the notepad-skeleton without any modifications in version 1.1.0 with the admin-plugin 0.4.2

![clear_cache](https://cloud.githubusercontent.com/assets/14054474/9579181/d124566e-4ff0-11e5-90bd-1e898754dc5c.JPG)

**Comment by rhukster** [comment]
Ok, we need to see what happend with the ajax request. Please use chrome and login.. Then open your developer tools and switch to the **Network** tab (1)

![dashboard grav2 2015-08-31 07-48-26](https://cloud.githubusercontent.com/assets/1084697/9580133/c0fa7ae8-4fb4-11e5-8d3d-dc14ce02c718.png)

Then click the **XHR** filter (ajax calls) (2).  

Now click the **Clear Cache** button in the admin, you should see a `task:clearCache` request show up..  Click that (3).

Now click the **Response** tab of this new view.  The Ajax there is what I need to see now.

![dashboard grav2 2015-08-31 07-46-12](https://cloud.githubusercontent.com/assets/1084697/9580092/7ae38a5e-4fb4-11e5-891c-b571b725ef47.png)

**Comment by siren386** [comment]
The output is:

{"error":{"type":"Whoops\\Exception\\ErrorException","message":"Invalid argument supplied for foreach()","file":"\/var\/www\/vhosts\/mydomain.com\/httpdocs\/notepad\/system\/src\/Grav\/Common\/Cache.php","line":242}}

I changed my domain-name to mydomain.com ;-)

Regards; siren

**Comment by rhukster** [comment]
For some reason Grav is getting back a null for one of your cache file paths.  Either that folder doesn't exist or it's null.  I've added a quick validation check in the code and that will be released with other releases with Grav today.

You should check to ensure you have the following directories at the root of your Grav install and they are writable by the apache web server process:

```
cache/
images/
assets/
```

**Comment by siren386** [comment]
Just for your information, with the update of admin-plugin to 0.4.3 the error is gone. :-)
