### ISSUE TITLE
H1 & H2 elements not left aligned

### ISSUE THREAD

**Issue by testXpert** [getgrav/grav-plugin-admin#1270]
Hello, 
I am using Grav for my websie on http://www.testxpert.fr/fr/experience .
I noticed that using H1 H2 elements make the headings centered.

Could you check please?

Best regards

**Comment by axel-rank** [comment]
This is not an admin-plugin-issue. This is simply css-styling.
Your H1 Headings are centered. Your H2 Headings are left aligned.
You are using antimatter theme. You need a custom css. Putting your css-style for H1 or H2 (text-align: center, left  or whatever you want) in there.
https://learn.getgrav.org/themes/customization
