### ISSUE TITLE
Could not encode content to ISO-8859-1 when activating 2-Factor Authentication

### ISSUE THREAD

**Issue by tealow** [getgrav/grav-plugin-admin#1271]
I get the error "Could not encode content to ISO-8859-1" when i try to activate 2-Factor Authentication.
![screenshot-2017-11-19 user thilo woo](https://user-images.githubusercontent.com/1232735/32992196-2575ac1e-cd48-11e7-92ad-b718b052fa08.png)

**Comment by rhukster** [comment]
I think for some reason your account yaml for this user is not saved as utf8. Try editing that file directly and resavibf it as a utf8 file.  

Or you could delete the file and have grav recreate it?

**Comment by tealow** [comment]
hm, encoding looks good. Can you reproduce this error?

**Comment by rhukster** [comment]
Nope, never seen this nor seen any report of this.  The only time I see anything related to encoding (usually in pages, not with user) is that the files are encoded in some other format other that UTF8.  As Grav is a file-based system, and UTF8 is standard, this is pretty much the only thing it can be.

**Comment by tealow** [comment]
ok thanks, i will get more into detail and give you feedback.

**Comment by tealow** [comment]
Seems to be some issue on my remote server. Local works fine, FTP file encoding setting is fine.

Thanks for your help!
