### ISSUE TITLE
Text not escaped in title attribute of Notifications

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#1272]
Due to the double quote, the text in the tooltip is truncated.

![notifications](https://user-images.githubusercontent.com/368084/33056022-fc20040e-ce37-11e7-8a5e-a81005fbfb4d.jpg)

**Comment by rhukster** [comment]
This is generated by JS, so i've assigned @w00fz to take a look when he gets a moment.

**Comment by w00fz** [comment]
Done.
