### ISSUE TITLE
*.meta.yaml does not exist, but file is present

### ISSUE THREAD

**Issue by MacGyer** [getgrav/grav-plugin-admin#1275]
Hey guys,

got an issue with media meta files here.

I added an image via "Page Media" on some site. The image shows up, but when clicking the "meta data" button, the Modal states "meta.yaml doesn't exist".

But the meta file is present and readable. I debugged the Media.php (https://github.com/getgrav/grav/blob/cb4147a4bd3572945608d01abb93dfc8f836b6d5/system/src/Grav/Common/Page/Media.php#L146) and the meta file existing check is ok.

![image](https://user-images.githubusercontent.com/2939625/33228969-b734783e-d1c5-11e7-8810-203fb73d1527.png)

![image](https://user-images.githubusercontent.com/2939625/33228996-565a23d2-d1c6-11e7-9973-c0c0cd03e68d.png)

Thanks for help.
Cheers

**Comment by MacGyer** [comment]
Additional information:

Things I tried:
* actually put in some content (`foo: bar`)
* changed the permissions to `0777` for both the image and meta file
* changed the permission to `0777` for the meta file only

The result stays the same: meta file does not exist

**Comment by MacGyer** [comment]
When setting `Auto metadata from Exif` to `Enabled` in the Site config the meta file is being written and all meta information is display correctly.

**Comment by rhukster** [comment]
According to your directory listing the filesize is 0

**Comment by MacGyer** [comment]
@rhukster that's right. The directory listing was from the initial manual file creation.
But even when I put some content into this file, the result did not change (see second comment).

The only time I actually saw the meta data was, when auto exif extraction was enabled in admin plugin.
Every manually created meta file did not get recognised.

**Comment by MacGyer** [comment]
@rhukster thanks for fixing. works like a charm

**Comment by zigojacko** [comment]
I'm getting this problem now. Just says that the filename.jpg.meta.yaml doesn't exist when it does...

**Comment by rhukster** [comment]
Can you provide a screenshot of the  folder in explorer/finder?

**Comment by zigojacko** [comment]
> Can you provide a screenshot of the folder in explorer/finder?

I've actually gone down a different route after speaking with @ricardo118 via your Discord server but the folder contained like:

seo.jpg
seo.jpg.meta.yaml
