### ISSUE TITLE
The parent element on the module page does not change

### ISSUE THREAD

**Issue by asinyayev** [getgrav/grav-plugin-admin#1276]
Hi guys! I have a problem -
When I try to change Parent page in setting changes not save.

structure of my pages:

-HomePage
--modular_1
---sub_modular_1_1
---sub_modular_1_2
--modular_2
---sub_modular_2_1

I try edit  sub_modular_2_1 to change parent on --modular_1 -save, but nothing changes.
( I use grav blueprints for all this pages)
PHP Version  5.6.31
server Apache
Grav v1.3.8 - Admin v1.6.6 
DevTools  v1.0.8

**Comment by rhukster** [comment]
This is a known issue.  You ned to do it in two steps.

**Comment by asinyayev** [comment]
Excuse me, in which 2 steps ?

**Comment by rhukster** [comment]
You can't change the order and the parent at the same time, but changing parent alone should work.
