### ISSUE TITLE
unable to add or delete menu entry on grav

### ISSUE THREAD

**Issue by furbyhaxx** [getgrav/grav-plugin-admin#1277]
In Grav I can't find a way to delete a top level item from the menu editor other than deleting the whole page from the CMS. Also adding a page is only possible when creating a page, so it's not possible to have the same page twice in the menu.

**Comment by rhukster** [comment]
The menu is built from pages.  So even if you want a menu item and no content in a particular item, you still need to create a page, just a blank one.

You can have the same 'text' in the menu by overriding the "Menu" field in the "Advanced" -> "Options"

**Comment by furbyhaxx** [comment]
yeah that's what I mean, I find this annoying but when it's the way it should be it's ok.
But the lack of a the function to delete a menu entry is the problem, I wanna have a page that don't appear in the menu, but this is not possible because it automaticaly add's every page created.

**Comment by rhukster** [comment]
You simply need to toggle the 'visible' option in the page.  This controls whether or not a page shows up in the menu or not.
