### ISSUE TITLE
references to PLUGIN_ADMIN everywhere in the UI (the correct translations are not coming in)

### ISSUE THREAD

**Issue by qikkeronline** [getgrav/grav-plugin-admin#128]
Hi there, somehow since the last update translated strings in the Admin plugin do not display properly anymore. See attached screenshot.
![schermafbeelding 2015-09-01 om 09 59 19](https://cloud.githubusercontent.com/assets/10937470/9598974/45ec4264-5090-11e5-94b9-37227eb12703.png)

Thanks for looking into it :+1:

**Comment by qikkeronline** [comment]
I have cleared the cache by the way :-)

**Comment by flaviocopes** [comment]
@qikkeronline try "Clear all cache" then logout and then login again, does it change?

**Comment by rhukster** [comment]
Logging out and back in should resolve this.

**Comment by patrickwelker** [comment]
I've this problem for a long time. I've also tried "Clear all cache", logged in and out, switched browsers. Anything else I can try?

**Comment by rhukster** [comment]
make sure the admin users' language is set to english (or another supported language).
