### ISSUE TITLE
grav admin screen gets messed up, apparently randomly

### ISSUE THREAD

**Issue by normawhit** [getgrav/grav-plugin-admin#1280]
![screen shot 2017-12-04 at 6 16 55 pm](https://user-images.githubusercontent.com/30988296/33581601-761cbfb2-d91f-11e7-969c-96ef73bf6c08.png)

The top row of buttons (save etc.) is missing.
This happens fairly often on iMAC. It fixes itself also apparently randomly.

**Comment by rhukster** [comment]
That firefox? What version? What plugins do you have running? Try disabling the plugins and see if its something related to that.

**Comment by normawhit** [comment]
This happens fairly often and with many browsers, and it comes and goes away by itself and for many months. I cannot reproduce it. Will try to keep a record of which browser next time.
