### ISSUE TITLE
Feature request: Default language per single page

### ISSUE THREAD

**Issue by phideas** [getgrav/grav-plugin-admin#1282]
It would be nice to have an additional 'default language' selector for every page.
e.g. page1 would open /en/page1 as default and page2 would open /es/page2 as default.
This feature would help multi language site with mixed content and mixed translations.

**Comment by rhukster** [comment]
Hmm.. i'm not sure how this could be accomplished.  Every language has it's own independent `.md` file.  And Grav doesn't actually know about what specific languages a page is translated into at runtime.  It simply knows about the current language, and if that language is not found, it knows about the fallback language. 

As there is no global options for all pages no matter the language, you would have to set this option on every translated page, and keep this in sync.  That sounds cumbersome.
