### ISSUE TITLE
plugins/admin/languages/de.yaml

### ISSUE THREAD

**Issue by krdau** [getgrav/grav-plugin-admin#1283]
There is a typo : »Lengende« to be changed to »Legende« & updated in repo
:
line 571 LEGEND: "Seiten Lengende" --> "Seiten Legende" 

![grav_admin_seiten_verwalten-2017-12-05 22-51-27](https://user-images.githubusercontent.com/14748568/33633369-d93c92a6-da10-11e7-8d8c-9acd7b730db7.png)

**Comment by rhukster** [comment]
Seems this has already been addressed: https://crowdin.com/translate/grav-admin/2/en-de#q=lengen

i will be updating lang strings for admin for the next release

**Comment by krdau** [comment]
Thank you
