### ISSUE TITLE
No update messages anymore

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#1284]
In latest admin 1.6.7:
If you click on check for updates -- no message anymore (e.g no updates available)

**Comment by rhukster** [comment]
I think this is relate to offline gpm PR. I will debug and sort it today.

**Comment by rhukster** [comment]
Fixed in 1.3.10 of Grav.  It was a much wider GPM issue: https://github.com/getgrav/grav/issues/1776
