### ISSUE TITLE
Can't create page or view settings.

### ISSUE THREAD

**Issue by oathorben** [getgrav/grav-plugin-admin#1289]
Grav v1.3.10 - Admin v1.6.7
After i updated  Grav and the Admin Plugin  i'm not able to 

- create a Page 
- view /admin/user-manager/admin
- view /admin/config/system

If i try to do one of the things i get the attached Server Error:
<img width="661" alt="bildschirmfoto 2017-12-08 um 20 17 13" src="https://user-images.githubusercontent.com/2337771/33781672-d61df028-dc55-11e7-9d47-e90040ba7a83.png">

**Comment by rhukster** [comment]
Seems to be coming from the `AdminAddonRevisions` plugin.  You might want to create an issue there: https://github.com/david-szabo97/grav-plugin-admin-addon-revisions/issues

**Comment by oathorben** [comment]
disabled the plugin and everything works fine. thx
I'll post the issue there again.
