### ISSUE TITLE
Update now button needs a confirmation dialog

### ISSUE THREAD

**Issue by qikkeronline** [getgrav/grav-plugin-admin#129]
Hi, a suggestion for a small UI tweak; I feel like the update now button needs a confirmation dialog. It is quite close to the save button when editing a page, and I've had now several times that I pressed the update button by accident.

Thanks for your consideration and kind regards,

Gerben

**Comment by rhukster** [comment]
Hmm there is no update button on page editing view:

![2015-09-07-11-3zv81](https://cloud.githubusercontent.com/assets/1084697/9720950/c85f646e-5550-11e5-9c24-bfb46ed0e5e7.png)

I'm not sure which 'update button' you are talking about?

**Comment by Vivalldi** [comment]
@rhukster I feel this deals with the purple bar that shows up then grav has an update ready.

**Comment by rhukster** [comment]
I don't feel like this Grav update bar should sit around that long, because you really should update ASAP. That's why it annoys you on every page after all.

**Comment by qikkeronline** [comment]
It was indeed related to the purple update bar. I am using grav to setup internal documentation for a product I'm developing, and I do not want to be forced to update at all while I'm in the middle of writing content. 

I think the purple update dialog is a good thing as it gives incentive to update - but that it is so close to the save button is a UX nightmare in my opninion.

**Comment by flaviocopes** [comment]
Added a new option to the Grav Admin plugin to disable automatic checks for updates, will come in the next release :+1:

**Comment by qikkeronline** [comment]
Epic @flaviocopes, thanks!
