### ISSUE TITLE
Themes do not show in admin panel

### ISSUE THREAD

**Issue by baimafeima** [getgrav/grav-plugin-admin#1290]
I've nearly tried everything but the `Themes` section in the admin panel won't show under Plugins as indicated here: https://learn.getgrav.org/admin-panel/themes
I have all admin access levels activated, not sure what is the issue. Admin panel: v1.6.4

**Comment by jgonyea** [comment]
Do you have a custom theme installed?

**Comment by baimafeima** [comment]
This is the configuration that I use: https://demo.frama.site/

**Comment by SansPseudoFix** [comment]
> Do you have a custom theme installed?

Actually, there is one theme and no choice. And it's not the right repo to report this issue :)

@baimafeima please, see https://framagit.org/framasoft/framasite-grav/issues if you have issues with frama.site.

**Comment by rhukster** [comment]
It only shows installed themes.

**Comment by SansPseudoFix** [comment]
> It only shows installed themes.

Yes. I'm one of the admins, and we don't allow theme installation (it will be possible to choose between 3 or 4 themes, later).

It's not a grav issue, but an frama.site restriction :)

**Comment by baimafeima** [comment]
Yeah, please close this issue. As @SansPseudoFix has indicated, this is a local frama.site restriction but not an issue with grav itself.

**Comment by hellocam** [comment]
This just happened to me today with a custom theme on Admin Panel v 1.6.7.  I used to be able to just add a theme into the themes folder and it'll show up.

**Comment by baimafeima** [comment]
@SansPseudoFix Just wondering whether the theme variability has been implemented on your side?

**Comment by SansPseudoFix** [comment]
@baimafeima as already mentioned [above](https://github.com/getgrav/grav-plugin-admin/issues/1290#issuecomment-351022395), **this is not the right place to ask about our service**. We don't know when/if it will be allowed but you can use CustomCSS plugin.
