### ISSUE TITLE
Bug with modular creation ( choice page )

### ISSUE THREAD

**Issue by asinyayev** [getgrav/grav-plugin-admin#1292]
Hi guys,

Here is an issue appeared while creating a new modular :

1. Add a new Parent Module (Test Section).

2. Add a new sub module which is related to previous  Parent module “Test Section”. So select for “Page” setting: “Test Section”

3. Select a Modular Template - http://prntscr.com/hpkyju

4. Now select the “Page” setting again.
And here is by clicking on the already selected item (Test Section) the "Add Modular Content" window is closed
http://prntscr.com/hpkzqx

How can it be fixed so the window isn't closed when clicking again on the same modular name ?

**Comment by rhukster** [comment]
I can't replicate this, what browser are you using?

**Comment by jleaders** [comment]
I get this bug all the time, even with the latest grav. I'm on firefox typically, on Linux. 

It happens on any theme, any page. When i change the parent or the page type, it closes the selection window. 

Good news is, if i click Add Page again, my changes persist as if the window never closed, so i continue on my merry way

**Comment by rhukster** [comment]
Duplicate? https://github.com/getgrav/grav-plugin-admin/issues/1682
