### ISSUE TITLE
DISPLAY BUG: Field override routable and override visible

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav-plugin-admin#1297]
Toggle off those fields save the correct header in `*.md` but the toggle button always display true.

This is pretty confusing when it's false in `*.md` and show the contrary in admin !

<img width="1855" alt="screen shot 2017-12-23 at 07 00 29" src="https://user-images.githubusercontent.com/10623367/34317472-e9aa75e8-e7af-11e7-99ee-9ee521605cd8.png">

**Comment by rhukster** [comment]
![default md enregistre 2017-12-27 14-05-35](https://user-images.githubusercontent.com/1084697/34393355-0d2aae90-eb0f-11e7-9272-2c97008ec507.png)

Seems to work for me.  Try a fresh Grav installation.

**Comment by rhukster** [comment]
BTW, you seem to have a custom blueprint as you have quite a few overrides missing. Might be related to this.

**Comment by jimblue** [comment]
Indeed I'm using a custom blueprint... Do you need it?

**Comment by jimblue** [comment]
I don't think the problem come from what's inside my custom blueprint.

If you copy the system default blueprint content and put it in a custom blueprint the bug remain.

**Comment by jimblue** [comment]
To help you replicate this bug, create a `yourpagetemplate.yaml` corresponding to a page template of your choice. Save this file in `user/themes/yourtheme/blueprints`.

Then copie the content of `system/blueprints/pages/default.yaml` inside `yourpagetemplate.yaml`.

In the admin you should be able to see the problem explain on this issue.

**Comment by jimblue** [comment]
I've been able to replicate it over different installation. I think you can change the tag of this issue to BUG for future seek.

**Comment by jimblue** [comment]
Hello @rhukster!

Have you been able to replicate this BUG?

Cheers

**Comment by jimblue** [comment]
Ok found the solution, my yaml formater was changing order of `enable` and `disable`.
Because of that it was no in the same order as it should in Grav which is first `enabled` then `disabled` like this:

```yaml
'1': PLUGIN_ADMIN.ENABLED
 '0': PLUGIN_ADMIN.DISABLED
```
