### ISSUE TITLE
Problem adding pages on main menu

### ISSUE THREAD

**Issue by b4r0n** [getgrav/grav-plugin-admin#1300]
Hi there, i'm trying to add some pages to main menu, i readed here that when you create a page it automatically adds to menu, but that's not my case, so searching i found a post that only have tu mark and override menu, visible, but it don't work, and have 3 annoying menu items that i can't delete neither modify to match with my pages. Any suggestion please?

Forgot to say that i'm using "soraarticle" theme.

Thanks in advance.

**Comment by rhukster** [comment]
Per the docs (https://learn.getgrav.org/basics/basic-tutorial#content-basics) any page with a numeric prefix is visible by default.  Does the page you created have a numeric prefix?
