### ISSUE TITLE
Editor Fullscreen broken Admin Beta 1.7.0-beta1

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#1302]
Normal view:

![editor1](https://user-images.githubusercontent.com/12480617/34448077-9c4cd3be-ecea-11e7-9d5e-76418058d230.png)

Fullscreen view:

![editor2](https://user-images.githubusercontent.com/12480617/34448087-aac3da5a-ecea-11e7-9da4-f18e303c5844.png)

Browser Firefox 57.0.3

**Comment by rhukster** [comment]
ah good catch, will check that out.
