### ISSUE TITLE
Background missing on admin account creation form

### ISSUE THREAD

**Issue by jgonyea** [getgrav/grav-plugin-admin#1307]
Unless it was intentional, the background color is missing on the admin account creation form.

![167](https://user-images.githubusercontent.com/1057441/34576035-a9cc3c82-f14a-11e7-8f43-a60d35e019d7.JPG)

vs 

![170b](https://user-images.githubusercontent.com/1057441/34576036-aab6ae0c-f14a-11e7-959d-76e261d8a23f.JPG)

**Comment by rhukster** [comment]
Thanks.
