### ISSUE TITLE
Images with parentheses in filename don't work

### ISSUE THREAD

**Issue by jpfleury** [getgrav/grav-plugin-admin#131]
Config: Grav 0.9.40, Admin Panel 0.4.3

In the Page Media area, if we upload an image containing parentheses in the filename (example: `image (2)@3x.jpg`), then click *Insert*, the Markdown code inserted is: `![](image%20(2).jpg)`.

It doesn't work because parentheses are not urlencoded. However, it doesn't work either even if we manually urlencode them: `![](image%20%282%29.jpg)`.

**Comment by flaviocopes** [comment]
Recreated, you're right. @rhukster should we solve this by encoding blank urls in the filename upon upload?

**Comment by rhukster** [comment]
I think urlencoding might be the best option.
