### ISSUE TITLE
Automatically set date when creating a blog item

### ISSUE THREAD

**Issue by Tamriel** [getgrav/grav-plugin-admin#1310]
By default blog items have a title and text content, but no date attribute. They are sorted by date, which defaults to the modification date of the file.
I recently restored a backup of the folder `user/pages`. Since the modification date of the files changed, the blog items where in the wrong order.
To solve this behaviour, I suggest that the attribute `date` is automatically set when new blog items are created.

**Comment by jgonyea** [comment]
Hi @Tamriel. Would the auto-date plugin do what you're looking for?

**Comment by Tamriel** [comment]
Great, thanks!
