### ISSUE TITLE
grav.CRITICAL: Call to undefined function ZendXml\simplexml_import_dom()

### ISSUE THREAD

**Issue by seffyroff** [getgrav/grav-plugin-admin#1312]
On a fresh install after adding admin user and arriving at the admin dashboard, the newsfeed is not working.  Screenshot:
![image](https://user-images.githubusercontent.com/8338529/34791995-81d9fde4-f5fb-11e7-8ff8-4d290189e688.png)

[Grav log entry](https://gist.githubusercontent.com/seffyroff/acddd1050be90aca40237a2bbf8d2323/raw/7f90de627b38f5e0e3b2d76b15ae31f43f75efb1/grav.log) for this error.

I'm running Grav inside [abiosoft/caddy:php](https://github.com/abiosoft/caddy-docker/tree/master/php) Docker container on a local server.  Grav is pulled from git by Caddy on startup, and then executes the grav installer and standard permissions fix from the Grav documentation.

**Comment by rhukster** [comment]
As mentioned, this is a PHP configuration issue.  simplexml is included by default when PHP is built with XML support.  You might need to install a special `php-xml` package to your docker container to ensure you have it.

**Comment by seffyroff** [comment]
sorted, thanks.  I added the php7-simplexml apk and everything works now!
