### ISSUE TITLE
Admin in multisite setup

### ISSUE THREAD

**Issue by unmick** [getgrav/grav-plugin-admin#1315]
Hello !

The main site is well working .
The subdomain is also working except the admin plugin.

I have a "array_map(): Argument #2 should be an array"  on line 500 of the /user/plugins/admin/admin.php

```php
$fa_icons_file = CompiledYamlFile::instance($this->grav['locator']->findResource('plugin://admin/themes/grav/templates/forms/fields/iconpicker/icons' . YAML_EXT));
        $fa_icons = $fa_icons_file->content();
        $fa_icons = array_map(function ($icon) {
            //only pick used values
            return ['id' => $icon['id'], 'unicode' => $icon['unicode']];
        }, $fa_icons['icons']);"

I have tried to add some path ( assets, config) in my setup but i have always got  the same message.
Extract of the setup.php :
"return [
    'environment' => $environment,
    'streams' => [
        'schemes' => [
            'user' => [
               'type' => 'ReadOnlyStream',
               'prefixes' => [
                   '' => ["user/{$folder}"],
               ]
            ],
            'plugins' => [
                'type' => 'ReadOnlyStream',
                'prefixes' => [
                    '' => ["user/plugins"],
                ]
            ],
            'themes' => [
                'type' => 'ReadOnlyStream',
                'prefixes' => [
                    '' => ["user/themes"],
                ]
            ],
            'cache' => [
                'type' => 'ReadOnlyStream',
                'prefixes' => [
                    '' => ["user/{$folder}/cache"],
                ]
            ]
        ]
    ]
];
```

Thanks

**Comment by rhukster** [comment]
It's a known issue that the admin is not fully multisite compatible.  This is something we hope to remedy in the future.

**Comment by unmick** [comment]
I have just duplicated the folder admin :
/domain/user/sites/subdomain/plugins/admin
and surely handle the folder config :
/domain/user/sites/subdomain/config

All is working ! except the uploaded files as the image .....
The system always save the image to the /domain/user/themes/gateway/img instead of /domain/user/sites/subdomain/themes/gateway/img

Following this, a subsidiary question a little bit out of scope : 
Is there a way to give a destination depending on if it's a "settle site" or the subdomain ?
main site : destination: 'user/themes/gateway/img'
subdomain : destination: 'user/sites/"subdomain"/themes/gateway/img'

something like destination: 'site@:/img' ? or with the streams ?

**Comment by bypper** [comment]
Can we solve with symbolic links?
If we store all themes in general folder, and then set symbolic links from multisites that we want use this theme...
I think we have all funcionality, perhaps...

**Comment by mahagr** [comment]
If you have all the streams set up correctly for the site, admin should be working just fine. I've been using multi-site setup for some of my testings.

**Comment by ironbrunet** [comment]
Was this ever looked at ? Having the same issue as above
