### ISSUE TITLE
Mutated vowels display as a "�" if text is truncated

### ISSUE THREAD

**Issue by Elrathor** [getgrav/grav-plugin-admin#1316]
To produce this behavior, I did the following:
1. Create a Blog Page which displays the list of posts
2. Create a Blog Item page containing over 300 characters with some umlauts
3. Navigate to the list of Blog Items.

The text summary of the post now displays a "�" instead of the wanted result. It's not happening, if preview of the post isn't truncated by the template engine and has therefore less than 300 characters.

# Tested environment:
* Browser: Not important because the raw data from the server already contains the charackter
* Server: SunOS localhost 5.10 Generic_150401-49 i86pc
* PHP Version: 7.0.0, 7.1.14, 7.2.1
* Grav Versions: 1.4.0-rc.1 and 1.3.10
* Installed Plugins: Admin Panel, Auto Date, Data Manager, Email, Error, Form, Login, Markdown Notices, PreCache, Problems, Gantry 5 Framework
* Testet Themes: Helium, Afterburner2

# Example

How it is:
> Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder w�nscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zuf�lligen Umst�nden, in denen M�hen und Schmerz ihm gro�e Freude bereiten k�nnen. Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender k�...

How it should be:
> Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können. Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender kö...

# Image
![bug](https://user-images.githubusercontent.com/7289590/35245471-d5becd6e-ffc3-11e7-8d03-3df07d14c22b.png)

**Comment by Elrathor** [comment]
Additional information - The "phpinfo()" dump of the server: 
[phpinfo().pdf](https://github.com/getgrav/grav-plugin-admin/files/1653639/phpinfo.pdf)

**Comment by rhukster** [comment]
Hmm.. I don' think it's an admin issue, nor a Grav core issue. I can use the `page.summary` to output german just fine in my theme on Grav 1.4-rc.1. I think it might be related to Gantry or the theme itself. Can you please test with the default theme.

**Comment by Elrathor** [comment]
I removed the Gantry content (Helium Theme + Framework Plugin) completely and tried the Antimatter as well as Quark Theme. The bug sadly stays.

Now the only content installed on the server is content from the Grav Team.

![image](https://user-images.githubusercontent.com/7289590/35294762-ac0cd362-0077-11e8-92e4-7bd9455c23bc.png)
