### ISSUE TITLE
z-index again

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#1317]
latest admin rc-1.
going to pages-menu-add:
normal view:
![bildschirmfoto_2018-01-22_22-28-14](https://user-images.githubusercontent.com/12480617/35245482-d8ec255e-ffc3-11e7-921c-9db407dcafc1.png)

fullscreen view:
![bildschirmfoto_2018-01-22_22-28-42](https://user-images.githubusercontent.com/12480617/35245500-e585883c-ffc3-11e7-890d-f5eea0ab0cd5.png)

**Comment by rhukster** [comment]
Ugg. fix  z-index issue, and it causes another

**Comment by rhukster** [comment]
fixed in feature branch
