### ISSUE TITLE
Add a link to a 'call to action' button - using 'The Pages Field'

### ISSUE THREAD

**Issue by Genenenenaam** [getgrav/grav-plugin-admin#1318]
**Story**: 
A user can select a page from a dropdown and the url of this page will be used as the 'href' of a call-to-action.

**Usecase**: 
A Call-to-action on the home-page that links to a landing-page that was selected from the dropdown.

**Probleme**:
I'm using ' [The Pages Field](https://learn.getgrav.org/forms/blueprints/fields-available#the-pages-field) ' from the Grav documentation to get this done. But i can't seem to get the full url.

If i selected the _contact page_, i can use the twig variable '_{{ header.home.alias }}_' wich gives me the value: '_localhost/contact_' wich is incorrect.

In my multi-language setup it should look like: `http://localhost/<your-folder-name>/<language>/contact`

**Question**:
Is there an example of how to get this to work?

Thanks

**Comment by rhukster** [comment]
I'm a bit confused.. you have a field that is set by the page's field.  That should result in a page **route** being set.  Something like `/contact`.

Then to get that converted into a URL you can use the Twig `url()` function.  If you had this set in your page header as:

```
home:
  alias: `/contact'
```

Then you could do something like this in your Twig to output the full URL:

```
{{ url(page.header.home.alias) }}
```
