### ISSUE TITLE
What controls the child page order in 'Manage Pages'

### ISSUE THREAD

**Issue by ThosG** [getgrav/grav-plugin-admin#1319]
I have a list of composers and I expected them to come up in title order, but they're coming up in the order of their full name - see screen snap. 

![image](https://user-images.githubusercontent.com/11003463/35327629-034b7b0e-00f2-11e8-8e29-f59fc030f6e4.png)

How can I make them come up in title order?

My yaml file:

    title: Composer

    form:
      fields:
        tabs:
          type: tabs
          active: 1

          fields:
            item:
              type: tab
              title: Form for Composers

              fields:
                header.title:
                  type: text
                  label: Short composer name, eg 'Blow'
                  validate:
                    required: true

                header.full_name:
                  type: text
                  label: Full name, eg 'John Blow, (1649-1728)'
                  validate:
                    required: true
          
                header.bio:
                  type: editor
                  label: Composer biography etc

**Comment by rhukster** [comment]
![screen shot on 2018-01-30 at 13 35 35](https://user-images.githubusercontent.com/1084697/35589901-79ab3a9e-05c2-11e8-8fc9-b1208005f799.png)

This can override the default order (it's at the bottom of the parent's advanced tab)
