### ISSUE TITLE
Wrong file size for responsive images

### ISSUE THREAD

**Issue by jpfleury** [getgrav/grav-plugin-admin#132]
Config: Grav 0.9.40, Admin Panel 0.4.3

In the Page Media area, if we upload a responsive image, the file size displayed under it is wrong. Example:

![capture d ecran_2015-09-02_03-49-11](https://cloud.githubusercontent.com/assets/687082/9625646/be6db4bc-5125-11e5-9b6d-a0cc25946be1.png)

Both images are identical. The first is named `image.jpg`, the second is named `same-image-but-responsive@3x.jpg`.

**Comment by flaviocopes** [comment]
I inspected it. What happens is that if you upload a 3x image, Grav automatically generates the corresponding 1x and 2x images in its cache. 
The filesize is always relative to the 1x image, so that's why it's shown with a different size.

**Comment by jpfleury** [comment]
OK, I see.

**Comment by jpfleury** [comment]
For the record, it's clear that the filesize is relative to the @1x image when we enable *Image debug watermark* in *Admin / Configuration / System / Media*. Example:

![capture d ecran_2015-09-03_19-00-29](https://cloud.githubusercontent.com/assets/687082/9673040/2571b318-526e-11e5-8a9e-b1da16596aa1.png)
