### ISSUE TITLE
Selectize field overlaps submenu of "Add" menu

### ISSUE THREAD

**Issue by lordrhodos** [getgrav/grav-plugin-admin#1320]
I am using Grav v1.4.0-rc.1 - Admin v1.7.0-rc.1 and the Quark theme 1.0.1 with Firefox quantum 

The submenu of the "add" menu disappears behind a selectize field, which I came across in the **Blog Config** tab of the quark theme.

![screenshot-tobaccotrail dev-2018-01-24-17-17-29](https://user-images.githubusercontent.com/807902/35343272-8937de00-012a-11e8-9947-ebb957633c6e.jpg)

**Comment by rhukster** [comment]
![screen shot on 2018-01-24 at 09 32 25](https://user-images.githubusercontent.com/1084697/35344160-a4ebc1d4-00e9-11e8-8771-712d871da1d3.jpg)

I think i fixed this yesterday.  Can you please test with the latest version in `features/1.7` branch of admin plugin?

**Comment by lordrhodos** [comment]
@rhukster Yes it is fixed in the current branch `features/1.7` !
