### ISSUE TITLE
Dropping images into page broken:  Safari / Admin v1.7.0-rc.2 Grav 1.4.0.rc.1

### ISSUE THREAD

**Issue by MattAppleton** [getgrav/grav-plugin-admin#1323]
If I try and drop an image into a page (using up-to-date Safari browser) I get no response (image simply does nothing) and this error in the console...

TypeError: e.map is not a function. (In 'e.map(function(e){return t.addFile(e)})', 'e.map' is undefined)

http://dgpr:8888/grav-admin/user/plugins/admin/themes/grav/js/vendor.min.js?7d37c4d3eb

**Comment by rhukster** [comment]
I've rolled the JS back to a known-working combination.

**Comment by iamlinkus** [comment]
Just updated admin to v1.7.2 and this bug still exists. What can I do about it?
