### ISSUE TITLE
[Display BUG] Dropdown out of windows

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav-plugin-admin#1325]
Hi,

Dropdown are actually all align to the left of a the parent button.

Because of this, when a dropdown button is on the right border the dropdown, this can happen:

<img width="396" alt="screen shot 2018-01-31 at 01 56 51" src="https://user-images.githubusercontent.com/10623367/35599786-c50174fa-062a-11e8-9426-4da518726c8b.png">

A quick is to add a new dropdown class to change the alignement.

**Comment by jimblue** [comment]
An other exemple:

<img width="607" alt="screen shot 2018-01-31 at 02 05 42" src="https://user-images.githubusercontent.com/10623367/35599875-4b3b3038-062b-11e8-8fea-8c442933650e.png">

**Comment by rhukster** [comment]
This commit should fix both of those, and any other ones.

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-admin/commit/07e4ca39d9a89925756d5057498c7fa7d651a3d6

**Comment by jimblue** [comment]
Thank for your fast answer!
I saw you used `last-child` to fix this issue.
Sadly it's not enough to fix all other ones.

<img width="395" alt="screen shot 2018-02-01 at 02 12 55" src="https://user-images.githubusercontent.com/10623367/35656108-bd12b602-06f5-11e8-8917-b1c59172eafa.png">

Why not align item to the right of parent button when they are on the right side of the screen?

**Comment by jimblue** [comment]
A `dropdown.is-right` and a `dropdown.is-left` class could ne added to handle this.

**Comment by jimblue** [comment]
can we re open this please?

**Comment by jimblue** [comment]
can we re open this please?

**Comment by jimblue** [comment]
I just saw you added this as fix in the last `changelog` of `feature/1.7`.
It's better indeed but not really resolved.

Could you please re open this?
