### ISSUE TITLE
[Feature request] Add multilingual support for custom dropdown

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav-plugin-admin#1326]
As seen here, multilingual is not currently supported for custom modal dropdown.

https://github.com/getgrav/grav-plugin-admin/blob/80a4649d5f3e39471ce7d6871c48473baa042306/themes/grav/templates/pages.html.twig#L147

**Comment by rhukster** [comment]
Please sumbit a PR on `feature/1.7` branch.

**Comment by jimblue** [comment]
Hey @rhukster I tried to found a solution without 100% success.
Provide multilingual support is easy as changing `{{ add_modal.label }}` to  `{{ add_modal.label|t }}` but this will be a breaking change... I'm not sure you want to do that?

I don't know if there is an other solution

**Comment by jimblue** [comment]
Fixed by #1388
