### ISSUE TITLE
Home page missing title is unclickable

### ISSUE THREAD

**Issue by zoof** [getgrav/grav-plugin-admin#1327]
Using the default Antimatter theme and the original home page edited for my own purposes, the "pages" sidebar tab lists the pages in the main panel but the "home" page has no link.  This seems to be only true of the "home" page.

**Comment by rhukster** [comment]
screenshot?

**Comment by zoof** [comment]
Sure: https://imgur.com/IwCLzHd

**Comment by rhukster** [comment]
Is the configuration `system.yaml` still set up to point to the correct page, and does that page actually exist or did you delete it?

**Comment by zoof** [comment]
Yes, that is all as before.  I had deleted the page title and noticed the missing link.  When I replace the page title, the link reappears.  I.e., the problem occurs when the title field is empty.  Seems particular to the "home" page.  I deleted the "title" field from another page and the link was still there.

Perhaps the "title" field for pages should be made mandatory?  I had deleted it initially as I was still learning my way around grav because I mistakenly believed that "Home" would show up in large text on the page.

**Comment by rhukster** [comment]
It actually works fine for me if I remove the title of Home.  There must be something else going on.

**Comment by zoof** [comment]
Strange.  Is there any way to have grav provide debugging output in `grav.log`?

**Comment by zoof** [comment]
I've turned on debugging but I'm not seeing anything useful.

**Comment by rhukster** [comment]
Can you please test again with the grav+admin package and outline the exact steps you make so I can replicate?

**Comment by zoof** [comment]
1. Click on admin/pages
2. Click on the "Home" page
3. Delete the text from the "Title" field
4. Save page
5. Click on admin/pages to reveal no active link for "Home" as with the prior screenshot.

It is running on a Centos 7 VPS with apache from epel and php7.0 from the ius repositories.

**Comment by mahagr** [comment]
Looks like this has been fixed at least in Admin 1.10.
