### ISSUE TITLE
Error after removing the photo

### ISSUE THREAD

**Issue by m-ochyra** [getgrav/grav-plugin-admin#1328]
I have an error in admin/themes/grav/templates/media-list-content.html.twig file:
An exception has been thrown during the rendering of a template ("Creating default object from empty value").

![pobrane](https://user-images.githubusercontent.com/5583015/35648076-cb8dc490-06d4-11e8-9789-9364e323a9e8.png)

How to reproduce:
- create new page
- add png photo into Page Media section
- save page
- delete previously added photo
- save page
- get the error

**Comment by rhukster** [comment]
I can't replicate this.. I tried deleting the file via the admin as well as in the filesystem.  I'm able to save the page no problem after deleting it.  I tested this on Admin 1.6 as well as 1.7RC.

**Comment by rhukster** [comment]
Ok this seems to be related to mediapicker field.  Can you provide me a sample of how you are using this field?  It's not used in the default Grav stuff, so must be a custom blueprint.

**Comment by rhukster** [comment]
Actually tracked it down... Was that mediapicker field.  The fix, however, does require a new method in Grav, so I've added that in Grav 1.4 repo: https://github.com/getgrav/grav/commit/08be06c9bc86344713d198149249d7279c98ad20

And also a fix to the field to use this check: https://github.com/getgrav/grav-plugin-admin/commit/4b415851222f2b37ef38f7e6d942a24225bc5deb

**Comment by m-ochyra** [comment]
Thank you so much.
