### ISSUE TITLE
TypeError when uploading an image with unicode filename

### ISSUE THREAD

**Issue by yurkobb** [getgrav/grav-plugin-admin#1329]
When uploading a new image to a page, the image is displayed in the "page media" block in the admin, however clicking on the eye icon to view it points to `http://localhost/undefined`. In the browser's console I see this:
> TypeError: t.dropzone.files.filter(...).shift(...) is undefined

EDIT: The error appears only on images with unicode filenames (like `тест.jpng`) when hovering over the image's action icons. Probably related to #1330.

Grav v1.3.10 - Admin v1.6.7
PHP Version 7.1.13

**Comment by rhukster** [comment]
Ok, this does appear to be an issue with unicode specific filenames.
