### ISSUE TITLE
Can't attach images with unicode filenames

### ISSUE THREAD

**Issue by yurkobb** [getgrav/grav-plugin-admin#1330]
1. Create an image titled `тест.jpg`
2. Add it to a page, click save;
3. The image disappears from the list of page media despite being present in the pages directory.

The same procedure with `test.jpg` works fine.

Probably related to #1329.

Grav v1.3.10 - Admin v1.6.7
PHP Version 7.1.13

**Comment by rhukster** [comment]
Duplicate issue. #1329

**Comment by tcyrus** [comment]
Having the same issue, the file also doesn't show up under `page.media` in twig.

Grav v1.4.2 - Admin v1.8.5
PHP Version 7.0.30

**Comment by tcyrus** [comment]
Changing `$info->getBasename()` to `$info->getFilename()` fixed this for me. This issue should probably be raised in the main repository (getgrav/grav)
