### ISSUE TITLE
Won't let me add a new page

### ISSUE THREAD

**Issue by Brittanymayb** [getgrav/grav-plugin-admin#1332]
I'm trying to write a blog post however it won't let me add a page at all and comes up with a HTML error message

**Comment by rhukster** [comment]
What specifically is the message?  Also what version of Grav + Admin are you running, and what platform?  Cheers.

**Comment by mahagr** [comment]
Not knowing anything about the issue, mod_security is something that tends to block form submissions on random text because of it thinks that the text contains SQL attack.
