### ISSUE TITLE
How do I create a form for the user to enter multiple email addresses 

### ISSUE THREAD

**Issue by isaacandy** [getgrav/grav-plugin-admin#1336]
How do I create a form for the user to enter multiple email addresses & sends out to all the recipients when submitting the form  ?

here's what I've done, but i'm still able only to successfully send out the email to the recipient if there's one email address stated. i thought we're able to send out email by stating recipient's email abd@domain.com,123@domain.com,999@domain.com ?

form:
    name: 'Boardroom Scheduler'
    fields:
        -
            name: emaillist
            id: emaillist
            classes: 'form-control form-control-lg'
            label: 'Email list'
            placeholder: 'Enter Invitee email address (use comma after each email)'
            type: text
            validate:
                rule: email
                required: true
        -
            name: roomid
            label: 'Room ID'
            placeholder: 'Create your meeting id'
            type: text
            validate:
                required: true
        -
            name: schedule
            type: date
            label: 'Enter a date'
            validate.min: '2014-01-01'
            validate.max: '2018-12-31'
            placeholder: 'Enter the Date of Your  Meeting'
            validate:
                required: true
        -
            name: schedule-time
            type: time
            label: 'Enter schedule time'
            placeholder: 'Enter the Time of Your  Meeting'
            validate:
                required: true
        -
            name: message
            label: Message
            classes: 'form-control form-control-lg'
            size: long
            placeholder: 'Enter a Description of the Meeting'
            type: textarea
            validate:
                required: true
    buttons:
        -
            type: submit
            value: Submit
            classes: 'btn btn-primary btn-block'
    process:
        -
            email:
                from: '{{ config.plugins.email.from }}'
                to: ['{{ grav.user.email }}', '{{ form.value.emaillist }}']
                subject: '[Boardroom] {{ form.value.meetingid }}'
                body: '{{ grav.user.fullname }} has invited you to attend Boardroom Meeting. Please find the details: {% include ''forms/data.html.twig'' %}. Please login to your Boardroom account to attend the Boardroom Conference at http://web.boardroom.work/join-meeting '
        -
            save:
                fileprefix: 'Meeting Invite - {{ grav.user.email }}'
                dateformat: Ymd-His-u
                extension: txt
                body: '{% include ''forms/data.txt.twig'' %}'
        -
            message: 'Your Appointment has been Sent to the respective receipients'
        -
            reset: true

**Comment by rhukster** [comment]
you need to have each item as an array item.. you can't have a comma separated list of email addresses as a single array item.
