### ISSUE TITLE
grav admin plugin using fonts without UTF-8 support

### ISSUE THREAD

**Issue by 07pepa** [getgrav/grav-plugin-admin#1339]
I There is problem with used fonts in grav expecialy with central and eastern europe languages using Standard latin letters with few additions.
I noticed it on czech leters like "ěščřžýáíéúůťň" in lower case but i susped their uppercase version is same story.

Problem is that browser will always fall back to some other font that it have for that letter.
With proper font it should not happen.  PS there are [Czech language able royalty free font if you are looking for them](https://www.ceskefonty.cz/ceske-fonty)

**Comment by rhukster** [comment]
In the new RC version of Grav (1.7.0) we've defaulted to turning off Google Fonts and just using system fonts.  This should resolve issues like this where the Google Fonts have limited UTF-8 or Cyrillic support.

In the current version however, you can disable Goolge fonts via the Admin Plugin options and things should work better for you.
