### ISSUE TITLE
Default onPageNotFound priority should be -1

### ISSUE THREAD

**Issue by Flamenco** [getgrav/grav-plugin-admin#1340]
Default onPageNotFound priority should be -1 or less.

This will allow other plugins to set the priority to 0 and still be called when they are loaded after the default fallback.

**Comment by rhukster** [comment]
I 'think' you are talking about the priority in the Error plugin specifically?

https://github.com/getgrav/grav-plugin-error/blob/develop/error.php#L19

This is really not an admin plugin issue is it?

**Comment by Flamenco** [comment]
I did not realize that file was in a plugin.  Yes, it is the Error plugin.

**Comment by Flamenco** [comment]
https://github.com/getgrav/grav-plugin-error/issues/30
