### ISSUE TITLE
New page creation needs validation for duplicates

### ISSUE THREAD

**Issue by hugoaf** [getgrav/grav-plugin-admin#1347]
Lets say you currently have pages like:
```
pages/test-1
```
If you try to create a new page with the name `Test 1` in the same parent folder, Grav will not check if the @slugify path folder exists, it will just open the current matching page for edit.

**Comment by replayshot** [comment]
I'd have to agree that this seems like it should be baked in. There should be no duplicate slugs. Any plans on adding this?

**Comment by mahagr** [comment]
To be honest, I think this is a bug.
