### ISSUE TITLE
After saving the page site shows some error.

### ISSUE THREAD

**Issue by geogeorgejoseph** [getgrav/grav-plugin-admin#1348]
After saving the page site shows some error.( unable to allocate memory for pool)

![capture](https://user-images.githubusercontent.com/25584016/36435993-1da5c8b8-1689-11e8-8f0d-68f68da03eb9.PNG)

**Comment by rhukster** [comment]
It's a problem with your APC setup on your server.  Seems like it's out of memory.  You can try switching to filesystem for the caching in `system.yaml` rather than letting Grav choose the best option (APCu) in your case
