### ISSUE TITLE
Site doesn't work after Switching theme

### ISSUE THREAD

**Issue by mohsinkh** [getgrav/grav-plugin-admin#1350]
Hi, I have freshly installed Grav with  "Cacti  v1.3.0" theme. And the site was working fine. Please note that I have also installed the GUI Admin.
Now when I install new theme, it gets installed successfully. But when I activate the new theme, the site homepage stops loading. Although the Admin GUI continues to work. When I switch back to " Cacti  v1.3.0" theme, the homepage starts working fine again.
I have installed it with 2-3 themes, the situation persists.
My site is http://historian.pk - right now it is working fine with "Cacti  v1.3.0"  theme.

**Comment by andrewd72** [comment]
If the themes don't use the same templates for the pages you already have it'll break.
Pages might be default.md on one theme and something else on the other, I use item.md for posts and blog.md for indexes. Turn the debugging on and see what the error is.

**Comment by mohsinkh** [comment]
@andrewd72  thanks - then what is the ideal work around (from following options), if I need to switch the theme ?
1- I delete all the pages that came with Cacti theme ? And create new pages with new theme
2- Reinstall Grav, with a new Skeleton, without re-installing Admin plugin etc. ?
 
[Question] Shouldn't the new theme, create new compatible pages itself or something similar. Because this suggests that a person should plan very carefully the scope of site, before choosing a skeleton.

**Comment by andrewd72** [comment]
Maybe Option 3 - Use the new templates by either have to rename the templates or rename the pages .md files. The data that is read from the frontmatter of each might not be compatible though. 
The themes that come from a common source might be more compatible with each other but those made by different people probably won't be. 
Starting with the nearest theme to what you'd like and tweaking the templates  till you have exactly what you want is probably advisable. 
It looks like you've got a lot of dummy content at the moment so starting with a new skeleton shouldn't be too bad?

**Comment by mohsinkh** [comment]
Yes, the site is just a hobbyist project, i will try installing a new skeleton.
Thanks for your guidance.

**Comment by mohsinkh** [comment]
However, I suggest that it should be added in Grav basic documentation that choosing a skeleton carefully is an important/different decision, it is not like selecting themes in wordpress.

**Comment by andrewd72** [comment]
Wordpress has "pages" and "posts". Not as flexible but every theme will do something with them. 
But not every wordpress theme has the same widgets, the same site building tools, the same javascript. I lost the bio section updating a wordpress theme to the newer version of itself! The layout pretty much always breaks changing theme. 
To get that level of "switchablity" in grav might be a matter of renaming the .md files to match the theme's template names.   
Some grav theme consistency guidelines in template names might be useful but, for example, a one page site theme doesn't need a blog or blog-post template. A modular business page might have a pricing modular template but why does that need to exist for a casual blog?
There is some help via the plugins, for example any theme referencing the pagination plugin for a blog listing should use the same pagination template. 
As you keep your content in folders and files then using that data without worrying about transferring a database should be simpler than moving a wordpress install. 

Adding "when switching themes be aware that the new theme might not have the same templates available" wouldn't be a bad idea here:
https://learn.getgrav.org/themes/theme-basics
With debugging turned on, it will tell you the template isn't found, that plus reading the docs should get you there. 
Hope that helps, perhaps join the getgrav.slack.com channel if you haven't done so already.

**Comment by mohsinkh** [comment]
@andrewd72 - The suggestions that you presented here, is what I actually intended in my previous comment. I really appreciate you taking time in discussing all this I am not a developer, but just a blogging/IT enthusiast, would you think joining slack channel will have any benefit ?

**Comment by andrewd72** [comment]
Its free to join. The #general channel should be able to answer your questions, the #notification channel was the only reason I saw your post here. 
I'm just a small business owner that decided I wanted more speed and control than I got from my old Wordpress site. An accidental developer if you like.
