### ISSUE TITLE
[feature] Add clear cache action to top of sidebar

### ISSUE THREAD

**Issue by Flamenco** [getgrav/grav-plugin-admin#1353]
It would be nice if there was a clear cache icon accessible from all admin pages in the sidebar.

Maybe refactor code from TNT and put it in the same container.

<img width="289" alt="screen shot 2018-02-25 at 11 38 04 am" src="https://user-images.githubusercontent.com/819940/36643931-5cc1ee60-1a20-11e8-9f14-f1191d6ef06c.png">

**Comment by rhukster** [comment]
so a simple clear cache, not with the dropdown options of the main one.

**Comment by Flamenco** [comment]
Yes, the default will be just fine.  It seems like the right place for it.  I find myself going to the dashboard often, just to clear the cache.

**Comment by rhukster** [comment]
Added in 1.7
