### ISSUE TITLE
Some warning messages when downloading xlsx files from the grav site 

### ISSUE THREAD

**Issue by geogeorgejoseph** [getgrav/grav-plugin-admin#1358]
Some warning messages when downloading xlsx files from the grav site using firefox .(issue only exist when open with ms-excel)

How to set MIME-TYPE for XLSX in grav?

Added xlsx mime-type as  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"  in config - > Media . But it is not working.

![download 1](https://user-images.githubusercontent.com/25584016/36728879-4a39b808-1be8-11e8-9e24-078a469f089c.jpg)

**Comment by rhukster** [comment]
Duplicate issue in admin core: https://github.com/getgrav/grav/issues/1894
