### ISSUE TITLE
plugin install permissions

### ISSUE THREAD

**Issue by SoGerh** [getgrav/grav-plugin-admin#1365]
Hello,

I have a problem with a group of user, indeed, I allowed the section admin.plugin to 'true'.
But the users of the group can't download plugins. Do you have an idea about how to solve the problem ?

Thanks in advance

**Comment by rhukster** [comment]
Really need to do a full security audit of the admin to ensure permissions are working as expected.  They are not used that frequently as most users are full admin

**Comment by SoGerh** [comment]
Thanks for your answer!
