### ISSUE TITLE
updating grav/plugins issues

### ISSUE THREAD

**Issue by simogeo** [getgrav/grav-plugin-admin#1367]
Working with Grav v1.3.3 - Admin v1.6.0, when I try to update to 1.3.10 I get the following error : 

`Error while trying to download (code: 302): https://getgrav.org/download/core/grav-update/1.3.10 `

any help would be welcome

Having also a similar problem when trying to update plugins

**Comment by simogeo** [comment]
Alternatively, I also get `Invalid AJAX response.`

**Comment by rhukster** [comment]
Can you first try forcing the `Remote Fetch Method` in the Configuration.  If that doesn't work, try disabling the `Remote Verify Peer`

![configuration__system___outdoorfloor](https://user-images.githubusercontent.com/1084697/37110389-fad022b2-21f9-11e8-8c9a-52e050159a54.jpg)

**Comment by simogeo** [comment]
working with cURL : 

`Error while trying to download (code: 302): https://getgrav.org/download/core/grav-update/1.3.10 Message: SSL connect error error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version`

I have also tried `Remote Verify Peer` with no more success

**Comment by rhukster** [comment]
Have you tried `fopen` or just `curl`? If curl, give fopen a whirl.

**Comment by rhukster** [comment]
BTW, googled, and it looks like your SSL version is out of date on your server: 

https://www.drupal.org/forum/support/upgrading-drupal/2017-09-17/openssl-error-tlsv1-alert-protocol-version-when-trying-to

**Comment by simogeo** [comment]
I've tried both `curl` and `fopen`.

Investigating a bit more, clicking the update button trigger an asynchrone request with the following url : `http://www.domain.tld/admin/update.json/task:updategrav/admin-nonce:b9e06ed378094ce7b1941e6d45fd8ad3`

response is empty


From phpinfo, i'm able to get ssl version (but I don't believe it is the problem) : 

> 

OpenSSL support | enabled
-- | --
OpenSSL Library Version | OpenSSL 0.9.8o 01 Jun 2010
OpenSSL Header Version | OpenSSL 0.9.8o 01 Jun 2010
Openssl default config | /usr/lib/ssl/openssl.cnf

**Comment by simogeo** [comment]
Do you think, this could be due to HTTPS protocol on me website ? (using [Let'sEncrypt](https://letsencrypt.org/))

**Comment by rhukster** [comment]
No, it's not related to your SSL certificate on your site, it's related to your out-of-date OpenSSL library (2010), that's nearly 8 years old.

If you update OpenSSL it will undoubtedly solve your issues.

**Comment by simogeo** [comment]
I'm on shared server. I'll try to make them update SSL library - which is a very good idea. I'll let you know

Many thank for your support

**Comment by simogeo** [comment]
Indeed updating openssl fixed the issue. Thanks again for your support and the great project !
