### ISSUE TITLE
Metadata letter case issue

### ISSUE THREAD

**Issue by underr-ua** [getgrav/grav-plugin-admin#1370]
Admin plugin saves all similar metadata that wrote in different way: 'description' and 'Description' both will be added like two different metadata.

**Comment by rhukster** [comment]
Can you give me an example of what you mean? How are you entering description both ways? via the frontmatter, or via the forms?

**Comment by underr-ua** [comment]
I talk about case sensitive of added metadata names (and no matters how i add it - via the frontmatter, or via the forms ):
Frontmatter:
```
metadata:
    Description: test
    description: 'test'
```
Output html:
```
<meta name="description" content="test" />
<meta name="Description" content="test" />
```
And when i use something like `page.header.metadata.description` in templates it is differnt of `page.header.metadata.Description`.

P.S.:Sorry if my poor English is hard to understand.

**Comment by rhukster** [comment]
I think we should force to lowercase.

**Comment by rhukster** [comment]
Fixed in Grav develop branch (not an admin issue)
