### ISSUE TITLE
Error when changing /admin path

### ISSUE THREAD

**Issue by Chris-KC** [getgrav/grav-plugin-admin#1371]
I am experiencing this same error both locally and remotely and with Admin 1.6.7 and 1.7.0. Grav 1.3.10.

Attempting to change the administrator path from Admin > Plugins > Admin Panel > Administrator path [/admin  ] to [/admin-new  ] produces the error "Invalid AJAX response." upon Save. After the error hitting either Back to Plugins or Save produces a 404 page. Browsing to /admin-new works and shows me still logged in. Able to log out and in at /admin-new as expected. The change is recorded in config/plugins/admin.yaml and nowhere else that I can see. The /plugins/admin folder is not renamed. 

Is this expected behavior? The error and manually browsing to the new path seems inelegant. Does the above still provide a mild security benefit even though the /admin folder has the same location and name?

**Comment by RobLui** [comment]
This is normal behavior, cause if you'd save or go back , they're still based on the old url wich was /admin :) hope this helped

**Comment by Chris-KC** [comment]
Understood. But perhaps the system could prompt the user with an alert and a button redirecting to the changed /admin-new, instead of the "Invalid AJAX response" error and leaving them on the outdated path.

**Comment by rhukster** [comment]
Fixed for next update.

**Comment by ppo** [comment]
I had this error with v1.7.40
