### ISSUE TITLE
On running Grav instance behind a reverse proxy and custom port.

### ISSUE THREAD

**Issue by moijafcor** [getgrav/grav-plugin-admin#1372]
First off, very impressive product! Kudos to the community.

I am running my instance behind two reverse proxies (the SSL termination and the caching). The backend runs on port 8080 and is not exposed to the public Internet.

I've noticed URIs take the PHP provided server parameter, http://www.example.com:8080; but in my use case, it has to be https://www.example.com/.

Is there a safe method to override this behaviour in such a way the Grav instance remains upgrade safe? (No hacking core files or theme tricks).

Thanks!

```
<meta name="generator" content="GravCMS" />
--
  | <meta name="description" content="" />
  | <meta name="keywords" content="" />
  | <meta name="og:sitename" property="og:sitename" content="" />
  | <meta name="og:title" property="og:title" content="" />
  | <meta name="og:type" property="og:type" content="article" />
  | <meta name="og:url" property="og:url" content="http://www.example.com:8080/myurl" />
  | <meta name="og:image" property="og:image" content="http://www.example.com:8080/path/to/image.jpg" />
```

**Comment by rhukster** [comment]
@moijafcor did you try Grav 1.4? It has some updates regarding how these ports are handled.  Also this should be a Grav core issue, not admin: https://github.com/getgrav/grav/issues

Cheers.

**Comment by moijafcor** [comment]
Yes, I just updated the instance and the issue is still there. My bad on not checking the repo I was posting on. Sorry about that.
