### ISSUE TITLE
Image library - Feature request

### ISSUE THREAD

**Issue by Genenenenaam** [getgrav/grav-plugin-admin#1373]
Hi,

My question is about uploading all files into a single folder. The documentation states:
["If you want to put all your images in a single folder, you can put them in a user/pages/images folder. "](https://learn.getgrav.org/content/media#where-to-put-your-media-files)

I like this approach as it makes all images availeble on all pages, and still allows the 'image actions' to be applied.

(Preview of the added folder)
![schermafbeelding 2018-03-10 om 22 19 33](https://user-images.githubusercontent.com/20650976/37246849-6eb15c28-24b1-11e8-8251-6394ba5a9d7a.png)

Grav-adim lists the pages in it's overview. Notice the 'image upload', which is actually the added 'image' folder. I altered the title from 'images' to 'Image upload' to state it's use, hence it's not a webpage.

(preview of the page structure in grav-adim)
<img width="567" alt="schermafbeelding 2018-03-10 om 22 23 26" src="https://user-images.githubusercontent.com/20650976/37246924-a9909a9c-24b2-11e8-8690-fef855f4ac94.png">

After hiding some tabs and fields, i'm trying to make it clear to a user that this is the 'media library' where he/she can upload all files. And they can be selected on all other pages by a field type 'filepicker'.

(Preview of the media library(?) page)
<img width="1671" alt="schermafbeelding 2018-03-10 om 22 37 41" src="https://user-images.githubusercontent.com/20650976/37246988-d7e11d8a-24b3-11e8-9e12-fa8e189d1f37.png">

My feature request is for a real media library (that still has acces to the media 'actions' stated in the link above.) Having to go to pages for a media overview, doesn't seem obvious for a user.

--

A small thought for now.

Could we...
- Add our own button to the sidebar? 'Media Library'.
- Link that button to 'pages -> Image upload'
- hide 'Image upload' from the listing?

Thanks a lot for creating GRAV! (and killing wordpress ;D )

**Comment by rhukster** [comment]
You can do these things with a custom plugin

1. you can add your own button in the sidebar (see Datamanager or Comments plugins)
2. You can link this to a specific page for managing the uploads
3. You can hide the regular mediaselect field by overriding the blueprints and unsetting that and media_order.
