### ISSUE TITLE
New font for buttons markdown editor not very legible

### ISSUE THREAD

**Issue by ThosG** [getgrav/grav-plugin-admin#1374]
The latest Admin version has a new font for the buttons on the menu bar of the markdown editor. Unfortunately it's not easy to read on my screen, in fact the lett B is unreadable. Looks like this:
![image](https://user-images.githubusercontent.com/11003463/37254683-022f9122-2539-11e8-845c-148785b896c3.png)
Please could we have the old font back? Sorry to sound ungrateful.

**Comment by paulhibbitts** [comment]
Hi @ThosG , you can choose to use either the LineAwesome (Light) or FontAwesome (Dark) font in the config for the Admin Panel plugin:

![2018-03-11_10-17-06](https://user-images.githubusercontent.com/1812771/37256268-60dee55c-2515-11e8-84ae-e0c5c24c11d1.png)

**Comment by rhukster** [comment]
Yup as @paulhibbitts says, you can go back to the prior icons if you prefer them.
