### ISSUE TITLE
Invalid scurity token

### ISSUE THREAD

**Issue by underr-ua** [getgrav/grav-plugin-admin#1376]
_Invalid security token_ error when i try to save edited page. And loss of all changes.

**Comment by karlingen** [comment]
Did you happen to do like me? I used my browser's back button to return to the form that I edited before. Thus causing the form to use an invalid form token..
Grav should be able to handle this though since this is veeery common. At least save the edited text in the editor using localstorage or something else..

**Comment by underr-ua** [comment]
**karlingen**, in my case i had lost authorization and had to enter credentials again. after successful login i had previous version of my page.

**Comment by karlingen** [comment]
Might be an issue with PHP's session expiry

**Comment by rhukster** [comment]
We're investigating a Session based issue that is likely causing this.  Hopefully have an update on this soon.

**Comment by rhukster** [comment]
Fixed here.. https://github.com/getgrav/grav/commit/234555b20898944670a4512523674aa8b3f647a1 

release coming soon...

**Comment by rhukster** [comment]
Then i can't replicate at this time, and i'm going to need a zip from your with a test site that I can use to replicate it. thanks!

**Comment by underr-ua** [comment]
Please: [jotter-theme-20180322122057.zip](https://github.com/getgrav/grav-plugin-admin/files/1837031/jotter-theme-20180322122057.zip)

Session expired less then 1 hour

**Comment by underr-ua** [comment]
[temp-20180322125649.zip](https://github.com/getgrav/grav-plugin-admin/files/1837147/temp-20180322125649.zip)
login:password: `admin:Admin2018`

**Comment by rhukster** [comment]
I will test this.  Does it matter what page you are sitting on? The page edit view perhaps?

**Comment by underr-ua** [comment]
It does not matter. Thanks.
