### ISSUE TITLE
'Save' page button not saving in Edge browser

### ISSUE THREAD

**Issue by Rocknet315** [getgrav/grav-plugin-admin#1377]
Hello.  I updated Grav today. Grav v1.4.0 - Admin v1.7.0
When I edit a page and click 'save' the page does not save.
This issue only seems to occur on one of my laptops... A HP Stream. All other laptops work fine.
Prior to the update, I could use the HP Stream to update pages.

Any advise is greatly appreciated.
Thanks

Stephen

**Comment by karlingen** [comment]
What does your error log say?

**Comment by Rocknet315** [comment]
Hello Karlingen. 
Thanks for responding.
I've discovered that the problem was with the Edge Browser. For some reason, it wouldn't save a page.
Using Firefox has fixed this for me.
Regards

Stephen

**Comment by rhukster** [comment]
Edge should work though.

**Comment by Rocknet315** [comment]
Hello. Just checked on another PC with edge and it works fine. Though there has been an update to Grav since my first post. The laptop with the issue is a Netbook HP Stream but I haven't had then opportunity to see if the fault remains on that. Maybe it is an isolated issue to that PC. Thanks for being so responsive. For my part. I have found a work around and am happy.
