### ISSUE TITLE
search function on the admin page problem

### ISSUE THREAD

**Issue by kristoferus75** [getgrav/grav-plugin-admin#1378]
Hi !

I have a problem with the search function on the admin page.
When ever I search I get the below:

TypeError: Cannot read property ‘forEach’ of undefined at e.value (http://192.168.100.66/user/plugins/admin/themes/grav/js/admin.min.js?1b7a11d60e:5:98431)

The next message it prompts is:
iconv(): Wrong charset, conversion from utf-8' toascii//translit’ is not allowed

newest grav and all plugins updated

Grav v1.4.1 - Admin v1.7.1

kind regards

kristoferus75

**Comment by rhukster** [comment]
I can't recreate this in my demo setups. Search is working fine.  Maybe its a plugin you have installed? Can you try disabling them one by one to see if that makes a difference?

**Comment by kristoferus75** [comment]
Hi !

These Plugins are currently installed :  

And i have disabled all plugins but not the admin panel  : -> but without sucess :-(

Admin Panel  v1.7.1
 Anchors  v1.5.2
 Breadcrumbs  v1.5.1
 Editor Buttons  v1.2.1
 Email  v2.7.1
 Error  v1.6.1
 Form  v2.13.0
 Highlight  v1.4.0
 Login  v2.6.0
 Problems  v1.4.7
 SimpleSearch  v1.14.1

**Comment by kristoferus75** [comment]
Hi ! I use this setup on an lxc container with newest alpine linux installed ! But i remember that after first grav install all works and after an update of the admin panel the search pages suddently not work anymore :-(
