### ISSUE TITLE
Chart size issue

### ISSUE THREAD

**Issue by nicolasdanelon** [getgrav/grav-plugin-admin#138]
This happens my Firefox developer and Standard Firefox . Safari, chrome & chromium does not have the issue.

![screenshot from 2015-09-04 10-38-46](https://cloud.githubusercontent.com/assets/2846046/9684952/490ea988-52f1-11e5-8938-d8c76d0c1033.png)
![screenshot from 2015-09-04 10-35-23](https://cloud.githubusercontent.com/assets/2846046/9684953/4911cafa-52f1-11e5-8992-b5b588e91051.png)

**Comment by rhukster** [comment]
It seems to be something with chartist. The charts are actually rendering a few pixels down in the svg causing the bottoms to be cut off.. Not sure why that is not seeing it in their demo.  I tried updating to latest version, but it's doing the same thing.  Perhaps @w00fz has some ideas?

**Comment by w00fz** [comment]
This seems to be a Chartist issue, I was able to workaround it by compensating with some padding in Firefox only, we will have to keep an eye on it and update the library when it gets fixed.
