### ISSUE TITLE
[Feature request] add autosize.js to textarea

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav-plugin-admin#1381]
To provide a better UX it could be nice to use [autosize.js](https://github.com/jackmoore/autosize).
It's a tiny piece of js very easy to use that automatically resize text area while typing.

**Comment by rhukster** [comment]
Not super keen to add something like this to core (especially when it has so many github issues).  Perhaps a plugin that adds this functionality makes more sense?

**Comment by jimblue** [comment]
Oh sorry didn't mean to be disturbing... Just tough sharing idea to improve UX in admin could interest you for future release. I also agree that it can be added from a plugin, but it make more sens in my opinion to add this kind of feature to the core.
