### ISSUE TITLE
Keyboard shortcut for save triggers on too many variations.

### ISSUE THREAD

**Issue by Flamenco** [getgrav/grav-plugin-admin#1382]
I am trying to write a keyboard handler for shift-meta-s.  There is a conflict with the code the save function currently triggers on:

https://github.com/getgrav/grav-plugin-admin/commit/4384ac5bb939da20fef97fe4760a6e5147d8278a

- meta-s
- control-s
- control-meta-s

It does not check for the shift key status, so it also triggers on

- shift-meta-s
- shift-control-s
- shift-control-meta-s

Can you add a check for the shift key?

**Comment by w00fz** [comment]
Looks like your PR made it already in the code so closing this. I just tweaked your code slightly for optimization.

Thanks!
