### ISSUE TITLE
textarea and editor acts funky in list element

### ISSUE THREAD

**Issue by superDuperCyberTechno** [getgrav/grav-plugin-admin#1386]
![grav_bug](https://user-images.githubusercontent.com/6486383/37397894-13313d7c-277d-11e8-89c5-29d15e008397.png)

The expand/collapse buttons doesn't seem to do anything.

Disabling the fixed 70px height rule in the browser dev tools expands the boxes just fine.

Adding a text element to the same list element as the textarea/editor causes the box to behave expectedly.

Tested in Chrome and Firefox.

**Comment by rhukster** [comment]
Lists strike again @w00fz !

**Comment by w00fz** [comment]
The collapsible field never shows up if there's only 1 field in the list.
You can trick this by adding an extra dummy field before the textarea. Like a `spacer`

```
spacer:
    type: spacer
    text: Fill the textarea below
```
