### ISSUE TITLE
Editor loses edits on save and reverts to previous text

### ISSUE THREAD

**Issue by ZeroGodForce** [getgrav/grav-plugin-admin#1387]
I've been using the content editor to write some documentation for a project using the learn2 skeleton.  And have been saving frequently as I go along.  However, after 2 hours of editing, it has lost all of my changes and reverted to the state the content was in when I first opened the page.

I don't know what could have caused this.  I used the [Grav Learn](https://github.com/getgrav/grav-learn) skeleton repo to get me started, but had to clear the cache every time I made edits, so I temporarily disabled caching.  It is the only thing I can think of, but surely disabling cache shouldn't do this.  I'm baffled how it could even retrieve the original state, especially when I've turned caching off.

Has anyone experienced anything like this, or am I missing something?  It's a great system, but right now it has just eradicated an entire morning of work, so this must be a bug somewhere.

**Comment by underr-ua** [comment]
Yes it is old problem

**Comment by underr-ua** [comment]
Yes it is old problem i hate. I have tried to increase cache lifetime but it does not resolve my problem.

**Comment by ZeroGodForce** [comment]
If I could do something about the bug I would, but I wouldn't know where to start and don't have the time available to try.

**Comment by rhukster** [comment]
Are you on latest Grav? There was a bug in 1.4.0 with sessions. Also try increasing your session timeout from 1800 (30mins) to something longer. 

 We have a keep alive that fires in the background and it should keep you connection alive for many hours. You can see it via hr XHR tab in the network inspector of chrome.  If you see it jumping from bytes to kB then the session timed out.  This was the exact problem Grav 1.4.1 fixed

**Comment by ZeroGodForce** [comment]
Yep it was a fresh install today. I had another doc project I started a week or two ago which I think had the bug you're referring to, it would give me session timeout errors and boost me back to the login page, even when actively using it.  

But this wasn't the same, even though I was saving progress regularly, all it took was one save and everything was gone.  Unfortunately I don't know what circumstances triggered it, so I don't know how to reproduce it.

I'm now just editing the file directly, can't risk it right now

**Comment by rhukster** [comment]
Yah that's weird because I've left the editor open for days and never had an issue.  if you can find a way to reproduce it, I will definitely look for a fix, but if I can't see it, I really can't fix it.

**Comment by ZeroGodForce** [comment]
Once I'm caught up, I'll switch back later and keep an eye out

**Comment by jleaders** [comment]
For a test path for this, you could use the git sync plugin and sync occasionally so that you can always revert back to previous versions if it happens again. Gives you peace of mind when working with prod data

**Comment by ZeroGodForce** [comment]
In the end I abandoned Grav altogether and migrated all the content to Gitbook.  Funny you should mention git sync, because I used the Gitbook legacy editor to write and edit - which does do git sync.  

Between that bug, and manually arranging the files so they are structured correctly in the browser, Grav was taking more time, effort, and patience than I had available.  I hope whatever the problem was is now fixed as it's still a great system.  Just not for me on that project.
