### ISSUE TITLE
Upgrading admin causes email plugin to disable sending engine

### ISSUE THREAD

**Issue by hdwebpros** [getgrav/grav-plugin-admin#1389]
This ended up causing some headaches. I'm not sure how we would avoid this...

We have a few Grav sites on our server. We updated them all through the update button on the site's admin.

This caused us to update the email plugin apparently.

The email.yml file in plugins/email/email.yml used to have on line 7
`engine: sendmail`
and that changed to 
`engine: disabled`
after the upgrade. This caused all of our forms on our sites to not send anything out.

I'm unsure how to stop this via code, but this should be considered so all sorts of sites don't get their email functionality shut off.

**Comment by hdwebpros** [comment]
I'm hoping "Make a custom yml file for every site" isn't the answer. I'd be willing to help. Just point me the right direction

**Comment by hdwebpros** [comment]
I think you misunderstood. That file doesn't exist. (user/config/plugins/email.yaml)

Should that be autogenerated or does it have to manually be created

**Comment by rhukster** [comment]
you do it manually, or when you save in admin, it's created for you based on those options.

**Comment by hdwebpros** [comment]
That may be the issue then. We saved in admin, but no file got generated. I'll try to reproduce when I get back to the office

**Comment by hdwebpros** [comment]
I'll mark this as closed. I tried to replicate and it works properly.

More than likely one of us set up the email params directly, but on the wrong file.

Thanks!
