### ISSUE TITLE
Error 503 on some pages' task:listmedia

### ISSUE THREAD

**Issue by stur86** [getgrav/grav-plugin-admin#1394]
I'm using Grav v1.4.1 and grav-admin v 1.7.1, and I get this problem persistently when trying to load certain pages containing media. The problem apparently started after a few new pictures were uploaded. The error message is:

```
503 Service Unavailable

Service Unavailable
The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.
Additionally, a 503 Service Unavailable
error was encountered while trying to use an ErrorDocument to handle the request.
```

sent back by `task:listmedia`, according to the dev console. I've tried creating a `php.ini` file and raising the memory limit, but to no avail. Any suggestions?

**Comment by rhukster** [comment]
It's coming from your server, perhaps the server has implemented some restrictions on CPU utilization or MEMORY or something like that?  You need to contact your hosting provider for more details.

**Comment by stur86** [comment]
I will try, but the page is of the same type of many others that work, and should not have an especially bigger amount of photos on it (neither in number nor in size). Plus the site itself works fine, it's only the admin plugin that has problems.

**Comment by mahagr** [comment]
Field has been updated, will likely not get the same error anymore.
