### ISSUE TITLE
Lang button is always visible

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav-plugin-admin#1395]
Even if only one language is enable the lang button stays visible.

![screen shot 2018-03-21 at 16 39 21](https://user-images.githubusercontent.com/10623367/37720000-9f0f9b64-2d26-11e8-8961-82cfb2e54afe.png)

**Comment by rhukster** [comment]
This is actually intentional.  It indicates you are in multilanguage mode (even with one language) so it's going to be looking for that lang first, even though it will fall back to non-lang versions.
