### ISSUE TITLE
[Question] one more 'default' page template

### ISSUE THREAD

**Issue by underr-ua** [getgrav/grav-plugin-admin#1396]
Why i see one more 'default' template in the template list? When i choose it page file renames in __default.md_
![xmpl](https://user-images.githubusercontent.com/10338746/37784835-634af39a-2e01-11e8-95c3-94e3f404b48c.png)

**Comment by rhukster** [comment]
I think your theme is providing a `modular/default.html.twig` file which is causing the confusion.

**Comment by underr-ua** [comment]
But my theme does not have any modular pages
