### ISSUE TITLE
Configuration Tab route is not dynamic

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav-plugin-admin#1398]
Grav handle config tab to be dynamic with `groups` but the navigation template isn't.

The route is static and point to `/config/system` here in [nav.html.twig](https://github.com/getgrav/grav-plugin-admin/blob/a756cc797589eb8f90215907adae3fdd3419bfaa/themes/grav/templates/partials/nav.html.twig#L22)

This create a bug when the `system` tab is disable from `group`, the page showed is empty and the user have to click on site tab.

PS: if there is only one tab display the tab element should not be display

**Comment by rhukster** [comment]
how about submitting a PR to fix?

**Comment by jimblue** [comment]
Hi @rhukster !
I've try to found a fix without success, that's why I've posted here an not in PR.

**Comment by rhukster** [comment]
Ok, just needs the authorize check to be added in nav.html.twig i think.

**Comment by mahagr** [comment]
This one has already been fixed.
