### ISSUE TITLE
help wanted - twig inside href renders invalid links

### ISSUE THREAD

**Issue by eddinn** [getgrav/grav-plugin-admin#1399]
while trying to display content from github with the guthub plugin the links render incorrectly.

this renders an invalid url:
`<a href="{{ repo.html_url|e }}">link</a>`

the invalid url:
`https://www.domain.tld/%7B%7B%20repo.html_url%7Ce%20%7D%7D`

total code from the github plugin:
`<ul>`
    `<li>Repositories (<strong>{{ github.client.api('user').repositories('eddinn')|length }}</strong>):`
        `<ul>`
        `{% for repo in github.client.api('user').repositories('eddinn') %}`
			`<li>{{ repo.name|e }} [ <a href="{{ repo.html_url|e }}">link</a> | forks: <strong>{{ repo.forks_count|e }}</strong> | stargazers: <strong>{{ repo.stargazers_count|e }}</strong>]</li>`
        `{% endfor %}`
        `</ul>`
    `</li>`
`</ul>`

if you would just put the following code as standalone without href, it renders correctly as an non-hyperlink address:
`{{ repo.html_url|e }}`

**Comment by andrewd72** [comment]
The fact the |escape does different things depending on context sounds like:
"different escaping strategies depending on the template context."
https://twig.symfony.com/doc/2.x/filters/escape.html
My guess is you might need:
|e('url')

**Comment by eddinn** [comment]
hey Andrew.

that renders thje following:
`https://www.domain.tld/%7B%7B%20repo.html_url%7Ce('url')%20%7D%7D`

**Comment by rhukster** [comment]
Is this a github plugin specific issue? or an admin issue? i'm a bit confused as to where you are seeing the problem.

**Comment by eddinn** [comment]
hey rhukster,

I think this is and grav issue.
the code inside the `a href`` does not render but when the same code is outside the `a href`, then it works.

the code  resides in a strandard, default template page in grav with standard settings and permissions prosessing twig and nothing else.

**Comment by eddinn** [comment]
I have resolved the problem, please delete/close the issue.

I selected "Process twig first" and that rendered the links correctly.

thanks
