### ISSUE TITLE
Upload file Always MAX 256 mb.

### ISSUE THREAD

**Issue by DerTFL** [getgrav/grav-plugin-admin#1400]
Hello. When I upload file the max size is 256 mb.
![default](https://user-images.githubusercontent.com/6413014/37920368-5a677fe2-312f-11e8-8f8b-0bfe473bced0.png)
So i can't set filesize bigger 256mb at all! In php.ini, system.yaml - not work.

**Comment by rhukster** [comment]
Double-check that your PHP is actually picking up your setting by looking at the Configuration -> Info tab to see the value in there for the max file-size.  Also, where are you seeing this specifically?

**Comment by rhukster** [comment]
Also what version of Grav are you on? System.yaml doesn't have a filesize option anymore.
