### ISSUE TITLE
Preview pages target

### ISSUE THREAD

**Issue by glooob** [getgrav/grav-plugin-admin#1401]
Hi, it's my first issue so I hope I will not make any mistakes.

In the plugin's configuration , I think the "inine in admin" is "In**L**ine in admin"

And if I select "New Tab" the preview is in the same tab... 
the `target="_blank"` is not active

Version : 1.7.2

Sorry for my english
Glooob

**Comment by rhukster** [comment]
Yes, typo in blueprint.  I've fixed that in devlop branch.

I can't recreate your issue with 'new tab' though, that definitely works for me.
