### ISSUE TITLE
Trouble dragging and dropping atoms

### ISSUE THREAD

**Issue by technolojesus** [getgrav/grav-plugin-admin#1404]
When I go to Gantry 5 > Pages dragging and dropping an atom at the bottom of the page doesn't work right in Safari 11.0.3.

When adding a new particle the outline/text show up, but when I release the drag it just snaps back up to the list of available atoms. Sometimes after I release it and move the cursor back down the separator bar appears between the existing atoms and clicking once will place the previously dragged atom... but either way it seems a bit broken vs. the previous admin version.

**Comment by rhukster** [comment]
This is a gantry5 issue, not a Grav issue, please post this on the appropriate repo: https://github.com/gantry/gantry5/issues
