### ISSUE TITLE
Unknown error issue/site not coming up

### ISSUE THREAD

**Issue by emckinnon** [getgrav/grav-plugin-admin#1406]
![screen shot 2018-03-30 at 11 08 59 am](https://user-images.githubusercontent.com/37935309/38142821-de14b13c-340b-11e8-9734-09d432c7b685.png)

**Comment by rhukster** [comment]
Some error in Events plugin, not Grav itself... I would suggest disabling it:

`user/config/plugins/events.yaml`

```
enabled: false
```

Then creating an issue on the appropriate repo: https://github.com/kalebheitzman/grav-plugin-events
