### ISSUE TITLE
Self title home page

### ISSUE THREAD

**Issue by koreos** [getgrav/grav-plugin-admin#1407]
Hi, on home page I have title "Home page | Grav" but I need to only "Home page" - this is important for SEO, how can I do it? I have also installed Tiny SEO but it doesn't change title like I need.

**Comment by andrewd72** [comment]
Check your /user/config/site file or  /system/config/site if you don't have it. 
Best thing to diagnose is to find where it gets the "| Grav" part in the template so you can see how it works.

**Comment by koreos** [comment]
Thank you for very quick answer! In /user/config/site I have "title: ' Grav' " and in /system/config/site is "title: Grav" but can't find " | ". I only need to change it on home page not for all pages. I thought that can change it in admin panel but didn't find solution. I have latest version of Grav.

**Comment by andrewd72** [comment]
The | is added in the template, likely templates/partials/base.html.twig in your theme folder
Confusing as some of the "|" pipes are to html escape the page titles. 
I have bolded the one that you see in the result.

<title>{% if header.title %}{{ header.title|e('html') }} **|** {% endif %}{{ site.title|e('html') }}</title>

If you want it only on the homepage you'll have to add an alternative using something like (untested)
{% if page.home %}
<title>MY NEW TITLE</title>
{% else %}
<title>{% if header.title %}{{ header.title|e('html') }} **|** {% endif %}{{ site.title|e('html') }}</title>
{% endif %}

**Comment by koreos** [comment]
Thank you but there is a problem:
Twig_Error_Syntax
Unexpected "else" tag (expecting closing tag for the "block" tag defined near line 8).

Will be very good to implement this solution in admin panel.

**Comment by andrewd72** [comment]
Tested it in the blog theme, it does work. Error suggests you might have missed the first {% if page.home %} line?
```
{% if page.home %}
<title>MY NEW TITLE</title>
{% else %} 
<title>{% if header.title %}{{ header.title|e('html') }} **|** {% endif %}{{ site.title|e('html') }}</title> 
{% endif %}
```
Might be easier to help in the slack channel.

**Comment by koreos** [comment]
Yes, now it's work very good, I also changed "|" on "-" and now is perfect for me. I think more people will need this function, will be good in official admin panel. Thank you very much! :-)

**Comment by andrewd72** [comment]
No problem. 
Each theme sets the metadata differently so its hard to tie in to the admin panel. 
For example I set mine in a metadata.html.twig partial. 
You could make a site "home page title" value that was editable in the admin and use that value in the template.

**Comment by clickwork-git** [comment]
Seems to be the question of a troll. He asked the same in Gitter today relating another CMS. Also stating: "It possibility should be in admin panel like in ..." I explained how to modify the code. His friendly answer was: "I have no time in this moment."
