### ISSUE TITLE
Multisite Setup.php

### ISSUE THREAD

**Issue by AndrewNB** [getgrav/grav-plugin-admin#1411]
I am attempting to run a multisite with subdirectories.  

I was unable to find a documented example of setup.php so have used the following version from an answer on StackOverflow:

Not sure if this is right in my situation but it was all I could find:  

My setup.php file:  

```php
<?php
/**
 * Multisite setup for sub-directories or path based
 * URLs for subsites.
 *
 * DO NOT EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!
 */

use Grav\Common\Filesystem\Folder;

// Get relative path from Grav root.
$path = isset($_SERVER['PATH_INFO']) 
    ? $_SERVER['PATH_INFO'] 
    : Folder::getRelativePath($_SERVER['REQUEST_URI'], dirname($_SERVER['SCRIPT_NAME']));
$path = preg_replace('|[?#].*$|', '', $path);

// Extract name of subsite from path
$name = Folder::shift($path);
$folder = "sites/{$name}";
$prefix = "/{$name}";

if (!$name || !is_dir(ROOT_DIR . "user/{$folder}")) {
    return [];
}

// Prefix all pages with the name of the subsite
$container['pages']->base($prefix);

$themes = ["user/themes"];
if (is_dir(__DIR__ . "/user/sites/{$folder}/themes")) {
  array_unshift($themes, "user/sites/{$folder}/themes");
}

return [
    'environment' => $name,
    'streams' => [
        'schemes' => [
            'user' => [
               'type' => 'ReadOnlyStream',
               'prefixes' => [
                   '' => ["user/{$folder}"],
               ]
            ],
            'environment' => [
                'type' => 'ReadOnlyStream',
                'prefixes' => [
                    '' => ["user/{$folder}"],
                ]
            ],

            'themes' => [
                'type' => 'ReadOnlyStream',
                'prefixes' => [
                    '' => $themes,
                ]
            ],

        ]
    ]
];
``` 

my setup_subdirectory.php:

```php
<?php
/**
 * Multisite setup for sub-directories or path based
 * URLs for subsites.
 *
 * DO NOT EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!
 */

use Grav\Common\Filesystem\Folder;

// Get relative path from Grav root.
$path = isset($_SERVER['PATH_INFO'])
   ? $_SERVER['PATH_INFO']
   : Folder::getRelativePath($_SERVER['REQUEST_URI'], ROOT_DIR);

// Extract name of subsite from path
$name = Folder::shift($path);
$folder = "sites/{$name}";
$prefix = "/{$name}";

if (!$name || !is_dir(ROOT_DIR . "user/{$folder}")) {
    return [];
}

// Prefix all pages with the name of the subsite
$container['pages']->base($prefix);

return [
    'environment' => $name,
    'streams' => [
        'schemes' => [
            'user' => [
               'type' => 'ReadOnlyStream',
               'prefixes' => [
                   '' => ["user/{$folder}"],
               ]
            ]
        ]
    ]
];
```

So far so good, was able to create subsites, visit them and login to admin.  However, on the subsites, I receive an invalid security token when I attempt to upload a file to anything other than pagemedia. 

On the main site, I have no issue with these tasks.   I am able to create a page on the main site and then physically move the page directory to one of the subsites and the page renders fine but still get errors in admin.      

When doing any updates on the gpm I receive this error:  
PHP Notice:  Undefined index: REQUEST_URI in C:\xampp\htdocs\gravlive\setup.php on line 14
Notice: Undefined index: REQUEST_URI in C:\xampp\htdocs\gravlive\setup.php on line 14

if I go to http://localhost/gravlive/setup.php I get this error:  
Fatal error: Uncaught Error: Class 'Grav\Common\Filesystem\Folder' not found in C:\xampp\htdocs\gravlive\setup.php:14 Stack trace: #0 {main} thrown in C:\xampp\htdocs\gravlive\setup.php on line 14

Like I mentioned before, the multisite functionality works except for the invalid security token and the errors mentioned.  
There wasnt a lot of documentation on what the setup.php should contain so unsure where to go from here.

**Comment by AndrewNB** [comment]
Whoops, my setup_subdirectory.php file is
`<?php
/**
 * Multisite setup for sub-directories or path based
 * URLs for subsites.
 *
 * DO NOT EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!
 */

use Grav\Common\Filesystem\Folder;

// Get relative path from Grav root.
$path = isset($_SERVER['PATH_INFO'])
   ? $_SERVER['PATH_INFO']
   : Folder::getRelativePath($_SERVER['REQUEST_URI'], ROOT_DIR);

// Extract name of subsite from path
$name = Folder::shift($path);
$folder = "sites/{$name}";
$prefix = "/{$name}";

if (!$name || !is_dir(ROOT_DIR . "user/{$folder}")) {
    return [];
}

// Prefix all pages with the name of the subsite
$container['pages']->base($prefix);

return [
    'environment' => $name,
    'streams' => [
        'schemes' => [
            'user' => [
               'type' => 'ReadOnlyStream',
               'prefixes' => [
                   '' => ["user/{$folder}"],
               ]
            ]
        ]
    ]
];`

**Comment by mahagr** [comment]
You do not need setup.php for subfolders, you just need the main one.

```php
<?php
/**
 * Multisite setup for sub-directories or path based
 * URLs for subsites.
 *
 * DO NOT EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!
 */
use Grav\Common\Filesystem\Folder;

if (!defined('GRAV_ROOT')) die();

$skeleton = false;

// $environment has already been set, but we want to
if (isset($_SERVER['REQUEST_URI'])) {
    // Extract name of subsite from the path.
    $path = isset($_SERVER['PATH_INFO'])
        ? $_SERVER['PATH_INFO']
        : Folder::getRelativePath($_SERVER['REQUEST_URI'], dirname($_SERVER['SCRIPT_NAME']));

    // Remove sub-path, query string and fragment.
    $parts = preg_split('|[/?#]|', trim($path, '/'));
    $environment = array_shift($parts);
}

// Path to subsite (filesystem).
$folder = "sites/{$environment}";

// Path to subsite (site).
$prefix = $environment;

if (!$environment || !is_dir(ROOT_DIR . $folder)) {
    // We are on main site.
    return [
        'environment' => '',
        'streams' => [
            'schemes' => [
                'sites' => [
                    'type' => 'ReadOnlyStream',
                    'force' => true,
                    'prefixes' => [
                        '' => ['sites'],
                    ]
                ]
            ]
        ]
    ];
}

// Prefix all pages with the name of the subsite.
$container['pages']->base("/{$prefix}");

return [
    'environment' => $environment,
    'streams' => [
        'schemes' => [
            'environment' => [
                'type' => 'ReadOnlyStream',
                'force' => true,
                'prefixes' => [
                    '' => $folder,
                ]
            ],
            'user' => [
                'type' => 'ReadOnlyStream',
                'force' => true,
                'prefixes' => [
                    '' => ['environment://', 'user'],
                ]
            ],
            'image' => [
                'type' => 'ReadOnlyStream',
                'prefixes' => [
                    '' => ['environment://images']
                ]
            ],
            'page' => [
                'type' => 'ReadOnlyStream',
                'prefixes' => [
                    '' => ['environment://pages']
                ]
            ],
            'asset' => [
                'type' => 'ReadOnlyStream',
                'force' => true,
                'prefixes' => [
                    '' => ["assets/sites/{$prefix}"],
                ]
            ],
            'backup' => [
                'type' => 'Stream',
                'force' => true,
                'prefixes' => [
                    '' => ["backup/sites/{$prefix}"]
                ]
            ],
            'cache' => [
                'type' => 'Stream',
                'force' => true,
                'prefixes' => [
                    '' => ["cache/sites/{$prefix}"],
                    'images' => ["images/sites/{$prefix}"]
                ]
            ],
            'log' => [
                'type' => 'Stream',
                'force' => true,
                'prefixes' => [
                    '' => ["logs/sites/{$prefix}"]
                ]
            ],
            'tmp' => [
                'type' => 'Stream',
                'force' => true,
                'prefixes' => [
                    '' => ["tmp/sites/{$prefix}"]
                ]
            ],
        ]
    ]
];
```

**Comment by AndrewNB** [comment]
Great, this worked.  After I figured out I needed to move my sites folder to the main directory.  

I am not recieving an error on setup.php and it's working how it was however I am still getting invalid security token errors when editing a template that has a pagemediaselect.

If I use pagemediaselect in a template on a "subsite" like site.com/site2 of a multisite I receive an invalid security token and the dropdown does not work correctly on the pagemediaselect field.  However on the main site: site.com - the drop-down works just fine and there's no invalid security token.  

this is my blueprint for the field 
```
header.featuresphere.img:
	type: pagemediaselect
	preview_images: true
	label: Choose media
```
then the template is this:  

```
{% set image_parts = pathinfo(header.featuresphere.img) %} 
{% set image_basename = image_parts.basename %} 
{% set image_page = image_parts.dirname == '.' ? page : page.find(image_parts.dirname) %} 
<img src="{{ image_page.media[image_basename].url }}">
```

**Comment by mahagr** [comment]
You can have the sites where you want, just change the `$folder` from `setup.php`. Also, the `$prefix` variable can be changed to change the URL.

I will need to take a look at the other issue, it may be a bug. There are also some other known issues with multisite, which will need to be ironed out.

**Comment by AndrewNB** [comment]
@mahagr is there any way to get content from one subsite to another...like ```page.find()```?  Or a way for all sites to share a common file.md to use in a template?

**Comment by mahagr** [comment]
@AndrewNB There's really no way to get content from one site to another unless the data is shared between the sites -- and then it'll really be data in the current site. Unfortunately, pages are one of the few things which cannot be inherited, so you'll share either all pages or none of the pages.

**Comment by mahagr** [comment]
@AndrewNB I think your security token issue is related to #2059

**Comment by mahagr** [comment]
Closed the issue due to inactivity.
