### ISSUE TITLE
Custom page creation modal button not showing

### ISSUE THREAD

**Issue by diegovogel** [getgrav/grav-plugin-admin#1414]
I'm following [these instructions](https://learn.getgrav.org/cookbook/admin-recipes#add-a-custom-page-creation-modal) to add a custom page creation modal but running into trouble with the second step, where I add the `add_modals` snippet to `user/plugins/admin.yaml`.

The issue is that if I put the snippet in `user/plugins/admin.yaml` as directed, the page creation button does not appear in the site admin area. I can only get the button to show up if I add the snippet to `user/plugins/admin/admin.yaml`. But this isn't ideal because I'm guessing the snippet will be erased when the plugin updates.

Not sure if there's anything else that needs to go in `user/plugins/admin.yaml` but I've tried it with just the `add_modals` snippet as well as copying the entire `user/plugins/admin/admin.yaml` code and adding the snippet to the end.

Any ideas?

**Comment by rhukster** [comment]
i think it should be put in `user/config/plugins/admin.yaml`.  is a typo i think.

**Comment by diegovogel** [comment]
Ok thanks, I'll give that a shot.
