### ISSUE TITLE
Single language different than English

### ISSUE THREAD

**Issue by webcoderkz** [getgrav/grav-plugin-admin#1416]
If using single language different than English, for example Kazakh, if i create a new page in Admin panel, it would create `page.kk.md` - is that expected behavior? Shouldn't it be just `page.md` ?

**Comment by rhukster** [comment]
Yes, that is expected.  With no supported languages specified, there's no specific language switching logic happening.  As soon you specify a supported language it starts adding the prefix to the pages, and these are picked up by default. 

The thought is that if you aren't specifying a language specifically, you can use whatever you like for your default language, so don't even set the language if you want this behavior.

**Comment by tremel** [comment]
But I have to set the language (single language different than English) to have the sidebar and login dialogs translated, have I? If I want the translations there without renaming files by the admin plugin it is not possible?

It is confusing to have modified markdown and media file names in content just to have german messages. This is not following the KISS principle.

Moreover: If I start with an existing site and some content is touched by the admin plugin I create a mix of files with and without language prefix.

Coudn't there be a configuration option to have translations to a single language different than English with changing default language files by the admin plugin?

**Comment by tremel** [comment]
Any opinion?

**Comment by mahagr** [comment]
There's now option to do just that in Admin 1.10 (Grav system setting).
