### ISSUE TITLE
List type form fields difficult to edit

### ISSUE THREAD

**Issue by mikegcox** [getgrav/grav-plugin-admin#142]
Using a List type form field on a Blueprint file for a theme template. When editing the text in any of the text fields, you cannot place your cursor inline in the text, you can only place your cursor at the beginning of the field and then you must use the arrow keys and backspace/delete to move within the field and edit the text.  Text is still editable, but this unusual behaviour would be confusing to a non-tech administrator.

**Comment by rhukster** [comment]
Well i can't seem to replicate this. What browser/platform are you using.  It's fine in Chrome/Mac.

**Comment by mikegcox** [comment]
Firefox and Win10. Will test more when I get home

**Comment by mikegcox** [comment]
In Chrome, I can edit normally but the text is a faded color just as it is in other browsers.  In Firefox I can only put my cursor at the beginning of the text box.  In Edge browser I cannot edit at all.  In IE, I cannot edit at all.  With my Blackberry browser, I cannot cannot edit.  In Opera it is the same as Chrome which makes sense as it is the same as Chrome now.

**Comment by mikegcox** [comment]
It looks to me that the fields are set to read-only, but Chrome and Firefox don't support the read-only method used by the control you are using.

**Comment by rhukster** [comment]
![2015-09-07-11-zl4p6](https://cloud.githubusercontent.com/assets/1084697/9720927/8e04b184-5550-11e5-8b14-e84bcf771fca.png)

your talking about this field right? Im not seeing any readonly settings.

**Comment by mikegcox** [comment]
Yes those are the fields.  You see how they are light coloured?  I don't see a readonly setting either, but those fields don't work normally in anything other than Chrome/Opera and they don't work at all with Edge and IE.

**Comment by rhukster** [comment]
Ok, the light color is CSS that was throwing me too.  I can replicate this in Firefox, but its fine in Chrome.  Seems to be a JS issue, i'm gonna as our local expert about it :)
