### ISSUE TITLE
Admin pages take 20s to load when offline

### ISSUE THREAD

**Issue by cweiske** [getgrav/grav-plugin-admin#1420]
I'm trying to use grav 1.4.2 with the current admin plugin on train rides to/from work without internet connection. My operating system is Ubuntu Linux 16.04.

Whenever I try to load an admin page, it takes **20 seconds** until the browser shows it, rendering the admin panel unusable for offline work.

The issues stems from the sidebar that [tries to show the number of plugins and themes](https://github.com/getgrav/grav-plugin-admin/blob/312530374476ec200c002e57c2a0c7d85ddc1202/themes/grav/templates/partials/nav.html.twig#L61). Internally GPM is instantiated, which adds the local and remote repositories - and the remote repository automatically loads the plugin list from the grav server. When the cache is empty or expired (which is basically everytime, since I only have time to work on that project on the train), the 20s problem strikes.

When I disable the `admin.plugins|length` and `admin.themes|length` calls in `nav.html.twig`, the backend is fast (except that the browser (Firefox) takes another 20s to notice that it can't reach gravatar.com).

----

My suggestion:

Do not load the remote plugin list unless it is needed.

----
Related issues:
- The long delay has been described in https://github.com/getgrav/grav/issues/1210.
- Bug https://github.com/getgrav/grav-plugin-admin/issues/928 led to graceful failure when the plugin list could not be loaded. Before it would simply throw an exception
- There is already an issue for offline mode avatar: https://github.com/getgrav/grav-plugin-admin/issues/1335

**Comment by mahagr** [comment]
There is an offline mode already in Grav, though you need to turn your ethernet/wifi off in order to have it turned on.

**Comment by rhukster** [comment]
Just to reiterate if you are connected to wifi/ethernet but your internet is down, then Grav has no way to know the internet is down until things 'timeout'.  However, if you simply disable your wifi/ethernet then it can detect that without the timeout and things are faster.  So, if you are on a plane for example, disconnecting from WIFI will enable the built-in offline mode just fine.
