### ISSUE TITLE
[question] Is it possible to add admin page via plugin or another way ?

### ISSUE THREAD

**Issue by Djibdjib** [getgrav/grav-plugin-admin#1428]
I would like create an admin page on sidebar of admin, to create an media gallery. Is it possible ?

Thx !

**Comment by OleVik** [comment]
It is, through the [onAdminMenu](https://github.com/getgrav/grav-plugin-admin/blob/7025f2fa2bf16c3a9f85fef58630a1da4205b063/admin.php#L523)-hook for the sidebar, and [onPluginsInitialized](https://github.com/getgrav/grav-plugin-admin/blob/7025f2fa2bf16c3a9f85fef58630a1da4205b063/admin.php#L88)-hook for the page itself. Several plugins do this, like [AdminStyles](https://github.com/OleVik/grav-plugin-adminstyles/blob/master/adminstyles.php) and [PiwikAdmin](https://github.com/ricardo118/piwikadmin).

**Comment by Djibdjib** [comment]
Thx a lot ! 
So nice 👍
