### ISSUE TITLE
Suggested plugin name mismatch

### ISSUE THREAD

**Issue by jgonyea** [getgrav/grav-plugin-admin#1432]
https://github.com/getgrav/grav-plugin-admin/blob/fec03d62a6a6f0564fa45755198735abe7f6bc44/themes/grav/templates/partials/nav-quick-tray.html.twig#L32

This line suggests to install the `quick-tray` plugin, but the real name is `quick-tray-links`.

**Comment by rhukster** [comment]
good catch, will sort..

**Comment by rhukster** [comment]
cheers.. merged
