### ISSUE TITLE
Admin - Pro: Information

### ISSUE THREAD

**Issue by AnthonyVO** [getgrav/grav-plugin-admin#1437]
I have seen some references to a Pro version of the Admin Plugin but can't seem to find any current information.

e.g. 
- Pricing
- Features.

Thanks

**Comment by koreos** [comment]
I also join to this question. When we can see Pro Version?

**Comment by rhukster** [comment]
We've kinda held off on admin pro to focus on core improvements.  Also we're thinking more and more of moving the admin to a more interactive solution powered by Vue.js.  This obviously is a major change in how the admin currently works, and we'll need a full API in order for it to work effectively.  So this has pushed things out, maybe even to Grav 2.0.
