### ISSUE TITLE
Page Media Image Name Starting with Numbers Breaks Editor Preview

### ISSUE THREAD

**Issue by thekenshow** [getgrav/grav-plugin-admin#1438]
If you upload a page media image whose name contains a space, the page media image preview feature fails because these images all linked to /undefined. The images still work as expected when inserted into the page.

Examples that trigger this include:
```
1b mypic.jpg
b1 mypic.jpg
b mypic.jpg
```
Similar names that work fine:
```
1b-mypic.jpg
b1_mypic.jpg
b-mypic.jpg
```
Confirmed with a fresh Grav+Admin 1.4.3 installation.

**Comment by w00fz** [comment]
Is this still an issue with the latest admin? I can't seem to reproduce it.

![edit core grav 2018-05-15 11-02-28](https://user-images.githubusercontent.com/11734/40074800-7eb1cdf4-582f-11e8-973c-fc25a7b86544.png)

**Comment by w00fz** [comment]
Sorry I misread that this is just the open in preview. I'll look into this

**Comment by w00fz** [comment]
Sorted 😃
