### ISSUE TITLE
Saving System configuration causes `Validation failed` message

### ISSUE THREAD

**Issue by bsheen** [getgrav/grav-plugin-admin#1439]
This is the message I receive from at the top of `Configuration - System` after clicking `Save`
```
Validation failed: 
Invalid input in "Timezone"
Invalid input in "Parameter separator"
Invalid input in "Default ordering"
Invalid input in "Default redirect code"
Invalid input in "Cache check method"
Invalid input in "Cache driver"
Invalid input in "Display errors"
```
Error persists when selecting a value for one or all of the above.

Grav v1.4.3
Admin v1.7.4

Cleared the cache ` bin/grav clear-cache` and copied over the default System.yaml from `system/config/system.yaml`

Additionally, I'm getting a similar validation error when saving a page:
```
Validation failed: 
Invalid input in "Sitemap change frequency"
```
Error persists when selecting a value for "Sitemap change frequency".

Finally, I've just upgraded from:
Grav v1.3.10
Admin v1.6.7
Both the System.yaml and pages saved successfully without validation errors on these versions for Grav and Admin.

**Comment by bsheen** [comment]
I tried upgrading Admin from Admin v1.6.7 from Grav v1.3.10 to attempt to isolate the issue. But I get:
```
One of the packages require Grav >=1.4.0. Please update Grav to the latest release.
```

**Comment by rhukster** [comment]
You have to upgrade Grav "first", then the admin.

**Comment by bsheen** [comment]
Please refer to the original issue post. I’d successfully upgraded Grav and Admin plugin. Just providing further info in an attempt to help (seems it only cause confusion, apologies for that)
