### ISSUE TITLE
Edit folder name in admin

### ISSUE THREAD

**Issue by Tyrion2737** [getgrav/grav-plugin-admin#144]
_From @Tyrion2737 on September 6, 2015 8:9_

For example deleting the h in home makes the cursor to jump to the end of the field.

_Copied from original issue: getgrav/grav#303_

**Comment by rhukster** [comment]
What browser are you using? i'm not seeing this in chrome/mac

**Comment by Tyrion2737** [comment]
Just tested Chrome/OS X 10.11 (15A279b) with no luck so maybe it is a 10.11-thing.

**Comment by rhukster** [comment]
can you try firefox on there?

**Comment by Tyrion2737** [comment]
Firefox works but Chrome, Opera and Safari 9 not.

**Comment by rhukster** [comment]
Ok, I can recreate in Safari (works in FF and Chrome for me) so seems to be a legit issue.  Thanks!

**Comment by Tyrion2737** [comment]
Thank you very much for your work!
