### ISSUE TITLE
Duplicate URL

### ISSUE THREAD

**Issue by petira** [getgrav/grav-plugin-admin#1440]
## **Introduction:**

The Grav uses sorting prefixes for folders (Folder Numeric Prefix) that make up the structure of the site at a specific level (Parent).

**E.g. for /root:**
/01.home
/02.about-us
/03.services
/04.contact
/other

When the Grav creating a URL, the prefix ignores and the URL of the /03.services is then http(s)://www.sitedomain.tld/services. Which is fine.

If a user wants to create a page with the same name (Folder Name) on the same level (Parent) over the Plugin Admin Panel, the Grav ignores it and redirects the user instead to edit an existing page (with the same Folder Name). Which is also fine.

## **Problem:**

When sorting prefixes (Folder Numeric Prefix) are used, the Grav when shifting pages in the administration (through the Admin Panel plugin) does not check the match of the existing pages name, respectively folders name and create duplicates.

**For example, there may be more pages named "Example" within one (Parent) level:**
/01.example
/02.example
/example

All listed pages have URL http(s)://www.sitedomain.tld/example, which is a problem. The Grav will display e.g. /01.example on the specified URL, others will be ignored.

The problem is with administration (via the Admin Panel plugin) too. Because only the page that the Grav favors can be edited (because they all have the same URL /admin/pages/home/example). There is a big risk even when the page is removed, because the Grav simply chooses.

> Note: I did not look at what the Grav determines which page is prefers.

A similar problem is when user rename a Folder Name within a specific Parent folder.

## **Solution:**

The Grav will check the page/folder names when moving/renaming if they are used in the target Folder Numeric Prefix, and if the same folder name exists, then let the user one of the following (or hard insert to the system):

1. notify the user that there is a folder with the same name in the destination parent folder and telling him to rename the moved folder first and then to move it,
2. notify the user that there is a folder with the same name in the destination parent folder and telling him that the moved folder will be renamed (e.g. contact => contact-1), ideally with the option of selecting a folder name by user,
3. notify the user that there is a folder with the same name in the destination parent folder and telling him that the Grav replace it with a prior consent (potential risk of data overwriting).

## **Risk:**

This can only be resolved at the Admin Panel plugin level, but it can't be avoided by directly editing a structure such as an FTP client, however, in this case, it can be assumed that the more advanced users are overseeing them.

> Tags: Admin Panel plugin, duplicate, URL, bug, rename, move, folder, name

**Comment by rhukster** [comment]
I can understand this could be a problem, but remember admin is purely an extra 'optional' interface. Fundamentally Grav is a flat-file system that can be 100% managed without the admin by manipulating files directly. It's possible to create an `01.example` and an `02.example` page but perhaps the `02.example` page has a custom `slug: example2` so that they are perfectly able to live together in the same site as `/example` and `/example2` URLs.  

This kind of flexibility is what makes Grav great, and it's all but impossible to determine what the user is intending to do.  There's a certain amount of user responsibility here that means the user needs to not do stupid things, or stupid results will result :) 

I think rather than trying to put in code to handle every situation, and probably stomping on people who have legitimate reasons and needs for the flexibility of Grav, some user education would save a lot of time and effort.

**Comment by rhukster** [comment]
Didn't mean to close...

**Comment by petira** [comment]
I agree with you in full. Grav is really perfect open content management system with maximum flexibility. Even so, you consider this as a suggestion for possible improvements in the future. I am convinced that a normal user would like the administrator interface to be completely user-friendly because he assumes that the system is fully controlling what he does.

However, using slug is possible, but not the ideal solution in the context of the problem. As I said, this may cause additional complications (e.g. deleting another page, the impossibility of editing pages). An advanced user will surely find the best solution, but you really do not forget the normal users ;).

**Comment by petira** [comment]
I just add that Grav has one of the best management interfaces, both graphically and user-friendly, although it is only an 'optional' interface. Therefore, when I see what it allows, I think adding duplicate checks is an easy thing for you.

**Comment by petira** [comment]
Related 'Issue': #1347
