### ISSUE TITLE
"Updat Grav now" does'nt work

### ISSUE THREAD

**Issue by Ikkache27** [getgrav/grav-plugin-admin#1443]
Hi !
I'm in localhost using xampp, i want to updat form 1.4.3 to 1.4.4, when i click on "updat Grav now" does'nt work, it shows "updating...please wait, downloading 3,49 MB", and nothing else.
Thanks for your help

**Comment by Ikkache27** [comment]
@rhukster thank's for your reply, but  when I've updated grav & plugins i found this issue that i have post it "Dashboard issue after updating Grav and plugins #2015" and i'm still waiting for the response : 

![grav dashboard issue](https://user-images.githubusercontent.com/29124164/40078108-f9161eca-5883-11e8-971b-48b3abaaf1ee.PNG)

**Comment by tyte** [comment]
Exactly same problem and dashboard view as for @Ikkache27 after latest update of Admin Plugin. "You don't have sufficient access to view the dashboard...".

**Comment by tyte** [comment]
PS I just reinstalled grav + admin package and it works again. Maybe @Ikkache27 could try that.

**Comment by jleaders** [comment]
It may be a timeout in the server config, either in PHP or Nginx. Suggest closing as config issue as updating worked fine for me.
