### ISSUE TITLE
Grav Editor Plugin by TwelveTone

### ISSUE THREAD

**Issue by moremeatlessfat** [getgrav/grav-plugin-admin#1447]
Hi,

I actually love this plugin for Grav where it allows you to edit the source files directly.

But in Chrome, there's a bug where the horizontal scrollbar is set at 100% height, so none of the file links are clickable.

![screenshot](https://user-images.githubusercontent.com/8219962/40287181-f8c2f5d2-5cee-11e8-85fe-6d7f6a3a4616.png)

![disabling the horizontal scrollbar makes the links clickable](https://user-images.githubusercontent.com/8219962/40287214-25f55752-5cef-11e8-9c6e-088f44685122.png)

Not sure if it's a plugin issue or a Grav admin issue.

Thanks,
Sharlene

**Comment by rhukster** [comment]
Sharlene, you need to post this on the issue tracker of the plugin in question.  Cheers.
