### ISSUE TITLE
Custom login frontend page does not show form fields

### ISSUE THREAD

**Issue by niccos** [getgrav/grav-plugin-admin#1448]
Hi,
I'm trying a grav 1.4.5  fresh installation.
I'm trying  plugin login and if I choose a non-default route in result page  username and password form fields are not shown.
I tried both with quark and with antimatter themes.
All settings are by default.
I changed the plugin "Login path" in "/my-login" and copied "login.md" from "user/plugins/login/pages/" to "user/pages/my-login/"
What am I doing wrong?
Thank you.
Regards

**Comment by rhukster** [comment]
Please post this on the issue tracker for login. Not an admin issue.
