### ISSUE TITLE
New version of Admin Plugin conflict js in Grav

### ISSUE THREAD

**Issue by lauroguedes** [getgrav/grav-plugin-admin#1449]
With the new version of Admin Plugin the behavior of the admin panel of Gantry 5 does not work correctly. You are giving a javascript confession, some gantry options do not work and ajax loading is blocked.

![script-conflict-js-grav-and-gantry](https://user-images.githubusercontent.com/3677780/40548179-5816bae6-600a-11e8-9131-95f170f73dd8.gif)

**Comment by rhukster** [comment]
That’s weird. Well take a look.

**Comment by mahagr** [comment]
I wasn't able to reproduce the issues (using latest admin from yesterday).

**Comment by mahagr** [comment]
@lauroguedes This is still fully working for me.
