### ISSUE TITLE
default.html.twig missing

### ISSUE THREAD

**Issue by crumblingwalls** [getgrav/grav-plugin-admin#1450]
The default.html.twig template seems to be missing, resulting in the following error message when trying to access the admin panel at: /admin: 

>  RuntimeException (400)
> Template "default.html.twig" is not defined.

When renaming another template file to »default.html.twig« the error message disappears.

The issue seems to have appeared when I tried to change users, using the »Login As« button in the »admin-addon-user-manager«-plugin. Weird thing though is that it persisted after removing the aforementioned plugin and re-installing the admin-plugin.

**Comment by crumblingwalls** [comment]
So, to clarify: Issue arises when clicking the »Login as«-button in the »admin-addon-user-manager«-plugin. A message pops up asking me whether I really want to leave the page as there are unsaved changes. I click »continue« and am presented with the error message. Uninstallation of that plugin does resolve the issue.

**Comment by rhukster** [comment]
This is not specifically a grav error.  It’s related to that’s plug-in.  Default twig template should not be required as grav really does not impose what template types must be supported by any theme

**Comment by MyluckMomentum** [comment]
How can I resolve this and revert it back?

**Comment by rhukster** [comment]
just delete the folder `user/plugins/admin-addon-user-manager`

**Comment by MyluckMomentum** [comment]
Already did that. Still same error.  :(
