### ISSUE TITLE
Cannot set errors.display to -1, leaking full backtrace

### ISSUE THREAD

**Issue by tribut** [getgrav/grav-plugin-admin#1452]
When the admin interface is used to set the config setting `error.display`, it is impossible to set it to `-1 (System error)`. The yaml file after saving looks like this:

    errors:
      display: '-1'

Note that display is set to the **string** `-1` due to the quotes. Grav [later checks the setting using `is_int`](https://github.com/getgrav/grav/blob/03a0c42795f45b95d20bd74ba2bd6a317ad23c2e/system/src/Grav/Common/Errors/Errors.php#L29) and then discards the value.

This is an information disclosure security vulnerability, because Grav falls back to the full backtrace(!) when the user presumably wanted to make sure to leak as little information as possible.

**Comment by rhukster** [comment]
What version of grav? This has never been an issue before.  I will need to investigate why this is happening now.

**Comment by tribut** [comment]
Sorry for not mentioning versions: Grav v1.4.5 - Admin v1.8.2

**Comment by rhukster** [comment]
Fixed here: https://github.com/getgrav/grav/commit/636bc97d29376928c45678a11bbf684b64e5aab5
