### ISSUE TITLE
admin error

### ISSUE THREAD

**Issue by Lablnet** [getgrav/grav-plugin-admin#1455]
when i click layout i redirect to logout , when i re-login then go again layout its show error

![screenshot 275](https://user-images.githubusercontent.com/27757785/40636522-c7e60096-6318-11e8-9e4e-28dafed9572b.png)

**Comment by rhukster** [comment]
What do you mean by clicking “layout”?

**Comment by Lablnet** [comment]
sorry !
wrong typing...
when i click logout i redirect to login , then i re-login then logout its show following above error
