### ISSUE TITLE
Image won't upload in newly created list

### ISSUE THREAD

**Issue by StylishUnicorn** [getgrav/grav-plugin-admin#1458]
I have tried to emulate a gallery, so I can add captions. You can add an image which is a _list_. This has two children: _text_ and _file_. Ive tried on a fresh install of grav and it's still happening.(local and live)

If you create a list then try to upload the image you get the error below. But if you add some text to a file inside the list then save, then go back and upload an image it uploads fine. 
> An error occurred while trying to upload the file newimg.jpeg
> Unable to upload file : 

If it helps I also got a different error in the previous version of admin (something like this, remembering from memory):
> An error occurred while trying to upload the file newimg.jpeg
> Mime type "" is not a supported ""

**Blueprint:** 

`            

              form:
                fields:

                  tabs:
                    type: tabs
                    active: 1
                    fields:

                      header.custom.events:
                        type: tab
                        title: Events
                        fields:

                          settings:
                            type: section
                            title: Header Content
                            underline: true

                          header.custom.events.pagetitle:
                            type: text
                            label: Heading
                            size: large

                          header.custom.events.pagesummary:
                            type: textarea
                            label: Summary
                            size: large

                          event:
                            type: section
                            title: Events
                            underline: true
                            
                          header.custom.events.list:
                            type: list
                            style: vertical
                            btnLabel: Add Event
                            sort: true
                            fields:
                              
                              eventcontent:
                                type: section
                                title: Event Content
                                underline: true   

                              .heading:
                                type: text
                                label: Heading

                              .description:
                                type: textarea
                                label: Description
                                rows: 5

                              gallerysection:
                                type: section
                                title: Gallery
                                underline: true                  

                              .gallery:
                                type: list
                                style: vertical
                                btnLabel: Add Image
                                sort: false
                                fields:

                                  .caption:
                                    type: textarea
                                    label: Caption
                                    style: vertical
                                    rows: 3

                                  .image:
                                    style: vertical
                                    type: file
                                    label: Image (Square - 400px x 400px)
                                    destination: 'theme@:/images/pages/events'
                                    multiple: false
                                    limit: 1
                                    avoid_overwriting: true
                                    filesize: 3       

              `

Thanks a lot for your continued support of Grav, you're doing a really good job!

**Comment by mahagr** [comment]
This issue is duplicate to #1465 and has just been fixed.

**Comment by StylishUnicorn** [comment]
Hi,

I've copied the develop branch to overwrite the older admin package through FTP. This issue is still persisting, and I've read the other issue and it does seem they're different.

**Comment by mahagr** [comment]
Can you recreate the issue with a newly installed Grav site without any extra plugins in it?

**Comment by StylishUnicorn** [comment]
Recreated the issue with a fresh install. I dug a little deeper and it does seem this is the same as #1262. Do you think there is any workaround to this?
