### ISSUE TITLE
Media deletion confirmation remains open

### ISSUE THREAD

**Issue by Salvatos** [getgrav/grav-plugin-admin#1459]
After deleting a media file from a page edit screen (specifically a PDF in my case), the confirmation pop up remains open after clicking Continue. Clicking Cancel (after deletion has been confirmed) or outside the modal closes it. I believe it shoud close on its own.

This is on Firefox 60 on Linux Mint.

**Comment by w00fz** [comment]
I can't reproduce this. Is it still an issue?

**Comment by Salvatos** [comment]
Seems fixed for me under Grav 1.5.5.
