### ISSUE TITLE
Feature request: Allow plugins to hook into admin panel

### ISSUE THREAD

**Issue by Sommerregen** [getgrav/grav-plugin-admin#146]
At the moment the admin plugin does not allow adding custom (admin) routes, pages and menus injected and handled by plugins. It would be good to have certain hooks a plugin could be used i.e. `onAdminInitialized`, `onAdminPageInitialized`, `onAdminMenu` etc.

As far as I can see listing additional entries is possible via defining a [`template/partials/nav-pro.html.twig`](https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/templates/partials/nav.html.twig#L54), but I do not want to provide one, since this seems to be intended for the pro version.

Do I have other possibilities to show a menu entry in the Grav Admin panel and provide a custom page?

**Comment by flaviocopes** [comment]
Was working right on this yesterday. 

I made an example plugin that plugs in the admin to provide its own view. It's an experimental thing for now. A couple of changes are needed in Admin: allow pages added by plugins, and a way to inject nav menu items.

We could have a `onAdminTemplateNav` (name hints welcome) event, to which we can provide the Admin plugin a label (already translated) and a route.

I'll post a PR today as a possible implementation

**Comment by Sommerregen** [comment]
@flaviocopes Glad to hear! :-D I will test it as soon you and probably @rhukster provide a way for me to hook my own plugin into this. Thanks and keep me updated!

**Comment by flaviocopes** [comment]
PR https://github.com/getgrav/grav-plugin-admin/pull/148 adds this possibility. Waiting for @rhukster's opinion if it's a good way to do it. Example plugin using this method: https://github.com/flaviocopes/grav-plugin-data

**Comment by rhukster** [comment]
done
