### ISSUE TITLE
Frontend registration error

### ISSUE THREAD

**Issue by catchlight** [getgrav/grav-plugin-admin#1460]
Just updated to 1.4.5 and when trying to register a new user on the frontend at /user_register I get the following error…

> Server Error
> Sorry, something went terribly wrong!
> 
> 0 - Username "test_user" already exists, please pick another username
> For further details please review your logs/ folder, or enable displaying of errors in your system configuration.
> Nothing in the logs and there is no page for the user at /user/accounts. I can register users via the admin backend no problem.
> 

I tried with a fresh Grav install and get the same error. No problems with my previous version 1.3.10.

Thanks,
Howard

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-login/issues/159

**Comment by ronCYA** [comment]
Please re-open this as it's not a duplicate. #159 relates to creating a new user with the registration form.

This issue relates to loading the registration page/form itself. I am having the same issue on a fresh install.
