### ISSUE TITLE
Checkbox field template id/value

### ISSUE THREAD

**Issue by sebastianbaumann** [getgrav/grav-plugin-admin#1462]
Hey guys,

currently im customizing the form templates and noticed following issues.
In line 12 of the `checkbox.html.twig` template `value`  is called, but never defined in the template ? `value="{{ value|join(', ') }}"`
How I'm supposed to set the value for checkbox fields? Changing it to `field.value` works.

Next question. `set id` is the same like for the radio buttons, but is there any way to add `key` to checkboxes, because right now every checkbox id will end with `-`, e.g. `id="myid-"`.
`    {% set id = field.id|default(field.name) ~ '-' ~ key %}`

**Comment by rhukster** [comment]
The parent form.htm.twig that includes the field should already be doing this:

```
    {% set value = form.value(field.name) %}
    {% include "forms/fields/#{field.type}/#{field.type}.html.twig" ignore missing %}
```

**Comment by sebastianbaumann** [comment]
Yes you're right. Overlooked that part… sorry! Anyways checkboxes are currently not working inside fieldsets, like I mentioned here https://github.com/getgrav/grav-plugin-form/issues/262
Maybe you can have a look at it, please.

**Comment by NicoHood** [comment]
This can be closed
