### ISSUE TITLE
Latest update breaks instance

### ISSUE THREAD

**Issue by tlflow** [getgrav/grav-plugin-admin#1464]
Logged in to the admin of my website and did an update for admin and login plugins. Now I get an error page where admin login used to be. 

Logs say admin and login are enabled but not found... so I tried clearing cache and going through CLI to install admin and it says following dependencies need to be installed... Login. It aborts installation if I try to go forward so I tried to just install Login and it says login is already installed.

What should I do to get around this issue?

**Comment by rhukster** [comment]
How did you update?  This is the first report of an error during the update of this version, and as nothing really fundamentally changed in the installation process, i'm not sure what happened.  Is the admin plugin still installed?

**Comment by tlflow** [comment]
@rhukster I just clicked the "update all plugins" button. I remember getting a few error alerts (one being about forms) and the admin page just churning...I guess it never found dependencies.

admin says it's not installed according to the plugin list (when I type "bin/gpm index") but I do see files under "user > plugins > admin". This is really strange as I was able to update the same plugins for other sites with the same setup.

**Comment by tlflow** [comment]
So... I just started over. I wasn't that far in the dev of the site so it wasn't that bad. But in doing so, I tried to do the same thing (clicking the "update all plugins" button) and I get the same result (see screenshot). Just to give you an idea of what I'm doing... I'm running my dev off of an MAMP htdocs folder (localhost/name-of-my-grav-folder). I've done a few plugin installs and updates here and haven't run into any problems with other plugins. Also, I don't seem to have any problems updating plugins on the actual prod server. 

![update-issue](https://user-images.githubusercontent.com/415773/41600049-d4b4984c-73a2-11e8-8778-c56664751789.JPG)

**Comment by rhukster** [comment]
Do you have those 3 plugins installed? (line 596)

**Comment by tlflow** [comment]
Well, sort of. According to "bin/gpm index" only form and email are installed but login isn't.
- Form v2.15.0
- Email v2.7.1

But, when I try to install "php bin/gpm install login" it says "The package login is already installed, overwrite? [y|N]"

**Comment by rhukster** [comment]
Seems login is not properly/fully installed, so just pick `Y` and reinstall it.

**Comment by tlflow** [comment]
Oh man.... I'm pretty sure I just figured out what the problem was all along. More than likely, it's Atom not allowing me to make changes because of file/folder permissions (duh). I closed everything, did update via the gpm and it worked fine. Makes sense, since we're talking about local files and I wasn't running into same problems with prod environment. 

Thanks for your help!
