### ISSUE TITLE
Invalid Security Token

### ISSUE THREAD

**Issue by yasirjani** [getgrav/grav-plugin-admin#1466]
Hi, I am facing problem in login to the admin with an error message (Invalid Security Token). I read all the post about this and tried all the way to solve this but I am not getting ride on this error. Please help

**Comment by rhukster** [comment]
What posts? have you checked everything mentioned in this document: https://learn.getgrav.org/troubleshooting/invalid-security-token ??

Hae you ever had this working? What platform are you running on? apache/nginx/etc? please provide as much details as possible.

**Comment by DominiqueVial** [comment]
Still have problem on localhost...

**Comment by DominiqueVial** [comment]
@rhukster 
If follow the link you provider earlier. Unfortunately this is kind of cryptic. For item 4, PHP tmp path setup the Grav documentation is empty...
As I wrote before is it possible to deactivate all this behavior during local development?
