### ISSUE TITLE
No access after update

### ISSUE THREAD

**Issue by AtjonTV** [getgrav/grav-plugin-admin#1468]
I just updated Grav to 1.4.5 and the Admin plugin to 1.8.3 and now I don't have access to the Dashboard on the admin account.

When I login, the only thing I see is this: ![You don't have sufficient access to view the dashboard...](http://dl.atvg-studios.at/_images_png/grav_error.png)

(I am using the Antimatter Theme 2.1.2)

I don't have access to the Terminal or any error logs of the server.

I hope someone can help me.

**Comment by rhukster** [comment]
I just tested upgrading a 1.3.10 install of Grav with 1.6.7 version of the Amin plugin.  Enabled 2FA, logged out and back in to make sure that was working.

Then upgraded to Grav 1.4.5, after this I upgraded all the plugins including Admin 1.8.3 and Login 2.7.1, and I remained logged in with 2FA enabled.  No errors. No problems, worked as expected.

There was some significant revamps of 2FA in Grav 1.4/Admin 1.8 - but it should make things more reliable, not less and we've not seen the issues you are reporting.

Can you please check ALL the plugins are updated to their latest versions?

**Comment by AtjonTV** [comment]
I updated before the issue occured, now after I loggedin the Login Plugin was back on the before-update version. It looks as the update failed without warning, but now after a second try on updating it it finally works with no problem.

My issue is now resolved, thanks for the quick response!

*PS. You guys make a great Job!*

**Comment by JWHBerlin** [comment]
I have the same issue, but I don't use any special plugins. I have no idea what to do. If I enter /admin/user/USERNAME I only can change user details? 

Where can I check I there is a plugin the reason for the plugin? Where can I deactivate something if I think, it causes the problem?

**Comment by AtjonTV** [comment]
The overview of all plugins is at /admin/plugins. To disable a plugin you would need to go to /admin/plugins/PLUGINNAME and click the disable button.

As i just saw there is a new update:

> Grav 1.4.6
Admin 1.8.5
Login 2.7.3

So if you go to /admin/plugins and you see that the Login plugin has an update, make the update and see if it fixed your issues.

If you are on the newest version try to disable 2FA (if enabled), if that fixed the issue i recommend to remove the Regex for the password and use a very secure password (20+ chars, upper- and lower-case letters, numbers and special chars), as long as the issues holds on with 2FA enabled.

I got the issue because the Login plugin i was using, wasn't supporting 2FA as it seemed. Disabling 2FA on my account did the trick fix the issue so i was able to pull the update and after the update 2FA worked fine.

If your issue isn't fix after all updates i can't help any more and a developer of Grav needs to take over ..

Anyways i hope i helped ;D

**Comment by JWHBerlin** [comment]
Thanks a lot: That saved my site. Thank you: The "login plugin" was the source of the problems. I downloaded the master branch, load it via ftp up and changed the directory name - everything is working again. I disabled 2FA (Don't knew about before...) and seems my password was strength enough.

**Comment by AtjonTV** [comment]
No problem, im happy it worked out for you.

**Comment by scan5415** [comment]
Thanks for all of your information. I updated the Login Plugin by hand and the issue was resolved.
I guess, the automaticly updater didn't update the Login Plugin.

**Comment by foufrix** [comment]
> Thanks a lot: That saved my site. Thank you: The "login plugin" was the source of the problems. I downloaded the master branch, load it via ftp up and changed the directory name - everything is working again. I disabled 2FA (Don't knew about before...) and seems my password was strength enough.
> 
> Thank you very much!

Save mine as well ! Thanks !
