### ISSUE TITLE
Uploading an image to page media throws a WebKitBlobResource error 4. with latest safari.

### ISSUE THREAD

**Issue by iamlinkus** [getgrav/grav-plugin-admin#1469]
When I try to upload an image file through the admin it shows up as an empty file (also empty image files in the file system) and console throws this:

`The operation couldn’t be completed. (WebKitBlobResource error 4.)`

The image I want to upload is [this](http://dev.monotwo.com/monotwo2018/images/uploads/work/trafi/trafi-intro-device.png).

Grav version v1.4.5
Admin version v1.8.4
Safari version 11.1.1 (13605.2.8)

Any ideas why this started happening? It's also impossible to delete the file in normal edit mode, only by switching to expert and deleting it fixes the page.

Sometimes even got an error in the console that `trafi-intro-device@2x.png` was not found (even though I never uploaded anything with the retina suffix (@2x). I usually upload `-retina` suffixed retina files, because grav admin seems to not like files with an @ in their name.

**Comment by rhukster** [comment]
Does it work for you with other browsers? Chrome/ Firefox?

**Comment by iamlinkus** [comment]
@rhukster I can confirm that chrome works as expected. Seems like it's just a safari issue.

**Comment by jannejava** [comment]
Did you find a solution to this?

**Comment by rhukster** [comment]
It works fine in Safari 12 on Mojave, as well as Chrome, Firefox etc. Can you guys try with an updated Safari version or Technology Preview release?

https://developer.apple.com/safari/download/

**Comment by jannejava** [comment]
I cannot re-create this myself either but got screen dumps from a user (Safari 12) with this error. The only I can find regarding this is that the error can happen when you try to upload a folder in Safari. Works in Chrome BTW.

**Comment by rhukster** [comment]
I had Googled and found the same issue reported in many places regarding uploading of folders.

**Comment by thomasliew** [comment]
I've encountered this kind of problem, if you are using too much memory in Safari (you can see it in the timeline), then there is a certain chance that this will happen, and it will not occur after killing Safari and trying again.
When I first cycled through more than 2000 photos, I found that Safari was using more and more memory, and I tried to put var img = new Image() in the loop out of the loop, and the memory usage stabilized. It also solves the problem you described. Hope it helps.

<img width="1679" alt="image" src="https://github.com/getgrav/grav-plugin-admin/assets/13864621/bb05ea01-5687-4128-899b-be6feac04b78">
