### ISSUE TITLE
Enhancement: Support fieldset and/or accordion form field

### ISSUE THREAD

**Issue by Sommerregen** [getgrav/grav-plugin-admin#147]
For plugins with a many options it would be good to structure them. Currently this is possible with the `section` form field only. Is it possible to provide a grouping fieldset? Further it would be nice if such form field could be opened and closed like the one for the plugin list.

**Comment by rhukster** [comment]
If you create the field, i'de gladly consider adding it.  Just look at section, tab, tabs, columns, etc.  These are all examples of structured field types.

**Comment by Sommerregen** [comment]
Ok, this PR may take a while, since I'm currently running out of time. But I will add as soon as I have some minutes left.
