### ISSUE TITLE
User and Group Permissions not working

### ISSUE THREAD

**Issue by HenroRitchie** [getgrav/grav-plugin-admin#1470]
I cannot get user and/or group permissions to work. Furthermore, dynamic page visibility is also not working. I implemented the guides to define access to a page by user or group and neither is limiting the access. All access limited pages should in theory not be visible from the outside (without any use logging in) but they are in the menu. The content of the pages are hidden.

**Comment by rhukster** [comment]
duplicate: https://github.com/getgrav/grav-plugin-login/issues/166
