### ISSUE TITLE
Link to changelog for plugins?

### ISSUE THREAD

**Issue by CSixtyFour** [getgrav/grav-plugin-admin#1474]
When there's an update to a plugin (or core Grav) one of the first things I want to check is the changelog, especially for breaking changes. Maybe we could have a direct link to the changelog on each plugin so that the link would be readily accessable when there are updates? Near the "Bug Tracker" field would seem a natural place. 
I can raise a PR if this sounds useful.

**Comment by w00fz** [comment]
This is something we are working on. It will be available on both admin, cli as well as from the website

**Comment by CSixtyFour** [comment]
Ok cool - looking forward to the future - I'll close off this request now.
