### ISSUE TITLE
Future request: disable numerical prefix when creating new folder

### ISSUE THREAD

**Issue by shigemk2** [getgrav/grav-plugin-admin#1475]
So far, folders' name have numerical prefix when creating new folder.
I want to disable numerical prefix.

**Comment by rhukster** [comment]
Pages with numerical prefix are `visible` by default, which means they show up in a menu.  The default behavior in the admin plugin is  'auto', which means, Grav tries to guess the page type based on the surrounding pages.

If you want a page to not have a numerical prefix, ie, `non-visible`, simply select `visible = false` in the new page modal, or set `visible: false` in the advanced options of a page.
