### ISSUE TITLE
Float Twig Error

### ISSUE THREAD

**Issue by amatilda** [getgrav/grav-plugin-admin#1478]
I apologize in advance for bad english.
An error occurs when the "Override locale" option is turned on and if there are multiple languages on the site.

When working with fractional numbers in Twig, the dot replaces the comma when the site is not English.

I do not know, maybe Twig can be guilty, but all the same I decided to write here.

![01](https://user-images.githubusercontent.com/40815843/42257445-3b0d305a-7f5f-11e8-82d2-2f5c276f9463.png)
![02](https://user-images.githubusercontent.com/40815843/42257461-43e4a85c-7f5f-11e8-9399-5dbe39d03111.png)
![03](https://user-images.githubusercontent.com/40815843/42257467-4abe73ba-7f5f-11e8-92d6-37be8837bf9f.png)
![04](https://user-images.githubusercontent.com/40815843/42257473-4f8395f6-7f5f-11e8-8ce7-fdabb8aa0de8.png)

**Comment by AmauryCarrade** [comment]
As a workaround, you could try to use the [`number_format`](https://twig.symfony.com/doc/2.x/filters/number_format.html) Twig filter.

```twig
{{ (iSearchHeight + 0.2)|number_format(2, '.', '') ~ 'rem' }}
```

**Comment by rhukster** [comment]
I'm a bit confused about this scenario and how it relates to the admin plugin?

It seems like the locale is being set, then you have some CSS in Twig on the frontend that is setting some inline style, and this CSS is being converted in the browser to the wrong output as the locale is set?  

This sounds like a theming question?
