### ISSUE TITLE
Fetch failed on built in php server.

### ISSUE THREAD

**Issue by iamlinkus** [getgrav/grav-plugin-admin#1485]
I've managed to serve grav using the built-in php server, everything seems to work great, except that the admin panel throws the errors below on every admin panel page:

`Warning:  require(index.php): failed to open stream: No such file or directory in /Users/XXX/grav/system/router.php on line 24`

`Fatal error:  require(): Failed opening required 'index.php' (include_path='.:') in /Users/XXX/grav/system/router.php on line 24`

Serving grav using the system/router.php.

Any ideas what could be the problem?

**Comment by rhukster** [comment]
What version of php is this?

i've tested with PHP 5.6, 7.0, and 7.2 with this command:

```
php -S localhost:8888 system/router.php
```

Works fine in admin, no issues loading anything.

**Comment by iamlinkus** [comment]
PHP version 7.1.16

**Comment by AlexPernot** [comment]
Bumping this issue since it's potentially the first result for googling the error message: you have to make sure the working directory (the folder from where you run the command) is the grav root folder where index.php is, since the include path is `.`, AKA the working directory.

**Comment by sundayz** [comment]
If you're using PHP Built-in web server with PhpStorm to try out Grav like I am, these settings worked:

![image](https://user-images.githubusercontent.com/11685806/63714050-cfb54d00-c838-11e9-9448-8422ea87e0b8.png)
