### ISSUE TITLE
Two pages in different languages are saved at the same time

### ISSUE THREAD

**Issue by kirillaristov** [getgrav/grav-plugin-admin#1489]
Open a page by giving its url (example-com/en/admin/pages/page-content-must-be-in-english-but-opened-in-russian). But instead of English content, the content in the second language (Russian) is opened. This is because I have just edited a page in another language in another tab.

If two tabs with one page are open, but in different languages, then after saving the first one, the second one switches to another language.

While saving two pages in different languages, I get one version for both languages.

_How can I turn off keeping of the main language in the administration panel? How can I remove the main language from the administration panel, and make two equivalent?_

Thank you!
(using Grav v1.4.7 - Admin v1.8.6)

**Comment by rhukster** [comment]
This is a bit of a limitation of the current admin plugin.  The active language is stored in session, so two tabs open at the same time will have weird results like the one you are seeing.  It's not really a simple fix, but something we plan to address when we rebuild the admin as part of Grav 2.0

**Comment by mahagr** [comment]
Should be fixed in Admin 1.10.
