### ISSUE TITLE
Can't type Japanese on iOS

### ISSUE THREAD

**Issue by kyo5884** [getgrav/grav-plugin-admin#1490]
It looks input method is disabled in markdown editor, so I can not type Japanese.
iOS' Flick keyboard can type Hiragana but cannot type Kanji.
![gif](https://user-images.githubusercontent.com/286439/43173962-9b76f2d4-8ff2-11e8-912c-1cd5fd52dd49.gif)

**Comment by kyo5884** [comment]
This is normal behavior on iOS notes app.
![output](https://user-images.githubusercontent.com/286439/43174125-639e95e6-8ff3-11e8-8038-04246de28373.gif)

**Comment by w00fz** [comment]
This unfortunately is a known issue with codemirror. Nothing we can do. We are considering switching to something different or at the very least offer a traditional Textarea to switch to if codemirror doesn't work.
