### ISSUE TITLE
Cant edit contentpages properly

### ISSUE THREAD

**Issue by Theenoro** [getgrav/grav-plugin-admin#1503]
So since the last update ( 1.5.1 ) I can't change the content of the pages properly.  
If I edit the page in normal mode, the page keeps it's old content. But if I edit it in expert mode it works normally.

~ edit
my currently guess is, that the php memory limit was a bit to low for the update, that some parts of the interface didn't set up properly or so.
after I made in over the console a force update it worked, after that i canged the php mem limit from 128M to 256M

**Comment by rhukster** [comment]
Thanks for the update.. I couldn't replicate this issue.  256M is the recommended (and default size) for most PHP7+ installations.

**Comment by nsteinmetz** [comment]
Thanks, I also just hit the bug - but incresing to 256M seems not enough (I'm in a Docker context). How did you guess it was a memory issue ?

Maybe I also need to add the yaml extension and a few others ?

**Comment by nsteinmetz** [comment]
I added the apcu, opc and yaml modules and the issue remains. My issue seems focues on modular content - for normal content, it works well

**Comment by rhukster** [comment]
Can you guys please provide me a sample blueprint for the page type you are trying to edit? I think it's related to that.

**Comment by nsteinmetz** [comment]
Pasted in #1507

**Comment by rhukster** [comment]
Still having troubles replicating, will try some other scenarios soon.

**Comment by nguyenchihien** [comment]
If you're using "Modular Page" with "Text" template.  Maybe you try to delete the line in Text.yaml (folder blueprint)
` uploads:
              label: Page Media (first one will be displayed next to your content)`
and you new text.yaml will be like this:
`title: Text
'@extends':
        type: default
form:
  fields:
    tabs:
      fields:
        advanced:
          fields:
            columns:
              fields:
                column1:
                  fields:
                    name:
                      default: modular/text
                      '@data-options': '\Grav\Common\Page\Pages::modularTypes'
            overrides:
              fields:
                header.template:
                  default: modular/text
                  '@data-options': '\Grav\Common\Page\Pages::modularTypes'
        content:
          fields:
           header.align:
              type: select
              label: Image position
              classes: fancy
              default: left
              options:
                'left': 'Left'
                'right': 'Right'`
This works for me.
