### ISSUE TITLE
Form in Appi theme

### ISSUE THREAD

**Issue by starfoxik** [getgrav/grav-plugin-admin#1505]
I was installed Appi theme and edit it for my work and found the problem. Form is not working from phone. I was try to submit from laptop, but its working 50/50 - sometimes sent and sometime doesnt sent anything. Log doesnt save any problem and form have this code: 
` -
            save:
                fileprefix: subscription-
                dateformat: Ymd-His-u
                extension: txt
                body: '{% include ''forms/data.txt.twig'' %}'`
Nothing is saved here too. So, I dont know what to do. Any idea?

**Comment by rhukster** [comment]
I think this is a bug/question for Appi theme, or perhaps Form plugin... not Admin plugin.  Please open in one of those places.
