### ISSUE TITLE
1.5.1 - Can't edit *modular* content properly

### ISSUE THREAD

**Issue by nsteinmetz** [getgrav/grav-plugin-admin#1507]
Hi,

Using Grav 1.5.1 + admin plugin 1.8.9.

I thought I was having the same issue as https://github.com/getgrav/grav-plugin-admin/issues/1503. So I switched to 256M for memory, added the yaml, apc, opcu and redis extensions but still. When I save modular content from the admin in normal mode it does not work.

I don't have special logs to get some clue - so if you have some ideas, I'm interested !

I'm on PHP 7.2.9 with nginx on top of it, using docker containers.

Thanks,
Nicolas

**Comment by rhukster** [comment]
Can you please provide a copy of the modular blueprint you are tryhing to save?

**Comment by nsteinmetz** [comment]
Here it is : 

```title: Text
'@extends': default

form:
  fields:
    tabs:
      fields:
        advanced:
          fields:
            columns:
              fields:
                column1:
                  fields:
                    name:
                      default: modular/text
                      '@data-options': '\Grav\Common\Page\Pages::modularTypes'
            overrides:
              fields:
                header.template:
                  default: modular/text
                  '@data-options': '\Grav\Common\Page\Pages::modularTypes'
        content:
          fields:
            uploads:
              label: Page Media (first one will be displayed next to your content)
            header.image_align:
              type: select
              label: Image position
              classes: fancy
              default: left
              options:
                'left': 'Left'
                'right': 'Right'
              type:```

**Comment by nsteinmetz** [comment]
@rhukster am I wrong or re-reading the docs, the blueprint format changed a little bit - https://learn.getgrav.org/forms/blueprints/example-page-blueprint

Could it explain the issue ?
