### ISSUE TITLE
change Site tile

### ISSUE THREAD

**Issue by ashokv54** [getgrav/grav-plugin-admin#1510]
hi team,

i'm new to Grav but i need to change belwo site title in home page.
![image](https://user-images.githubusercontent.com/29498166/45169693-c859f580-b21b-11e8-9f35-5a9d2e8a8a6f.png)

**Comment by rhukster** [comment]
Best if you ask this on our slack channel: https://getgrav.org/slack

This issue tracker is intended for bugs and issues related to the admin.  Thanks!
