### ISSUE TITLE
Question: Modular pages with different number prefix and same folder name 

### ISSUE THREAD

**Issue by joville** [getgrav/grav-plugin-admin#1513]
I had a problem with a grav site using using modular pages with number prefixes AND SAME folder name, e.g. 01._module, 02._module. I made the observation that this can lead to not working properly in editing in admin. The page tree have been always right, but opening a modular page in admin did often show the wrong content even if you have different prefixes.  Therefore I am asking wether this behavior is by design that the prefix number is only for the ordering alone and therefore the folder name have still to be unique? Without prefix the case is clear (from the docs: "If the slug is not set in the page, Grav falls back to using the folder name (without any numerical prefixes)." Thanks for any clarification!

**Comment by rhukster** [comment]
basically it comes down to the fact that the page folder directly corresponds to the URL slug.  If you have two modular pages (or any pages in grav) with the same folder name (irrespective of numeric prefix or `_` for modular), you will have conflicting URLs.  

Being flat-file based, there's nothing to stop you from doing this via the files directly, so Grav admin doesn't stop you either.  But don't do it, it won't work :)

**Comment by joville** [comment]
Thanks, I have this sorted out now. :)
