### ISSUE TITLE
Grav Summary delimiter has stopped working after Gantry5 update on 10-11 September 2018 ?

### ISSUE THREAD

**Issue by withindale** [getgrav/grav-plugin-admin#1514]
Pages display summary before '===' and content after, following Gantry 5 updates 10-11 September 2018 

Configuaration: int 300 characters; format short.

Documentation: 
format: short -- Detect and truncate content up to summary delimiter position.
size: int -- Always truncate the content after int chars. If a summary delimiter was found, then truncate content up to summary delimiter position.

Behaviour: as described in documentation until 10 September 2018.

**Comment by withindale** [comment]
10. Cookbook > Twig Recipes > #4

Ian Russell

**Comment by withindale** [comment]
Gabriel

Trust you have solved the problem but, if not, I found the same thing again
today (after an update!). The reason was I was using a default page when
the slice only cut off the summary in blog list and blog item pages.

Was your problem something like that.

Ian Russell

**Comment by ganar** [comment]
@withindale [I think is something not working as it should in the Quark template](https://github.com/getgrav/grav-theme-quark/issues/57). I'm working on my own template —which is inheriting from Quark— and calling {{page.summary}} does not honor the delimiter.

Today I found that the _blog template item_ in Quark does honor the delimiter. I will checkout how the template does it and comment here.

**Comment by bonnebulle** [comment]
same here...
```
Lorem ipsum dolor....

===

![img](url)
```
Showing the image...
