### ISSUE TITLE
Theme Inheritance of Quark => Theme Variables not inherited / available

### ISSUE THREAD

**Issue by iocron** [getgrav/grav-plugin-admin#1516]
I've used bin/plugin devtools new-theme and activated the new theme (e.g. mytheme), but the variables of quark.yaml arent't loaded into the new theme, therefore some stuff is missing. I've added the variables of quark.yaml manually to mytheme/mytheme.yaml, but i can't edit those settings in the admin panel (themes->mytheme).

**Comment by rhukster** [comment]
Theme variables are very much tied to the theme in question.  They are not intended to be inherited.  You should copy the default variables yaml from quark to your custom theme, and edit them as required.

BTW, this is not an admin plugin issue.
