### ISSUE TITLE
How to set up custom admin-pages wich stores data via blueprint

### ISSUE THREAD

**Issue by mgollmer** [getgrav/grav-plugin-admin#1517]
Hello there, 

I'm trying to setup some custom pages in the admin plugin. I already looked up the article about setting up custom blueprints for custom  YAML-files inside the config folder.

Is there a way/example of how I can copy this behaviour for my on custom admin page? 

For example creating a `myplugin/blueprints/data/details.yaml` blueprint-file and then refers to it in my custom page so I can store my own data inside the `user/data` folder.

Regards, 
Michael

**Comment by mahagr** [comment]
In Grav 1.7/Admin 1.10: https://learn.getgrav.org/17/advanced/flex
