### ISSUE TITLE
List multi upload field numbering bug

### ISSUE THREAD

**Issue by piramix** [getgrav/grav-plugin-admin#1519]
Hi ,

When I add another element in sublist there's a problem in numbering the first element
is header.lista.0  . When I add another file_upload element in the sublist the "header.lista.0" is not numbered properly it appears in data-graf-file-settings like that "header.lista.1.file_upload.1.file" so it looks like index id from file_upload is copied as header.lista index.

example:
`
data-grav-file-settings="{"name":"header.lista.3.file_upload.3.file","paramName":"data[header][lista][0][file_upload][3][file]","limit":1,"filesize":64,"accept":["*"],"resolution":null,"resizeWidth":null,"resizeHeight":null,"resizeQuality":null}"
`

yaml file in theme:

`extends@: default
child_type: item

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab
          unset@: true
        test:
          type: tab
          title: Przetargi
          ordering@: -2
          fields:
            header.lista:
              name: buttons
              type: list
              label: Przetarg
              fields:
                .text:
                  label: Nazwa
                  type: text
                .file_upload:
                  type: list
                  label: Plik
                  fields:
                    .plik:
                      label: Nazwa
                      type: text
                    .file:
                      type: file
                      label: Plik
                      destination: 'user/themes/quark/przetargi/'
                      accept:
                        - '*'
`

**Comment by rhukster** [comment]
You cannot nest fields inside a list.  That is probably the problem you are running into.

**Comment by piramix** [comment]
Why ? A nested list works. But there's a problem with the reindex function in javascript. It is reindexing two keys intead the last one. When I add item one by one and save them then I can add files in the next step. But when I try to do everything in one step I get an error.
