### ISSUE TITLE
Backup button links to wrong URL

### ISSUE THREAD

**Issue by srameko** [getgrav/grav-plugin-admin#1521]
My site is on https, when i backup my site and try to download the backup it follows me to this link

`https://www.mysite.com:80/admin/task:backup/download:XXX`

I dont know where, but Grav still thinks that I use only HTTP. If I remove `:80` it works.

**Comment by rhukster** [comment]
Will look into this.

**Comment by rhukster** [comment]
I'm trying to recreate this but am having trouble.  On a test site of mine with `https://` enabled, the url is also a full HTTPS link.

**Comment by rhukster** [comment]
OK, i've actually changed this to use a relative link, so should work no matter what going forward.
