### ISSUE TITLE
Very long time to save pages from admin plugin

### ISSUE THREAD

**Issue by fsancho** [getgrav/grav-plugin-admin#1523]
When saving pages from admin, it takes a very ong time to save data, and admin gets stall for a long time. The other CMSs in the server work fine, and there is no PHP process executing during this process, and no errors in log.

**Comment by rhukster** [comment]
Do you have GitSync installed?  What about other plugins?

**Comment by fsancho** [comment]
Yes, it was installed, because I was using the Learn2 Git Sync v1.10 theme. At the beginning it was fine, saving with no problems.
Then, I removed every plugin in order to know if any of them was behind the problem, and only "error" and "problems" plugins are enabled, but the issue with save times is still there.

**Comment by rhukster** [comment]
Are you sure gitsync is actually disabled? It does sound like there's something still intercepting the save process.

**Comment by fsancho** [comment]
Dear @rhukster, I have found the problem, but not the solution: it is the "TNT Search" plugin, and the same problem is reported among the issues of that plugin (it is still an open problem), so I will be looking there for a solution.
Thanks for your help!!!

**Comment by fsancho** [comment]
Thanks!, updated, and I disabled the page events... it works fine now!. I will index manually, it is not a big problem.
Great support from you, thanks a lot!
