### ISSUE TITLE
Admin crashes when a new page is created with a special character in the name

### ISSUE THREAD

**Issue by samingle** [getgrav/grav-plugin-admin#1524]
In trying to bring our previous site’s blog posts over, we found that the grav admin gets itself into an infinite loop, and eventually crashes when trying to create a page with a special character in the title.

To reproduce:
1. In the title field, type `How’s it going?` (or copy/paste this, if you're not familiar with how to type right single apostrophes on whatever OS you're using)
2. Press continue

**Comment by rhukster** [comment]
Ah its the `’`... its not a standard single tick. I can definitely replicate it

**Comment by rhukster** [comment]
Fixed in develop
