### ISSUE TITLE
Add Folder -> Foldername Field -> Slug Assistant

### ISSUE THREAD

**Issue by jens-t** [getgrav/grav-plugin-admin#1525]
When one wants to add a folder in the pages section, there is a "Folder Name" field, that stands for the url slug of the folder. This means the field shouldn't contain any special characters invalid for ulrs. It is easy to get this wrong, because of the wording of the label of this field. Name implies something like a title for me, where these special haracters are normally allowed.

So, if one types a "Folder Name" with spaces inside (for example), you can save that invalid folder slug. There is no validation. This could then cause consequential errors, like if one wants to add a sub page to this folder, one would get an internal server error, caused by a php memory problem.

One simple solution would be to add the "Folder Name" field js formatter from the "Add Page" dialog also to the same field in the "Add Folder" dialog. This js formatter automatically replaces spaces with minus.

What do you think?

**Comment by rhukster** [comment]
It actually does already convert whatever you type to a slug-safe version.  At least in the 1.9 beta version i'm testing it works as expected.

**Comment by jens-t** [comment]
Thanks for looking into it!

I couldn't Test the beta right now, but for 1.8.14 & 1.8.15 it behaves like this:

![bildschirmfoto-20190115104458-763x359](https://user-images.githubusercontent.com/9143480/51172426-8456bb80-18b3-11e9-866d-6c97b79a2f01.png)

![bildschirmfoto-20190115104911-261x76](https://user-images.githubusercontent.com/9143480/51172437-8882d900-18b3-11e9-874b-f12c45b9879f.png)

I can test the 1.9 version later, if that helps. Otherwise if you think that this is clearly fixed in 1.9, the ticket can be closed when 1.9 goes from beta to stable, i think.

Thanks.
