### ISSUE TITLE
Grav suddenly rendering scripts and the page content as escaped HTML

### ISSUE THREAD

**Issue by Lazza** [getgrav/grav-plugin-admin#1526]
While working on a custom theme (based on the Pure template) on Grav 1.5.2 with Admin 1.8.0 I suddenly encountered an issue: the template stopped working and Grav filled the CSS assets and the page content with escaped HTML, like you would need to add `|raw` to get them properly.

No worries, I though, I will switch back to **the default Quark theme.** Here it is, the problem is not gone:

![screenshot](https://user-images.githubusercontent.com/8294041/46631058-90a9da80-cb46-11e8-9752-e9e5abdf6f7a.png)

Here's an excerpt of the generated code:

```
<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="utf-8" />
    <title>Home</title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="generator" content="GravCMS" />
    <meta name="description" content="My Grav Site" />

    <link rel="icon" type="image/png" href="/user/themes/quark/images/favicon.png" />
    <link rel="canonical" href="http://localhost:8080/it" />

                                                            &lt;link href=&quot;/user/plugins/markdown-notices/assets/notices.css&quot; type=&quot;text/css&quot; rel=&quot;stylesheet&quot; /&gt;
&lt;link href=&quot;/user/plugins/form/assets/form-styles.css&quot; type=&quot;text/css&quot; rel=&quot;stylesheet&quot; /&gt;
&lt;link href=&quot;/user/plugins/login/css/login.css&quot; type=&quot;text/css&quot; rel=&quot;stylesheet&quot; /&gt;
&lt;link href=&quot;/user/themes/quark/css-compiled/spectre.css&quot; type=&quot;text/css&quot; rel=&quot;stylesheet&quot; /&gt;
&lt;link href=&quot;/user/themes/quark/css-compiled/theme.css&quot; type=&quot;text/css&quot; rel=&quot;stylesheet&quot; /&gt;
&lt;link href=&quot;/user/themes/quark/css/custom.css&quot; type=&quot;text/css&quot; rel=&quot;stylesheet&quot; /&gt;
&lt;link href=&quot;/user/themes/quark/css/line-awesome.min.css&quot; type=&quot;text/css&quot; rel=&quot;stylesheet&quot; /&gt;


                                    &lt;script src=&quot;/system/assets/jquery/jquery-2.x.min.js&quot; &gt;&lt;/script&gt;


</head>
<body id="top" class="title-center title-h1h2 header-fixed header-animated sticky-footer">

 [...]
    
        <section id="start">
                    <section id="body-wrapper" class="section">
                <section class="container grid-lg">
                                            
                                            &lt;h1&gt;Lorem ipsum&lt;/h1&gt;
&lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas congue pretium lacus ut congue. Donec sem lacus, feugiat at lorem nec, ultrices placerat nisl. Proin aliquam lectus sem, et finibus mi ullamcorper nec. Nunc consectetur turpis augue, eget bibendum turpis dignissim ut. Phasellus justo quam, tincidunt quis sagittis ut, congue sed nulla. Nam ornare quam massa, vitae euismod elit lobortis a. Cras quis diam ornare, ullamcorper felis nec, vestibulum justo. Maecenas quis est et enim lobortis commodo ut ut libero. Donec non orci laoreet, pharetra tortor nec, pellentesque risus. Praesent sed nunc ac nisi tempus suscipit a in nunc. Pellentesque bibendum quis risus vitae mattis. Sed ultrices id nulla eget suscipit. Aliquam condimentum est eu interdum mollis. Vivamus mattis neque consequat risus dictum, condimentum molestie nulla facilisis. Mauris vitae enim quis ante lobortis sollicitudin nec sit amet urna. &lt;/p&gt;
```

I tried to:

- clear the cache and
- restart from a new Grav installation
- activate / deactivate debug mode
- disable all optional plugins (the only plugin I added is DevTools)
- delete all the themes and only keep the Quark one (unmodified)

I do not know if it's relevant, but this is a multi-language site. The development is being done inside a Vagrant VM which was used two months ago with another Grav site, not showing any issue.

**Comment by rhukster** [comment]
Weird, are you sure you didn't enable Twig auto-escaping in the system config?

**Comment by Lazza** [comment]
I do not think it is enabled:

- Markdown - Escape markup: NO
- Twig templating - Autoescape variables: NO

Is there any other info I can provide? This happened simply by editing the files of one theme and then the issue propagated to the whole site. 😢

**Comment by rhukster** [comment]
How about this in your system yaml?

```
strict_mode:
  yaml_compat: true                              # Grav 1.5+: Enables YAML backwards compatibility
  twig_compat: true                              # Grav 1.5+: Enables deprecated Twig autoescape setting (autoescape: false)
```

**Comment by Lazza** [comment]
Oh gosh. I initially disabled `twig_compat` because it was giving a warning in Grav debug... and then forgot about it and it seemed to still work. Probably I was working on the CSS and the cached template looked OK until it finally collapsed.

So now I have enabled `twig_compat`again and refreshed all caches again and it works.

I can't believe I lost hours on this. 🙈 Apologies for bothering and **thank you very much** for your help.

**Comment by hughbris** [comment]
This is happening to me under v1.8.13, all else current, when I use the Snapygrav plugin and invoke `{{ snappygrav(page.route) }}` in a custom data-manager `item.html.twig`.

I also just tested this dumping something simple from core Grav:

```twig
{{ page.find('/images').media['example.jpg'].html() }}
```

and also get escaped output:

```html
&lt;img alt="" src="/user/pages/images/example.jpg" /&gt;
```

Could you have another look please?

**Comment by rhukster** [comment]
Did you have that `strict_mode.twig_compat` set to `false` ??? That would force you to use `|raw` on any Twig output that needs to output HTML.  The better solution is to simply put that `|raw` filter on your code:

```
{{ snappygrav(page.route)|raw }}
```

You'll need this for Grav 2.0 anyway.

**Comment by jaboto** [comment]
Thanks, enabling this fixed my issue while using the simplesearch plugin which resulted in wrongly rendered pages.
