### ISSUE TITLE
Admin v1.9.0-beta.2 - Editing interface does not keep settings properly without manual intervention on each edit

### ISSUE THREAD

**Issue by clarjon1** [getgrav/grav-plugin-admin#1527]
Version: Grav v1.6.0-beta.2 - Admin v1.9.0-beta.2 
Upgraded from Grav Blog skeleton, installed today.

I've attached a link to a video showing the behaviour.

Essentially, it appears that when there's overridden behaviour, the checkbox that indicates this seems to lose its status, and on a subsequent save, if the user does not ensure that the override checkboxes are checked, the override will be lost.

https://youtu.be/mgimCLft2B4  with a screen recording i made that shows this behaviour.

**Comment by clarjon1** [comment]
I've just rolled back my site to Grav v1.5.3 - Admin v1.8.11, and confirmed that this behaviour does not exist with this version, indicating that this is a regression

**Comment by mahagr** [comment]
Should be fixed now.

**Comment by mahagr** [comment]
PS: also needs Grav 1.6 update.
