### ISSUE TITLE
Unable to download plugins, etc. (code: 302)

### ISSUE THREAD

**Issue by GlebBrando** [getgrav/grav-plugin-admin#1528]
Hello!

I'm a bit newbie in Grav, keep studying documentation and trying to build my first website from scratch with local server (using Ampps). Ev is ok, but now have big problem - when I try to download any package from admin panel or cmd line, It throws me an error:

**> Error while trying to download (code:302)**

By the way, about six months ago, I downloaded another grav skeleton and Base Grav Package for tests, and I remember everything was fine with downloading packages. Can you help me please? :)

![image](https://user-images.githubusercontent.com/44124537/46909836-73b04580-cf52-11e8-8a2e-731c93b3295a.png)
![image](https://user-images.githubusercontent.com/44124537/46909969-f76b3180-cf54-11e8-82f6-0203c8a71809.png)
![image](https://user-images.githubusercontent.com/44124537/46909977-2e414780-cf55-11e8-9c7c-03076ca2a159.png)

**Comment by w00fz** [comment]
You might want to try changing from curl to fopen in the gpm configuration.

**Comment by w00fz** [comment]
Verify peer was going to be my next suggestion 😃

Glad it’s sorted, the problem is not the certificate missing but the way your servers verifies it which I’m not too familiar with on windows, although I’ve seen this before.
