### ISSUE TITLE
Admin 1.9.0 - Beta 3 Media settings

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#1529]
I've just noticed a possible visual glitch on the media config panel in the Admin.

In the past I've been using custom admin plugin to increase the default font size for the users of my skeletons, and for the first time I've noticed this in Beta 3:

![2018-10-15_14-09-24](https://user-images.githubusercontent.com/1812771/46978617-495ea500-d084-11e8-9382-560edde1b2e3.png)

Not sure exactly when this happened, but it used to look like this:
![2018-10-15_14-09-04](https://user-images.githubusercontent.com/1812771/46978644-5a0f1b00-d084-11e8-8859-c9805050facf.png)

This is the only visual glitch I've noticed so far, all other screens seem to be a-ok.

Thanks very much!
Paul

**Comment by mahagr** [comment]
This may be related to the new structure where all the fields must extend field.html.yaml in order to add proper ACL to the fields.

**Comment by paulhibbitts** [comment]
Thanks very much for looking into this @mahagr !
