### ISSUE TITLE
Getting "Failed to retrieve notifications"

### ISSUE THREAD

**Issue by thomasjsn** [getgrav/grav-plugin-admin#1530]
I'm getting no notifications; just the message "Failed to retrieve notifications".

Looking at the call to `/admin/notifications.json/task:getNotifications`, the response contains an empty array of notifications:

```
{"status":"success","notifications":[],"need_update":true}
```

I do see the notifications occasionally, but most times it fails.

**Comment by rhukster** [comment]
Are you behind a proxy server or firewall? Do the GPM updates and Blog updates work in the dashboard?

**Comment by thomasjsn** [comment]
I use Firefox both at work and at home, but at work it's behind a proxy. Is the notification results cached somehow?

**Comment by cyhwuhx** [comment]
Had the same problem, turned out to be the Privacy Badger Firefox-extension blocking getgrav.org by default. 🤦‍♂️ Unblock and it's fixed.

**Comment by Rotzbua** [comment]
`Dashboard-feed` is crawled by the webserver. `Dashboard-notifications` by client. I am right?
I think both should be done by the webserver to avoid cross-origin errors.

**Comment by DerPhlipsi** [comment]
@Rotzbua Yup, that's correct. I've got an error on the notifications because of CORS for a while now :D

**Comment by rhukster** [comment]
I'm actually already working on this.  Newsfeeds and Notifications are getting a little refactor that should make them faster and more reliable.
