### ISSUE TITLE
Grav found potential XSS issues in content: 'dangerous_tags'

### ISSUE THREAD

**Issue by kailoon** [getgrav/grav-plugin-admin#1531]
I am getting this notice when using google map iframe. Should I be worried?

**Comment by rhukster** [comment]
No, its just a warning about 'potential' HTML tags that might be used nefariously.  If you are using it and are comfortable it's fine.

If you are `super admin` you will be warned but wont be stopped from saving.  Or you can remove `iframe` in the **Dangerous HTML Tags** field of the Config -> Security settings page.
