### ISSUE TITLE
Using custom_base_url or another setting for custom url rewrite?

### ISSUE THREAD

**Issue by dimitarsp** [getgrav/grav-plugin-admin#1532]
I've recently moved my grav website from the root hosting folder to a subfolder and adjusted the .htaccess accordingly, based on [siteground's suggestions](https://www.siteground.com/kb/how_to_change_my_document_root_folder_using_an_htaccess_file/). Once moved, all links had the actual subfolder name showing up. eg. www.domain.com/subfolder/blog instead of www.domain.com/blog. I saw a setting that may resolve this issue in system.yaml called custom_base_url, which I set to be only http://www.domain.com. Now the menu links show up correctly. However, when trying to login to the admin, I get invalid security token. I followed all the suggestions on [this page](https://learn.getgrav.org/troubleshooting/invalid-security-token) but to no avail.

**Comment by rhukster** [comment]
Frankly you should not need to mess with the custom base url at all. Moving a site in grav is as trivial as moving the files.  Custom base url is usually only needed for reverse proxy setups or very custom domain rewrite configurations.  

If you are running Apache the provided .htaccess file handles rewrites no matter the sub directory.

**Comment by dimitarsp** [comment]
@rhukster Thanks for the comments. 

My website is uhstudio.com. I've recently moved the site into a subdirectory and used htaccess rewrite to direct to the subdirectory from the top domain. However all the grav links now inlcude the /subdirectory in the URL

E.g.: 
From the http://www.uhstidio.com, if I click on projects, it points to http://www.uhstudio.com/uhstudio/projects instead of http://www.uhstudio.com/projects. 

However, if I manually put http://www.uhstudio.com/projects in the browser, it also works, meaning that the top level htaccess is properly set up, but it may be a setting within grav, and hence I was trying to use `custom_base_url`
