### ISSUE TITLE
Direct install of packages not working

### ISSUE THREAD

**Issue by Tiaryn** [getgrav/grav-plugin-admin#1535]
Hello,

after adding the XSS protection it's not possible to upload and install grav packages anymore.
Selecting the zip package and clicking 'upload and install' just reloads the page.
No errors are given in any log as far as I can tell.

Grav v1.5.3
Admin Panel v1.8.11

**Comment by rhukster** [comment]
Hmm. Not sure it’s related to XSS but I’ll take a look.

**Comment by rhukster** [comment]
Was kinda related.. fixed.
