### ISSUE TITLE
Proxy / Remote Fetch Method - Auto 

### ISSUE THREAD

**Issue by pretsell** [getgrav/grav-plugin-admin#1539]
Remote Fetch Method Auto doesn't fall back to curl.
Manually setting curl Grav able to connect out.

Grav v1.5.3 - Admin v1.8.12

**Comment by rhukster** [comment]
The logic here is basically this:

```
    private static function getAuto()
    {
        if (!ini_get('open_basedir') && self::isFopenAvailable()) {
            return self::getFopen(func_get_args());
        }

        if (self::isCurlAvailable()) {
            return self::getCurl(func_get_args());
        }

        return null;
    }
```

The `isFopenAvailable()` method does this:

```
return preg_match('/1|yes|on|true/i', ini_get('allow_url_fopen'));
```

So it looks in your PHP ini for `allow_url_fopen` and if so, assumes that's good to go.

So it tries to see if `fopen` is available, and uses that.. else it will use `curl` if that's available.  My guess is that `fopen` is available but for some reason is not working for you.
