### ISSUE TITLE
Template "default.html.twig" is not defined.

### ISSUE THREAD

**Issue by kryukov54** [getgrav/grav-plugin-admin#1541]
1. Install grav from scratch.
2. Start admin (grav/admin).
3. Add admin user and enter to admin page.
4. Add plugin for user management.
5. Add new group.
6. Add new user for that group.
7. Press "Login as"
---> Template "default.html.twig" is not defined.
Any attempts to come grav/admin have no success. The grav in user mode is working.

**Comment by rhukster** [comment]
This sounds like a bug in the 3rd party user management plugin.  Please submit a ticket on that plugin, it's not a core part of Grav nor is it developed by the Grav core team: https://github.com/david-szabo97/grav-plugin-admin-addon-user-manager/issues

**Comment by kryukov54** [comment]
I used default grav package for setup. Nothing more.
