### ISSUE TITLE
Backupshistory issues in 1.9.0 Beta 5

### ISSUE THREAD

**Issue by AtjonTV** [getgrav/grav-plugin-admin#1542]
I encountered a issue on a Beta installation to rebuild my homepage for 2019.

The new installation uses `Grav v1.6.0-beta.5 - Admin v1.9.0-beta.5`, and when I try to access the backups tab in the admin panel (`/admin/config/backups`) I get the following error:

![image](https://user-images.githubusercontent.com/24845056/48306931-95e1b700-e542-11e8-8329-4213b17aac3a.png)

## System Details

Used System:

| Name | Version |
|----------|-----------|
| Ubuntu | 18.04 |
| PHP | 7.2.10 |
| Linux | 4.15.17-1-pve |
| VM | Proxmox VM (PVE) |
| Apache | 2.4.29 |

Used Plugins:

| Name | Version | Type |
|----------|-----------|---------|
| Admin Panel | v1.9.0-beta.5 | test release |
| Admin Power Tools | v0.1.10 | |
| Core Service Manager | v1.0.12 | |
| Editor | v0.1.8 | |
| Email | v2.7.1 | |
| Error | v1.6.1 | |
| Form | v3.0.0-beta.3 | test release |
| Gantry 5 Framework | v5.4.26 | |
| Language Selector | v1.0.0 | |
| Login | v2.7.3 | |
| Markdown Notices | v1.0.1 | |
| Problems | v2.0.0 | |

Used Themes:

| Name | Version |
|----------|-----------|
| Helium | v5.4.26 |

**Comment by rhukster** [comment]
I cannot replicate this, but it appears as if something else is providing a Twig variable called `backups` ? Maybe disable the admin power tools plugin?  Or some of the others?

**Comment by AtjonTV** [comment]
After disabling the admin power tools the issue still exists. When disabling the core services manager the whole backuphistory disappears.

**Comment by rhukster** [comment]
I'm guessing you are talking about something related to the admin power tools.  Grav 1.6 has it's own backup manager available via the Tools menu.

**Comment by AtjonTV** [comment]
Well, what I don't understand is that the site that errors (but is only avaiable with power admin tools enabled) is in this repository? -> [backupshistory.html.twig on line 13](https://github.com/getgrav/grav-plugin-admin/blob/1.9/themes/grav/templates/forms/fields/backupshistory/backupshistory.html.twig#L13)

**Comment by rhukster** [comment]
Like I said, the admin power tools plugin is conflicting with the twig variable `backup` from the core admin plugin.  We can't check every 3rd party plugin to ensure we use unique variable names, it should be the responsibility of the 3rd party plugin to ensure it works correctly with the underlying platform it's buit for.  Please take it up with the author of the admin power tools plugin.  Thanks.
