### ISSUE TITLE
document the date field for the blueprints

### ISSUE THREAD

**Issue by aoloe** [getgrav/grav-plugin-admin#1545]
in https://learn.getgrav.org/forms/blueprints/fields-available#special-form-fields-available-exclusively-in-the-admin the "date" field type is missing.

i have learned about it from https://github.com/getgrav/grav-plugin-admin/issues/281 .

**Comment by aoloe** [comment]
in the chat i've been made aware of

https://learn.getgrav.org/forms/forms/fields-available#the-date-field

in my eyes the link is not visible enough. 

i would move the paragraph "in addition to..." down as the first paragraph in the "special form fields..." section. just before the table.

**Comment by rhukster** [comment]
Please feel free to edit the documentation directly via the learn site.  It will automatically create a Pull Request.
