### ISSUE TITLE
Plugin YouTube is being removed constantly after it's installed

### ISSUE THREAD

**Issue by skinchu** [getgrav/grav-plugin-admin#1552]
I installed YouTube plugin and it's working OK.  but the plugin YouTube is removed frequently although I keep installing it.  Any suggestion?

**Comment by rhukster** [comment]
If it’s being unistalled then it’s not grav doing it.  It has no capability to auto uninstall a plug-in.  Could be some security software you run, or if you are using some syncing technique it could be related to that.
