### ISSUE TITLE
Files Unset Bug

### ISSUE THREAD

**Issue by whollaus** [getgrav/grav-plugin-admin#1555]
Grav v1.6.0-beta.6 - Admin v1.9.0-beta.6

I have two image fields:
![grafik](https://user-images.githubusercontent.com/4582757/49802479-48c55080-fd4d-11e8-81f8-2d250f44c2c5.png)
Then I click on "Unset" and save the entry:
![grafik](https://user-images.githubusercontent.com/4582757/49802507-58dd3000-fd4d-11e8-819d-48c9f04f099b.png)
After that the pictures are gone for both fields.:
![grafik](https://user-images.githubusercontent.com/4582757/49802527-68f50f80-fd4d-11e8-905a-405f33b412c8.png)

default.yaml (quark template)
`extends@: default

form:
  fields:
    tabs:
      fields:

        content:

          fields:

            header.image1:
              type: file
              label: Image 1
              avoid_overwriting: true
              destination: '@self'
              multiple: false
              style: vertical
              accept:
                - image/jpg
                - image/jpeg

            header.image2:
              type: file
              label: Image 2
              avoid_overwriting: true
              destination: '@self'
              multiple: false
              style: vertical
              accept:
                - image/jpg
                - image/jpeg

        advanced:
          fields:
            columns:
              fields:
                column1:
                   fields:
                     header.body_classes:
                       markdown: true
                       description: ''`

**Comment by w00fz** [comment]
I can't reproduce this in the latest admin develop. I think i already sorted this recently.

Mind trying latest develop?

**Comment by whollaus** [comment]
Thank you very much. With the last version it works. But I found another bug(?). But I create a new entry for it :)
