### ISSUE TITLE
When updating, versions are not displayed.

### ISSUE THREAD

**Issue by Lufog-git** [getgrav/grav-plugin-admin#1560]
This happened during the update of the Login plugin.

![tmp](https://user-images.githubusercontent.com/10379487/50038675-3e98a000-0034-11e9-90ca-eda96d83c7bf.PNG)

**Comment by rhukster** [comment]
Was this a particular plugin that admin reported as needing an update?

**Comment by rhukster** [comment]
I couldn't replicate this.  I tried updating from an old Grav install and the versions were displayed just fine

**Comment by Lufog-git** [comment]
Again, on version Grav v1.6.0-rc.2 - Admin v1.9.0-rc.2
![image](https://user-images.githubusercontent.com/10379487/52456784-8ab11e00-2b67-11e9-8f92-59e77a00019f.png)

**Comment by Lufog-git** [comment]
And on another site:
![image](https://user-images.githubusercontent.com/10379487/52456914-54c06980-2b68-11e9-8997-330bc697577d.png)

**Comment by rhukster** [comment]
I noticed this right after release.  The update works, but the versions were not displaying: https://github.com/getgrav/grav/commit/48816d9f2e0d8004717b86b2a02852b22ab5198e
