### ISSUE TITLE
Misleading description under XSS Security

### ISSUE THREAD

**Issue by Rotzbua** [getgrav/grav-plugin-admin#1565]
Type: documentation
Difficulty: trivial

Hi,

the description of the xss security options is confusing.
it is not clear whether the setting allows or disallows the use of the rule.

![grafik](https://user-images.githubusercontent.com/7337347/50373097-d7ea2800-05d9-11e9-8d80-c41f88f754db.png)

I think "Filter On-events" yes/no is better.

Best

**Comment by rhukster** [comment]
Agreed, merged.
