### ISSUE TITLE
Admin 1.9.0-beta.7 login error with PHP 7.3.0

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#1567]
Using PHP 7.3.0 and going to my admin page:

![error](https://user-images.githubusercontent.com/12480617/50426469-4f47e200-088e-11e9-9ac4-6c288eba0a5e.png)

**Website (Grav 1.6.0-beta.7) working only error in admin 1.9.0-beta.7!**
**Working with admin 1.8.15**

**Comment by mahagr** [comment]
See the another issue.
