### ISSUE TITLE
Chinese translation issue

### ISSUE THREAD

**Issue by vrabe** [getgrav/grav-plugin-admin#1569]
Currently translation in zh.yaml is actually a Chinese Traditional translation. That's probably why people using Chinese Simplified in getgrav/grav#1794 can't find translation in their language. I think we should follow language codes in crowdin. zh-TW.yaml for Chinese Traditional translation; zh-CN.yaml for Chinese Simplified translation.

**Comment by rhukster** [comment]
There should be a zh-TW and zh-CN already: https://crowdin.com/translate/grav-admin/2/en-zhcn

**Comment by vrabe** [comment]
Yes, but it seems you didn't put it into this repository.
There is still only zh.yaml in languages folder.

**Comment by rhukster** [comment]
I will make sure they both make it in for version 1.9

**Comment by vrabe** [comment]
Thanks.

**Comment by rhukster** [comment]
I just updated these in 1.6 manually because when i export from crowdin, the 2 chinese translations are overwriting each other resulting in a single `zh.yaml` file.  I will just need to remember to do these 2 manually in the future.

**Comment by vrabe** [comment]
Hello,
2 Chinese translations have been separated, but the native name of Chinese Traditional is not right.
It is `中文 (简体) (tw)` now.
I think the filename of `zh-tw.yaml` should be `zh-TW.yaml` to match the language code listed in [here](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Language/LanguageCodes.php#L149).
