### ISSUE TITLE
Layout not mobile friendly Admin 1.9.0 beta 7

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#1579]
Admin 1.9.0-beta.7 mobile layout, system tab:
Left side pane not adjustable, words are cut

![layout](https://user-images.githubusercontent.com/12480617/50734336-fa656f00-119d-11e9-823d-16c179a6eef8.png)

Admin 1.8.15 mobile layout:

![layout2](https://user-images.githubusercontent.com/12480617/50734338-03564080-119e-11e9-9ed5-0a05ea09b205.png)

**Comment by rhukster** [comment]
Yup, not gotten around to making this responsive...
