### ISSUE TITLE
Improvements in Data Protection for Popularity visitor history

### ISSUE THREAD

**Issue by Rotzbua** [getgrav/grav-plugin-admin#1582]
A little fussy review ;)

Type: Improvement, Data Protection Compliance

## Vistor data is not deleted after time

`visitors.json` can contain old user data. User data is not deleted by date. User data is deleted by value `plugins.admin.popularity.history.visitors`.
If this number is high and visitors number low it may violate some compliance rules.

Suggested solution: introduce a max save time

## Insufficient pseudonmisation of ip

`hash('sha1', $ip)` can easily reverted for ipv4. A lookup file is just 80gb big.

Suggested solution: add browser user agent e.g. `hash('sha1', $ip+$user_agent)`

**Comment by rhukster** [comment]
The clearing out of old data is something that is better done with the scheduler that will be available in Grav 1.6.  That's something I would like to add in the near future.

**Comment by rhukster** [comment]
merged your PR.. thanks!
