### ISSUE TITLE
Remove (unused) visitors history from Popularity

### ISSUE THREAD

**Issue by Rotzbua** [getgrav/grav-plugin-admin#1583]
I do not see any usage of `visitors.json` and the containing last visitors of the site. Is it unused code?
I guess it can be removed.

Solves:  #1582

**Comment by rhukster** [comment]
visitors.json is used.  See `updateVisitors($ip)` in `popularity.php`

**Comment by Rotzbua** [comment]
@rhukster You misunderstand. That function creates `visitors.json` and do not use it.

**Comment by rhukster** [comment]
Ah yes, its not currently used in the widgets, but it's there so we can use it if needed in the future.
