### ISSUE TITLE
Fieldtype datetime does not display datepicker after upgrade from v1.8.15 

### ISSUE THREAD

**Issue by grelle** [getgrav/grav-plugin-admin#1584]
I run two grav-sites. One with admin-plugin v1.8.15 and one with the latest version.

In the latest version the field-type "datetime" does not produce a datepicker in Chrome.

**Comment by rhukster** [comment]
Duplicate of: https://github.com/getgrav/grav-plugin-admin/issues/1581

Already fixed in develop branch.
