### ISSUE TITLE
Security improvements / GDPR

### ISSUE THREAD

**Issue by Rotzbua** [getgrav/grav-plugin-admin#1590]
Hi,

I have checked the grav according to the requirements of the GDPR.

I found that

* the pure IP address is used for brute force protection/rate limiting.
  * proposed PR #1589
* leak information to 3rd party, also [noopener problem](https://developers.google.com/web/tools/lighthouse/audits/noopener)
  * proposed PRs #1577 #1576 #1575 #1574

Best.

**Comment by rhukster** [comment]
I think i got all these merged.. Thanks!!
