### ISSUE TITLE
Trouble with accessing themes and plug-ins, can't change menu items and published content not displayed

### ISSUE THREAD

**Issue by helloremym** [getgrav/grav-plugin-admin#1592]
Whenever I try to access the /themes and /plugin options to edit my site I get this error 500 message:

Server Error
Sorry, something went terribly wrong!
0 - An exception has been thrown during the rendering of a template ("GPM not reachable. Please check your internet connection or check the Grav site is reachable") in "partials/themes-list.html.twig" at line 21.

And 

0 - An exception has been thrown during the rendering of a template ("GPM not reachable. Please check your internet connection or check the Grav site is reachable") in "partials/plugins-list.html.twig" at line 20.
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.

How can I fix this so that I can fully edit my site?

**Comment by rhukster** [comment]
Check the possible solutions in the docs and let us know if you continue to have problems: https://learn.getgrav.org/troubleshooting/internal-server-error

**Comment by helloremym** [comment]
Hi,
I think the problem is with the permissions. We hired a guy to build our website for us, and because of his slow response time, we've asked him to give us full control of the site. However, he has been completely unresponsive for the past month. Is there any way you can hand over the permissions that we need to fully edit our site? 
Thanks,
Remy
