### ISSUE TITLE
Bug Creating modular page: The page not assigned as modular.md

### ISSUE THREAD

**Issue by Daryadi-S** [getgrav/grav-plugin-admin#1594]
Posibble bug on Admin Panel when adding new modular page:

Bug: The page not assigned as modular.md

Reproduce:
1. Add new page using "+Add" button. Select "Modular" as the page template.
2. Possible bug: The "modular setup" options not appear on "Content" tab.
3. Go to "Advanced" tab. The page template select instead showing the modular children template (hero,text,features).

Workaround:
1. Save the page.
2. Now the template select on "Advanced" tab showing the right templates, choose "Modular". Save the page.
3. The "modular setup" option now available on "Content" tab.

Now sure if this is a bug or expected behaviour. Still, it can be confusing 😁

Running Grav v1.6.0-beta.7 - Admin v1.9.0-beta.7 - Quark 2.0.0-beta.4

**Comment by rhukster** [comment]
Please try the latest beta releases, should be fixed.

**Comment by whollaus** [comment]
It works for me now. Thank you very much.

**Comment by Daryadi-S** [comment]
Yeah it is works fine now, Thanks 😊
