### ISSUE TITLE
admin.min.js error

### ISSUE THREAD

**Issue by rmrten** [getgrav/grav-plugin-admin#1595]
Hi,

suddenly i start to experience "Fetch Failed" issue but when i checked dev tool in Firefox i see problem with loading/using admin.min.js correctly

output from console: 
![image](https://user-images.githubusercontent.com/31125723/51611550-c620db00-1f1f-11e9-87f5-ab033b3d3049.png)
output from Network tab:
![51609182-b8685700-1f19-11e9-8fc0-0a66a33bc185](https://user-images.githubusercontent.com/31125723/51611500-aab5d000-1f1f-11e9-9c21-69b3363edd5f.png)
Things which are not working: 
- when editing page cant see any media in Page Media section ( Pictures are in current folder and displaying on website)
- preview of the page in admin is not working
- some of markdown codes are not working ( for example check boxes ) 

What i tried: 
- update grav and admin panel ( it is up to date with versions 1.5.6 and admin 1.8.15 )
- openSSL and curl is enabled
- on local enviroment (using WAMP with same versions) it is working
- permissions for folder where is admin.min.js located are the same as for rest of the files/folders

Was looking into php.ini configuration and also all the similar issues around.

Any tips what to check else?

**Comment by rhukster** [comment]
Passed this along to @w00fz to see if he has any insight

**Comment by w00fz** [comment]
The 404 source map can be ignored, you can fix that by disabling sourcemaps from the developer tools settings in your browser.

The first error is the one that seems causing the issues for you. With js something breaking in the middle of the application can cascade down to everything else, producing unexpected behaviors.

Unfortunately that first screenshot is not being very useful in identifying the problem but I do suspect the Ajax response is dirty and not a pure json response that the js is expecting.

Could you look into the network panel and take a screenshot of the response there?

**Comment by rmrten** [comment]
Hi thanks for looking at this for me. here is network tab: 
![image](https://user-images.githubusercontent.com/31125723/51844440-9275f480-2315-11e9-9117-8f8d162e9b15.png)

**Comment by w00fz** [comment]
Hey @rmrten, did you ever resolve this issue? There's been a few releases since January and I was wondering if all is working as intended now.

Please leave a comment if it's still a problem and I can reopen the issue.

Cheers.

**Comment by nullrend** [comment]
Just ran into this issue on Firefox 77.0.1/Windows 10 2004 on a brand new grav install. Just to verify I hadn't enabled that specific setting on Firefox tried Edgemium (Version 83.0.478.54), also ran into this very issue:

![2020-06-23_11-34](https://user-images.githubusercontent.com/6384507/85430447-bd359e00-b545-11ea-9fbc-78ba35542b6a.png)

Server-side (Debian 10, Nginx 1.14.2 on PHP 7.4) error logs also reflect this fact:

```
2020/06/23 11:33:32 [error] 8764#8764: *1264 open() "/var/www/whittiersolidarity.network/user/plugins/admin/themes/grav/css/fork-awesome.min.css.map" failed (2: No such file or directory), client: 50.93.252.159, server: whittiersolidarity.network, request: "GET /user/plugins/admin/themes/grav/css/fork-awesome.min.css.map HTTP/2.0", host: "whittiersolidarity.network"
```
