### ISSUE TITLE
Page Media too long

### ISSUE THREAD

**Issue by JDomleo** [getgrav/grav-plugin-admin#1597]
Could you add the following CSS to the page media:

max-height: 400px;
overflow-y: scroll;

This is because we have a homepage with lots of images we do not want to delete (SEO purposes) and the page media section is getting too long.

Thanks in advance.

**Comment by rhukster** [comment]
I suggest installing this plugin: https://github.com/RomainFallet/grav-plugin-customadmin

this will let you override any admin css.
