### ISSUE TITLE
disabling Twig Compatibility errors

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav-plugin-admin#1598]
Grav v1.6.0-beta.8 - Admin v1.8.15

fresh install of latest beta

the following settings have been "changed:

Process ; markdown and twig
Assets: jquery 3.x...
Markdown Extra : enabled
Debugger: enabled

Twig compatibility: disabled

![screenshot 2019-01-26 at 12 27 42](https://user-images.githubusercontent.com/7076631/51787178-4f295380-2166-11e9-8062-b86cfeb5e8b3.png)

**Comment by rhukster** [comment]
BTW, you need to be running admin 1.9.0-beta.8 with Grav 1.6.0-beta.8 - Can you please test that???

**Comment by JohnMica** [comment]
I downloaded the latest beta package (Grav and Admin) and I got this strange error.

I tried another fresh install and it seemed that the error went away.

Could close this as an 'install issue" ?

**Comment by rhukster** [comment]
I think my rebuild package might have fixed this issue. Please let me know if it happens again. Thanks!

**Comment by JohnMica** [comment]
Grav v1.6.0-beta.8 - Admin v1.9.0-rc.1  

no errors
