### ISSUE TITLE
Editing Page Information Error

### ISSUE THREAD

**Issue by linavo** [getgrav/grav-plugin-admin#160]
This error occurs after saving edited changes.

![screen shot 2015-09-11 at 11 15 24 am](https://cloud.githubusercontent.com/assets/12104092/9820556/40e0886a-587a-11e5-9611-ac70d40a4b8a.png)

This error was occurring on my own site, but I tested this on the skeleton **Twenty** as well.
The screenshot included is from testing on **Twenty**.

Here are the steps I took.
1. Updated GRAV to ensure I had the latest version
2. Installed Admin Plugin, no errors occurred on install.
3. Added user, no errors occurred in adding user.
4. Navigated to site to make sure plugin didn't cause errors on site.
5. Logged on as admin > clicked on page > edited content > clicked save
6. Navigated back to site, error message appeared. 

*Note* : When I deleted the page that I edited, the error message went away and the site looked fine.

**Comment by rhukster** [comment]
what specifically was the page in twenty skeleton that you edited? I want to try to recreate this exactly.

**Comment by linavo** [comment]
@rhukster I changed the text on the "behold the icons" page to say *testing*. I didn't change the title of the page at all.

**Comment by rhukster** [comment]
I can reproduce it, and it's mainly caused by the fact that this theme has no blueprints to define the modular page types it supports. However, we should fallback in a safer way.. So i'll take a look at it now.

**Comment by linavo** [comment]
@rhukster Thanks, is there currently a workaround for this bug?

**Comment by rhukster** [comment]
There is no workaround other than manually editing the markdown rather than using the admin.  However, i've managed to sneak this fix in already and was going to do a release today anyway, so hang tight!
