### ISSUE TITLE
Language error in login form

### ISSUE THREAD

**Issue by pavolmarak** [getgrav/grav-plugin-admin#1601]
I found a language error in admin login form for Slovak language. There are 2 buttons:

- _Zabudli ste_ for password recovery in case of forgotten password
- _Prihlasovacie meno_ for login ... but this is wrong, the correct Slovak version is **_Prihlásiť_**

_Prihlasovacie meno_ means something like nickname, but the word _Prihlásiť_ is verb which means to login somewhere.

**Comment by rhukster** [comment]
Can you please fix that issue here: https://crowdin.com/project/grav-admin

Thanks!

**Comment by pavolmarak** [comment]
I fixed it.
