### ISSUE TITLE
Call to undefined method Grav\Plugin\Form\Form::unsetFlash()

### ISSUE THREAD

**Issue by Flamenco** [getgrav/grav-plugin-admin#1604]
Updated to latest RC today (v1.9.0-rc.1 ), and could not log into admin after.

```
Call to undefined method Grav\Plugin\Form\Form::unsetFlash()
```

Workaround was to comment out call to `unsetFlash()` in `Form.php`

**Comment by rhukster** [comment]
Form rc.1 relies on something in Grav that is not released yet. I pulled this release for now.  So please revert to last beta of Form plugin.

**Comment by Flamenco** [comment]
That's what I figured and why I posted the 'workaround'.  Looking good BTW!

**Comment by rhukster** [comment]
All new releases are out.
