### ISSUE TITLE
Return debugger contents on AJAX task calls

### ISSUE THREAD

**Issue by hamiltont** [getgrav/grav-plugin-admin#1605]
When the admin page gets a task request, it processes and returns data as JSON. Right before calling sending the json response and calling `exit`, would it be possible to also grab the contents of `grav['debugger']` and extend the admin javascript to append those contents onto the existing debug log? 

Basically, anything done inside an admin task cannot (currently) use the debugger - it has to either add debug material into the content you want to return, or dump it to the log. This can bite you in unexpected ways e.g. other plugins that extend grav and suddenly cannot reliably use the debugger inside their logic 

If this sounds reasonable, it would likely also be wise to have the debugger include a line about the task being sent (e.g. "Sending task 'processmarkdown'"). There are a few other ways admin could be tweaked to know if the debugger was online and integrate nicely, but this is a solid first step

For some context, see https://github.com/getgrav/grav-plugin-shortcode-core/issues/60

**Comment by mahagr** [comment]
Grav 1.7 / admin 1.10 supports clockwork debugging tool, which logs and displays all the requests.
