### ISSUE TITLE
Session timeout losing unsaved work

### ISSUE THREAD

**Issue by bjfisher** [getgrav/grav-plugin-admin#161]
If you happen to come back to an open browser tab thats session has expired (or maybe even if you just spend longer then the session timeout value working on a page) then once you click save you will be taken to the logon screen instead of your work being saved. After logging back in, any changes that you made and were trying to save will have been lost.

**Comment by rhukster** [comment]
What behavior were you expecting? A keep alive when editing perhaps?

**Comment by rhukster** [comment]
Fixed in latest develop branch with an ajax keep alive.
