### ISSUE TITLE
Missing "unauthorized.html.twig" file.

### ISSUE THREAD

**Issue by 56Kbps** [getgrav/grav-plugin-admin#1610]
When a user that is not an administrator tries to access a page that it does not have authorization. An error occurs with the message:

**Template "default.html.twig" is not defined in "unauthorized.html.twig" at line 1.**

Creating a file ({plugin_path}/themes/grav/templates/unauthorized.html.twig) with just "{% extends 'partials/base.html.twig' %}" as content solves the problem.

I create a pull request in expectation of saving some time for the developers of the plugin (https://github.com/getgrav/grav-plugin-admin/pull/1609).

**Comment by rhukster** [comment]
merged, thanks
