### ISSUE TITLE
Installed outdated shortcode-ui plugin?

### ISSUE THREAD

**Issue by fbrinker** [getgrav/grav-plugin-admin#1611]
I've installed shortcode-core and -ui and when trying to use the animated texts I've got an PHP error due to the fact that I'm using PHP 7.2.

After some investigation and looking into the repository, I've found out that the problem was fixed "a while ago" (a year ago):
https://github.com/getgrav/grav-plugin-shortcode-ui/commit/ecf985e6fcb96c3fda9626ee1a65ea846d046986#diff-577975d1a6ebaa0341130040eae185a9

Why isn't that fix available in the installed version?

Edit: Okay the installed version 2.2.5 is from 2017 :/

**Comment by rhukster** [comment]
Seems it was never 'released'.  I've done so now, and should show up in GPM in 30mins or so.

**Comment by fbrinker** [comment]
Thank you :)
