### ISSUE TITLE
Unexpected versions when updating to latest plugins

### ISSUE THREAD

**Issue by Flamenco** [getgrav/grav-plugin-admin#1612]
After updating Grav to latest beta, and then proceeding to update plugins, the following dialog was presented:

<img width="782" alt="screen shot 2019-02-08 at 7 41 54 am" src="https://user-images.githubusercontent.com/819940/52478986-19786780-2b75-11e9-9866-4fcbc1c259cf.png">

**Comment by Flamenco** [comment]
BTW The updates process was successful.

**Comment by rhukster** [comment]
Fixed for Rc.3 https://github.com/getgrav/grav/commit/48816d9f2e0d8004717b86b2a02852b22ab5198e

**Comment by rhukster** [comment]
reopened in case anyone else has the problem, they can see it's been fixed already :)
