### ISSUE TITLE
call_user_func_array error

### ISSUE THREAD

**Issue by chhinsras** [getgrav/grav-plugin-admin#1617]
I just new to grav, it looks interesting.

When, I install everything working fine. Then, I started to some plugins.

The error call_user_func_array() occured.

Please help me.

![image](https://user-images.githubusercontent.com/31751665/52900534-8ea90400-3229-11e9-8cca-f404d7a22a95.png)

**Comment by rhukster** [comment]
What version of Grav/Admin are you running?  It looks like there's an issue with the `admin-addon-user-manager` plugin, so you might want to create an issue on that 3rd party repo:

https://github.com/david-szabo97/grav-plugin-admin-addon-user-manager

**Comment by chhinsras** [comment]
I use Admin Addon User Manager v2.1.6

Even I disable it. It still has same error. Like, I go configuration menu. It showed error


This showed when I create new page. NOTE: I disable Admin Adon User Manager
![image](https://user-images.githubusercontent.com/31751665/52907349-b7191880-3292-11e9-838b-c1ede6509c04.png)

**Comment by mahagr** [comment]
Likely a bug in the field.
