### ISSUE TITLE
Admin UI pops up grey overlay

### ISSUE THREAD

**Issue by desmondchoon** [getgrav/grav-plugin-admin#1621]
When in the Admin panel, I can't do any add pages or install themes/plugins. A grey overlay with class "remodal-wrapper remodal-is-opened" will pop up and nothing happens after. If I click on the overlay it simply dismisses. No JavaScript error as well.

**Comment by desmondchoon** [comment]
Did some testing and realised this only happens in Chrome browser.

**Comment by rhukster** [comment]
What other plugins do you have installed? Can you try to disable all the non-standard plugins one at a time to see if this resolves the issue?

The key ones that you can't disable are `admin`, `form`, `login`, `email`

**Comment by desmondchoon** [comment]
I have installed a clean version with no plugins and still face the same issue with Google Chrome.

**Comment by rhukster** [comment]
Maybe a browser extension? I simply can't replicate this.

**Comment by orangutanga** [comment]
I think I know some more about this? When using the Admin plugin in either Google Chrome or Chromium on either Fedora 30 or Mint Linux 19.

Add a plugin or something that causes the background to go blurred e.g. [+Install Plugin]. This seems to cause the rendering engine of Chrome to do a repeated call to a some surface presentation helper function, which slows down user interaction with the PC. This causes the user to think that nothing is happening. Keyboard and mouse responses are very slow. See error from Fedora log below.

[12188:12188:0618/131829.230138:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 13824 times!

I'm going to see if I can change the blur to just a shadow?? Or else just stick to the command line.
