### ISSUE TITLE
additional assets not working

### ISSUE THREAD

**Issue by rweymann** [getgrav/grav-plugin-admin#1624]
Maybe I'm wrong. But i tried to extend a form field with some assets and ended up extending the assets pipeline. So far so good. :)
Then i found in admin/themes/grav/templates/pages.html.twig:420
```
{% block bottom %}
<script>
    {{ parent() }}
    $('.admin-pages .form-tabs .tabs-nav').css('margin-right', ($('#admin-topbar').width() + 20) + 'px');
</script>
{% endblock %}
```
so my added script tag was wrapped by the script tag above. It's possible i got something wrong, but changing the code to 
 ```
{% block bottom %}
 {{ parent() }}
<script>
    $('.admin-pages .form-tabs .tabs-nav').css('margin-right', ($('#admin-topbar').width() + 20) + 'px');
</script>
{% endblock %}
```
worked pretty well for my case.

**Comment by rhukster** [comment]
This won't work as you can't extend `bottom` block from a form field.  You can only extend blocks that the field directly inherits.

however, you can use the Asset manager directly from twig like this:

```
    {% do assets.addInlineJs("
    $('.admin-pages .form-tabs .tabs-nav').css('margin-right', ($('#admin-topbar').width() + 20) + 'px');
    ", {'group': 'bottom'}) %}
```
