### ISSUE TITLE
Maintain cursor position and fullscreen on "save"

### ISSUE THREAD

**Issue by hamiltont** [getgrav/grav-plugin-admin#1627]
Similar to #1034 

I know ajax is being evaluated. I'm wondering if it would be easy to add some values to the save post that are passed onwards to the page reload and trigger the javascript to re-enter fullscreen and re-position the cursor to where it was when 'save' was triggered. 

Seems like a nice 'tweak' to make the UI better today without having to write an entire ajax pipeline

**Comment by rhukster** [comment]
We're trying to limit UI tweaks in current admin as we want to focus on a new version of the admin plugin this year. These are the exact kinds of things we want to address.
