### ISSUE TITLE
Bug: Admin Dashboard "Maintenance" box not picking up MR cron backup

### ISSUE THREAD

**Issue by matchavez** [getgrav/grav-plugin-admin#1629]
Hello all,

I've noticed a mismatch. Now that I have cron running nightly backups, the green Maintenance box in the Dashboard doesn't seem to be aware of those backups. I'm sure it's just triggered by manual backups as it has in the past, but I wanted to point out that it now has a mismatch.

Cheers.

**Comment by rhukster** [comment]
How are you doing the backups?  Are you using the Grav 1.6 scheduler/backup capability or your own in Grav 1.5?

**Comment by matchavez** [comment]
Sorry. I should have mentioned that it's the 1.6 Cron setup you just solved, Andy. :)

**Comment by rhukster** [comment]
Ok, i found it..only the admin task was logging last backup, moved that logic to the backup class itself, so it will be the same no matter how you initiate backup.... fixes in Grav + Admin
