### ISSUE TITLE
Forbidden issue after submitting the grav form

### ISSUE THREAD

**Issue by geogeorgejoseph** [getgrav/grav-plugin-admin#1632]
Forbidden issue after submitting the grav form

**Form**
--------

![grav-form](https://user-images.githubusercontent.com/25584016/54526756-c24c8a80-499d-11e9-9fd8-523f304cc306.png)

**Issue**
---------
![403-Forbidden](https://user-images.githubusercontent.com/25584016/54526755-c1b3f400-499d-11e9-8f11-98021ef837f2.png)

**Comment by rhukster** [comment]
Please open this in form plugin, not admin.  Cheers: https://github.com/getgrav/grav-plugin-form
