### ISSUE TITLE
Wrong version being recommended to updater

### ISSUE THREAD

**Issue by Yandols** [getgrav/grav-plugin-admin#1633]
As of the release of Grav 1.5.9, the admin plugin is recommending to update to the wrong version.

The updater should continue to recommend Version `v1.8.19` of the Admin Panel for the Grav Stable 1.5 branch, but is now recommending to update to `v1.9.0-beta.1` instead.

Attempting to update however will yield this error message since it's not for the right version of Grav:

```
One of the packages require Grav >=1.6.0-beta.1. Please update Grav to the latest release.
```

Unless it is actually compatible (I only use stable so I don't know how different is unstable branch), then this should be resolved.

**Comment by rhukster** [comment]
I'm seeing this also, but i don't see anything wrong.  will investigate further...

**Comment by rhukster** [comment]
This was sorted by @w00fz ... we had reached our maximum of pre-releases.. do a clear cache and it shouldn't prompt you anymore.
