### ISSUE TITLE
Page media order in Expert mode

### ISSUE THREAD

**Issue by petira** [getgrav/grav-plugin-admin#1634]
Page Media order in Expert mode are not ordered by `media_order` and change order is not possible in Page Media section.

(But perhaps it is the intention.)

**Comment by rhukster** [comment]
Actually, that is intentional.  There's no advanced Tab, so ordering can't be changed.  This is a limitation that we will address in a future version.

**Comment by petira** [comment]
Yes, it is quite logical. If the change occurs in the Page Media section, it would have to be immediately reflected in the `media_order` and vice versa. So it is really fine that the media in the Page Media section are now sorted by default and cannot be edited. Just as the change is done only in the `media_order` variable.
