### ISSUE TITLE
Template for "Add a custom page creation modal"

### ISSUE THREAD

**Issue by k1ll1n** [getgrav/grav-plugin-admin#1635]
Hi!
what should be the path for a custom template?
![unknown](https://user-images.githubusercontent.com/4102348/54796216-f10a7f80-4c81-11e9-8760-0cc7563fbd04.png)
I tried:
`active theme: plugins/admin/partials/templatename.html.twig`
`active theme: admin/partials/templatename.html.twig`
etc
None of this works

**Comment by julienbenisty** [comment]
Hi @k1ll1n 
Did you finally manage to do it?
The guide is correct and works well. Maybe this will help.
Say you have a theme called `my-theme/`
You should have a folder called `templates/` which should be in `user/themes/my-theme/`, therefore you should have `user/themes/my-theme/templates/`
And say you have a custom template called my-project.html.twig, therefore you should have 
`my-theme/templates/my-project.html.twig`

Now, say you want to add a custom button and modal in the admin panel to create a new project.
You will create a file called `new_project.yaml `in `user/blueprints/admin/pages/`, therefore you will have `user/blueprints/admin/pages/new_project.yaml`
And in `user/config/plugins/admin.yaml` you should add the following:
```
add_modals:
  -
    label: Add Project
    blueprint: admin/pages/new_project
    show_in: bar
```
Note that for the setting `show_in` you have 2 options: `bar` or `dropdown`.
And now, if you refresh the `pages` list of the admin panel, you will see your new button called
 `Add Project`.
I hope it helps.
