### ISSUE TITLE
imagethumbnail generation

### ISSUE THREAD

**Issue by pr0grammr** [getgrav/grav-plugin-admin#1637]
I tried to display my thumbnail as explained in the doc. 

`{{ page.media["sample-image.jpg"].display('thumbnail').html() }}`

and i tried various varations with the thumbnail filter and display filter. but it only shows the original image.. i dont see that it creates the thumbnails.. i really need the thumbnails for performance optimizing.. 
so how are the thumbnails created?

**Comment by rhukster** [comment]
You can resize images on the fly but the thumbnail method will look for a predated .thumb file. 

https://learn.getgrav.org/15/content/media#thumbnail-location

**Comment by pr0grammr** [comment]
ok, thanks, thats nice to know.. 
but is it possible to resize and keep the aspect ratio? so eg. i just provide a value for width and its resized and keep its aspect ratio?

**Comment by rhukster** [comment]
Ya cropZoom should handle that for you.

**Comment by pr0grammr** [comment]
thanks! i will try that

one last question.. the images are resized when i load the page and will be cached? so i dont have to reupload the images again?

**Comment by rhukster** [comment]
Correct.

**Comment by rhukster** [comment]
https://learn.getgrav.org/15/content/media#cropresize-width-height

Pretty sure you have to specify both but you can give the other dimension a large value that will never be reached.

**Comment by pr0grammr** [comment]
ok, thanks, that would be the alternative way. i just wrote a twig macro, that resizes the image to a given percentage. 

`{% macro resize_image(imageObj, percent) %}

    {% set width = (imageObj.width * percent) / 100 %}
    {% set height = (imageObj.height * percent) / 100 %}

    {{ imageObj.resize(width, height).url }}

{% endmacro %}`

`<img src="{{ _self.resize_image(image, 60) }}" alt="{{ page.title }}" />`

So that will resize the image to 60% of the original image. You can add it if you like or i make a PR. 
Thanks for the advice!

**Comment by rhukster** [comment]
Nice job!
