### ISSUE TITLE
Social Links Steam

### ISSUE THREAD

**Issue by martirale** [getgrav/grav-plugin-admin#1638]
Steam's social link does not disappear after deleting the word "test" in the field.

**Comment by rhukster** [comment]
steam's social link? not following.

**Comment by martirale** [comment]
In the configuration of the theme, in the fields where the URLs are placed to our profiles in social networks had a small error.

This error is that when you erase the word "test" that comes by default in the Steam field, it does not disappear. Already solved. I just deleted a line in the configuration files on my server.

Thank you!
