### ISSUE TITLE
grav 0.9.42 and grav-plugin-admin error

### ISSUE THREAD

**Issue by simogeo** [getgrav/grav-plugin-admin#164]
Hi, I just tried to install grav-plugin-admin error after a fresh grav 0.9.42 update.

After authentication process I get the following error : 

```

Server Error

Sorry, something went terribly wrong!
E_ERROR - Call to a member function getInstalledPlugins() on a non-object
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.

```

here is the log message : 

> [2015-09-12 23:41:32] grav.CRITICAL: Call to a member function getInstalledPlugins() on a non-object - Trace: #0 /path/to/grav/vendor/filp/whoops/src/Whoops/Run.php(357): Whoops\Run->handleError(1, 'Call to a membe...', '/grav/www...', 417) #1 [internal function]: Whoops\Run->handleShutdown() #2 {main} [] []

**Comment by trojkat** [comment]
Same here
```
Whoops\Exception\ErrorException thrown with message "Call to a member function getInstalledPlugins() on a non-object"

Stacktrace:
#0  in /srv/www/grav/user/plugins/admin/classes/admin.php:417
```

**Comment by rhukster** [comment]
How did you guys install? via GPM?  can you try a:

```
$ bin/gpm index --force
```

to clear the GPM cache

**Comment by rhukster** [comment]
Just so you know what we are dealing with here, its the line in here:

```
    public function plugins($local = true)
    {
        $gpm = $this->gpm();

        return $local ? $gpm->getInstalledPlugins() : $gpm->getRepositoryPlugins()->filter(function (
            $package,
            $slug
        ) use ($gpm) {
            return !$gpm->isPluginInstalled($slug);
        });
    }
```

So for some reason your `$gpm` object is null. This is usually caused by the inability of the server to get the GPM information from the getgrav.org server.  The weird thing is that if you installed via GPM, it should work because its the same call happening from the admin as the GPM command line utility does.

**Comment by trojkat** [comment]
Yes, via GPM. After doing `bin/gpm index --force` bug still occurs.

**Comment by trojkat** [comment]
Problem solved `cache/gpm` didn't have write permissions.

**Comment by simogeo** [comment]
> Problem solved cache/gpm didn't have write permissions.

Indeed. Thanks
