### ISSUE TITLE
Backup Manager Scheduler problem (v1.6.0-rc.4 - Admin v1.9.0-rc.4)

### ISSUE THREAD

**Issue by ozbod** [getgrav/grav-plugin-admin#1640]
In Grav v1.6.0-rc.4 - Admin v1.9.0-rc.4 when opening the scheduler from backup manager throws a code error:

 TypeError
Return value of Symfony\Component\Process\Process::close() must be of the type integer, null returned

Have attached a full screenshot in case that helps
![process-close](https://user-images.githubusercontent.com/9497537/55195311-0b71bb00-51a4-11e9-9dc2-cfde16e53111.png)

**Comment by mahagr** [comment]
Looks like a bug in Symfony Process, to be honest.
