### ISSUE TITLE
Hovering over labels in Safari makes them disappear

### ISSUE THREAD

**Issue by lucaswillering** [getgrav/grav-plugin-admin#1643]
In Safari, if you hover a label/field name in the admin plugin, the label disappears.

You can test this in the site configuration or for example the 'options' and 'advanced' tabs of a page.

**Comment by paulhibbitts** [comment]
I am seeing this too - latest Mac OS/Grav 1.6 RC 4 release

![2019-04-10_08-00-13 (1)](https://user-images.githubusercontent.com/1812771/55890077-eea39300-5b66-11e9-8ce1-e0d1bf0c4f15.gif)

**Comment by rhukster** [comment]
mine's even worse, all jumps to top right corner!
