### ISSUE TITLE
Possible issue with use of |raw (after discussion with Matias)

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#1644]
My apologies @rhukster but after a discussion with @mahagr about a suggested PR for Quark using `|raw` for page titles (https://github.com/getgrav/grav-theme-quark/pull/107#event-2266342998) perhaps it is best to remove `|raw` as well from the recent commit for displaying page title vs menu in the Admin Panel? https://github.com/getgrav/grav-plugin-admin/commit/e0bec534d681bf165b32a4d3340cefd59db6bef4

Thanks very much,
Paul

**Comment by rhukster** [comment]
I've removed `|raw` from the page title.  thanks.
