### ISSUE TITLE
Upgrade Bug - "v7.3.1 required" (instead of v7.1.3)

### ISSUE THREAD

**Issue by mkacfr** [getgrav/grav-plugin-admin#1646]
Please go and see the folowing image to understand my bug --> https://ibb.co/9pLhK0W
If I understood the  Andy Miller's post : https://getgrav.org/blog/raising-php-requirements-2018 and the last changelogs... this restriction is nonsense :-S and should be "v7.1.3 required".... and not "v7.3.1 required" (inversion?)

Thanks GRAVTEAM for your wonderfull work and updates... Amazing !!!

Take Care,
-Michael- (from France)

**Comment by rhukster** [comment]
OK, turns out this is not a bug.  It's intentional because there were some really bad bugs in PHP 7.3.0 that caused Grav not to work properly.  These were fixed in PHP 7.3.1, hence the message.
