### ISSUE TITLE
Uploaded Avatar removed from user's yaml when editing e.g. name of the user

### ISSUE THREAD

**Issue by cyberlussi** [getgrav/grav-plugin-admin#1647]
Hi,

when changing the user e.g. his own password or email, a previously uploaded avatar gets nulled in the users yaml. Hence the avatar needs to be uploaded again.

I use Grav 1.6.2.

**Comment by rhukster** [comment]
confirmed

**Comment by mahagr** [comment]
Should be fixed now with data user (default setting).

**Comment by rhukster** [comment]
In release
