### ISSUE TITLE
Updating Folder Names / Slugs broken

### ISSUE THREAD

**Issue by lasse186** [getgrav/grav-plugin-admin#1648]
Since updating to Grav 1.6.2 it seems like updating existing Folder Names / Slugs stopped working.

Updating the field in the admin and hitting Save will show "Successfully saved" but the string won't change and jump back to the initial value. I thought it's maybe linked to folder permissions, but nothing has changed and they are still running on  755.

Updating the folder name manually via FTP works perfect. And also creating new folder works perfect.

Site is running on Grav v1.6.2 // Admin v1.9.0 // PHP Version 7.3.3-nmm1

PS: Due to the increased PHP requirement, PHP was also updated to 7.3 with the update to 1.6.2

**Comment by rhukster** [comment]
confirmed.

**Comment by rhukster** [comment]
Fixed in 1.9.1
