### ISSUE TITLE
No child type for this rawroute

### ISSUE THREAD

**Issue by PodrugStudio** [getgrav/grav-plugin-admin#1650]
When trying to move page under another page - I get notification No child type for this rawroute and it cannot be moved.

Same happens with latest grav install (1.6.2) or if I upgrade from 1.5.10
This error start appearing after upgrading admin-plugin to v1.8.20

**Comment by rhukster** [comment]
OK, the message was just a status message saying no child_types had been set. However, this is kind of a useless message and only serves to confuse, so i've commented this out.

The problem with the file not moving was a bug with save which I've resolved here: https://github.com/getgrav/grav-plugin-admin/commit/33c84222d74409616a7f60587087284369d6fddb

**Comment by rhukster** [comment]
Fixed in 1.9.1

**Comment by PodrugStudio** [comment]
I confirm it is working fine.
Thanks!

**Comment by rhukster** [comment]
cool,
