### ISSUE TITLE
Folder Prefix Enabling doesn't stick

### ISSUE THREAD

**Issue by geudde** [getgrav/grav-plugin-admin#1651]
I have a simple page structure of chapter1 > chapter2 > doc

Creating a new doc in the second level of chapters has always switched the default to Folder Prefix Number disabled. Manually enabling it in the admin panel has reset the inherited default for subsequent docs in that chapter.

That isn't working since I updated to Grav 1.6.x. Saving the doc with Number Prefix Numbering set to enable doesn't preserve the new setting. It's still disabled. I've been adding prefixes manually, and once I've added one, all works as before.

**Comment by rhukster** [comment]
Did you try 1.9.1 of admin? I released it yesterday.

**Comment by geudde** [comment]
> Did you try 1.9.1 of admin? I released it yesterday.

Thanks for the heads-up. I've updated the admin plugin and all's well again. Much appreciated!
