### ISSUE TITLE
Unable to add page in Grav 1.6.3

### ISSUE THREAD

**Issue by jameswill** [getgrav/grav-plugin-admin#1652]
I have installed Grav 1.6.3 on one of our test servers with PHP 7.1 and Mysql 5.6  I am unable to view any new page added through admin panel. (except default pages)

When I add a new page and preview it, it shows "Error 404 Woops. Looks like this page doesn't exist "

It worked fine on my another test server. On further debugging I found that when I keep "Debugger: enabled= True" in user\config\system.yaml, I can view newly added page and its preview.

**Comment by rhukster** [comment]
Does admin 1.9.1 fix the issue?

**Comment by EroticD** [comment]
> Does admin 1.9.1 fix the issue?

1.9.1 does not fix this issue. Downloaded complete grav+admin from getgrav.org, and uploaded to my webserver.

Not letting me install any plugins, not letting me add pages, folders or modulars.

**Comment by rhukster** [comment]
Doesn’t sound like the original issue.  Please create a new issue and provide some more details like what errors you get etc.

**Comment by EroticD** [comment]
No errors at all, just does nothing. Debug not active though.

tir. 16. apr. 2019 kl. 15:02 skrev Andy Miller <notifications@github.com>:

**Comment by rhukster** [comment]
Can't replicate this.. can add everything just fine.. 1.9.2 is out now BTW, might wanna try that.

**Comment by EroticD** [comment]
I am now on 1.6.5 with admin 1.9.2. Fresh install
![2019-04-16-163853_1920x1080_scrot](https://user-images.githubusercontent.com/12676250/56219104-76f1ce80-6066-11e9-92e8-14ba1cbb7bb8.png)

Unable to add anything.

**Comment by rhukster** [comment]
If you open up your browser dev tools and look at the console, you probably have an error.  What does it say?  

Also what plug-ins do you have installed? Try disabling any that are don’t have a blue check mark (third party) and see if that makes a difference.

**Comment by EroticD** [comment]
No error in dev console. 
The plugin ' Admin Addon Media Rename v1.6.2 ' was at fault, and did something strange. All is good in latest release.

**Comment by rhukster** [comment]
Great, thanks fo the update.
