### ISSUE TITLE
Error updating version 1.6.2 to 1.6.5

### ISSUE THREAD

**Issue by ZelTrad** [getgrav/grav-plugin-admin#1653]
Hello.
When upgrading from version 1.6.2 to version 1.6.5, an error occurs "Invalid AJAX response." What could this be about? and how to fix?

**Comment by rhukster** [comment]
I downloaded a fresh `grav-admin-v1.6.2.zip` package here: https://github.com/getgrav/grav/releases/download/1.6.2/grav-admin-v1.6.2.zip

Installed it, and upgraded just fine to 1.6.5. 

So not sure what's going on for you.  

* First thing I would try is to force update check again by hitting "check for updates" in dashboard. After that try upgrading again.
* Second, you could try upgrading via CLI with `bin/gpm self-upgrade`
* Third thing, in admin you could try `Tools` -> `Direct Install` and upload the update package: https://github.com/getgrav/grav/releases/download/1.6.5/grav-update-v1.6.5.zip

**Comment by ZelTrad** [comment]
> 
> 
> I downloaded a fresh `grav-admin-v1.6.2.zip` package here: https://github.com/getgrav/grav/releases/download/1.6.2/grav-admin-v1.6.2.zip
> 
> Installed it, and upgraded just fine to 1.6.5.
> 
> So not sure what's going on for you.
> 
>     * First thing I would try is to force update check again by hitting "check for updates" in dashboard. After that try upgrading again.
> 
>     * Second, you could try upgrading via CLI with `bin/gpm self-upgrade`
> 
>     * Third thing, in admin you could try `Tools` -> `Direct Install` and upload the update package: https://github.com/getgrav/grav/releases/download/1.6.5/grav-update-v1.6.5.zip

If you update manually downloading packages, then everything is correctly set. I decided to figure out why not updated. I found why the update is not happening.
In the admin panel settings, "Remote update method" you need to select "fopen" and it was "Automatic"
Now the update is going well.

**Comment by rhukster** [comment]
Cool. Closing then.
