### ISSUE TITLE
redirects show up on address bar

### ISSUE THREAD

**Issue by thomasb892** [getgrav/grav-plugin-admin#1654]
when I redirect main domain to the index.php of Grav then odd, things happen.
For example subfolder name - subf

orginal url - abc.com/
becomes - abc.com/subf/
Note: It happens without using the R fag in .htaccess

RewriteCond %{HTTP_HOST} indiaxis\.org$
RewriteRule ^(.*)$ subf/index.php/$1 [QSA,L,NC]

How to fix this?

**Comment by rhukster** [comment]
first, sounds like a core issue, not admin.. so wrong repo.

second, you should definitely NOT be redirecting to main index.php. It will break all the routing.
