### ISSUE TITLE
Running 1.9 branch local doesn't work, Output filename not configured on Webpack

### ISSUE THREAD

**Issue by hdwebpros** [getgrav/grav-plugin-admin#1655]
I'm trying to run 1.9 branch locally to test and submit fixes, but errors persist.

Steps to reproduce:

- Go to https://github.com/getgrav/grav-plugin-admin and create a fork by clicking the fork button. I hope you didn't create one already. If you did, you'll likely have to just delete your old fork and make a new one. Babker can help if that's the case.
- Clone that fork off to the side for now
- Download the 1.6 Beta grav (no admin, just Grav)
- Extract that Grav in your local setup (Homestead area, etc) and setup your hosts file to look for it
- use vagrant ssh or whatever ssh tool ya want and go to the site root for that grav install and run `php bin/gpm install login`. Say yes to installing the other dependncies
- Once installed, go to your user/plugins/ folder and create one called `admin`
- Copy your forked repo over to that admin folder you just created
- On your command prompt, navigate to that admin folder root then type `git checkout 1.9`
- Finally, go to your site and make the admin account and log in. Go to a page edit screen. You won't see the unset icon anywhere if you had luck like me
- navigate to `themes/grav` within your admin plugin and run `npm install`
- Now, running `npm run dev` should work. It doesn't. That's where I'm hung up.

I get the following error:
> Output filename not configured.

There is no output filename configured in the Webpack conf file. I'm stuck here, can't compile the JS to test any potential fixes, like trying to help out in the issue: https://github.com/getgrav/grav-plugin-admin/issues/1427

**Comment by w00fz** [comment]
Admin still uses the old setup where I preferred Gulp. I never got to update it to use webpack like everything else we use nowadays.

For compiling admin you have to `gulp js` or `gulp watch`

**Comment by w00fz** [comment]
I will also update the `package.json` to use the proper commands

**Comment by rhukster** [comment]
Also make sure you use `develop` branch now for Grav and Admin as `Grav 1.6` and `Admin 1.9` are released.

**Comment by hdwebpros** [comment]
Thanks for the update. I'll keep my eye out for the `package.json` update

**Comment by w00fz** [comment]
I updated it with https://github.com/getgrav/grav-plugin-admin/commit/9ae5502925f5c32641835fbbfd4098d1a54c8067 👍
