### ISSUE TITLE
Question about theme "Receptar"

### ISSUE THREAD

**Issue by ZelTrad** [getgrav/grav-plugin-admin#1658]
Hello. I really liked this topic. Now I understand it. I found a lot. But I can not find it even in scripts where the name changes: My Blog
![555](https://user-images.githubusercontent.com/49678741/56499257-9aa98e80-6516-11e9-8677-a5e63e355adb.png)

**Comment by rhukster** [comment]
Wrong repo. Please open on Receptar theme repo.
