### ISSUE TITLE
Unable to turn caching on after upgrading from 1.5.10 to 1.6.8

### ISSUE THREAD

**Issue by Yandols** [getgrav/grav-plugin-admin#1662]
_(Again, i'm not sure whether to open this here or at the admin panel repo, but I'll re-open one there if this is the wrong place for it)_

I can no longer turn on caching through the admin panel and it was defaulted to `off` after upgrading. When I attempt to turn it on again it just goes back into the `off` setting after saving. 

Everything else that I changed was saved so it's not a permission writing problem, so I don't know what's causing this to happen.

**Comment by rhukster** [comment]
Grav core itself has no way to change values, only the admin can create or modify files (unless you do it yourself at the files-level).  Grav works by using the `system/config/system.yaml` as the default values, and then when you modify things, you store those **override** values in `user/config/system.yaml`.  It sounds like that the admin plugin is unable to save to `user/config/system.yaml` and therefore it's going back to the system level defaults.

I would check the permissions of this file, and perhaps the whole `user/config/` folder.

**Comment by Yandols** [comment]
The permissions in `user/config/` are correct, it's `0775`, the same as when I first set it up in 1.5.x. When I change any other settings through the configuration page in the admin panel they do get saved correctly, all except for the Caching setting, it keeps going back to off for whatever reason.

**Comment by rhukster** [comment]
What if you manually change the setting via editing the `user/config/system.yaml` file?

**Comment by Yandols** [comment]
Alright this is interesting. I've manually edited the file to have it enabled by changing `cache: enabled:` to `true`. When I go back into the admin panel and navigate to the configuration it is still displayed as being turned off. If I turned it back on and saved the settings through the admin panel, navigate away and come back, it'll be off again.

**Comment by rhukster** [comment]
Do you have an environment-based configuration folder that has an override of `user/config/system.yaml`?  Ie, `user/yoursite.com/config/system.yaml`??? If you have a setting here, perhaps this folder is the ones with the bad permissions that is not letting you save?

more info here: https://learn.getgrav.org/16/advanced/environment-config

**Comment by Yandols** [comment]
No, I have all my grav instances completely isolated from each other and have not set up any environment-based configuration.

**Comment by rhukster** [comment]
You've stumped me! :) I really am out of ideas...

**Comment by Yandols** [comment]
I'll try setting up another fresh instance of grav to compare results. In the meantime, is there any other information I can provide you with to help further investigate this problem?

**Comment by rhukster** [comment]
Try a new Grav install, myabe just the grav+admin package, and see if you can recreate this issue.  Else, you are going to have to send me your site so i can try to recreate things locally. 

Another thing to try, disable any 3rd party (non Grav/Trilby) plugins, especially anything related to admin.

**Comment by Yandols** [comment]
Alright, so I had set up a new and clean instance of grav to do some testing and comparison. Owner and group is `apache` and every single file and directory is set to `0775` for perms. Tried toggling caching around and it didn't seem to have a problem with it, however statistics are still not generating as I originally reported in #1663. Will also update this on the other issue.

That aside, I tried to replicate my setup on my the instance where this originally occured on, and found out something. So it turns out that this problem occurs when I install **Quark Open Publishing** theme. It seems that the 1.6 version of Quark Open Publishing or one of it's dependencies enforces caching to be turned off for some reason. 

I tried to troubleshoot and see if it was one of it's dependency plugins that was causing the problem but when I turned some of the plugins off, the entire grav site stopped working so I had to manually edit the plugin config.yml to reenable it.

Maybe you'll have a better idea on what's causing this since I've managed to track down some more things related to this problem.

**Comment by paulhibbitts** [comment]
Hi @Yandols , I am the author of Quark Open Publishing (Quark does all the heavy lifting). Perhaps as an additional test have you tried to download the Open Publishing Space Skeleton? I am not aware of how the theme itself would prevent turning on/off the cache.

**Comment by Yandols** [comment]
I was thinking and hoping that there was gonna be a difference in results in this test as I haven't done that.

Unfortunately it yielded the exact same results. I downloaded the skeleton and set it up for testing, immediately go to configuration and see that Caching was turned off by default. And again, can't be kept in the on position.

Here is a screen recording: https://arceus.zxicar.us/o/2019-04-28_17-20-06.mp4

**Comment by paulhibbitts** [comment]
With that skeleton, does the same issue exist if you change the active theme to Quark @Yandols ?

**Comment by Yandols** [comment]
@paulhibbitts Apologies for the much delayed response, was out of town for quite some time.

Anyways, yes, unfortunately there was no difference as the same issue exists when changing the active theme to Quark. The cache was in the "off" position by default and still remains off after being toggled on and returning to the configuration page.

**Comment by paulhibbitts** [comment]
Sorry but I am stumped @Yandols

**Comment by Yandols** [comment]
Well that is a bummer. I've tried changing a few things around but I can't produce any different results either. I'm closing this issue for now until something changes or until I can find out more information on why is this happening for me.

**Comment by mahagr** [comment]
@Yandols Make sure you enable debugbar and look what the configuration looks like (there's config tab with a full dump from the site configuration). Maybe you will get some hints from there from what is going on...?
