### ISSUE TITLE
Statistics no longer updates after upgrading from 1.5.10 to 1.6.8

### ISSUE THREAD

**Issue by Yandols** [getgrav/grav-plugin-admin#1663]
_(I'm not sure to open this here or on the admin panel repo, but I'll reopen one there if this is the wrong place for it)_

After upgrading one of my sites to the latest version, the statistics counter shown on the admin panel no longer updates. It remains static with statistics collected from before the upgrade. Visiting pages on the site won't add anything to it's counter where it previously would.

I've tried resetting it by deleting the `popularity` folder under `/logs`. In the past where I've done this, it would completely reset it and regenerate the files again. However on 1.6.8 that doesn't seem to be happening. The `popularity` folder and its files are not regenerating thus the statistics are all displayed as 0.

**Comment by rhukster** [comment]
Like your other issue, it sounds like permissions.  If the `user/data/` folder is unwritable by the webserver, you won't get updated statistics.

**Comment by Yandols** [comment]
I don't think that's the case as everything else is working fine. All permissions are either `0755` or `0775` for apache, so they should work fine just like they did before the upgrade.

**Comment by rhukster** [comment]
You are the only person having this issue, so stands to reason it's an issue on your end. 99% of the time the culprit is permissions. Is the **owner** of the folders the same one as the owner of the webserver process?  If it's not then `755/775` is not going to be much help.

**Comment by Yandols** [comment]
I've just double checked to confirm. Yes owner and group of the folders are owned by `apache` which is the webserver process. I can see backups that I've just made written in the log file.

**Comment by Yandols** [comment]
I've set up a brand new instance of grav to see if this problem occurs on a clean install and it indeed is still occuring, no statistics file is being generated and thus nothing is being written. Owner and group is `apache` and every single file and directory is set to `0775` for perms.

I went to check on one of my instances that is still running 1.5.10, making sure not to accidentally hit update grav and the statistics is indeed being collected and updated accordingly. So from my testing, this only occurs on 1.6(.8) regardless if I make a clean install or an upgrade.

**Comment by axel-rank** [comment]
Yes, I can confirm. No statistics in Grav 1.6.8

**Comment by rhukster** [comment]
I just installed a basic Grav Blog Skeleton and statistics work fine.  Must be some other plugin you guys are running.

**Comment by rhukster** [comment]
BTW, that logic has not changed at all in 1.6

**Comment by Yandols** [comment]
It's definitely not a plugin I am running as this also occurs on a fresh installation of 1.6.8.

Here's a screen recording of me setting up the quark open publishing skeleton for my other issue, but the statistics not collecting/updating is also shown here: https://arceus.zxicar.us/o/2019-04-28_17-20-06.mp4

**Comment by axel-rank** [comment]
Plugins:

![Bildschirmfoto_2019-04-28_12-53-21](https://user-images.githubusercontent.com/12480617/56863290-ec3d9780-69b4-11e9-8637-554f89d8847b.png)

**Comment by axel-rank** [comment]
Found the problem:
Just did a clean GRAV/Admin install and compared the standard settings.

![Bildschirmfoto_2019-04-28_13-49-22](https://user-images.githubusercontent.com/12480617/56863900-89e89500-69bc-11e9-91f9-42b0b960e3b9.png)

The first ignore setting was set to / instead of /test*
So after resetting to /test* Statistics working again.
