### ISSUE TITLE
The main page does not open if the folder does not have the name "home"

### ISSUE THREAD

**Issue by ZelTrad** [getgrav/grav-plugin-admin#1664]
When you create a page, if you just call the folder "home", then it goes to the main? And if you call it differently then the page will not be the main one.
![home](https://user-images.githubusercontent.com/49678741/56850589-daf17e00-6915-11e9-9a00-089a18e7078a.png)

**Comment by rhukster** [comment]
https://cl.ly/49e7a23f5560

Cannot replicate with either different name or different folder.
