### ISSUE TITLE
Premature end of script headers: php71.cg

### ISSUE THREAD

**Issue by SephReed** [getgrav/grav-plugin-admin#1666]
On almost every screen in grav admin, I get a 500 internal server error popup.  I've checked the error logs, and found the following.

Upon looking the error up I found that it is generally a file permission issue (https://stackoverflow.com/questions/17583341/error-500-premature-end-of-script-headers).  I tried modifying the permissions of all of the files from my root folder up, going so far as `chmod 777 -R .`, but the error persists.

I'm pretty sure I'll have to message my provider (dreamhost) if it's a permission issue beyond this scope, but I'd like to know what's going on first.  Below is a chunk of my error logs:

```
[Sun Apr 28 14:20:34 2019] [error] [client 70.116.45.205] Premature end of script headers: php71.cgi, referer: http://www.someurl.com/admin
[Sun Apr 28 14:20:39 2019] [error] [client 70.116.45.205] Premature end of script headers: php71.cgi, referer: http://www.someurl.com/admin/pages
[Sun Apr 28 14:20:44 2019] [error] [client 70.116.45.205] Premature end of script headers: php71.cgi, referer: http://www.someurl.com/admin/pages/home
[Sun Apr 28 14:20:44 2019] [error] [client 70.116.45.205] Premature end of script headers: php71.cgi, referer: http://www.someurl.com/admin/pages/home
```

Any clues on what's going on here?

**Comment by SephReed** [comment]
This is the request which is generating the errors:

```
Request URL:http://www.someurl.com/admin/task:getNotifications
Request method:POST
```

**Comment by rhukster** [comment]
Maybe try changing the `Remote Fetch Method` in **Advanced** section of **System** configuration to `fopen` rather than `auto`

**Comment by SephReed** [comment]
Did not seem to do the trick.  Do you know what php71.cgi is about?

**Comment by rhukster** [comment]
It’s the PHP 7.1 CGI process that your web server is using to serve the PHP. It’s very much a server side thing so you will probably need to talk to the support folks.

**Comment by SephReed** [comment]
Kk.  thanks for the clue
