### ISSUE TITLE
language code bug when save as ca-valencia or any code with more than 5 characters

### ISSUE THREAD

**Issue by robotpapier** [getgrav/grav-plugin-admin#1667]
Hi,
I would like tom ake a special use of the language. Instead of language I would use a city name of the same language.
I noticed if the language code you add in system.yaml is more than 5 character,
the file that is writen does'nt work correctly.

For instance if I add language fr-paris and in my page I save as frparis,
grav redirects me to login and the file written looks like this  default.frparis.frparis.md 
whereas if the language code is no morethan 5 character like paris, it's working and the file is written properly : default.paris.md

If I try with ca-valencia which is in the laguage code array (LanguageCodes.php), it's the same.

Does anyone know a way I can use language code that is more than 5 characters?

Thanks

**Comment by robotpapier** [comment]
I think so, I must login again to re-access admin

**Comment by robotpapier** [comment]
Oh, no, it's just that it redirects to http://localhost/frparis/admin/pages/home instead of http://localhost/admin/pages/home

**Comment by rhukster** [comment]
ok, this is a multi-part issue.. there actually **are** some legit Grav side issues.. I think I have addressed these here: https://github.com/getgrav/grav/commit/4f83b5da5b1ab6e792e2aed46a3eff702d98dd20

Now I need to tackle the admin issues that are related to the saving of the filenames.

**Comment by robotpapier** [comment]
I kept on searching to find a temporary fix.
I found at line 2376 of plugins/admin/classes/admincontroller.php,
the function determineFilenameIncludingLanguage is responsible for the filename.
I commented the following at line 2385 :
`//$filename .= '.' . $language;`

now the filename is correct but it still redirect to 
http://localhost/frparis/admin/fr/admin/pages/home

**Comment by rhukster** [comment]
Please try with the Fix above, this should handle the different scenarios safely.

**Comment by rhukster** [comment]
The redirection to login issue is sorted by the commit in grav i referenced a little further above.

**Comment by robotpapier** [comment]
works perfect! thanks!
are the commits going to be included in next version of grav or should I fix the codes after each update?

**Comment by rhukster** [comment]
They will be in next set of releases

**Comment by robotpapier** [comment]
As I will have more than 170 cities, 
I just adding a css modification of the file user/plugins/admin/theme/grav/css-compiled/template/_buttons.scss at line 72 to get a scrollingbar in the dropdown menu.
I put it here for reference : 

`.button-group .dropdown-menu.language-switcher {
    min-width: 50px;
    max-height: 300px;
    overflow: scroll;
}

.button-group .dropdown-menu.lang-switcher {
    min-width: 150px;
    left: inherit;
    right: 0;
    max-height: 200px;
    overflow: scroll;
}
`
