### ISSUE TITLE
Task Markdown give jQuery error

### ISSUE THREAD

**Issue by namaless** [getgrav/grav-plugin-admin#167]
I don't know why but when click on the eye here i give a jquery error into console.

https://monosnap.com/file/etcz6SWjgQhatfXZfrbLG5ZdvMsuVR.png

**Comment by rhukster** [comment]
I'm not seeing any error.. it just works and shows me the preview.  What browser are you using? if you inspect your XHR network traffic with dev tools, what does the response say?

**Comment by namaless** [comment]
I use chrome for windows, it's true this working but i give this:
https://monosnap.com/file/O9FXdR1FcvzesbhBGx6NgTXeStmPFZ.png

This the form data:
```
tab:on
header[title]:Thank You for Contact Us
content:Thank you for contact us!
header[published]:1
header[date]:
header[publish_date]:
header[unpublish_date]:
header[jscomments][provider]:
header[simple_form][token]:
header[simple_form][template_file]:
header[simple_form][redirect_to]:
header[sitemap][changefreq]:
header[sitemap][priority]:
ordering:0
folder:thank-you-for-contact-us
route:/plugins/simple-form
name:default
header[body_classes]:
order:
header[menu]:
header[slug]:
header[redirect]:
header[process][markdown]:1
header[child_type]:default
header[routable]:1
header[cache_enable]:1
header[visible]:1
header[template]:default
header[order_by]:
header[order_manual]:
blueprint:default
```

**Comment by namaless** [comment]
I have disabled all plugins for sure is not one of this create a problem.

When you click on markdown in top i see the notice popup "Not found" -> https://monosnap.com/file/5z67Ehoh8qbFmh3f1ORzSdkvWmqoLE.png

**Comment by rhukster** [comment]
What's the URL that it's requesting for you?

**Comment by namaless** [comment]
you can see here in panel "Request URL" https://monosnap.com/file/O9FXdR1FcvzesbhBGx6NgTXeStmPFZ.png

and the url where im are is this: http://localhost:8888/admin/pages/plugins/simple-form/thank-you-for-contact-us

But I tested the same into the Home page.

I don't know if change but I used a php builtin server php -S localhost:8888 in the grav root path.

**Comment by rhukster** [comment]
Ok, that's you problem. Due to the limitations in routing capabilities of the PHP built in webserver the admin plugin will not work with it: http://learn.getgrav.org/basics/installation#webserver

basically can't handle the `:` in the URL.
