### ISSUE TITLE
Admin Plugin change for multisite setup

### ISSUE THREAD

**Issue by AkkuFresh** [getgrav/grav-plugin-admin#1674]
This is a suggestion for the minor change in the 
file: user\plugins\admin\admin.php
About line 470 there is a block:
// If not provided by Admin, lookup pages added by other plugins
Inside the foreach loop there is a line:

`$path = $locator->findResource("user://plugins/{$plugin->name}/admin/pages/{$self->template}.md");`

My suggestion is change the stream from **user://** to **plugins://** like this

```
$path = $locator->findResource("plugins://{$plugin->name}/admin/pages/{$self->template}.md");
```

The reason is, if the multisite setup uses the changed user stream, like provided below, then the admin plugin will not find any page provided by the other plugins.

```
'streams' => [
        'schemes' => [
            'user' => [
               'type' => 'ReadOnlyStream',
               'prefixes' => [
                   '' => ["user/{$folder}"],
               ]
            ],
```
This change was tested in my multisite setup with success.

**Comment by rhukster** [comment]
Agreed, done...
