### ISSUE TITLE
backup fail

### ISSUE THREAD

**Issue by bcneb** [getgrav/grav-plugin-admin#1677]
Recently, perhaps since last upgrade the backup function is failing. Grav generates files with names like "default_site_backup--20190517053830.zip.Scdw45", and they are large files.  When downloaded, they cannot be expanded as zip files, so this seems to be some intermediate step on the way to the .zip file, and the last part of the process has failed.  Anyone else seen this?

**Comment by mahagr** [comment]
Those look like temporary files; maybe PHP ran out of memory while creating the archive? Please check your PHP error logs and Grav log files if they have any clues on what happened.

**Comment by bcneb** [comment]
Right, so it seemed that the backup process exceeded the 1GB memory limit of the host. I excluded a folder of pdf files and now it works.

Even on a fairly highend plan, a 1GB memory limit is common, so that I'm surprised this issue hasn't come up before!

**Comment by trevirtu** [comment]
Backup Manager in Grav not work correctly, this is de result:
Validazione fallita: 
Input non valido in "Backup Timeout"
Input non valido in "Maximum space allowed for backups"
Input non valido in "Keep backups x days"
Input non valido in "Backups to show"
Suggestions ? Thank's very much

**Comment by rhukster** [comment]
@trevirtu It sounds like you don't have everything up to date.  Are you on the latest Grav + Admin version?

**Comment by bcneb** [comment]
Everything definitely up to date!

**Comment by trevirtu** [comment]
Thanks for the reply
  I use gantry in grav and I have the latest version of everything,
I can't backup by excluding videos
thanks for your time answering me
