### ISSUE TITLE
Translation not works in admin panel grav v1.6.9, Admin plugin v1.9.4

### ISSUE THREAD

**Issue by ergoz** [getgrav/grav-plugin-admin#1678]
In admin panel i have a problem with translation is Service - backups. It shows me `GRAV.NICETIME.HR_PLURAL` and `GRAV.NICETIME.DAY_PLURAL`
I found that no HR_PLURAL in /system/languages/ru.yaml, but it have HOUR_PLURAL. I tried to fix it by adding `HR_PLURAL: ч` but it didn't help. And `DAY_PLURAL` already exists but not shows.

How it looks:
![](https://habrastorage.org/webt/8m/ew/ma/8mewmabgrcuoone1lcf7e-np2d8.png)

**Comment by rhukster** [comment]
![Image 2019-05-26 at 11 16 12 AM](https://user-images.githubusercontent.com/1084697/58379094-ba195880-7fa7-11e9-9ca9-cb53edfa6927.png)

![Image 2019-05-26 at 11 17 04 AM](https://user-images.githubusercontent.com/1084697/58379102-d917ea80-7fa7-11e9-9951-08a4896d22ee.png)

It works fine for me? Try clearing cache?

**Comment by mahagr** [comment]
I remember that those translation keys were changed for Grav 1.6 release, so it's likely that the translations used by the site are for the older version of Grav.

**Comment by ltGuillaume** [comment]
Why has this issue been closed? It is still there, and the suggestion by @mahagr that the translation doesn't have the proper (changed) keys is false.

**Comment by mahagr** [comment]
Forgot to add the duplicate tag, sorry.
