### ISSUE TITLE
PHP 7.3 admin/config/backups exception

### ISSUE THREAD

**Issue by matrixino** [getgrav/grav-plugin-admin#1679]
count(): Parameter must be an array or an object that implements Countable
for {% if backups|count == 0 %} in backupshistory.html.twig

**Comment by rhukster** [comment]
Are you on on latest Grav and Admin versions?  I'm on PHP 7.3 and cannot recreate this even with a fresh installation.

Also are you running Advanced Backup Manager plugin? That might be conflicting with Grav's new built-in capabilities.

**Comment by matrixino** [comment]
Grav v1.6.9
Admin Panel v1.9.4
No Advanced Backup Manager
All caching plugin disabled

![image](https://user-images.githubusercontent.com/6110527/58380965-809d1900-7fb8-11e9-9309-2f5cfa193229.png)
![image](https://user-images.githubusercontent.com/6110527/58380987-ba6e1f80-7fb8-11e9-83b1-27119575514e.png)
![image](https://user-images.githubusercontent.com/6110527/58380996-ce198600-7fb8-11e9-9311-87e69f3efa47.png)

Also, but not related, I noticed a bug in the Admin Addon Revisions v1.3.3 plugin. When enabled I'm getting asked if I want so save or lose changes when moving from the default Configuration Tab (System) even if no changes has been made (just loaded). It happens only when switching from System tab to any other.

**Comment by rhukster** [comment]
I think if you disable those "Admin Addon..." and "Admin PowerTools" plugins it will work fine.  They are causing the issues.

**Comment by matrixino** [comment]
Already tried, no luck. Even with those 3 disabled I still get the error.
Also PowerTools is required for the Editor plugin.

**Comment by mahagr** [comment]
Where are you getting the error? It looks like the field only works from the backup manager.

**Comment by matrixino** [comment]
I'm getting the error when switching to the backup tab in the configuration menu of admin plugin

**Comment by rhukster** [comment]
OK, that isolates the issue.

You should not see Backups in the configuration tabs, because you administer it from Tools.  

https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/templates/config.html.twig#L10

This code is saying to ignore backups and scheduler configuration up here.  This leads me to believe you are still running some plugin that 'overrides the `templates/config.html.twig` file that comes with admin plugin, and has not been updated to use the new logic.

**Comment by matrixino** [comment]
Found it. It's the Core Service Manager v1.0.16 plugin. I'll try to fix it now, since it's required for 3 other plugins.
