### ISSUE TITLE
Add page modal closes when selecting a template

### ISSUE THREAD

**Issue by tritos-design** [getgrav/grav-plugin-admin#1682]
When adding a page via the "Add page" button, the modal closes unexpectedly when the template select list extends to outside the modal and a template which lies "outside" of the modal is selected. Please refer to the attached screenshot.

![grav_add_page_modal_bug](https://user-images.githubusercontent.com/51099789/58441913-72e5b180-80e6-11e9-8cdd-c366ee484dab.png)

When Text or Ztest are selected the modal closes as if I had clicked anywhere outside the modal.

This seems to be browser dependent: The error occurs on Firefox for Ubuntu (67.0 (64-Bit)), but it is working fine in Chromium 73.0.3683.86. OS: Linux Mint 18.2

**Comment by blacoC** [comment]
I can confirm this bug. I'm using Arch Linux - and Firefox 67.0 has this issue, Chromium Version 74.0.3729.169 works fine.

Furthermore, this is also an issue if you're adding a new page and change the parent page to an value which is "outside" of the modal.

**Comment by rhukster** [comment]
Confirmed...

**Comment by SeriousKen** [comment]
Looks like this is a bug in remodal.js (https://github.com/vodkabears/Remodal) but this project is no longer maintained.

**Comment by clivebeckett** [comment]
I confirm that bug on Admin v1.10.0-rc.11 (Firefox 76 on a Mac) … I just wanted to add a bug report about it when I found this issue :)

**Comment by w00fz** [comment]
This bug has been permanently squashed.
