### ISSUE TITLE
Auto-Type Keepass login form

### ISSUE THREAD

**Issue by immertroll** [getgrav/grav-plugin-admin#1685]
The login form of the Grav Admin Plugin is the only frontend in the world where you can't use the Auto-Type function of Keepass.

The field will be filled correct with username and password but the login will allways fail.
You have to copy & paste each value manually!

Please fix it. It is really annoying.

Thx

**Comment by rhukster** [comment]
Works fine with 1Password (I don't use Keepass), so not sure what could be different for Keypass.. We're not doing anything special for the login fields.
