### ISSUE TITLE
Grav failed to open stream: No such file or directory in ...

### ISSUE THREAD

**Issue by LukasK1212** [getgrav/grav-plugin-admin#1687]
Hi, I installed Grav on the server. When I open the URL it reports this error: 

Warning: require(/data/web/virtuals/221661/virtual/www/vendor/composer/ClassLoader.php): failed to open stream: No such file or directory in /data/web/virtuals/221661/virtual/www/vendor/composer/autoload_real.php on line 12. 

Thank you for your help

Warning: require(/data/web/virtuals/221661/virtual/www/vendor/composer/ClassLoader.php): failed to open stream: No such file or directory in /data/web/virtuals/221661/virtual/www/vendor/composer/autoload_real.php on line 12

**Comment by rhukster** [comment]
Sounds like you installed via GitHub or something.  You probably need to do a:

```
composer install --no-dev
```

Alternatively, you can just download Grav package from getgrav.org and that will have all the vendor folders already in the zip.
