### ISSUE TITLE
hide_next_prev_page_buttons: true doesn't hide section buttons

### ISSUE THREAD

**Issue by m33m33** [getgrav/grav-plugin-admin#1688]
Hi,

On the main section page (type: sections), `the hide_next_prev_page_buttons: true`  attribute does not hide the next/prev buttons.

On leaf pages (type: section and subsections) the next/prev buttons is hidden.

It is a bit odd since "sections" pages shows prev/next buttons relating to other content.

Am I doing something wrong with this setting ? I want all next/prev buttons hidden for these pages

Regards
M33

**Comment by rhukster** [comment]
what is this `hide_next_prev_page_buttons` and where are you seeing it? I don't think it's an Admin issue, perhaps something with the theme you are using ???

**Comment by m33m33** [comment]
It may be an issue with the quark open publishing theme then ... I will look after it.

Thanks :)
