### ISSUE TITLE
Maximum function nesting level of '256' reached, aborting!

### ISSUE THREAD

**Issue by Penuhinfo19** [getgrav/grav-plugin-admin#1691]
When I want to add an item page on the parent page, I always get this error message "Maximum nesting level of '256' reached, aborting!" (the error: http://prntscr.com/nykufu). Which made me wonder, why when I reloaded the parent page, I found the error page I was referring to appeared, even though I didn't have the chance to click save before? Why? Can anyone help me or show me a solution to overcome it? Thanks.

**Comment by mahagr** [comment]
The error comes from xdebug which has too small limit for recursive calls. Please google your error and you'll find how to fix the issue.

**Comment by replayshot** [comment]
just to add a solution here without the need to google: in your php.ini (if you are in development), change  or add xdebug.max_nesting_level=500 or higher

One thing I also noticed is that if the article is too long and there is no summary specified, then it throws this error on blog listing page. Easy fix is to add a short summary.
