### ISSUE TITLE
No longer possible to add / move page expect /root

### ISSUE THREAD

**Issue by tschaban** [getgrav/grav-plugin-admin#1697]
Hi, after upgrade to 1.6.10 / Admin: 1.9.5
- adding or moving page can't be made outside of the /root folder

Basically, I can't make any longer more than 2 level tree structure of the site.

![just-root](https://user-images.githubusercontent.com/22762502/59548201-dc214d80-8f4b-11e9-8c8c-623ee0e89f1b.jpg)

**Comment by ConteZero** [comment]
I can confirm the problem after the update to grav 1.6.10 and Admin 1.9.5

**Comment by tschaban** [comment]
I've downgraded to 1.6.9 and admin plugin 1.9.4 and the problem persist.

**Comment by ConteZero** [comment]
I've found the problem, in Admin 1.9.5 a new default configuration has been added to admin.yaml:

parents_levels: "2"

If you change that value to something higher you'll have the previous behavior restored.
But there is no mention in the changelog about this change, I think that a simple note into the changelog would have been very useful.

**Comment by tschaban** [comment]
Thanks @ConteZero - indeed it restores the previous behaviour

**Comment by rhukster** [comment]
Could you guys possibly try grav 1.7 beta with admin 1.10 beta? We have created a new parent move field that used Ajax for better performance.

**Comment by rhukster** [comment]
BTW, I've also re-release Admin as 1.9.6 with this accidental `parents_levels: "2"` setting removed.  That was not intentional

**Comment by tschaban** [comment]
> Could you guys possibly try grav 1.7 beta with admin 1.10 beta? We have created a new parent move field that used Ajax for better performance.

Hi Andy, I've upgraded to 1.7. I quickly tested adding a new page and moving it to a different folder. All worked well - I do like new move functionality.

thanks!
