### ISSUE TITLE
Error selecting parent page

### ISSUE THREAD

**Issue by lufog** [getgrav/grav-plugin-admin#1699]
Grav v1.10.0-beta.1
Admin Panel v1.10.0-beta.1

![image](https://user-images.githubusercontent.com/10379487/59562478-02231c80-9036-11e9-9945-ee8eea991acb.png)

**Comment by rhukster** [comment]
Need more information on your setup.

**Comment by lufog** [comment]
@rhukster, checked it on a pure Grav beta-1 distribution (Core + Admin) and:
Operational system: Windows 10
Browsers: Opera, Chrome, Firefox
Server: Build-in PHP 7.3

The animation shows bugs #1699 and #1698
![ihSwSfJ9FW](https://user-images.githubusercontent.com/10379487/59657673-0ff9ae80-91aa-11e9-91e4-e27f507a6324.gif)

**Comment by w00fz** [comment]
Fixed with ⬆️

**Comment by lufog** [comment]
Nope, both problems (#1699, #1698) remained on Grav v1.7.0-beta.2 - Admin v1.10.0-beta.2
![mshVqshaqG](https://user-images.githubusercontent.com/10379487/59961175-ea87e000-94dc-11e9-974f-ef32381532b7.gif)

**Comment by lufog** [comment]
@w00fz, @rhukster ⬆️

**Comment by w00fz** [comment]
@lufog is your Grav on windows? The path in your gif has a forward slash and then a backslash which is odd

**Comment by lufog** [comment]
@w00fz, yes, is currently Grav working on Windows. I develop on Windows, and check the site in the built-in PHP server.

**Comment by rhukster** [comment]
Ok fixed in 1.10 branch.
