### ISSUE TITLE
Statistics graph shows 0 for all y-axis values

### ISSUE THREAD

**Issue by wilchak** [getgrav/grav-plugin-admin#1700]
Hi there,

Having an issue with the stats graph on the dashboard. Even though my site is getting hits, it just shows 0 for all values on the y-axis. Screenshot: 
<img width="898" alt="Screen Shot 2019-06-16 at 9 11 19 PM" src="https://user-images.githubusercontent.com/2185789/59572448-6fa56c00-907b-11e9-9454-79713e1499f4.png">

Grav v1.6.10 - Admin v1.9.6 
PHP 7.3.6
nginx 1.16

**Comment by rhukster** [comment]
This is fixed in 1.10 beta branch.  Just need to port that change back to 1.9

**Comment by wilchak** [comment]
Hi, I'm still having this issue in Firefox. The graph values are partially cut off. (Looks fine in Chrome.) Increasing the inline width to 10px (from 5px) fixes the issue, but uncertain if that is the best fix. Screenshots below:
Firefox: 
<img width="930" alt="firefox" src="https://user-images.githubusercontent.com/2185789/60024275-82183a80-9665-11e9-86f3-b36194c6ebc3.png">
Chrome: 
<img width="930" alt="chrome" src="https://user-images.githubusercontent.com/2185789/60024282-86445800-9665-11e9-96b8-38c1500e44a4.png">

**Comment by w00fz** [comment]
I am unable to reproduce this. Even though you are running a nightly build of Firefox and we don't really support that level of releases (maybe betas but nightly can break too easily), I went ahead and tried with Chrome, Firefox Stable and Firefox Nightly and the result are the same for me.

<img width="726" alt="Dashboard | Grav 2019-07-09 18-45-38" src="https://user-images.githubusercontent.com/11734/60934197-2f03d180-a27a-11e9-8243-f520e87d19fc.png">


Is this still an issue or was it a problem of the nightly? Can you also test with stable Firefox?

Thanks.

**Comment by wilchak** [comment]
Well... it does seem to be working correctly for me too now! Who knows. Thanks for following up.
