### ISSUE TITLE
Little CSS bug in the admin panel switching to italian language

### ISSUE THREAD

**Issue by microcluster** [getgrav/grav-plugin-admin#1702]
In the Administration panel > Dashboard > Profile there's a css error at permissions level as you can see from the image below that doesn't allow to read the content:

![admin_panel](https://user-images.githubusercontent.com/31942122/59714029-f3dd2800-9210-11e9-8660-f5c2835314ec.png)

The error is here:
/user/plugins/admin/themes/grav/scss/template/_forms.scss at line 342 where max-width should be adjust to **25rem**

**Comment by rhukster** [comment]
What version of admin are you on?

**Comment by rhukster** [comment]
Fixed in develop
