### ISSUE TITLE
after update admin login returns 404 page not exist

### ISSUE THREAD

**Issue by x11r1** [getgrav/grav-plugin-admin#1708]
after most recent grav update (26 June 2019) admin login returns just this:

Error 404
Woops. Looks like this page doesn't exist.

all site pages are still there, everything seems on with the website

i tried to fix by installing a fresh copy in another folder and copied the entire old "users" folder to get back all my plugins and pages - the same problem came back - cant login to /admin

it seems quite strange as instead of the site showing the admin panel, it shows the website menu and within the content area it shows

"
Error 404

Woops. Looks like this page doesn't exist."

the problem persist even after i deleted all files in "/mysitel.com/public_html/grav/cache"

![admin login error](https://user-images.githubusercontent.com/35359642/60255207-82c8ff00-98f9-11e9-86b0-c363b5b96e2e.png)

**Comment by james1990** [comment]
Getting the same thing...No fixes currently

**Comment by x11r1** [comment]
thanks. i solved it by fresh install and overwriting all plugins and pages.. sort of worked, most things preserved

from now on i guess i will never press the update button.. terrible...

**Comment by rhukster** [comment]
need more information on your setup.  Did you have a custom `.htaccess` file?

**Comment by x11r1** [comment]
no, i did not use a custom .htaccess file (i left the default one from Grav as it was)

**Comment by rhukster** [comment]
Must have been a weird bad-update... not sure how to recreate this, but we already have plans to improve the reliability of update process in admin.
