### ISSUE TITLE
Blueprint Field Type List Limit

### ISSUE THREAD

**Issue by localnetwork** [getgrav/grav-plugin-admin#1710]
Is there a way to limit list items?

Example: I want to add groups, but this can only be limit to 3

- Group 1
- Group 2
- Group 3

Related issue here: https://discourse.getgrav.org/t/list-limit/2689

Thanks

**Comment by thejame** [comment]
Along these lines, can a `type: pages` be filtered to not show every single page? `show_all: false` doesn't seem to help.

**Comment by localnetwork** [comment]
Hi @thejame ,

Thanks for your reply. Actually, i just want the users to prevent from adding once exceed to the limit of 3. An can add if it's below 3. See screenshot.
![field-type-list](https://user-images.githubusercontent.com/15809239/60660625-b91ef500-9e8a-11e9-90bb-73239b204acb.jpg)


Thank you.
