### ISSUE TITLE
Newbie Q: How to get the image url from custom image field

### ISSUE THREAD

**Issue by localnetwork** [getgrav/grav-plugin-admin#1714]
Hi, I have a custom image field and i want to get the url in twig.

test.yaml

header.slider:
                  type: file
                  label: Slider 
                  type: file
                  destination: '@self'
                  description: Only .png, .jpg, .jpeg file types are allowed.
                  multiple: true
                  style: vertical
                  accept:
                    - .png
                    - .jpg
                    - .jpeg
                  ordering@: 2

----------------

test.html.twig

{% extends 'partials/base.html.twig' %}

{% block content %} 
{% for slide in page.header.slider.images %}
    `<img src="{{ slide.url }}"> `
{% endfor %}
{% endblock %}

**Comment by localnetwork** [comment]
'<img src="{{ url(slide) }}"> '

**Comment by localnetwork** [comment]
`<img src="{{ url(slide) }}"> `

**Comment by localnetwork** [comment]
i also tried {% for slide in page.header.slider %} and still not able to get the url

**Comment by sojimaxi** [comment]
@localnetwork you use `{{ slide.url }}` it's that simple. or better still generate your tag usig `{{ slide.html('','','class_names') }}` to get the img html tag together with the src link. 

NB: I would be better to use the discussion channels instead of github issue for qustions

**Comment by localnetwork** [comment]
Hi @localnetwork , tried that but still no luck. Closing this issue and will post this on discourse.
