### ISSUE TITLE
Page Preview not working, wrong url, admin 1.10.0-beta.4

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#1715]
Going to your pages overview, clicking on page preview --> whoops page does not exist.
Preview url appends **/fi** to your url...so it can't work.

**Comment by rhukster** [comment]
Hardcoded `fi` language @mahagr ?

**Comment by mahagr** [comment]
Likely, I'll check it.

**Comment by axel-rank** [comment]
Working again.
