### ISSUE TITLE
Update fails 1.4.5 to 1.6.11

### ISSUE THREAD

**Issue by pixmin** [getgrav/grav-plugin-admin#1716]
I logged in the admin, got a message to update Grav, clicked the button, and got this error:

`Too few arguments to function Grav\Common\Processors\DebuggerAssetsProcessor::process(), 0 passed in [...]system/src/Grav/Common/Grav.php on line 132 and exactly 2 expected`

**Comment by pixmin** [comment]
If I refresh, it shows that it is at version 1.6.11 and there are no update, so maybe it managed to update itself successfully?

**Comment by mahagr** [comment]
Yes, the upgrade succeeds, but there is an error because of Grav continues to load itself after the classes have been changed. This has been fixed, so in the future upgrades shouldn't have issues with files changing in mid-request.
