### ISSUE TITLE
Incorrect layout of Installed Plugins page

### ISSUE THREAD

**Issue by MarcinOrlowski** [getgrav/grav-plugin-admin#1717]
Incorrect layout of Installed Plugins page - "right side of list elements is missaligned as shown on the attached screenshot (using Quark 2.0.1 if that matters)

![screenshot](https://user-images.githubusercontent.com/8041294/60955649-90bb4e80-a301-11e9-9d51-f246a8dbdba1.png)

**Comment by rhukster** [comment]
Fixed in 1.10 beta branch
