### ISSUE TITLE
Frontmatter lists removed images

### ISSUE THREAD

**Issue by MarcinOrlowski** [getgrav/grav-plugin-admin#1718]
I edited the page, added `pic.jpg` image to it, linked image in the page body. Saved. Edited again, removed image, edited body to remove image reference. Saved. Edited again. clicked "Expert" and I still see:

    media_order: 'pic.jpg'

**Comment by rhukster** [comment]
media_order is only updated when you save with media, and is only used when there is media.  Add another image, and save, and that should be reset.
