### ISSUE TITLE
Unable to update plugins

### ISSUE THREAD

**Issue by prinla** [getgrav/grav-plugin-admin#1719]
![sail4fun-problem](https://user-images.githubusercontent.com/16805582/61050540-86738000-a3e7-11e9-8c7f-0d7c34be552b.JPG)

I have 3 plugins that need to be updated but I have the same error on all three of them - see picture.

Can you help please?

Grav v1.6.11 - Admin v1.9.7

**Comment by prinla** [comment]
Changing from Remote fetch from "auto" to FOPEN solved the problem

**Comment by MakaryGo** [comment]
FYI, exact same thing happened to me
Grav v1.7.0-rc.1 - Admin v1.10.0-rc.1

Changing the above setting fixed the issue, but it took me some time to debug it...
