### ISSUE TITLE
Orderindex of Pages not working on Server (Grav v1.6.11)

### ISSUE THREAD

**Issue by IMGSaibh** [getgrav/grav-plugin-admin#1724]
On XAMPP Localhost the Ordering of Pages working fine. Pages are Rendered according the order set in Dashboard. When pushing it to Server (Manitu) Pageindex stop working. The Order seems to be completely random.

We used linked pages
Filestructure:

- Home ->modular.md

- Projekts -> default.md
-- Projekt1 -> text.md
-- Projekt -> text.md

- Imprint

**Comment by rhukster** [comment]
What does your collection ordering by? Look in the filesystem, are you manually ordering, and if so are the folder numeric prefixes correct?
