### ISSUE TITLE
Parse Error Cache file after admin modification

### ISSUE THREAD

**Issue by LabInc-Nico** [getgrav/grav-plugin-admin#1730]
Hi,

I get this error after modification in admin (for exemple Admin -> site -> modify description -> save) :
```
 ParseError syntax error, unexpected '.isso.rep'
Stack frames (67)
/cache/compiled/blueprints/file.php
```
The file can be different but always in the cache folder.

I have to add a new line at the end of the file specified (or delete the file).

```
bin/gpm version 
You are running Grav v1.6.11
```

Thanks.

**Comment by rhukster** [comment]
Does that .isso.rep look familiar? Where is that betting set?

**Comment by LabInc-Nico** [comment]
I think is part of jscomment pluggin but the file or the error is not always the same. 

To reproduce with a fresh install (just extract the last zip) :
I only change the lang to Fr (system -> langue -> add fr)
And when i try to update the plugin :
```
Parse error: syntax error, unexpected '' => true' (T_ENCAPSED_AND_WHITESPACE) in /home/code/testgrav/cache/compiled/files/eb49e85d2eafe1cdc1c0b0c595811423.yaml.php on line 196
```

**Comment by rhukster** [comment]
What happens when this plugin is disabled?

**Comment by LabInc-Nico** [comment]
After disabling this plugin (or another one) I got the same error.
I can also reproduce this type of problem when i change another option (like language)  : 
```
Parse error: syntax error, unexpected ']', expecting end of file in /home/vagrant/code/labinc/cache/compiled/config/master-labinc.local.php on line 1466
```
or with a new installation without adding additional plugin.
The way to fix is ​​always the same: I add a blank line to the end of the cache file indicated in the error.
But the error appears with every modification of the configuration

**Comment by rhukster** [comment]
I really dont' know what this can be.  It's definitely not a common issue as I've never seen this before.  That generally means its something very specific to your setup.  As you seem to be running in a vagrant container, it's probably something related to that.  Can you try just running on the local machine without vagrant?

**Comment by LabInc-Nico** [comment]
Well seen! Actually outside Vagrant (homestead more precisely) I do not meet these errors anymore ...

**Comment by mahagr** [comment]
To me, this issue looks like old PHP version being somehow used as those errors come from cached YAML files, which are stored as PHP files.
