### ISSUE TITLE
Make markdown filter page-context aware

### ISSUE THREAD

**Issue by stephan-strate** [getgrav/grav-plugin-admin#1731]
We just discovered, that inserting media from page media to the codemirror editor does not work correctly in modular pages.

```
01.mypage
  -> _somemodular
02.otherpage
```

You can upload media to the modulars page media. That will be placed into `_somemodular` in this case. When linking it to the editor, only the relativ filename will be linked.

![chrome-capture (1)](https://user-images.githubusercontent.com/19595615/62517705-39d56600-b828-11e9-9a37-75ae468dae31.gif)

But what is really needed is the relativ path starting from the parent page, so in this case `_somemodular/instagram_button.png`, because the modular will be rendered in context of the parent standalone page.

**Comment by rhukster** [comment]
It’s correct.  Modular content is pre-rendered with its own twig template before being added to the parent page’s content.

**Comment by stephan-strate** [comment]
But linking is absolute. That means this links will be dead!

**Comment by rhukster** [comment]
Grav handles all the things :)

https://learn.getgrav.org/16/content/image-linking

**Comment by stephan-strate** [comment]
Ok, got it. It does work with the default content editor.
But when adding another editor and rendering it with `{{ header.customcontent|markdown }}`, it does not work. Is there a way to get it working with other than the default editor?

**Comment by rhukster** [comment]
That’s because the twig markdown filter is not as powerful as the regular markdown process. For example it doesn’t have any page context so it doesn’t know what page you are on.

**Comment by rhukster** [comment]
Actually I just thought of a way to make it optionally context aware. Not able to look  at this now but maybe next week.

**Comment by rhukster** [comment]
Actually I just thought of a way to make it optionally context aware. Not able to look  at this now but maybe next week.

**Comment by rhukster** [comment]
Actually looks like it's already using the current page as the context: https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Utils.php#L1535

**Comment by rhukster** [comment]
Ok, this will always use the global page object, which won't be correct for modular.. have a solution though.

**Comment by rhukster** [comment]
https://github.com/getgrav/grav/commit/618a59921a1c4b54fdcf22ccffbc11aace912701

**Comment by mahagr** [comment]
This fix caused some regression: https://github.com/getgrav/grav/issues/2635
