### ISSUE TITLE
private plugin login

### ISSUE THREAD

**Issue by id027102** [getgrav/grav-plugin-admin#1735]
With 2 users  and 2 passwords , it seems of each user can login with even which password
So user2 can login with password1 and password2 , user1 too with password1 and password2
Or am I missinf something ?
users:
# comment
user1 : password1
user2 : password2

**Comment by rhukster** [comment]
Is this an admin question? or is this about the private plugin? if private, that's a 3rd party plugin and we recommend simply using Grav's official 'login' plugin.
