### ISSUE TITLE
Mp4 and Webm upload hang in admin panel 1.9.8

### ISSUE THREAD

**Issue by hotdoy** [getgrav/grav-plugin-admin#1737]
Tested it on 2 different install with 1.9.8.
Then tested on a pre update one (can't remember the version ,1 or 2 behind).
Uploaded just fine, then I did the 1.9.8 update and same problem.

No problem uploading images.(tested jpg and png).
I did not try other video formats.

Windows 10
Chrome Version 76.0.3809.100

![image-397745290759522](https://user-images.githubusercontent.com/11572524/63224682-b277e300-c195-11e9-8fc6-8dc300851905.jpg)

The media never loads. It's just stays like that. No error, nothing in the console.
No blue checkbox or loading animation. Saving the page is just fine but of course the video do not save. Warning on page leave also does not trigger if page is not saved.

**Comment by mattandwhatnot** [comment]
I am seeing this same behavior on any file that is not a jpeg or png. All data file types (.pdf, .csv, .xlsx, even .md) fail in the same way.
Began right after I updated to Grav v1.6.14 and Admin v1.9.8


Browser Chrome Version 70.0.3538.77 (Official Build) (64-bit)
OS Ubuntu 19.04

**Comment by rhukster** [comment]
@mattandwhatnot do you remember what versions of Grav + Admin you were on before?

**Comment by mattandwhatnot** [comment]
Grav v1.6.14 and Admin 1.9.7

**Comment by mattandwhatnot** [comment]
updated Grav to v1.6.15 today. Problem remains

**Comment by hotdoy** [comment]
Same.

**Comment by rhukster** [comment]
We're investigating

**Comment by matthewbecker1990** [comment]
I am having this exact same issue on admin v1.9.12.

Images dragged into the media field trigger a POST event. All other file types do not.

https://discourse.getgrav.org/t/page-media-only-accepts-images/11544/6
