### ISSUE TITLE
onAdminData event don't have post data.

### ISSUE THREAD

**Issue by mhlsf** [getgrav/grav-plugin-admin#1740]
onAdminData is an event that is fire in admin.php in the data() method. It is means to check if the data are plugin related but it doesn't pass along the post data.

`$event = $this->grav->fireEvent('onAdminData', new Event(['type' => &$type]));`

Is it normal behaviour ? How should I access the post data from my plugin by listening to this event ?

**Comment by rhukster** [comment]
let me invesitgate this a little, i know i'm using it, just need to remember where and how.

**Comment by mhlsf** [comment]
Found the solution for this

You should access the data via the admin controller that can be reach by listening to the the event onAdminControllerInit.


```
public function onAdminControllerInit($e) {
    $controller = $e['controller'];
    $this->adminController = $controller;
}
```


Then in onAdminData you should be able to do something like this : 

`$this->adminController->data;`
