### ISSUE TITLE
Unable to minize admin sidebar

### ISSUE THREAD

**Issue by jwillp** [getgrav/grav-plugin-admin#1745]
I client of mine reported that they are unable to minimize the sidebar in Chrome with a specific display:
- Screen size: 12.3-inch display with a 235ppi density (Google Pixelbok) 

They reported that when they change the zoom of the page to be smaller e.g. 75% it does work, but when they are on 100% it simply does not work.

Has anybody else experienced this?

**Comment by rhukster** [comment]
A screenshot might be helpful to get an idea of the actual window width that is causing the issue.  I've not seen or heard of any issues like this before.
