### ISSUE TITLE
Update to v1.7.0-6 failed with message: Undefined index: grav-update

### ISSUE THREAD

**Issue by nscomputing** [getgrav/grav-plugin-admin#1746]
Running v1.7.0-beta.5 and trying to update to Grav v1.7.0-beta.6. 

In both cases , the web admin and bin/gpm update failed.

In web admin with the message : **Undefined index: grav-update**
With bin/gpm: **In Response.php line 316: Error while trying to download (code: ):**

**Comment by mcgonigle-dev** [comment]
I am also getting the same error with upgrading 'v1.7.0-beta.5'  to 'v1.7.0-beta.7'.

**Comment by rhukster** [comment]
can you guys try clearing your cache/checking for updates again? Everything 'looks' OK on the GPM and GitHub side.

**Comment by rhukster** [comment]
BTW, I just tested a b5 to b7 upgrade in admin and it was fine.

**Comment by nscomputing** [comment]
Thanks for prompt reply. After clearing cache (In Admin Clear Cache - All Cache) everything was OK. Upgraded to Grav v1.7.0-beta.7  and Admin to v1.10.0-beta.7 .
Hint: What about including Cache clearing in Upgrade process?
