### ISSUE TITLE
Page Status doesn't update until browser cache cleared

### ISSUE THREAD

**Issue by blizam** [getgrav/grav-plugin-admin#1750]
If you change a page's status... either from published to unpublished, visible to non-visible, or routable to non-routable, that status is not reflected on the main Pages list (ie: the circle is red even though it's published) until you clear your browser cache... you can come back 3 days later and it'll still incorrect

**Comment by GogoAkira** [comment]
Can confirm similar or same.  Grav v1.6.16 - Admin v1.9.10 on localhost local machine

Added new page, changed root folder, also changed external to default etc, the page showed up at fist was visible, then the page was there on the menu but content said this page is non existent.  disabled and enabled again it didn't work, also it was still visible while saying it's invisible.  deleted page, added new page, works good.  still great program :) , thanks, will keep

**Comment by mahagr** [comment]
@blizam Can you try if Flex pages in admin fixes this issue?

**Comment by GogoAkira** [comment]
idk if you can tell i'm a newbie , I just got grav today on my server :) ..I'm being more careful now, it was probably user error on my part, regarding publishing, not having that issue anymore.

I couldn't find a plugin called flex, sooo... :)

**Comment by blizam** [comment]
@mahagr  Is that available in the current stable release of the admin plugin? Enabled by default? In any case, I upgraded to v1.9.10 and the issue appears to be resolved.

**Comment by mahagr** [comment]
Flex is not enabled by default, so looks like I accidentally fixed that one, too. :) But yeah, I've been fixing some page bugs as well when I've seen those.
