### ISSUE TITLE
Grav tries to update the admin plugin to 1.10.0-beta.8

### ISSUE THREAD

**Issue by lucaswillering** [getgrav/grav-plugin-admin#1753]
Hi, I've updated to Grav 1.6.16 and it says there is also an update of the admin plugin, but it wants to update it to version 1.10.0-beta.8 instead of 1.9.10. In the system settings I have GPM releases set to Stable. 

(Not sure if this should be reported here or in the main Grav repo)

**Comment by paulhibbitts** [comment]
I am seeing this too

**Comment by glasswork** [comment]
Here as well.

**Comment by rhukster** [comment]
Try forcing a fresh GPM "check for updates", this issue was user error on my part not setting the beta release as "pre-release" in GitHub.

**Comment by lucaswillering** [comment]
Thanks! That worked.

**Comment by paulhibbitts** [comment]
Thanks very much @rhukster, the update now works a-ok!

**Comment by glasswork** [comment]
Yep, that did the trick.

**Comment by romannl** [comment]
I had errors, admin folder was wiped out, had to uninstall admin package and now when executing bin/gpm install admin
I get this:

  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...
In Folder.php line 321:
                 
  Unknown error

**Comment by rhukster** [comment]
No need to hijack the thread @romannl, you know full well that is the same issue you have been seeing on your windows installation.  We still don't know why you are having a problem with that delete method in the Folder.php class and no one else does...Let's keep it a separate issue though.

**Comment by romannl** [comment]
@rhukster  I installed grav-admin bundle, a couple of days ago and didn't see any errors.. I thought the message was related to the issue with 1.10-beta, nice to know it only happens in Windows.
