### ISSUE TITLE
RuntimeError proc_open

### ISSUE THREAD

**Issue by TorbjornN** [getgrav/grav-plugin-admin#1756]
Just updated everything in Grav today. Site works fine. But clicking "Scheduler" in Admin menu Tools I get this error :

_Twig \ Error \ RuntimeError
An exception has been thrown during the rendering of a template ("The Process class relies on proc_open, which is not available on your PHP installation.")._

I have PHP 7.3.9  What more info is needed ?

**Comment by rhukster** [comment]
The message is telling you what the issue is:

The Process class relies on proc_open, which is not available on your PHP installation."

Your host probably has it listed in the disabled functions in php.ini

Might want to try contacting your hosting provider.

**Comment by TorbjornN** [comment]
Thanks. 
I'll check if proc_open is available in my hosting providers PHP.
