### ISSUE TITLE
1.10.0-beta.9 Mystery green lines on Plugin and Themes sidebar buttons (collapsed)

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#1757]
I've just noticed on the 1.10.0-beta.9 Admin beta two green lines that seem to appear on the Plugin and Themes sidebar buttons after an update check, here is a short video:

![2019-10-01_09-02-56 (1)](https://user-images.githubusercontent.com/1812771/65979786-c2d4dc00-e42a-11e9-80dd-63ee491aa7c9.gif)

For reference, here is the same behavior on Stable - no lines appear:
![2019-10-01_09-02-16 (1)](https://user-images.githubusercontent.com/1812771/65979864-eef05d00-e42a-11e9-84ad-1c88ef0cf621.gif)

Please let me know if any more info is helpful etc.

Thanks,
Paul

**Comment by w00fz** [comment]
Is this still an issue for you @paulhibbitts ? I tried with Safari and cannot reproduce. I am certain the mysterious line was nothing but some artifact left from the updates counter badge. Something probably Safari related that now is resolved.

This is how it looks for me now on Safari where I purposely have Plugins with badges and Themes without:

<img width="228" alt="Dashboard | Grav 2020-11-21 16-18-24" src="https://user-images.githubusercontent.com/11734/99890533-33355280-2c15-11eb-9093-8bb7a4f92600.png">

**Comment by paulhibbitts** [comment]
Thanks for looking into this @w00fz . I moved to FireFox for my local testing some while ago... just re-tested with more recent RC and I know longer see this issue so it looks like it can be closed.
