### ISSUE TITLE
Admin UI console does not show full configuration

### ISSUE THREAD

**Issue by moremeatlessfat** [getgrav/grav-plugin-admin#1758]
Hi,

The options in the user/config/site.yaml file does not match the same number of options shown in the Configuration -> Site page in the Admin Tool.

How would I be able to modify those settings without going into the .yaml file itself?  It seems to cut off at Redirect & Routes.

![Admin UI](https://user-images.githubusercontent.com/8219962/66019417-b03fcd00-e526-11e9-9f57-de349e694830.png)

![Ymal file](https://user-images.githubusercontent.com/8219962/66019434-c3eb3380-e526-11e9-8111-c4b7b4029dbf.png)

Thanks,
Sharlene

**Comment by rhukster** [comment]
Just looks like the extra things in `site.yaml` (header/footer/copyright/social) are not defined in the site blueprint. (`user/blueprints/config/site.yaml`).  Is this a theme you are developing, one that was developed for you, or a theme/skeleton?

**Comment by moremeatlessfat** [comment]
Thanks, @rhukster , I am using the antimatter theme.  Ohhh, so, I need to add the extra attributes into blueprint/config/site.yaml and then it'll show up in the UI?
