### ISSUE TITLE
Exception error in grav-plugin-admin / possibly created by highlights module in Quark One-Page Theme

### ISSUE THREAD

**Issue by mkacfr** [getgrav/grav-plugin-admin#1759]
Exception error - possibly created by highlights module in Quark One-Page Theme

Please go and see the issue made in Quark's repo :
https://github.com/getgrav/grav-theme-quark/issues/131

2 videos and the error file : https://drive.google.com/drive/folders/1fOhDL8IgSkH-1vYD1EzfT4JS1lcYva7r

- video 1 - error when changes are made via ADMIN
- video 2 - no error when changes are made via FTP

so... I think the problem is more about grav-plugin-admin than quark one-page theme...

---

Take Care
_Michael_

**Comment by rhukster** [comment]
I can't replicate this in my demo install of "one page" skeleton.  The error about the `modular/features.html.twig` missing just tells me you are missing that file in the `user/themes/quark/templates` folder.
