### ISSUE TITLE
Unable to edit modular content

### ISSUE THREAD

**Issue by attiks** [getgrav/grav-plugin-admin#176]
I can edit all pages, including a modular page, but I'm unable to edit a subpage, I get the following error: ``` The requested resource /en/admin/pages/wagenpark/_01.intro was not found on this server. ```

The URI to edit the modular page is ``` en/admin/pages/wagenpark ```

**Comment by rhukster** [comment]
I am unable to replicate this. I am able to create modular suppages and edit them, even in a multilanguage specific site.. Perhaps some more details on how you setup this page would help?

Also perhaps you can send a URL to a ZIP of your site so we can try to recreate this locally?

**Comment by flaviocopes** [comment]
Cannot replicate it too

**Comment by attiks** [comment]
I'll try to setup a minimal site, to see if I can replicate my self.

**Comment by rhukster** [comment]
Did you ever find a way to replicate this one?

**Comment by attiks** [comment]
Didn't find the time, will try during the weekend

**Comment by attiks** [comment]
Found it, if you name a modular page like *_1.footer* it doesn't work anymore

**Comment by flaviocopes** [comment]
Seems to work fine for me..  e.g. 06.modular/_1.showcase/showcase.md

**Comment by attiks** [comment]
Running on *php -S localhost:9999* or on a real server?

**Comment by flaviocopes** [comment]
PHP built-in server is not supported http://learn.getgrav.org/basics/installation#phps-built-in-web-server, might be the cause of the issue?

**Comment by attiks** [comment]
@flaviocopes i know, but our themer uses it during development, might has problems with the URI

**Comment by attiks** [comment]
Thanks for the feedback

**Comment by flaviocopes** [comment]
It's unsupported because of some lacking features in the PHP built-in server itself that cause problems with the current codebase, not because we do not want to support it :)

**Comment by attiks** [comment]
I know, not blaming you ;-) Our themer has a workaround, so he's happy again.

**Comment by flaviocopes** [comment]
:+1: just post here if it happens also with another web server
