### ISSUE TITLE
[Bug] Deleting content from fields within the user object aren't reflected to account's yaml

### ISSUE THREAD

**Issue by jgonyea** [getgrav/grav-plugin-admin#1762]
To reproduce:

* Setup clean Grav site and install admin w/ dependencies
* Login to admin and create new user USERNAME
* Navigate to /admin/user/USERNAME
* Remove all text from any field (tried title and groups) and click Save
* Logout
* Login and navigate to /admin/user/USERNAME

Expected result:
Changes made above were actually saved

Actual result:
Even though on initial save, data seems to be cleared out of the fields, examining the account yaml will show that the fields are still filled in.  Subsequent logout/logins will repopulate the admin form with that data.

Largest Security Implication:
Fields can't be cleared, which means that things like group membership (a selectize field) can't be fully removed from a user.

**Comment by rhukster** [comment]
I can reproduce this.

**Comment by jgonyea** [comment]
Anecdotally, it seems that a field that's blank isn't passed to the event object, and therefore the user update functions don't know to change anything.  This is good in the case of the password (you wouldn't want a blank password field changing the password accidentally), but this breaks the expectation for other fields.

**Comment by mahagr** [comment]
This one should be fixed in the upcoming Grav 1.6.20
