### ISSUE TITLE
Set custom_admin_logo?

### ISSUE THREAD

**Issue by henk23** [getgrav/grav-plugin-admin#1764]
In the file`user/plugins/admin/themes/grav/templates/partials/logo.html.twig` there is a variable `custom_admin_logo`. How is it possible to set this variable?

If it was `config.plugins.admin.custom_admin_logo`, I would be able to set it in the config file.

Also, there seems to be no other mention of that variable in the whole of Grav.

**Comment by rhukster** [comment]
Actually it's a twig variable.  It is there because we originally had plans to release 'admin pro' and it set this twig variable based on an image path you could provide.  Unfortunately this never really got finished and we didn't release it.
