### ISSUE TITLE
Tools -> Logs: Log field could benefit with some dynamic way of populating the dropdown

### ISSUE THREAD

**Issue by w00fz** [getgrav/grav-plugin-admin#1765]

**Comment by rhukster** [comment]
Ok, dug in, we already added a  config field in admin to set the visible log viewer file names.

**Comment by w00fz** [comment]
The config field is there but isn’t it static? The idea with the issue was to allow 3rd party plugins like rsync to register themselves so they can appear in the dropdown.
As far as I can tell right now the only way is by either having the user adding the entry manually or for the developers to edit and save  that admin config field through the plugin itself (config.set, config.save).

Is there actually a way of doing this dynamically?
