### ISSUE TITLE
Use of multiple colour Page Editor button, esp. Red

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#1768]
I know a PR was requested, but I cannot figure out how to make the below change via code.

Recently I've noticed that when editing Pages there are now up to four colors in the top-right Page Editor button row:

![2019-10-21_11-15-18](https://user-images.githubusercontent.com/1812771/67235909-ed4c0080-f3fc-11e9-8edf-fd422d7ec9e6.png)

While the color choice of red for the "Delete" button is to serve as a warning, it actually seems to draw even more attention to itself as is a distraction and fights for attention with the primary action button in purple.

Perhaps one alternative is to keep the "Delete" button the standard color, but change both the color and label (from the more generic "Continue") of the resulting confirmation dialog:

![2019-10-21_11-18-14](https://user-images.githubusercontent.com/1812771/67236492-35b7ee00-f3fe-11e9-9273-6d9095054b40.png)

![2019-10-21_11-29-52](https://user-images.githubusercontent.com/1812771/67236182-a14d8b80-f3fd-11e9-86a5-f5baea96ac43.png)

I look forward to hearing feedback on this proposal.
Paul

**Comment by OleVik** [comment]
I second the highlighted issue above: Marking the Delete-button as red initially indicates interaction - of the focus, hover, or active variety - which has not yet occurred. The warning of completing the action should be highlighted when the interaction is performed, and confirmation asked for in the modal. Warning the user beforehand is superfluous, and not expected by the user.

**Comment by rhukster** [comment]
merged
