### ISSUE TITLE
Call to undefined method Grav\Common\User\User::authorize() 

### ISSUE THREAD

**Issue by katosdev** [getgrav/grav-plugin-admin#177]
Trying to install the admin panel and getting an error:

 Whoops \ Exception \ ErrorException (E_ERROR)
Call to undefined method Grav\Common\User\User::authorize() 

The error : http://puu.sh/kcDWd/45e6e56db9.png

I am running PHP Version 5.6.3

The full call stack that I am receiving: http://puu.sh/kcDYo/b95164b5c2.png

Hope someone can help, I am really rather confused with this!

**Comment by rhukster** [comment]
You need to upgrade Grav to the latest version.

**Comment by katosdev** [comment]
Upgrade Grav? I have only just cloned it from Github?! 
(sorry, I should have mentioned that)

**Comment by rhukster** [comment]
How did you clone it? The 'develop' branch has a file: `system/src/Grav/Common/User/User.php`, it should have at line 119 a function called `authorize()`.  This was renamed from `authorise()` but below on line 136 is a backwards compatible method.  

You would definitely see this error if you were not running the latest release version of Grav (0.9.42), or the GitHub version.  So please check your version as displayed in `system/defines.php` or the `CHANGELOG.md`

**Comment by rhukster** [comment]
Oops, didn't mean to close that on you :)

**Comment by katosdev** [comment]
http://puu.sh/kcEvV/4605fcac40.png

Solved, superb - thanks for your amazingly quick support. Thank you very much! 
Thank you, thank you, thank you! I was getting very confused ;(
