### ISSUE TITLE
Add a form to preview page

### ISSUE THREAD

**Issue by anisiearadis** [getgrav/grav-plugin-admin#1771]
Hey!

I would like to add a form to the preview page of this plugin. I was able to override the Twig template by creating `myplugin/admin/themes/grav/templates/preview.html.twig` and added the following HTML inside the `content_wrapper` block:

```
<form action="{{ (uri.path)|e }}" method="post">
    <label for="note">
        Note
        <input id="note" name="note" type="text">
    </label>
    <button class="button" type="submit" name="task" value="preview.note">Submit</button>
</form>
```
This works pretty good so far. Now I'm stuck where I have to define the form inside my plugin. I started to create a file at `myplugin/admin/pages/admin/preview.md` to notify Grav to override that page.

```
---
title: My Preview Page

forms:
  note:

    fields:
        note:
          type: text
          id: field
          placeholder: Field
          label: Field
---
```

In my plugin's PHP file I have something like that:

```
<?php

...

class MyPlugin extends Plugin
{
    public static function getSubscribedEvents(): array
    {
        return [
            ...
            'onFormProcessed' => ['onFormProcessed', 0],
        ];
    }

    public function onFormProcessed(Event $event)
    {
        $form = $event['form'];
        $action = $event['action'];
        $params = $event['params'];

        dump($form);
        dump($action);
        dump($params);
        exit;
    }
}
```

If I enter something into the text field and submit the form I just get redirected to the preview page and nothing else happens. I expected to see some debug output. Can anyone tell me where I did a mistake?

I'm really sorry, if that isn't the right channel to ask questions like that. And I'm really thankful for every hint I get.

**Comment by rhukster** [comment]
The admin does not support page-defined forms as the frontend does.  Not that I've ever tried adding a form to preview (not sure what it would need to do), but you would need to pass a hidden attribute called `task` with value `save`.  Then listen to the event `onAdminSave()` event and do something in that event.

**Comment by mahagr** [comment]
However, upcoming Flex Objects plugin does support preview in admin, though in quite limited way right now.
