### ISSUE TITLE
Newly created user cannot login on localhost

### ISSUE THREAD

**Issue by alljamin** [getgrav/grav-plugin-admin#1772]
When I create a user with `bin/plugin login newuser` it successfully creates a yaml file, but when I try to login with the exact same details I will get

> Login failed ...

I have noticed that the newly generated user password gets hashed even though the [docs](https://learn.getgrav.org/16/admin-panel/introduction#usage) say that plaintext password gets hashed only on login.

Example of generated yaml:

```yaml
state: enabled
email: bob@email.com
access:
  site:
    login: true
fullname: 'Bob Johnson'
title: CEO
hashed_password: ***
```

I am running MAMP 5.5 on macOS Catalina with PHP 7.3.8 installed via brew.

UPDATE:
```yaml
state: enabled
email: bob@email.com
access:
  admin:
    login: true
  site:
    login: true
fullname: 'Bob Johnson'
title: CEO
hashed_password: ***
```
This allows the user to login. But now I do not understand what does "site access" mean. In [docs](https://learn.getgrav.org/16/admin-panel/faq#adding-and-managing-users) it is said that site role is the following:

> Gives user access to all pages in the front end. This is the equivalent of a logged-in user.

Is this equivalent to the user who can edit content on the page? Does this user have a separate default URL to login? Where should this user be logging in?

**Comment by rhukster** [comment]
Under the `access:` settings there are 2 sets of permissions.. `admin:` for admin side, and `site:` for frontend side.

You simply have `login:true` for each.  When you **just** had `site: login: true` you didn't have permission to even log into the admin, so you were logging in, your password was hashed, then your permissions were examined, and found you didn't have proper permission, so the system reported your login attempt failed.

When you added the `admin: login: true`, you were able to login successfully, but you had no permissions to do anything.

The best thing for your primary use is to give the `super: true` permission, this makes them a super-user:

```
admin:
    login: true
    super: true
```

All this is documented here: https://learn.getgrav.org/16/admin-panel/faq#adding-and-managing-users

**Comment by alljamin** [comment]
Thank you for your prompt response!
I do not think I quite understand the concept of having access to "frontend side". How the user with "Site" access supposed login? And, more importantly, where (URL) will he be logging in?

**Comment by rhukster** [comment]
This info I think is covered in quite some depth in the docs.

**Comment by alljamin** [comment]
Not to argue or anything, but I do not think that there is any mention how and where the user with "Site" access is supposed to login. The only mention of "Site" role is in this table:
<img width="1307" alt="Screen Shot 2019-10-29 at 9 16 00 am" src="https://user-images.githubusercontent.com/10956179/67723728-c3ae5d00-fa2c-11e9-8c98-e634e370f6fe.png">

Hence I am wondering where the user with "Site" access supposed to login? What will be the use-case of using such role?

**Comment by rhukster** [comment]
It allows you to create a membership type set up on a site.  Letting people register or login via oauth providers etc.  Then they can access things via their logged-in account that a guest would not have access to.

**Comment by alljamin** [comment]
Thank you for your clarification! Perhaps adding what you have just wrote to the docs will help out other new Grav users.

**Comment by coolemur** [comment]
Hello

I have kind of same'ish problem.

Newly created user cannot login into admin panel.

The odd thing is: when I replace ONLY /accounts/user.yaml file in this project with yaml file from another grav project - it works fine 

But yaml files are identical only user email, fullname and hashed_password differs.

New user was created using:

```bin/plugin login newuser --user myuser --password mypassword --email myemail@myemail.com --permissions b --fullname myname --title Admin```

Perhaps this might help you with reproducing the issue

And my question is: has anyone tried to create new user with "b" permissions (Admin and Site) and login into latest version of grav ? Can anyone confirm if it's working please ?

**Comment by coolemur** [comment]
@rhukster 

Just tested another case:

Replaced ONLY hashed_password field in account yaml file from another old project - and it works.

Something is wrong with tool that generates password hash

**Comment by coolemur** [comment]
Also I've updated Grav and Plugins using:

```$ bin/gpm selfupgrade -f```
```bin/gpm update -f```

Then again tried to create new user. Login still fails.

BTW I'm trying to run grav using https://lando.dev/ . It works on MAMP server. But that doesn't explain why on Lando it's working with old hash and fails with newly created user.

**Comment by mahagr** [comment]
@coolemur Which version of Grav are you using? Stable or testing?

**Comment by coolemur** [comment]
@mahagr I am using Grav v1.6.19 - Admin v1.9.12

**Comment by mahagr** [comment]
@coolemur I cannot reproduce this; make sure your PHP is up to date as it really seems to be php/library bug.

**Comment by coolemur** [comment]
@mahagr I am using PHP v7.3.

Checked using Lando server LAMP configuration - that works.

Doesn't work with Lando custom Grav configuration:

```
name: website
services:
  appserver:
    type: php:7.3
    via: apache
    version: 2.4
    webroot: .
    ssl: false
proxy:
  appserver:
    - website.lndo.site
```

But this doesn't differ much from LAMP config.

Is there some kind of logs that could give me more information about hashed password issues ?

**Comment by coolemur** [comment]
Also tested other cases: config without proxy server, with ssl, with different php version, with changed webroot (grav root dir) - no success..

```
name: website
services:
  appserver:
    type: php:7.0
    via: apache
    version: 2.4
    webroot: ./
    ssl: true
```

**Comment by coolemur** [comment]
Login issue was solved by deleting all Docker containers. It turns our something wasn't working with grav+ lando + docker combination. For now it works for me.
