### ISSUE TITLE
Profile access levels is missing from admin panel

### ISSUE THREAD

**Issue by alljamin** [getgrav/grav-plugin-admin#1775]
In [docs](https://learn.getgrav.org/16/admin-panel/dashboard/profile#access-levels) there is a mention of setting access levels for users and creating groups. I do not seem to find it anywhere in the admin UI. Do I need to install a separate plugin to get this functionality?
<img width="1327" alt="Screen Shot 2019-10-29 at 9 43 33 am" src="https://user-images.githubusercontent.com/10956179/67724934-95cb1780-fa30-11e9-8842-e308b498ad1c.png">

**Comment by rhukster** [comment]
This does not currently exist for regular users.  It's something we are going to be building out with our "FlexUsers" functionality.  It's still in the experimental stages but you cand find the option to enable it in the "Experimental" section of the "System" configuration if you are running the latest Grav 1.7 beta + Admin 1.10 beta.

**Comment by alljamin** [comment]
Oh, I see. May be having a beta tag on this section or simply extending section title to "Access Levels (beta)" can eliminate the need to post a question on GitHub.
