### ISSUE TITLE
0 - Call to undefined method Grav\Common\Data\Data::header()

### ISSUE THREAD

**Issue by lgwapnitsky** [getgrav/grav-plugin-admin#1776]
I'm receiving this whenever I try to save any plugin or configuration changes from the admin interface

I'm currently running Grav v1.6.16 - Admin v1.9.1

I've done updates in-place for at least the past 2 years, and have not seen this until today.

**Comment by rhukster** [comment]
Can you update to latest.  Admin in particular is at 1.9.10

If you are on latest it would appear you are missing some core files.  Perhaps an update failed partly.  You might want to try to manually download grav and copy the system and vendor folders back on top of you current ones.  Do not copy user as that will clause a loss of site data
