### ISSUE TITLE
error message from grav: "Error while trying to download (code: ) ..."

### ISSUE THREAD

**Issue by pflegende** [getgrav/grav-plugin-admin#1777]
we (as no-coders) start using GRAV
on:
https://cp1.awardspace.net/beta/zacky-installer/

after installing grav with panel - installer "zacky"
system said:
"...
 Thank you for Installing Grav with us.
You can now access your site's frontend here:
http://pflegende.dx.am
In order to start editing your website you need to login into the control panel of the website which is accessible here:
http://pflegende.dx.am/admin
    Creating database
    Configuring domain
    Building path
    Copying files: All done
    (Please be patient, this might take several minutes)
    Sending email
..."

so we try using grav - tool;

everytime using grav tool
on every used sub-side in the tool
it apears this message:

"...
Error while trying to download (code: ): 
https://getgrav.org/notifications.json?1572564430 
..."

"...
Error while trying to download (code: ): https://getgrav.org/blog.atom 
..."

"...
The connection to the GPM cannot be established
..."

trying ReInstall Grav generally
because of grav's hint:
"...
Paket mittels "Remote URL Reference" installieren
Alternativ können Sie auch eine vollständige URL zu der gezippten Paketdatei angeben um das Paket über eine Fremd-URL zu installieren.
..."

it appears a input form for the URL
but this URL is nowhere anotated, so we call grav devops:
please give us the needed URL where full(?)-Grave-zip for remote install is available.
please, please, please ...   ;)  ...

And grav call us also strongly to make a note on github
so we does ...

ready
done
:)

**Comment by rhukster** [comment]
Can you please provide some screenshots? I'm not really following what you mean by "Grav Tool", do you mean the admin?  It sounds like your hosting provider is blocking some PHP functionality that is used to access data remotely.  See this page in the docs: https://learn.getgrav.org/16/troubleshooting/common-problems
