### ISSUE TITLE
self blocking grav - installation on panel driven hoster

### ISSUE THREAD

**Issue by pflegende** [getgrav/grav-plugin-admin#1778]
we (as no-coders) start using GRAV
on:
https://cp1.awardspace.net/beta/zacky-installer/

in the grav panel is a option:
(now no more available for us, the grav user by awardspace.net-hosting and grav-native-panel, because by grav blocking itself, see forward ...)

something like:
"you can use ssl ... for every connection of your website"

we set it "on"

and now all grav - tools are blocked for us by
firefox (also in other browser)
(we think because of setted ssl)
but we can't re-set it because we could not arrive the self blocked grav-panel
- ??? -

"...
Fehler: Gesicherte Verbindung fehlgeschlagen

Die Verbindung zum Server wurde zurückgesetzt, während die Seite geladen wurde.

    Die Website kann nicht angezeigt werden, da die Authentizität der erhaltenen Daten nicht verifiziert werden konnte.
    Kontaktieren Sie bitte den Inhaber der Website, um ihn über dieses Problem zu informieren.

Weitere Informationen…

Fehler an Mozilla melden, um beim Identifizieren und Blockieren böswilliger Websites zu helfen
..."

**Comment by rhukster** [comment]
Seems you turned on "force SSL", but didn't have SSL setup correctly? You need to use SFTP, SSH, FTP, or some way to edit a file on the server:  `user/config/system.yaml`

and change the value back to `false`:

```
...
force_ssl: false
...
```

**Comment by pflegende** [comment]
Hi, great I will check to edit user/config_ ... sounds good, like the solution.  thx               
Selbsthilfegruppe pflegender Angehöriger
Demenz - Pflaster
Tel.: EF 7447 460

(registriert bei KISS Erfurt Tel. 655-4204
https://www.erfurt.de/ef/de/rathaus/sv/aemter/stelle-241.htmc )

Zur anonymen Kontaktaufnahme:
https://www.afpk-erfurt.de/kontakt
(Bitte Kennwort "Demenzpflaster" verwenden.)   

Am 07-Nov-2019 03:43:33 +0100 schrieb notifications@github.com:   

Seems you turned on "force SSL", but didn't have SSL setup correctly? You need to use SFTP, SSH, FTP, or some way to edit a file on the server: user/config/system.yaml 

and change the value back to false: 

... force_ssl: false ...
