### ISSUE TITLE
Backup file contains no extension

### ISSUE THREAD

**Issue by K232** [getgrav/grav-plugin-admin#178]
When I'm in the dashboard and click on 'Backup' it lets me download the backup file. That works fine, but the filename contains no extension. I don't know from which setting the filename is computed, but in some settings i have blanks in the title of my site, e.g. "This is a test". The filename is then just "This" instead of e.g. "This.zip" or "This_is_a_test.zip". I could easily rename it once downloaded, but users might be confused so maybe you want to fix it.

**Comment by rhukster** [comment]
It is computed based on the site title, and a date time stamp.  it works with spaces or without, and for me always has a .zip extension:

```
-rw-r--r--   1 rhuk  staff  10842867 Sep 15 16:59 Grav Admin-20150915165936.zip
-rw-------   1 rhuk  staff   9073449 Aug 21 17:36 Grav2-20150821173638.zip
-rw-r--r--   1 rhuk  staff  10842863 Sep 15 16:58 Grav2-20150915165807.zip
```

If you want to look at the logic it's in `src/Grav/Common/Backup/ZipBackup.php` line 29 contains the `backup()` method.

The naming logic is here:

```
        $name = self::getGrav()['config']->get('site.title', basename(GRAV_ROOT));

        if (is_dir($destination)) {
            $date = date('YmdHis', time());
            $filename = $name . '-' . $date . '.zip';
            $destination = rtrim($destination, DS) . DS . $filename;
        }
```

As you can see it clearly is getting a `.zip` extension forced.

**Comment by rhukster** [comment]
FWIW, i'm going to make a change so that the site name is 'hyphenized' to make it a bit safer for naming

**Comment by K232** [comment]
Well, not for me :-\ . When I set the title at /admin/site to 'Test' I could create a backup and it's name e.g. 'Test-20150916010744.zip' so that's fine. But when I rename the site title to 'This is a test' and create a backup, the file is named just 'This'. I swear ;-) I have all the latest versions of Grav and Grav Admin.

**Comment by rhukster** [comment]
The space in the filename must be throwing it in firefox.  Not to worry, the fix I put in to hyphenize the title should fix your problem with the upcoming next Grav release.
