### ISSUE TITLE
Saving default.md in multi language mode renames md file to first language

### ISSUE THREAD

**Issue by qmtester** [getgrav/grav-plugin-admin#1783]
We are using multiple languages in grav, but have pages that have the same content no matter the language. We are using a markdown file without language extension for that, e.g. default.md instead of default.en.md etc.

However, when editing that page through the admin plugin, the default.md file is renamed to a language specific file, e.g. default.en.md, depending which language is set first in the list of supported languages.

Is there a way to store the markdown under its original name when using save and only store it language specific when actually using the save button drop down? This is actually the behaviour we expected.

Further, once I have the constallation of a combination of say default.md and default.en.md, I am not able to edit/select default.md anymore through the admin plugin for editing and saving.

**Comment by rhukster** [comment]
First what versions of grav + admin are you using?

**Comment by qmtester** [comment]
Oh sorry forgot to mention. The actual site is running 1.6.9, however I also tried with 1.7 rc1 today and the behaviour is the same.

My current workaround is to introduce a language called "default", and renaming my markdown files that should be used by all languagles to XXXX.default.md.

**Comment by rhukster** [comment]
I think this behavior was changed in 1.7 if you use Flex Pages via the FlexObjects plugin configuration. @mahagr was working on this, so he probably has more insight.

**Comment by mahagr** [comment]
There is a configuration option for saving default language, which should work both with the old pages and flex pages: `Include default language in file extension`

**Comment by qmtester** [comment]
@mahagr Thanks for the info. I suppose this is 1.7 right?

**Comment by mahagr** [comment]
Yes, it' in Grav 1.7. Please test it out in your test site (and report any bugs) as it helps us to get the release out faster.

**Comment by mahagr** [comment]
@qmtester Did Grav 1.7 fix your issue?

**Comment by qmtester** [comment]
@mahagr I had not yet time to test it with 1.7, feel free to close this issue for now. Once I test it and it does not work I will reopen or create a new issue. Thanks.
