### ISSUE TITLE
[beta] Keyboard shortcut for save does not work with Flex Pages

### ISSUE THREAD

**Issue by MakaryGo** [getgrav/grav-plugin-admin#1787]
Shorcut `Ctrl + S` does not work on latest Admin (rc.1) when using Flex Pages.

**Comment by rhukster** [comment]
Thanks we had seen this reported but don’t think we had a ticket.

**Comment by w00fz** [comment]
Thanks for reporting the issue @MakaryGo , I have now taken care of this and will be available in next RC

👍
