### ISSUE TITLE
0 - Identifier "accounts" is not defined.

### ISSUE THREAD

**Issue by sowoi** [getgrav/grav-plugin-admin#1788]
Since I do not have SSH access on my website I used the manual installation method. 
But as soon as I try to access my website I am getting the following error:

```

Server Error

Sorry, something went terribly wrong!
0 - Identifier "accounts" is not defined.
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.
```

Server logs show:

`[2019-12-01 15:43:46] grav.CRITICAL: Identifier "accounts" is not defined. - Trace: #0 /var/www/vhosts/MyWebsite/MyWebsiteSub/user/plugins/login/classes/Events/UserLoginEvent.php(94): Pimple\Container->offsetGet('accounts') #1 /var/www/vhosts/MyWebsite/MyWebsiteSub/user/plugins/login/classes/Login.php(94): Grav\Plugin\Login\Events\UserLoginEvent->__construct(Array) #2 /var/www/vhosts/MyWebsite/MyWebsiteSub/user/plugins/login/login.php(118): Grav\Plugin\Login\Login->login(Array, Array) #3 /var/www/vhosts/MyWebsite/MyWebsiteSub/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Plugin\LoginPlugin->Grav\Plugin\{closure}(Object(Grav\Common\Grav)) #4 /var/www/vhosts/MyWebsite/MyWebsiteSub/user/plugins/login/login.php(536): Pimple\Container->offsetGet('user') #5 /var/www/vhosts/MyWebsite/MyWebsiteSub/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Grav\Plugin\LoginPlugin->authorizePage(Object(RocketTheme\Toolbox\Event\Event), 'onPageInitializ...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #6 /var/www/vhosts/MyWebsite/MyWebsiteSub/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPageInitializ...', Object(RocketTheme\Toolbox\Event\Event)) #7 /var/www/vhosts/MyWebsite/MyWebsiteSub/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onPageInitializ...', Object(RocketTheme\Toolbox\Event\Event)) #8 /var/www/vhosts/MyWebsite/MyWebsiteSub/system/src/Grav/Common/Grav.php(279): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onPageInitializ...', Object(RocketTheme\Toolbox\Event\Event)) #9 /var/www/vhosts/MyWebsite/MyWebsiteSub/system/src/Grav/Common/Processors/PagesProcessor.php(26): Grav\Common\Grav->fireEvent('onPageInitializ...', Object(RocketTheme\Toolbox\Event\Event)) #10 /var/www/vhosts/MyWebsite/MyWebsiteSub/system/src/Grav/Common/Grav.php(131): Grav\Common\Processors\PagesProcessor->process() #11 /var/www/vhosts/MyWebsite/MyWebsiteSub/system/src/Grav/Common/Grav.php(370): Grav\Common\Grav->Grav\Common\{closure}() #12 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('pages', 'Pages', Object(Closure)) #13 /var/www/vhosts/MyWebsite/MyWebsiteSub/system/src/Grav/Common/Grav.php(346): call_user_func_array(Object(Closure), Array) #14 /var/www/vhosts/MyWebsite/MyWebsiteSub/system/src/Grav/Common/Grav.php(132): Grav\Common\Grav->__call('measureTime', Array) #15 /var/www/vhosts/MyWebsite/MyWebsiteSub/index.php(54): Grav\Common\Grav->process() #16 {main} [] []

`

**Comment by rhukster** [comment]
It looks like you've uploaded your files incorrectly.  Try just grabbing a complete admin+grav package: (https://getgrav.org/download/core/grav-admin/latest), and unzipping that on the server via your CPanel or whatever.

**Comment by sowoi** [comment]
thank you! that solved my problem!
