### ISSUE TITLE
The menu selected is empty!

### ISSUE THREAD

**Issue by marcodeluca** [getgrav/grav-plugin-admin#1789]
Not sure if this is a Grav, Gantry or Admin Plugin issue. But on the latest update to Grav v1.7.0-rc.1 - Admin v1.10.0-rc.1 I now have an empty mainmenu when the menu is not, in fact, empty:)

<img width="1282" alt="Screen Shot 2019-12-02 at 4 17 37 PM" src="https://user-images.githubusercontent.com/968926/69996274-b4d13380-151f-11ea-9e98-6aad4b566586.png">

**Comment by mahagr** [comment]
This has already been fixed for the next Gantry release.
