### ISSUE TITLE
Grav 1.7-rc2, New Flex Pages Filter unexpectedly has Plugin Page types

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#1790]
The new Flex Pages Filter in the admin is 👍

I've been working with it a bit, and have noticed that when the SimpleSearch Plugin is installed/enabled that the `Simplesearch results` page type is listed - is that intentional (I am hoping not)? BTW, if SimpleSearch is installed that page type seems to get automatically selected when you refresh the Filters page(as shown below too).

UPDATE: After some more exploration, I can see that for some Plugins, like Presentation, this behaviour could be beneficial. For example, if the Presentation Plugin is active to filter by "Presentation" and "Slide" page types. Hmm... maybe only show items when both a Twig template and Blueprint are available???

<img width="1200" alt="2019-12-06_09-45-00" src="https://user-images.githubusercontent.com/1812771/70344081-ae87d380-180d-11ea-93b7-96cd644a8aeb.png">

Thanks very much,
Paul

**Comment by mahagr** [comment]
There's also a related issue where the previous selection is remembered after logout/login, even for days. I found it very confusing to have no pages showing up next day after doing some testing on the previous day.

**Comment by paulhibbitts** [comment]
It might be too much processing, but perhaps also consider only showing Page Types that are used within the current site?

**Comment by mahagr** [comment]
See the other issue, should be configurable now. :) Plugins can also hide their page types by an events `onAdminPageTypes` and `onAdminModularPageTypes` (they have been there forever).

**Comment by paulhibbitts** [comment]
Gotcha, thanks very much @mahagr !
