### ISSUE TITLE
Possibility to hide Page Types in new Flex Pages Page Filter UI?

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#1791]
As I've got a lot of custom page types in several of my themes, I've noticed that the new Flex Pages Page Filter UI can get pretty complex:

<img width="914" alt="2019-12-06_10-42-30" src="https://user-images.githubusercontent.com/1812771/70347352-358c7a00-1815-11ea-862e-5e9f8e4a8237.png">

The likelihood that a user would want filter by some of these types is pretty minimal, so I'd find the ability to 'hide' certain page/module types quite valuable - much like there is an option in the Admin UI to 'hide' certain templates when creating new Pages etc.

Might something like this be possible/of interest?

Thanks very much,
Paul

**Comment by mahagr** [comment]
The filters should show only the used page types?

**Comment by paulhibbitts** [comment]
That is what I expected as well, but as you see other templates/blueprints seem to show up. Even if this was not the case being able to hide certain page/modular types would be very valuable here.

**Comment by mahagr** [comment]
Should be fixed in RC.7 (requires grav+admin+flex update).

**Comment by mahagr** [comment]
@paulhibbitts It obeys admin plugin settings, so you have the same list as in dropdowns.

**Comment by paulhibbitts** [comment]
Thanks @mahagr , yes it sounds like Andy did some work on the Admin side of things to handle this - just confirming 🙂https://github.com/getgrav/grav-plugin-admin/commit/a46368ac7c66d5b38eaeffea07a8a59e21c749ab

**Comment by mahagr** [comment]
I reverted that change as I found we already had the feature.
