### ISSUE TITLE
Regression: Widget display changes in Admin v1.10.0-rc.2 

### ISSUE THREAD

**Issue by jgonyea** [getgrav/grav-plugin-admin#1792]
Before, the key used to be `plugins.admin.widgets`, but now it is `plugins.admin.widgets_display`.

I was told to submit an issue so someone could note the change.

Cheers.

**Comment by jgonyea** [comment]
Following up on this.  This affects anyone who changed the default widget selection. I had previously turned off some widgets, but after the upgrade, the disabled ones returned.

**Comment by mahagr** [comment]
This change was made when fixing #1766, but it's not backwards compatible change.

@rhukster ?

**Comment by rhukster** [comment]
Can’t change it now it’s been this way for over a year. Just re-save your config and it will use the new variable.
