### ISSUE TITLE
Grav 1.7-rc2, Admin Panel Pages button colours vs. Grav 1.6?

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#1796]
Not sure if this is due to differences in the RC builds and 1.6 releases, but this 1.6 change re: red Delete button does not seem to be in the most recent 1.7 RC build?

https://github.com/getgrav/grav-plugin-admin/issues/1768

Grav 1.6x
<img width="1200" alt="2019-12-09_10-54-39" src="https://user-images.githubusercontent.com/1812771/70464031-f22f4700-1a72-11ea-88fc-9f576c67578f.png">

Grav 1.7RC
<img width="1200" alt="2019-12-09_10-55-34" src="https://user-images.githubusercontent.com/1812771/70464039-f52a3780-1a72-11ea-958d-4c74a1075a03.png">

Might this still find it's way in the 1.7 release?

Thanks very much,
Paul

**Comment by rhukster** [comment]
Looks fine to me in a sock install of latest 1.7/1.10

**Comment by paulhibbitts** [comment]
Thanks for taking a look Andy, perhaps it was an update issue.
