### ISSUE TITLE
Grav 1.7-rc2, custom Admin Panel Page list buttons not appearing?

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#1798]
This may be a known issue, but I've noticed new [Admin Panel Page list buttons](https://learn.getgrav.org/16/cookbook/admin-recipes#add-a-custom-page-creation-modal) added via the `admin.yaml` file do not seem to appear when Flex Pages is enabled.

Standard pages:
<img width="1200" alt="2019-12-20_08-18-31" src="https://user-images.githubusercontent.com/1812771/71269316-e6117800-2303-11ea-8152-eb11b917fef6.png">

Flex pages:
<img width="1200" alt="2019-12-19_13-45-53" src="https://user-images.githubusercontent.com/1812771/71269329-eb6ec280-2303-11ea-86d6-224360d11801.png">

Please let me know if more info is helpful etc.

Thanks very much,
Paul

**Comment by mahagr** [comment]
Flex Pages needs likely a bit different implementation; we will need to look into it.

**Comment by mahagr** [comment]
FYI: This is fixed in the Flex plugin (RC4).

**Comment by paulhibbitts** [comment]
Thanks very much @mahagr , that is excellent news!
