### ISSUE TITLE
Не устанавливаются плагины и шаблоны

### ISSUE THREAD

**Issue by webmaster280211** [getgrav/grav-plugin-admin#1799]
When you try to download any of the plugins, and when you click install, the alert window "No slug set is displayed". The installation spins for a long time, as a result, nothing is installed, it is simply not possible to wait, I click on the translucent area to reset, it is reset and there is no trace of the installation. Help solve the problem, because it does not make sense to continue working with this system.

**Comment by rhukster** [comment]
Sounds like you have problems with your setup.  It really could be anything.  Try hopping on the Grav Discord chat as it's going to take a while to determine exactly where things are going wrong.
