### ISSUE TITLE
Flex plugin fails on fresh install

### ISSUE THREAD

**Issue by ThosG** [getgrav/grav-plugin-admin#1800]
After a fresh install of Grav 1.6.19 with Admin 1.9.12, I installed Flex Objects and Flex Directory. These created the expect navigation links in the left menu, but they failed when I tried them. The menu item for Flex Objects linked to XXX/admin/flex-objects/contacts which gave an error:
`Call to undefined method Grav\Framework\File\Formatter\JsonFormatter::getFileExtension() `

The menu item for FlexDirectory linked to CXXX/admin/flex-directory/entries which gave a 404, after (I think) a 'Too many redirects' error.

PHP Version 7.3.11

**Comment by lufog** [comment]
As far as I know, the Flex Directory plugin is no longer supported. Flex Objects is still under development and testing. It can be tested on Grav 1.7.0. But for production, it is not ready yet. Depending on the operating system or version of the PHP, various errors appear.

**Comment by ThosG** [comment]
Ok, thanks. Didn't realise it wasn't ready.

**Comment by mahagr** [comment]
Flex plugin requires both Grav 1.7 and Admin 1.10 to work.
