### ISSUE TITLE
Grav 1.7-rc3, initial placement of new "Root" settings feature

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#1805]
It's great to see a new RC build to kick off the New Year! With rc3 though I am concerned about the use of the new Flex Pages list (which has been awesome to use in my various skeletons esp. MultiCourse Hub with a larger number of levels/sites) to contain root Page settings (vs. only Page content):

<img width="1200" alt="2020-01-02_16-34-44" src="https://user-images.githubusercontent.com/1812771/71771406-fc682800-2eee-11ea-8c4b-8410114b9627.png">

While I appreciate that some sort of root/default settings is a very useful addition I am concerned that their inclusion in the Flex Pages list can confuse site users (esp new users/devs trying out Grav for the first time). In addition, if a site uses the Git Sync Plugin this special `root` page will appear in Git repositories which are only intended to hold page Markdown page content.

Might it be possible to explore other locations/methods for users to access these settings? Since these appear to be more related to settings, might one candidate be the existing Config area in Admin? 

I hope I have understood the purpose of this new `root` feature. Thanks very much for considering this concern,
Paul

**Comment by mahagr** [comment]
As you said, root is a real page: `user/pages/root.md`. Right now it is work in progress and contains only some default settings (which is why it uses root blueprint), but in theory, it could be any type and it could act as the home page or `/` in the future (right now I just hardcoded it to be the root, mostly because of backwards compatibility to the old pages).

Root page was added to implement parent ACL, but it can be extended to contain any inherited settings to the child pages. The reason why it is a page is to simplify the logic as it would be the same regardless of in which page you're in. So it basically solves the issue of having two separate inheritance systems for the first level pages vs the others.

**Comment by paulhibbitts** [comment]
Thanks for the additional info @mahagr ! As development proceeds, I hope that the UX of this feature is carefully considered as it impacts beginner to advanced Grav users in several ways (i.e. Flex Page list conceptual model, Git Sync page repos, etc.).

If at any time I can be of help please let me know, thank you.
Paul

**Comment by paulhibbitts** [comment]
Hi @mahagr , just checking in to see if you have any followup updates/thoughts on this issue. I remain concerned about 'settings/config' type options intermixed with actual pages in the new Flex Pages UI.

Another scenario where the current implementation is a concern is when Grav is pre-configured/setup for a client's site, and this `root` type feature is exposed (where we do not want site editors to alter or even see this config etc.).

Thanks very much,
Paul

**Comment by mahagr** [comment]
I'm working on something that will help on this, but the root page is not just for exposing the configuration, it is just like any other page. 

CC @rhukster @w00fz

**Comment by OleVik** [comment]
Does `root` then replace the current `home.alias: /home` in system.yaml? I am also concerned that this mixes configuration with content, if `root` handles the Access Control List.

**Comment by mahagr** [comment]
It can do that (root being home) for sure, though right now I'm not allowing that because of the backwards compatibility to the older code.

That ACL setting will be added to all pages, not just root. We will likely restrict it to the super admin users (or to a specific ACL rule) only.

**Comment by paulhibbitts** [comment]
Thanks for the update @mahagr , if I can be of any help please let me know - I hope I have explained my concerns clearly.

**Comment by rhukster** [comment]
I agree that root probably should be something that only `super admins` see.

**Comment by paulhibbitts** [comment]
Thanks @rhukster , that would help in some situations but all new users and users of pre-packages skeletons would still see this special `root` page item and likely be confused that it is listed the same way as Markdown content pages, possibly try to delete it, and still also see it on GitHub etc when Git Sync is used. Any other thoughts?

Might it be possible to "assign" an existing Grav content page to be `root`, like you do with the idea of setting a `home` page? Or perhaps an option to use or not use (to included or not include) a root page? I really want to have that new Flex Pages UI easily understood and used by both new and more experienced users etc.

Thanks very much,
Paul

**Comment by mahagr** [comment]
Remember that redirects, placeholders etc are already listed in the same way as content pages, most skeletons just do not have them (outside Gantry that is). Root page can be deleted with no other ill effects but loosing default ACL settings.

Like I said, having root as your home is possible as well as using any page type, but right now it is kind of hardcoded not to work because of backwards compatibility (Flex Pages isn't ready for frontend in all sites). We are not getting rid of it, though, because of it is exactly what it is supposed to be, a page below every other page. We could hide it it in admin for any non-super user for now.

We could have option to hide root page for sure.

**Comment by paulhibbitts** [comment]
Hi @mahagr , thanks very much for your feedback!

To confirm, it sounds like the new `root` page could be deleted and Grav Flex Pages would still work? If so, this would be very helpful as then for Grav Skeletons where this `root` item could not be included for new installs (esp. of simpler sites) etc. Could you please confirm this?

It also sounds like in the future a Grav a standard Grav Page could be assigned to be `root` and thus eliminating the need for an actual `root` page? Could you please confirm this?

Thanks very much,
Paul

**Comment by mahagr** [comment]
Confirmed and yes, planned in the future.

**Comment by paulhibbitts** [comment]
Thank you so much @mahagr , that makes me feel much better and I appreciate your discussion of this issue.

Looking forward to using Flex Pages for all of my open education and publishing projects!
Paul

**Comment by paulhibbitts** [comment]
Hi @mahagr , I've just gotten a chance to install RC 11 and it looks fantastic! I wanted to reopen this issue though to see if there is now any way to "hide" the Root item from users of my Skeletons? Thank you!

**Comment by mahagr** [comment]
@paulhibbitts The file is not required. Also, it can be hidden from users if you deny access to edit page directory settings.

**Comment by paulhibbitts** [comment]
Thanks @mahagr , in my case I'd like to remove it from my Skeletons to reduce possible confusion. How can I delete it? If I try to delete it from the Admin Panel I get this error message right now:
`Delete Failed: You have insufficient permissions for task delete.`

Thanks,
Paul

**Comment by mahagr** [comment]
Delete it manually from the filesystem.

**Comment by paulhibbitts** [comment]
That's what I was thinking too @mahagr but I cannot seem to find it? It does not seem to appear in my Pages folder.

**Comment by mahagr** [comment]
If it's not there, it's not being saved. The root is always there for the users who have super admin access.

**Comment by paulhibbitts** [comment]
Thanks @mahagr , then are there any approaches left for me to initially "hide" the Root item within my skeletons by default?

**Comment by mahagr** [comment]
Do not give users permissions to the page configuration. Otherwise no, it's part of the ACL implementation.

**Comment by paulhibbitts** [comment]
Ah, ok thanks @mahagr I will then assume it always has to be there and plan accordingly🙂
