### ISSUE TITLE
Default options when creating pages in Admin Panel

### ISSUE THREAD

**Issue by jpfleury** [getgrav/grav-plugin-admin#181]
Using Grav v0.9.43 and Admin Panel v.0.6.0, default options when creating a page are:

- Parent Page: *- Root -*
- Page FIle: *Default*

It would be useful to have a way to set default values. For example, for a blog, I would set default to *Home* and *Item*.

**Comment by jpfleury** [comment]
Set default settings or simply remember last values used.

**Comment by flaviocopes** [comment]
Good suggestion, last values used are now remembered in the session with https://github.com/getgrav/grav/commit/198046a5d3f5598de77a4230767d13cfd71791c5 and https://github.com/getgrav/grav-plugin-admin/commit/d2daa17352882c56229804207de8f18de24cde2d
