### ISSUE TITLE
I installed today and I have the same problem...

### ISSUE THREAD

**Issue by Kobraz** [getgrav/grav-plugin-admin#1810]
I installed today and I have the same problem...

When will RC4 become awailable? 

How do I update GravCMS? Do I have to download and install again?

_Originally posted by @Kobraz in https://github.com/getgrav/grav-plugin-admin/issues/1806#issuecomment-574633011_

Any solution?

**Comment by rhukster** [comment]
We're in the middle of some pretty big ACL improvements. As soon as they are ready, we'll release RC4.
