### ISSUE TITLE
Media Setting Double Admin 1.10.0-rc.3

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#1813]
![Bildschirmfoto_2020-01-20_09-00-40](https://user-images.githubusercontent.com/12480617/72708951-15fea600-3b64-11ea-8f89-bae4ced29d6d.png)

**Comment by mahagr** [comment]
I'm not seeing this.

**Comment by rhukster** [comment]
Duplicate: https://github.com/getgrav/grav/issues/2794
