### ISSUE TITLE
Widget Plugin - Widget area location doesn't work

### ISSUE THREAD

**Issue by Mohamed-Programmer** [getgrav/grav-plugin-admin#1815]
Hello every one!

I added [Widget Plugin](https://github.com/sojimaxi/grav-plugin-widget) to my Grav project. It's working fine except one thing. When I change the widget location for e.x "Content-top" or "Content-bottom" it doesn't work. But when I set it to "Default" it works.
![Capture](https://user-images.githubusercontent.com/56513986/72730946-e3b86d00-3b92-11ea-98ad-cf0ad0b3cb18.PNG)

Someone has an idea what I am doing wrong?

**Comment by mahagr** [comment]
Likely your theme does not support the positions?

This issue should really be reported in the plugin.

**Comment by Mohamed-Programmer** [comment]
Yes, I think the same thing, that my theme doesn't support the positions. But I thought the plugin should do that for me.

**Comment by rhukster** [comment]
These are not standard features of Grav, they are obviously provided by a custom theme.  You will need to take it up with the theme developer on the theme repo.
