### ISSUE TITLE
ErrorException when deleting a page

### ISSUE THREAD

**Issue by jpfleury** [getgrav/grav-plugin-admin#182]
I've encountered this bug quite often. It seems to be (but maybe not exclusively, I'm not sure) with pages that are translated, for example `en` and `fr`, and when deleting one language. Error:

![capture d ecran_2015-09-17_01-52-37](https://cloud.githubusercontent.com/assets/687082/9926062/1aa2d490-5ce0-11e5-9fac-409ccd5883fa.png)

Config: Grav v0.9.43 and Admin Panel v.0.6.0

**Comment by rhukster** [comment]
I've never seen this error. Can you please provide exact steps to recreate. or perhaps a location of a zip of a site that can have this error.  It is imperative to be able to recreate a problem before it can be fixed.

**Comment by jpfleury** [comment]
I can always reproduce this bug with the steps below. Sometimes not always the first time, but if I do these steps 2, 3 or 4 times in a row (an easy way to test it is with default pages from the blog skeleton), the bug will occur:

- In the Admin Panel, open a page that is not related to any language, for example *Classic Modern Architecture* in the default blog skeleton. There's no language code in the left of the button *Normal*:

    ![01](https://cloud.githubusercontent.com/assets/687082/9944830/c9c54256-5d57-11e5-9d22-8fa76f3d454f.png)

- Save as Français (I have `fr en` as languages in my site):

    ![02](https://cloud.githubusercontent.com/assets/687082/9944842/d1464994-5d57-11e5-8db4-248619ced77e.png)

- Click *Delete*. I don't know if it's relevant, but note that even if I previously saved as *Français*, there's still no language code in the left of the button *Normal*:

    ![03](https://cloud.githubusercontent.com/assets/687082/9944851/d91c2922-5d57-11e5-92e4-81924eabada5.png)

- Confirm with *Continue*.

**Crikey! There was an error...**

**Comment by flaviocopes** [comment]
I noticed that pages are not saved as a new language any more, not sure when this problem started, they used to work! If you notice, in the last page you don't have the lang code, it should appear left to the `Normal` button.

![screen shot 2015-10-01 at 15 00 49](https://cloud.githubusercontent.com/assets/11783388/10221189/3d41fc38-684d-11e5-943c-afec8c3a6422.png)

I posted a fix that should address this problem in the next update (https://github.com/getgrav/grav-plugin-admin/commit/bc7efe0dd4adc46244ae6bb7313c2707a70389a6)
