### ISSUE TITLE
New User Created in Admin With Site Login Permission Cannot Log Into Site

### ISSUE THREAD

**Issue by thekenshow** [getgrav/grav-plugin-admin#1821]
I'm running Grav 1.7-RC3 + Gantry latest, and have found an issue that can be repeated as follows:

1.  Enable Flex User accounts.
2. Create a new account using the Admin and assign only Site Login permission.
3. Attempt to login as that new user - fails with Login failed... message.

When I create the same user/password using CLI `bin/plugin new-user`, the login works as expected.

I noticed that the Admin-created account had a long string for the account yaml file, e.g.,  `847a0c7b580daa1d821d2fbcc1493288.yaml` while CLI creates `username.yaml`. Tried renaming the Admin-created file, made no difference.

**Comment by mahagr** [comment]
This has already been fixed for rc.4.
