### ISSUE TITLE
Grav 1.7 RC.5 Flex Pages UI minor visual glitch?

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#1825]
On both Firefox and Safari (Mac) I've noticed a possible minor visual glitch (or maybe it is intentional) which nI thought I'd make of a note of here for your review:

<img width="1200" alt="2020-02-04_09-04-33" src="https://user-images.githubusercontent.com/1812771/73768657-429eea00-472e-11ea-9f72-0786f7a47505.png">

Fantastic UI improvement for Pages! If more testing/info is helpful please let me know.

Thanks very much,
Paul

**Comment by rhukster** [comment]
That gap is actually standard in the admin, it just stands out more as we've put a background color behind the breadcrumbs at the bottom. I've fixed this for next release.

**Comment by paulhibbitts** [comment]
Sounds good, thanks for taking a look Andy.
