### ISSUE TITLE
Visible: False not being set when creating a page.

### ISSUE THREAD

**Issue by ChrystalSolutions** [getgrav/grav-plugin-admin#1831]
When creating a new page and selecting "Visible: No" it has no affect on the page that is created.  The page is still created as Visible: Auto, both before and after saving the page.  I created a custom page modal for adding a new page, but this issue is also present when using the regular "Add"  button.

See this [forum post](https://discourse.getgrav.org/t/trying-to-default-new-pages-to-not-visible-but-its-not-setting-visible-false-in-the-front-matter/11418/2) for more details.

**Comment by mahagr** [comment]
@ChrystalSolutions Which version of Grav you're on? I was assuming 1.7 / 1.10

**Comment by ChrystalSolutions** [comment]
Version 1.6.21.

I have two sites that are affected by this issue.  Both are on 1.6.21

**Comment by ChrystalSolutions** [comment]
I just updated to Grav 1.6.22 and admin plugin 1.9.13 and it still seems to be an issue.  I clicked the regular (stock) "Add" button, and in the modal dialog, I selected visible:no and when the page was created, nothing was set on the visible field.

**Comment by rhukster** [comment]
Pretty sure this was a bug that was fixed with the latest Grav+Admin+Form plugin. have you updated them all?

**Comment by ChrystalSolutions** [comment]
Everything is updated.

 Admin Panel  v1.9.13
 Admin Addon Media Sort v0.1.0
 Admin Addon User Manager v2.2.1
 Bootstrapper  v2.0.0
 Email  v3.0.7
 Error  v1.6.2
 Form  v4.0.5
 Google Maps v1.0.10
 Login  v3.1.0
 Markdown Notices  v1.0.4
 Problems  v2.0.3
 Quick Tray Links  v1.0.0
 Shortcode Core  v4.2.2
 Sitemap  v1.9.4
 Unitegallery v1.1.3

**Comment by rhukster** [comment]
Actually @mahagr this is not working in 1.7 either. Something has changed with that `visible:` attribute.

**Comment by ChrystalSolutions** [comment]
If it helps, it was working previously.  When I setup my site in September, it was working.  I was setting up a new site recently and noticed it wasn't working.   I went back and checked the first site and found it had broken there too.  The site had been updated since I first built it.

**Comment by rhukster** [comment]
Actually it does work, but maybe not as you expect.   Choosing the visibility option for a new page **does not** set the `visible` override in advanced, it actually controls if the `folder prefix` is enabled or not.  That's because, by default, the `folder prefix` is what determines visibility. The `visible` override is purely to override the default behavior.

**Comment by mahagr** [comment]
Yes, the variable does not affect header, but folder ordering prefix. Header properties can be changed by `header.*`, though I'm not sure if that is supported either.

**Comment by ChrystalSolutions** [comment]
Let me back up a step.  I created a site with a blog, but I didn't want each blog article to show up as a submenu item under the "blog" heading.  However, I still want the blog author to be able to sort the blog articles.  When I created the site, and using the custom model for adding a page.  It worked exactly as planned initially.  Since then, something has changed and it no longer works.  New pages are visible under the "blog" menu, when created with the custom "Add" button.  If I use the regular "add" button, and choose visible:no, the created page is created, like you said, without the prefix numbering.  However, what we want to do is override the visible to false, but still have the pages be abled to be ordered.

**Comment by mahagr** [comment]
Let me look into this one.

**Comment by sp2ong** [comment]
I have used Grav 1.6.23 with Admin v1.9.13 and not working switching "Publish" in normal mode. It is very strange that it is displayed twice "YES" and "NO" in row "PUBLISH". See attached image 

![page](https://user-images.githubusercontent.com/822846/79719876-c608ba00-82df-11ea-96e9-d5b95221d695.jpg)

**Comment by sp2ong** [comment]
I have reinstall grav and all works OK

**Comment by w00fz** [comment]
Also tested again to make sure and it is working in 1.7
