### ISSUE TITLE
Cannot save Archive plugin with new value.

### ISSUE THREAD

**Issue by flpommeton** [getgrav/grav-plugin-admin#1832]
I cannot change the parameters of the Archive system See attached error message.

![Screen Shot 2020-02-17 at 7 21 07 PM](https://user-images.githubusercontent.com/5676632/74681210-baebbd80-51ba-11ea-8495-4b787ea3e6c3.jpg)

**Comment by rhukster** [comment]
This has been fixed in latest update of archives plugin.. should be available shortly.
