### ISSUE TITLE
Object layout 'save' not found.

### ISSUE THREAD

**Issue by qumuq-til** [getgrav/grav-plugin-admin#1836]
After updating from 1.7.0 rc2 to 1.7.0 rc6 I get a "Object layout 'save' not found." message on saving any page in admin. Update installed flex objects plugin as a dependency and disabling it made the error go away although now it has a large red block of complaint saying that admin plugin dependency is missing. Any other info I can provide, let me know.

**Comment by mahagr** [comment]
You need to install the latest Flex Objects plugin before continuing.

**Comment by qumuq-til** [comment]
Continuing with what? When I updated, Grav installed flex plugin as a dependecy, afterwards I checked for newer versions and none were available. Unless there was a new version pushed in the last 2 days.

**Comment by mahagr** [comment]
You can disable pages/user admin from the plugin and admin will revert to the old behaviour.

**Comment by qumuq-til** [comment]
I don't understand that, sorry.
The original bug report cocerned broken save functionality after updating from rc2 to rc6 with default settings. I worked around it as mentioned already.

**Comment by Japhys** [comment]
Don't want to create a new issue if it's a known issue (or not impemented yet). Whenever I save a page with Flex Pages enabled I too get this error.

**Comment by mahagr** [comment]
Must be some plugin breaking things as I've never been able to get this issue. Something is hooking into save task and breaking the logic.
