### ISSUE TITLE
Error on save in new plugin

### ISSUE THREAD

**Issue by Silbad** [getgrav/grav-plugin-admin#1838]
Hello,
I create a new plugin and I have an error on save parameters :
"text_var is not defined in blueprints"
Note : I have delete all refs of this field because I not use it...
Thanks

**Comment by rhukster** [comment]
This is something we are going to fix for next update of Admin/Grav.  However, the quick fix is to edit your plugin's blueprints and change the `validation: strict` to `validation: loose`.  I've also just re-released devtools plugin with this in by default.
