### ISSUE TITLE
Using custom admim route = error after page edit

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#184]
I tried to edit a page. After save button I get:
Call to a member function header() on null
(user/plugins/login/login.php:112)
![error](https://cloud.githubusercontent.com/assets/12480617/9933732/25f75a2e-5d4d-11e5-92b4-4110181a4a1a.png)
Changes in article are applied but I get the error message.

**Comment by rhukster** [comment]
I've never seen this error. Can you please provide exact steps to recreate. or perhaps a location of a zip of a site that can have this error. It is imperative to be able to recreate a problem before it can be fixed.

**Comment by axel-rank** [comment]
Ok, I found out.
I had changed default Admin login path for security reason in my admin.yaml from mysite/admin to mysite/cfg3. That worked.
But after pressing save after page editing I got this error.
After resetting to default 'admin' path error is gone.

**Comment by rhukster** [comment]
Ok, that helps a lot.  We'll track this one down. Thanks!
