### ISSUE TITLE
Pages menu won't load with limited (editor) user priviledges (Grav v1.7.0-rc.6)

### ISSUE THREAD

**Issue by dkophelyi** [getgrav/grav-plugin-admin#1841]
I made a new user with editor priviledges:

![image](https://user-images.githubusercontent.com/59764298/75548505-bbdbe500-5a2d-11ea-855c-ed28a99c8b76.png)

When i sign in with the new profile and select Pages (17 pages have been created at this point), i get this:

![image](https://user-images.githubusercontent.com/59764298/75548570-e62da280-5a2d-11ea-8397-8e96c6c357e6.png)

Any ideas?
Thanks in advance!

**Comment by mahagr** [comment]
For me, this works perfectly with flex pages turned on. I have about 20 users with different permissions and all of them can access pages.

It does not work with the old pages, but you shouldn't be able to see the CRUD settings if you do not have Flex pages admin turned on.

I need to dig deeper...

**Comment by dkophelyi** [comment]
Thanks for your reply!

Forgot to turn on Flex Object for account type - now it's working, thank you!
However i was able to see the CRUD settings even with the old settings.

**Comment by mahagr** [comment]
It should work in admin even if not turned on in the system settings. But yes, you need it turned on in admin because of the old ACL logic works in a slightly different way and will not be able to handle partial settings properly.

**Comment by Strixos** [comment]
Hi, I have the same issue.
I created a group "User" who could just manage Pages and Login to Admin (to access the Pages menu).
I had troubles to see the Pages menu on the user account but I have the error 404 message when I try to access it.

**Comment by mahagr** [comment]
@Strixos Could you give me the URL paths for both the admin and the URL you get when you click to the pages, please?

**Comment by Strixos** [comment]
Hi @mahagr 

The URL from the admin plugin is this one : http://localhost:8000/fr/admin/pages
And the one for the pages is this one : http://localhost:8000/fr/admin/pages

It's the same URL from my admin account and the user account I'm testing.

Here is the configuration the group of user I want to give access : 
![image](https://user-images.githubusercontent.com/27220378/80284446-d32e0a80-871e-11ea-832b-dace43f19cdc.png)
![image](https://user-images.githubusercontent.com/27220378/80284463-e7720780-871e-11ea-8a83-445f33f4a85d.png)
![image](https://user-images.githubusercontent.com/27220378/80284474-01134f00-871f-11ea-8914-b8bc65fc6d87.png)

Regards

**Comment by mahagr** [comment]
Just FYI: Fixed related issue where page count from one user affected another (they saw different amount of pages).

**Comment by Strixos** [comment]
Hi, I still have the error with the User account. Did you find anything about this issue ?
Regards

**Comment by mahagr** [comment]
Unfortunately I didn't find anything else than what I fixed. I really need to be able to reporduce this one locally.

**Comment by Strixos** [comment]
Hi,
If it helps I can send you the sources. Just give me a mail I can send it.

**Comment by mahagr** [comment]
matias at trilbymedia dot com.

**Comment by Strixos** [comment]
Hi Matias,
I just sent you my project by mail. The mail object is "Strixos - Grav Issue #1841".

Regards

**Comment by mahagr** [comment]
Thank you. I will take a look when I have a chance. If you don't hear anything from me, please ping me in this issue.

**Comment by Strixos** [comment]
Hi @mahagr,
Any news on this subject ?

Regards

**Comment by mahagr** [comment]
@Strixos I updated everything in your site to the latest and changed the second user not to have delete rights. Everything worked just fine, the user was able to access the pages, but didn't have the delete button in the edit page. (Yeah, I know that the list page still has the button)

PS: you probably need to rename the user files to match the lowercased username. There was a bug on that one.. Or just remove the random named files and create new ones.

**Comment by mahagr** [comment]
Also, you don't need to deny access, just leave it to `Not set`. Deny should only be used as an override, as you should use smaller roles and assign multiple roles to the user. Like: Page Editor + User Manager.
