### ISSUE TITLE
Unable to install or update plugins

### ISSUE THREAD

**Issue by prinla** [getgrav/grav-plugin-admin#1843]
![grav](https://user-images.githubusercontent.com/16805582/75624424-359ddb00-5bb4-11ea-9edd-8d54c52d5f46.jpg)

I have a problem updating or installing plugins on all my websites (different servers... so it can't be an internal problem from my side). There might be a github problem because it happened from one day to the other on sites with different version of Grav.

Please help

**Comment by prinla** [comment]
We found the solution:
The config/system needed to be Remote Fetch Method = fopen and not on auto

**Comment by prinla** [comment]
Could you maybe check why from one day to the other the Remote Fetch Method = auto doesn't work anymore? Is there a reason in github or grav? Mabe adjust in the next updates

**Comment by mahagr** [comment]
There have been no changes on the installer for likely in months, likely closer to a year. I bet there's something server related going on breaking CURL.

**Comment by mahagr** [comment]
Same as https://github.com/getgrav/grav-plugin-admin/issues/1844

**Comment by w00fz** [comment]
Please see https://github.com/getgrav/grav-plugin-admin/issues/1851#issuecomment-731487693
