### ISSUE TITLE
No plugin installation - similar to issue #939

### ISSUE THREAD

**Issue by beamaria** [getgrav/grav-plugin-admin#1844]
I had everything working properly with "remote Fetch method" set to "Auto", but suddenly I was unable to install new plugins (not only the grav plugin admin) and I had to switch from "Auto" to "fopen"- This solved the problem, but I can't understand why the site worked for nearly two months and then- without any change in settings or in server- I had the same error and behaviour using different browsers (Safari, Chrome) -Cache cleaned in website and browsers-
Switching to cURL doesn't solve the problem.
I noticed that the preview of pages in backend has slowed down in comparison to "Auto" settings...not sure if this is related to this issue.

Grav version: 1.6.21
Admin panel: 1.7.0
Gantry 5 version: 5.4.32
Helium: 5.4.32
php: 7.2.22
Linux server

_Originally posted by @beamaria in https://github.com/getgrav/grav-plugin-admin/issues/939#issuecomment-593118292_

**Comment by mahagr** [comment]
It's not browser related issue but has something to do with your server settings (maybe curl is disabled?). Not sure why auto uses it.

**Comment by beamaria** [comment]
I 've just checked in Admin Panel->System->Info : both support for cURL and fopen are enabled...maybe is it related to SSL??

**Comment by mahagr** [comment]
BTW: auto setting prefers to curl over fopen (which more likely to be disabled for remote files as it can be used for attacks) so if it's enabled, it was the right thing to do.

Are you getting any errors which may indicate that the issue is related to SSL?

**Comment by beamaria** [comment]
Nothing in reports or logs- When I tried to install some plugin I had this error: 
Error while trying to download (code: 0): https://getgrav.org/download/plugins/relatedpages/1.2.2 Message: URL using bad/illegal format or missing URL/malformed

**Comment by mahagr** [comment]
@rhukster @w00fz Have you seen this one before?

**Comment by beamaria** [comment]
I've just seen in the chat someone else - @Loopios7 - has this issue...
 I described what I've done.I'm in Plesk panel too, but it has worked without any problem till the day I opened the issue

**Comment by Loopios7** [comment]
Yes, I do indeed have this issue as well and have been unable to resolve it so far.

**Comment by jurnskie** [comment]
I do also have this issue. 
<img width="335" alt="Screen Shot 2020-03-23 at 9 25 35 AM" src="https://user-images.githubusercontent.com/4242668/77297308-5d7eeb00-6ce9-11ea-8f53-5efda1d1d42f.png">

**Comment by beamaria** [comment]
the only solution is to go to Configuration, "Advanced" Tab and set the "remote fetch method" to "fopen" . 
No one was able to offer a satisfactory reason for this behaviour , apart from a misconfiguration of "cURL" in server or perhaps the use ofGRAV in Plesk Panel.

**Comment by vince2bir** [comment]
Same error here, fixed the same way.
Clean install - latest stable release as today.

**Comment by rhukster** [comment]
Could you guys who have this problem please set up a test install of latest 1.7rc grav release? We’ve switched to Symfony’s HttpClient for these calls.  Would be good to know if it solves these problems out of the box.

**Comment by vince2bir** [comment]
Checked and found OK !
No issue with version 1.7.0-rc.10 on a clean install.
