### ISSUE TITLE
Admin v1.10.0-rc.7 - Flex Pages: Preview not working

### ISSUE THREAD

**Issue by kiranetph** [getgrav/grav-plugin-admin#1845]
The Preview button is not properly working. It opens the page in edit mode.
![image](https://user-images.githubusercontent.com/15226809/76069852-7e97ca00-5fce-11ea-8a31-434a1c781a02.png)

**Comment by w00fz** [comment]
@mahagr this is for you, preview work on the button but it gets redirected to edit.

Try hitting `admin/pages/home/?preview=1` manually and you will see.

**Comment by mahagr** [comment]
@w00fz The URL has trailing slash which causes the redirect (Grav system setting).

PS: The correct path is `admin/pages/home/:preview` as I've simplified all the actions to use simpler syntax.
