### ISSUE TITLE
Admin v1.10.0-rc.7 - Flex Pages: wrong filter behavior

### ISSUE THREAD

**Issue by kiranetph** [getgrav/grav-plugin-admin#1846]
Filter does not work properly after "Reset to Defaults". It does not apply the filter again.

![2020-03-06_17-32-43 (2)](https://user-images.githubusercontent.com/15226809/76071293-fe269880-5fd0-11ea-8b2a-792f88cb1070.gif)

**Comment by w00fz** [comment]
I can't replicate this in the current repo state. Did you try @rhukster ?

**Comment by rhukster** [comment]
Sort of, I get the issue if i click a custom page type, then reset to defaults, leave the page, then come back, the page type is again set, when it should not be anymore (as I had reset).

**Comment by w00fz** [comment]
You might have left the page without applying which doesn't store the state as you expected, hence coming back repopulates them.

However, OP is saying that within the same 'session' (so no leaving or coming back the page), resetting the filter and applying again doesn't work as expected but that is in my tests.

**Comment by rhukster** [comment]
Ah yes, had not applied in that use case. After apply it does save the reset state.
