### ISSUE TITLE
Update to v1.6.22 does not work

### ISSUE THREAD

**Issue by petira** [getgrav/grav-plugin-admin#1847]
![1](https://user-images.githubusercontent.com/38700805/76072341-18905000-5f98-11ea-8c8a-69f653d3b6e4.png)
![2](https://user-images.githubusercontent.com/38700805/76072350-1f1ec780-5f98-11ea-8113-e3f47ee14ea3.png)

`Error while trying to download (code: 0): https://getgrav.org/download/core/grav-update/1.6.22 Message: URL using bad/illegal format or missing URL malformed`

Grav v1.6.21 - Admin v1.9.12 - PHP Version 7.3.6

Also issue #1843 still persists.

**Comment by rhukster** [comment]
If this is the same issue as posted on Discord, switching from 'curl' to 'fopen' resolved it for this user.
