### ISSUE TITLE
Cannot preview modular content in editor

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#185]
All my modular pages are listed:
![list](https://cloud.githubusercontent.com/assets/12480617/9933788/ae1be8f2-5d4d-11e5-91ae-71775a724702.png)
After editing I press preview and the associated twig file is not found:
![message](https://cloud.githubusercontent.com/assets/12480617/9933831/2597f768-5d4e-11e5-8934-5df4f973203c.png)

**Comment by rhukster** [comment]
You can't preview a modular sub page because they are not routable, and are not intended to be viewed individually, only in the whole modular page.  I'm not sure if there's anything I can do to fix this short of removing the preview button on these modular pages, but I will have a look.

**Comment by flaviocopes** [comment]
We should probably remove the preview on modular pages, and also (related to the topic of editor buttons) when on the preview, disable/gray-out the other *action* buttons

**Comment by rhukster** [comment]
I actually have a workaround that lets you preview this.. Of course if your modular template relies on something else from the parent page, it could have weird effects, but at least most of the time it will work now.

**Comment by axel-rank** [comment]
Thanks, was just writin...Maybe it's possible to show the whole modular page in preview?
Preview of what I'm editing  is a 'must have' in my opinion, especially as long there is no 'Version Feature' of Content to quickly rollback to a previous version of the article.

**Comment by rhukster** [comment]
Actually the long-term solution is to rework how modular pages are built with a completely different UI.  Something more akin to a top level modular page where you can add modular subpage sections to this page, and they all display on the main modular page. 

This is compared to handling modular sub-pages like regular pages as we do now.
