### ISSUE TITLE
Instalación relentiza el navegador

### ISSUE THREAD

**Issue by jhmorenof** [getgrav/grav-plugin-admin#1854]
Instale el usuario administrador la pagina es elnta y no hay desplazamiento (barra lateral) luego  habilite seguridad 2FA, Luego no puede volver a ingresar.
Well hice una nueva instalación  y es muy lenta la pagina por ejemplo no puedo abrir el vinculo a lenguaje ni las plantillas, ni nada ...Solo esta pagina se vuelve lenta y no hay desplazamiento ni abajo ni arriba. no puedo cambiar templates...estoy  bloqueado

**Comment by rhukster** [comment]
English please....

**Comment by DannyJJK** [comment]
Translation:
I installed the admin user, the page is slow and there's no scrolling (sidebar), I then activated 2FA security, then I couldn't sign in.

I made a new installation and the page is very slow, for example I can't click the "Language" link, or the templates, or anything. The page is slow and there's no upwards or downwards scrolling. I can't change templates, I'm stuck.

**Comment by rhukster** [comment]
Sounds like same issue: https://github.com/getgrav/grav-plugin-admin/issues/1855
