### ISSUE TITLE
el mause no  funciona

### ISSUE THREAD

**Issue by jhmorenof** [getgrav/grav-plugin-admin#1855]
el mause no  funciona en los  vinculos de la pagina... Install theme  no vincula, hago clic  y no  hace nada

**Comment by rhukster** [comment]
English please....

**Comment by DannyJJK** [comment]
Translation: The mouse doesn't work on the page links. "Install theme" is not linked, I click it and nothing happens.

**Comment by rhukster** [comment]
Sounds like JS broken.. Possible some plugin is causing this.. check your devtools in your browser it might give an error and reference a file in a particular plugin.  Try disabling any plugin  'admin' related that is not the core admin plugin.

**Comment by DannyJJK** [comment]
Traducción: Parece que el JavaScript no funciona en la página. Es posible que un plugin esté haciendo que suceda. Echa un vistazo a las herramientas para desarrolladores del navegador, puede mostrar un error y hacer referencia a un archivo de un plugin en particular. Intenta desactivar cualquier plugin relacionado con el admin, excepto el admin plugin del Grav.
