### ISSUE TITLE
botones no funcionan

### ISSUE THREAD

**Issue by jhmorenof** [getgrav/grav-plugin-admin#1856]
Botones de crear pagina  instalar temas, plugins y muchos  botones  no  funcionan en mi pagina

**Comment by rhukster** [comment]
English please....

**Comment by DannyJJK** [comment]
Translation: The buttons "create page", "install theme", and many more don't work on the page.

**Comment by rhukster** [comment]
Sounds like same issue: https://github.com/getgrav/grav-plugin-admin/issues/1855
