### ISSUE TITLE
Admin v1.10 RC8 - Issue re: Mac visible scrollbars has returned?

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#1857]
On a Mac, with all Browsers, there is an issue of the Page panel never loading:

![2020-03-20_10-34-52 (1)](https://user-images.githubusercontent.com/1812771/77193988-5747ff00-6a9c-11ea-850d-29b009d5a65e.gif)

Here is Chrome console error:
<img width="1539" alt="2020-03-20_10-57-23" src="https://user-images.githubusercontent.com/1812771/77194543-68454000-6a9d-11ea-8062-e7ca42840f29.png">

And FF console error:
<img width="1192" alt="2020-03-20_10-58-09" src="https://user-images.githubusercontent.com/1812771/77194533-624f5f00-6a9d-11ea-8456-58e649ac085a.png">

Please let me know if any more info is helpful etc.

Thanks,
Paul

**Comment by w00fz** [comment]
Fixed with https://github.com/trilbymedia/grav-plugin-flex-objects/commit/5281cd71f1e587a17a89d7e0a0123ffeedee3c40

**Comment by paulhibbitts** [comment]
Thanks so much @w00fz , break-neck speed 🙂

**Comment by rhukster** [comment]
Flex-Objects 1.0.0-rc.9 has been released and should show up in GPM within the hour: 

https://github.com/trilbymedia/grav-plugin-flex-objects/releases/tag/1.0.0-rc.9
