### ISSUE TITLE
Error while trying to download

### ISSUE THREAD

**Issue by ZteamDL** [getgrav/grav-plugin-admin#1861]
![fefsf](https://user-images.githubusercontent.com/59402172/77378660-dd06cb80-6d76-11ea-877f-c11b5d3af8b4.PNG)

Is there any way to fix that?

**Comment by rhukster** [comment]
try changing the `gpm.method` option in system.yaml.  It tries curl first, then fopen, but you can force one or the other.  Try forcing `fopen` and see if that works.

**Comment by TomPecs** [comment]
same to me :\ any plugin // have a feeling host/php settings problem limitation....

**Comment by TomPecs** [comment]
![image](https://user-images.githubusercontent.com/59783091/77469847-9d3bf480-6e07-11ea-95c0-057af6f0d39e.png)

**Comment by rhukster** [comment]
If that's working for you then that means there's a problem with Curl on your server machine.

**Comment by rhukster** [comment]
duplicate of https://github.com/getgrav/grav-plugin-admin/issues/1847
