### ISSUE TITLE
Error when deleting pictures from a plugins file field

### ISSUE THREAD

**Issue by ruben-vb** [getgrav/grav-plugin-admin#1866]
When I upload a Picture to a file field of a Plugin, deleting it causes the following error:

Undefined property: stdClass::$destination

The picture disappears from the backend but the file itself does not get deleted.

This occured on at least the following versions of grav/the plugins:

grav 1.6.23/22
admin 1.9.13
form 4.0.6/5
PHP Version 7.2.10 (if relevant)

Im not entirely sure if its the admin or form plugin.
On another system it was working for Grav 1.6.17 with admin 1.9.7 and form 3.0.x.

**Comment by rhukster** [comment]
Is it a specific plugin or one you are building?

**Comment by ynn1k** [comment]
We noticed this error in a plugin we are building. But we also tested it with the [AboutMe ](https://github.com/Birssan/grav-plugin-about-me) plugin on different systems. 
On an older system the error occured after updating to Grav v1.6.23 - Admin v1.9.13 (just checked it - Form plugin is still on v3.0.6)

**Comment by w00fz** [comment]
Can you try with Grav 1.7 and Admin 1.10? There's been quite a lot of changes in the media field zone. Wouldn't be surprised if this is resolved there.

**Comment by ynn1k** [comment]
seems solved. Tested on Grav v1.7.0-rc.17 - Admin v1.10.0-rc.17 and also on Grav v1.6.28 - Admin v1.9.17
