### ISSUE TITLE
Admin v1.10.0-rc.8 – Media upload: onAdminAfterAddMedia?

### ISSUE THREAD

**Issue by clivebeckett** [getgrav/grav-plugin-admin#1867]
My [Admin Addon Media Metadata Plugin](https://github.com/clivebeckett/grav-plugin-admin-addon-media-metadata) is making use of the event hook `onAdminAfterAddMedia` to create a `[mediafile].meta.yaml` file for each newly uploaded media file with empty values for title, alt, and caption.

In Admin v1.10.0-rc.8 that doesn’t work anymore since files are being stored in a tmp folder and moved to the page folder only on saving the page.

1. Is the event hook `onAdminAfterAddMedia` still being fired? If not, what’s the alternative?
2. What is the reason for the temporary storage? First I thought this is to make uploading possible for new pages – but you still have to save a new page once, before being able to upload media files.

See also the issue _Limited functionality in Admin Plugin v1.10.0-rc.8_ in my plugin’s repository: clivebeckett/grav-plugin-admin-addon-media-metadata#7

**Comment by mahagr** [comment]
Regarding to why temporary location is being used:

Using temporary files before saving has multiple benefits, including that you can upload files on new pages and that your pages won't be broken while you are modifying them. This means that frontend will not change until you hit save.

This also means that all the media will be added/removed at once during the save.

I need to check if `onAdminAfterAddMedia` is still being called.

**Comment by clivebeckett** [comment]
> Using temporary files before saving has multiple benefits, including that you can upload files on new pages and that your pages won't be broken while you are modifying them. This means that frontend will not change until you hit save.

Thank you! So I wasn’t completely wrong about this being a feature to make upload for new pages available – only it isn’t yet working but probably in the final release. The other reason – not breaking pages while still editing them – also makes sense, I guess :)

So I’m excited to see how I can make my plugin work properly again.

**Comment by mahagr** [comment]
@clivebeckett 

I've now reverted the behavior of the `pagemedia` field to act just as it used to be in Grav 1.6. This is because of it is too large behavioral change and breaks multiple things. I have also fixed a few issues in file/image fields, so they should be used instead of `pagemedia` as they work also when creating a new page/object.

We may need to figure out how to add more metadata to the updated files, I think it should happen when you're uploading the file...?

**Comment by clivebeckett** [comment]
> I've now reverted the behavior of the `pagemedia` field to act just as it used to be in Grav 1.6. This is because of it is too large behavioral change and breaks multiple things.

Thanks, that sounds like good news to me :)

> I have also fixed a few issues in file/image fields, so they should be used instead of `pagemedia` as they work also when creating a new page/object.

I don’t quite know what that means. But I’ll check once the next release is out.
 
> We may need to figure out how to add more metadata to the updated files, I think it should happen when you're uploading the file...?

I’m not sure here either what you mean, I’m sorry. My plugin now creates the metadata file when you save data for the first time using the provided modal. Later on, the metadata will be overwritten by saving the form. There’s no creating an empty metadata file anymore, also because this got in the way with the automated EXIF data writing as provided by the core (setting `media.auto_metadata_exif`).

**Comment by mahagr** [comment]
Let's try out if everything works with this fix. If there are more issues, please just create a new issue about it.
