### ISSUE TITLE
Change order of pages

### ISSUE THREAD

**Issue by dkophelyi** [getgrav/grav-plugin-admin#1868]
Is it possible to change the order of the pages and child pages?
If i open any page and click on Move button, the popup window stuck on loading.

**Comment by ricardo118** [comment]
you can change the order of pages on admin via the Advanced Tab.

Check the following picture:

![image](https://i.imgur.com/3DI3Nvh.png)

Use the button "enable Folder prefix" to add a page to the sortable group, then you can drag them as you wish
