### ISSUE TITLE
Invalid input in "Parent"

### ISSUE THREAD

**Issue by PraserX** [getgrav/grav-plugin-admin#1869]
In expert view page cannot be saved, event if nothing changed. It seems that the Parent input field is empty by default. After adding Parent again, page could be saved. There is no bug if user switch to normal view.

Admin plugin version: v1.10.0-rc.8 (grav-admin-1.7.0-rc.8 default installation)

![Screenshot_2020-04-18 Typography Grav](https://user-images.githubusercontent.com/24474722/79645437-a7a3a100-81af-11ea-8b70-1cc5d56891c6.png)

**Comment by mahagr** [comment]
Value can be saved if it is updated. Hmm.

**Comment by mahagr** [comment]
An empty field is an alias of the root page, so made field optional as it is in `default.yaml`.
