### ISSUE TITLE
getimagesize(): corrupt JPEG data: XX extraneous bytes before marker

### ISSUE THREAD

**Issue by adamwlewis** [getgrav/grav-plugin-admin#1874]
I have two grav websites within the same hosting environment (literally, same cPanel). One of them is using the Clarity theme, the other is using the default "blank" theme uncustomized at this point.

To the best of my ability, the sites appear to be configured 100% the same from a PHP standpoint.

95% of all jpg images trying to be uploaded through the blank theme into a page's media area result in this error: getimagesize(): corrupt JPEG data: 17 extraneous bytes before marker (17 for this particular one).

I can take the exact same image, however, and load it into a page in the Clarity theme and it works fine.

Any ideas what would be causing it on the blank theme or what configuration the theme could be changing?

**Comment by rhukster** [comment]
I really have no clue!  Never heard of anything like this especially on the same server. 

I would say compare the `config/system.yaml` settings on each server.  Also the `.htaccess`. It does sound like some kind of gzip, compression, or some other webserver type manipulation.

**Comment by mahagr** [comment]
Maybe you should check the first 17 bytes if there's some extra data being appended to the files by server(?) or something else.
