### ISSUE TITLE
Error while trying to download (code: ): https://getgrav.org/notifications.json?1588009582

### ISSUE THREAD

**Issue by MattAppleton** [getgrav/grav-plugin-admin#1875]
One of the sites we look after (thames-sidestudios.co.uk) has recently started to encounter this error when doing things in the admin... ie saving pages, amending plugins etc.

`Error while trying to download (code: ): https://getgrav.org/notifications.json?1588009582`

<img width="389" alt="Screenshot 2020-04-27 18 50 28" src="https://user-images.githubusercontent.com/6295710/80403765-0f48a300-88b8-11ea-85f9-b9eb2a5aa1d0.png">

The admin itself seems to be going veeeery slowly too.

Any ideas?

many thanks

**Comment by MattAppleton** [comment]
If I turn off Notifications and News feed in the admin plugin (and enable Admin caching) we still see sluggish behaviour and other error messages such as

`Error while trying to download (code: ): https://getgrav.org/blog.atom`

**Comment by MattAppleton** [comment]
<img width="691" alt="Screenshot 2020-04-27 18 56 54" src="https://user-images.githubusercontent.com/6295710/80404322-f096dc00-88b8-11ea-9856-3a3eaaa8f10b.png">

**Comment by ricardo118** [comment]
could you test switching to curl from fopen/auto in system config?

**Comment by MattAppleton** [comment]
Will do...

**Comment by MattAppleton** [comment]
OK, it was on 'auto' in `system/config/system.yaml`

now set to `fopen`

Still incredibly sluggish, but that may be my connection (does viewing the admin panel impact upload speeds?)

And no discernible change so far... still getting red warnings about notifications.json not loading, whether the dashboard widgets are switched on or not in the admin plugin settings...

**Comment by MattAppleton** [comment]
I am still getting this kind of warning popping up...

<img width="1249" alt="Screenshot 2020-04-28 20 44 05" src="https://user-images.githubusercontent.com/6295710/80530584-23ac9e80-8991-11ea-9e13-ddc8b38d6876.png">

**Comment by rhukster** [comment]
Try curl?

**Comment by MattAppleton** [comment]
Apologies for the delay closing this @rhukster  — curl does the trick... thanks... wondering what has prompted this changed behaviour in the recent Grav updates...? Would it make sense to default to curl from now on?

**Comment by dcrobertson01** [comment]
Sorry - maybe I am a bit dense, but which setting to I change to curl? Is that the 
Cache:
    driver ?
