### ISSUE TITLE
Update from Grav v1.6.17 to 1.6.24 > Invalid AJAX response : Error while trying to download (code: 0) 

### ISSUE THREAD

**Issue by lucieduverger** [getgrav/grav-plugin-admin#1878]
Hi everyone,
I get this error message trying to update my Grav v1.6.17 to 1.6.24.

> Error while trying to download (code: 0): https://getgrav.org/download/core/grav-update/1.6.24 Message: URL using bad/illegal format or missing URL malformed

Could you please help me :)
Tx in advance.

**Comment by rhukster** [comment]
Duplicate: https://github.com/getgrav/grav-plugin-admin/issues/184

**Comment by lucieduverger** [comment]
> Duplicate: #184
Tx for helping but I really don’t see what is similarity with Questions 184
Are you sure you mentionned the right issue? Maybe #1847 would be more relevant...

**Comment by ricardo118** [comment]
try switching  'curl' to 'fopen'

**Comment by lucieduverger** [comment]
Whaou ! Is this a place where people forget about politesness and speak without proper sentences? LOL
So... Hi and thank you Ricardo118 for your attend to reply.
I don't understand a word of your switching thing.
You should not have to deal with technical issues when you just try to click on the upgrade button from the admin consol, don't you think?
If you could be more precised, I would appreciate.
Thanks in advance

**Comment by ricardo118** [comment]
Yeah ideally we would not have any issues when upgrading from admin console. However, there's many different kinds of hosting out there and sometimes some hosts allow things other do not.

The option I was talking about is this:
https://learn.getgrav.org/16/basics/grav-configuration#gpm

Specifically this:
`method: Either 'curl', 'fopen' or 'auto'. 'auto' will try fopen first and if not available cURL`

Grav does attempt auto first but like i said again, sometimes some hosts/setups just dont work. You can also change this option in the system configuration via admin. Should be pretty easy to spot 

![image](https://i.imgur.com/JLBNaZz.png)

**Comment by lucieduverger** [comment]
Hi Ricardo, tx for your explanation. I tried what you suggested but it is still the same.
I'm hosted on a shared server but already updated my site a few times without any issues.
Can I upgrade manually? Or would it be easier to reinstall it?

**Comment by lucieduverger** [comment]
Hi. Sorted. Php version was obsolete. I upgraded it and now it works fine. I was able to update with normal setting :) Tx for your help anyway
