### ISSUE TITLE
Can't install themes or plugins 

### ISSUE THREAD

**Issue by qbolaa** [getgrav/grav-plugin-admin#1879]
Hello every one 

I have Grav 1.7  and every time I try to install a new theme comes some red message "  Error while trying to download ( code: 0): https://getgrav.org/download/plugins/devtools/1.4.0 Message: URL using bad/illegal format or missing URL malformed "

 Have anyone a clue why this happens to me...

 Thank Rleal

**Comment by petira** [comment]
Solution: #1847
