### ISSUE TITLE
Login redirects to about:blank

### ISSUE THREAD

**Issue by yonas** [getgrav/grav-plugin-admin#188]
Clicking on the login button always redirects the page to about:blank.

I installed admin using `bin/gpm install admin`

Using Grav v0.9.43 and nginx 1.6.2

**Comment by rhukster** [comment]
Does your site work on the frontend? Specifically do subpages work?  As your running nginx, my first guess is that you don't have rewriting setup properly, so pages are not routing.  Did you configure your virtual host with something similar to the `nginx.conf` provided with the Grav package?

**Comment by yonas** [comment]
Yes, the frontend works and subpages work. I used the supplied nginx.conf as a template.

I tested subpages by creating user/pages/02.mypage and going to /mypage.

**Comment by rhukster** [comment]
OK, i could ask you a bunch of questions, but I could save a lot of time, if you zip up your `user/` and put that on dropbox and provide me a link.  That way i can quickly test and see anything obvious.  If it works for me, then its a server issue, if it doesn't its most likely a config issue.

**Comment by yonas** [comment]
Don't have dropbox, how about the old fashion way :) http://fizk.net/grav.zip

**Comment by rhukster** [comment]
Ok, so i was able to log in to the admin just fine running under Apache on my local mac setup, so it's not the Grav configuration/setup, per say, it's something related to your server configuration/setup.

Out of curiosity if you type the wrong username/pw, do you get redirected back to the login page with an error message?

**Comment by yonas** [comment]
It redirects to about:blank no matter what I enter as username/password, correct or incorrect. It feels like a Javascript bug. There's no network traffic in the Dev Tools Network tab during the redirect.

**Comment by rhukster** [comment]
Is there a JS error in your browser? What browser are you using btw?

**Comment by yonas** [comment]
I've been testing in Chrome, but in Firefox the behaviour is different. It redirects to "http://~^grav.%28/?%3Cdomain%3E.+%29.dev3$/admin", which is the domain name from nginx. That's probably what's causing the issue.

**Comment by rhukster** [comment]
I have this nginx.conf on my raspberry pi config.. it's pretty minimal, maybe try something like this:

```
server {
        #listen 80 default_server;
        index index.html index.php;
        root /home/pi/www/blog;

        server_name localhost;

        location / {
                try_files $uri $uri/ /index.html;
                if (!-e $request_filename){ rewrite ^(.*)$ /index.php last; }
        }

        location ~ \.php$ {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
        }
}
```

**Comment by yonas** [comment]
Thanks, that was the issue.

I've used other CMSes, like Wordpress and Drupal, and they don't have an issue with weird server names. The server name is a regular express:

http://nginx.org/en/docs/http/server_names.html

In my case:
`server_name ~^grav\.(?<domain>.+)\.dev3$;`

allows me to set the domain dynamically based on domain:
`root /var/www/grav-sites/$domain;`

There should be a way for us to tweak this plugin to make this work.

**Comment by rhukster** [comment]
i had not tested nginx in a while, but in my testing just now i am seeing a slight problem. It's not exactly the same as the one your seeing, but i need to fix it before i can test further (could be a setup config on my end).

**Comment by rhukster** [comment]
I'm afraid I don't really know too much about nginx.. so i've never used server_names for example.  it would be great to get some help with this.

**Comment by yonas** [comment]
For sure, I'm looking at the code right now. I'll let you know if I find anything.

**Comment by yonas** [comment]
Using a relative URL for the login form action seems to do the trick.

**Comment by rhukster** [comment]
Actually was my configuration was out of date.  Working for me too.

Regarding the `sever_name` The logic would need to be looked at it in the Uri class, it's not related to the admin plugin specifically.

Your PR fix is a good one for this usecase, but anytime you ask for the full URL, via the URI class, it will be a problem, so need to look there for the full fix.

**Comment by yonas** [comment]
Ok, sounds good :+1:

**Comment by rhukster** [comment]
I think i have a solution...

Change line 35 in `src/Grav/Common/Uri.php` to this:

```
$name = isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : isset($_SERVER['SERVER_NAME']) ? $_SERVER['SERVER_NAME'] : 'localhost';
```

Then simply test with the old login URL, hopefully it will use the nginx 'computed' name rather than the un-processed one.

**Comment by yonas** [comment]
Nice, that works, except the SERVER_NAME part needs to be wrapped in parentheses:

`$name = isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : (isset($_SERVER['SERVER_NAME']) ? $_SERVER['SERVER_NAME'] : 'localhost')`

**Comment by rhukster** [comment]
Yup good call. Will update and commit for next release.  Thanks!

**Comment by yonas** [comment]
Cheers! :beers:
