### ISSUE TITLE
adding a page with a +

### ISSUE THREAD

**Issue by yurii-a-lebedev** [getgrav/grav-plugin-admin#1882]
<img width="476" alt="image" src="https://user-images.githubusercontent.com/53998580/81353866-3f275000-90db-11ea-9796-be66370465b8.png">

when adding a page with the symbol + the page in the loop is duplicated

**Comment by ricardo118** [comment]
does this happen if you do not keep the `+` in the slug/folder field?

**Comment by yurii-a-lebedev** [comment]
unfortunately, the error could not be reproduced. thank

**Comment by yurii-a-lebedev** [comment]
<img width="288" alt="image" src="https://user-images.githubusercontent.com/53998580/81877724-e9e5b580-9596-11ea-820e-a1349fb46623.png">
is not deleted, the page exists until it is deleted in the console

**Comment by mahagr** [comment]
This is likely caused by `urlencode()` / `urldecode()` (or raw-variants) mismatching space and +.
