### ISSUE TITLE
Dashboard Statistics Have No Units

### ISSUE THREAD

**Issue by thekenshow** [getgrav/grav-plugin-admin#1885]
A client pointed out that the Statistics chart has no units for the Y axis and wanted to know if it was visitors or pageviews, unique or total. Good question! So I went to [the documentation](https://learn.getgrav.org/16/admin-panel/dashboard) which says its the "number of visitors the front end has received". 

But according to the Google Analytics data for this site, that's wrong - it lines up most closely with page views. I was going to request that units be added to the chart, but since there's only one metric being displayed it makes sense to rename it "Page Views" instead of "Statistics".

**Comment by w00fz** [comment]
Good point, this is now called Page View Statistics in admin (1.10) and I also updated the references in the docs.
