### ISSUE TITLE
Add Support for Custom Fonts in Admin Plugin

### ISSUE THREAD

**Issue by OrthoCube** [getgrav/grav-plugin-admin#1886]
Depending on the language, a different font might be needed to display text in the Admin plugin. This becomes extremely important when editing posts written in said language.

This can be resolved by manually editing the compiled CSS in the plugin files and adding the `@import` to the Web Font, and then editing the font-family value to include the new font.

However, this is not user-friendly and this change will be lost when the Admin plugin is updated.

If possible, it would be great if a special CSS file that will not get overwritten when updating the Admin plugin will be included by the Admin plugin automatically to its default CSS styles. This special CSS file can be edited by users and customized to their need to override certain parts of the default CSS.

Another option will be to add a section in the settings menu to be able to directly add font `@import`s dynamically and then be able to edit the default font-family via the same settings menu.

I'd be very glad if someone can point me to the right direction on how to implement this myself so that I can submit a pull request, as I am not familiar with the Grav plugin system (nor the Admin plugin codebase). If someone can do it well, it would be better if the knowledgeable person would help fix this issue, though :D

I would really appreciate any help regarding this.

Thanks in advance!

**Comment by rhukster** [comment]
This can be achieved in Grav 1.7/Admin 1.10 which is currently in RC. There's a custom CSS field in the Plugins->Admin->Customize tab where you could override the default font stack with a custom one.

**Comment by OrthoCube** [comment]
Wow, that's unbelievably awesome!

Thanks, will patiently wait until 1.10 gets released (or maybe I already have it since I'm using testing plugins...?)

**Comment by mahagr** [comment]
I think it's safe to use the RC releases if you just remember to test that everything in your site works. There are still some issues (or special cases, backwards compatibility etc) which we need to fix before getting the stable release out.
