### ISSUE TITLE
[RC-11] Customization Logo upload instructions hard to read 

### ISSUE THREAD

**Issue by kiranetph** [getgrav/grav-plugin-admin#1887]
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/15226809/81993978-6ea90000-9679-11ea-95b2-acb28f05bcb4.png">

**Comment by kiranetph** [comment]
re-saving the "default" preset fixed it.

**Comment by rhukster** [comment]
Also clearing cache will do it too... as that removes the generated `preset.css` and forces a recompile
