### ISSUE TITLE
FETCH_HEAD fatal: refusing to merge unrelated histories

### ISSUE THREAD

**Issue by mrtngrsbch** [getgrav/grav-plugin-admin#1893]
Hi guys,

- I have a new installation [Grav v1.6.25 - Admin v1.9.14]
- I install `bin/gpm install git-sync`
- I carefully follow the installation steps of the video "Up and Running in 2 mins" [https://github.com/trilbymedia/grav-plugin-git-sync]
- And I receive this error: "From https://github.com/mrtngrsbch/GLAM-grav-test * branch master -> FETCH_HEAD fatal: refusing to merge unrelated histories"

Perhaps, as a reference, I have executed:
`$ bin/plugin git-sync sync`
and I received this error:
`PHP Fatal error:  Uncaught Error: Class 'Grav\Plugin\GitSync\GitSync' not found in /home/grav/public_html/user/plugins/git-sync/cli/SyncCommand.php:25
Stack trace:
#0 /home/grav/public_html/system/src/Grav/Console/ConsoleCommand.php(41): Grav\Plugin\Console\SyncCommand->serve()
#1 /home/grav/public_html/vendor/symfony/console/Command/Command.php(255): Grav\Console\ConsoleCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /home/grav/public_html/vendor/symfony/console/Application.php(917): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/grav/public_html/vendor/symfony/console/Application.php(269): Symfony\Component\Console\Application->doRunCommand(Object(Grav\Plugin\Console\SyncCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/grav/public_html/vendor/symfony/console in /home/grav/public_html/user/plugins/git-sync/cli/SyncCommand.php on line 25`

Sorry I'm a little lost with this setup

best

**Comment by ricardo118** [comment]
looks like the git is having issues because of unrelated histories. Was the git already there or a new empty git? Might wanna try to fix the git issues with CLI first then running the git sync

**Comment by rhukster** [comment]
Please create an issue at https://github.com/trilbymedia/grav-plugin-gitsync
