### ISSUE TITLE
Plug in Drug and Drop 

### ISSUE THREAD

**Issue by sergio-dotcom** [getgrav/grav-plugin-admin#1895]
Buonasera, ho iniziato da pochissimo ad utilizzare grav.. sono passato da website x5 pro 19 per varie rogne..
Volevo chiedere se era disponibile un plug in che possa avere questa funzione o in parte

Grazie

**Comment by rhukster** [comment]
english please :)

**Comment by w00fz** [comment]
Salve,

Grav does not have any kind of official page builder and I'm not aware of any 3rd party Grav plugin that does it. The closest thing you can find is [Gantry](http://gantry.org/) which has a Layout Manager that allows organizing blocks of your page via drag and drop.

Hope this helps!
