### ISSUE TITLE
Josefin Slab?

### ISSUE THREAD

**Issue by manuchan** [getgrav/grav-plugin-admin#1898]
In `grav-plugin-admin/themes/grav/scss/fonts.scss`
```
$font-definitions: (
    Josefin+Slab: 400,
    Roboto: '300,400,500',
    Inconsolata: '400,700'
);
```
Should it be `'Josefin Slab': 400,` ?
Otherwise it won't pass the if clause in `@function admin-font-faces` in `grav-plugin-admin/themes/grav/scss/configuration/fonts/_support.scss`

**Comment by rhukster** [comment]
probably.. will change
