### ISSUE TITLE
[Admin 1.10] Changing a modular page template does not work

### ISSUE THREAD

**Issue by clivebeckett** [getgrav/grav-plugin-admin#1899]
Changing a page template of a modular in the editing form (Advanced → Page Template) does not work. A second markdown file named after the newly selected template will be created next to the old markdown file.

Assuming you have the following modular templates:
`/user/themes/yourtheme/templates/modular/mod1.html.twig`
`/user/themes/yourtheme/templates/modular/mod2.html.twig`

And a modular page file
`/user/pages/01.page/01._modular/mod1.md`

Changing the template in the form will result in
`/user/pages/01.page/01._modular/mod1.md`
`/user/pages/01.page/01._modular/mod2.md`
with `Mod1` selected in the form again after submitting the change.

This problem does not occur in regular pages, only in modulars.

**Comment by rhukster** [comment]
I think i ran into this already, have you tried the latest github 1.10 branch? might already be fixed.

**Comment by clivebeckett** [comment]
> I think i ran into this already, have you tried the latest github 1.10 branch? might already be fixed.

Thank you! I tested it and the same issue still happens. I hope I did everything correctly though with cloning and checking out. This is `git status` in the `user/plugins/admin` folder

```
MyComputer:admin clive$ git status
On branch 1.10
Your branch is up to date with 'origin/1.10'.
```
