### ISSUE TITLE
Active Materialize Theme causes displace of dashborard items

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#190]
Installed and activated materialize theme -->result:
![screenshot](https://cloud.githubusercontent.com/assets/12480617/9963627/7756a00c-5e2c-11e5-8e31-c3e9e20b2666.png)
![screenshot2](https://cloud.githubusercontent.com/assets/12480617/9963772/2e9cfd6a-5e2d-11e5-8ab4-c41f355ca68d.png)

Not sure if it's an admin panel or marerializetheme issue.
Other themes work.

**Comment by rhukster** [comment]
Well definitely seems to be related to materialize theme. Must be loading some CSS in the admin side?

**Comment by rhukster** [comment]
Please create an issue on the materialize repo.  If it turns out to be admin related (unlikely) we can open this back up. https://github.com/bobrocke/grav-theme-materialize/issues
