### ISSUE TITLE
If I call the page _mymodule.md the YAML file in the theme with configuration of the module is not taken into consideration.

### ISSUE THREAD

**Issue by bu3tt1** [getgrav/grav-plugin-admin#1900]
If I call the page _mymodule.md the YAML file in the theme with configuration of the module is not taken into consideration.

My actual configuration:
```bash
user/pages/01.home/
|-- modular.md
|-- 01._mymodule
  |-- mymodule.md
```
```bash
themes/mytheme/blueprints/modular
|-- mymodule.yaml
```
Everything works well, in fact the configurations of the backend defined in the YAML I see them in the admin page.

_Originally posted by @bu3tt1 in https://github.com/getgrav/grav-plugin-admin/issues/1884#issuecomment-628518346_

**Comment by rhukster** [comment]
What do you mean 'call the page _mymodule.md` ?

**Comment by w00fz** [comment]
Please have a look at the Modular documentation https://learn.getgrav.org/16/content/modular
