### ISSUE TITLE
Images on Multisite

### ISSUE THREAD

**Issue by ironbrunet** [getgrav/grav-plugin-admin#1902]
I have just duplicated the folder admin :
/domain/user/sites/subdomain/plugins/admin
and surely handle the folder config :
/domain/user/sites/subdomain/config

All is working ! except the uploaded files as the image .....
The system always save the image to the /domain/user/themes/gateway/img instead of /domain/user/sites/subdomain/themes/gateway/img

Following this, a subsidiary question a little bit out of scope : 
Is there a way to give a destination depending on if it's a "settle site" or the subdomain ?
main site : destination: 'user/themes/gateway/img'
subdomain : destination: 'user/sites/"subdomain"/themes/gateway/img'

something like destination: 'site@:/img' ? or with the streams ?

_Originally posted by @unmick in https://github.com/getgrav/grav-plugin-admin/issues/1315#issuecomment-359770104_

Was this ever resolved? Having the same issue.

**Comment by mahagr** [comment]
After reading this issue a few times and trying it myself, I don't think this is a bug at all. As your multi-site setup has overrides in the subfolder (it can be prevented in the multi-site setup), the file gets saved where it should. To access the file, you need to use stream `theme://img/filename.jpg` or fix the multi-site configuration not to use the subdomain to save the theme files.
