### ISSUE TITLE
bug: empty metadata causes deleting all other already set metadata of a page

### ISSUE THREAD

**Issue by markushuebner** [getgrav/grav-plugin-admin#1906]
If you add metadata within the options section of a page and fill in e.g.
```
keywords | lorem, ipsum, dolor
description | my example text
```
everything works fine after saving. The entered data is still set in backend and implemented in frontend. But if you leave the content of the last item blank, e.g. for an added
`author | `
and save your edited information, all metadata items of this page will be deleted and you will have to start over again. Neither in backend nor in frontend the previously set information for keywords and description are contained anymore.

This only happens, when the last (!) item does not have content. If you don't fill in content for the first item or another (except the last one), only the empty item will be deleted.

additional information:

- os: windows 10
- xampp, localhost
- Grav v1.6.26 - Admin v1.9.15
- php version 7.4.6
- theme: quark 2.0.3
- installation: nearly "naked" install via grav core and admin plugin, following the instructions [https://learn.getgrav.org/16/content/headers](url)

**Comment by w00fz** [comment]
Thanks you for the very thorough description of the issue and the state of your system. Really appreciate it!

This has been recently fixed with https://github.com/getgrav/grav-plugin-admin/commit/ed8f24a8e77eae4e87cd53f5964658da3c473918 (see also #1972)
