### ISSUE TITLE
Ability to remove Default from dropdown

### ISSUE THREAD

**Issue by lufog** [getgrav/grav-plugin-admin#1908]
Remove **Default** from dropdown
![image](https://user-images.githubusercontent.com/10379487/84926815-9f46e400-b0d4-11ea-946f-efc637f69156.png)
and message from edit page
![image](https://user-images.githubusercontent.com/10379487/84927293-4b88ca80-b0d5-11ea-97c9-b1e43cbbe16e.png)
if **Configuration/Languages/Include default language in file extension** is enabled.

**Comment by ricardo118** [comment]
this is to do with flex pages, i too am not 100% sure how the default is supposed to work

**Comment by mahagr** [comment]
Default is supposed to show you file without language suffix. It is mostly there because of otherwise there's no way to access those files from admin. That said, I've run into this issue myself and it may be a good idea to hide the Default language by default and only display it when needed.

**Comment by mahagr** [comment]
Fixed in https://github.com/trilbymedia/grav-plugin-flex-objects/issues/47
