### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Trying to access array offset on value of type null").

### ISSUE THREAD

**Issue by steeve-legal** [getgrav/grav-plugin-admin#1909]
Hello, 
    
     Just made a fresh local  install of Grav 1.6.26 with apache2, composer and php 7.4
and got 1 error message when I attempt to go through my admin page to see template page and/or plugins page.

Error message is :
 Twig \ Error \ RuntimeError
An exception has been thrown during the rendering of a template ("Trying to access array offset on value of type null").

Didn,t find any issue related or explained about it and rather to say this is completely new for me.

Did I made something wrong ?

Best regards

**Comment by rhukster** [comment]
What steps did you follow to install?  Also if you download the 'prebuilt package' from https://getgrav.org/download/core/grav/1.6.26, does it's work?

**Comment by steeve-legal** [comment]
I followed those steps exactly, then upgraded php to 7.4.7

https://websiteforstudents.com/install-grav-cms-with-composer-on-ubuntu-16-04-18-04-and-apache2-and-php-7-2-support/

Things seems to work fine excepted mentioned above.

Thanks for your quick reply.

**Comment by steeve-legal** [comment]
![Screenshot_2020-06-20 Crikey There was an error ](https://user-images.githubusercontent.com/48728759/85193703-338f9180-b2f5-11ea-9f3e-b2d49aa498ce.png)
![Screenshot_2020-06-20 Crikey There was an error (1)](https://user-images.githubusercontent.com/48728759/85193706-35595500-b2f5-11ea-92c6-fdcc8daee645.png)

Here is the result when I am trying to reach respectively plugins and themes

**Comment by steeve-legal** [comment]
Hello,
   When I've made this install everything was successful excepted a warning not to use sudo with composer (huge breach opened) which is impossible not to use sudo when all is in var/www folder unless rights given to all users ...

**Anyway I've made again a new fresh local install without composer and now this is working properly.**

Sorry to bother you ... My apologizes

**Comment by mahagr** [comment]
I still think this is a rare issue you can run into, so I'm going to keep this open.

**Comment by replayshot** [comment]
I've run into this as well, but not after install. 
It works perfectly fine on my localhost, but when uploaded to server, it bombs with this error. 

This is the line causing this: {% for tax,value in taxonomylist[taxonomy]|sort_by_key('value')|reverse %}

If I switch this to ksort instead, it works fine.  Any idea why this is happening?
