### ISSUE TITLE
Minor - Login expires, try to add new page, warning

### ISSUE THREAD

**Issue by webstationhq** [getgrav/grav-plugin-admin#1910]
Synopsis:

If you are logged in to the admin panel/pages/{some-random-page] and your login times out (and you fail to notice), and try to add a new page, clicking on the add button allows the new page dialog to appear. A user can fill in a new page name, the root page, template etc however when you click "NEXT", the "leave page without saving changes" warning comes up.

NOTE: I have only observed this with the top right hand side buttons.

![Screen Shot 2020-06-22 at 2 36 46 PM](https://user-images.githubusercontent.com/51736270/85337749-e0a11000-b495-11ea-9c6b-07aa70f5092f.png)

Cause:

By default, Grav redirects users to the login page to re authenticate.
Fix:

Add a test to the "add new page" button to detect login first and redirect user to authenticate first prior to adding the button.  Maybe something like this:

{% if grav.user.access.admin %}
{# add the "add" page button or change it's color, whether it is enabled, add an alert to the user letting them know they are not time in. etc #}
{% endif %}

Why:

Our staff sometimes have numerous grav tabs open on multiple local and remote sites during the day.  Occasionally this happens and it is not clear what caused it. Although the user can make only minor changes prior to being redirected to the login page, it may be good to make this change for all potential similar functions.

To reproduce:

Access Grav admin
go to pages menu and select any page
let session expire
click "add" on top right hand corner to add a new page
fill in new page dialog and click next

Grav tries to redirect, the event listener picks up on unsaved changes and warns you.

**Comment by webstationhq** [comment]
IF you wish, I can implement a fix.

**Comment by ricardo118** [comment]
admin should have a keepalive function running that doesnt time you out. is it not working for you?

**Comment by webstationhq** [comment]
Aha!  Did not see this or know about it.  Thank you.  Should I close this or is it worthwhile thinking there may be others out there who may experience the same behavior and possibly provide them with this data?  Maybe an sentence on the login dialog? Otherwise, feel free to closet this with no action.

**Comment by rhukster** [comment]
I think the keepalive resolves this issue 99% of the time.
