### ISSUE TITLE
Loading list takes very long time

### ISSUE THREAD

**Issue by Jakub-Nagy** [getgrav/grav-plugin-admin#1912]
Hello,
I'm reposting this here from the Grav forum, because they forwarded me here. We are using a frontmatter form in the Grav Admin panel with a very large number of inputs (1000+).

It takes incredibly long time for it to load and interfacing with the form is very had. From our analysis, the form seems to firstly load the contents of the markdown using PHP. Then it uses JS to parse this data into HTML. We have all the list items collapsed by default, we only use them as fieldsets. But the current JS parses all of the internal list items as hidden items. We suspect that this unnecessary parsing is what takes such long time.

We would like to edit the JS function so that it only parses only the list items names, like this:
![image](https://user-images.githubusercontent.com/37936430/85854803-633b0f80-b7b5-11ea-9018-daf6436be326.png)

Only when you would click the uncollapse arrow, you would activate a JS which would parse that part of the form. That way the parsing shouldn’t take so long. Another solution would be to divide the list element into multiple pages.

The problem is that we cannot find the original JS functions which do this loading. Only thing we could find is **“admin.min.js”** which is minified so it doesn’t help us very much.

Could you please point us to the right direction? Thanks.

**Comment by ricardo118** [comment]
@Jakub-Nagy what fields do you have in the list?

**Comment by Jakub-Nagy** [comment]
@ricardo118 all kinds of fields. Text box, markdown editor, file upload, selectize box, another list and another two text fields. Here is it:
![image](https://user-images.githubusercontent.com/37936430/85923523-fa729680-b88b-11ea-9140-dac4a9aa3252.png)

**Comment by ricardo118** [comment]
ur using two of the heaviest fields, editor and file repeated a ton over the page so its understandable it takes so long, id recommend using less intense fields to replace those  such as type: filepicker with on_demand: true and textarea instead of markdown editor. if you absolutely need to have those fields then id recommend using a flex directory to keep all this data in instead

**Comment by Jakub-Nagy** [comment]
@ricardo118 thank you very much. I looked into flex directory, then flex objects and finally Grav 1.7.0 which integrates all of this.

The flex objects is amazing and it's exactly what we wanted to develop! So thank you, I will play around with this.
