### ISSUE TITLE
Get Flex Objects from Grav API

### ISSUE THREAD

**Issue by Jakub-Nagy** [getgrav/grav-plugin-admin#1914]
Hello,
is there a way to get an array of Flex Objects from the Grav API and load them into a select field? I want to create a module, which contains the selected Flex Object, which can be then placed inside any page.

I would like to import the data using the **data-options** parameter. For example I use this for getting modular templates: 
`data-options@: '\Grav\Plugin\AdminPlugin::pagesModularTypes'  `

Thanks.

**Comment by ricardo118** [comment]
using what you are `data-options@: '\Grav\Plugin\AdminPlugin::pagesModularTypes' ` you setup a custom function in your theme or a plugin, and create the method that grabs and returns the flex objects you want

**Comment by Jakub-Nagy** [comment]
@ricardo118 I wanted to get the list of directories rather than a list of objects inside a specific directory. Nevertheless, your code helped us to make the code we needed. It looks like this:
`public function listFlexObjects() {
        $flex = Grav::instance()['flex'];
        $collection = $flex->getDirectories();

        $result = [];
        foreach ($collection as $key => $value) {
            $result[$key] = $key;
        }

        //dump($result);

        return $result;
    }
`
So thank you for your help, I'm closing the issue.
