### ISSUE TITLE
PLEASE UPDATE YOUR SETTINGS VIA ADMIN OR PAGE YAML

### ISSUE THREAD

**Issue by dmitriykipriot** [getgrav/grav-plugin-admin#1915]
Hi. How i can deletet "PLEASE UPDATE YOUR SETTINGS VIA ADMIN OR PAGE YAML" title from mobile version?

**Comment by rhukster** [comment]
Not sure what this is. Screenshot ?

**Comment by dmitriykipriot** [comment]
![Снимок](https://user-images.githubusercontent.com/67556796/85955373-f5067080-b99f-11ea-9e4f-3f2bfc396528.JPG)

**Comment by rhukster** [comment]
Must be coming from a 3rd party plugin.  This string does not exist in Grav itself, nor in any of the plugins I have installed in my test site (nearly 40 of our core plugins).

probably simplest just to search your site (vscode, grep, etc) for the string: "please update your settings via admin or page yaml" with case sensitivity off.

**Comment by dmitriykipriot** [comment]
but I don't have any plugins. only the Brilliant Resume theme is installed

**Comment by dmitriykipriot** [comment]
All these plugins were installed with the platform, but there are no others

**Comment by rhukster** [comment]
did you search your site for that string? has to be coming from somewhere, maybe the theme, or content?
