### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by PraserX** [getgrav/grav-plugin-admin#1916]
Hi, I have a problem with admin plugin and GPM. My website has no connection to the internet and there should be offline mode, but I still get this error: "An exception has been thrown during the rendering of a template ("GPM not reachable. Please check your internet connection or check the Grav site is reachable")." So is it possible to use Grav in internal network without internet connection (in previous version 1.6 everything was OK and everything worked)? Thanks

**Comment by NicoHood** [comment]
I think I also ran into this issue here https://github.com/getgrav/grav/issues/1237#issuecomment-722540799

Nevertheless I think the admin panel should work without internet.

**Comment by PraserX** [comment]
No internet connection also slowing down the admin interface (or it looks like that). So I "fixed" that adding `$ignore_exception = true;` to the [GPM method](https://github.com/getgrav/grav/blob/54dccd11ef0422d0e9bceccff372d8b54be7ce4e/system/src/Grav/Common/GPM/GPM.php#L483).

**Comment by NicoHood** [comment]
Yes, it slows down every call, as it always tries to connect to the grav page. There should be a cleaner way than just this hack.

**Comment by w00fz** [comment]
Thanks for your comments guys. This is handled better now in Grav 1.7 / Admin 1.10. The implementation was in place but it was indeed missing a few areas where it would still try and wait on a repository indexing.

I tested offline mode now and i could navigate and use the admin as if I was online. Of course you won't see pending updates, some gravatar images might look broken, but you can definitely save in Intranet mode.

**Comment by NicoHood** [comment]
@w00fz Nice! Will this fix get backported to grav 1.6?

**Comment by w00fz** [comment]
Done.

**Comment by NicoHood** [comment]
Nice! I do not see the commit in the git yet, but I might be missing it with all those different branches.
