### ISSUE TITLE
New Group Error 404

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav-plugin-admin#1917]
The only field required for a new Group is the "Group Name". Thre is no help, or hint, but if you type anything with a space like `My Group` it will error with a 404. I think this is because this field is intended to be a slug, but there is no validation or indication regarding this.

**Comment by rhukster** [comment]
Follow on to this.. related but not the same.. 

Trying to delete a Group from the "list" view results in: `Object layout 'delete' not found.`

**Comment by mahagr** [comment]
Fixed in https://github.com/getgrav/grav/commit/c060d1a36e97f912cc37165ba648c8cdbd470b96
