### ISSUE TITLE
how to change something in the CodeMirror code

### ISSUE THREAD

**Issue by skinofthesoul** [getgrav/grav-plugin-admin#1925]
Not sure if this is the right place to post, but the Grav discourse forum came up with nothing and this does seem to me to be a Grav Admin issue. So: I would like to try out some different options for the CodeMirror editor. The only place I could find that code (please tell me if I've missed something!) is in [themes/grav/js/vendor.min.js](https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/js/vendor.min.js). Apparently there are several third party javascript bits and pieces in there, and as it's minified, it's quite difficult to work with. (Also I don't know a lot of javascript really.)

So my question is, is there an easy way to change that CodeMirror code bit? I've been thinking of creating a plugin that checks the vendor.min.js file from Admin, cuts out the whole CodeMirror bit, and then inserts a different version with configured options. Sounds hacky though… but would that even work? How would I know where to start and stop cutting?

Your help is much appreciated!

**Comment by ricardo118** [comment]
what kind of change to codemirror are you looking to do?

**Comment by skinofthesoul** [comment]
[I posted about it in the CodeMirror forum](https://discuss.codemirror.net/t/how-to-markup-different-special-chars-differently-and-also-double-spaces/2505) – at the end of the day, what I want is to have double spaces and no-break spaces marked visually in the editor but also differently from soft hyphens or other special chars. When I've achieved that, I'll look for a way to easily insert configurable special chars, preferably as a list of buttons to click much like the formatting buttons. It is not clear to me yet how exactly I could make this work, but I think some form of access to the CodeMirror bits will be necessary?

**Comment by ricardo118** [comment]
i read your post and adding buttons to the editor is possible without needing to modify the actual codemirror source. Regarding the marker for spaces im not sure anyone has tried.

Regarding the cut out of codemirror:

Admin uses webpack to compile both its vendor.min.js and its main js file. You can see here the list of vendors in this array for the webpack config file [here](https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/webpack.conf.js#L7)

So how to create a new vendor.min.js in a clean way:

1. a plugin that has the same package.json that admin does and the same webpack.conf.js
2. The plugin also overrides admin template: `partials/javascripts.html.twig` and there you swap the url for the `vendor.min.js` from `{% do assets.addJs(theme_url~'/js/vendor.min.js', { 'loading':'defer' }) %}` to your plugin's replacement
3. modify the codemirror as you wished, then compile the vendor.min.js again in your plugin

**Comment by skinofthesoul** [comment]
Well first off, thank you for this very helpful reply! I have since thought some more about this, and I have come across two CodeMirror bits that might be better suited to the task (but I'm not sure…):

1. CodeMirror's [text-marking methods](https://codemirror.net/doc/manual.html#api_marker), possibly in conjunction with the [search addon](https://codemirror.net/demo/search.html) since it has a handy `find()` function,
2. the [.addOverlay method](https://codemirror.net/doc/manual.html#addOverlay).

Both sound like they were intended to mark configurable bits of text, which is basically what I want. The specialChars list only works for single characters and thus would not help me with marking double spaces. Plus, as a bonus, I wouldn't have to change anything in the CodeMirror js code either (except maybe with the search addon).

However, I can't seem to find the interfacing bits between Grav and the CodeMirror editor. I'll do my best to explain:

In my plugin folder, I put a copy of `plugins/admin/themes/grav/templates/forms/fields/editor/editor.html.twig` (same folder structure of course). [Right at the top it sets a twig variable](https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/templates/forms/fields/editor/editor.html.twig#L5) `codemirrorOptions` which ends up on Admin pages with an editor field in a textarea attribute, like this: `<textarea data-grav-editor="{"codemirror":{"mode":"gfm","ignore":[]}}">`. I have absolutely no idea how and where this gets turned into functioning javascript bits. If I add a simple option like the tabSize into the twig variable like so: `{% set codemirrorOptions = {'mode': 'gfm', 'tabSize': 8, 'ignore': ['code', 'preview']}|merge(field.codemirror|default({})) %}`, this ends up setting the tabSize in the editor to the given value, so that's nice. But how do I add an overlay with `.addOverlay`, for example, or use `.markText`? Where and how is the editor js object constructed?

As always, your time and thoughts are much appreciated!

**Comment by w00fz** [comment]
Note that I am exposing access to the Editor instance. You can access it through `Grav.default.Forms.Fields.EditorField.Instance.editors` which contains an array of instances (normally it's only 1 entry) where you can use the codemirror API.

Knowing that, you could have your plugin load a JS file and in that JS file you could use CodeMirror's API at runtime however you like.

Hope this helps!

**Comment by skinofthesoul** [comment]
Oh wow, that does sound helpful! Not sure I can work with it just like that since I'm a n00b ;-) but I will give it a go in a while (too busy right now). Thank you!

**Comment by skinofthesoul** [comment]
Really sorry to bother you with this again, but it seems I do need a little more help. I have now added my javascript file to load at the very bottom in Admin, and `console.log(window.Grav.default.Forms.Fields.EditorField.Instance.editors[0])` gives me the editor instance just like you said. However, the following produces a "getOption is not a function" error:

`let cmty = window.Grav.default.Forms.Fields.EditorField.Instance.editors[0];    
console.log(cmty.getOption('mode'));`

According to the CodeMirror API, this should work, and when I try it in one of the CodeMirror demos, it does. Looking at the object that I get in Grav, it seems to be quite different from the ones I can work with in the demos. I don't think this is due to a different CodeMirror version being used in Grav, I rather suspect that I am missing some crucial understanding or piece of information here. I humbly ask for help figuring out what it is because I am _stumped_…

**Thank you!**

**Comment by w00fz** [comment]
Hey there @skinofthesoul 

You were actually quite close:

```js
const editor = window.Grav.default.Forms.Fields.EditorField.Instance.editors[0];
const codemirror = jQuery(editor).data('codemirror');
const mode = codemirror.getOption('mode');
```

**Comment by skinofthesoul** [comment]
That is absolutely fantastically working. You are my **hero**! :-D
