### ISSUE TITLE
Drag and Drop Images broken in expert mode

### ISSUE THREAD

**Issue by ricardo118** [getgrav/grav-plugin-admin#1927]
As per discord discussion 

> Ok, so what it looks like is that there's at least a bit of a bug with allowing drag and drop with expert mode. When I have expert mode turned on from the toggle in the page editor, it prevents me from dragging images. However, when expert mode is enabled through the plugin settings, the drag and drop still works in the interface, it just doesn't save it to the frontmatter.

[Discord Link](https://discordapp.com/channels/501836936584101899/501854266873348112/732746036765917274)

**Comment by 123qwe33** [comment]
To summarize: image drag and drop gets properly disabled when expert mode is set from the toggle above the page editor, however if you enable expert mode globally through the plugin settings ( Settings -> Editor Mode -> Expert), the drag and drop still works, but doesn't save.

**Comment by mahagr** [comment]
In which version of admin did this happen?

**Comment by 123qwe33** [comment]
I experienced this in v1.9.15

**Comment by mahagr** [comment]
I'm wondering if I did or didn't fix this in 1.10...

**Comment by w00fz** [comment]
In 1.10 this always works for me. I can Drag & Drop images from Normal mode, Export mode and persistent Expert Mode (set from the plugin).

Could you give 1.10 a try?

**Comment by w00fz** [comment]
Now 1.10 is out can you guys confirm this is no longer an issue?

**Comment by ricardo118** [comment]
clicking to open the "browse" works, drag and drop does not. tested just now latest stable

**Comment by mahagr** [comment]
Yup, drag & drop isn't working @w00fz
