### ISSUE TITLE
Help tooltips cropped on collapsed list items

### ISSUE THREAD

**Issue by arkhi** [getgrav/grav-plugin-admin#1928]
As shown on the following image, tooltips on the first element of a list item will be cropped by the item container.

This forces to expand the item to see the content of the tooltip.

The way I understand the tootlip has been implemented will also make the tooltip invisible to screen readers.

![image](https://user-images.githubusercontent.com/277773/87519656-34aca800-c682-11ea-8a70-d863a2dca488.png)

**Comment by arkhi** [comment]
The tooltip uses the `content` CSS property to display.

The tooltip being a descendant of `<li class="collection-collapsed">` which has `overflow: hidden` when collapsed, results in that cropping.

**Comment by ricardo118** [comment]
because its created within a for loop and defined per item via the `help`. if you have a solution or suggestion to go around it we can try it

**Comment by w00fz** [comment]
I have found a trick to workaround this that seems to be reliable enough to guarantee the same behavior while allowing the tooltip of the first item to not get cut off.

This is in 1.10.
