### ISSUE TITLE
Saving changes opens off-canvas menu (mobile)

### ISSUE THREAD

**Issue by Mezarith** [getgrav/grav-plugin-admin#193]
The button for saving changes calls the off-canvas menu, before refreshing. I've only experienced this on mobile.

**Comment by Mezarith** [comment]
UPDATE: all buttons and links that go to other pages within the admin site open the menu.

**Comment by Vivalldi** [comment]
@rhukster and @Mezarith I've got this.

**Comment by Mezarith** [comment]
You might want to add the bug label to this.
:P

**Comment by Vivalldi** [comment]
no need as it's closed. It's more for tracking when open to show importance.

**Comment by Mezarith** [comment]
@Vivalldi Ah, makes sense. I though the labels were also used for archives.
