### ISSUE TITLE
incorrect quote characters in presentation.yaml

### ISSUE THREAD

**Issue by SteveDaulton** [getgrav/grav-plugin-admin#1932]
Line 257 of grav-admin/user/themes/bootstrap4-open-matter/blueprints/presentation.yaml
`                      description: ''Short name, e.g. ''file''.'`
Should be:
`                      description: 'Short name, e.g. "file".'`
Note the use of two ' 'single quotes' ' that should each be one "double quote"

**Comment by paulhibbitts** [comment]
Hi @SteveDaulton , this looks like an issue in my Bootstrap4 Open Matter theme, if so please close here and re-open at https://github.com/hibbitts-design/grav-theme-bootstrap4-open-matter. Thanks!

**Comment by SteveDaulton** [comment]
Sure, will do.
Nice theme by the way :+1:
