### ISSUE TITLE
Pages tab is extremely slow to load

### ISSUE THREAD

**Issue by azpery** [getgrav/grav-plugin-admin#1934]
Hello, 

First, thank you for your work :) 

We have built our website on top of Grav and it works very well. But the pages management through the admin plugin is very slow (Up to 5-10 seconds). 
We have up to 5000-10000 pages and I believe the JS or the PHP are pain while it's loading it. 
Also when we want to edit a page, it takes also 5 to 10 seconds for the page to load.

Do you have a clue or advises to give us?
Thanks

**Comment by ricardo118** [comment]
@azpery for that many pages you need to use the new flex pages for admin. They are designed for large sites now. It is currently under grav1.7RC only, but you can already use and test it

**Comment by azpery** [comment]
Hello Ricardo, 
We've just tried to implement new flex pages feature using the version 1.7 RC but it is even worse than before :/. Even with < 1000 pages my local server take > 30 seconds to load any tab of the admin panel. 
SO, I guess we are not implementing it well. SO my question is, how do I implement it ? Do we need to migrate the previous pages ? (I read not) 
Thank you again and bye :)

**Comment by rhukster** [comment]
It's quite hard to determine what the issue is without being able to poke through everything.  The two most common causes:

1. plugin that is not well optimized, and causing lots of extra process.  Fix: work your way through your plugins disabling them to see if one of them is causing the issue
2. custom blueprint with lots of complex custom fields that is causing the page to render slowly. Fix: try using the default page blueprint by renaming the page to `default.md` to see if the custom blueprint is causing it.

**Comment by ricardo118** [comment]
is it just the page edit load or the page list mode?

for flex, you need latest "testing" grav, you can set it in system configuration.

Will be admin 1.10 and grav 1.7.

Once that is on, you need flex-objects plugin, and enable pages (admin) on the flex objects plugin itself.

Like andy said, if the slow load is just on the page edit and not the page listing, then its likely a poorly optimized blueprint or overly complex.

You could also message me directly on the grav discord and send me a test login to take a look

**Comment by mahagr** [comment]
@azpery In Grav 1.7 admin you should not use the normal Page logic from the frontend, but use flex directory instead. If you're using the indexes correctly in there, you'd have super fast page loads.

**Comment by w00fz** [comment]
As Flex Pages started taking shape, I have benchmarked 50,000 pages and the admin has always been well noticeably faster than traditional pages.

Not sure if you have sorted the issue but perhaps try with the latest 1.7/1.10, there really isn't anything you need to do other than having Flex Pages enabled.
