### ISSUE TITLE
Grav 1.7.0 : Fetch Failed (but appears to succeed?)

### ISSUE THREAD

**Issue by ezchile** [getgrav/grav-plugin-admin#1935]
Hi, I'm receiving the following message when trying to purge old cache (Grav v1.7.0 - rc12):

Fetch Failed:  Purged 0 old cache folders...{"status":"success","message":null}

![Screenshot 2020-07-21 at 14 23 24](https://user-images.githubusercontent.com/1766389/88060294-f588c600-cb5d-11ea-849b-fb59b2c1819e.png)

**Comment by mahagr** [comment]
Confirmed as a bug.

**Comment by w00fz** [comment]
This was introduced as an issue when trying to fix the same problem for Scheduler. One expected echo of the message, another the return of it.

I am now handling both and should be fixed in 1.7 (reference: https://github.com/getgrav/grav/commit/0a601f10c09262dfbdce46701dc84ee40ac233a9)
