### ISSUE TITLE
Grav 1.7.x Duplication (non-deletion) of template file after template change of existing page. 

### ISSUE THREAD

**Issue by ezchile** [getgrav/grav-plugin-admin#1936]
Hi.  I've noticed that if you create a page, save it and then change the page template at a later stage, the new and correct .md file is copied into the folder, however, the original .md file is sometimes not deleted automatically.

I.E. I created a section that used my own template 'side-featurebox' initially, but then decided that I wanted to use a different page-template.  I changed the page template via the Admin panel to another template file 'side-featurebox-case-studies' and both a side-featurebox.md and the side-featurebox-case-studies.md were left in the directory.  Grav then applies the template of the first .md file it finds, which can the the wrong one.  

I can of course delete the incorrect .md file via ftp, but I'm pretty sure the 'old' .md file should be deleted automatically upon template change, shouldn't it?

<img width="287" alt="two-md-files" src="https://user-images.githubusercontent.com/1766389/88285045-5a6f2800-cce6-11ea-95bd-fa7c5419b5d8.png">

**Comment by ricardo118** [comment]
can confirm this bug has happened to me too

**Comment by mahagr** [comment]
Yes, this should not happen. It should delete (or move) the old file, not create a new one.

**Comment by mahagr** [comment]
I'm unable to reproduce this bug, can you please provide simple steps in a newly installed site on how to reproduce it?

**Comment by mahagr** [comment]
May be related to #1899, which is fixed.

**Comment by ezchile** [comment]
I've just installed a fresh copy of rc15, and now cannot reproduce either.  I think it was an intermittent issue, rather than happening every time however, so will keep an eye out for it happening in the future and report if I see the behaviour again.  Agreed, it does sound related to #1899, so likely fixed by that.
