### ISSUE TITLE
Cannot install Plugins, Themes in admin --> Error

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#194]
Tried to install plugins/themes in admin  --> result:
![plugin](https://cloud.githubusercontent.com/assets/12480617/9975218/3f53ca4e-5eb4-11e5-8978-3bf921d19274.png)
![themes](https://cloud.githubusercontent.com/assets/12480617/9975220/44ef5eb4-5eb4-11e5-8198-9d14bf899d02.png)

Removing/uninstall works

**Comment by flaviocopes** [comment]
Maybe it was a temporary issue with getting Zip downloads from GitHub, is it happening again for you? Just tried, works fine for me

**Comment by axel-rank** [comment]
Still the same error in Admin Panel.
gpm install works.

**Comment by flaviocopes** [comment]
Strange! Is that an Apache install? Local install or on a remote server?

**Comment by axel-rank** [comment]
Install on my hoster, Apache.

**Comment by rhukster** [comment]
I can't replicate this also.  The admin uses the same methods as the GPM install, so its very strange that it works for one and not the other.  The only thing that springs to mind is the PHP version on your webserver doesn't have the same modules and options that the CLI version does.  Can you paste a copy of your config/info settings from the admin into a code block here?

**Comment by axel-rank** [comment]
I have just uninstalled admin plugin recently. (doing well without so far) Seems that I'm the only one with this problem. My hoster is doing a PHP/Server update in a few weeks. So I'll wait for this and check again (maybe admin plugin is stable until then too).

**Comment by axel-rank** [comment]
OK, in my hoster config I can choose between php 5.4, 5.5, 5.6. used on my Domains. So I changed back to php 5.5, installed grav admin panel again and now it works, no error anymore.
(Wondering why I can choose php 5.6 und PHP (cli) is still php 5.5?)

**Comment by axel-rank** [comment]
Issue seems to be resolved. Error cause was two different PHP Versions.
