### ISSUE TITLE
Glitch Deletes Entire Pages Directory

### ISSUE THREAD

**Issue by adamwlewis** [getgrav/grav-plugin-admin#1941]
Found a glitch today that completely deleted the pages directory of a site :-/

I recorded it happening, easily reproducible, but essentially editing an existing page and putting it in a folder that doesn't exist (in my case, the intent was grav would create the folder) and then trying to delete the non-existent folder will result in the entire pages directory being deleted. 

https://www.dropbox.com/s/ysrr78o1rrpxvxz/Grav-Delete-All-Pages.mp4?dl=0

**Comment by mahagr** [comment]
@rhukster We need Admin 1.9 release to fix this in the stable release, too.
