### ISSUE TITLE
In Grav, contact form does not work

### ISSUE THREAD

**Issue by Bahvya-Dev** [getgrav/grav-plugin-admin#1943]
I have used the form plugin in quark theme in grav and follow the instructions mentioned in the documentation https://learn.getgrav.org/16/forms/forms   but my form form is not displaying. It looks like this http://prntscr.com/u4r67l

Please let me know how can I fix this issue.

**Comment by rhukster** [comment]
You have bad YAML, or a broken .md file it looks like
