### ISSUE TITLE
Grav 1.7 RC.16 Unexpected slowness in Admin UI

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#1945]
I decided to take the plunge and upgrade my production course site with RC 1.7RC 16. Much to my surprise the Admin Panel navigation seems slower, but the Page Panel in particular which can now take over 15 seconds to load with only ~680 pages:

![2020-09-07_11-36-34 (1)](https://user-images.githubusercontent.com/1812771/92411999-020db180-f0ff-11ea-9f37-622da5424ee6.gif)

Running on a pretty average server, with PHP Version 7.3.5.

Is there anything perhaps on my end of things which is configured incorrectly?

Not sure if it is related, but seeing this in the Console:
<img width="1469" alt="2020-09-07_11-48-59" src="https://user-images.githubusercontent.com/1812771/92412280-2f0e9400-f100-11ea-811e-62eb1cdd17fe.png">

Here is the site:
https://opencoursehub.cs.sfu.ca/paulh/cmpt-363/

Thanks very much!
Paul
ps - running the same site using MAMP on the Mac I do not see the big hit re: Pages panel loading but the same Console messages

**Comment by rhukster** [comment]
Is admin caching turned on?

**Comment by paulhibbitts** [comment]
Thanks very much @rhukster , it was not but turning it on seems to have no effect esp: Pages panel.

**Comment by mahagr** [comment]
There is a way to get detailed information on what takes all the time in your site.

1) Enable debugger and switch to clockwork (should be default)
2) Install clockwork to your browser
3) Look into the performance tab in clockwork to see what is taking all the time

And if you are able:

4) If you're able, install and enable this module to your PHP: https://github.com/tideways/php-xhprof-extension
5) Look into the profiler tab in clockwork

PS. I'm in discord atm

**Comment by paulhibbitts** [comment]
Thanks @mahagr , here is an example:

<img width="1540" alt="2020-09-07_12-10-26" src="https://user-images.githubusercontent.com/1812771/92413040-28355080-f103-11ea-91ea-e98854446aad.png">

I will connect with you on Discord too🙂

**Comment by mahagr** [comment]
This was an upgrade from Grav 1.6 to Grav 1.7.0-rc.16 with a lot of plugins enabled. Disabling Flex Pages from the Flex Objects plugin fixes the slow page loads.

**Comment by paulhibbitts** [comment]
Hi @mahagr , sorry for the long delay it took quite a while to get a test Grav setup going on the same university server.

For some reason when I enable Clockwork it results in bringing down the site, so for now I've only got the standard debugger.

Here is a sample from within the Admin (Flex pages enabled):
<img width="1565" alt="2020-09-12_10-10-17" src="https://user-images.githubusercontent.com/1812771/93001088-779fc600-f4e1-11ea-97ed-e3d597a4c935.png">

And here is a sample when viewing pages (Flex pages enabled):
<img width="1568" alt="2020-09-12_10-10-37" src="https://user-images.githubusercontent.com/1812771/93001094-7ec6d400-f4e1-11ea-83fb-21cbc3e66bf8.png">

I've also disabled all non-Trilby/Grav plugins and no change:
<img width="1377" alt="2020-09-12_10-11-07" src="https://user-images.githubusercontent.com/1812771/93001114-90a87700-f4e1-11ea-9972-5001634214c4.png">

You can see the site live at:
https://opencoursehub.cs.sfu.ca/paulh/cmpt-363-2020/203/home

Connect me again via Discord for access etc.

Thanks very much,
Paul

**Comment by acondura** [comment]
The slowness I get in Admin UI is that it tries to constantly request admin.min.js file. Please see the following screenshot.
I started to get this after upgrading from 1.7 rc16 to rc17.

![admin-ui-slow](https://user-images.githubusercontent.com/1694890/95665421-bebcbd80-0b58-11eb-818d-ef9ede37e0f1.png)

**Comment by rhukster** [comment]
The original issue was sorted.

@acondura your issue is different and looks like a server configuration issue with JS ajax queries failing.  If you continue to have this problem please open a new issue.

**Comment by acondura** [comment]
Yes, I got the sense this was so after I posted my reply.
Thank you!

**Comment by paulhibbitts** [comment]
UPDATE: After getting a test area setup on that same server, and manually updating to the latest RC 17 etc (do not have CLI access etc.) the Admin Pages tab now renders as expected (not massively slow) with Flex Objects front-end disabled, but once Flex Objects front-end rendering is ENABLED the slowness returns in the Admin Panel Pages tab.

**Comment by rhukster** [comment]
We actually have decided to hide the 'frontend flex' option in 1.7.  It's just not ready for prime time, it's not performance-optimized nor has it been thoroughly tested.   The best solution is currently to use regular pages in frontend but flex-pages in the backend. This is the default setup for Grav 1.7 anyway.

**Comment by paulhibbitts** [comment]
Thanks @rhukster , Matias has mentioned that too and it sounds fine to me at this point!
