### ISSUE TITLE
"Smarten" page hit logic

### ISSUE THREAD

**Issue by bobrocke** [getgrav/grav-plugin-admin#195]
Right now the Admin counts every hit as a page hit - whether it's from a bot, a web spider, or a real visitor. Improve the logic to filter as much as possible of the junk hits.

**Comment by rhukster** [comment]
We need to add some logic that can filter out 'robot' and 'crawler' type requests.  I'm not sure if our current Browser() class has the required capability for this or not.. Will need to be looked at.

**Comment by flaviocopes** [comment]
The logic is now very simple, it looks for 'bot' or 'crawl' in the user agent. It's a start, and can later welcome custom blacklists if desired.
