### ISSUE TITLE
Cannot update to 1.6.28

### ISSUE THREAD

**Issue by tmc210** [getgrav/grav-plugin-admin#1954]
I get this error message:

Installation failed: rmdir(/app/code/system): Read-only file system

**Comment by rhukster** [comment]
that `app/code/system` folder is not anything in Grav, so it's probably related to your server setup.  Need some more information thought to know what's going on.

**Comment by tmc210** [comment]
I set it up in Digital Ocean and it works fine, but it won't upgrade and keeps giving me that message.

**Comment by mahagr** [comment]
If /app/code is the root for the web page, your site may be behind a readonly filesystem, meaning that you cannot update the code from the web server. Did you setup the site yourself or was grav installed by some cpanel script?
