### ISSUE TITLE
[v1.7.0-rc17 ] Adding Page Access option under Page Security Tab not working 

### ISSUE THREAD

**Issue by kiranetph** [getgrav/grav-plugin-admin#1955]
![page_access0](https://user-images.githubusercontent.com/15226809/95401917-08cb5680-0941-11eb-995e-3c1ee049af1d.png)

**Comment by paulhibbitts** [comment]
Just tested this locally on a Mac with Firefox, here is what I get - hope it helps vs. Safari issue:
![2020-10-08_09-12-09 (1)](https://user-images.githubusercontent.com/1812771/95485453-9bbabf80-0946-11eb-87fa-325c84e725ee.gif)

**Comment by paulhibbitts** [comment]
I can also confirm issue on Mac Safari, here is my console log:

<img width="1000" alt="2020-10-08_09-22-13" src="https://user-images.githubusercontent.com/1812771/95486424-d2dda080-0947-11eb-93ad-16530b13d23f.png">

**Comment by w00fz** [comment]
Thanks for the extra details, this is now fixed.
