### ISSUE TITLE
error pease contact github Numeric Folder Prefix 

### ISSUE THREAD

**Issue by thomas309** [getgrav/grav-plugin-admin#1957]
I wrote an new articel and started to publish him, but then the system said error please contact github.
and
Die Sortierung ist für diese Seite deaktiviert, weil Numerisches Ordner Präfix nicht aktiviert ist
Sorting is disabled for this page because Numeric Folder Prefix is not enabled

**Comment by rhukster** [comment]
github? sounds like an issue with gitsync plugin perhaps?
