### ISSUE TITLE
Cannot connect to the GPM

### ISSUE THREAD

**Issue by sunilsmail** [getgrav/grav-plugin-admin#1959]
{status: "error", message: "Cannot connect to the GPM"}
message: "Cannot connect to the GPM"
status: "error"

API: http://localhost:8999/admin/update.json/task:getUpdates

http://localhost:8999/admin/task:getNotifications

"Error while trying to download (code: ): https:\/\/getgrav.org\/notifications.json?1603278650\n"}

**Comment by rhukster** [comment]
Try these first: https://learn.getgrav.org/16/troubleshooting/common-problems#cannot-connect-to-the-gpm
