### ISSUE TITLE
Expert taxonomy saves incorrectly

### ISSUE THREAD

**Issue by KnownSyntax** [getgrav/grav-plugin-admin#196]
It seems that when you use the admin plugin and use the expert mode, if you save a taxonomy it gets saved incorrectly.

An example on a pure vanilla install of the latest grav and admin plugin. Make any page, click on expert mode, and then add the following:
```
taxonomy:
category: blog
```

Now, once the page loads back up after you hit "Save" you'll see the following is what gets saved:
```
taxonomy:
    category:
        - b
```

**Comment by rhukster** [comment]
I had seen this in the past, I thought I fixed it, but I guess that was only in the 'normal' mode.  I will investigate!
