### ISSUE TITLE
Cannot go in to edit existing page

### ISSUE THREAD

**Issue by t-clarity** [getgrav/grav-plugin-admin#1960]
I never had this issue where I could not reaccess a page that I just saved and edited.

When I click on the article, to take out the coding I just implemented (which has an 'unexpected character' error).

The screenshot I attached pops up. What can I do to have access to edit this page, and fix the error? 

![error](https://user-images.githubusercontent.com/73309574/96914884-8fb91c80-1473-11eb-9bba-b47dd60d4564.JPG)

**Comment by w00fz** [comment]
In the bottom right of that error it says it has found an unexpected error at line 132 of 03.meaning. Did you check the twig at that line for the template your page is using?
