### ISSUE TITLE
Error when deleting a page on GRAV

### ISSUE THREAD

**Issue by Andrey8806** [getgrav/grav-plugin-admin#1962]
Hello!
Got a problem when managing pages on GRAV: every action I see an error: "Deleting page failed on error: fatal: No path specified. See 'man git-pull' for valid url syntax"
At the moment I simply want to delete mistaken pages off the list.

I already updated my GRAV and plug-ins but it didn't help.

I might be doing something wrong but there is no Help page on it.

Can you please help asap?

**Comment by mahagr** [comment]
Looks like this is an issue with https://github.com/trilbymedia/grav-plugin-git-sync ?

Which version of Grav are you using?

**Comment by Andrey8806** [comment]
Hello!
I use GRAV v1.6.28
And look all I need from it is just to have a place to keep the manual available for customers.
So I don't understand the background of this system as I am not a coder, sorry.

**Comment by Andrey8806** [comment]
Hello!
I realized that the problem was caused by the name of the article ending with "+"
So URL was created with " " at the end.
And somehow it has not been detected during deleting
![image](https://user-images.githubusercontent.com/73528075/97399268-3a16c100-1906-11eb-9d64-3c85194e128f.png)

**Comment by rhukster** [comment]
Did it let you create a page with a `+` in the slug? If so that's the bug.  A plus sign is equivalent to a space in a URL and really slugs should have only lowercase letters and `-` for spaces.  I think the issue is this space got snuck in at some point, that's converted to a space, and perhaps trimmed, and then the slug you are trying to delete does not equal the slug of the page.

**Comment by rhukster** [comment]
If you have access to filesystem via ssh or ftp, try renaming and removing the plus.

**Comment by Andrey8806** [comment]
Hello, Andy!It seems your understanding is correct but I don't know how to resolve this.If I try to edit the slug I just receive another page but all that mistaken pages stay in the list and I even cannot make them invisible.Can you recommend anything?Thank you for help!Andrey19:54, 28 октября 2020 г., Andy Miller <notifications@github.com>:
Did it let you create a page with a + in the slug? If so that's the bug.  A plus sign is equivalent to a space in a URL and really slugs should have only lowercase letters and - for spaces.  I think the issue is this space got snuck in at some point, that's converted to a space, and perhaps trimmed, and then the slug you are trying to delete does not equal the slug of the page.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Andrey8806** [comment]
Hello, rhukster, I really don't know what is SSH or FTP, but I tried to remove the plus in admin interface (manage pages) and it didn't work out. Can you advise something?
Thank you!

**Comment by Andrey8806** [comment]
Hello guys!
Can you help me somehow?
We anyway need to resolve this issue with the bug.
The + in the name of article got into the slug.
I cannot rename because it just makes a new page with a new name but old mistaken pages leave in place.

Asking for your support again! Please help!

**Comment by rhukster** [comment]
You can't really fix it unless you can get access to the files in some other way.  SSH, SFTP are the standard ones, but perhaps your hosting provider has a filemanager built in to the hosting dashboard?

I suggest you at least learn how to use SFTP (Secure FTP), as that is supported on every host and is just like using a file manager on your desktop once you get it connecting to your server.

Just google, like: https://www.webhostinghub.com/help/learn/website/managing-files/connect-sftp-filezilla
