### ISSUE TITLE
Clicking page template type "post" causes "Add" page modal close

### ISSUE THREAD

**Issue by b7s9** [getgrav/grav-plugin-admin#1963]
in the "Add" page modal, from the `Page Template` dropdown, **clicking** an option which hangs over the edge of the modal, causes the whole modal to close. Specifically you can see this when attempting to select "Post". My guess is this has something to do with event capture bubbling. Using the keyboard to select "Post" won't close the modal

screenshot  ![Screen Shot 2020-10-27 at 15 37 41](https://user-images.githubusercontent.com/19176695/97353420-641aa580-186a-11eb-9467-18ad4114d2c1.png)

video [Screen Recording 2020-10-27 at 15.13.54.mov.zip](https://github.com/getgrav/grav-plugin-admin/files/5447665/Screen.Recording.2020-10-27.at.15.13.54.mov.zip)

- Grav v1.7.0-rc.17 - Admin v1.10.0-rc.17
- Firefox 81

**Comment by w00fz** [comment]
I fixed this recently. Was a long standing issue that is no longer with us :)

More details at https://github.com/getgrav/grav-plugin-admin/issues/1682#issuecomment-728729849
