### ISSUE TITLE
Sharing on Facebook

### ISSUE THREAD

**Issue by Draecal** [getgrav/grav-plugin-admin#1965]
Direct posting the url on facebook can show a preview of the content getting the following: 
![image](https://user-images.githubusercontent.com/8697000/98069051-c7519c80-1e55-11eb-8001-260db8e5fd4d.png)

**Comment by rhukster** [comment]
Sharing what? How?

**Comment by Draecal** [comment]
Sharing a page by copy paste the url

**Comment by rhukster** [comment]
That's all based on your opengraph tags.  There are a couple of SEO plugins available that help you with those, and we have our own SEO-Magic plugin coming out soon that will give you a tonne of features for opengraph tags and also other things to help improve your own SEO.

**Comment by Draecal** [comment]
I´m not confident with that because time to time accesing the admin panel I got redirected to a white page saying: Verifiying you are not a robot. I´m pretty sure that is what is messing all but can't manage to capture it.

Also happens that a side panel shows for like 1 sec with something related also to the bot verification on my site, so fast to get a screenshot.

**Comment by rhukster** [comment]
That’s not coming from grav.  There is no bot protection in grav so it’s something else in your setup or perhaps your browser.

**Comment by Draecal** [comment]
Manage to debug a little, there is only one connection and its the re-captcha function of Forms plugins Facebook scrapper reach the page that re-captcha uses for verifiying instead the main site.

**Comment by Draecal** [comment]
`<!DOCTYPE html>
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
    <title>Bot Verification</title>
    <script>
        function onSubmit() {
            document.getElementById('lsrecaptcha-form').submit();
        }

        var onloadCallback = function() {
            var cont = grecaptcha.render('recaptchadiv', {
                'sitekey': '6LcPROgUAAAAAL18aNmkXPASE_Ix2XXR83D5WOeG',
                'callback': onSubmit,
                'size': 'invisible'
            });
            grecaptcha.execute(cont);
        };
    </script>
    <style>
        body {
        height: 100%;
        }
        .panel {
        padding: 30px;
        max-width: 425px;
        margin: 10% auto;
        box-shadow: 0 0 2px 2px rgba(0, 0, 0, 0.2);
        }
        .title {
        font-size: 1.5em;
        font-weight: 100;
        margin-top: 10px;
        text-align: center;
        }
        .recaptcha-center {
        margin-top: 35px;
        margin-bottom: 20px;
        margin-left: 13%;
        margin-right: 13%;
        display: block;
        }
    </style>
</head>
<body>
    <div class="panel">
        <h3 class="title">Verifying that you are not a robot...</h3>
        <form id="lsrecaptcha-form" method="POST" action="/.lsrecap/recaptcha?">
            <div id="recaptchadiv" class="recaptcha-center"></div>
        </form>
    </div>
    <script src="https://www.recaptcha.net/recaptcha/api.js?onload=onloadCallback&amp;render=explicit" async defer>
    </script>
</body>
</html>`

That's what Facebook scrapper see when I try to share the main url of my site
