### ISSUE TITLE
Work with stream

### ISSUE THREAD

**Issue by dimayakovlev** [getgrav/grav-plugin-admin#197]
1. Install Bootstrap theme (for example)
2. Create a new theme based on Bootstrap using [described way](http://getgrav.org/blog/theme-development-with-inheritance) or download [small test theme](http://1drv.ms/1iJptf7)
3. Activate new theme
4. Save new theme setting

I got error:

![theme bootstrap new grav](https://cloud.githubusercontent.com/assets/8279974/10002627/e9ca6980-60b0-11e5-8bf0-4f67874a1b19.png)

**Comment by rhukster** [comment]
I will investigate this further! Thanks.

**Comment by flaviocopes** [comment]
The simplest thing to do to fix the problem is to put 

```
form: 
  validation: loose
```

in the theme's `blueprints.yaml`. Should we add a sort of 'form.ignore' field where we can put items the validation should specifically ignore, so we can have `validation: strict` enabled?
