### ISSUE TITLE
Cannot delete pages when "secure delete" is enabled

### ISSUE THREAD

**Issue by DidierLmn** [getgrav/grav-plugin-admin#1970]
When "Secure Delete" is enabled I get a confirmation popup, but after clicking "Confirm" nothing happens, not even an error.

Server: Linux (Fedora 31) + nginx (Can also reproduce locally on MacOS 10.15 + built in PHP server)
Grav: 1.6.28
Grav Admin Plugin: 1.9.17

1. Open Admin plugin settings
2. Set "Warn on page delete" to "Enabled"
3. Set "Secure Delete" to "Enabled"
4. Go to "Pages"
5. Click delete button
6. Type "Delete" in popup text box
7. Click "Confirm"
8. Nothing happens
9. Set "Warn on page delete" to "Disabled"
10. Keep "Secure Delete" on "Enabled"
11. Go to "Pages"
12. Click delete button
13. Page gets deleted without confirmation or popup
14. Set "Warn on page delete" to "Enabled"
15. Set "Secure Delete" on "Disabled"
16. Go to "Pages"
17. Click delete button
18. Click "Continue" in popup
19. Page gets deleted

It seems like "Secure Delete" doesn't work, but also that "Secure Delete" cannot be used without "Warn on page delete". I don't know if the latter is intended behaviour but if it is, I think it should be made cleare somewhere.

**Comment by w00fz** [comment]
Both those feature have been retired with 1.10. It is no longer optional getting warned about deleting a page, you just get asked all the times, it is safer.

Sorry this is probably not the answer you were looking for but this also allows to simplify the settings in the admin plugin which is already prolific with them.
