### ISSUE TITLE
Adding an empty meta field in Admin / Site unsets earlier metadata.

### ISSUE THREAD

**Issue by ulab** [getgrav/grav-plugin-admin#1972]
I have been trying to add an empty "generator" meta field to Admin / Site ([as suggested](https://github.com/getgrav/grav/issues/603#issuecomment-170278153)), but this empties meta fields that are listed prior too.

I start with something basic like

![Screenshot 2019-08-09 at 08 37 44](https://user-images.githubusercontent.com/504616/62759284-26710780-ba81-11e9-983a-b5eb4fe6b4c1.png)

After saving the page, I empty the field for `generator` and save the page which results in

![Screenshot 2019-08-09 at 08 38 06](https://user-images.githubusercontent.com/504616/62759335-49032080-ba81-11e9-86f5-094d4a202aad.png)

**Comment by w00fz** [comment]
This is now resolved in admin 1.10 develop.

Please note I have also transferred the ticket from grav to admin where it belongs.
