### ISSUE TITLE
error Please enable JavaScript in your browser.

### ISSUE THREAD

**Issue by lokha** [getgrav/grav-plugin-admin#1974]
if I click on this button, there will be an error like this

![image](https://i.imgur.com/5pDkxFa.png)

then there will be such a error:

![image](https://i.imgur.com/vHIY5eE.png)

i installed grav-admin following this instruction https://learn.getgrav.org/16/basics/installation on my debian 9 host  
i use nginx, php7.4

**Comment by w00fz** [comment]
Can you please try opening your browser developer inspector, reload the page and see if you get any JS error in console?

I am assuming you have JavaScript enabled?

**Comment by lokha** [comment]
I forgot to write that I solved this problem. here is the solution:

blame cloudflare and its rocket loader that prevented the execution of js scripts  
![image](https://user-images.githubusercontent.com/32991511/99487311-ad907900-296e-11eb-90bc-487d9fe2accc.png)

solution to either turn off rocket loader in cloudflare settings
or at the beginning of each script add `data-cfasync="false"`
```
find /var/www/grav-admin -regex ".*\.\(php\|twig\)" | xargs sed -i 's/script type/script data-cfasync="false" type/g'
find /var/www/grav-admin -regex ".*\.\(php\|twig\)" | xargs sed -i 's/script src/script data-cfasync="false" src/g'
find /var/www/grav-admin -regex ".*\.\js" | xargs sed -i 's/s=document.createElement("script");s.type="text\/javascript"/s=document.createElement("script");s.data-cfasync="false";s.type="text\/javascript"/g'
find /var/www/grav-admin -regex ".*\.\php" | xargs sed -i "s/'<script'/'<script data-cfasync=\\\'false\\\''/g"
```

**Comment by w00fz** [comment]
Awesome! Thanks for replying back with the solution.
