### ISSUE TITLE
Not displaying properly in Chrome 86.0.4240.198

### ISSUE THREAD

**Issue by ArtyomCZ** [getgrav/grav-plugin-admin#1978]
A few days back without a problems today I tried to login but the admin page is displayed like this
![image](https://user-images.githubusercontent.com/16862369/99824368-eb9bc180-2b55-11eb-8ede-d7b7f48764fa.png)
- Chrome 86.0.4240.198
- Windows 10 

It displays correctly in Microsoft Edge

**Comment by w00fz** [comment]
This looks like broken css. Try clearing your browser cache. Also if you have Chrome plugins, maybe one of these is affecting the rendering of the page. I do not think this is a problem of the admin but more of your browser.

Can you also try Firefox perhaps?

**Comment by ArtyomCZ** [comment]
I updated chrome to 87.0.4280.66 and it looks normal again. So i think its problem with specific browser version
![image](https://user-images.githubusercontent.com/16862369/99846531-c9ff0200-2b76-11eb-8b9c-c9d91d392fbb.png)

**Comment by w00fz** [comment]
Glad to hear! 🎉
