### ISSUE TITLE
saving content when site is running as redirected port (8081)

### ISSUE THREAD

**Issue by Andy-Flack** [getgrav/grav-plugin-admin#1981]
Running the system as a redirected port through a docker configuration on a local setup (192.168.1.70:8081),
after hitting Save the screen tries to go to
http://192.168.1.70:8081/admin/pages/entities/:8081#
not 
http://192.168.1.70:8081/admin/pages/entities/#

**Comment by mahagr** [comment]
I just tried this with Grav 1.7 and Admin 1.10 with `php -S localhost:8000 system/router.php` and it seems to work just fine.

Older versions have some known issues with this, so please try the latest version. :)

**Comment by Andy-Flack** [comment]
running under latest versions and problem has now become  a crash due to a null value. I am running the system as a full docker-compose configuration under apache not as a local php server which will probably be throwing different values into the process.

**Comment by mahagr** [comment]
I was finally able to reproduce this one, thank you for your extra information. I have a fix in place, but I'm not 100% sure if it works.

Open system/src/Grav/Common/Uri.php around line 165 and find the first line from below. Replace all the content inside the following if as follows:
```php
        // Handle custom base
        $custom_base = rtrim($grav['config']->get('system.custom_base_url'), '/');
        if ($custom_base) {
            $custom_parts = parse_url($custom_base);
            if ($custom_parts === false) {
                throw new RuntimeException('Bad configuration: system.custom_base_url');
            }
            $orig_root_path = $this->root_path;
            $this->root_path = isset($custom_parts['path']) ? rtrim($custom_parts['path'], '/') : '';
            if (isset($custom_parts['scheme'])) {
                $this->base = $custom_parts['scheme'] . '://' . $custom_parts['host'];
                $this->port = $custom_parts['port'] ?? null;
                if ($this->port !== null && $config->get('system.reverse_proxy_setup') === false) {
                    $this->base .= ':' . (string)$this->port;
                }
                $this->root = $custom_base;
            } else {
                $this->root = $this->base . $this->root_path;
            }
            $this->uri = Utils::replaceFirstOccurrence($orig_root_path, $this->root_path, $this->uri);
        } else {
            $this->root = $this->base . $this->root_path;
        }
´´´

Let me know if it fixes your issues.

PS: I assume you're using `custom_base_url: http://192.168.1.70:8081/` as I get the issue only with that setting.

**Comment by mahagr** [comment]
Hmm, there may be another issue as well...

**Comment by mahagr** [comment]
Hmm, after some more testing, I think the issue gets fixed with the above change.

**Comment by mahagr** [comment]
FYI for myself: this issue should be moved to Grav.

**Comment by drzraf** [comment]
Mentioning https://github.com/getgrav/grav-plugin-admin/issues/2214 here
