### ISSUE TITLE
1.7:  Saving theme config with empty filepicker throws error

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav-plugin-admin#1982]
When `blueprint.yaml` of theme contains `filepicker`, Admin will throw error when saving the config without selecting a file. Apache will no longer serve the page and needs a restart.

Environment:
- Windows 10
- Windows Subsystem for Linux
- Ubuntu 20.04.1 LTS
- PHP 7.4.3
- Grav 1.7.0-rc.17

Steps to reproduce:
- Create new theme: `bin/plugin devtools newtheme`
  - Name it `Test`
  - Select 'pure blank'
- Add the following to default `blueprints.yaml`
  ```
  headerImage:
    type: filepicker
    folder: "theme@:/images/headers"
    label: Select an image as header
    preview_images: true
    accept:
      - .png
      - .jpg
  ```
- Open Admin page `admin/themes/test`
- Save config without selecting an image
- Admin throws following error:
  ![image](https://user-images.githubusercontent.com/5120011/100128290-64658b00-2e80-11eb-9e14-c34f61f36cd9.png)
- Content of `config/themes/test.yaml`:
  ```
  enabled: true
  dropdown:
    enabled: true
  headerImage: null
  ```
- Refreshing page and server throws error:
  ![image](https://user-images.githubusercontent.com/5120011/100121111-0b462900-2e79-11eb-88cc-f7a810ff60f9.png)
- After restarting Apache, Admin config page is shown correctly.
- Content `/var/log/apache2/error.log`:
[Tue Nov 24 18:28:00.697455 2020] [mpm_prefork:notice] [pid 453] AH00169: caught SIGTERM, shutting down
[Tue Nov 24 18:28:02.469695 2020] [mpm_prefork:notice] [pid 532] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Tue Nov 24 18:28:02.469802 2020] [core:notice] [pid 532] AH00094: Command line: '/usr/sbin/apache2'
[Tue Nov 24 18:28:32.968538 2020] [core:notice] [pid 532] AH00051: child pid 545 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Tue Nov 24 18:28:33.160751 2020] [php7:notice] [pid 537] [client 127.0.0.1:62937] PHP Fatal error:  Uncaught Error: Class 'Monolog\\Handler\\AbstractProcessingHandler' not found in /mnt/c/Users/pamtbaau/Documents/Development/Web/www/grav/grav-admin/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:24\nStack trace:
#0 /mnt/c/Users/pamtbaau/Documents/Development/Web/www/grav/grav-admin/vendor/composer/ClassLoader.php(444): include()
#1 /mnt/c/Users/pamtbaau/Documents/Development/Web/www/grav/grav-admin/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile()
#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()
#3 /mnt/c/Users/pamtbaau/Documents/Development/Web/www/grav/grav-admin/system/src/Grav/Common/Service/LoggerServiceProvider.php(37): spl_autoload_call()
#4 /mnt/c/Users/pamtbaau/Documents/Development/Web/www/grav/grav-admin/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\\Common\\Service\\LoggerServiceProvider->Grav\\Common\\Service\\{closure}()
#5 /mnt/c/Users/pamtbaau/Documents/Development/Web/www/grav/grav-admin/system/src/Grav/Common/Processors/InitializeProcessor.php(189): Pimple\\Container- in /mnt/c/Users/pamtbaau/Documents/Development/Web/www/grav/grav-admin/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 24, referer: http://dev-dev/admin/themes/test
Tue Nov 24 18:28:33 2020 (535): Error Internal error: wrong size calculation: /mnt/c/Users/pamtbaau/Documents/Development/Web/www/grav/grav-admin/user/plugins/problems/vendor/autoload.php start=0x00007fccfaafbe80, end=0x00007fccfaafc308, real=0x00007fccfaafc3a8

  [Tue Nov 24 18:28:33.969461 2020] [core:notice] [pid 532] AH00051: child pid 546 exit signal Segmentation fault (11), possible coredump in /etc/apache2

**Comment by mahagr** [comment]
This works just fine for me.

Looks like your PHP crashes. I would install later version, 7.4.3 is super old and has a lot of known bugs.

**Comment by pamtbaau** [comment]
> 7.4.3 is super old

Super old? Its release date is: [20 Feb 2020](https://www.php.net/releases/index.php)... :-)

Any way, I'll upgrade and test again.

**Comment by pamtbaau** [comment]
Using fresh download of grav-admin-v1.7.0-rc.17.zip

- Current install PHP 7.4.3 on localhost: -> Error
- Upgraded to PHP 8.0.0 on localhost: -> Error
- `scp`-ed website to remote host using PHP 7.4.11: -> No error

Hum... Seems to be pointing so something beyond php version. Not going to spend any time on this...

**Comment by mahagr** [comment]
I was trying it with PHP 8.0.0, no issues here.
