### ISSUE TITLE
Admin 1.9: Deleting a page does not work in FF with confirmation modal

### ISSUE THREAD

**Issue by mahagr** [getgrav/grav-plugin-admin#1984]
You cannot delete a page in FireFox if the confirmation modal is enabled. Task is not being run likely because of the button submits the form.

**Comment by w00fz** [comment]
It’s fixed in 1.10

**Comment by mahagr** [comment]
I know, but it is broken in Admin 1.9, which is the only stable release. I thought it broke during 1.10 development, but it did not, hence the issue.

We can mark this fixed in 1.10 and ask people to upgrade. Or we can fix it in 1.9.

**Comment by mahagr** [comment]
WORKAROUND: Go to `Plugins` > `Admin Panel` and disable `Secure Delete`.
