### ISSUE TITLE
Html entities are not rendered properly

### ISSUE THREAD

**Issue by renards** [getgrav/grav-plugin-admin#1990]
Hello,
today I updated my Admin Panel to version 1.9.18. Now in the Pages section under the Advanced Tab and there in the Settings section, the HTML entities in the Parent-Page-List are no longer rendered properly, as you can see on the screenshot :

![grav_admin_html_entities](https://user-images.githubusercontent.com/17121804/101284145-d45c0580-37de-11eb-858e-62947bdc2c22.png)

I think this is caused by the following commit : [commit d01c959](https://github.com/getgrav/grav-plugin-admin/commit/d01c9599bd6d7eaa83f56f5d235b5d8d3f1374ee)

Therefore I changed line 13 in _public/user/plugins/admin/themes/grav/templates/forms/fields/pages/pages.html.twig_ from 
`<option {% if page_route == value or (field.multiple and page_route in value) %}selected="selected"{% endif %} value="{{ page_route }}">{{ option }}</option>`
to 
`<option {% if page_route == value or (field.multiple and page_route in value) %}selected="selected"{% endif %} value="{{ page_route }}">{{ option|striptags|raw }}</option>` 
in my local installation.

It's no big issue, but for some editors it might be a bit confusing.

**My environment** :
* Grav version : 1.6.30
* Admin Panel : 1.9.18
* PHP version : 7.4.13
* Linux server

**Comment by mahagr** [comment]
Also https://github.com/getgrav/grav/commit/db24d3e53e8cb0b886ff3fc58af855e03fe61a9c
