### ISSUE TITLE
Call to undefined method Grav\Common\Data\Data::header() in Site configuration

### ISSUE THREAD

**Issue by Robertofon** [getgrav/grav-plugin-admin#1991]
I just downloaded the primarily offered admin .zip and extracted it on a current PHP 7.3 server. 
Most of the cms works as expected, using the site configuration page or parts of the admin area raises this exception. 

Please provide an update

Error:
/www/htdocs/w01b51e3/xxxxxxxde/user/plugins/admin-frontmatter-yaml/admin-frontmatter-yaml.php

                'onPageProcessed' => ['onPageProcessed', 0],
                'onAdminSave' => ['onAdminSave', 0],
                'onAdminAfterSave' => ['onAdminAfterSave', 0],
            ]);
        }
     
        /**
         *
         *
         * @param Event $e
         */
        public function onAdminSave(Event $e)
        {
            $blocks = $this->config->get('plugins.admin-frontmatter-yaml.blocks');
            if (!is_array($blocks)) {
                $blocks = explode(',', $blocks);
            }
            $frontmatter = [];
            $header = [];
            $header_all = (array)$e['object']->header();  //<<<<<<<<<<<----
            $blocks_root_keys = [];
                    foreach ($blocks as $block_path) {
              $blocks_root_keys[$block_path] = current(explode('.', $block_path));
            }
            $frontmatter_blocks = [];
            $header_blocks = [];
            foreach ($header_all as $block_name=>$block_data) {
                if (in_array($block_name, $blocks_root_keys)) {
                    $header_blocks[$block_name] = $header_all[$block_name];
                } else {
                    $frontmatter_blocks[$block_name] = $header_all[$block_name];
                }
            }
            foreach ($blocks_root_keys as $block_path=>$block_name) {
                $key_paths = explode('.', $block_path);
                if (in_array($block_name, array_keys($header_blocks))) {
                    $value = get_array_by_key_path($header_blocks, $key_paths);
                    $header[$block_name] = isset($header[$block_name]) && is_array($value) ? array_merge_recursive_distinct($header[$block_name], $value) : $value;
                }
            }

Arguments

    "Call to undefined method Grav\Common\Data\Data::header()"

---------------
Stack:

- 
-  Error
- …/user/plugins/admin-frontmatter-yaml/admin-frontmatter-yaml.php52
- 59
- Grav\Plugin\AdminFrontmatterYamlPlugin onAdminSave
- …/vendor/symfony/event-dispatcher/EventDispatcher.php212
- 58
- Symfony\Component\EventDispatcher\EventDispatcher doDispatch
- …/vendor/symfony/event-dispatcher/EventDispatcher.php44
- 57
- Symfony\Component\EventDispatcher\EventDispatcher dispatch
- …/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php23
- 56
- RocketTheme\Toolbox\Event\EventDispatcher dispatch
- …/system/src/Grav/Common/Grav.php403
- 55
- Grav\Common\Grav fireEvent
- …/user/plugins/admin/classes/admincontroller.php765
- 54
- Grav\Plugin\Admin\AdminController taskSaveDefault
- …/user/plugins/admin/classes/admincontroller.php574
- 53
- Grav\Plugin\Admin\AdminController taskSave
- …/user/plugins/admin/classes/adminbasecontroller.php110
- 52
- Grav\Plugin\Admin\AdminBaseController execute
- …/user/plugins/admin/admin.php835
- 51
- Grav\Plugin\AdminPlugin initializeController
- …/user/plugins/admin/admin.php457
- 50
- Grav\Plugin\AdminPlugin onPagesInitialized
- …/vendor/symfony/event-dispatcher/EventDispatcher.php212
- 49
- Symfony\Component\EventDispatcher\EventDispatcher doDispatch
- …/vendor/symfony/event-dispatcher/EventDispatcher.php44
- 48
- Symfony\Component\EventDispatcher\EventDispatcher dispatch
- …/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php23
- 47
- RocketTheme\Toolbox\Event\EventDispatcher dispatch
- …/system/src/Grav/Common/Grav.php403
- 46
- Grav\Common\Grav fireEvent
- …/system/src/Grav/Common/Processors/PagesProcessor.php31
- 45
- Grav\Common\Processors\PagesProcessor process
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php45
- 44
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php57
- 43
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Common/Processors/TwigProcessor.php27
- 42
- Grav\Common\Processors\TwigProcessor process
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php45
- 41
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php57
- 40
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Common/Processors/AssetsProcessor.php28
- 39
- Grav\Common\Processors\AssetsProcessor process
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php45
- 38
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php57
- 37
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Common/Processors/SchedulerProcessor.php29
- 36
- Grav\Common\Processors\SchedulerProcessor process
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php45
- 35
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php57
- 34
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Common/Processors/BackupsProcessor.php28
- 33
- Grav\Common\Processors\BackupsProcessor process
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php45
- 32
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php57
- 31
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Common/Processors/TasksProcessor.php59
- 30
- Grav\Common\Processors\TasksProcessor process
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php45
- 29
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php57
- 28
- Grav\Framework\RequestHandler\RequestHandler handle
- …/user/plugins/admin/classes/Router.php25
- 27
- Grav\Plugin\Admin\Router process
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php45
- 26
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php57
- 25
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Common/Processors/RequestProcessor.php52
- 24
- Grav\Common\Processors\RequestProcessor process
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php45
- 23
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php57
- 22
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Common/Processors/ThemesProcessor.php27
- 21
- Grav\Common\Processors\ThemesProcessor process
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php45
- 20
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php57
- 19
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Common/Processors/PluginsProcessor.php30
- 18
- Grav\Common\Processors\PluginsProcessor process
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php45
- 17
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php57
- 16
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Common/Processors/InitializeProcessor.php95
- 15
- Grav\Common\Processors\InitializeProcessor process
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php45
- 14
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php57
- 13
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Common/Processors/DebuggerProcessor.php27
- 12
- Grav\Common\Processors\DebuggerProcessor process
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php45
- 11
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php57
- 10
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Common/Processors/ErrorsProcessor.php27
- 9
- Grav\Common\Processors\ErrorsProcessor process
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php45
- 8
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php57
- 7
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Common/Processors/LoggerProcessor.php48
- 6
- Grav\Common\Processors\LoggerProcessor process
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php45
- 5
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php57
- 4
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Common/Processors/ConfigurationProcessor.php49
- 3
- Grav\Common\Processors\ConfigurationProcessor process
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php45
- 2
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php57
- 1
- Grav\Framework\RequestHandler\RequestHandler handle
- …/system/src/Grav/Common/Grav.php272
- 0
- Grav\Common\Grav process

**Comment by mahagr** [comment]
The error happens in `admin-frontmatter-yaml` plugin, it is missing a check if the saved object is a page. Please report the issue into the plugin.
