### ISSUE TITLE
Is there a night mode for the admin panel? 

### ISSUE THREAD

**Issue by kalak-sudo** [getgrav/grav-plugin-admin#1993]
Hi!

Simple question: Is there a night mode for the admin panel? 

I have searched for it, with no luck.

Thanks in advanced!

**Comment by rhukster** [comment]
Admin 1.10 which is paired with Grav 1.7 (currently in final RC release) supports themes and there’s a dark version.

**Comment by kalak-sudo** [comment]
And how do I activate or install it??  thanks @rhukster :)

**Comment by kalak-sudo** [comment]
I saw it. It is a normal plugin that has to be installed. Thanks!!
