### ISSUE TITLE
SameSite: None cookie is deprecated errors in JS

### ISSUE THREAD

**Issue by mahagr** [getgrav/grav-plugin-admin#1998]
```
Cookie “cookies.js” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. 
```

To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

In admin we should probably set `SameSite: Strict` as admin pages should not never be linked from an another site.

**Comment by w00fz** [comment]
This is also affecting https://github.com/trilbymedia/grav-plugin-flex-objects
