### ISSUE TITLE
2fa access code corrupted by just saving account

### ISSUE THREAD

**Issue by Andy-Flack** [getgrav/grav-plugin-admin#2000]
Having scrubbed my install and reinstalled the latest 1.7 rc 19
Create a user 
turn on 2fa
note the 2fa code or use the QR scan
save the user

check you can log in as that user using 2fa
log out
log in as an administrative user (not the user in question)

now revisit the users page (you will notice that the 2fa code has changed)
if you hit save at this point you overwrite the correct agreed 2fa code and lock out the user

The twig template cannot see the existing 2fa code so it generates a new code and creates the corruption.

**Comment by mahagr** [comment]
This one has already been fixed and will be in the next 1.7 release.
