### ISSUE TITLE
Copying a page within a parent with no _Create_ permission for the current user

### ISSUE THREAD

**Issue by arkhi** [getgrav/grav-plugin-admin#2002]
In this issue, my assumption is the _Create_ permission allows to create pages within the current one, not siblings of the current page.

This issue uses the same configuration as #2001.

---

I expect the _Copy_ button to not be available on pages which parent have no _Create_ permissions for the current user (or _Copy_ permissions if that was to exist).

1. I login with _limited_ (password: _Limit3d!_).
1. I go to the only page I have _read_ access to (_01.page-1_).
1. I click on the _Copy_ button.
1. A sibling called _01.page-3_ was created although I have no _Create_ permission in the parent page (_03.page-0_).

**Comment by mahagr** [comment]
Fixed in https://github.com/trilbymedia/grav-plugin-flex-objects/commit/96f91fe84eaefaee7d41bd9b61b83c5338f86532
