### ISSUE TITLE
OnAdminMenu hooked page has no access to page.collection

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav-plugin-admin#2009]
I've added a new admin sidebar 'widget' via:

```php
    public function onAdminMenu()
    {
        $this->grav['twig']->plugins_hooked_nav['TODO'] = ['route' => $this->route, 'icon' => 'fa-check'];
    }
```

The page shows up, but `page.collection` is empty. I've set it in the frontmatter:
```
content:
    items: '@root.descendants'
```

With 1.6 this works. The plugin can be found [here](https://github.com/NicoHood/grav-plugin-todo), but it is not documented very well (yet).

**Comment by mahagr** [comment]
Maybe it is worth to check the changes from learn (just in the end of the page): 

https://learn.getgrav.org/16/advanced/grav-development/grav-17-upgrade-guide#admin

```twig
{% do admin.enablePages() %}
```

I think it may work from within the page, if you just call it before collection.

**Comment by NicoHood** [comment]
Nice!!! How could I miss this? Thanks!
