### ISSUE TITLE
Redirect causes scheduler (and other cli commands) to fail

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav-plugin-admin#2010]
Lets assume:
* The admin plugin is set to enabled for localhost only
* No user was added yet
* You want to setup the scheduler using the cli

Any scheduler command (e.g. `./bin/grav scheduler -j`) will then fail, as the cli is treated as a `localhost` environment, the admin plugin is treated as enabled and the redirect stops the cli for continuing:
https://github.com/getgrav/grav-plugin-admin/blob/develop/admin.php#L154

Also see my findings here:
https://github.com/getgrav/grav/issues/2974#issuecomment-753381722

**Comment by rhukster** [comment]
How do you have your admin enabled for localhost only? And why do you have admin enabled at all if there is no user created? What's the point?

**Comment by NicoHood** [comment]
I am using the admin plugin to add pages locally. I commit them to git and push those to the server. By default the admin plugin is disabled, but for localhost it is enabled. The problem is, that the CLI runs under the localhost context and on the server no user is (and will be) created. The cli should run under the server hostname context, if possible.

**Comment by rhukster** [comment]
You are running very much and 'edge case'.  I'm not sure it's worth putting valuable development time into working around this situation when you can easily just create an empty `/accounts/dummy-user.yaml` file in the repo so the check is skipped.

**Comment by NicoHood** [comment]
Sure, but shouldnt the CLI run in a different context?

**Comment by mahagr** [comment]
I just added general support for CLI environments, from the next 1.7 build you can now set `--env=cli` (or environment of your choice) to use the configuration you want to.

**Comment by NicoHood** [comment]
That is a nice idea! Is there also a way to autodetect the host within the cli? I am not sure if this is possible, as the cli runs independent from the php server.

**Comment by rhukster** [comment]
you can't determine the host as there's no webserver to tell you that information. That's why we usually pass an `--env localhost` kinda thing to CLI commands to tell the CLI command the environment to use.

**Comment by NicoHood** [comment]
Okay, cool. I would suggest defaulting to `cli` context then, as I've set several debug options in `localhost` which should not accidentally executed by the cli. Does that make sense to you?

Will this fix get backported for 1.6?

**Comment by mahagr** [comment]
I really wish we had environment aliases.. Like www.site.com -> site.com and cli -> whatever I want.

No, fixes will not be backported into 1.6 anymore, it is at end of its life and I don't have any extra time. I don't think that there's anyone in the team with interest on keeping it up to date as none of us use it. Heck, it doesn't even run in PHP 8 :)

**Comment by NicoHood** [comment]
Alias would be nice. Would you still set `cli` as default?

**Comment by mahagr** [comment]
I can only set `cli` as default if it was alias to `localhost`. Otherwise my test sites break. So yeah, it would be backwards incompatible change.

**Comment by NicoHood** [comment]
Alright, then we should not go for a default, but document the --env somewhere.

**Comment by NicoHood** [comment]
I dont know why, but this has been fixed with grav 1.7 and admin 1.10 for some reason. I dont even need the --env here.

**Comment by mahagr** [comment]
I have fixed some bad redirects when they should never have happened.

**Comment by NicoHood** [comment]
I will close this and report if it causes trouble again
