### ISSUE TITLE
[1.10.0-RC20] After save option not redirecting correctly

### ISSUE THREAD

**Issue by SeriousKen** [getgrav/grav-plugin-admin#2011]
I've enabled the contacts flex object example and when you select either 'Create New Item' or 'List Items' for after save on a new item it does not redirect to the correct page after save.

**Comment by mahagr** [comment]
Can you provide full link (you can omit domain) from the page where you hit the save and the resulting page where you end up, thank you!

**Comment by SeriousKen** [comment]
After creating a new entry and selecting 'List Items' it ends up at /admin/contacts/:add
If I choose 'Create New Item' it ends up at the edit page of the new item (eg /admin/contacts/f0f27f8c43219e0d035e495892d3d8b1)

**Comment by mahagr** [comment]
Fixed in https://github.com/trilbymedia/grav-plugin-flex-objects/commit/38fdaf25ddbb5b626af537431d944f6f5c8602fe
