### ISSUE TITLE
Bad links/redirects in FlexPages admin

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav-plugin-admin#2014]
I was testing and found a couple of issues with FlexPages admin workflow.

1. On a new page I just created, i clicked "Advanced" and made some changes, then clicked "save" it saved but gave a 404 error because it doubled up the page-slug in the URL.

<img width="1308" alt="cleanshot_2021-01-13_at_13 37 46_2x" src="https://user-images.githubusercontent.com/1084697/104512175-09f8c900-55ab-11eb-93e5-1b3db318ceec.png">

2. When previewing a page with the eye icon in the top toolbar, the preview works fine, but the "back" button takes you to the list of pages, and not back the page you were just editing.

**Comment by mahagr** [comment]
Fixed in trilbymedia/grav-plugin-flex-objects@e813674 (the behavior is what happened if you change parent and saved).
