### ISSUE TITLE
Ordering issue with moving pages

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav-plugin-admin#2015]
When you move a page into another page as a child page, the order gets set to 9999999 until save, at which point its gets fixed (to `01.` in my case as it was the only page)

![image](https://user-images.githubusercontent.com/1084697/104632882-906ce380-565b-11eb-9937-14a791aafc64.png)

**Comment by mahagr** [comment]
I cannot reproduce this, may be fixed with #2018?

**Comment by mahagr** [comment]
Yes, getgrav/grav@515eab7 fixes this one.
