### ISSUE TITLE
404 when editing a page and session timeout forces login

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav-plugin-admin#2016]
I was editing a page yesterday and left my browser open. Today i hit save and was prompted to login.  Upon login, i got taken to this url:

```
http://localhost/grav-typhoon-rockets/admin/pages/sample-page/page:/sample-page
```

![image](https://user-images.githubusercontent.com/1084697/104632950-a8446780-565b-11eb-896e-8fa76054dc4a.png)

**Comment by mahagr** [comment]
I cannot reproduce this with existing pages. You will loose any changes you made (and new pages), though...
