### ISSUE TITLE
Wrong saved value of Pages field in multilanguage

### ISSUE THREAD

**Issue by Karmalakas** [getgrav/grav-plugin-admin#2021]
I have two languages - _en_ and _lt_ (_lt_ is the default). I've set up, so that default language wouldn't appear in paths.

I have page where [Pages field](https://learn.getgrav.org/16/forms/blueprints/fields-available#pages-field) is used. In both languages the select options seem fine - _en_ page has a selection of _en_ pages and _lt_ has _lt_ pages listed in select input. But when saved, not only the default _lt_, but also _en_ saves path without the language prefix. Eg., if I have a slug for _lt_ page - _puslapis_ and select this page, saved values are:
- _en_ - `/page`
- _lt_ - `/puslapis`

I'd expect non default language (in this case _en_) to be saved with a prefix, as `/en/page`

Grav v1.7.0-rc.20
Admin v1.10.0-rc.20

**Comment by mahagr** [comment]
I have to investigate this, but no, I don't think it should save the language prefix as the current language is being assumed.

**Comment by Karmalakas** [comment]
What would you suggest as a solution then?
Is the issue in Grav core itself, that prefix is not added when using `{{ page.url|e }}`?

**Comment by ptarmic** [comment]
If I'm understanding your issue correctly then I put `{{ base_url }}` in front of {{ page.url }} (or as a string concatenation `{% set lang_url = uri.base ~ page.url %}`) to resolve this issue. If you're on the default language base_url will be empty and if its another language you'll get `it/`

**Comment by Karmalakas** [comment]
That's a workaround and I wouldn't want to extend every theme template, that uses page links, to fix this :(

**Comment by Karmalakas** [comment]
Was just playing around, and it seems I got a bit confused. `{{ page.ur }}` is fine - it's with the language code. But `{{ page.header.url }}` (which is saved from Admin form by selectin an option in _Pages_ field), is without and that's why the link is wrong.

So it actually isn't a Grav core bug :/ But adding `{{ base_url ~ variable }}` in all templates that uses this, is a bit weird.

If that's how it's supposed to be, feel free to close the issue and I'll know, that concatenation is the way to go.

**Comment by Karmalakas** [comment]
I give up :(

Now no matter how I try, when I save _lt_ version of a page, which is the default language and has a slug different from folder, it still saves the folder name as URL :(

I'm getting desperate here

**Comment by mahagr** [comment]
`{{ grav.pages.route(page.header.linked_page) }}` returns route relative to grav installation.

`{{ grav.pages.url(page.header.linked_page) }}` returns absolute path (second argument adds domain name).

**Comment by ptarmic** [comment]
Thanks Matias I learned something new today.
Also I've found some of my links in 1.7 add an extra language/ to the url when I use `{{ base.url }} {{ page.url }}` so getting rid of using base.url is definately the way to go.

**Comment by mahagr** [comment]
Yes, that is the reason why I added those methods (btw, I forgot to mention that they also support changing the language). They do not check if the page (or route) exists, though.

The constants like `base_url` are great -- as long as you don't have subfolder multi-site or multi-language enabled. If you have those enabled, constants become a nightmare as they are not flexible enough to know the context you're in.

**Comment by Karmalakas** [comment]
> `{{ grav.pages.route(page.header.linked_page) }}` returns route relative to grav installation.
> 
> `{{ grav.pages.url(page.header.linked_page) }}` returns absolute path (second argument adds domain name).

But still in both cases it points to a folder, but not a slug I have defined :( Any chance to get correct URLs right in the `<a>` tags?

**Comment by Karmalakas** [comment]
Just installed Sitemap plugin and noticed `<loc>` holds correct link with the slug, but alternate is wrong - with folder (which, as mentioned, redirects to slug)

```
<loc>.../[slug-based-path]</loc>
<xhtml:link rel="alternate" hreflang="lt" href=".../[folder-based-path]" />
<xhtml:link rel="alternate" hreflang="en" href=".../en/[folder-based-path]" />
```

**Comment by Karmalakas** [comment]
I thought I found a solution/workaround, that could be used in custom templates, but it doesn't work in module templates :/

```twig
{{ pages.find(page.header.linked_page).route }}
```

It appears module doesn't have `pages` object at all :( It's `null`
In other cases I tested this seems to work

**Comment by Karmalakas** [comment]
It seems `page.find()` works fine in modules, so I guess I'll have to stick with
```twig
{{ grav.language.getLanguageURLPrefix(grav.language.getLanguage()) ~ page.find(page.header.url).route }}
```
