### ISSUE TITLE
Editor in fullscreen mode overflows under admin sidebar

### ISSUE THREAD

**Issue by hotdoy** [getgrav/grav-plugin-admin#2022]
![image](https://user-images.githubusercontent.com/11572524/105035801-95e67700-5a29-11eb-8a6c-b9ff76b63e02.png)

**Comment by hotdoy** [comment]
When sidebar is collapsed as well.

![image](https://user-images.githubusercontent.com/11572524/105035897-b6aecc80-5a29-11eb-8017-0e07b6229e03.png)

**Comment by rhukster** [comment]
I will take a look at this

**Comment by hotdoy** [comment]
Thank all.
