### ISSUE TITLE
404 on [page].json/task:listmedia

### ISSUE THREAD

**Issue by brettdewoody** [getgrav/grav-plugin-admin#203]
After uploading an image to the page media section in the admin I get the following console error and an on-screen warning.

**Comment by rhukster** [comment]
Can you please attach the media file in question so I can test it?

**Comment by brettdewoody** [comment]
I have tried it with several `.jpg` files and had the same result with each. As a test, I tried this album cover. 
![actionbronson-mrwonderful](https://cloud.githubusercontent.com/assets/409070/10048977/c44ed70e-61d2-11e5-9839-ab26daa20a07.jpg)

**Comment by rhukster** [comment]
ok, something on your end as it works for me.  Let's get some information on your setup (server, browser, php version, etc)? 

BTW, this will **not work** with build in PHP web server as it doesn't know how to route the `:` in the URL.

Also, if you could look in chrome development tools, under 'network' and filter 'xhr' when you drop the file in to upload.  You should see something in the 'preview' tab that is giving an error. You can see it working fine for me.

![2015-09-23-09-faifr](https://cloud.githubusercontent.com/assets/1084697/10049116/568e7c14-61d3-11e5-8f5a-e92e04b49788.png)

**Comment by brettdewoody** [comment]
Ah, I was trying this on `localhost`. I'll upload and try it on the web.

**Comment by rhukster** [comment]
Well localhost should work fine, as long as it's running Apache or Nginx or something with proper rewrite capabilities.

**Comment by brettdewoody** [comment]
What do you mean by:

> this will not work with build in PHP web server as it doesn't know how to route the : in the URL

Do you mean that if I'm running it on a port with localhost it won't work?

**Comment by rhukster** [comment]
I mean running `php -S localhost:8080`, this is the built in web server, and is not supported.

http://learn.getgrav.org/basics/installation#webserver

**Comment by brettdewoody** [comment]
I typically run it on a different port but that is how I'm testing it. I'll try uploading to a true web server. It sounds like my issue is to running it locally using `php -S localhost:XXXX`.

**Comment by rhukster** [comment]
Yup, definitely the problem, built in webserver is not compatible with admin plugin (and other Grav plugins).  

Just install a proper LAMP/WAMP/MAMP stack on your local computer.  It's way better to develop locally and setting up a local environment is not a big deal.  Before I went to my *homebrew* solution, I used MAMP to good effect.

**Comment by GitHamburg** [comment]
It's a nginx issue about "Nginx pseudo static", you can solve it by adding the rewrite content below to nginx conf.

## Begin - Index
        rewrite ^/your grav subfolder/admin/(\w+).json/(.*)+$ /apps/grav/index.php?$query_string;
        ...
## End - Index
