### ISSUE TITLE
Save Failed, invalid entry: "folder name" - accented characters 

### ISSUE THREAD

**Issue by lolejeun** [getgrav/grav-plugin-admin#2032]
**Hi, me again** 

Thank you for your reactivity and your quick correction! 

When I try to save my changes I get an error message related to the name of the folder "Pensées"(always with an accent) 
with Grav v1.7.1 - Admin v1.10.1

![Capture d’écran du 2021-01-21 19-06-35](https://user-images.githubusercontent.com/28999942/105392797-e58c9480-5c1b-11eb-9316-4da7842a9f8c.png)

Thanks again for the work and good luck!

**Comment by mahagr** [comment]
This should already been fixed in flex-objects plugin v1.0.1 which was out yesterday.

**Comment by lolejeun** [comment]
Hi, I'm sorry but I did the updates well yesterday and I'm currently in Flex Objects v1.0.1

**Comment by APachecoDiSanti** [comment]
Hello, I'm having a similar problem. My folder name doesn't have accents, just English alphabet letters and dash symbols.
When opening an existing page and clicking save again it complains that the input for the "Folder Name" is incorrect.

I found that when opening the page to edit it in the admin plugin it will change the Folder Name value in the Advanced tab and capitalize some words. If I remove the capital letters so the value of the Folder Name field is the same as the real folder name in the server it can save the article successfully.

Maybe something is changing the "Advanced > Field Name" value automatically?

**Comment by lolejeun** [comment]
@APachecoDiSanti Hi, I try and it's exactly the same issue for me! I was able to save my work using your trick, thanks!

**Comment by mahagr** [comment]
@lolejeun By default, the folder name isn't allowed to have accented characters like `äö`. You can change that by overriding slug rule in `default.yaml`.

@APachecoDiSanti Were you trying to save a module page? In that case, you need to look into your theme's blueprints and make sure they do not define the slug rule.
