### ISSUE TITLE
Cannot update to 1.7.2 

### ISSUE THREAD

**Issue by mrtngrsbch** [getgrav/grav-plugin-admin#2033]
I want to do the update v1.7.0-rc.20 > v1.7.2 
but the file https://github.com/getgrav/grav/releases/download/1.7.2/grav-update-v1.7.2.zip does not exist

![ScreenShot 2021-01-21 a las 17 27 57](https://user-images.githubusercontent.com/693328/105408961-752b4680-5c0e-11eb-9a1f-488593090c6f.png)

![ScreenShot 2021-01-21 a las 17 28 21](https://user-images.githubusercontent.com/693328/105408953-70ff2900-5c0e-11eb-9fc7-780fbc35ad68.png)

**Comment by rhukster** [comment]
We pulled the 1.7.2 release due to a bug in the installer post-processing.  Try "Check Updates" now as 1.7.3 is out and has the issue fixed (crossing fingers).

**Comment by mrtngrsbch** [comment]
hummm...
still asking for the 1.7.2 update

![image](https://user-images.githubusercontent.com/693328/105426801-97cb5880-5c2a-11eb-9baf-d7e594513c2c.png)

**Comment by rhukster** [comment]
did you click "Check Updates"? That forces the new repository data to be retrieved.

![CleanShot 2021-01-21 at 17 03 10@2x](https://user-images.githubusercontent.com/1084697/105427528-9b4ee780-5c0a-11eb-853d-8abb82c03c8d.png)

**Comment by rhukster** [comment]
I've not heard back, and no other issues reported.  closing

**Comment by mrtngrsbch** [comment]
thanks @rhukster !
