### ISSUE TITLE
Grav 1.7.3 + Admin 1.10.3, can't change Page template twice and re-save

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#2037]
This is based of a report in the Discourse forum:
https://discourse.getgrav.org/t/cant-save-modification/14835/2

I was able to reproduce it locally with latest 1.7.3 build on Mac Chrome and Firefox.

Steps:
1) Edit page
2) Change page template
3) Save
4) Change page template again
5) Save (this does not seem to work)

Please let me know if any more info is helpful etc.
Paul

**Comment by Karmalakas** [comment]
[Added a comment](https://discourse.getgrav.org/t/cant-save-modification/14835/3?u=karmalakas) on same topic. I also couldn't save a template change no matter what, until I filled _Title_ field in _Content_ tab. Then it saved.

Could it be it won't detect a changed template field and since nothing changes in _Content_ it just says form is saved, but it really isn't?

**Comment by Karmalakas** [comment]
Might be related - https://github.com/getgrav/grav-plugin-admin/issues/2056

**Comment by rhukster** [comment]
I can't replicate this one with the steps provided @paulhibbitts

**Comment by rhukster** [comment]
I'm on Grav 1.7.5 / Admin 1.10.3

**Comment by rhukster** [comment]
BTW this is not related to #2056 that is most certainly an issue for List field only.

**Comment by paulhibbitts** [comment]
Hi @rhukster , here is video to help demo the issue:

https://user-images.githubusercontent.com/1812771/106789679-70e82b80-6607-11eb-94fd-b52c983352fc.mov

I used my most recent build of my skeleton as the test site:
https://github.com/hibbitts-design/grav-skeleton-course-hub/releases/download/v3.2.9/grav-skeleton-open-matter-course-hub-site.zip

Any luck replicating with the above?

Thanks very much,
Paul

**Comment by rhukster** [comment]
I tried even with the leaving and going back to the page like you did, works fine for me.  Please check your "Console" in web dev tools to see if you are getting a JS error.

**Comment by paulhibbitts** [comment]
Hmm... I just tried locally and saw the same issue but nothing in the Console?

![Capto_Capture 2021-02-03_10-27-52_AM](https://user-images.githubusercontent.com/1812771/106792057-8d399780-660a-11eb-9a3c-2449050b6945.png)

i will next try online site just in case.

Thanks,
Paul

**Comment by paulhibbitts** [comment]
Ok, I've done some more testing. For some reason both my Open Course Hub and Open Publishing Space skeletons (using two different themes) show this issue on my end. However, both the Grav Admin and Ole's Project Space do not.

@Karmalakas what skeleton/theme are you having this issue with? Any ideas of what might be going on @rhukster ?

Happy to do more testing etc.
Paul

**Comment by paulhibbitts** [comment]
UPDATE: If I change my active theme to Bootstrap4 (from my inherited theme) Save works! So, perhaps this is some sort of a theme/blueprint issue that might be related to 1.7?

**Comment by paulhibbitts** [comment]
Re: perhaps issue is related to theme blueprints, is there anything off with this one re: 1.7 @rhukster ?

https://github.com/hibbitts-design/grav-theme-bootstrap4-open-matter/blob/master/blueprints/item.yaml

**Comment by Karmalakas** [comment]
I'm using my own very simple theme with only one event and 3 custom template blueprints with standard fields for content editing (3-6 fields each)

```php
    public static function getSubscribedEvents()
    {
        return [
            'onTwigInitialized'     => ['onTwigInitialized', 0],
        ];
    }

    public function onTwigInitialized()
    {
        $twig = $this->grav['twig'];

        $form_class_variables = [
            'form_outer_classes' => 'form-horizontal',
            'form_button_outer_classes' => 'button-wrapper',
            'form_field_wrapper_classes' => 'form-floating',
            'form_field_inline_error_classes' => 'invalid-feedback',
        ];

        $twig->twig_vars = array_merge($twig->twig_vars, $form_class_variables);
    }
```

**Comment by paulhibbitts** [comment]
My themes also have some custom PHP going on:
https://github.com/hibbitts-design/grav-theme-bootstrap4-open-matter/blob/master/bootstrap4-open-matter.php

I've been following all the 1.7RC stuff so I thought no further changes were needed (if this might be related).

What does your page blueprint look like @Karmalakas where you have this issue?

**Comment by Karmalakas** [comment]
> What does your page blueprint look like @Karmalakas where you have this issue?

Oh if only I could remember now :D As soon as I filled a title and it saved, I forgot about it :D But I think it was this template I couldn't save:

```yaml
title: Contact form
'@extends': default

form:
  fields:
    tabs:
      fields:
        content:
          fields:

            header.media_order:
              unset@: true

            header.form_content:
              type: markdown
              label: "Form text"
              validate:
                type: textarea
```

**Comment by paulhibbitts** [comment]
Hey @rhukster @Karmalakas , maybe I have a lead!

I notice that when I've switched to another template, and then that template has required items, a second save (with another template is not working)... for example, here is External:

<img width="1440" alt="2021-02-03_11-44-50" src="https://user-images.githubusercontent.com/1812771/106800407-4309e380-6615-11eb-9a29-3a4083b20e67.png">

And save is not working second time. BUT going to Content I see this:
<img width="1440" alt="2021-02-03_11-44-59" src="https://user-images.githubusercontent.com/1812771/106800452-51f09600-6615-11eb-8222-56740e91ad20.png">

Which I think was preventing the change to template (second time) being saved... any thoughts? Can you confirm @Karmalakas ?

**Comment by mahagr** [comment]
Required fields do prevent the save button from firing, so it is what happens here. When you change the type, Grav only renames the file and reloads the page. When you try to save a second time, your page does not pass the tests and you cannot click the save button. 

This is what is expected and happened with older versions, too.

I think that there should be some warning if required fields are failing in other tabs, I find it annoying that the button just stops working without any indication of what is going on.

Also in the future, changing the page template should probably reload the page with the new form fields pre-filled with the current data from your browser.

**Comment by paulhibbitts** [comment]
Thanks very much for looking into it and verifying the behaviour @mahagr . Your idea of some sort of indication of why the save fails sounds helpful too.
