### ISSUE TITLE
Grav 1.7.3 + Admin 1.10.2 - Display labels names and not values

### ISSUE THREAD

**Issue by AnaelMobilia** [getgrav/grav-plugin-admin#2038]
Hello,

I just update to latest version of grav and plugin admin on a shared website hosting (OVH).
All the labels on the admin are now displayed as name and not values :
![image](https://user-images.githubusercontent.com/6187125/105578712-5ea5fc00-5d82-11eb-8367-0785d8f3ab97.png)

I tried to clean the cache, no results.

Plugins : 
![image](https://user-images.githubusercontent.com/6187125/105578732-85643280-5d82-11eb-9aad-7726f2a8d8f6.png)

Hosting environement : PHP 7.3.20, all clean on report tool.

See maybe related #1763 

Bests regards,
Anael

**Comment by rhukster** [comment]
Make sure you have not disabled "Translations" in the "Languages" section of the System configuration. It looks like that's turned off.

**Comment by AnaelMobilia** [comment]
Nice catch !
Admin -> Configuration -> Languages -> Translation & Translations fallback was to "No".
Put it to yes, logout & login solve the issue.

Thanks @rhukster !

**Comment by jonata** [comment]
Yes, same here. Changing `PLUGIN_ADMIN.LANGUAGE_TRANLATIONS` to `PLUGIN_ADMIN.YES` solves the issue.

![teste](https://user-images.githubusercontent.com/908065/105908638-38dc5980-6005-11eb-968d-41baa75c6c08.png)

**Comment by rhukster** [comment]
Documented this here: https://learn.getgrav.org/17/advanced/grav-development/grav-17-upgrade-guide#untranslated-admin
