### ISSUE TITLE
php code block breaking site

### ISSUE THREAD

**Issue by mabushey** [getgrav/grav-plugin-admin#204]
I ran into another issue where this code block killed the site:

This config automatically scans all sites in `/var/www/html` and makes an alias out of the subdomain. Additionally it detects if there is a www folder inside the site folder.

`/etc/drush/aliases.drushrc.php`:

```
<?php
$sites = array_diff(scandir('/var/www/html'), array('..', '.'));
foreach ($sites as $val) {
  $tmp = explode('.', $val)[0];
  if (file_exists("/var/www/html/${val}/www")) {
    $aliases[$tmp]['root'] = "/var/www/html/${val}/www";
  } else {
    $aliases[$tmp]['root'] = "/var/www/html/${val}";
  }
  $aliases[$tmp]['uri'] = "http://${val}";
  $aliases[$tmp]['path-aliases']['%drush'] = '/usr/bin';
  $aliases[$tmp]['path-aliases']['%site'] = 'sites/default/';
}
```

**Comment by rhukster** [comment]
Pretty sure this is related to the `summary()` method and more specifically the `truncateHTML()` method used in there.  I think it's splitting in the middle of your PHP code leaving a dangling mess.

**Comment by flaviocopes** [comment]
Yes, tested a bit - if you remove the PHP opening tag, for some reason it works.
Should we remove all <pre> tags prior to calling truncate()? Or just strip all tags except the normal text tags?

**Comment by rhukster** [comment]
I would rather get it working 'with' pre tags. It could turn out to be complicated though.
