### ISSUE TITLE
Admin panel display issues after update

### ISSUE THREAD

**Issue by asimanov** [getgrav/grav-plugin-admin#2042]
Every control is prefixed with PLUGIN_ADMIN. Any ideas on how to fix this? Everything works aside from this.
![Screenshot 2021-01-26 125945](https://user-images.githubusercontent.com/4551400/105904874-91e0c900-5fd6-11eb-8d2c-62d53cec8c19.png)

**Comment by petira** [comment]
Look here #2038

**Comment by asimanov** [comment]
@petira thank you! That was it, configuration -> translations -> "yes" fixed this without further issues. Thanks again!
