### ISSUE TITLE
Label names has disappeared.

### ISSUE THREAD

**Issue by ctuluxfr** [getgrav/grav-plugin-admin#2043]
Hello,

I upgraded my website to the last version of Grav and also the latest version of Grav plugins. But once the update was done, I'm encountering some troubles with the admin plugin.

![Capture](https://user-images.githubusercontent.com/78078206/105973236-ca42de80-608c-11eb-9694-bb8d14dc70e7.PNG)

I don't know what to do. I think I should reinstall the plugin but this will erase most of my data.

Can someone help me ?

Sincerly,
ctuluxfr

**Comment by rhukster** [comment]
https://learn.getgrav.org/17/advanced/grav-development/grav-17-upgrade-guide#untranslated-admin
