### ISSUE TITLE
Modular underscore Folder Names not accepted by Admin

### ISSUE THREAD

**Issue by knoidy** [getgrav/grav-plugin-admin#2044]
I'm not a professional theme developer but I have been trying to modify a theme that doesn't include modular pages to be able to create very simple modular pages within the chosen theme.  I've been able to clear most hurdles to be able to render module.content|raw on pages.  When directly editing files I can create and process modular pages and they appear as intended.  However when i try to pull up modules i've already created elsewhere, then try to save in admin, I get the attached error message: "Folder name invalid" - even though the folder already exists.  I know this is a problem with theme compatibility because I can build modular pages with admin fine on other themes.

However, I can't figure out what validation error this is to be able to resolve it for my modified theme.  I can't even imagine what piece of the theme i need to fix, looking through the admin plugin repo doesn't give me any further signs either as to what is the problem with validation.  Potentially that the "slug" validation for folder names has some kind of bypass at the theme level?

Anyway, I think this validation is potentially too strict and should be altered to always accept the preceding underscore, the modular pages work on the site it's just admin that is causing the issue by not validating the folder name

![chrome_7Gqmiv0fb5](https://user-images.githubusercontent.com/77756972/105984963-17588d80-6058-11eb-9ba6-0fa34dcae273.png)

**Comment by rhukster** [comment]
How about attaching the the theme as a zip so we can take a look?

**Comment by knoidy** [comment]
[hypertext.zip](https://github.com/getgrav/grav-plugin-admin/files/5882407/hypertext.zip)

**Comment by mahagr** [comment]
You need to remove the slug rule in `blueprints/default.yaml` (and use Grav default).

**Comment by knoidy** [comment]
@mahagr that fixed it!
