### ISSUE TITLE
Creating pages with a field type of 'file' breaks on save

### ISSUE THREAD

**Issue by hdwebpros** [getgrav/grav-plugin-admin#2046]
I now see this error when trying to save:
Save Failed: Cannot set nested property header introimage imagename.jpg on non-array value

Grav v1.7.3 - Admin v1.10.2 Flex Objects 1.0.1

Disabling Pages (Admin) in the flex objects plugin solved my issue.

**Comment by mahagr** [comment]
I need an example of how to reproduce this error. Blueprint file and some walkthrough on a clean install would do it.

**Comment by mahagr** [comment]
Duplicate of #1967

**Comment by mahagr** [comment]
Fixed in https://github.com/getgrav/grav/issues/3191
