### ISSUE TITLE
Confusing page order based on folder name

### ISSUE THREAD

**Issue by DerSev** [getgrav/grav-plugin-admin#2048]
Hello grav team!

After the upgrade from grav 1.6 to 1.7 my page order seems to got mixed up in the admin panel _(Grav v1.7.3 – Admin v1.10.2)_.
The page order now seems to be based on all leading numbers, what is very confusing to me.

The „Default ordering“ ist set to „Default - based on folder name“ and „Folder Numeric Prefix“ is set to „Disabled“.

**# now _(1.7)_ it is**
/000asd
/01asd
/02asd
/008asd
/9asd
/012asd
/15asd
/023asd
/0070asd
/99asd
/asd

**# before _(1.6 and preferred)_ it was**
/000asd
/0070asd
/008asd
/012asd
/01asd
/023asd
/02asd
/15asd
/99asd
/9asd
/asd

It would be nice to have the „old“ behaviour back, or to have the choice in setup.

Thanks.

**Comment by mahagr** [comment]
This was actually a bug when using `intl` PHP extension, without the extension it used to behave just like it does now. Grav uses natural ordering where numbers in the string are treated as people order them naturally: 1 < 10 < 100 < 1000.
