### ISSUE TITLE
Statistics: Call to a member function trackHit() on null

### ISSUE THREAD

**Issue by schnumsel** [getgrav/grav-plugin-admin#2049]
Hi there,

The statistics is working properly, page views get counted. Nevertheless there are frequent entries in my log files saying:

```
NOTICE: PHP message: PHP Fatal error: Uncaught Error: Call to a member function trackHit() on null in [...]/user/plugins/admin/admin.php:425"
```
See  [here](https://github.com/getgrav/grav-plugin-admin/blob/17d425fef95774f026787e0446d0925337a4bf98/admin.php#L424-L426) for details.

So if i understand correctly, although the popularity module is enabled the popularity member is not instatiated.

How can this be?

Best regards,

Willi

**Comment by mahagr** [comment]
It likely happened when running a task.

**Comment by schnumsel** [comment]
Thanks a lot! I made a workaround just that way, should have done a PR, next time:)
