### ISSUE TITLE
Links from admin panel to plugin repos that don't use 'develop' branch 404

### ISSUE THREAD

**Issue by z3cka** [getgrav/grav-plugin-admin#205]
The plugin data template partial hard codes the link to the plugin's README.md file:

https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/templates/partials/plugin-data.html.twig#L56

Some plugins, like the [private](https://github.com/Diyzzuf/grav-plugin-private) plugin, are using the ```master``` branch so the link is not found.

Is this something that the admin plugin should handle better or should this be a standard that is documented?

**Comment by z3cka** [comment]
The [Github Setup](http://learn.getgrav.org/advanced/grav-development#github-setup) section of the Grav documentation mentions that Grav development uses the [gitflow](http://nvie.com/posts/a-successful-git-branching-model/) methodology. This mentions the use of the 'develop' branch. Maybe we should put a warning that the readme link in the admin's plugin page will not link properly if this pattern is not followed.

**Comment by rhukster** [comment]
This is a known issue, it's just quite 'expensive' (read **slow**) to find out the default branch for each plugin.

**Comment by z3cka** [comment]
Would it make sense for admin to point to `master` instead? ... as:
1. the `master` is the branch that get's tagged
2. new documentation on `develop` may not be accurate to the version of the plugin being used

Agreed that dynamically figuring the default branch via github API is too slow and expensive.

**Comment by rhukster** [comment]
Actually that probably would make sense.  I'll leave it open to remind me to change to master.

**Comment by Sommerregen** [comment]
Actually, pointing admin to `master` instead is a good idea. The `master` branch unlike the `develop` branch always exists! :smile: 

@rhukster BTW: Currently the file to the README for a plugin can be set using the `readme` option. But I would like to consider the `docs` option, too, since it is used by [getgrav.org](getgrav.org) anyhow.
