### ISSUE TITLE
Language not loading

### ISSUE THREAD

**Issue by Psychoxell** [getgrav/grav-plugin-admin#2050]
Hi after updating to the newest version my admin center is not loading any languages and looks like this 
![image](https://user-images.githubusercontent.com/46071136/106359860-83b3e500-6315-11eb-9d16-0ad0e22c2a6a.png)

How can i fix this?

My default langauge was english

**Comment by rhukster** [comment]
https://learn.getgrav.org/17/advanced/grav-development/grav-17-upgrade-guide#troublshooting-issues

**Comment by Psychoxell** [comment]
i tried everything of this link. Everything else is working. Just not the admin plugin. But ok. better close a ticket..
