### ISSUE TITLE
Deleting list field options completely, won't save changes

### ISSUE THREAD

**Issue by Karmalakas** [getgrav/grav-plugin-admin#2056]
If I remove all items under _Configuration > Languages > Content Language Fallback_ and click "Save", item just reappears

Grav 1.7.5
Admin 1.10.3

**Comment by Karmalakas** [comment]
Might be related to [this issue](https://github.com/getgrav/grav-plugin-admin/issues/2037)

**Comment by mahagr** [comment]
I can reproduce this with Grav 1.6 and admin 1.9 as well.

**Comment by mahagr** [comment]
I found the reason, which is that the admin isn't using the form plugin but relies on the old method of merging two arrays together. It is not a reliable method and was replaced everywhere else than in admin.
