### ISSUE TITLE
language constants showing in Admin

### ISSUE THREAD

**Issue by skinofthesoul** [getgrav/grav-plugin-admin#2057]
I have just updated one of my Grav installations and now there are language constants all over my Admin pages. Here is a screenshot:
![grav-admin-language-constants](https://user-images.githubusercontent.com/16343870/106775193-2f757180-6643-11eb-835e-cb7059dad78a.jpg)

Reverting to Admin v1.10.2 did not help (neither did clearing the cache). I'll try other versions and report back.

**Comment by rhukster** [comment]
https://learn.getgrav.org/17/advanced/grav-development/grav-17-upgrade-guide#untranslated-admin

I'm amazed how many people toggled that option to disable the translation of strings!
