### ISSUE TITLE
Incomplete styling appearance after upgrade 

### ISSUE THREAD

**Issue by AwebsomeFr** [getgrav/grav-plugin-admin#2058]
Hi,

I have a issue with **grav 1.7** and **grav-admin v1.10.3**.

![grav screenshot](https://user-images.githubusercontent.com/49813904/106924106-0ae6cb80-670f-11eb-81b6-cd323583699b.png)

Some styles are **missing**, I guess. And it seems that the viewport is fixed to 100vh, so everything is beyond is hidden (no scroll), which makes the interface unusable. 

It is similar to this [issue #2035](https://github.com/getgrav/grav-plugin-admin/issues/2035) (except I don't have any installed plugin like imagecreate).

If it can help, here the full list on my plugins :

* Admin Panel - v1.10.3
* DevTools - v1.4.2
* Email - v3.1.1
* Error - v1.7.1
* Flex Objects v1.0.2
* Form v4.3.1
* Login v3.4.0
* Problems v2.0.3

I updated these plugins one by one from the interface. Everything was OK until I updated the plugin-admin (in last).

Tested on Firefox and Chrome (with refreshing the cache). With no result. 

Any idea ?
Thanks !

**Comment by rhukster** [comment]
Do you have an `assets/` folder at the root of your Grav and is it writable?  This could be the cause as Admin 1.10 dynamically generates an `assets/admin-preset.css` based on the configuration in the Admin plugin.

**Comment by AwebsomeFr** [comment]
@rhukster My bad.

The problem was elsewhere.

By playing with `admin-preset.css`, with no repercussion, I realized that something was wrong.

I had tried hard refreshes and deletion of browsing data. But it was necessary to **purge Grav's cache FROM its interface**.

Everything is back to normal now.
Thank you very much for your help (and for your work, obviously) !

**Comment by mahagr** [comment]
@rhukster I've seen the same issue sometimes after upgrading from Admin 1.9 to 1.10. It is quite random though, sometimes it fails. To reproduce this I just downloaded some older version (grav+admin) and updated it from the admin plugin.

**Comment by rhukster** [comment]
I have done that many times and not been able to reproduce it. :(

**Comment by arkhi** [comment]
The issue still exists on v1.7.12. It seems the `assets/admin-preset.css` is generated with no content.

**Comment by rhukster** [comment]
It’s been fixed now in develop.  We should have a release out soon.

**Comment by arkhi** [comment]
After upgrading Grav (v1.7.13) and its plugins (Admin v1.10.13) to the latest version with GPM, purging all cache with the UI of the admin plugin or the CLI with `bin/grav cache-clear` or `rm -Rf cache/*`, logging out and clearing all cookies and browser data, I have a style-less admin:

![image](https://user-images.githubusercontent.com/277773/116053780-56a87180-a67b-11eb-9c47-22459ddab2f9.png)

`bin/grav security` and `bin/grav yamllinter` show no error.

@xaa, I see you showed some love to the previous comment; are you impacted after upgrading?

**Comment by arkhi** [comment]
The problem does not appear when developing locally on my vagrant box though (which known latency issues when doing codeception tests, if I remember well). :shrug:

**Comment by xaa** [comment]
hi @arkhi, 
You've right I had similar issue before updating to Grav v1.7.13 - Admin v1.10.13. It seems fixed after updates.

Are you sure the /assets folder is writable in your project ? 

Here, the assets/admin-presets.css is deleted if clearcache from the backend or cli.

**Comment by arkhi** [comment]
Thanks for your feedback, @xaa.

> Are you sure the /assets folder is writable in your project ?
>
I am sure. :/

I applied the permissions as stated in the documentation 
<https://learn.getgrav.org/17/troubleshooting/permissions> and Grav does 
not complain about wrong permissions. _assets/admin-presets.css_ is 
generated, it’s just empty like before.

$ ls -la assets/
total 96
drwxrwxr-x  2 me       www-data  4096 Apr 26 10:57 .
drwxrwxr-x 16 me       www-data  4096 Apr 26 10:48 ..
-rw-rw-r--  1 me       www-data    84 Apr 20 19:05 .gitkeep
-rw-r--r--  1 www-data www-data 40436 Apr 26 10:57 18b322aa4ad552f6331d358be2831e81.css
-rw-r--r--  1 www-data www-data 41308 Apr 26 10:57 252121091e6983fca22c8bcae32f8277.js
-rw-r--r--  1 www-data www-data     0 Apr 26 10:53 admin-preset.css

**Comment by mahagr** [comment]
@arkhi 
I would say that there's SCSS compilation error. Maybe some of your plugin settings don't compile properly?

**Comment by arkhi** [comment]
Thank you @mahagr; you’re a real time saver.

I initially added scss files from plugins in _.gitignore_ and they were missing when deploying; the idea was that scss files should be compiled before being deployed. Deployments were working until now but I guess the introduction of the new admin plugin in the v1.7 changed the way things are working.

Thanks again.
