### ISSUE TITLE
Trying to access array offset on value of type null in user/plugins/admin/classes/adminbasecontroller.php

### ISSUE THREAD

**Issue by gebeer** [getgrav/grav-plugin-admin#2059]
Hello,
after aupgrading grav to 1.7.5 and admin plugin to 1.10.3 when I changelangauge settings in configuration and attempt to save, I get following error:
`Trying to access array offset on value of type null in user/plugins/admin/classes/adminbasecontroller.php`
responsible is code on lines 683-84:
```
        $queue = $this->admin->session()->getFlashObject('files-upload'); // this returns null
        $queue = $queue[base64_encode($this->grav['uri']->url())]; // this throws error
```
After moving line 684 into the if statement, error is gone:
```
        $queue = $this->admin->session()->getFlashObject('files-upload');
        if (is_array($queue)) {
            $queue = $queue[base64_encode($this->grav['uri']->url())];
```
Not sure if this quickfix is a solid solution.

Running grav through php cli version 8.0.2 on localhost

**Comment by mahagr** [comment]
Admin plugin does not have file `/classes/adminbasecontroller.php` and installer should remove the old Admin 1.9 file. Did you copy the files manually? Maybe uninstall the plugin and try to install it again.

**Comment by gebeer** [comment]
> Admin plugin does not have file `/classes/adminbasecontroller.php` and installer should remove the old Admin 1.9 file. Did you copy the files manually? Maybe uninstall the plugin and try to install it again.

I was wondering about that, too. I had updated plugins via gpm. In the admin's plugin list, version is shown as 1.10.3. But code seems to be from 1.9 which is really strange.
