### ISSUE TITLE
Toggleable checkboxes load with wrong state inside of fieldset columns

### ISSUE THREAD

**Issue by rcheetah** [getgrav/grav-plugin-admin#2063]
Well, I admit this is very very specific, but still a bug. It's hard to find a short title for this issue ^^

If you have a structure roughly like: **Fieldset > Columns > Toggleable field**, then all frontmatter values are loaded correctly into the fields, but the toggleable fields are not initialized correctly. So fields that actually contain a value should be active with a ticked checkbox, but are not.

See the screenshot attached. In the example there are 4 fields. 2 of them are not in columns, 2 are in columns. As you can see, if this structure is inside a fieldset, then the toggleable fields are not checked correctly. If the structure is outside a fieldset, then everything works as expected.

![grav-plugin-form-bug](https://user-images.githubusercontent.com/15356984/106201769-37ec2900-61b9-11eb-837a-53c06cdf506e.png)

**Comment by mahagr** [comment]
@rcheetah This one was admin bug, should be fixed now.

**Comment by rcheetah** [comment]
Awesome!
