### ISSUE TITLE
Is the Crowdin translation dead?

### ISSUE THREAD

**Issue by lufog** [getgrav/grav-plugin-admin#2064]
Can you explain please how to translate this plugin? If you do this through GitHub, commits are not merging as the translation is done through the Crowdin service. But the strings added in new versions of Grav Admin are simply missing there. And this has been going on for over a year.

**Comment by rhukster** [comment]
yes, i've been behind on this.  I will update the English version very soon.

**Comment by rhukster** [comment]
I've updated the english source file.  https://crowdin.com/project/grav-admin

Apology note! https://crowdin.com/project/grav-admin/discussions/10
