### ISSUE TITLE
[Firefox] "Add page modal" auto-closes when using dropdown

### ISSUE THREAD

**Issue by newick** [getgrav/grav-plugin-admin#2065]
When I want to add a page, I fill the name, etc. and when I want to choose my template the modal closes itself. 
If I click on the "Add" button it opens it already filled but it's quite disturbing.

I tested on Chrome, and can reproduce it.

**Comment by mahagr** [comment]
@w00fz Didn't you already have a fix for this one? I can confirm that it's still an issue.

**Comment by w00fz** [comment]
See my comment here https://github.com/getgrav/grav-plugin-admin/issues/2089#issuecomment-802374767
