### ISSUE TITLE
For apply the language change is necessary to logout and login again

### ISSUE THREAD

**Issue by petira** [getgrav/grav-plugin-admin#2066]
For apply the language change is necessary to logout and login again. Just saving after a change is not enough.

Grav v1.7.5 - Admin v1.10.3

**Comment by mahagr** [comment]
This is known as by default the user information will not be updated during the session. There's an option in the login plugin to read the user data from the file on every request.

**Comment by petira** [comment]
Thanks for the explanation. It works.
