### ISSUE TITLE
Error after updating Grav 

### ISSUE THREAD

**Issue by beamaria** [getgrav/grav-plugin-admin#2074]
I've just updated Grav to version 1.7.6 and four related plugins (admin, flex objects, login and form)
I use also a Gantry 5 paid theme (and of course Gantry 5 plugin,latest version)
After the uptdate I have this "Critical error" message
0 - Argument 2 passed to Grav\Plugin\Admin\Admin::mergePost() must be of the type array, string given, called in /Applications/MAMP/htdocs/2febbraio/user/plugins/admin/classes/plugin/Admin.php on line 919

I'm working in local environment, but I need to go live ASAP

As I'm not sure if this is a Gantry5 or a GRAV issue, I opened a new issue in gantry/gantry5 repository as well
 gantry/gantry5#2763

**Comment by Sumeragi85** [comment]
Got the same error after upgrading. I get the error if I try to edit an image in a slide. Steps to reproduce:

Go to Gantry 5 => click on tab "Layout" => click on gear symbol of slide particle => at the particle tab click on "Particle Items" =>click on an item to edit it

Error that is shown:

> Server Error
> Sorry, something went terribly wrong!
> 
> 0 - Argument 2 passed to Grav\Plugin\Admin\Admin::mergePost() must be of the type array, string given, called in /home/handwdbn/grav/user/plugins/admin/classes/plugin/Admin.php on line 919
> For further details please review your logs/ folder, or enable displaying of errors in your system configuration.

Here is my stacktrace

`[2021-02-18 12:38:30] grav.CRITICAL: Argument 2 passed to Grav\Plugin\Admin\Admin::mergePost() must be of the type array, string given, called in /home/hand/grav/user/plugins/admin/classes/plugin/Admin.php on line 919 - Trace: #0 /home/hand/grav/user/plugins/admin/classes/plugin/Admin.php(919): Grav\Plugin\Admin\Admin->mergePost(Object(Grav\Common\Data\Data), '{"title":"New i...') #1 /home/hand/grav/user/plugins/admin/classes/plugin/Admin.php(272): Grav\Plugin\Admin\Admin->data('media') #2 /home/hand/grav/user/plugins/admin/admin.php(1069): Grav\Plugin\Admin\Admin::configurations() #3 /home/hand/grav/user/plugins/admin/admin.php(247): Grav\Plugin\AdminPlugin->initializeAdmin() #4 /home/hand/grav/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Grav\Plugin\AdminPlugin->onPluginsInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onPluginsInitia...', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #5 /home/hand/grav/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPluginsInitia...', Object(RocketTheme\Toolbox\Event\Event)) #6 /home/hand/grav/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'onPluginsInitia...', Object(RocketTheme\Toolbox\Event\Event)) #7 /home/hand/grav/system/src/Grav/Common/Grav.php(550): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(RocketTheme\Toolbox\Event\Event), 'onPluginsInitia...') #8 /home/hand/grav/system/src/Grav/Common/Processors/PluginsProcessor.php(36): Grav\Common\Grav->fireEvent('onPluginsInitia...') #9 /home/hand/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\PluginsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #10 /home/hand/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #11 /home/hand/grav/system/src/Grav/Common/Processors/InitializeProcessor.php(129): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #12 /home/hand/grav/system/src/Grav/Common/Debugger.php(546): Grav\Common\Processors\InitializeProcessor::Grav\Common\Processors\{closure}() #13 /home/hand/grav/system/src/Grav/Common/Processors/InitializeProcessor.php(130): Grav\Common\Debugger->profile(Object(Closure)) #14 /home/hand/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\InitializeProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #15 /home/hand/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #16 /home/hand/grav/system/src/Grav/Common/Grav.php(295): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #17 /home/hand/grav/index.php(58): Grav\Common\Grav->process() #18 {main} [] []`

**Comment by beamaria** [comment]
@Sumeragi85 : thanks, this is exactly what happens; if you try to use a Gantry 5 particle which fetches its content directly from GRAV you have this error

**Comment by beamaria** [comment]
@mahagr : Thanks Mathias!
