### ISSUE TITLE
Add a button "View Changelog" for motor update

### ISSUE THREAD

**Issue by AnaelMobilia** [getgrav/grav-plugin-admin#2076]
Hello,

Now, the admin plugin add the button "View Changelog" on plugins, which open a pop-up with the Changelog.
It would be nice to add this button for grav motor updates too.

Bests regards

**Comment by rhukster** [comment]
<img width="1438" alt="CleanShot 2021-02-24 at 09 49 56@2x" src="https://user-images.githubusercontent.com/1084697/109035234-ab346e00-7685-11eb-808d-674a0a3d5f49.png">

Check the "info" tab in system settings.
