### ISSUE TITLE
first supported language overrides user's preferred language in Tools section

### ISSUE THREAD

**Issue by qasedak** [getgrav/grav-plugin-admin#2077]
there's a bug, when user's preferred language differs from site first supported language in Tools section and some other sections like Alerts above the page, text are displayed in site first supported language... 
![Screenshot 2021-02-20 190930](https://user-images.githubusercontent.com/9540896/108601042-bb133000-73af-11eb-9e94-c94498d70593.png)

**Comment by w00fz** [comment]
This has been confirmed by several people

**Comment by mahagr** [comment]
Login and logout still show messages in the wrong language, mostly because the language changes only after the message has been generated.
