### ISSUE TITLE
Error in files.js

### ISSUE THREAD

**Issue by Karmalakas** [getgrav/grav-plugin-admin#2079]
My code editor (PHP Storm) shows an error in [_/themes/grav/app/forms/fields/files.js_ on line 90](https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/app/forms/fields/files.js#L90). Unnecessary closing bracket `)`. After removing this bracket file becomes clean of errors.

Not sure if I'm missing something or it really is a bug. Admin seems to be working fine with file uploads, so it just brings more confusion. I'm glad to create a PR if it really is a bug

![image](https://user-images.githubusercontent.com/3602819/108624950-cb2f1c00-7450-11eb-9c57-94ad4f3e0a78.png)

**Comment by w00fz** [comment]
Thanks, I somehow missed that
