### ISSUE TITLE
Issues with multiple themes using themer plugin

### ISSUE THREAD

**Issue by cord** [getgrav/grav-plugin-admin#208]
the editor can only handle one theme - the active one.

so it is not possible to create a new page with a different template type as contained in the active theme.

I think it should be possible to have multiple active themes and then select the default theme.

**Comment by rhukster** [comment]
At this time we're not going to add support for multiple concurrent themes to the admin.  It just complicates things too much, especially as this plugin is a 3rd party one, and not a part of grav core functionality.

We may revisit this again in the future, but closing for now.
