### ISSUE TITLE
Bugfix (?): changes in pages.html.twig

### ISSUE THREAD

**Issue by ChristianaHoJo** [getgrav/grav-plugin-admin#2093]
There must be two changes in **_user/plugins/admin/themes/grav/templates/pages.html.twig_** to make the folder field
automatically changed related to the entry of the title field again  when clicking "**add new module**" button.

**Button:**

old:

`{% if admin.modularTypes is not empty %}
                        <li><a class="button" href="#modular" data-remodal-target="modular">{{ "PLUGIN_ADMIN.ADD_MODULE"|tu }}</a></li>
                    {% endif %}`

new:

` {% if admin.modularTypes is not empty %}
                        <li><a class="button" href="#module" data-remodal-target="module">{{ "PLUGIN_ADMIN.ADD_MODULE"|tu }}</a></li>
                    {% endif %}`

**Modal:**

old:

`  <div class="remodal" data-remodal-id="modular" data-remodal-options="hashTracking: false">
        {% include 'partials/blueprints-new.html.twig' with { blueprints: admin.blueprints('admin/pages/modular_new'), data: obj_data, form_id:'new-modular' } %}
    </div>`

new:

` <div class="remodal" data-remodal-id="module" data-remodal-options="hashTracking: false">
        {% include 'partials/blueprints-new.html.twig' with { blueprints: admin.blueprints('admin/pages/modular_new'), data: obj_data, form_id:'new-modular' } %}
    </div>`

**Comment by mahagr** [comment]
I do not understand what is the issue. Can you explain what is broken?

**Comment by mahagr** [comment]
Not sure why it works for me. Tried both in the list and edit views.

**Comment by mahagr** [comment]
@w00fz @rhukster @ricardo118  Can you guys test this for me?

**Comment by rhukster** [comment]
Unless i'm missing something, the only change I see is the target modal ID and the link have changed.  This should not impact anything.

**Comment by ChristianaHoJo** [comment]
Yes and the correct ids make the javascript work that fills the folder title exactly at the time user writes into the title field.

**Comment by rhukster** [comment]
Ok so sounds like a change in the IDs, has broken a bit of JS.  Assigning our JS guru....

**Comment by w00fz** [comment]
@ChristianaHoJo Are you using the legacy Pages instead of Flex Pages? This issue was reported a long time ago and fixed in Nov 2020 (https://github.com/getgrav/grav-plugin-admin/issues/1937) as we approached Grav 1.7 and Admin 1.10.
But maybe you are not using Flex Pages and we missed this?

I have applied the changes you suggested, this should be better now.

**Comment by ChristianaHoJo** [comment]
@w00fz yes, we don not use flex pages. The project exists since 2018 and the more than 1000 pages with modulars and blog entries.  Don't know of it is possible to convert them without any problems.

**Comment by mahagr** [comment]
If you don't have plugins affecting admin, you can just enable Flex Pages from the Flex Objects plugin and it should work. It only affects the admin part of the site, Flex isn't used by the site just yet. 

If there are plugins that change admin, at this point most of those work, but may need some testing. There may be some changes needed though, even if everything works, to take advantage of the new classes.

I recommend trying Flex Pages admin (in a test site to be on the safe side) as it already fixes many issues over the old admin and adds new features, too. If something breaks, just report those issues as bugs and we look into those.
