### ISSUE TITLE
A user with update access can change its own ACL permissions

### ISSUE THREAD

**Issue by arkhi** [getgrav/grav-plugin-admin#2094]
This issue uses the same configuration as #2001. Versions used are:

- Grav v1.7.7
- Admin Panel v1.10.6
- Email v3.1.1
- Error v1.7.1
- Flex Objects v1.0.3
- Form v5.0.0
- Login v3.4.1
- Markdown Notices v1.1.0
- Problems v2.0.3

---

As I understand ACL, a user should not be able to update its permissions except, maybe, for a super user. This is possible with Grav Admin plugin by following these steps:

1. I login with _limited_ (password: _Limit3d!_).
1. I go to the only page I have _read_ and _update_ access to (_01.page-1_).
1. I click on the _Expert_ button.
1. I update the value of `permissions.groups.authors.delete` from `false` to `true`.
1. I save the page.
1. I delete the page:
    - The page is deleted successfully with the message _Directory Entry removed successfully_.
    - I am redirected to /admin/pages/page-0 with a _Error 403_.

**Comment by mahagr** [comment]
@rhukster Should we disable expert mode from everyone else but super users? I'm asking this because expert mode saves YAML just like it was written into the text field without any other checks than YAML syntax errors and some XSS checks.

**Comment by arkhi** [comment]
Although I like the idea of disabling the expert mode for some, maybe making it configurable with an `access.edit_mode: (expert|false)` like the existing [PHP check in Page.php](https://github.com/getgrav/grav/blob/0d1c63f0fdfbdf2b9c1802895076a67cd5eb2ebd/system/src/Grav/Common/Page/Page.php#L1215) would be good?

**Comment by mahagr** [comment]
Well, the main issue with the expert mode is that it gives you raw access to the page. That means you can see every header variable on the page and you can modify it, no questions asked. As it bypasses all the security checks, I am not sure when we should expose it to the user.

IMHO configuration option should not override ACL. That said, the check does need to be updated so that it has no effect when the user isn't allowed to see raw mode.

**Comment by arkhi** [comment]
I had this problem with my Grav 1.6 pages-permissions plugin. I’m not a PHP developer so my solution might seem to work for me and not actually be good, but I tackled the issue by defining [locked properties](https://github.com/arkhi/grav-plugin-admin-pages-permissions#locked-properties).

**Comment by mahagr** [comment]
I do not like the locked properties approach for the same reason: users should not be able to see everything from the file. It also doesn't really work if the user can add an infinite amount of new properties which happen not to be listed in the locked list.

**Comment by arkhi** [comment]
Fair enough. :)

**Comment by mahagr** [comment]
@rhukster @w00fz To fix this issue I propose that we allow raw edit only for super users and perhaps allow specifying a special group from the configuration..?

**Comment by w00fz** [comment]
Sounds like the most logical solution for me.

**Comment by mahagr** [comment]
See also https://github.com/trilbymedia/grav-plugin-flex-objects/commit/bcd0ac47ca12c22be81eec37daee6cf6b7b0ed16
