### ISSUE TITLE
Clicking "move" on modular pages resulting in endless loading spinner.

### ISSUE THREAD

**Issue by sebastianbaumann** [getgrav/grav-plugin-admin#2095]
Tested on GRAV 1.7.7 and Admin v1.10.6 on two different sites.

When editing a modular page in admin and clicking on move button on the upper right corner the modal just shows an endless loading spinner. See attached screenshot. 

![Bildschirmfoto 2021-03-12 um 12 25 46](https://user-images.githubusercontent.com/9118735/110934294-1d67ac80-832e-11eb-97fd-cd0997b23ceb.png)
![Bildschirmfoto 2021-03-12 um 12 25 51](https://user-images.githubusercontent.com/9118735/110934298-1e98d980-832e-11eb-9d9d-f65bf20b0319.png)

**Comment by mahagr** [comment]
Looks like it works for me (edited the same _hero module) with the latest grav / admin develop versions.

Can you check from the inspector what happens with the AJAX request?

**Comment by sebastianbaumann** [comment]
Sure! 

I'll get `jquery-3.x.min.js?8403e8d200:2 POST http://grav-boilerplate.lok:8888/admin/pages/home/_hero 400 (Bad Request)`

Header response:

`{"code":400,"status":"error","message":"Bad Request","error":{"code":400,"message":"Bad Request","type":"Grav\\Framework\\RequestHandler\\Exception\\RequestException","file":"\/Users\/s.baumann\/www\/grav-boilerplate\/user\/plugins\/flex-objects\/classes\/Admin\/AdminController.php","line":586,"trace":["#0 \/Users\/s.baumann\/www\/grav-boilerplate\/user\/plugins\/flex-objects\/classes\/Admin\/AdminController.php(1271): Grav\\Plugin\\FlexObjects\\Admin\\AdminController->actionGetLevelListing()","#1 \/Users\/s.baumann\/www\/grav-boilerplate\/user\/plugins\/flex-objects\/flex-objects.php(271): Grav\\Plugin\\FlexObjects\\Admin\\AdminController->execute()","#2 \/Users\/s.baumann\/www\/grav-boilerplate\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php(264): Grav\\Plugin\\FlexObjectsPlugin->onAdminPageInitialized(Object(RocketTheme\\Toolbox\\Event\\Event), 'onPageInitializ...', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))","#3 \/Users\/s.baumann\/www\/grav-boilerplate\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php(239): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'onPageInitializ...', Object(RocketTheme\\Toolbox\\Event\\Event))","#4 \/Users\/s.baumann\/www\/grav-boilerplate\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php(73): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners(Array, 'onPageInitializ...', Object(RocketTheme\\Toolbox\\Event\\Event))","#5 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Common\/Grav.php(550): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch(Object(RocketTheme\\Toolbox\\Event\\Event), 'onPageInitializ...')","#6 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Common\/Processors\/PagesProcessor.php(44): Grav\\Common\\Grav->fireEvent('onPageInitializ...', Object(RocketTheme\\Toolbox\\Event\\Event))","#7 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Framework\/RequestHandler\/Traits\/RequestHandlerTrait.php(50): Grav\\Common\\Processors\\PagesProcessor->process(Object(Nyholm\\Psr7\\ServerRequest), Object(Grav\\Framework\\RequestHandler\\RequestHandler))","#8 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Framework\/RequestHandler\/Traits\/RequestHandlerTrait.php(62): Grav\\Framework\\RequestHandler\\RequestHandler->handle(Object(Nyholm\\Psr7\\ServerRequest))","#9 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Common\/Processors\/TwigProcessor.php(38): Grav\\Framework\\RequestHandler\\RequestHandler->handle(Object(Nyholm\\Psr7\\ServerRequest))","#10 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Framework\/RequestHandler\/Traits\/RequestHandlerTrait.php(50): Grav\\Common\\Processors\\TwigProcessor->process(Object(Nyholm\\Psr7\\ServerRequest), Object(Grav\\Framework\\RequestHandler\\RequestHandler))","#11 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Framework\/RequestHandler\/Traits\/RequestHandlerTrait.php(62): Grav\\Framework\\RequestHandler\\RequestHandler->handle(Object(Nyholm\\Psr7\\ServerRequest))","#12 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Common\/Processors\/AssetsProcessor.php(39): Grav\\Framework\\RequestHandler\\RequestHandler->handle(Object(Nyholm\\Psr7\\ServerRequest))","#13 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Framework\/RequestHandler\/Traits\/RequestHandlerTrait.php(50): Grav\\Common\\Processors\\AssetsProcessor->process(Object(Nyholm\\Psr7\\ServerRequest), Object(Grav\\Framework\\RequestHandler\\RequestHandler))","#14 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Framework\/RequestHandler\/Traits\/RequestHandlerTrait.php(62): Grav\\Framework\\RequestHandler\\RequestHandler->handle(Object(Nyholm\\Psr7\\ServerRequest))","#15 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Common\/Processors\/SchedulerProcessor.php(40): Grav\\Framework\\RequestHandler\\RequestHandler->handle(Object(Nyholm\\Psr7\\ServerRequest))","#16 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Framework\/RequestHandler\/Traits\/RequestHandlerTrait.php(50): Grav\\Common\\Processors\\SchedulerProcessor->process(Object(Nyholm\\Psr7\\ServerRequest), Object(Grav\\Framework\\RequestHandler\\RequestHandler))","#17 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Framework\/RequestHandler\/Traits\/RequestHandlerTrait.php(62): Grav\\Framework\\RequestHandler\\RequestHandler->handle(Object(Nyholm\\Psr7\\ServerRequest))","#18 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Common\/Processors\/BackupsProcessor.php(39): Grav\\Framework\\RequestHandler\\RequestHandler->handle(Object(Nyholm\\Psr7\\ServerRequest))","#19 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Framework\/RequestHandler\/Traits\/RequestHandlerTrait.php(50): Grav\\Common\\Processors\\BackupsProcessor->process(Object(Nyholm\\Psr7\\ServerRequest), Object(Grav\\Framework\\RequestHandler\\RequestHandler))","#20 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Framework\/RequestHandler\/Traits\/RequestHandlerTrait.php(62): Grav\\Framework\\RequestHandler\\RequestHandler->handle(Object(Nyholm\\Psr7\\ServerRequest))","#21 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Common\/Processors\/TasksProcessor.php(69): Grav\\Framework\\RequestHandler\\RequestHandler->handle(Object(Nyholm\\Psr7\\ServerRequest))","#22 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Framework\/RequestHandler\/Traits\/RequestHandlerTrait.php(50): Grav\\Common\\Processors\\TasksProcessor->process(Object(Nyholm\\Psr7\\ServerRequest), Object(Grav\\Framework\\RequestHandler\\RequestHandler))","#23 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Framework\/RequestHandler\/Traits\/RequestHandlerTrait.php(62): Grav\\Framework\\RequestHandler\\RequestHandler->handle(Object(Nyholm\\Psr7\\ServerRequest))","#24 \/Users\/s.baumann\/www\/grav-boilerplate\/user\/plugins\/admin\/classes\/plugin\/Router.php(51): Grav\\Framework\\RequestHandler\\RequestHandler->handle(Object(Nyholm\\Psr7\\ServerRequest))","#25 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Framework\/RequestHandler\/Traits\/RequestHandlerTrait.php(50): Grav\\Plugin\\Admin\\Router->process(Object(Nyholm\\Psr7\\ServerRequest), Object(Grav\\Framework\\RequestHandler\\RequestHandler))","#26 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Framework\/RequestHandler\/Traits\/RequestHandlerTrait.php(62): Grav\\Framework\\RequestHandler\\RequestHandler->handle(Object(Nyholm\\Psr7\\ServerRequest))","#27 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Common\/Processors\/RequestProcessor.php(63): Grav\\Framework\\RequestHandler\\RequestHandler->handle(Object(Nyholm\\Psr7\\ServerRequest))","#28 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Framework\/RequestHandler\/Traits\/RequestHandlerTrait.php(50): Grav\\Common\\Processors\\RequestProcessor->process(Object(Nyholm\\Psr7\\ServerRequest), Object(Grav\\Framework\\RequestHandler\\RequestHandler))","#29 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Framework\/RequestHandler\/Traits\/RequestHandlerTrait.php(62): Grav\\Framework\\RequestHandler\\RequestHandler->handle(Object(Nyholm\\Psr7\\ServerRequest))","#30 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Common\/Processors\/ThemesProcessor.php(38): Grav\\Framework\\RequestHandler\\RequestHandler->handle(Object(Nyholm\\Psr7\\ServerRequest))","#31 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Framework\/RequestHandler\/Traits\/RequestHandlerTrait.php(50): Grav\\Common\\Processors\\ThemesProcessor->process(Object(Nyholm\\Psr7\\ServerRequest), Object(Grav\\Framework\\RequestHandler\\RequestHandler))","#32 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Framework\/RequestHandler\/Traits\/RequestHandlerTrait.php(62): Grav\\Framework\\RequestHandler\\RequestHandler->handle(Object(Nyholm\\Psr7\\ServerRequest))","#33 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Common\/Processors\/PluginsProcessor.php(39): Grav\\Framework\\RequestHandler\\RequestHandler->handle(Object(Nyholm\\Psr7\\ServerRequest))","#34 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Framework\/RequestHandler\/Traits\/RequestHandlerTrait.php(50): Grav\\Common\\Processors\\PluginsProcessor->process(Object(Nyholm\\Psr7\\ServerRequest), Object(Grav\\Framework\\RequestHandler\\RequestHandler))","#35 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Framework\/RequestHandler\/Traits\/RequestHandlerTrait.php(62): Grav\\Framework\\RequestHandler\\RequestHandler->handle(Object(Nyholm\\Psr7\\ServerRequest))","#36 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Common\/Processors\/InitializeProcessor.php(129): Grav\\Framework\\RequestHandler\\RequestHandler->handle(Object(Nyholm\\Psr7\\ServerRequest))","#37 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Common\/Debugger.php(546): Grav\\Common\\Processors\\InitializeProcessor::Grav\\Common\\Processors\\{closure}()","#38 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Common\/Processors\/InitializeProcessor.php(130): Grav\\Common\\Debugger->profile(Object(Closure))","#39 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Framework\/RequestHandler\/Traits\/RequestHandlerTrait.php(50): Grav\\Common\\Processors\\InitializeProcessor->process(Object(Nyholm\\Psr7\\ServerRequest), Object(Grav\\Framework\\RequestHandler\\RequestHandler))","#40 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Framework\/RequestHandler\/Traits\/RequestHandlerTrait.php(62): Grav\\Framework\\RequestHandler\\RequestHandler->handle(Object(Nyholm\\Psr7\\ServerRequest))","#41 \/Users\/s.baumann\/www\/grav-boilerplate\/system\/src\/Grav\/Common\/Grav.php(295): Grav\\Framework\\RequestHandler\\RequestHandler->handle(Object(Nyholm\\Psr7\\ServerRequest))","#42 \/Users\/s.baumann\/www\/grav-boilerplate\/index.php(58): Grav\\Common\\Grav->process()","#43 {main}"]}}

![Bildschirmfoto 2021-03-12 um 13 54 12](https://user-images.githubusercontent.com/9118735/110942762-910fb680-833a-11eb-9cd7-addaa62c3d12.png)
![Bildschirmfoto 2021-03-12 um 13 54 44](https://user-images.githubusercontent.com/9118735/110942769-93721080-833a-11eb-9a61-bb5706148679.png)
`

**Comment by sebastianbaumann** [comment]
This seems to have something todo with the page blueprint. 
If I use the page blueprint from official quark theme moving a modular page works, but if I use for example the following custom page blueprint from the documentation moving does not work as explained earlier.

https://learn.getgrav.org/17/forms/blueprints/example-page-blueprint#create-a-completely-custom-page-form 

`title: Gallery

form:
  fields:
    tabs:
      type: tabs
      active: 1
      
      fields:
        gallery:
          type: tab
          title: Gallery
          
          fields:
            header.an_example_text_field:
              type: text
              label: Add a number
              default: 5
              validate:
                required: true
                type: int
            
            header.an_example_select_box:
              type: select
              label: Select one of the following
              default: one
              options:
                one: One
                two: Two
                three: Three
            
            route:
              type: select
              label: PLUGIN_ADMIN.PARENT
              classes: fancy
              '@data-options': '\Grav\Common\Page\Pages::parents'
              '@data-default': '\Grav\Plugin\admin::route'
              options:
                '/': PLUGIN_ADMIN.DEFAULT_OPTION_ROOT
`

**Comment by mahagr** [comment]
Yeah, you need to have the route field as the button uses that field. Not sure if you can make it hidden..?

**Comment by rhukster** [comment]
I think it is related to you overriding that 'route' field.  that's a fundamental one in Grav, and I think that alone is breaking things.

**Comment by mahagr** [comment]
I'm thinking if we should hide the move button if `route` is missing from the blueprint. Missing fields do not matter in save as they will be skipped, but not having it does break move as it is basically a shortcut to clicking the field itself and hitting save.

**Comment by mahagr** [comment]
I added check for the route field in https://github.com/trilbymedia/grav-plugin-flex-objects/commit/fe4a58cad01886c8c2814e91b087ab17a0d2c68e

The above commit fixes the issue by hiding Move button if the field is not there or is using the wrong type. I also updated learn site to use the new `parent` field in `route`, which will make the example work again.
