### ISSUE TITLE
When you delete all pages, you get fatal error

### ISSUE THREAD

**Issue by 810** [getgrav/grav-plugin-admin#21]
When you remove all pages, then the admin will stop working.

**Comment by rhukster** [comment]
Good catch!

**Comment by flaviocopes** [comment]
Yes, actually happens when you delete the homepage. You can also have other pages left, but if you delete the home, an error is thrown.

I pushed a PR to avoid throwing the error, and correctly show the pages list (we might also prevent deleting the homepage)
