### ISSUE TITLE
Add Page Doesn't Sanitize Pasted Page Title With Curly Quote

### ISSUE THREAD

**Issue by thekenshow** [getgrav/grav-plugin-admin#2101]
When adding a page, pasting in a title that contains a curly quote doesn't get properly sanitized and results in a folder that can't be saved. 

**Pasted Title**

![Screen Shot 2021-03-22 at 11 19 34 AM](https://user-images.githubusercontent.com/998832/112013653-95895b80-8b00-11eb-8414-6e18d0ea342c.png)

**Error on Save**

![Screen Shot 2021-03-22 at 11 19 50 AM](https://user-images.githubusercontent.com/998832/112013656-9621f200-8b00-11eb-8753-3cfcce019f4d.png)

**Comment by w00fz** [comment]
Is this still an issue? It seems to be stripping the apostrophe on my end as expected. What version are you using?

<img width="723" alt="w00fz-2021-04-20_@_10 49 17@2x" src="https://user-images.githubusercontent.com/11734/115441800-2027ae00-a1c6-11eb-8fd7-96b8dee5561b.png">

**Comment by mahagr** [comment]
Also, check that the modal isn't having an override in the site or theme.

**Comment by mahagr** [comment]
I cannot replicate this issue either.

**Comment by thekenshow** [comment]
Updated to latest, still exists. Please note I said "curly quote", as in a typographer's quote/apostrophe. Anything pasted into the title field from something like Word will trigger this.

**Comment by w00fz** [comment]
Sorry @thekenshow I didn't catch you meant the single curly quote. I was able to replicate and fix this now.

### Before
<img width="338" alt="w00fz-2021-05-02_@_22 04 38@2x" src="https://user-images.githubusercontent.com/11734/116842825-c72b2300-ab92-11eb-9f07-0d46b9846481.png">

### After
<img width="324" alt="w00fz-2021-05-02_@_22 07 34@2x" src="https://user-images.githubusercontent.com/11734/116842842-d316e500-ab92-11eb-803d-5223335e08ac.png">
