### ISSUE TITLE
Can not upgrade Grav version, Ubuntu version upgrade and PHP 7.4

### ISSUE THREAD

**Issue by Porrumentzio** [getgrav/grav-plugin-admin#2104]
To update Grav `v1.6.28` to `v1.7.9` I needed PHP being superior or equal to `7.4`.

So I updated that pakcage updating Ubuntu version, rebooted and Grav restarted automatically. But now, even having `php 7.4+75`,
>$ apt list php
Listing... Done
php/focal,focal,now 2:7.4+75 all [installed,automatic]

I get the same error. How could I restart Grav in order to it detect the proper PHP version? Should I make something else?

![irudia](https://user-images.githubusercontent.com/61913683/112341443-b816a280-8cc1-11eb-8bac-a2b2b03d10d8.png)

**Comment by mahagr** [comment]
It says that you're not running PHP 7.4. Maybe your server has custom php packages? You probably want to contact their support.

**Comment by Porrumentzio** [comment]
We solved it. The problem seemed to be that nginx was pointing to a previous version of PHP, even if the actual PHP version on server and CLI was the correct.

See the full solution here in Spanish (after that we had some problems setting Grav up): https://forum.anartist.org/t/actualizacion-de-grav-problemas-con-la-version-de-php/490
