### ISSUE TITLE
de.yaml language file contains mongolian text

### ISSUE THREAD

**Issue by grav-mike** [getgrav/grav-plugin-admin#2105]
Some translations in the German language file (de.yaml) for the admin plugin are in mongolian (maybe other language files are affected, too):

SESSION_SAMESITE
SESSION_SAMESITE_HELP
IMAGES_LOADING_HELP
INCLUDE_DEFAULT_LANG_FILE_EXTENSION
INCLUDE_DEFAULT_LANG_HELP_FILE_EXTENSION
ENABLED_SRI_ON_ASSETS
ENABLED_SRI_ON_ASSETS_HELP

Please translate these correctly into German. Thank you!

**Comment by w00fz** [comment]
Hello @grav-mike 

We rely on the community to translate through Crowdin, you can make these changes directly in the Grav Admin project (https://crowdin.com/project/grav-admin/de) and they will be pulled in on the next update.

Cheers,

**Comment by rhukster** [comment]
I've asked our "German" channel on Discord to take a look.

**Comment by stephan-strate** [comment]
I have added "correct" german translations for the given translation variables.
It seems like this commit brought in the wrong translations: https://github.com/getgrav/grav-plugin-admin/commit/46838a62a7d1874552914887818d44c3e631dc73

**Comment by rhukster** [comment]
Thanks! closing
