### ISSUE TITLE
When installing the Grav Widget Plugin it returns an Internal error from the Pages.php file

### ISSUE THREAD

**Issue by Victor5032** [getgrav/grav-plugin-admin#2108]
When installing the Grav Widget Plugin it returns an Internal error from the Pages.php file, I have tried to see if it was an error when the package was installed but I cannot find what could be

![image](https://user-images.githubusercontent.com/44327566/113383718-bd1ec600-9341-11eb-9d12-df56abeed516.png)

**Comment by rhukster** [comment]
Looks like a problem with the widgets plugin. I suggest creating an issue on that repo.
