### ISSUE TITLE
error while trying to download https://github.com/getgrav/grav/releases/download/0.9.43/grav-update-v0.9.43.zip

### ISSUE THREAD

**Issue by offray** [getgrav/grav-plugin-admin#211]
If I try to run:

    ./bin/gpm selfupgrade -f

I got:

    error while trying to download https://github.com/getgrav/grav/releases/download/0.9.43/grav-update-v0.9.43.zip

despite that, putting https://github.com/getgrav/grav/releases/download/0.9.43/grav-update-v0.9.43.zip in the browser, downloads correctly the zip file. Of course, because upgrading fails, admin plugin fails, with a similar error. I'm using Manjaro Linux, and everything else works with grav, but not self upgrading, or plugin installation (I'm doing it manually). What I'm missing?

**Comment by flaviocopes** [comment]
Can you check the SSL PHP extension is loaded? You can see it under `/admin/info` if you're using the Admin plugin

**Comment by offray** [comment]
Thanks for your response @flaviocopes. The problem was related with disabled ssl extension. I didn't verify it in the admin (it was not installed, because I would need to made it by hand), but by looking for a line containin ssl in the `/etc/php/php.ini` file. So I uncommented the line containing `;extension=openssl.so` in that file by removing the leading semicolon and now downloading works :-) 

The next error is related with unzipping. The output goes like this:

    ./bin/gpm selfupgrade -f
    Grav v0.9.43 is now available [release date: Wed Sep 16 18:44:24 2015].
    You are currently using v0.9.40.
    Would you like to read the changelog before proceeding? [y|N] 
    Would you like to upgrade now? [y|N] y
    
    Preparing to upgrade to v0.9.43..
      |- Downloading upgrade [2.13M]...   100%
      |- Installing upgrade...  PHP Fatal error:  Class 'ZipArchive' not found in /home/offray/Documentos/Bio/Blog/Blog3/system/src/Grav/Common/GPM/Installer.php on line 73
    Whoops\Exception\ErrorException: Class 'ZipArchive' not found in file /home/offray/Documentos/Bio/Blog/Blog3/system/src/Grav/Common/GPM/Installer.php on line 73
    Stack trace:
      1. () /home/offray/Documentos/Bio/Blog/Blog3/system/src/Grav/Common/GPM/Installer.php:73

So I need to enable unzipping support via ZipArchive on php now.

May be some notes about this on installation instructions could help a smoother updating/using experience of gpm.

Cheers,

**Comment by offray** [comment]
Solved. To enable zip support is necessary to uncomment the line `;extension=zip.so` on `/etc/php/php.ini` by removing the leading semicolon. 

So to give proper support to gpm on Gnu/Linux system is necessary to uncomment two lines, by removing leading semicolons on them:

  - `;extension=openssl.so` for downloading support via SSL.
  - `;extension=zip.so` for unzipping support.

The "PHP Requierements" section of documentation deals with open ssl in a general way and tells nothing about zip support. Because both are related with a proper and smooth experience with gpm, which is a key component of grav, would be convenient to put some visible prompt message like the ones you get from gd and curl when they're not installed/enabled in your php (may be something saying that grav will work, but gpm will not if these two are not installed).

Hope this helps.

**Comment by flaviocopes** [comment]
@offray you can create a PR on the documentation site to improve it, by clicking 'Edit this page' on the top-right. Contributions are welcome! Most of the times those two PHP settings are already enabled by the hosting provider, but you're right it should be more clear.

**Comment by offray** [comment]
Done:

https://github.com/getgrav/grav-learn/compare/develop...offray:patch-1

Sometimes (like in my case), you develop on a local machine and deploy on a VPS and php modules are not enabled in "desktop" configurations of Gnu/Linux systems. This helps to made it clearer.

Cheers,

**Comment by rhukster** [comment]
Just need to create a pull request from that patch.. hint: click the green button :)

**Comment by offray** [comment]
Sorry I don't use GitHub, but [Fossil](http://fossil-scm.org/) for almost all my development, so I'm making newbie mistakes about how is used. Green button pushed :-).
