### ISSUE TITLE
2FA login broken

### ISSUE THREAD

**Issue by awrog** [getgrav/grav-plugin-admin#2110]
L.S.

It looks like the last update of the admin plugin (v1.10.10) did not solve the 2FA login problems (#[2109](https://github.com/getgrav/grav-plugin-admin/issues/2109))
After entering the right 2FA code the screen displays : 'you're logged in' (in Dutch), but the login screen remains.

![2fa-login](https://user-images.githubusercontent.com/12153667/113994206-7ce5a900-9855-11eb-9f02-c42fe2bb0ff2.gif)

**Comment by mahagr** [comment]
Please check out the commits in: https://github.com/getgrav/grav-plugin-admin/issues/2109#ref-commit-6db7e4a

**Comment by awrog** [comment]
Matias, my bad, I thought the update contained the latest code.
I can confirm, the latest commit works!

**Comment by mahagr** [comment]
It was supposed to be fixed, but it wasn't on all sites.
