### ISSUE TITLE
Проблема с порядком страниц

### ISSUE THREAD

**Issue by ArchyKali** [getgrav/grav-plugin-admin#2112]
![image](https://user-images.githubusercontent.com/82211823/114165297-1b553580-994e-11eb-8632-a175c137e047.png)

Устанавливаю нужный мне порядок, сохраняю - ничего не меняется. Почему не могу поменять порядок в нужный мне?

**Comment by petira** [comment]
English, please.

When you reorder pages (you see 1, 2 and 3) and save them, do the 4, 5, and 6 numbering still remain?
