### ISSUE TITLE
Bug with Grav Admin

### ISSUE THREAD

**Issue by mlacunza** [getgrav/grav-plugin-admin#2113]
Hello,
I just update all my website to the latest version of Grav and Admin, all fine after update, logout and when I try login, Im rejecting from the login screen after I enter my 2FA code from Google App

BUT after I put my login, website check it and I can see the 2FA screen I see a red message in the top rigth side: "You have beed login out" 

Whats happening?

**Comment by rhukster** [comment]
I think this is a repeat of this issue: https://github.com/getgrav/grav-plugin-admin/issues/2109

**Comment by mlacunza** [comment]
Looks like its the same issue BUT its not, because like I said I just installed the LATEST version of the Admin.

**Comment by rhukster** [comment]
It's the same, its just not released yet.. only fixed in develop branch.

**Comment by mlacunza** [comment]
Oh thats another thing, perfect, any ETA for the next realease?

**Comment by rhukster** [comment]
We have a security issue pending that we need to review before release. I estimate a couple of days.  In the meantime, you can probably just 'port' the fix over to your installation. https://github.com/getgrav/grav-plugin-admin/commit/9108a4a85fe1b15a08aa2a88759cae052542dfc2

**Comment by mlacunza** [comment]
I just disable the 2FA plugin and nothing, same bug.  But no problem, I just rollback to my last backup, taken before of upgrade all. I'll wait for the next version, thanks!
