### ISSUE TITLE
Missing slash in password reset url

### ISSUE THREAD

**Issue by treechime** [getgrav/grav-plugin-admin#2119]
Password reset emails are sending with the url `.../adminreset/u/...` with a missing slash between admin and reset.

I think I've narrowed the issue down to the below functions in `AdminController.php` that strip slashes from the input. I tried changing the Administrator path to `/admin/` with a slash at the end but this didn't seem to have any effect as slashes are also being stripped when the base url is created.

```
/**
     * @param string $route
     * @param string|null $lang
     * @return string
     */
    public function getAdminUrl(string $route, string $lang = null): string
    {
        /** @var Pages $pages */
        $pages = $this->grav['pages'];
        $admin = $this->getAdmin();

        return $pages->baseUrl($lang) . $admin->base . trim($route, '/');
    }

    /**
     * @param string $route
     * @param string|null $lang
     * @return string
     */
    public function getAbsoluteAdminUrl(string $route, string $lang = null): string
    {
        /** @var Pages $pages */
        $pages = $this->grav['pages'];
        $admin = $this->getAdmin();

        return $pages->baseUrl($lang, true) . $admin->base . trim($route, '/');
    }
```

**Comment by mahagr** [comment]
Thanks for reporting this one. It should be fixed now. :)

**Comment by mahagr** [comment]
https://github.com/getgrav/grav-plugin-admin/commit/c097eee87f17d22bd05d92e7d40fb9581bd9c320

**Comment by treechime** [comment]
Thanks!
