### ISSUE TITLE
Media Files Issue in Normal Page Edit View

### ISSUE THREAD

**Issue by redlabmedia** [getgrav/grav-plugin-admin#212]
The Media page just has Files title and clicking Add Item just inserts another blank box. It does not seem functional in the Normal Edit view.

**Comment by flaviocopes** [comment]
@redlabmedia can you make a screenshot? Happens with which file types?

**Comment by redlabmedia** [comment]
Here's a screenshot of the Media tab on Normal view after clicking the Add Files button. It does not allow any file uploads, it just opens a blank field.
![adminfilescreen](https://cloud.githubusercontent.com/assets/4422637/10369744/d23c3086-6da9-11e5-8cd6-4d3c3636968e.png)

**Comment by flaviocopes** [comment]
What is the "page type" of the page you're trying to see? And which theme is that?

**Comment by redlabmedia** [comment]
It's the Deliver skeleton package with a couple plugins added. I've tried on multiple pages- you're looking at a screenshot of editing the Home page, which is modular. It happens on any page I try, including Members, which is a default page type. I could give you a login if that helps.

**Comment by redlabmedia** [comment]
I also am finding on editing Blog items in Normal mode, that when I update author or tags, they do not change. Only when I go into Expert mode can I save those changes.

**Comment by flaviocopes** [comment]
Ok replicated, it's something related to the Deliver theme only. Will open an issue there.

**Comment by rhukster** [comment]
Closing this as it's a deliver issue and @flaviocopes has opened a ticket on that Repo.

**Comment by hexplor** [comment]
I commited changes into Deliver develop branch. Can anybody test if it's fine ? There was some leftovers from antimatter.

**Comment by flaviocopes** [comment]
Works fine for me! :+1:

**Comment by redlabmedia** [comment]
Updating the author in Normal mode works now. However, I select one tag in Normal mode and it adds all tags. Also, the Media->Files function still does not work.

**Comment by hexplor** [comment]
Please continue in that topic:
https://github.com/getgrav/grav-theme-deliver/issues/5
