### ISSUE TITLE
Still cannot see pages with FlexObjects enabled on localhost

### ISSUE THREAD

**Issue by tonhaarmans** [getgrav/grav-plugin-admin#2120]
With Grav version 1.7.12 and FlexObjects 1.0.7, AdminPanel 1.10.12 I still cannot see any pages, except Root.
![pages](https://user-images.githubusercontent.com/37418410/115188786-b9cb5e80-a0e5-11eb-8626-a0e3c68b1874.jpg)
Online there is no problem.

Is there anything I can do?

**Comment by mahagr** [comment]
Do you mean that you cannot see them at all or just not with the above filters? Not sure what's different in your server. Are there any filters that do work?

**Comment by tonhaarmans** [comment]
I figured it out! I just had to set the filter thingie to default and everything worked. I have been very stupid.
