### ISSUE TITLE
fork-awesome.min.css.map

### ISSUE THREAD

**Issue by McLaynV** [getgrav/grav-plugin-admin#2122]
This might be related to #1595
In GRAV v1.7.12 Admin Panel v1.10.12 on all pages under `/admin`, JavaScript console is logging this warning:

    DevTools failed to load SourceMap: Could not load content for https://<my-hostname>/user/plugins/admin/themes/grav/css/fork-awesome.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

(I replaced the hostname with "<my-hostname>" above)

There is no `fork-awesome.min.css.map` in my GRAV instalation directory.

    # find ./ | grep fork-awesome.min.css.map

    # find ./ | grep fork-awesome.min.css
    ./user/plugins/admin/themes/grav/css/fork-awesome.min.css

    # grep -ir fork-awesome.min.css.map ./
    ./user/plugins/admin/themes/grav/css/fork-awesome.min.css: ......../*# sourceMap pingURL=fork-awesome.min.css.map */

(I replaced the long one-liner with "........" above)

**Comment by rhukster** [comment]
It's just a warning that shows up in dev-tools ONLY because there is an SCSS source map referenced in the CSS. Nothing to worry about. just ignore it.
