### ISSUE TITLE
BG colors do not load on initial setup of Admin

### ISSUE THREAD

**Issue by simmonsr** [getgrav/grav-plugin-admin#2126]
![Screen Shot 2021-04-20 at 2 59 03 PM](https://user-images.githubusercontent.com/5002814/115456792-3004b980-a1e9-11eb-9590-ccbaf0e1af89.jpg)

Get this every time I load new Grav skeleton with admin. However on refresh it loads the colors.

**Comment by rhukster** [comment]
I think this should already be addressed in the latest develop version of Admoin.

**Comment by simmonsr** [comment]
fix confirmed with dev version
