### ISSUE TITLE
button-bar buttons get blue border from blog plugin

### ISSUE THREAD

**Issue by kat05** [getgrav/grav-plugin-admin#213]
this should probably be ticketed under the blog plugin itself.

when the blog plugin is activated, a blue border gets added to the buttons in the button-bar, please see pic

![grav_blog_blueborder](https://cloud.githubusercontent.com/assets/5719486/10399462/1d68fc4c-6eb3-11e5-8ae1-d16bb60f0bd7.png)

**Comment by flaviocopes** [comment]
Ah yes, it also adds other CSS that cause weird problems in adding pages, for example. Already has an issue for this: https://github.com/giansi/grav-plugin-blog/issues/1 You can add your screenshot too!

**Comment by rhukster** [comment]
This is a bug in the blog plugin probably.. shouldn't be loading the CSS in the admin. Please add the issue there.
