### ISSUE TITLE
add_modals custom modular does not work

### ISSUE THREAD

**Issue by kaphadley** [getgrav/grav-plugin-admin#2132]
the custom modular addition does not work.

In `admin.yaml`:

    add_modals:
      -
        label: Add a custom modal
        blueprint: admin/pages/new-custom-modular
        show_in: dropdown

For this demonstration `new-custom-modular.yaml` is simply a copy of [modular_new.yaml](https://github.com/getgrav/grav-plugin-admin/blob/c97177e0ee5eac3dc652ddce50ba41fdea831d70/blueprints/admin/pages/modular_new.yaml).

When you open the page/parent selection of this custom modular,  the selection loads but it is not functional, you cannot select anything. The following error shows in the console:

    parents.js?49c8:153 Uncaught TypeError: Cannot read property '$emitter' of undefined

**Comment by w00fz** [comment]
This seems to work fine for me now with latest version, I have fixed a few things with the Parents field, let me know if it's still an issue.
