### ISSUE TITLE
AdminController.php not compatible with Blueprint::validate()

### ISSUE THREAD

**Issue by raven2cz** [getgrav/grav-plugin-admin#2133]
Hello, after update Grav v1.7.13 and AdminPanel plugin v1.10.13. I cannot duplicate pages.
There is this error screen. It seems that there is incompatibility between Blueprint.validate which is called from AdminController.php. I don't know if it is caused by AdminPanel. But it is from folder plugin, and updated are Grav and AdminPanel.

`Sorry, something went terribly wrong!
0 - Argument 1 passed to Grav\Common\Data\Blueprint::validate() must be of the type array, null given, called in /home/pi/www/grav/user/plugins/flex-objects/classes/Admin/AdminController.php on line 556`

**Comment by mahagr** [comment]
This has already been fixed in: https://github.com/getgrav/grav/issues/3335

**Comment by raven2cz** [comment]
Thanks
