### ISSUE TITLE
Theme update - custom files overwritten

### ISSUE THREAD

**Issue by grimnebluna** [getgrav/grav-plugin-admin#2135]
Hi,

I am a theme developer and make use of a custom/ folder inside the theme folder structure which is declared in the .gitignore:

custom/css/
custom/logo/
etc.

Other themes use a custom.css as well. Since a couple of days (1.7.12 update?) the theme update process breaks sites with my themes, but also sites with other themes that are using a custom.css.

The custom folder gets deleted with the the theme update.

Is this intentional? What can I do? How do other theme developers deal with this? the custom.css was a really easy way for my users to customize their theme.

Thanks for a quick response (some of my sites will update automatically during the next few days, so i hope to fix it by then.

Thanks!

**Comment by mahagr** [comment]
@grimnebluna 

The above commit should fix the issue. In the meantime, if you do the theme update from CLI, it should work properly.

**Comment by grimnebluna** [comment]
thanks for your work and your quick action!

**Comment by mahagr** [comment]
This should make sure that this issue can never happen again: https://github.com/getgrav/grav/commit/9f5a15f00ad268077bd32e679d060288e67c6ea7
