### ISSUE TITLE
Add Page form: Parent page UI doesn't update

### ISSUE THREAD

**Issue by yankl** [getgrav/grav-plugin-admin#2136]
When I click on the Add Page option from the main pages page (/admin/pages), parent page is by default set to `<root>` as expected. However, when I click to change the parent page, and choose a different page (e.g., in a fresh install, "Home") and then continue "Continue", the parent page option on the form UI doesn't update: it still says `<root>`. Despite this, the option is indeed saved somewhere, as when I create the page, it's put in the correct, selected folder. 
As far as I can tell, this bug happens only when I click Add page on the main "pages" page, not when I click Add Page from a specific page, i.e, not when the default isn't `<root>`. 

I just confirmed this on a fresh install of Grav v1.7.14 - Admin v1.10.14.

**Comment by fseesink** [comment]
I was about to open a ticket on this as well, but I see you beat me to it.  I had only noticed the issue when in the **Admin** panel on the **Pages** page and clicking **[+Add]**, as that is typically where I am when I want to add a new page.   And as mentioned, it does actually set the parent page when you create the page.

But yes, I can also confirm that if I have _any_ of my pages open in the editor and then click **[+Add]**, the parent page updates properly.

So whatever this is, as @yankl reported, it is only occurring when on the Admin Pages page (e.g., `<site>/admin/pages`) where updating the parent page is not reflected in the dialog box.

To reproduce,

1. Navigate to the Admin panel (`<site>/admin`)
2. Click **Pages** on the left side (`<site>/admin/pages`)
3. Click **[+Add]** to open a dialog box to add a new page
4. Click `<root>` and select something other than `<root>` as the parent page and click **[Continue]**
5. Note that **Parent Page** does _not_ reflect this choice.  It still shows `<root>`

Repeat the above, only this time after step 2 click on any existing page to open it in the editor first.  Then continue with step 3.  This time you will see that the **Parent Page** does update after you click **[Continue]** in step 4.

**Comment by rhukster** [comment]
I can confirm there's an issue with this as I have seen similar.

**Comment by mahagr** [comment]
I can also reproduce this issue. CC @w00fz 

Also related to #2145

**Comment by fseesink** [comment]
Just an FYI:  This is still an issue in Grav v1.7.15.
