### ISSUE TITLE
Admin crashes when system.twig.undefined_functions = false

### ISSUE THREAD

**Issue by yankl** [getgrav/grav-plugin-admin#2138]
I was getting tired of Twig failing silently when I accidently used an undefined function in my code (e.g. if I forgot to import it), as it made it harder to debug. So I changed `system.twig.undefined_functions` to `false`, which had the intended effect of crashing the site with an error with the undefined function in the template instead of just printing nothing. 

However, this also seems to cause the Admin plugin to crash on various occasions. I was able to reproduce it in a fresh install by saving at configuration (so that the variable option appears in my `user/config/system.yaml`) switching the variable there, clearing the cache from the admin plugin, and then going to the Configuration page, where I get this: 

![image](https://user-images.githubusercontent.com/425828/116885875-1031b480-ac31-11eb-86a4-8845c76082fe.png)

Or, if I try to go to my admin user page, I get this: 

![image](https://user-images.githubusercontent.com/425828/116887153-a4e8e200-ac32-11eb-9287-a2729029c15d.png)

Is the Admin plugin not supposed to be able to work with this variable set to false? If so are there any suggestions for making debugging Twig templates easier besides setting undefined_functions to false? 

I'm on Grav v1.7.14 - Admin v1.10.14.

**Comment by mahagr** [comment]
Fixed a few: https://github.com/getgrav/grav/commit/7d01977a89436526538d536aa8a943cfcac418c4

**Comment by mahagr** [comment]
Not sure what to do with base64 methods -- they are already defined as filters, but not functions. @rhukster ?

**Comment by rhukster** [comment]
I changed the functions to filters
