### ISSUE TITLE
Duplicate Page from Page List drop-down menu does not seem to actually make a new page?

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#2139]
Hello!

I noticed some comments about an updated page copy feature in Admin, so I tried out to Duplicate a page from the Admin Page List panel.

For some reason this does not result in a duplicate page, it looks like the the page underneath the purple "Copy created successfully" status message is in fact the source page vs. a new copy. Mac OX, Latest Firefox and Google Chrome.

Not sure if this is a new issue or existing, but thought I best share my test results.

Please let me know if any more info/details are helpful.

Thanks very much,
Paul

**Comment by mahagr** [comment]
Make the copy to work without modal: https://github.com/getgrav/grav/commit/d058c1d4fc5bae018bcb45ec8ccc0e5048d30907

@w00fz We still need to introduce the modal into the page list.

**Comment by w00fz** [comment]
@mahagr We might need a new modal and logic for the pages list. Copying from the page edit is relying and expecting the form of the page itself to be submitted. For the listing we cannot do this, instead we need a whole new logic where all we have available for the task to receive are the URL/slug of the page + customizable settings such as new title/slug of the copy. We really cannot submit a form of a page it's not loaded yet.

Need you to start thinking about this, we can discuss it further in chat later.

**Comment by w00fz** [comment]
I got this implemented. It is however a Flex Objects enhancement so it will be available at next Flex Objects release .

**Comment by w00fz** [comment]
This is now released in Flex Objects v1.0.14

**Comment by paulhibbitts** [comment]
Awesome @w00fz , thanks so much! My MacBook Pro is getting repaired but once I get it back I'll try this out too🙂
