### ISSUE TITLE
Menu overrides page title

### ISSUE THREAD

**Issue by bassplayer7** [getgrav/grav-plugin-admin#214]
If I have a page like this: 

```markdown
    title: "Blog Page"
    pagination: true
    body_class: right-sidebar
    header_class: skel-layers-fixed
    icon: comment-o
    menu: blog
```

It will show up in the admin panel like this:
![pages___blog](https://cloud.githubusercontent.com/assets/1171147/10432157/07b9e488-70cf-11e5-8ac5-477ae67542b2.png)

However, if I remove `menu`:

```markdown
    title: "Blog Page"
    pagination: true
    body_class: right-sidebar
    header_class: skel-layers-fixed
    icon: comment-o
```

It then looks good:
![pages___blog](https://cloud.githubusercontent.com/assets/1171147/10432191/490838f4-70cf-11e5-8d02-82a2a8c3b5b5.png)

**Comment by flaviocopes** [comment]
Thanks for reporting, fixed in https://github.com/getgrav/grav-plugin-admin/commit/fc87d184e8d03d29c9ed379f17dd6fb739575f37
