### ISSUE TITLE
Raw language strings displayed when theme is not the active theme

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#2140]
I just updated to the latest Typhoon release, and noticed that if the Active Theme is not Typhoon (mine was set to Quark) raw language strings are shown in the Typhoon settings page. However, if Typhoon is made the Active Theme then language strings are shown as expected.

Below is what I see when Typhoon is not the Active Theme:

<img width="1200" alt="2021-05-05_07-18-10" src="https://user-images.githubusercontent.com/1812771/117156277-5cd0d900-ad72-11eb-83e0-5e2759cf8203.png">

If any more info etc. is helpful please let me know.

Thanks very much, 
Paul

**Comment by omega8cc** [comment]
We can see the same problem affecting sites which skipped many releases and were recently upgraded to latest Grav release. However, in these sites admin literally everything is looking like that, including all admin menus and buttons. We have checked site settings etc and everything looks fine, yet, the default (en) language is simply not loaded in the admin panel at all.
