### ISSUE TITLE
Add year on logs

### ISSUE THREAD

**Issue by AnaelMobilia** [getgrav/grav-plugin-admin#2141]
Hello,

We have access to log on Admin -> Tools -> Logs -> Grav System Log Output

On the date field, year isn't display which made log hard to read.

For example, I have error dating of January 2020 on my logs :
![image](https://user-images.githubusercontent.com/6187125/117195580-b9b9a700-ade5-11eb-9ad1-b20fbbfe9c44.png)
But nothing allow to know it's more one year ago log ;-)

My suggestion : add year on the date field

Regards

**Comment by w00fz** [comment]
I don't think having the year is that much useful as logs usually are meant to be consulted for immediate feedback. Adding the year kinda takes real estate more useful for the message.

Instead I added it as a tooltip, so you can hover and you will get the full extended date in `RFC 2822` format.

<img width="367" alt="w00fz-2021-06-04_@_11 54 45@2x" src="https://user-images.githubusercontent.com/11734/120850272-0f3fbb80-c52c-11eb-8f81-0e1ffab9af45.png">
