### ISSUE TITLE
add item page to blog not it the right place & move not working

### ISSUE THREAD

**Issue by fjunillon** [getgrav/grav-plugin-admin#2145]
Hi
I recently update all things and I got 
grav 1.7.14
plugin admin  1.10.14
flex 1.0.9

working on macos / safari (but issue is also happening on firefox)

Now when adding a page (item or page or else) under another setup as a blog :
- popup raises to naming options
- I can click to select path (cf shot1)
- when I click ok and come back on first popup, destination stills "root" (cf. shot2)
- And (that's the troubled point...)  it's created on root's path 😞 

Then if I try to move it, It's definitly not working
- open the page
- click "move" button
- popup raises to select path destination
- clicking doesn't allow any selection (cf. shot3)

Everything was working on previous version and nothing else has changed (server configuration, dir rights etc.)

Any idea/help on this bug ? 
Of course actually I go on command line to resolve it, but it's a bit annoying... 😄 

thanks a lot

![shot1](https://user-images.githubusercontent.com/12086095/117562998-2e6d3980-b0a3-11eb-95c5-42c232460eec.png)
![shot2](https://user-images.githubusercontent.com/12086095/117562999-2f9e6680-b0a3-11eb-9f19-c3f88f9445bf.png)
![shot3](https://user-images.githubusercontent.com/12086095/117563000-2f9e6680-b0a3-11eb-97e7-3f1b6501cc06.png)

**Comment by mahagr** [comment]
@w00fz This is definitely an issue in FF, though I'm only getting the issue in the `Add Page` modal.
