### ISSUE TITLE
In Admin pages some list elements are not containing their content

### ISSUE THREAD

**Issue by glasswork** [getgrav/grav-plugin-admin#2146]
The admin needs a bit of css so that list elements contain their content:

![Screen Shot 2021-05-13 at 6 53 44 AM](https://user-images.githubusercontent.com/4681577/118158689-5c22ed00-b3d9-11eb-9603-dc683218a560.png)

This is fixed by adding:

.form-list-wrapper ul[data-collection-holder] > li.collection-collapsed { overflow:hidden; }

Fix tested using the Customadmin plugin.

**Comment by mahagr** [comment]
@rhukster Can you have a look?

**Comment by rhukster** [comment]
What is this field that is oveflowing the list item and how can i recreate it?

**Comment by glasswork** [comment]
Sorry for the hiatus ... my mother went into sepsis Thursday evening and passed away Friday morning. I have been busy with other things. I will gather that data and get back to you today.

**Comment by glasswork** [comment]
Ok, here is the yaml:

`title: Capabilities
'@extends':
    type: default
    context: blueprints://pages

form:
    fields:
        tabs:

            fields:
                home:
                    type: tab
                    title: Capabilities
    
                    fields:
        
                        # Capabilities Jumbotron Section
                        cap_jumbotron_section:
                            type: section
                            title: "Jumbotron Slides"
                            underline: true
                            text: "For each entry you'll need a 1920w x 751h JPG image."
                            
                        header.cap_jumbotron_section:
                            name: jumbotron
                            type: list
                            help: "Add at least three and up to seven jumbotron sliders."
                            collapsed: true
                            collapsible: true
                            style: vertical
                            label: "Add Three (or more) Jumbotron Slides."
                            max: 7
                            fields:
                                .slider_link:
                                    type: text
                                    label: "Jumbotron Link"
                                    help: "The relative path ofo the internal resource to which the slide will link."
                                    classes: large
                                    placeholder: "Something like: '/portfolio/penguin-chill'"
                                .slider_image:
                                    type: file
                                    label: "Jumbotron Slide"
                                    destination: 'user/themes/ideum2017/assets/images/capabilities/jumbotron_slides'
                                    help: "This will be 1920w x 751h JPG image."
                                    multiple: false
                                    avoid_overwriting: true
                                    size: medium
                                    limit: 1
                                    filesize: 1
                                    accept:
                                        - image/*
                                .slider_image_alt:
                                    type: text
                                    label: "The alt text for the image."
                                    help: "Brief decsritptive text for use as the img alt tag content."
                                    classes: long
                                    placeholder: "Something like: 'People interact with multiple science stations to learn about STEM concepts related to Antarctic field research.'"
                                .slider_type_fieldset:
                                    type: fieldset
                                    title: "Capability Type"
                                    help: "This describes the capability type of which the slide is an example."
                                    info: "...for the slide..."
                                    text: "Provide details about the capability type."
                                    icon: comments
                                    collapsed: true
                                    collapsible: true
                                    fields:
                                        .slider_cap_title:
                                            type: text
                                            label: "The type of capability."
                                        .slider_cap_desc:
                                            type: textarea
                                            label: "A brief description of the same."
                                .slider_project_fieldset:
                                    type: fieldset
                                    title: "Project Description"
                                    help: "This describes a specific project that exemplifies the capability type."
                                    info: "..in brief..."
                                    text: "Provide details about an associated project."
                                    icon: comments
                                    collapsed: true
                                    collapsible: true
                                    fields:
                                        .slider_proj_desc:
                                            type: textarea
                                            label: "A sentence describing the project."
                                        .slider_proj_client:
                                            type: text
                                            label: "The name of the client."`

Here is how it looks (corrected) on the backend:

![Screen Shot 2021-05-17 at 6 52 23 AM](https://user-images.githubusercontent.com/4681577/118492025-d22a9b00-b6dc-11eb-9ab2-58266ac9d1d8.png)

**Comment by glasswork** [comment]
You can tell from the previous (original) image, that the capability type and project description fields were not being contained, and the yaml will clue you in as to what exact type those fields were.

I will have limited availability today, but will be more available tomorrow.

**Comment by rhukster** [comment]
Commited.
