### ISSUE TITLE
Custom Page date format added via the Admin Panel does not display in the selection field

### ISSUE THREAD

**Issue by petira** [getgrav/grav-plugin-admin#2149]
If you add your custom **Page date format** via the **Admin Panel**, it will be saved in `/user/config/system.yaml`, but to display the date format in the selection field it is necessary to reload the page. This behavior is confusing.

However, it is good that it can be added. I do not know if this option was added in a later version, or I did not notice it before (https://github.com/getgrav/grav/pull/2780), or maybe the above behavior confused me. So far, I have edited my custom **Page data format** directly in `/user/config/system.yaml`.

**Comment by mahagr** [comment]
This happens because Grav uses only a single POST request and doesn't reload the page with 302.
