### ISSUE TITLE
Backup returns with "Not Found"

### ISSUE THREAD

**Issue by bjorntheart** [getgrav/grav-plugin-admin#216]
I tried to make a backup from the admin backend and Grav returns a "Not Found" notification.

Firebug shows the following in ajax html response

```
Not Found
The requested resource /admin/backup.json/task:backup was not found on this server.
```

**Comment by flaviocopes** [comment]
@bjorntheart is it a Windows server?

**Comment by bjorntheart** [comment]
On Mac OSX running it through ```php -S localhost:8000```

**Comment by flaviocopes** [comment]
The PHP built-in server is not supported unfortunately. Use MAMP instead (or the built-in OSX Apache web server)

**Comment by bjorntheart** [comment]
@flaviocopes Thanks! I've got a vagrant machine which I will test it on
