### ISSUE TITLE
Themes only show HTML code - Grav-Noob Problems

### ISSUE THREAD

**Issue by IAWMSascha** [getgrav/grav-plugin-admin#2163]
I just installed GRAV (+Admin-Tool) for the first time on XAMPP (latest) on my Win10.
Everything works fine, except I cannot use other Themes then Quark and Lingonberry.
If I download new themes, the content is only shown as HTML source  (with the Mache Theme, I only see a white loading-circle, but no content or images).
I double checked the PHP.ini and Apache.conf Requirements, but can't find why only these 2 Themes work.
Do I miss a plugin? Or need to Check some boxes first?

Thanks, Sascha

**Comment by mahagr** [comment]
Those themes are not fully compatible with the latest Grav 1.7. However, you can make them to work by changing two settings, see details from here:

https://learn.getgrav.org/17/advanced/grav-development/grav-17-upgrade-guide#twig

**Comment by IAWMSascha** [comment]
Thank you for your answer @mahagr, some more templates work now, but still a lot of them have errors. But due to the latest GRAV version, ich will wait a bit an read more docs on templatecoding.
