### ISSUE TITLE
Meta Data missing "metadata:" tag

### ISSUE THREAD

**Issue by khaefeli** [getgrav/grav-plugin-admin#217]
Hi

When I newly insert some meta data on a page, the content is written to the .md with:

    description: 'asdf asdf'

But the "metadata:" tag is missing, so the data doesn't render in the frontend.
After inserting it manually in the .md file - everything works.

Cheers

**Comment by flaviocopes** [comment]
Works fine for me, just tested. Which page type is that? If it's a custom theme, can you post the page type yaml file? It might depend on that

**Comment by rhukster** [comment]
Closing due to lack of response.
