### ISSUE TITLE
Uncaught TypeError: Cannot read property 'notifications' of undefined

### ISSUE THREAD

**Issue by ChristianaHoJo** [getgrav/grav-plugin-admin#2171]
After updateing admin panel, my plugin throws an javascript error in admin.min.js. 

```
admin.min.js?5a66ee27e0:1089 Uncaught TypeError: Cannot read property 'notifications' of undefined
    at canFetchNotifications (admin.min.js?5a66ee27e0:1089)
    at Module.40535 (admin.min.js?5a66ee27e0:1244)
    at __webpack_require__ (admin.min.js?5a66ee27e0:14897)
    at admin.min.js?5a66ee27e0:15065
    at Function.__webpack_require__.O (admin.min.js?5a66ee27e0:14941)
    at admin.min.js?5a66ee27e0:15066
    at admin.min.js?5a66ee27e0:15069
```

Is there a simple solution to fix this issue?  I'm not really familiar with webpack requirement.

**Comment by ChristianaHoJo** [comment]
In Admin Plugin v1.10.12 in file "_user/plugins/admin/themes/grav/templates/partials/javascript-config.html.twig_" 

`user.authorized`

is added to the twig File. 

In another custom plugin in twig the variable "user" is also set and overrides the "user" variable from admin. Changing the "user" in the other plugin solves the problem.

**Comment by rhukster** [comment]
What is the other plugin? Probably shouldn't use it at all if it is messing with user object?

**Comment by ChristianaHoJo** [comment]
It is custom plugin in our project that implements an intern review workflow. It is not a public plugin. The problem with the overwritten object was only in the modified pages.html.twig of that plugin. Renaming the variable solves the problem.
