### ISSUE TITLE
Unable to upload media files other than images

### ISSUE THREAD

**Issue by dallaslu** [getgrav/grav-plugin-admin#2172]
https://github.com/getgrav/grav-plugin-admin/blob/eb4d9703db62703ab237ab625b4877fb235d7c2c/themes/grav/app/forms/fields/files.js#L89

```js
const image = new Image();
image.src = event.target.result;
image.onerror = function() {
    done(translations.PLUGIN_ADMIN.FILE_ERROR_UPLOAD);
};
```
Always run to the line `done(translations.PLUGIN_ADMIN.FILE_ERROR_UPLOAD);`.

**Comment by w00fz** [comment]
For the longest time I thought this was a non-issue because you never specified specifically it was only happening with the admin `resolution` setting enabled, and so I was never able to reproduce it!

I came across this issue by accident and then connected the dots. This is now resolved, thanks!
