### ISSUE TITLE
Backup settings are written to /system/config/backups.yaml which is wiped on update

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav-plugin-admin#2176]
When saving Backup settings in Admin, changes are being written to */system/config/backups.yaml*. After upgrading Grav, this file gets replaced with the default config.

**Comment by rhukster** [comment]
odd, i will look into that.

**Comment by mahagr** [comment]
I can verify the bug. If there's no file `backups.yaml` in the configuration, system folder is being used.

**Comment by mahagr** [comment]
LOL. Looks like I have added FIXME just for this issue, likely when going through the code for some other reason.

**Comment by mahagr** [comment]
I also ended up making the configuration more strict so that it's not possible to save the configuration if the blueprint doesn't exist.
