### ISSUE TITLE
Admin Plugin Can't Update Settings

### ISSUE THREAD

**Issue by berensn** [getgrav/grav-plugin-admin#2180]
I went to the admin plugin and changed administrator path but when I saved I got the error 'Validation failed:
Invalid input in "Resize Quality"'
The error occurs for any change made in the admin plugin. 
The resize quality is on the 'Extras' tab of the admin plugin at the bottom. Its a value between 0 and 1 and the default is 0.8 

My setup is an A2 Hosting shared hosting. PHP is v7.4

**Comment by mahagr** [comment]
Already fixed, see https://github.com/getgrav/grav/issues/3433

**Comment by berensn** [comment]
When will that fix be pushed as an update?

**Comment by mahagr** [comment]
It has already been released last week, sorry for the slow response.
