### ISSUE TITLE
Dependabot Alerts

### ISSUE THREAD

**Issue by benabus** [getgrav/grav-plugin-admin#2184]
As I backup my user folder to github, I get a number of dependabot security alerts:

path-parse
moderate severity
by GitHub
plugins/admin/themes/grav/yarn.lock
glob-parent
high severity
by GitHub
plugins/admin/themes/grav/yarn.lock
browserslist
moderate severity
by GitHub
plugins/admin/themes/grav/yarn.lock
set-value
high severity
by GitHub
plugins/admin/themes/grav/package-lock.json
path-parse
moderate severity
by GitHub
plugins/admin/themes/grav/package-lock.json
postcss
moderate severity
by GitHub
plugins/admin/themes/grav/package-lock.json
trim-newlines
high severity
by GitHub
plugins/admin/themes/grav/package-lock.json
glob-parent
high severity
by GitHub
plugins/admin/themes/grav/package-lock.json
browserslist
moderate severity
by GitHub
plugins/admin/themes/grav/package-lock.json
ssri
high severity
by GitHub
plugins/admin/themes/grav/package-lock.json
lodash
high severity
by GitHub
plugins/admin/themes/grav/package-lock.json
y18n
high severity
by GitHub
plugins/admin/themes/grav/package-lock.json
ini
high severity
by GitHub
plugins/admin/themes/grav/package-lock.json
yargs-parser
moderate severity
by GitHub
plugins/admin/themes/grav/package-lock.json
codeception/codeception
critical severity
by GitHub
plugins/admin/composer.lock 

ansi-regex
moderate severity
by GitHub
plugins/admin/themes/grav/yarn.lock
ansi-regex
moderate severity
by GitHub
plugins/admin/themes/grav/package-lock.json

**Comment by w00fz** [comment]
These should be all resolved now
