### ISSUE TITLE
Attempting to preview page results in "not found" warning

### ISSUE THREAD

**Issue by goodbayscott** [getgrav/grav-plugin-admin#219]
![screen shot 2015-10-15 at 5 21 51 pm](https://cloud.githubusercontent.com/assets/5986616/10531025/e2f2c0b2-7361-11e5-8bd1-8b2c72036668.png)

new base level page, cloned from homepage, only tweak is title. Preview isn't functioning, nor on the default homepage. No other changes to site.

**Comment by rhukster** [comment]
Is this page 'saved' yet?

**Comment by goodbayscott** [comment]
page was initially created via ftp. I discovered a few permissions errors which when resolved seemed to clear up this particular issue.
