### ISSUE TITLE
Server Error Grav

### ISSUE THREAD

**Issue by kevin19100** [getgrav/grav-plugin-admin#2190]
Hi, il cant edit a page with grav.

When i open any page i have this error
![error](https://user-images.githubusercontent.com/93037207/138553828-dff5a01f-527d-4b4c-bef1-71b08f4aa3ca.PNG)
r.

Someone can help me pls.

**Comment by elkwaet** [comment]
> Already fixed in [getgrav/grav@33a5709#diff-9c8c5d41e6157a9b50222fe05ddac93d78844ce2ba511c8c3a77219184603fd9R134](https://github.com/getgrav/grav/commit/33a57099038a30aa8001d908abaa08b37943c228#diff-9c8c5d41e6157a9b50222fe05ddac93d78844ce2ba511c8c3a77219184603fd9R134)

AND HOW END USERS CAN FIX IT IN THEIR SIDE?

**Comment by rhukster** [comment]
Please don't use caps.. its very rude.

This fix is already in the 1.7.24 release of Grav.
