### ISSUE TITLE
Page list display field not working.

### ISSUE THREAD

**Issue by npetri13** [getgrav/grav-plugin-admin#2191]
Hello,

i tried to define a list display title:
```
---
title: Imprint
cmsTitle: This is a cmsTitle
---
```

I set the the ‘pages_list_display_field’ option in the admin.yaml like:

```
pages_list_display_field: cmsTitle
```
also tried:
```
pages_list_display_field: header.cmsTitle
```
but always the usal title is displayed.

[Thread - Grav Forum](https://discourse.getgrav.org/t/admin-page-list-display-field-not-working/18772)

**Comment by w00fz** [comment]
Sorry @npetri13, this feature was only ever available with the old Pages list. Since we moved to Flex Pages, this option has become obsolete and is no longer supported.

I have now sunsetted the setting from the admin.
