### ISSUE TITLE
An extra '?' on line 19

### ISSUE THREAD

**Issue by JacobBorgProgramming** [getgrav/grav-plugin-admin#2194]
I was having issues post installing with index.php. The server said there was an extra '?' on line 19, I tried removing the '?' and it fixed it. 

I'm using version 1.7.24 with PHP version 7.4

**Comment by mahagr** [comment]
Which line 19? In Grav itself, line 19 of `index.php` is `if (PHP_SAPI === 'cli-server') {, no question mark in there.

**Comment by JacobBorgProgramming** [comment]
It was in index.php

It is possible that my host's online editor messed it up.
