### ISSUE TITLE
Depracated messages on top of my page. 

### ISSUE THREAD

**Issue by mark-novelero** [getgrav/grav-plugin-admin#2198]
Hi all. Very new to Grav. I  dowloaded the zip file and got the page up and running but at the top of the page, I have the following messages.  Please help. Thanks. 

/Desktop/Grav-Projects/grav/vendor/pimple/pimple/src/Pimple/Container.php
on line
133

Deprecated
: Return type of Pimple\Container::offsetGet($id) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in
/Desktop/Grav-Projects/grav/vendor/pimple/pimple/src/Pimple/Container.php
on line
98

Deprecated
: Return type of Pimple\Container::offsetSet($id, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in
/Desktop/Grav-Projects/grav/vendor/pimple/pimple/src/Pimple/Container.php
on line
79

Deprecated
: Return type of Pimple\Container::offsetUnset($id) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in
/Desktop/Grav-Projects/grav/vendor/pimple/pimple/src/Pimple/Container.php
on line
143

**Comment by rhukster** [comment]
Sounds like you are running PHP 8.1. This is just about a week old and not fully supported in Grav yet but we're working on  it.

I suggest switching to PHP 8.0.

Cheers.

**Comment by mahagr** [comment]
That said, we are fixing PHP 8.1 bugs as we speak. However as PHP 8.1 is so new, I only recommend using it for testing purposes right now.

**Comment by mark-novelero** [comment]
Thanks Matias. Switching to PHP 8.0 worked.

Mark
