### ISSUE TITLE
UX: change Updates Available text

### ISSUE THREAD

**Issue by 810** [getgrav/grav-plugin-admin#22]
Please change the text: Updates Available on dashboard to:
No Updates Available

when there are no updates. And maybe hide the update button

**Comment by rhukster** [comment]
I think the button is still valuable.. I think i might update it to 'force' updates if you push it when there says no updates.

**Comment by w00fz** [comment]
This is now implemented with 1e470fb15641955641002c12c30fc2b5fe29a849 and 8f753696ea2fa1dbe06ca17d64571cafb9bc0fe9.

If there are no updates, the button is going to go away. I also added a new `Check for Updates` button in Dashboard, Plugins and Themes which does a flushed GPM refresh and checks for updates.

**Comment by 810** [comment]
please change also the text: https://github.com/getgrav/grav-plugin-admin/blob/1e470fb15641955641002c12c30fc2b5fe29a849/themes/grav/templates/dashboard.html.twig#L40

Just call it "Updates"
