### ISSUE TITLE
(Safari) Add Page - Cursor stuck in Folder Name field

### ISSUE THREAD

**Issue by rezafouladian** [getgrav/grav-plugin-admin#2209]
On macOS Safari when you add a new Page and click in the Folder Name field you are unable to click back into the Page Title field.

Issue tested on Safari 15.2 on macOS 12.1 as well as Safari on iOS 15.1.1
Issue does NOT occur on Firefox 95.0.2 on macOS 12.1

Steps to reproduce:
1. Log in to Grav Admin
2. Click on Pages
3. Click Add
4. Click in the Folder Name input field
5. Attempt to click in the Page Title input field
     1. The blinking cursor will stay in the Folder Name field
     2. Tab and Shift+Tab also has no effect

System Info:
Grav v1.7.25
Admin v1.10.25
PHP 7.3.20
Oracle Linux 8.5

**Comment by w00fz** [comment]
Wow I never seen anything like this! I'm investigating what's going on.

**Comment by w00fz** [comment]
Was able to reproduce and fix.

Thanks.
