### ISSUE TITLE
Minor: Icons don't match

### ISSUE THREAD

**Issue by bassplayer7** [getgrav/grav-plugin-admin#222]
This is very minor, but since I noticed, I thought I'd open an issue in case it is something that you'd like to fix. 

![grav_themes](https://cloud.githubusercontent.com/assets/1171147/10559478/1eecc026-74b7-11e5-87e3-e170cd245d86.png)

`Configuration - System` seems to have the same problem.

**Comment by flaviocopes** [comment]
Thanks for reporting!
