### ISSUE TITLE
Getting error in Utils::slug(): `iconv(): Wrong charset, conversion from UTF-8 to ASCII//TRANSLIT//IGNORE is not allowed`

### ISSUE THREAD

**Issue by hughbris** [getgrav/grav-plugin-admin#2229]
This is happening at [line 44 of Utils.php](https://github.com/getgrav/grav-plugin-admin/blob/c9e4d6fb0e7a5df5eeabc08d6a9d273fcb13d652/classes/plugin/Utils.php#L44) after proceeding through a custom page creation modal (as per the [recipe in learn](https://learn.getgrav.org/17/cookbook/admin-recipes#add-a-custom-page-creatio), also described in #1362).

My setup: `Grav v1.7.28 - PHP 7.3.8`

```php
public static function slug(string $str)
{
    if (function_exists('transliterator_transliterate')) {
        $str = transliterator_transliterate('Any-Latin; NFD; [:Nonspacing Mark:] Remove; NFC; [:Punctuation:] Remove;', $str);
    } else {
        $str = iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $str);
    }
```
So Grav is finding that `transliterator_transliterate` is not installed in my setup and using `iconv()`, where it is failing.

I am surprised that my php-fpm build does not include the intl extension which would deliver the Transliterator class. My workaround if this is not fixed soon will be to add it as a custom hack into my stack. That doesn't change that there is a fatal bug in the fallback.

**Comment by mahagr** [comment]
@hughbris You don't have iconv installed on your system and there seems to be a plugin that uses a very old version of iconv polyfil  (1.6 or older from Oct 2017). Make sure you update the plugins!
