### ISSUE TITLE
Hacked site title (Hacked by tokeichun)

### ISSUE THREAD

**Issue by fosil** [getgrav/grav-plugin-admin#2236]
I noticed a successful penetration even with relatively fair current versions: Grav 1.7.28 + admin 1.10.28 :-(

**Comment by spamhater-grav** [comment]
mmm bit weird that one, as the issue was with admin <1.10.9 where is was fixed and the script kiddie has been finding vulnerable admins ... but all they can change is the title... If you do see it again with an admin of that version might be worth logging in security tab of this github.  Be interesting to see if they try and come back .

![image](https://user-images.githubusercontent.com/84087968/153728322-c6bbe7db-6048-43bb-9da3-b80d1885f1ac.png)

**Comment by mahagr** [comment]
It's still likely that the title was changed before updating to the latest Grav, please check the modification time of `user/config/site.yaml` (I'm assuming you haven't edited that one for some time).

**Comment by patdavid** [comment]
Is it safe to assume they were only able to change the title?
I wasn't able to find any instance of the string "Hacked by tokeichun" in any files in my installation for some reason - but it _was_ in the admin interface for the site `admin/config/site` => Site Title.

**Comment by mahagr** [comment]
The text may be using encoded characters, check `user/config/site.yaml` file.

We are not aware that the attack changed anything else, but the vulnerability makes it possible to change configuration files and can probably be used for further attacks in that way.

**Comment by patdavid** [comment]
I've fixed the site title manually in the admin panel and it's now gone - but I'm still concerned about the possible breadth or depth of the compromise.  Is there more information we can get about what happened and how?  It would help us to have more confidence that the defacing isn't actually indicative of something deeper or more problematic.

**Comment by rhukster** [comment]
From the various sites that we've been able to inspect, and the nature of this attack, it appears that only configuration files (`user/config/*`) could have been effected.  Also when this was reported, they example they gave was for changing the site title, so it seems the 'hackers' just used this example.

That's all we've seen, and the fixes we put in place last year (march 2021) mitigated against all scenarios of this attack. So the best thing to do is just check your configuration files (primarily `system.yaml` and `site.yaml`) for anything weird.
