### ISSUE TITLE
Page editing completely broken :(

### ISSUE THREAD

**Issue by andynemzek** [getgrav/grav-plugin-admin#224]
Just updated to the latest grav and admin plugin and it appears that the page editor is completely broken.  Can't edit front-matter or content.
![screen shot 2015-10-21 at 3 54 20 pm](https://cloud.githubusercontent.com/assets/1213547/10649899/2a316fb0-780c-11e5-961d-8cb8cfd50cf8.png)

**Comment by rhukster** [comment]
You have some really strange CSS going on there.  What plugins are you running? If you are running the 'blog' plugin, please disable it and try again.

**Comment by andynemzek** [comment]
Plugins include: admin, email, error, form, login, problems, simple_form.

**Comment by rhukster** [comment]
try disabling simple_form, also what browser is this?

**Comment by andynemzek** [comment]
Unfortunately no effect.  Here's what's now installed:

```
Grav Package Manager version 0.9.45

08. Admin Panel          [       admin        ]  [v0.6.2]            (installed)
09. Email                [       email        ]  [v0.2.1]            (installed)
10. Form                 [        form        ]  [v0.5.0]            (installed)
11. Login                [       login        ]  [v0.3.3]            (installed)
20. Error                [       error        ]  [v1.3.0]            (installed)
33. Problems             [      problems      ]  [v1.2.0]            (installed)
```

Using Chrome 45.0.2454.101 on OS X

**Comment by rhukster** [comment]
Do you have CSS pipelining on? If so can you try turning it off?

**Comment by andynemzek** [comment]
Yep, that did it.  So this is a bug with the CSS pipelining?

**Comment by rhukster** [comment]
Working on a fix for that now... stand by.

**Comment by rhukster** [comment]
Ok See that fix listed above.  Should resolve it.  Not sure how that was working and now it's not, but still!

**Comment by andynemzek** [comment]
Awesome, thank you!
