### ISSUE TITLE
Elements Field does not work inside a List Field

### ISSUE THREAD

**Issue by jonata** [getgrav/grav-plugin-admin#2241]
I recorded a video showing the issue. If you put a Elements Field inside a List Field (using the example [here](https://learn.getgrav.org/17/forms/blueprints/fields-available#elements-field)), here is the result.

https://user-images.githubusercontent.com/908065/155578113-fbdfe982-a9a2-4568-9491-2b41f2af1bf8.mp4

The selected content does not change/show.

**Comment by w00fz** [comment]
This is fixed
