### ISSUE TITLE
Missing language strings

### ISSUE THREAD

**Issue by kunago** [getgrav/grav-plugin-admin#226]
I have found 4 missing language strings in the languages.yaml (even for English):
* PLUGIN_ADMIN.HOME_REDIRECT_INCLUDE_LANGUAGE
* PLUGIN_ADMIN.HOME_REDIRECT_INCLUDE_LANGUAGE_HELP
* PLUGIN_ADMIN.HOME_REDIRECT_INCLUDE_ROUTE
* PLUGIN_ADMIN.HOME_REDIRECT_INCLUDE_ROUTE_HELP

**Comment by rhukster** [comment]
Actually those settings were removed intentionally as they have also been removed from system.yaml
