### ISSUE TITLE
Couldn't connect 

### ISSUE THREAD

**Issue by arabdivers** [getgrav/grav-plugin-admin#2263]
Couldn't connect to the admin page.

**Comment by arabdivers** [comment]
Fetch Failed:
Failed to fetch
TypeError: Failed to fetch
    at parseJSON (https://www.arabdivers.jo/user/plugins/admin/themes/grav/js/admin.min.js?c9568bfecd:769:19)

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-admin/issues/2254#issuecomment-1077303191
