### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by arabdivers** [getgrav/grav-plugin-admin#2264]
Found an issue I can not use the admin panel page to edit, also all the photos from the website have an error .
Fetch Failed:
Failed to fetch
TypeError: Failed to fetch
    at parseJSON (https://www.arabdivers.jo/user/plugins/admin/themes/grav/js/admin.min.js?c9568bfecd:769:19)

Kindly advice .
Regards.
Obada 
![12](https://user-images.githubusercontent.com/30256453/160279954-f86dc719-84f3-4a8e-af88-8f57dd377d58.JPG)
![Capture](https://user-images.githubusercontent.com/30256453/160279957-ebebfb3e-89c0-490f-b014-45c773fa57df.JPG)

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-admin/issues/2254#issuecomment-1077303191
