### ISSUE TITLE
Copy->Edit Page workflow issue

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#227]
I have noticed that page titles do not seem to display as expected when copying and then editing a page in the AP, and a blank page is also sometimes displayed.

Recipe:
1) Open page
2) Copy page
3) Edit title of page
4) Save (title of page updates as expected)
5) Click Advanced
6) Change default created folder name
7) Click Save

Th page title unexpectedly changes, and states Create and not Edit. It also appears the content is gone, but it is saved if you re-navigate to the page.

Happy to provide any other needed info, etc.

**Comment by paulhibbitts** [comment]
An update - a copied Page also seems to keep the old URL, that is the new page is displayed in a child list, but clicking on it goes to the original page and not the new page.

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-admin/commit/179958e6979bca602eb1948a7ac4fa81d46ec953

Fixed now.

I broke this about 3 weeks ago with another 'fix' but should be properly sorted now.

**Comment by paulhibbitts** [comment]
Thanks very much! Will test once an Admin update is available.
