### ISSUE TITLE
First-time user experience re: user account

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#228]
Perhaps this is already planned, but I think it would draw even more people to Grav to not require the use of the CLI when getting going with the Admin Panel.

In essence, once Grav and the Admin Panel are present and the user goes to .../admin/ if no user account has been created they would get a simple form where they could enter their desired username, password, email address, etc. Once that is done then the user gets logged into the AP and can start working with their site. CLI would still be supported of course, this would just be an alternative workflow.

**Comment by rhukster** [comment]
I hear what your saying, but the only issue is that if someone installs the admin, but doesn't for some reason try to use it straight away. Then someone else might stumble across the `/admin` URL, and allow them to create an account and get full access.

I really don't know what the best way is other than somehow prompting during installation.  In GPM this could be possible, but it's definitely harder with the admin UI.

**Comment by paulhibbitts** [comment]
Hmmmm.. what if this process kicked in with any URL for the site, that way the Admin is bound to see it and set up an account _if_ the Admin Panel is present? I can see there are issues, but I'd love to have a broader audience who is tech-savvy but perhaps not Terminal savvy get going with the Admin Panel.

**Comment by rhukster** [comment]
Currently if there is no user created, there is a message that one needs to be created, i'll try to work out how this can be improved to be more helpful.

**Comment by paulhibbitts** [comment]
Thanks Andy, I think that would be helpful. I also left some possible help text in the Gitter room that might be a useful reference.
