### ISSUE TITLE
Left margin won't return to default after using bullets using Grav

### ISSUE THREAD

**Issue by bpappas20** [getgrav/grav-plugin-admin#2312]
When I use bullets on my Grav site, the margin remains at the first bullet when using any other format, such as headings or plain text.

CODE
#### Heading<br>
* First bullet<br>
* Second<br>
#### New heading<br>
* New first bullet<br>
* Second<br>
END CODE

Here is what I'm using (CODE and END CODE shown for clarity):
CODE
\#### Heading\<br>
\* First bullet\<br>
\* Second\<br>
\#### New heading\<br>
\* New first bullet\<br>
\* Second\<br>
END CODE

It doesn't occur here for headings, but it does for plain text. Any idea what could be the cause on my site?

Thanks for your help.
-Bruce

**Comment by bpappas20** [comment]
Update. I tried a clean Grav install on a different site and the same issue repeated. So it's not an install problem.

**Comment by bpappas20** [comment]
Worked for the text in my example above, but not for the heading in my actual page.

####To raise the group temp:
* Flush hot water through the group before inserting the portafilter.
* Dry pump (by raising and lowering the lever, stopping at the top before water comes out of the group bottom) to circulate water inside the group.
<br>
#### To lower the group temp:
* Cool a portafilter with very cold water or put in the freezer for a period of time, lock it into the group, and allow it to absorb some of the group temp.
* Place a cool wet towel over the back neck of the group.
* Immerse the group in a ramekin (small bowl) of cold tap water with a couple of small ice cubes.
* Or just wait for it to cool.

**Comment by rhukster** [comment]
Please post some screenshots (of code in editor and rendered on site) as i'm not clear on what's going on.

**Comment by bpappas20** [comment]
You pointed me in the right direction. Grav wasn't liking my <br> that I was using for line breaks. I replaced them with double spaces and a return, added one between bullet lists, and it works fine. Weird, but it's fixed.  Thanks.
