### ISSUE TITLE
spl_autoload_register(): Argument #2 ($do_throw) has been ignored, spl_autoload_register() will always throw

### ISSUE THREAD

**Issue by winderickxeli** [getgrav/grav-plugin-admin#2322]
Hi

I'm fairly new to Grav management and suddenly I'm receiving a weird error when we try to visit pages.  
``spl_autoload_register(): Argument #2 ($do_throw) has been ignored, spl_autoload_register() will always throw``  
![image](https://user-images.githubusercontent.com/42890887/203541320-3b491f5d-e31e-4416-9916-098467d808d1.png)

When I request logs on the server with ``./bin/grav logviewer``, I don't get any relavant data. I also tried a ``./bin/grav clearcache`` as suggested by the documentation but to no avail.

On the server are two Grav installations; site A which still works fine, and site B which gives the error. We're currently on the last version on both sites: Grav v1.7.37.1

We can still reach the admin panel of site B. I don't feel like this is a server or update related issue but I'm unfamiliar with Grav to go digging in the code...

Could you please help me or give some pointers to set me on my way?

**Comment by winderickxeli** [comment]
When I disable the `Media Embed` plugin, which is causing the error, I can access the site.

**Comment by rhukster** [comment]
I would typically say to add an issue in the media embed plug-in’s GitHub repo. However I think this plugin is no longer being developed. I suggest finding an alternative plugin if you are needing it.
