### ISSUE TITLE
New feed not loading in PHP 8.2

### ISSUE THREAD

**Issue by techws-dev** [getgrav/grav-plugin-admin#2329]
I was checking the plugin under PHP 8.2, and when loading / reloading the news feed I had these error :

```
Trying to access array offset on value of type bool
```

I had no issue in PHP 8.1.

**Comment by paulmoffat** [comment]
I am also experiencing this issue. I am using PHP 8.2.2

**Comment by rhukster** [comment]
Yup, if you find any more 8.2 issues please create a new issue.
