### ISSUE TITLE
Number of updatable plugins/themes vanishes after reload

### ISSUE THREAD

**Issue by Sommerregen** [getgrav/grav-plugin-admin#234]
This issue is more a question rather than a real bug. It concerns how updates are displayed to the user. Once hitting the button for searching for updates, the admin immediately shows how many plugins/themes need an update. However when reloading the page or clicking on any menu click (e.g. plugins), this info disappears. I manually have to hit the "Check for updates" button again before I can actually update the plugins (the same goes for themes). Is this behaviour intended? Does it happen on your systems, too?

**Comment by rhukster** [comment]
Probably a dom ordering JS issue.

**Comment by flaviocopes** [comment]
You mean the `Check for updates` button on the top-right of the screen?
To me, it just checks and tells how many things you can update, nothing more.

But then to actually update, you need to click update from the dashboard / plugins / themes pages.

**Comment by flaviocopes** [comment]
You mean the sidebar count?

![screen shot 2015-10-27 at 18 00 05](https://cloud.githubusercontent.com/assets/11783388/10765742/93ae3118-7cd4-11e5-97f0-269fc055c97f.png)

**Comment by Sommerregen** [comment]
@flaviocopes Yes, I mean the sidebar count, it's vanishing when I reload the page. I then have to click on the "Check for updates" button to make them appear. I'm on it to give you more information. I already tested the ajax action and this works fine. It must be somehow connected with the browser Firefox) or system (Windows). I'll test more. I haven't found yet the JS code, which runs to show the sidebar count after a reload. I've only found the code from the "Check for updates" button...

**Comment by flaviocopes** [comment]
Ah I'll test firefox on windows. On a mac it works fine (FF 41)

**Comment by flaviocopes** [comment]
It's under `GPMRefresh()` in the admin theme's `js/admin-all.js`

**Comment by Sommerregen** [comment]
I have FF 41.0.2. Maybe it has something to do with my multisite installation. I'm using a custom `setup.php`, but the Grav refresh call always returns the correct updateable plugins/themes. Only the sidebar count vanishes... On a fresh install it is working!

Maybe I have to setup a clean grav environment again. I'll dig into it further, and get back to you (e.g. on Gitter) when I have time. Closing this for now. Thanks.

**Comment by flaviocopes** [comment]
If you post your `setup.php` file (pm if you want) I'll try myself too
