### ISSUE TITLE
Class 'ZipArchive' not found error when updating to Grav v1.7.42.1

### ISSUE THREAD

**Issue by reilly33** [getgrav/grav-plugin-admin#2363]
I'm trying to install Grav v1.7.42.1, but I keep getting an error saying I don't have 'ZipArchive'.
What can I do to resolve this?

**Comment by rhukster** [comment]
This is not a hard thing to find out:

https://stackoverflow.com/questions/3872555/fatal-error-class-ziparchive-not-found-in
