### ISSUE TITLE
The requested resource /admin/media/blog/articolo-blog.json/task:listmedia was not found on this server.

### ISSUE THREAD

**Issue by micc83** [getgrav/grav-plugin-admin#237]
Grav version 1.0.0-rc.1
Admin Panel  v1.0.0-rc.2

When trying to upload a new image into a blog item I get the following responses: 
POST http://localhost:999/admin/media/blog/articolo-blog.json/task:listmedia 404 (Not Found)
POST http://localhost:9999/admin/media/blog/articolo-blog.json/task:addmedia 404 (Not Found)

The response body is some framework generated html with the following content:
Not Found
The requested resource /admin/media/blog/articolo-blog.json/task:addmedia was not found on this server.

**Comment by flaviocopes** [comment]
Are you using PHP's built-in webserver?
Or Windows?

**Comment by micc83** [comment]
PHP's built-in webserver.

**Comment by flaviocopes** [comment]
The Admin plugin will not run on it due to its limited features, see http://learn.getgrav.org/basics/installation#phps-built-in-web-server

**Comment by micc83** [comment]
Sorry about that. I'll keep looking into a proper web server.

**Comment by flaviocopes** [comment]
No problem :+1:
