### ISSUE TITLE
Better Comments Plugin: "Unmaintained - do not use"

### ISSUE THREAD

**Issue by aaronxn** [getgrav/grav-plugin-admin#2373]
Better Comments v1.0.10 by @[AizkibelRojo](https://github.com/AizkibelRojo), released on Oct 25, 2022, is the last release and **is no longer maintained**. It should not be listed in the stable Admin GUI plugin page until it is updated for the current version of Grav. 

Many plugins are outdated and broken for the current version of Grav. This problem _needs_ to be addressed.

**Comment by rhukster** [comment]
already removed
