### ISSUE TITLE
Language method error

### ISSUE THREAD

**Issue by mesguerrab** [getgrav/grav-plugin-admin#238]
Whoops\Exception\ErrorException thrown with message "Call to undefined method Grav\Common\Language\Language::isLanguageInUrl()"
Stacktrace:
#0 in C:\xampp\htdocs\magment\user\plugins\admin\admin.php:362

**Comment by flaviocopes** [comment]
Could be solved by https://github.com/getgrav/grav-plugin-admin/commit/f0f8cd6c7fd49f96c30789012c34ea841fc2cd36

**Comment by rhukster** [comment]
Actually that was commented out in Admin RC2.  Can you check to make sure Grav and Admin are both up to date?  You might have to do with GPM - http://learn.getgrav.org/advanced/grav-gpm

**Comment by mesguerrab** [comment]
I upgraded to RC2 via GPM. Still same issue.

**Comment by flaviocopes** [comment]
Really strange. Now RC3 is out, try clearing all the cache (`bin/grav clear-cache --all`) and trying updating.
If the problem persist, can you paste the line that the error points to?

**Comment by mesguerrab** [comment]
I cleared the cache but could not install RC3 via GPM. Same error as before:
The error points to:

            $this->template = array_shift($array);
            $this->route = array_shift($array);
        }
 
        /** @var Language $language */
        $require_language = ['pages', 'translations'];
        $language = $this->grav['language'];
        if ($language->isLanguageInUrl() && !in_array($this->template, $require_language)) {
            $this->grav->redirect($this->uri->route());
        }

**Comment by rhukster** [comment]
Can you try updating Grav from GPM:

```
$ bin/gpm selfupgrade --force
```

**Comment by mesguerrab** [comment]
Now it works. Many thanks for your help!
