### ISSUE TITLE
Invalid input in “Content” Failed to save entry: Form validation failed, please check your input

### ISSUE THREAD

**Issue by LauPld** [getgrav/grav-plugin-admin#2385]
Hi
Iam experiencing this error message when updating content and trying to saving it on some pages of a grav website. I can only change and save the content directly from the files and not from the back office. Is there a way to fix this bug please ? Thanks for the help

**Comment by moemabaiao** [comment]
Hello!
I'm also going through the same problem.
Isn't there some workaround to deal with this bug?

**Comment by rhukster** [comment]
Some more information would be a great help. What theme are you using (as it can impact the blueprints), what type of page are you trying to save, what is the error? etc etc.  

If possible please provide a zip of the 'user' folder where this can be replicated.

**Comment by LauPld** [comment]
Thanks for the responses. I am no more experiencing the issue since I 've changed the chmod in some files server side. By the way, Grav is a killer CMS, keep up the good work !
