### ISSUE TITLE
Markdown editor styling issues

### ISSUE THREAD

**Issue by joshbartolomucci** [getgrav/grav-plugin-admin#239]
If you add the markdown editor as a list item, buttons and textarea are too large. Also, textarea only allows a few characters because of other elements blocking.

![grav_list](https://cloud.githubusercontent.com/assets/999503/10761174/2e6e0bf2-7c8e-11e5-86fe-249dedd3ac18.png)

**Comment by rhukster** [comment]
Hmm.. I don't think we have really tested using the markdown field outside of the Page content form.  

We'll take a look to see how to ensure this renders/stores properly when used in custom forms. Thanks.

**Comment by joshbartolomucci** [comment]
Thanks for looking into it.  Really appreciate it.

**Comment by flaviocopes** [comment]
It works, and saves the values to the page header, but we should drop the preview button as it uses the page preview functionality

**Comment by joshbartolomucci** [comment]
Just to confirm, I experience the issue when editor was used in a List

**Comment by lukasluecke** [comment]
Yeah the styling issues still happen if you try to use the markdown editor for list items (as is the case in the original screenshot).

**Comment by flaviocopes** [comment]
Ok I got it! 
Actually I got the an empty textarea since probably I am testing inside a page that already has an editor in another tab.
Can you paste here your page blueprint, just to make sure I fix the exact issue you're having?

**Comment by w00fz** [comment]
This should be good now
