### ISSUE TITLE
Newuser command not working on windows

### ISSUE THREAD

**Issue by labo-css** [getgrav/grav-plugin-admin#240]
Hello, i tried many things, adding the bin/grav to path, trying to configure Cmder (my cli app) and nothing worked. I don't understand i successfully added ruby on the path before, no reason to fail here.

So, do you have any basic tutorial to make the grav cli tools to work on windows?

**Comment by flaviocopes** [comment]
Does bin/grav have execution permission? Also try calling it with `./bin/grav`

**Comment by labo-css** [comment]
I used the git bash with cmder, it work now
