### ISSUE TITLE
Account creation does not support french accents

### ISSUE THREAD

**Issue by labo-css** [getgrav/grav-plugin-admin#241]
I created i new user with grav newuser and in the title i used "Développeur front end".
The account file was created but the admin login does not let me in, in fact the account file used a <?> symbol instead of the "é".

Corrected manually and then, it work. So, it seems the cli tool have trouble to register accents.

**Comment by flaviocopes** [comment]
Thanks for reporting, must be a windows/git cli encoding issue. Just tested on OSX, works correctly

**Comment by rhukster** [comment]
This is not something we can fix.  Basically the terminal you are using must support extended encoding.  Windows does not support this by default, although it might work ok in Cygwin or one of the other more 'unix-like' terminal apps.
