### ISSUE TITLE
Adding port number when creating folder

### ISSUE THREAD

**Issue by motionthings** [getgrav/grav-plugin-admin#2418]
When I add a new folder and click create it adds the port number at the end of the url.

![grav-add-folder](https://github.com/getgrav/grav-plugin-admin/assets/264911/5ef9e1fc-ea86-4ba9-8e54-a858f7bf3a26)

![grav-vew-folder-error](https://github.com/getgrav/grav-plugin-admin/assets/264911/eb9d02b5-75af-4100-a0f2-6ba1fb096189)

If I remove the port number (:8111) at the end, everything is fine and it did create the folder.

I am running this in a docker container on Unraid.
Not sure if that is the problem?

And this problem will go away for me when I give the site an actual url and cert through my proxy.
So it's not a "biggie".

**Comment by rhukster** [comment]
I don’t have this problem when running a server  on a specific port so probably some issue with your docker setup. If you are using the same docket in production it might be an issue.  

Best to test it.

**Comment by motionthings** [comment]
I did a reinstall and the problem was gone.
Don't know what changed.

Closing
