### ISSUE TITLE
AJAX error when upgrading

### ISSUE THREAD

**Issue by jeebeezebee** [getgrav/grav-plugin-admin#242]
from v1.0.0-rc.1 to v1.0.0-rc.2

**Comment by rhukster** [comment]
What is the contents of the XHR data response as displayed in the developer tools?  Does clearing the cache and trying again help?

**Comment by jeebeezebee** [comment]
I don't know what is the develoèr tools but I solved the problem by 
uploading the upgrade with FTP.
