### ISSUE TITLE
Pages field as a List item issue

### ISSUE THREAD

**Issue by joshbartolomucci** [getgrav/grav-plugin-admin#243]
If you use the Pages field as a List item, changes to items are not saved: http://d.pr/i/17QxI/5xPBAhnU  

I found that if you add another field (ie: Text Field) with the Pages field, data will then save:  http://d.pr/i/Vp7W/xzKEz77T But the Pages field does not save on first try.  If you choose your page again and save, it properly saves.

If you remove the text field from the blueprints, data will not save.

**Comment by w00fz** [comment]
Good catch, this is fixed now!

**Comment by joshbartolomucci** [comment]
Thanks so much!
