### ISSUE TITLE
"Validation failed" Error Message

### ISSUE THREAD

**Issue by vmcosta** [getgrav/grav-plugin-admin#246]
Trying to change admin password from within the admin itself, gives a validation failed error, see below.
```
Validation failed: PLUGIN_ADMIN.PASSWORD_VALIDATION_MESSAGE
```

**Comment by rhukster** [comment]
https://github.com/getgrav/grav/commit/77d80f12f3acf53ee918b85acedd18bae5b0c087

Fixed in develop
