### ISSUE TITLE
Save not working on Edge browser

### ISSUE THREAD

**Issue by 810** [getgrav/grav-plugin-admin#247]
Save not working on Edge browser.

**Comment by rhukster** [comment]
As mentioned before. The admin has only been tested in Safari, Chrome, Firefox.  IE is not at the top of our list at the moment as we're mac-centric.  We'll get to it though.  For now please use one of these other browsers.

**Comment by paulhibbitts** [comment]
Ah yes, I just ran across this same issue (left note in Gitter room).

**Comment by 810** [comment]
merged: https://github.com/getgrav/grav-plugin-admin/pull/261
