### ISSUE TITLE
Updating account info page behavior re: password field

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#249]
While trying to update info on the account page I was not able to save my changes without entering a (new) password.

If the password field is left blank then any changes are made to this page should be saved and the password left unchanged.

**Comment by flaviocopes** [comment]
Yes the current behavior is a bit "strange". Will make sure that when leaving the password field blank, the user settings get saved

**Comment by paulhibbitts** [comment]
Thanks very much Flavio.
