### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by OwenMelbz** [getgrav/grav-plugin-admin#250]
I've just installed a fresh core version of grav.

I've updated the plugins etc etc. then installed the admin plugin via the CLI.

I now try access `/admin` and get `500 Internal Server Error`

My apache log says

```
[Mon Nov 02 20:01:01 2015] [error] [client 127.0.0.1] Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://owen.grav.dev/admin
```

**Comment by rhukster** [comment]
Is Grav working on the front end?  If you create a new page (manually: http://learn.getgrav.org/basics/basic-tutorial) Can you navigate to it?

**Comment by rhukster** [comment]
Closing due to lack of feedback.  Please reopen if you want to continue tracking this down.

**Comment by JohnGurin** [comment]
`grav core`, `grav core + admin plugin`, skeletons v 1.0.10
  
All give 500 on any url `grav.dev/<any_path>`
For example, `grav core` shows home page on `grav.dev` but gives `500` when `grav.dev/home`.

Windows 8.1 Pro  64-bit
XAMPP Version: 7.0.2 (Apache 2.4.18)

httpd-vhosts.conf
```
<VirtualHost *:80>
  ServerAlias *.dev
  VirtualDocumentRoot "c:/Users/John/Documents/_www/%1/"

  <Directory "c:/Users/John/Documents/_www">
    AllowOverride All
    Require all granted
  </Directory>
</VirtualHost>
```

**Comment by flaviocopes** [comment]
Most probably a misconfiguration of the web server. Take a look at learn.getgrav.org/troubleshooting/internal-server-error for common causes of 500 errors.

**Comment by JohnGurin** [comment]
Thanks, uncommenting `# RewriteBase /` helped.

**Comment by rhukster** [comment]
Glad you got it sorted.

**Comment by JohnGurin** [comment]
Actually, I red `.htaccess` comments. But I skipped the `RewriteBase` part because the paragraph starts with `# If you are getting 404 errors...` . I was getting 500. Just for your information.
```

**Comment by flaviocopes** [comment]
Modified the comment
https://github.com/getgrav/grav/commit/5d97fed383a2ec960098dfe2f1c4fe614dd0766d

Il giorno lun 18 apr 2016 alle ore 21:31 JohnGurin <notifications@github.com>
ha scritto:

**Comment by vpietri** [comment]
I think, ```RewriteBase \``` is needed only when you're working with VirtualDocumentRoot in your virtual host.
