### ISSUE TITLE
Editor "Preview" button not working as expected with Modular content pages

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#254]
If the "Preview" button is clicked when editing a modular content page the UI of the editor itself seems to be presented along with the content preview.

Snapshots attached:
![edit _reminders cmpt-363 2](https://cloud.githubusercontent.com/assets/1812771/10950863/e83ae8dc-82ee-11e5-98a8-09a5b7851840.png)

![edit _reminders cmpt-363](https://cloud.githubusercontent.com/assets/1812771/10950841/ccc279ee-82ee-11e5-9a5d-f68e8dfa95d0.png)

**Comment by flaviocopes** [comment]
Uhm strange! I don't have this problem. Which theme are you using?

**Comment by paulhibbitts** [comment]
It didn't occur to me it might be theme related. I am using Materialize with a fair bit of inherited theme elements.

**Comment by flaviocopes** [comment]
Maybe put your user/ folder on Dropbox and post me a link on Gitter so I can try myself

**Comment by bobrocke** [comment]
I'm the author of the Materialize theme, and don't have that problem on my test set-up. I did have some trouble, since fixed, with my theme's CSS intruding on the Admin. Now I can't remember how I fixed it! I'll keep looking; maybe there's a clue there.

**Comment by paulhibbitts** [comment]
Thanks Flavio and Bob, here is a link to the user folder if that helps: https://www.dropbox.com/s/8u2pbz8ixu2h8q2/user.zip?dl=0

**Comment by flaviocopes** [comment]
I installed and recreated, find the cause in this line: https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Page.php#L1634

Commenting that, it works. Not sure why that is needed. @rhukster have an explanation at why is that needed?

Anyway this behavior is not happening on my other installs, I thought it could be related to the inherited theme and the fact it does not provide a default.html.twig (but adding it makes no difference, so I'm not sure).

**Comment by rhukster** [comment]
@flaviocopes can you let me know what that line is again? It doesn't match up anymore.  Cheers.

**Comment by flaviocopes** [comment]
Sorry @rhukster missed your reply! 
This line: https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Page.php#L1657

**Comment by flaviocopes** [comment]
PR https://github.com/getgrav/grav/pull/460 fixes the issue without modifying the behavior on the frontend. Probably not the best way to handle it?

**Comment by rhukster** [comment]
I'm a bit confused.  Does this only happen for Materialize theme? Can this be replicated in Antimatter?  If not then I think this fix could cause more problems than it fixes. That process is there for a legitimate reason (even if i can remember exactly what that reason is!)

**Comment by flaviocopes** [comment]
Tested, it's not the theme, even with antimatter with the default modular pages (text for example), all works fine. If adding another one (with any name), it outputs this strange layout.

**Comment by flaviocopes** [comment]
For example I tried duplicating `templates/modular/text.html.twig` to `templates/modular/text2.html.twig`, and using a `text2.md` page file, the bug is replicated

**Comment by rhukster** [comment]
Ok was a bit tricky to track down, but found it!

**Comment by paulhibbitts** [comment]
Great to hear, thanks!
