### ISSUE TITLE
Gravatar Causes SSL Warnings When Loaded Over HTTPS

### ISSUE THREAD

**Issue by adkinstm** [getgrav/grav-plugin-admin#255]
When the Grav admin dashboard is loading over SSL, insecure content errors occur because the Gravatar image is not being loaded over SSL.  Briefly poked around to try to find where to fix it, but figured people besides me might run into this.

![grav - insecure content](https://cloud.githubusercontent.com/assets/6365836/10959647/023ccc46-8349-11e5-893f-2bdab67a2b74.png)

**Comment by flaviocopes** [comment]
:+1:
