### ISSUE TITLE
Little CSS bug in the header menu part on low size devices

### ISSUE THREAD

**Issue by muuvmuuv** [getgrav/grav-plugin-admin#256]
If you resize to a lower size like for mobile devices. The action buttons and title is doing some float shit. Its not the hardest issue but should be fixed in the next update.

Browser: Chrome 46.0.2490.80 (64-bit)
OS: MAC OSX El Capitan 10.11.1 (15B42)
GRAV: 1.0.0-rc.4

![dashboard promediagroup](https://cloud.githubusercontent.com/assets/11534760/10967276/9e326442-83b9-11e5-94e7-cf2271e8b8b3.png)

Thanks for this create, beautiful and simple CMS
Have a nice day

**Comment by flaviocopes** [comment]
PR https://github.com/getgrav/grav-plugin-admin/pull/265 should fix this

**Comment by lukasluecke** [comment]
This issue should probably be closed now, since the PR was merged.
