### ISSUE TITLE
Display internal pages into the home navigation.

### ISSUE THREAD

**Issue by antisnerd** [getgrav/grav-plugin-admin#257]
Hi all,

i have 2 folders: one for the Homepage(Modular onescroll)  and one folder for 4 internal pages.
What i'm trying to do is to display into the hompage navigation a link fot this 4 internal pages. Im trying with 
```
{% set datacenter_page = page.find('/services/datacenter') %}
<li><a href ="{{ datacenter_page.url() }}">{{ datacenter_page.menu() }}</a></li>
```
 but this call only the .children element, and my pages are into a different folder. Any ideas?

**Comment by rhukster** [comment]
This is not an appropriate admin plugin issue.  Please ask this kind of question on the forum or on gitter chat via http://getgrav.org
