### ISSUE TITLE
No guestbook page file

### ISSUE THREAD

**Issue by aptly-io** [getgrav/grav-plugin-admin#258]
Have the guestbook plug-in installed.
Updated all plug-ins, core and delivery theme (on 5/11/2015).
Tried to add a guestbook page through the admin plug-in in the delivery skeleton.
But the "Page File" does not have Guestbook in its list of available templates in the "Add File" dialog.

Note maybe this is an issue of the guestbook plug-in rather than the admin plug-in

**Comment by flaviocopes** [comment]
You're right. I'll leave this open, in the meanwhile copy the `user/plugins/guestbook/templates/guestbook.html.twig` to `user/themes/delivery/templates/`

**Comment by rhukster** [comment]
This is really a bug in the guestbook plugin.

**Comment by flaviocopes** [comment]
Released a fix for that plugin. Will soon appear on the GPM
