### ISSUE TITLE
UX: Date format option not precise enough

### ISSUE THREAD

**Issue by reachcontent** [getgrav/grav-plugin-admin#26]
The default **January 1st** example is not to show the formatting differences. Pick a day bigger than the 12th so that it is easy to see which format is US (MM-DD) and which is EU/International (DD-MM).

January (or March...) the 31st (01-31 or 31-01) is a better example to help the user make a quick and easy choice.

**Comment by rhukster** [comment]
Which dates exactly are your talking about? A screenshot would work fine.  Cheers!

**Comment by reachcontent** [comment]
Sorry, I wrongfully assumed it was obvious I was talking about Date setting in System Configuration.
Ex: 01-01-14 is ambiguous since you don't know if it will render DD-MM or MM-DD
![datesformatsystemcfg](https://cloud.githubusercontent.com/assets/11965032/9138741/f5150830-3d25-11e5-97a4-c26de6938cdc.png)

**Comment by rhukster** [comment]
Got yah, good point!  I will update this.

**Comment by reachcontent** [comment]
Thanks
