### ISSUE TITLE
Error whille switching to the page priview mode

### ISSUE THREAD

**Issue by gautamkrishnar** [getgrav/grav-plugin-admin#266]
![screenshot 40](https://cloud.githubusercontent.com/assets/8397274/11073403/7bf57670-8810-11e5-8368-1f613f3190be.png)
![screenshot 41](https://cloud.githubusercontent.com/assets/8397274/11073480/d4a79c8a-8810-11e5-8e07-c4c76b02a2ca.png)

Url: installdir/admin/pages/home/_banner
Theme: Twenty 1.4.0

**Comment by flaviocopes** [comment]
I think it's the same issue as https://github.com/getgrav/grav-plugin-admin/issues/254 - are you using an inherited theme?

**Comment by gautamkrishnar** [comment]
Closing this now
