### ISSUE TITLE
H3 style in plugin settings form

### ISSUE THREAD

**Issue by lab-dev-code** [getgrav/grav-plugin-admin#267]
Hello,

The `<h3>` tags created with  **spacer** fields (plugin Forms) don't look very well :(
![H3 in the admin UI](http://i.imgur.com/cgiileU.png)

I modified a little the CSS with `padding: 0 3rem 0.5rem;` and replaced the `<hr>` added when using the `underline: true` option by `border-bottom: 3px solid #e1e1e1;` and it already looks nicer :
![Once modified](http://i.imgur.com/ZmjeCHQ.png)

**Comment by flaviocopes** [comment]
Can you create a PR for this?

**Comment by lab-dev-code** [comment]
Yes, I'll work on it

**Comment by ramono** [comment]
This seem to be happening again, as there seem to be something else overriding the original fix, I don't know where this comes from.

![screen shot 2017-03-22 at 15 16 19](https://cloud.githubusercontent.com/assets/1303840/24205196/9ed92292-0f12-11e7-8a6b-0be70478e3ff.jpg)
