### ISSUE TITLE
Adding a "Save" keyboard shortcut when editing pages

### ISSUE THREAD

**Issue by bovisp** [getgrav/grav-plugin-admin#269]
Hi

Several individuals, including myself, have been discussing on Gitter the usefulness of having a "Save" keyboard shortcut when editing pages in the admin panel. Probably something along the lines of `CTRL` or `CMD` + `S`.

Thanks so much!

Paul B.

**Comment by solusipse** [comment]
On Windows, pressing `RIGHT ALT` + `S` forces panel to save post. That is a problem for users with regional keyboard layouts (e.g. it's not possible to type in `ś`). On Mac (where meta key is control) everything works fine.

**Comment by flaviocopes** [comment]
For reference, @solusipse added this PR https://github.com/getgrav/grav-plugin-admin/pull/405
