### ISSUE TITLE
Buttons JS fail in admin

### ISSUE THREAD

**Issue by amdad** [getgrav/grav-plugin-admin#270]
On one-page demo site _showcase in admin, you have tab called _Buttons_. When you add more than 2 items of those buttons. Switcher called Primary doesn't work for more than two instances. So when I switch third one it switch second one. Third stays inactive. Bug?

![](https://files.gitter.im/getgrav/grav-plugin-admin/s814/01.png)

**Comment by flaviocopes** [comment]
Fixed in develop!
