### ISSUE TITLE
Markdown Editor on other Pages than Page edit

### ISSUE THREAD

**Issue by lennerd** [getgrav/grav-plugin-admin#271]
It would be great to be able to work with the Markdown editor also in other places of the admin panel.

For example, I would like to have global content for the footer which is as far as I know best suited for the `site.yaml` configuration file. As I'm working with multiple columns and special markup, it would be great to have Gravs Admin Markdown editor in place.

**Comment by lukasluecke** [comment]
#239

**Comment by lennerd** [comment]
Unfortunately not. It simply renders a textarea form element, because the markdown code is not added to the assets I think:

https://github.com/getgrav/grav-plugin-admin/blob/fc87d184e8d03d29c9ed379f17dd6fb739575f37/themes/grav/templates/pages.html.twig#L41-L45

**Comment by lukasluecke** [comment]
Oh alright, I still think it should be somehow merged into one issue, as the other one also is about "using the markdown field outside of the Page content form". Although loading the markdown code for other pages in the admin should be a pretty small & easy change.

**Comment by flaviocopes** [comment]
We just need to load the codemirror js and css into the configuration views, just tested. @rhukster you think it's fine?

**Comment by flaviocopes** [comment]
(and have a way to remove the preview button)

**Comment by lennerd** [comment]
I think there is another problem with elements interacting with multiple Markdown powered textareas.

For example, when you have multiple Markdown fields in one admin page (so also when placed on different tabs), buttons like the "Insert" button from page media items choose always the last insert textarea. So the media is not insert into the main content field but into manually added fields.

**Comment by flaviocopes** [comment]
Yes, multiple markdown fields is another issue, not yet tested outside the main content area.

**Comment by w00fz** [comment]
You can now use markdown fields in Configurations (System, Site, etc), Plugins and Themes.
There's also now support for a label (previously not available).

**Comment by w00fz** [comment]
Also multiple markdown fields should be fixed with #285
