### ISSUE TITLE
Private browsing Breaks adding pages in admin

### ISSUE THREAD

**Issue by Code-Slave** [getgrav/grav-plugin-admin#272]
In sfari if i have private browser window. Admin loses any functionality regarding pages

**Comment by flaviocopes** [comment]
Thanks for reporting, fixed in develop. The problem was that Safari in private mode blocks Local Storage and Session Storage, setting a quota of 0 so all attempts to save something generate an error and all the subsequent JS breaks.

**Comment by Code-Slave** [comment]
excellent. thanks
