### ISSUE TITLE
Modular visibility

### ISSUE THREAD

**Issue by lennerd** [getgrav/grav-plugin-admin#274]
I struggle with navigation generation as I'm trying to have links to certain modulars of a page (not all). I thought of using the `visible` property to define which modulars should be shown in the navigation. Unfortunately every modular is invisble by default.

https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Page.php#L1635

When I comment out this line, the modulars are visible as expected. Does that have any performance reasons? Why is this necessary?

**Comment by rhukster** [comment]
Modular sub pages (i.e. ones that being with `_`)  **cannot be visible** in a menu because they are not a page at all, they are just elements of a parent modular page.

If you take a look at the `modular.html.twig` file in antimatter theme, you will see how the modular **on-page** menu is not a true menu but just manually built from the titles of the modular sections.

https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/modular.html.twig#L30-L45

**Comment by lennerd** [comment]
Oh okay. I understood the ideas behind Modulars and Pages, but because they are handled by the same PHP data structure I thought I could use them for both navigation.

So how would you implement a navigation with multiple main pages and dropdowns with links to sub sections of this pages?

I already took a look into the antimatter theme and tried to adopt the navigation for my clients theme:

``` twig
{% import 'macros/helpers.html.twig' as helpers %}

<ul class="nav__list nav__list--main">
    {% for child in pages.children.visible %}
        {% set has_modular = child.children.modular.visible.count > 0 %}
        <li class="nav__list__item{% if child.active or child.activeChild %} active{% endif %}">
            <a href="{{ child.url }}"{% if has_modular %} data-toggle="dropdown"{% endif %}>
                {{ child.menu }}
                {% if has_modular %}<i class="icon icon--arrow-down"></i>{% endif %}
            </a>
            {% if has_modular %}
            <ul class="nav__list nav__list--main">
                {% for modular in child.children.modular.visible.order(child.header.content.order.by, child.header.content.order.dir) %}
                    <li class="nav__list__item">
                        <a href="{{ child.url }}#{{ helpers.slug(modular.slug) }}">{{ modular.menu }}</a>
                    </li>
                {% endfor %}
            </ul>
            {% endif %}
        </li>
    {% endfor %}
</ul>
```

The slug helper simply trims all `_` characters.

**Comment by lennerd** [comment]
Ping @rhukster
