### ISSUE TITLE
Add more visible preview page button in admin

### ISSUE THREAD

**Issue by amdad** [getgrav/grav-plugin-admin#275]
# »

Is not very logic / userfriendly UX. I suggest to add it in buttons line, before or after *Save* button.

:mag: Preview

**Comment by flaviocopes** [comment]
I think the current preview is less intrusive and especially on mobile and thin screens it allows to save some space on the page, instead of yet another button

**Comment by amdad** [comment]
But is not intuitive. Icon » ... is not very obvious it open page itself.  My suggestion about button was only one idea. Another one is, that whole Page title should be linked to preview. With _eye_ icon instead of ».

**Comment by rhukster** [comment]
![2015-11-19-22-x29nu](https://cloud.githubusercontent.com/assets/1084697/11292356/02390850-8f0a-11e5-806c-f948b5014f78.png)

**Comment by amdad** [comment]
Nice, thanks!
