### ISSUE TITLE
Blog child order in grav admin

### ISSUE THREAD

**Issue by fredericmohr** [getgrav/grav-plugin-admin#277]
Hi,

first of all thanks for GRAV, it's awesome! I'm using it for our website and blog and there is one thing that's a bit annoying when it comes to blogging. The child pages under my blog parent page are sorted by alphabet instead of publish date. (I added the numbers to represent the publishing order, 1=first, 10=newest)

![grav-blog-children](https://cloud.githubusercontent.com/assets/5955966/11218017/792b4404-8d53-11e5-8908-d8912cfcd012.png)

Any chance this could be changed? I had to force the order of modular pages by naming the modular pages

_01_something
_02_something-else

But I would like to avoid that with real pages (e.g. blog posts) as it would be visible in the url later and also I would have to lookup the number of the last blog post each time I write a new one.

Thanks!

**Comment by flaviocopes** [comment]
I think it makes sense, should it be a general rule so we follow the parent page ordering settings? It's also applicable to modular pages

**Comment by fredericmohr** [comment]
I think it would be nice to have a drop down menu for each parent page, as to how child pages are ordered. The order on the website should then be the same as in the grav admin interface.

    Order: [ alphabet ascending      ]
           [ alphabet decending      ]
           [ publish date ascending  ]
           [ publish date descending ]
           [ manual                  ]

manual would then be the same as in default page, where child pages can be sorted through drag&drop. 

Hope that makes sense...

**Comment by flaviocopes** [comment]
Depending on the page type and the blueprint that defines it, it's already there (e.g. blog.md pages in the Blog list tab). That's up to the theme. 

In the admin we could use the value of `content.order` to determine the ordering of the child pages.

**Comment by fredericmohr** [comment]
You're right, that's what I used to sort the content on the website. Only thing that's left is doing the same in the admin panel. I don't know enough about the admin plugin to help much there unfortunately.
