### ISSUE TITLE
Date format dropdown menu on admin plugin shows incorrect date

### ISSUE THREAD

**Issue by artecnico** [getgrav/grav-plugin-admin#278]
It should show "Wed, 18 Nov..." on the third row (see attached image)

![captura de pantalla de 2014-12-29 20_25_47](https://cloud.githubusercontent.com/assets/15910243/11244931/8c359ea6-8e10-11e5-9af0-e615bc9eea39.jpg)

**Comment by flaviocopes** [comment]
Good catch!
