### ISSUE TITLE
error while downloading any theme or plugin

### ISSUE THREAD

**Issue by urbanhop** [getgrav/grav-plugin-admin#279]
installed from getgrav today. whenever i install a theme or plugin i receive an error message like this (in the admin page)

Error while trying to download 'https://github.com/getgrav/grav-theme-twentyfifteen/zipball/1.0.4'

but generally: nice plugin, nice grav

**Comment by flaviocopes** [comment]
Please, 'Grav' as in Gravity, not grave, which is another thing! :)

That said, are you behind a proxy? In that case http://learn.getgrav.org/troubleshooting/proxy. Can you install using `bin/gpm` (http://learn.getgrav.org/advanced/grav-gpm) or same error?

**Comment by urbanhop** [comment]
no proxy. the link is working in the browser, eg 'https://github.com/getgrav/grav-theme-afterburner2/zipball/1.5.1.

disabling the firewall did not help. in the console window i can see no error. if i can provide any error log, will do so.

this is a minor issue for me, since i can download directly to the file system, just wanted to let you know.

**Comment by flaviocopes** [comment]
Did you also try using Grav's `bin/gpm` command-line utility?

**Comment by urbanhop** [comment]
yes, pls see my updated comment .

**Comment by rhukster** [comment]
```
bin/gpm https://github.com/getgrav/grav-theme-afterburner2/zipball/1.5.1
```

is not valid, try:

```
bin/gpm install afterburner2
```

**Comment by rhukster** [comment]
Do you have Curl installed? how about openssl support in php.ini?  Please double check you have the requirements: http://learn.getgrav.org/basics/requirements#php-requirements

**Comment by urbanhop** [comment]
oh yes. editing php.ini 

    ;extension=php_openssl.dll

to

    extension=ext/php_openssl.dll

did it. thank you so much, you have been very helpful.
