### ISSUE TITLE
Antimatter Inheritance Problem

### ISSUE THREAD

**Issue by fluidworks** [getgrav/grav-plugin-admin#280]
Hello, i've followed the instruction in the documentation for extending Antimatter theme (http://learn.getgrav.org/themes/customization#theme-inheritance)

I'm created a *warg* directory, the default blueprints.yaml and a *warg.yaml* composed as follow:

streams:
schemes:
  theme:
    type: ReadOnlyStream
    prefixes:
      '':
        - user/themes/warg
        - user/themes/antimatter

I have also created a *warg.php* class:

<?php
namespace Grav\Theme;
class Warg extends Antimatter
{
  // Some new methods, properties etc.
}
?>

I'm getting this error: 

Grav\Common\Themes autoloadTheme
…/­system/­src/­Grav/­Common/­Themes.php290

I've checked the method and i've received this:

$path = ltrim(preg_replace('#\\\|_(?!.+\\\)#', '/', $class), '/');
string(10) "Antimatter" 
$file = $locator->findResource("themes://{$path}/{$path}.php");
bool(false)

What's wrong ?

Thank you !

**Comment by rhukster** [comment]
BTW, this is actually an issue with Grav itself, not the admin. So should really be an issue in https://github.com/getgrav/grav/issues

I believe its a case sensitivity issue, that $path should be `antimatter` not `Antimatter`.  Can you try changing the preg_replace line with:

```
$path = ltrim(strtolower(preg_replace('#\|_(?!.+\)#', '/', $class), '/'));
```

**Comment by rhukster** [comment]
Actually it looks like this is already fixed but just not released yet:

https://github.com/getgrav/grav/commit/ed8b08a9e4d01a595a472fa538c8917fd82bcd20

We'll get that release out soon.

**Comment by fluidworks** [comment]
Thank you. This fixed it.

But now i've another problem.

RuntimeException thrown with message "Template "blog.html.twig" is not defined."

Stacktrace:
#9 RuntimeException in /home/listalav/public_html/sito/system/src/Grav/Common/Twig/Twig.php:335
#8 Twig_Error_Loader in /home/listalav/public_html/sito/vendor/twig/twig/lib/Twig/Loader/Chain.php:115
#7 Twig_Loader_Chain:getCacheKey in /home/listalav/public_html/sito/vendor/twig/twig/lib/Twig/Environment.php:312
#6 Twig_Environment:getTemplateClass in /home/listalav/public_html/sito/vendor/twig/twig/lib/Twig/Environment.php:378
#5 Twig_Environment:loadTemplate in /home/listalav/public_html/sito/vendor/twig/twig/lib/Twig/Environment.php:347
#4 Twig_Environment:render in /home/listalav/public_html/sito/system/src/Grav/Common/Twig/Twig.php:324
#3 Grav\Common\Twig\Twig:processSite in /home/listalav/public_html/sito/system/src/Grav/Common/Grav.php:157
#2 Grav\Common\Grav:Grav\Common\{closure} in /home/listalav/public_html/sito/vendor/pimple/pimple/src/Pimple/Container.php:113
#1 Pimple\Container:offsetGet in /home/listalav/public_html/sito/system/src/Grav/Common/Grav.php:255
#0 Grav\Common\Grav:process in /home/listalav/public_html/sito/index.php:37
