### ISSUE TITLE
Adding new user not working from CLI

### ISSUE THREAD

**Issue by Gineton2** [getgrav/grav-plugin-admin#286]
Trying out grav for the first time, so this may be a PEBKAC or installation issue. 

I am running the latest version of MAMP on El Capitan with PHP 5.6.10. 
I git cloned grav (1.0.0-rc.4) to a folder, set MAMP to that folder, and installed Grav successfully. I then tried installing the admin plugin using gpm, which appears to have worked (going to localhost:****/admin gives me a login page). 

My issue is getting the command to add a new user in the CLI to work.

First, the documentation lists the command `$ bin/grav newuser` to add a new user.
However, when attempted, we get this:

    [InvalidArgumentException]
      Command "newuser" is not defined.
      Did you mean this?
          new-user

Trying `$ bin/grav new-user` gives me:

    DEPRECATED COMMAND
      `bin/grav new-user` has been deprecated in favor of the new `bin/plugin admin new-user`

Trying `$ bin/plugin admin new-user` then gives me:

    No Console Commands for 'admin' where found in 'plugins://admin/cli'

A few possibilities are: the documentation (in the READMEs, learn.grav.org, etc.) is outdated, my installation is broken, or adding new user in the CLI is not yet implemented .

**Comment by rhukster** [comment]
Resolved in Gitter.im.  Basically new 'develop' branch has moved this command to login plugin.  That needs to be updated so it is available.
