### ISSUE TITLE
Unauthorized on update theme on theme page

### ISSUE THREAD

**Issue by 810** [getgrav/grav-plugin-admin#289]
You can't update the theme on the theme page. Error message: Unauthorized

**Comment by rhukster** [comment]
Try logging out and back in.

**Comment by 810** [comment]
I have already updated on the dashboard. But on the theme page you het this error

**Comment by rhukster** [comment]
ddi you log out and back in?????

**Comment by 810** [comment]
Nope. Same session.

**Comment by rhukster** [comment]
We added **nonces** in this release.  You might well need to log off and back on. So just do it already :)

**Comment by 810** [comment]
I updated it to lasted version by the dashboard page. So the issue is gone. 

but maybe on the next version there is the same issue.

**Comment by rhukster** [comment]
Should not repeat, adding nonces was a one time thing.
