### ISSUE TITLE
Deleting all custom redirects / routes does not work

### ISSUE THREAD

**Issue by lionep** [getgrav/grav-plugin-admin#290]
In 1.0.0.rc5, on admin module, on site configuration (admin/site), the removal of all rules does not have any effect after save and reload.

If I leave at least one existing rule, it saves fine.

**Comment by flaviocopes** [comment]
You mean removing all redirects, for example?

**Comment by lionep** [comment]
yes

**Comment by flaviocopes** [comment]
You're right. It's not just on rc5, also happened before (tested rc1).

It happens because when you remove all the options, the yaml file stored in user/config does not retain the original property, so Grav falls back to the default yaml. 

If you see, it adds the default properties.

**Comment by flaviocopes** [comment]
A possible solution could be instead of adding two real redirects as examples, provide a placeholder with an example

**Comment by flaviocopes** [comment]
Fixed by https://github.com/getgrav/grav-plugin-admin/commit/4f29263377c943bf5c3c21970c30b4a4ebf2ad75
