### ISSUE TITLE
Unauthorized During Page Delete

### ISSUE THREAD

**Issue by umbergerba** [getgrav/grav-plugin-admin#292]
When I click the "X" to delete a page from the page list the page simply refreshes and I get an "Unathorized" remark at the top of the page (see attachment).

"Delete" from the actual page works fine though.

![screen shot 2015-11-21 at 11 56 12 am](https://cloud.githubusercontent.com/assets/5008228/11319806/5388efc8-9049-11e5-8c5f-38bd9de6b1ff.png)

**Comment by rhukster** [comment]
Another **nonce missing** issue I think.

**Comment by flaviocopes** [comment]
Fixed in https://github.com/getgrav/grav-plugin-admin/commit/05bfe20c330e3f3a1edf6138dd79ec64488ae4b1
