### ISSUE TITLE
Fonts too big in Firefox

### ISSUE THREAD

**Issue by bobrocke** [getgrav/grav-plugin-admin#293]
The Admin interface is rendered too large in Firefox:

![2015-11-21 at 4 41 pm](https://cloud.githubusercontent.com/assets/2962426/11320664/e835c658-906e-11e5-96f3-728fef12d68d.jpg)

**Comment by rhukster** [comment]
![2015-11-21-23-kkmif](https://cloud.githubusercontent.com/assets/1084697/11322345/75f95f1a-90a4-11e5-8d96-df5e809557e4.png)

I think your zoomed in :)

Try clicking "CMD 0` to reset it...

**Comment by bobrocke** [comment]
I did reset the zoom. It looks OK on my regular display, but too big on my retina display. Possible?

**Comment by flaviocopes** [comment]
Could be a retina display thing. But I don't have a retina display to test it on at the moment!

**Comment by rhukster** [comment]
@bobrocke what version of Firefox is this? Only stuff I can find about Firefox and 'big' elements relates to Firefox 22,23 etc, which is mega old.

**Comment by bobrocke** [comment]
Checking other Firefox versions, it appears to just be the Firefox Developer v44. I hope it's just an alpha/beta problem and not a prediction of the future Firefox.

**Comment by rhukster** [comment]
I'm on latest Firefox developer also, but it could be Retina related.  All the stuff I find relates to windows: https://support.mozilla.org/en-US/questions/963773 or Unix: https://support.mozilla.org/en-US/questions/1061791

**Comment by bobrocke** [comment]
Yes. I don't see the problem on my cinema display, but do on the MacBook Pro's own display.

**Comment by bobrocke** [comment]
Strangely, everything looks as it should using Firefox stable 42.0.
