### ISSUE TITLE
Encoding Issue with Umlaute

### ISSUE THREAD

**Issue by SirNovi** [getgrav/grav-plugin-admin#295]
Umlaute (äüö) are not handled correctly in page titles.
I created a [short video](http://www.arbeitswut.com/phil/share/Screen-Recording-2015-11-23-15-46-52-7YNQ9KYgo3.mp4) to demonstrate.

A workaround that works is to use HTML character entity references. 
(i. e.`&Uuml;`  for Ü)

**Comment by flaviocopes** [comment]
It works perfectly fine for me. 
Can you check `default_charset` is set to UTF-8 under `yoursite.com/admin/info`

**Comment by SirNovi** [comment]
As you can [see for yourself](http://www.arbeitswut.com/phil/share/Screen-Shot-2015-11-23-16-18-15-PJWOsyD7Su.png) I now set the value to UTF-8 and it's still the same. I cleared the cache and logged out and in again as well.

**Comment by SirNovi** [comment]
Installed Grav on another Server and don't have this issue. But I couldn't find a difference between the two servers that could be the culprit – yet.

**Comment by flaviocopes** [comment]
I have UTF-8 in the second column too. Not sure if this is the key thing

**Comment by rhukster** [comment]
Well I can't replicate this either. It just works on my system.  I think that you must have some configuration setting or option that is causing this on your one server.  It's clearly not a Grav thing, it's a system configuration thing, so closing.
