### ISSUE TITLE
Exception Error when using Plugin toggle

### ISSUE THREAD

**Issue by coelmay** [getgrav/grav-plugin-admin#297]
Attempting to enable/disable a plugin (version 1.0.0-rc.5) via the toggle button on plugins page (not using enable/disable button on individual plugin page) results in:

…/­user/­plugins/­login/­login.php 206

## Call to a member function header() on a non-object

Open: /home/coel/fukr.co/grav-admin/user/plugins/login/login.php
````
    {
        /** @var User $user */
        $user = $this->grav['user'];
 
        /** @var Page $page */
        $page = $this->grav['page'];
 
        $header = $page->header();
        $rules = isset($header->access) ? (array) $header->access : [];
 ````

<img width="1280" alt="plugin-error" src="https://cloud.githubusercontent.com/assets/14990463/11358875/a4d753c0-926e-11e5-8f25-99f04e4a865a.png">

**Comment by rhukster** [comment]
I fixed this one today and it's ready in the develop branch.  Will get that out to you guys tomorrow hopefully.

**Comment by coelmay** [comment]
excellent!
