### ISSUE TITLE
error when translations are disabled

### ISSUE THREAD

**Issue by stickyhands** [getgrav/grav-plugin-admin#299]
as soon as I disable the translations I get an error:

Whoops \ Exception \ ErrorException (E_ERROR)
Call to a member function get() on a non-object 

is about the getTranslation function inside system/src/Grav/Common/Language/Language.php

everything is updated to the last version

**Comment by rhukster** [comment]
How did you disable translations?

**Comment by stickyhands** [comment]
first by the admin panel, then as it was broken I had to enable it back inside the system.yaml file

**Comment by rhukster** [comment]
What setting specifically?

**Comment by stickyhands** [comment]
languages:
  translations: false

**Comment by rhukster** [comment]
ok thanks, i'll look into this.

**Comment by rhukster** [comment]
wrong button!

**Comment by rhukster** [comment]
I 'think' this will fix it.  I dont' get the same error as you but did see translations disabled in admin when they should still show.  Closing for now. Please reopen if the issue persists after the next update.
