### ISSUE TITLE
Page Media with PHP build-in server not working

### ISSUE THREAD

**Issue by aptly-io** [getgrav/grav-plugin-admin#3]
I cloned grav, did bin/grav install, bin/gpm install admin and run locally with php -S localhost:8000

I tried to drop an image on the "page media" pane. There's a thumbnail appearing. But hovering over shows some widget filled with HTML source. I can see the text inside saying: the requested resource /admin/media/home.json/task: addmedia was not found on this server. Maybe I do something wrong or something is not correctly installed?

**Comment by flaviocopes** [comment]
Replicated on the PHP built-in server (php -S localhost:8000). Works fine in MAMP

**Comment by w00fz** [comment]
This seems to be an issue with the php built-in server. Any dot contained in the path script is interpreted as a file. In the case of admin, many ajax request documents as `.json`, to get back a JSON format.
For the media upload you see `/media/home.json/task:addmedia` and the php built-in server looks for a file named `home.json`.

Unfortunately this bug has been reported and doesn't look like they are willing to fix it.

Refs:
  * http://php.net/manual/en/features.commandline.webserver.php#115907
  * https://bugs.php.net/bug.php?id=61286]

**Comment by w00fz** [comment]
Note: This is not just Media, any URL call that has a dot in it and is not a file will behave the same, clearing cache from the Dashboard should give you an error too.

**Comment by rhukster** [comment]
It seems we really cannot make the admin compatible with PHP's built-in webserver. It's really a bit beyond it's capabilities.  We probably will need to remove it from the docs as a viable option.
