### ISSUE TITLE
SplFileInfo: stat failed for `.../admin/task:logout.md`

### ISSUE THREAD

**Issue by Sommerregen** [getgrav/grav-plugin-admin#30]
Everytime when I'm loggin out from the admin panel I get the following message:

![error](https://cloud.githubusercontent.com/assets/9073307/9141415/c48d0024-3d38-11e5-97b8-4fb452532911.png)

Maybe this is a Windows related issue (again something with the shlases and backslashes), but I don't know.

**Comment by rhukster** [comment]
Yah probably a windows issue with pathing.. i'll dig into it today if you can test for me :)

**Comment by flaviocopes** [comment]
@Sommerregen Can you try this for me? Before the line that throws the error, add this test:

```
if (!file_exists($file->getRealPath())) {
    echo 'uhm';
    var_dump($file->getPathName());
    exit();
}
```

Do you see the dump of the variable, or just the exception, same as before?

**Comment by flaviocopes** [comment]
(after this: https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Page.php#L114)

**Comment by Sommerregen** [comment]
Actually, I have found the error, see PR. Maybe it needs some refinements.

**Comment by flaviocopes** [comment]
It would be interesting to catch where that trailing 'task:' was added, I'll try to replicate.

**Comment by Sommerregen** [comment]
Ok:-)

**Comment by Sommerregen** [comment]
@flaviocopes See my comment here #36.
