### ISSUE TITLE
page update time for modular pages

### ISSUE THREAD

**Issue by simonhaenisch** [getgrav/grav-plugin-admin#301]
The date for the last update of a page that is modular is the update time of the page markdown file, but I think it should be the update time of the module that was last modified, because thats the real update time of that page. The sitemap plugin uses this date for the sitemap and thus it seems a homepage wasn't updated even though the modules changed.

**Comment by flaviocopes** [comment]
Sounds like a good idea. Let's wait @rhukster opinion. It's not a Grav Admin bug btw, should be put under https://github.com/getgrav/grav/issues

**Comment by rhukster** [comment]
Yes, this is not super trivial, but probably doable.  It really should be a new feature request in the Grav issues tracker that @flaviocopes linked to.
