### ISSUE TITLE
Issue when trying to change 'Folder Numeric Prefix' and 'Folder Name' at the same time

### ISSUE THREAD

**Issue by SirNovi** [getgrav/grav-plugin-admin#304]
I'd say it's a really minor thing but I guess it should be looked into and possibly fixed ad some point. 

Right now it does not seem to be possible to change the 'Folder Numeric Prefix' setting – either from enabled to disabled or the other way 'round – and the folder name at the same time. 

Changes to the folder name are always disregarded.

**Comment by flaviocopes** [comment]
Sorry referenced the wrong issue

**Comment by rhukster** [comment]
LOL, i just spent 4 hours spinning in circles trying to get this to work.  It's actually quite a complex problem that has to take into account so many situations.  I'm going to sleep on it and see if i can come up with a simpler (and workable solution).

**Comment by SirNovi** [comment]
Oh my.. If I just had known. I would have kept it a secret, at least until we're out of beta. No one would have noticed.

**Comment by mahagr** [comment]
Should have been fixed at least in Grav 1.10 if not before.
