### ISSUE TITLE
Title variable in admin

### ISSUE THREAD

**Issue by GeGeek** [getgrav/grav-plugin-admin#310]
Hello,

the meta title doesn't use variables, so when you don't use the default english language, the meta title should be updated too.

Not a big bug, but it could be fixed :)
![capture](https://cloud.githubusercontent.com/assets/5159674/11471102/2024cf3c-9763-11e5-8273-89c7c148580b.PNG)

**Comment by GeGeek** [comment]
Apparently, it's the case only for some parts of the administration.

When you edit a page (/admin/pages/home), the title is correctly translated, but not when you are editing settings( /admin/site ) for example :)

**Comment by flaviocopes** [comment]
Good catch!
