### ISSUE TITLE
Buggy username CSS hover class

### ISSUE THREAD

**Issue by artifex404** [getgrav/grav-plugin-admin#312]
![out](https://cloud.githubusercontent.com/assets/3011068/11474541/53ce8288-9781-11e5-99bf-b63d48a22f51.gif)

MacOS 10.11.1, Chrome Version 46.0.2490.86 (64-bit)

**Comment by flaviocopes** [comment]
Same version, same OS.. not sure what that could be!

![screen shot 2015-11-30 at 15 47 46](https://cloud.githubusercontent.com/assets/11783388/11474665/beb02a32-9779-11e5-8c5a-3791d4714d99.png)

**Comment by artifex404** [comment]
Oh, I guess that I have Ghostery enabled which blocks Gravatar icons. Anyway, I think it would be logical to highlight the whole block, not only the icon?

**Comment by flaviocopes** [comment]
I installed Ghostery and I recreated it.

The circular animation is a nice effect, once you whiltelist gravatar
