### ISSUE TITLE
Unable to set up two users with admin plugin

### ISSUE THREAD

**Issue by daz3dpr0z** [getgrav/grav-plugin-admin#313]
I have been having a problem getting two users set up on the admin plugin. When I first set up an admin account with full access i can log in fine and it seems stable but if i then add a second account and try log in with that new account i get an access denied plus i loose ability to log back in with admin account. even deleting the new user account wont allow me to log back in with the admin account. have tried several installs of grav and plugin thinking it may have been a version and update problem . It would seem not to be the case. has anyone encountered this before or any insights as to what may be happening

**Comment by flaviocopes** [comment]
I cannot recreate this problem. Are you on the latest version of Grav, Admin Plugin and Login Plugin?
Which browser? In normal or "incognito" mode?

**Comment by flaviocopes** [comment]
I tried the same on the current develop branches, and also on a Skeleton with the latest plugins versions, still unable to replicate

**Comment by daz3dpr0z** [comment]
OS: Slackware 14.0
Firefox version 33.0.2
On the latest grav and admin plugin from http://getgrav.org/downloads
I also noticed the same behaviour on the Sea Monkey Browser and Konqueror browser
I am unsure what you meen about the mode normal/incognito.
Am wondering if it is a security issue/setting
Thanks for looking into it for me.

**Comment by daz3dpr0z** [comment]
i have set up a new login account with a user who just has site access. my login plugin now says 

You have successfully logged in
access denied

This is the first time i tried to set up a user with only site access. This appears to be related to new users with just site access

**Comment by rhukster** [comment]
That is actually how ti currently works.  You are logged in, but you don't have access to the admin because you only have site access.

**Comment by daz3dpr0z** [comment]
thanks rhukster, i forced a logout using http://localhost:8001/admin/logout
I have two accounts one with admin access and one with admin and page access
both accounts not working now because i set up and tried to login using a user with just page access.

good to know. i will be leaving the just page access user alone for now 

appreciate your time on this one
