### ISSUE TITLE
When you uncheck an option and save, option gets rechecked.

### ISSUE THREAD

**Issue by andregoldstein** [getgrav/grav-plugin-admin#32]
When a previously checked box is unchecked and the page saved, the checkbox appears to get rechecked.

![Uploading Screen Shot 2015-08-07 at 18.26.39.png…]()

**Comment by rhukster** [comment]
Would be great if you could get that screenshot working because I don't know exactly what you mean :)

**Comment by andregoldstein** [comment]
Sorry, here it is again. 

Steps to get here:

- Clicked on options then checked meta description and filled one in. Saved page, this works.
- Unchecked box and resaved page, but the box remains checked.

<img width="1004" alt="screen shot 2015-08-07 at 18 26 39" src="https://cloud.githubusercontent.com/assets/7061578/9141666/556438e4-3d32-11e5-8874-45e6bba2ba26.png">

**Comment by rhukster** [comment]
Flavio can you double check this one with your latest toggleable updates?

**Comment by flaviocopes** [comment]
Yes, confirmed this is solved in the latest `develop` branch
