### ISSUE TITLE
Cannot change Date, Published Date, or Unpublished Date

### ISSUE THREAD

**Issue by zebradots** [getgrav/grav-plugin-admin#322]
When editing an existing page, the date fields do not allow a proper date format to be set. Regardless of whether a date is manually entered or the datepicker is used, the value is rewritten. Datepicker resets to "DD, YYYY", while manually entered dates seem to be erased entirely. As a result it is impossible to save the changes, since no month is specified.

**Steps to reproduce:**
Admin > Pages > [click page to edit] > Options > Enter or select a date > Save

**Expected result:**
New post date or new published date is saved and applied

**Actual result:**
Validation failed: Invalid input in "Date"

![date](https://cloud.githubusercontent.com/assets/16127777/11550795/d06937b2-9938-11e5-8aa9-18e210588e42.png)

**Comment by flaviocopes** [comment]
It works fine for me. What are your date settings in the System configuration?

**Comment by zebradots** [comment]
The TwentyFifteen 1.0.3 Site Skeleton appears to have set the "Page date format" to "d, Y (e.g. 05, 2015)". Seems like a very strange setting! Will try changing it, and also see if this is the default when starting with this particular skeleton.

**Comment by zebradots** [comment]
On a fresh install of this skeleton, once the admin plugin is added, "d, Y" appears to be the default setting that is selected.

**Comment by zebradots** [comment]
The problem appears to be with this skeleton and/or theme, rather than the admin plugin.
