### ISSUE TITLE
UX: links on plugins info: open in new tab

### ISSUE THREAD

**Issue by 810** [getgrav/grav-plugin-admin#33]
All links on the info from the plugins, should be opened in new tab

**Comment by w00fz** [comment]
Why? It is bad practice to force opening in new tabs from the site, you can use the browser functionalities to open links in new tabs or windows. ie, Right click on links, shift + click on link etc.

**Comment by 810** [comment]
for example, 
Now I'm testing plugins, features and now I see a bug, so I click on back tracker link, But its opens in the same window. I submit a new issue. But then I need to go back 4/5 pages, to go back to the admin.

**Comment by w00fz** [comment]
Yeah but my point is that this is pretty much how it works nowadays. You can CMD + Click the link to get it into a new tab so you dont loose the admin page.
It's just not the best practice to force that on the user, I might be actually wanting it to leave the admin.

**Comment by 810** [comment]
I know the shortcuts but its more user friendly, but its up to your guys to change it or not.

**Comment by rhukster** [comment]
I'll make the call.  I personally really hate being forced to open pages in new tabs. I much prefer having the choice of what I want to do.  However, I understand that many more novice users don't even know about the key modifiers and context menu options, so for them we should automatically open in a new tab.  So we'll do it.

**Comment by paulhibbitts** [comment]
I agree with you Andy. Many less technical users do not use modifier keys and looking at the pogo-stick behaviour of viewing the linked page and going back to the Admin UI I'd also say opening in a new tab (window) would be a preferable way to proceed.
