### ISSUE TITLE
IE11 - Unable to Save or Copy/Cut from editor window in 

### ISSUE THREAD

**Issue by wesleyahall** [getgrav/grav-plugin-admin#333]
Upon attempting a page save via admin plugin in IE, we get a "Unauthorized" dialog. 

Also, the option to cut/copy text is greyed out. Not sure if related.

**Comment by rhukster** [comment]
IE is not officially supported yet.  Something we will get sorted in time.  For now please use Chrome, Firefox or Safari (heck even Opera).
