### ISSUE TITLE
Opting out of Gravatar

### ISSUE THREAD

**Issue by sunnyolives** [getgrav/grav-plugin-admin#339]
Hi there! 
I just installed the admin plugin, suspiciously giving up my email address (because I am just trying things out on localhost), just to be greeted with a Gravatar. As such, I would suggest that sending email address to Gravatar without warning be disabled, as it is a leakage of personal information without consent and a violation of privacy. Instead there could be an opt-out and a possibility of uploading a local avatar. At the bare minimum a _warning about Gravatar use should be given._

I don't really see a lot of other people caring about this issue, but I think it is important, still.

**Comment by rhukster** [comment]
Yup, you are definitely the first person to mention this as a concern.  My advice is always use a test/bogus email address if your concerned about giving it out. 

We'll consider having an uploadable avatar in a future version however.

**Comment by atomGit** [comment]
> I would suggest that sending email address to Gravatar without warning be disabled, as it is a leakage of personal information without consent and a violation of privacy.

6 years later, testing grav myself and i wasn't aware that the email address is sent anywhere - that the developers chose to ignore user privacy in this regard is very worrying - i can only wonder where else such privacy violations may arise
