### ISSUE TITLE
Forced template not visible in the admin

### ISSUE THREAD

**Issue by gagarine** [getgrav/grav-plugin-admin#342]
In a page of a modular page I forced the template like that:
template: form/subscribe

But then in the administration is not visible
![screen shot 2015-12-12 at 17 18 43](https://cloud.githubusercontent.com/assets/164074/11762838/76209b60-a0f4-11e5-96d9-fb849ea43712.png)

So when you save you end up with a broken website and the message "Validation failed: Invalid input in "Display Template""

**Comment by flaviocopes** [comment]
Currently subfolders of the `templates/` folder are not scanned, you need to put `subscribe.html.twig` under `templates/subscribe.html.twig`

**Comment by gagarine** [comment]
Ok but it shouldn't break the website if you do it manually and use after the admin to do an other change in the page.
