### ISSUE TITLE
Theme not showing up since update

### ISSUE THREAD

**Issue by jamie-lord** [getgrav/grav-plugin-admin#344]
I have a copy of the antimatter theme that I've edited and works perfectly well when enabled manually. However it does not appear in the admin plugin since updating to Grav to 1.0.0, before that release the theme showed up fine.

I'm not sure whether this is an issue with my theme or this plugin, but it did work before updating to the latest version and the theme has not changed at all in that time.

Thanks for the great work!

**Comment by flaviocopes** [comment]
Hi, what is the theme folder name?

**Comment by jamie-lord** [comment]
"lordv4"

**Comment by flaviocopes** [comment]
Ok, the name is fine. Maybe it's something in the blueprint.. not sure. Send me the zipped theme folder (via Gitter PM) so I can give it a try.

**Comment by rhukster** [comment]
Needs to have.a yaml file to show up in the admin

**Comment by jamie-lord** [comment]
Fixed. The theme didn't have a .yaml file with the same name as the theme.
