### ISSUE TITLE
Invalid Security Token when updating 

### ISSUE THREAD

**Issue by dericcain** [getgrav/grav-plugin-admin#348]
Here is what I am running:
PHP 5.4.41
Grav 1.0.0-rc.5

I am trying to update to 1.0.4 and I'm getting an error: Invalid Security Token

**Comment by flaviocopes** [comment]
Hi, try updating from the plugin screen (admin/plugins/admin/) or via the command line `bin/gpm update`. See http://getgrav.org/blog/grav-1.0.0-rc6-released

**Comment by dericcain** [comment]
That fixed it! Thanks!
