### ISSUE TITLE
Admin redirect for user creation skips problem validation

### ISSUE THREAD

**Issue by hugoaf** [getgrav/grav-plugin-admin#352]
Hi, normally when I install Grav if the server requirements are not meet, the issue page comes and points that out:
![error](https://cloud.githubusercontent.com/assets/8611472/11910558/25d2778c-a5ae-11e5-9331-6c8c1c85f1ab.png)

Now (I believe after web user creator) if I install Grav+Admin in a new server with issues, the problem is not detected and a redirect to  `/my-site.tld/admin` occurs, if no errors, fine, admin is displayed, but if there is a server issue like above it is not shown but the 404.

![404](https://cloud.githubusercontent.com/assets/8611472/11910582/e0e2f970-a5ae-11e5-8494-fd975e7685a4.png)

I believe, for better ux the issue should be checked before redirecting to `/admin`

**Comment by rhukster** [comment]
Are you sure this is the case?  I will double check, but problems plugin should override all. Did you test this?

**Comment by hugoaf** [comment]
yes, just tested in my windows local server, easy to reproduce:

WITH ADMIN
1. disable Apache mod_rewrite
2. Unzip a new Grav+Admin, redirects to /admin showing 404
3. Enable mod_rewrite and web user form is shown as expected

WITHOUT ADMIN
1. disable again mod_rewrite
2. Install Grav core (without Admin) it shows the problems issue Found page as above

**Comment by rhukster** [comment]
Ok thanks, i'll take a look.

**Comment by rhukster** [comment]
Fixed with this: https://github.com/getgrav/grav-plugin-problems/commit/cd30d5b42f3f2ef016d85ce22da7ba29bc1a72c3

Thanks

**Comment by hugoaf** [comment]
@test patch works as expected. Thanks.

**Comment by MomoGunz** [comment]
Hi,

The same issue happens with nginx 1.9.11 and PHP 7.0.3

**Comment by Stas404** [comment]
Hi guys. I got this error now.
Fresh "lubuntu" with installed apache2 and php 5.6. 
Created vhost "webdev.local" with contents of ".zip".
After screen with "Issues found", added mbstrings, php-curl, php-gd, mod_rewrite, etc. 
Now it redirect to "/admin" with 404.
What could I miss?
