### ISSUE TITLE
Clicking "Backup" button resets the counter but does not create a backup

### ISSUE THREAD

**Issue by zebradots** [getgrav/grav-plugin-admin#354]
This used to work a few releases ago, but it no longer works.
* No backup is created in the /backup folder
* The /logs/backup.log reflects the last time the backup button was clicked and a ZIP filename (which does not exist)
* When you click the "Download backup" notification, the page refreshes, but no download begins

**Comment by webfed** [comment]
Works fine here, on local machine and server. Grav 1.05 admin panel 1.0.2

**Comment by mikewink** [comment]
Works for me with Grav 1.0.5 and Grav Admin 1.0.2. System is running on a OS X 10.11 with Homebrew PHP7.0 (yaml, opcache, mcrypt, intl, imagick extensions installed). Debug mode is running, no errors.

**Comment by flaviocopes** [comment]
Check the /backup folder permissions. Maybe the webserver user (the one used by Grav) cannot write to it? http://learn.getgrav.org/troubleshooting/permissions

**Comment by rhukster** [comment]
Yah this definitely does work, i'm not able to replicate.  Maybe also have a look at your XHR tab in chrome development tools and see what the response is you get back from the Ajax.

**Comment by zebradots** [comment]
As of the latest release, I now see a pretty red error message:

**An error occurred. ZipArchive::close(): Can't open file: Permission denied**

However, even `chmod 777 backup` does not correct the problem, and ownership/permissions appear to be in order.

Is there a filesize issue or some other case that could be the culprit here?

**Comment by flaviocopes** [comment]
What is the environment? What would be the filesize of the backup?

**Comment by zebradots** [comment]
1. Environment is up-to-date Debian Jessie x86_64 with Apache/2.4.10 + PHP 5.6.14-0+deb8u1
2. The uncompressed size of entire Grav folder is 35MB

This used to work fine, and would name the backup after the site title, so it's unclear what could have caused it to stop working. Is there anything else we can provide that would helpful here?

**Comment by w00fz** [comment]
The ownership needs to be correct for all files in your grav instance, as those are the ones getting zipped and if Zip fails to add a file because of permissions, it throws that error.

Can you try running the command via CLI `bin/grav backup` and see if that works?

This is how a successful backup looks like:

```bash
 ☯  bin/grav backup
Creating new Backup "/Users/w00fz/Sites/RT/grav/grav-site/backup/grav-20151224140416.zip"

Archiving 3806 files [============================] 3 secs 6.2 MiB
Saving and compressing archive...
```

**Comment by zebradots** [comment]
Thank you for the input. We were finally able to locate the problem.

A file that was not owned by the user was buried deep in the site's directory structure, which was easily located with `find . ! -user example` (though this is just one potential cause of a permission error).

Maybe in the future the specific file that threw the error could be listed, as this would immediately help the user resolve the problem.

**Comment by stewag** [comment]
I have the same problem: "An error occurred. ZipArchive::close(): Can't open file: Permission denied"
I copied a new grav-admin per FTP to the webspace and replaced the contents of user/ from my local files.

> Can you try running the command via CLI bin/grav backup
No. I only have FTP access.

But my hosting service has a tool to reset the passwords (recursively) for folders. But I can choose between the FTP user and the PHP user. Which one should I choose?

**Comment by flaviocopes** [comment]
You already gave a read of https://learn.getgrav.org/troubleshooting/permissions ?

**Comment by stewag** [comment]
Yes I have. I seem to have case 3 - different accounts. I'll start a topic on the forum.
