### ISSUE TITLE
Add ability to edit "collection style" pages in admin

### ISSUE THREAD

**Issue by larsenwork** [getgrav/grav-plugin-admin#357]
E.g. trying to edit the "features" module in the `grav-skeleton-twenty-site` just displays blank fields. Is this a bug, something in the pipeline or am I missing something obvious? :smile: 

![screen shot 2015-12-20 at 19 41 02](https://cloud.githubusercontent.com/assets/3859425/11919393/d0f3199c-a751-11e5-9361-543e4ae0693e.png)
![screen shot 2015-12-20 at 19 40 33](https://cloud.githubusercontent.com/assets/3859425/11919394/d118b490-a751-11e5-9a82-b97a5c6b99e6.png)

**Comment by rhukster** [comment]
The theme needs to provide appropriate bluerprints for that modular type.  it's an issue for the Twenty theme, not for admin itself.

**Comment by larsenwork** [comment]
Cheers, any examples of blueprints that has that?

**Comment by flaviocopes** [comment]
https://github.com/getgrav/grav-theme-antimatter/tree/develop/blueprints/modular
