### ISSUE TITLE
Force user session expiration after logout

### ISSUE THREAD

**Issue by Sommerregen** [getgrav/grav-plugin-admin#36]
When logging out, the session for the current user have to be closed and any credentials deleted. Currently this is not the case.

**Comment by rhukster** [comment]
Umm.. should be the case, the session is invalidated and restarted.  

https://github.com/getgrav/grav-plugin-login/blob/develop/classes/controller.php#L114-L120

**Comment by rhukster** [comment]
I just tested this and the session is reset on logout.  A new session is started, but it's a new session.

**Comment by Sommerregen** [comment]
Good catch! But... sorry to reopen it :yum:

I found the issue. This is issue is closely connected with issue #30. It is due to different setting of `config.system.param_sep`. In my case it was `config.system.param_sep: '+'`, which (as you know) is necessary for Windows... Actually I just have to replace all `task:` to `task{{ config.system.param_sep }}` in the Twig files.

See my PR #35, which also adds a logout page, since even though you are destroying and re-creating a new session in the above lines, the logout message will not be printed to the user after the redirect...
