### ISSUE TITLE
404 Page not Found error when switching to alternate language for page

### ISSUE THREAD

**Issue by bobbywatson100** [getgrav/grav-plugin-admin#361]
Hello,
I just upgraded to Grav 1.0.5 (with admin panel 1.0.3). I am currently developing a webcomic website using Grav, and the site will be available in both English and French.

The issue is: I have a page in both English and French. By default, it comes up in French when I try to view it in the Admin panel.  If I try to switch to English, I get a 404 page not found error, even though the message says 'Successfully switched language'.

I have tried clearing the website's cache, clearing my browser's cache, no change.

I don't know if you need this information, but here goes:I have tried with both Firefox v. 43.0 and Chrome v.47.0.2526.106, running on an Apache 2.4.16 server, with PHP v. 5.5.29, on a Mac OS X Yosemite computer.

**Comment by flaviocopes** [comment]
Hi, can you check it's not one of the common 404 causes? http://learn.getgrav.org/troubleshooting/page-not-found

**Comment by bobbywatson100** [comment]
I went through the list of potential issues (.htaccess, AllowOverride, RewriteBase, etc.) I did find an issue with RewriteBase, but that did not fix the problem. Everything else on the site seems to work perfectly fine: I can go from page to page, switch the language in the URL...

One thing I've noticed: If I go to a French article through the admin panel, I get a URL like this:

.../grav/admin/pages/a-propos

If I try to switch to the English article using the menu next to the 'Normal / Expert' toggle, this is the URL that my browser is sent to:

http://localhost/grav/fr/admin/admin/pages

I'm not a web development expert, but that looks wrong...

**Comment by flaviocopes** [comment]
No, this is correct, as we must tell Grav which page language it needs to edit, and we do it that way.

**Comment by adelnoureddine** [comment]
Hi, I am having exactly the same problem as bobbywatson100 : http://s12.postimg.org/k0lulgti5/error2.png

**Comment by rhukster** [comment]
Confirmed this is a problem that has crept into the admin at some point.

**Comment by flaviocopes** [comment]
Fixed in develop, will issue an update today to the Admin plugin with this fix

**Comment by shula** [comment]
hmmm, I had exactly the same thing, fresh (and first ever) install, and it's 2019.

steps:
I instalelled grav latest grav as of today: 

- grav-admin-v1.7.0-rc.3.zip
- installed it,
- created a page,
- then went in to the page, and set it to "he"
- then went in to the site, and set it to "he"

now i go to the admin:  http://localhost/grav/admin
- when just HOVER over the side menu, "pages", the preview bar shows: "http://localhost/grav/admin/pages"
- but when I click, it redirects itself to http://localhost/grav/en/admin/pages
- which gives a nice 404 error.
