### ISSUE TITLE
Editing content does not use the typing enhancement of the device

### ISSUE THREAD

**Issue by symac** [getgrav/grav-plugin-admin#363]
Yesterday I tried to add an article to a Grav website using an iPad and good thing is that it works fine, less good thing is that the autocorrect does not work. I think it is because the content is not in the textarea but rather in the div.CodeMirror. I don't know if there is any way to add the autocorrect to this type of tag but that would be a great enhancement (and from what I have seen, not using a textarea prevents spellcheck control in my desktop browser too).

**Comment by rhukster** [comment]
Correct, this is because it's no longer a text area.  This is just how CodeMirror (and other editors) work. 

If you want to discuss it further, the place would be on the CodeMirror repo: https://github.com/codemirror/codemirror
