### ISSUE TITLE
Send email via a contact form

### ISSUE THREAD

**Issue by sabrilime** [getgrav/grav-plugin-admin#366]
I'm using grav and I have a page contact.form.twig that contains a contact form:

<form action="" method="post" name="contact">
<input type="text" id="input-2" required>
<label>Name</label>
<input type="text" type="email" id="input-2" required>
<label>E-mail</label>
</form>
<button form="contact-form" type="submit">Send</button>

I wanna when I click send the content of the form is sending by email.

I create a file user/config/plugins/email.yaml that contains the configuration to my mailtrap account

	enabled: true
	from: 'my_email'
	from_name: 'my_name'
	to:
	to_name:
	mailer:
	  engine: mail
	  smtp:
	    server: localhost
	    port: 25
	    encryption: none
	    user: ''
	    password: ''
	  sendmail:
	    bin: '/usr/sbin/sendmail'
	content_type: text/html

and the contact.md file contains:
	form:
	    name: Contact Form
	    fields:
 	       - name: name
 	         label: Name
 	         placeholder: Enter your name
 	         autofocus: on
 	         autocomplete: on
	          type: text
	          validate:
	            required: true

	        - name: email
	          label: Email
	          placeholder: Enter your email address
	          type: email
	          validate:
	            required: true

	    buttons:
	        - type: submit
	          value: Submit
	        - type: reset
	          value: Reset

	    process:
 	       - email:
 	           subject: "[Site Contact Form] {{ form.value.name|e }}"
 	           body: "{% include 'forms/data.html.twig' %}"
 	       - save:
 	           fileprefix: contact-
 	           dateformat: Ymd-His-u
 	           extension: txt
	            body: "{% include 'forms/data.txt.twig' %}"
	        - message: Thank you for getting in touch!
	        - display: thankyou

But I don't know the next step that makes me connect my form to the configuration and send the form content by email.

Thank you in advance

**Comment by flaviocopes** [comment]
Please post this on the forum or in Gitter. Github Issues are for problems with the codebase, not with its usage. Also, this is the Admin repository.

As for your problem, `user/config/plugins/email.yaml` is not currently configurated for Mailtrap. For example mine is using Mailtrap too and I have

```yaml
enabled: true
from: xxx@gmail.com
to: xxx@gmail.com
mailer:
  engine: smtp
  smtp:
    server: mailtrap.io
    port: 2525
    encryption: none
    user: xxxxxxx
    password: xxxxxxxxxxxx
content_type: text/html
```

**Comment by miqj69** [comment]
enabled: true
from: xxx@mail.com
to: xxx@mail.com
mailer:
	engine: smtp
	smtp:
		server: smtp.gmail.com
		port: 465
		encryption: ssl
		user: xxx@gmail.com
		password: xxxxxxxxx
	sendmail:
		bin: /usr/sbin/sendmail
content_type: text/html
