### ISSUE TITLE
Unwanted tab: - 'on' when saving plugin settings with tabs

### ISSUE THREAD

**Issue by Birssan** [getgrav/grav-plugin-admin#368]
Hi,
There is a small bug for plugins with tabs in their settings.
When you edit your settings for the plugin and save them, at the end of your config file (in `/user/config/plugins/superplugin.yaml`), there is a new line with 
```yaml
tab:
  - 'on'
```

And every time you save your settings for the plugin, a new line is added, so that can be really be ugly after 50 savings or so...

**Comment by flaviocopes** [comment]
I'm not able to replicate. 
Can you replicate this on a clean Grav installation?

**Comment by Birssan** [comment]
Well I have the last version of Grav/Plugins.

I've tested it on my plugin that I'm changing, I though it was coming from me so I've tested it on the login plugin which also uses tabs in plugin settings. And after saving in `user/config/plugins/login.yaml` I have this new line...

**Comment by flaviocopes** [comment]
Recreated on the Login plugin. I think it's the use of the tabs field in the blueprint. Will find out why.

**Comment by flaviocopes** [comment]
The above commit fixes the issue. Tabs were considered as form fields. Didn't show up before as it was "masked" by a JS-related issue recently fixed.

**Comment by flaviocopes** [comment]
The Login plugin is probably the first one that uses tabs in its blueprint, and your plugin is the second ;)

**Comment by Birssan** [comment]
Well thanks for fixing it so fast :)
Two features I need to use for my plugin that were bugged, each bug fixed the same day, so efficient :p
