### ISSUE TITLE
Admin plugin with local installation

### ISSUE THREAD

**Issue by iusvar** [getgrav/grav-plugin-admin#37]
Just as from the forum: I am following reports of problems but does not seem to have been reported this problem: the three buttons, **Clear Cache**, **Update** and **Backup** in the local installation reporting the message **Not Found** as savescreen 
![screensaver 2015-08-07 09 53 09](https://cloud.githubusercontent.com/assets/11983610/9145476/ff70bdb8-3d54-11e5-95e8-7fb70027fe72.png)
OK in the online.
This happens with Grav 0.9.35 and 0.2.0 Admin Plugin: installations with no errors.
FYI I work on a computer with Ubuntu 14.04.3 LTS Ubuntu and PHP 5.5.9-1ubuntu4.11 Development Server, both with the latest Chrome and Firefox 39.0.3.
In the console of Chrome the message is **Failed to load resource: the server responded with a status of 404 (Not Found)**

**Comment by rhukster** [comment]
In chrome, if you inspect in the network tab, and check the XHR content, what does the request look like? This is mine where it works fine:

![dashboard grav admin 2015-08-07 14-48-12](https://cloud.githubusercontent.com/assets/1084697/9145620/57e1f6e8-3d13-11e5-973c-a05901958645.png)

**Comment by iusvar** [comment]
![savescreen 2015-08-07 23 13 35](https://cloud.githubusercontent.com/assets/11983610/9146099/30e03036-3d5a-11e5-9302-a4384c1644a1.png)

**Comment by w00fz** [comment]
Are you using `php -S` for server? That is known to not work due to an issue of PHP itself.

**Comment by iusvar** [comment]
Yes, I use this command to launch the web server: **php -S 127.0.0.1:8080 -t** etc.

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-admin/issues/3

This is a known issue with the built in server.  There's not much we can do about it short of losing the whole parameter support in Grav (not going to happen).  We will remove the official support for the built-in server on the learn site.

**Comment by rhukster** [comment]
I've added a note here: http://learn.getgrav.org/basics/installation#phps-built-in-web-server

Basically anything that uses params will not work because the php built in webserver doesn't understand how to handle these more complex URLs.  There is really no solution to this short of PHP's web server being improved. 

Solution is to use a real webserver :)

**Comment by w00fz** [comment]
More infos with link to the bug itself https://github.com/getgrav/grav-plugin-admin/issues/3#issuecomment-128079164
