### ISSUE TITLE
pagemediaselect does not save selection

### ISSUE THREAD

**Issue by scottzirkel** [getgrav/grav-plugin-admin#374]
When using the pagemediaselect input type, it loads the media into the select, but it does not save it to the md file. If the field is added to the file manually, saving the page in the admin will wipe it out.

This is the image as defined in the blueprint. I tried it again in a fresh install, but I get same result. All other fields are saving fine.

````
image:
  type: pagemediaselect
  label: Choose Image
````

**Comment by flaviocopes** [comment]
A PR sent yesterday and a commit by me should have fixed this issue: https://github.com/getgrav/grav-plugin-admin/commits/develop can you check with the latest develop branch for the Admin plugin?

**Comment by scottzirkel** [comment]
Just tried the develop branch on two different installs/blueprints. Still isn't working. Same result, it never writes the value of the selection to the md file.

**Comment by flaviocopes** [comment]
Can you post me your user/ folder via Gitter PM so I can try it?

**Comment by aymerix** [comment]
I've downloaded the develop branch and the field is saving well :+1: 
The PR and your commit fixes the issue for me :)

**Comment by scottzirkel** [comment]
Ok, had a few issues with my MacBook I had to sort out, and when I went back it was working with the dev branch. So it looks like everything is working now.

Thanks @flaviocopes!
