### ISSUE TITLE
Consistency modular page content > normal | expert

### ISSUE THREAD

**Issue by B-iggy** [getgrav/grav-plugin-admin#375]
Hey,

yesterday I started using Grav and still playing around for now. Looks really promising!
What I found confusing was following case:
(in normal mode) You add a page > Write some stuff in Content > go to Advanced and set Page File to Modular > go back to Content and the field for writing stuff is missing!
If you switch now to expert mode it's there again.

So why do you hide the markdown field for writing stuff in normal mode but show on expert mode? Doesn't make sense to me.
Especially for end users who are scared of the meaning "expert" haven't the chance to write stuff when set the Page File to Modular for this certain page.

![screenshot from 2015-12-31 10 43 42](https://cloud.githubusercontent.com/assets/7815434/12063244/97f700e2-afab-11e5-8f17-4ae07dcbb2f2.png)
![screenshot from 2015-12-31 10 44 11](https://cloud.githubusercontent.com/assets/7815434/12063245/97fa6318-afab-11e5-81ed-c2e6c0bfe74c.png)

**Comment by flaviocopes** [comment]
You changed the page file to "Modular", this causes the page form to change, as it's a different page file, and the "Modular" page file does not provide a content field, so the editor was not shown any more. All fine up to now.

Expert mode on the other hand is more like writing directly to the markdown file, so you have the frontmatter and the content, regardless of the page type, like when you edit files from the filesystem directly.

In the case of a Modular page it might make little sense, but Expert mode is the same across any page file, while Normal mode changes depending on the page file.

**Comment by B-iggy** [comment]
Thanks for your answer.
Ok, I understand that.

But what if the user wants the following page:

Page with Content: 
"h1 > This gonna be awesome"
---
Modular 1 (e.g. slider)
---
Modular 2 (text)
---
Modular 3 (footer)

The only thing he can do is to switch to expert mode und

**Comment by flaviocopes** [comment]
That's an option, another option is to add a text module child and stack it on top.

**Comment by B-iggy** [comment]
Ok, my only little concern was for end user who are scared of "expert" mode (they are almost no experts in anything). On the one hand it's good for me and he is calling for my help but on the other hand I would give him the freedom to do it by himself.
So I have to explain it to him then. Just my observation.
Thanks.
