### ISSUE TITLE
Link to site index in sidebar

### ISSUE THREAD

**Issue by le717** [getgrav/grav-plugin-admin#376]
Can we get a link in the sidebar or somewhere to take us back to the main site? I am considering switching to Grav from WordPress.com for my personal blog and the absence of such a link in the admin panel is a big accessibility/usability flaw. :)

**Comment by rhukster** [comment]
![dashboard grav 2016-01-01 22-51-18](https://cloud.githubusercontent.com/assets/1084697/12073364/31bb4970-b0da-11e5-8627-b93fcf0300aa.png)

Clicking this arrow takes you to the main site.

**Comment by le717** [comment]
Wow. That's not at all obvious. I honestly thought that was part of the Grav Admin link indicating the path to getting back to the admin panel home, not a link to the site index. :\ Thanks for the answer.
