### ISSUE TITLE
Facilitate editing of all YAML settings in the site.yaml config file

### ISSUE THREAD

**Issue by mikegcox** [getgrav/grav-plugin-admin#38]
Currently editing the site.yaml file is limited to default data.  It would be good to be able to edit all the YAML in that file as it is a good place to store site settings that a website content administrator would need to make changes to periodically.

**Comment by rhukster** [comment]
Thanks mike...

**Comment by rhukster** [comment]
Things that need to happen here:

1) `user/blueprints/` merged with `system/blueprints`.  Currently `user/blueprints` are picked up but completley override he ones from system.  So you must copy **all** blueprints from system to user or it breaks things.

2) Supporting `@extends` would be good, currently this sends things into an infinite loop.

I'm going to ask matias about these things which are really needed before we can implement this functionality.

**Comment by rhukster** [comment]
Also we might be able to provide the 'extra' fields in a textarea rather than in hidden json encoded fields as they are now.

**Comment by mahagr** [comment]
I've been thinking something like this for both blueprints and twig; to be able to say ```extends parent```. We do need similar functionality also in Gantry 5 as I really hate copying the whole files because of the base file cannot be seen.

**Comment by mahagr** [comment]
Fix for 1) is in:

https://github.com/getgrav/grav/commit/4a59b8ae4359040434f135fafdee4f839853bb67

**Comment by mahagr** [comment]
Fix for 2) is in: https://github.com/getgrav/grav/commit/c4cd355f5b3802b8c1348bb205f5e7bc61b1b311

Just note that it allows only single level of inheritance -- I will need to think up a way to generalize the function.

**Comment by rhukster** [comment]
Very cool! Closing...
