### ISSUE TITLE
admin plugin will not create initial user

### ISSUE THREAD

**Issue by Yokai** [getgrav/grav-plugin-admin#381]
I have just upgraded to v1.0.6 of Grav and pulled down the learn2 skeleton. On install of admin (bin/gpm install admin) I am prompted to create a user - unfortunately all that happens is "oops something went wrong"  Creating the user with the CLI works, but unfortunately the admin plugin just returns with "Invalid Security token"

I am based on Rochen, and have the following settings:
![screenshot 2016-01-04 15 53 00](https://cloud.githubusercontent.com/assets/589355/12103981/dd610d0a-b2fb-11e5-9aa9-9014c3d45b36.png)

Please check other details here:
http://getgrav.org/forum#!/general:form-and-admin-plugin-faili

Thanks for all the help

**Comment by rhukster** [comment]
can you explain to me how you updated Grav and used the Learn2 skeleton?  Perhaps it's a setup/configuration thing?  Perhaps you could provide me with a ZIP of your current installation folder?

**Comment by rhukster** [comment]
Also please try the latest version with 1.0.8 which has new nonce code.  Closing for now due to lack of response, but feel free to reopen if the issue persists.
