### ISSUE TITLE
group permission reset after gpm update yesterday

### ISSUE THREAD

**Issue by JustBreakIt** [getgrav/grav-plugin-admin#386]
Tried updated the admin panel today from within grav, and got permission error(s) . After checking, it appears that the update on 01/07 was done  from gpm , reset dir owner back to root for all plugins updated/touched at that time.  To clear this error, I had to manually touch all folders/files updated 01/07 back to the correct webserver owner and then the admin panel upgrade to 1.06 from within grav using the 'check for updates' under plugins.

**Comment by rhukster** [comment]
If you are relying on group writable permissions between shell user and webserver user, then we have added some functionality in the Grav 1.0.5 (?) to make this simpler.  I will be updating the docs today to add information regarding how to set this up. 

It basically involves creating a `setup.php` in the root of your site and setting an appropriate `umask` for PHP in there.  Also there's a newish cache perms setting you can modify to ensure images are created with 664 perms also.

**Comment by JustBreakIt** [comment]
I'd rather use the minimum permissions possible . So I need to set umask correctly (002) so that new and updated files are created  0664 .  And will they inherit the webserver user?

**Comment by rhukster** [comment]
all it will do is ensure 775 and 664 for folders/files.  No ownership changes.  This means that your shell user and webserver user need to share the group.

**Comment by rhukster** [comment]
You probably will need to set these also:

1. in `user/config/system.yaml` set `image: cache_perms: ‘0775’`

2. in `user/config/systeml.yaml` set `twig: umask_fix: true`

**Comment by JustBreakIt** [comment]
Originally I used the 'permission fixing' shell script example during the initial setup.  Just to be clear, when I did the recent update, was there additional steps needs to avoid the permission error ?  I assume there would be no difference between updating via gpm vs web panel.  I'll set the system config as you suggested and look for your updated docs as well.

**Comment by rhukster** [comment]
Well, this kinda outlines the issues: http://learn.getgrav.org/troubleshooting/permissions

Most often on shared hosting (and even the preferred approach on dedicated or VPS hosting) is that the webserver and the user is the same.. This works great for Grav, as that means that files crated via GPM in the terminal are going to have the same permissions a the ones via the admin (webserver).

However, it is possible to use a shared Group, but it's not ideal.  Files created via the admin will be owned by the webserver, and ones created by the GPM in the terminal will be owned by the terminal user.  You **must** have a shared group and that be writable for all users or you will end up with files that one of the other user cannot delete.

**Comment by JustBreakIt** [comment]
Oh,I may have just found one problem..  I made a typo when setting umask during original setup.. Also understand why the update complained (used a combo of gpm and admin panel to do so.)
This is a VPS with compiled php-fpm using nginx , so I'm locking down as much as I can.  
Thank you ....

**Comment by rhukster** [comment]
Read up on our hosting overview for DigitalOcean VPS.  It explains how to setup a dedicated user "grav" and then use that user for terminal and Nginx.
