### ISSUE TITLE
Parent not loaded on admin form on save

### ISSUE THREAD

**Issue by Crealoz** [getgrav/grav-plugin-admin#387]
When loading a page to enhance content on the admin. The parent is set to -root- instead of its parent that was set the previous time. Therefore, the user is obliged to set again the parent every time he wants to change the content or any other thing.

**Comment by flaviocopes** [comment]
Fixed in the repo, will be added to the next release. 
Happened on pages which were not under the home route, and `home.hide_in_urls` in the System config was enabled.
