### ISSUE TITLE
Enhancement/Bug: Support `param_sep` option

### ISSUE THREAD

**Issue by Sommerregen** [getgrav/grav-plugin-admin#39]
This is a gentle reminder that the `config.system.param_sep` option is not yet properly supported with the current version of the admin plugin.

This issue adresses #30, #36 and the ongoing changes to my open PR #35 . Any ideas and enhancements are welcome!

P.S.: Please leave #35 open as this is the branch I push changes to.

**Comment by rhukster** [comment]
I think the PR automatically closes when merged. But as this is now merged, i'll close this.
