### ISSUE TITLE
Incorrect number of pages being displayed

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#390]
When working on my site I noticed that the # of pages indicated in the Admin Panel do not match actual pages (I am assuming total pages, not just total visible pages), here is an example:

![pages cpt 363](https://cloud.githubusercontent.com/assets/1812771/12277931/01dc6714-b933-11e5-98a4-ae0ba0691676.png)

Thanks very much,
Paul

**Comment by rhukster** [comment]
Let me know if those doesn't sort it.. It should do, not sure why it was broken out into multiple counts before.

**Comment by paulhibbitts** [comment]
Thanks Andy, once the release is available I will test it out.

**Comment by rhukster** [comment]
You can click on the commit up there and see the minor change that was made, then copy/paste that into your own. That way you can test 'before' the release to ensure it works as expected :)

**Comment by paulhibbitts** [comment]
Thanks for the tip. Didn't work with copy/paste so I downloaded the Develop version of the Admin Plugin and SUCCESS! Page count is now 20 - looks correct to me, thanks!

**Comment by flaviocopes** [comment]
With Git's Blame :) I was able to find the original reason why the code was the count of routable and modular pages: https://github.com/getgrav/grav-plugin-admin/commit/772074cd97a6c6f5a67c84cf54582699a06ae98f 

I got in this problem when using Data Manager. 

You can recreate it with standard Admin, without any other plugin: http://yoursite.com/admin/pages/a/b/c/d/e/f/g/h/i
Watch the pages count increasing +8, using `grav['pages']->all()`, as Admin tries to recreate the pages structure by adding "just-in-time" pages.

**Comment by flaviocopes** [comment]
The count was wrong however, on Paul site, that's a legit issue.

**Comment by rhukster** [comment]
Ok I have an idea.  We can get the count and store it early before the 'just-in-time' pages are added.
