### ISSUE TITLE
Edge/IE error on saving: Invalid Security Token

### ISSUE THREAD

**Issue by 810** [getgrav/grav-plugin-admin#391]
When you save a page, you get a error: 
Successfully saved
Invalid Security Token

But the page is saved.

Only on Edge and IE

**Comment by 810** [comment]
@flaviocopes fix does not work for me, i still get the error with this patch, or need i edit more patches

**Comment by flaviocopes** [comment]
Try clearing the browser cache  to reload the JavaScript

**Comment by 810** [comment]
Done. On both browsers. Also cleand grave cache. Mhh maybe i can try clean cloudflare





On Fri, Jan 15, 2016 at 8:55 AM -0800, "Flavio Copes" <notifications@github.com> wrote:





Try clearing the browser cache  to reload the JavaScript

---

**Comment by flaviocopes** [comment]
Compare the JS file you get, if it contains the fix or not

**Comment by 810** [comment]
Ok fixed now, looks like cache from siteground.
