### ISSUE TITLE
Github Wiki Sync

### ISSUE THREAD

**Issue by ryanleesipes** [getgrav/grav-plugin-admin#392]
It would be really interesting and useful if some kind of Github wiki sync feature was included, which would allow folks to put a pretty face (and interface) on their Github wiki by syncing the info from a repo's wiki over to the Grav install.

This would also allow for collaboration on the information contained within the docs without having to anticipate all the people who want to contribute and give them access to the Grav install, or have them detail the changes they want to make through other mediums.

**Comment by flaviocopes** [comment]
Github wikis aren't really a standard, and as such Grav shouldn't and cannot tie itself to a commercial entity's service.

On the other hand what you ask is already doable through the Github interface: take a look at the Learn site: learn.getgrav.org

Its user folder lives in the github repository https://github.com/getgrav/grav-learn, people can (and are encouraged to!) contribute to the site by forking or just editing the page through the github interface (which internally creates a temp fork) and they can propose edits via PRs.

When a PR is accepted the site is rebuilt automatically via Github webhooks.

**Comment by ryanleesipes** [comment]
@flaviocopes I was talking about for our own Grav install. Perhaps we should host the static files in our own repo?

**Comment by flaviocopes** [comment]
Yes, I mean - you can follow the same way. Even for private repositories, you can use the Github GUI to edit the pages and then push them automatically to the site when edited.

**Comment by ryanleesipes** [comment]
Is there any way to easily set this up to be tied to a repo through Grav?

**Comment by flaviocopes** [comment]
Check those blog posts:

https://getgrav.org/blog/developing-with-github-part-1

https://getgrav.org/blog/developing-with-github-part-2

**Comment by ryanleesipes** [comment]
This is exactly what I needed. Thank you.
