### ISSUE TITLE
Feature request: option to create a page without a .md file

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-plugin-admin#393]
Hello,

I spoke with mahagr about the possibility in Gantry to have a menu item that is not clickable (for dropdown) and he said that it works (I tested it) if this page has no .md file.

Is it possible to have for example a option to create in admin a page consisting only of the folder without a .md file?

Olli

**Comment by Tyrion2737** [comment]
Thank you very much for your work!

**Comment by Tyrion2737** [comment]
The folder can not be selected as the parent page for a new page 😀

**Comment by flaviocopes** [comment]
Try clearing the Grav cache. Does it come up?

**Comment by Tyrion2737** [comment]
🙈 Do you want the issue to stay opened?

**Comment by rhukster** [comment]
did you see @flaviocopes last questions? does clearing the cache fix it for you? If so we probably need to add some logic to clear the cache when creating only a folder because the current 'default' logic is looking for page timestamps.

**Comment by Tyrion2737** [comment]
Sorry! Yes it does so I wrote the emoji 😉

**Comment by rhukster** [comment]
We'll keep it open because it does require a fix still to clear the cache automatically when a folder is added.

**Comment by Tyrion2737** [comment]
Fixed 😀

**Comment by flaviocopes** [comment]
:+1:

**Comment by Tyrion2737** [comment]
One folder name should have a "ä" in it. Thoughts?

**Comment by flaviocopes** [comment]
As per our `slug` field rules, a folder name currently cannot contain characters other than a-z, A-Z or numbers.

**Comment by Tyrion2737** [comment]
Maybe an exception for a folder without a .md file?

**Comment by rhukster** [comment]
A slug is a standard, and should not have exceptions: https://en.wikipedia.org/wiki/Semantic_URL

**Comment by Tyrion2737** [comment]
Yes the slug should have "ae" in it as it is.
I meant the displayed name in the navigation.

**Comment by rhukster** [comment]
At that point you would need to create a page .md file and set a `menu: whatever` item in the frontmatter.

**Comment by Tyrion2737** [comment]
Okay. Or change "ae" to "ä" without admin, the scenario in Gantry is to have a non-clickable menu item like @mahagr wrote. My idea is to do it user friendly in admin.

**Comment by Tyrion2737** [comment]
I do not know how to ask. So it is impossible that an empty folder has for example "ä" in the navigation and "ae" in the URL?

**Comment by Tyrion2737** [comment]
Everything works with an empty folder except that in the navigation "Einsaetze" has to be "Einsätze".

![bildschirmfoto 2016-02-22 um 18 03 39](https://cloud.githubusercontent.com/assets/14146656/13225841/fe77022e-d98e-11e5-9b31-b17c005f8922.png)

**Comment by rhukster** [comment]
So i'm still a bit confused.  You want the folder to be called `Einsätze`, but then it needs to be set as a route of `einsaetze` so it's a valid slug.  So it should still be displayed as `Einsätze` in the menu however?

**Comment by Tyrion2737** [comment]
Sorry for the confusion!

* The folder has no .md file so in Gantry the menu item links to no page
* The menu item has to be "Einsätze"
* The slug has to be "einsaetze"

**Comment by rhukster** [comment]
No promises, but i'll take a look again.

**Comment by Tyrion2737** [comment]
Thank you 😀

**Comment by mahagr** [comment]
I think we need to have a way to return `$page->isPage() === false` even if md file is in there. It would be benefitical to have some page type like `folder.md` for this, not only for having placeholders in menu, but also to define default page type etc inside of the folder. For example you may have `authors` folder with only authors in it. In that case you may also want to specify in admin that all pages inside that folder defaults to `author.md` page type.

**Comment by tyrion273** [comment]
Sounds good 😉

**Comment by nsteinmetz** [comment]
Hi,

Let me know if I should open a new issue but I have 3 questions:
* Do we speak there about the item "Add folder" in the admin panel ? If yes, with 1.0.10, I still have the cache issue, normal ? I precise I created the folder from the admin panel and it didn't show up immediately after creation.
* What the use cases about folders ? Are folders made to have non clickable item in a menu and no content ? It's what I expect in fact
* If we could indeed have a way to define "labels" for the folder as you suggested with a ``folder.md`` file, it would be awesome :) 

Thanks!

**Comment by flaviocopes** [comment]
The latest published release does not include the cache fix yet.

The use case is that, yes, to have a more structured menu.

**Comment by flaviocopes** [comment]
Closing as the OP feature is merged in develop

**Comment by nsteinmetz** [comment]
Hi,

Using 1.1rc3, I'm not sure it's merged within. Could you confirm ?

btw, is there a doc about new features for 1.1 which we can read somewhere ?

If I add a page within a folder, it's not considered as visible ?

Let me know if I should open a new issue for this.

Thanks,
Nicolas
