### ISSUE TITLE
Copying page in Admin makes resulting page have same slug

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#394]
When copying a page the slug of the new page does not seem to get changed, and is the exact same slug as the original page which then causes various issues.

I've attached a screenshot, look at the new copy folder name field vs. slug field.

![edit grav cms for educators flipping your lms with an open and collaborative web platform designing and building open source learning environments 2016-01-14 17-21-06](https://cloud.githubusercontent.com/assets/1812771/12342884/a8c36d28-bae3-11e5-96cd-f12f3b310089.png)

To repeat issue:
1. Open existing page
2. Click "copy" button
3. Go back to page list
4. Open newly created page
5. View slug on "Advanced" pane

Thanks very much,
Paul

**Comment by flaviocopes** [comment]
What you suggest, adding `*-copy` to the slug?

**Comment by paulhibbitts** [comment]
Hi Flavio,

I think we want to make it align with the current naming scheme logic, which seems to be using a " - #" format where # is either 2 or adding 1 to the existing value.

So, let's say there is a page called "New Page" and we make a copy. Here is what I would expect:

Copied page
- title: "New Page 2" (currently it is not, just the same title as orig - I suggest we change it)
- folder : "new-page-2" (currently as-is)
- slug: "new-page-2" (currently it is not, just the same slug orig. This is not an issue if no slug is defined on original page as new page slug field is then left blank)

What do you think?

Thanks very much,
Pau

**Comment by flaviocopes** [comment]
:+1: sounds good!

**Comment by flaviocopes** [comment]
Created a PR to solve this. Works at the basic level, still need to test with multilanguage and edge cases.

**Comment by flaviocopes** [comment]
Doing final tests to merge this

**Comment by flaviocopes** [comment]
Fixed by https://github.com/getgrav/grav-plugin-admin/pull/537

**Comment by flaviocopes** [comment]
@paulhibbitts give it a try when you have time, just to make sure there are no issues I didn't find

**Comment by paulhibbitts** [comment]
This is really awesome @flaviocopes! I've been able to do some testing and looks like a winner 👍

This is a perfect way to blow the mind of a WordPress person... 'you can even have two or more blogs in one Grav site, look it's so easy just a simple page copy and you're done.' 😉

**Comment by paulhibbitts** [comment]
So everything is working really nicely, but I think there will  be less possible user confusion if the new title of copied pages is also updated.

For example, I have a page called ‘My Apple’ with the slug ‘apple’. After making a page copy I have ‘My Apple 2” with the slug ‘apple-2’.

Another example is that I have a page called 'Home' with the default slug 'home. After making a page copy I have "Home 2" with the slug 'home-2'.

**Comment by flaviocopes** [comment]
Should now be fixed in develop. Copy "Test", the title is "Test 2". Copy "Test 2", the new title is "Test 3", and so on.

**Comment by paulhibbitts** [comment]
Thanks very much Flavio. I did some tests on noticed one issue:

If you start with 'Home' and make a copy you get 'Home 2' and 'home-2'. Make a copy of that and you get 'Home 3' and 'home-3' - perfect :-)

However if you at this point make another copy of 'Home 2' you get a page named 'Home 3' but with the right slug 'home-4'. Here is a snapshot:

![2016-06-15_06-46-02](https://cloud.githubusercontent.com/assets/1812771/16082078/236c4078-32c5-11e6-9a42-1c57bfc52849.png)

If the name # could match the slug # then I think it's good to go.

Thanks again,
Paul

**Comment by flaviocopes** [comment]
I did this on purpose - the slug **must** be unique, the title does not. 

The usage most likely is to copy a page one time, so you get its title + "2". 

If you want to copy it again, you'll get the page title + "3", but it's unlikely you'll keep the title the same on all pages.

**Comment by paulhibbitts** [comment]
Sounds fine, thanks. It is a more extreme use case I am testing with - as you say more likely to copy one page at a time and then change page names too.

Great to have page copying working even better in the new Admin Panel 👍
