### ISSUE TITLE
Updating Frontmatter (Expert Mode) - All data gets erased

### ISSUE THREAD

**Issue by sturple** [getgrav/grav-plugin-admin#396]
If you make a slight syntax error while editing the front matter (ie one two few spaces for yaml syntax) either the entire frontmatter gets wiped out or if you lucky the error gets translated to the content section.
It might be good to have a validation checker before saving, and give an error.
I have also had it where i get an Invalid Token while saving, which looses all changes.
This would probably be part of this https://github.com/getgrav/grav-plugin-admin/issues/346 fix as well.

Also it might be nice to save the original file to default.md.bak just in case your admin erases all data in frontmatter or content.

Otherwise I am really liking Grav, Thanks for all your hard work.
Shawn

**Comment by flaviocopes** [comment]
Thanks for reporting, will look into this tomorrow

**Comment by flaviocopes** [comment]
Fixed, now returns an error and the page is not saved. Could later improve this by checking via AJAX prior to saving so you don't lose the changes.
