### ISSUE TITLE
New pages are not created visible

### ISSUE THREAD

**Issue by astfgl** [getgrav/grav-plugin-admin#4]
When a new page is created, a numeric prefix is not prepended to the folder name when the directory is created on disk.

For example, when the user creates a new page of the name "Test1", the UI automatically fills in the folder name "test1". Clicking the continue button causes the module to create the directory "test1".

The expected behavior is for the module to enumerate the sibling pages and create the next directory in the sequence, such as "02.test1"

Steps to reproduce:
Install grav 0.9.34
Install beta admin module with gpm
Configure admin as per beta release blog post
Log into /admin
Click "Pages" in left nav panel
Click "+ Add Pages"
Enter "Test1" in "Page Title" input field
Leave all other fields as default
Click "continue"
Click "Save"

There will now be a sibling directory to "01.home" called "test1" in user/pages, instead of "02.test1".

**Comment by rhukster** [comment]
Should be sorted with: c59d5d4c9ffdb0e5dbeafab3c42e5a5ae7aeabd5
