### ISSUE TITLE
Font Montserrat from Google Fonts is missing some locale specific characters

### ISSUE THREAD

**Issue by martinsik** [getgrav/grav-plugin-admin#401]
Hey, I know this issue with missing characters has already been here #60. For example in Czech language:

![screen shot 2016-01-19 at 17 28 38](https://cloud.githubusercontent.com/assets/238765/12424892/8017953c-bed2-11e5-956b-ca333dfb6e66.png)

Font Montserrat from Google Fonts is missing some characters:

![screen shot 2016-01-19 at 17 32 09](https://cloud.githubusercontent.com/assets/238765/12424920/98381fa6-bed2-11e5-83d4-c8bacc9d3c90.png)

However, I found the same font on [fontsquirrel.com](http://www.fontsquirrel.com/fonts/montserrat) and it seems like it supports all possible languages so maybe it could be better to use this one instead of the one from Google Fonts.

![screen shot 2016-01-19 at 17 34 51](https://cloud.githubusercontent.com/assets/238765/12424984/f7045a2c-bed2-11e5-91b7-fa5ce4e69021.png)

**Comment by rhukster** [comment]
I'll look into this.. In the meantime, you can disable the Google fonts in the admin plugin preferences.

**Comment by petira** [comment]
@rhukster I think that this issue can be closed.
