### ISSUE TITLE
Parents display template types not choosable

### ISSUE THREAD

**Issue by BlkChockr** [getgrav/grav-plugin-admin#404]
Hi,

I recently got and error when trying to edit the "About me" section while using the "SoraArticle"-skeleton. I thought it was an error in the theme, but when I investigated it further, I saw that in the "Advanced" Section under "Pages" in the Admin Plugin, the "Display Template" was set to "Blog". But the theme does not offer a `blog.html.twig` for pages which have "sidebar" as a parent. In fact, it was a "Widget" before, but when I saved my edits, it was set to "Blog", because "Widget" was not choosable as a display template.

There is a `widget.html.twig` under `sidebar` (-> parent of the page) in the theme's "template"-folder, but you can not choose from them in the Admin-Pages-Configuration. When you then edit a page and try to save it, it will be saved with the first display template available, which ist "Blog" in this case.

My question is: Could you make the display templates lying in the page's parent folder available for choosing them in the dropdown? Or might this be a mal-structured template and the author(s) of SoraArticle have to fix this?

Greetings, BlkChockr

**Comment by flaviocopes** [comment]
Inspected and recreated. 

That part of the theme was created before the Admin plugin was available, and I am in doubt whether the Admin plugin should support this scenario, as the theme files available for pages in Admin are only those that live in the templates/ root folder. 

Maybe the sidebar of that theme should be reworked to use a modular page @hexplor what do you think?

**Comment by rhukster** [comment]
Actually the very point of **partials** is that they are snippets that are used by other things.  They are not intended to be a page-template.

If this `sidebar` is actually a page-template, it should not be in `templates/partials` it should be at the root of the `templates/` folder like all the other page-templates, so yup, sounds like a bug in the SoraArticle theme.

Please create an issue on that repo: https://github.com/getgrav/grav-theme-soraarticle/issues
