### ISSUE TITLE
Add blueprint list (type) button label override and lang translation

### ISSUE THREAD

**Issue by sturple** [getgrav/grav-plugin-admin#409]
## Features added
It would be nice to have an override field for the 'Add Item' button in the blueprint form field type 'list'.

* https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/templates/forms/fields/list/list.html.twig#L67
* https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/templates/forms/fields/list/list.html.twig#L107

The  'Add item' default should also be added to be translations in the lang file.
Thanks
Shawn

**Comment by gRoberts84** [comment]
Created PR #438 to resolve this.

@sturple - Once approved/pushed, you will be able to add `btnLabel: 'Click me to add another item'` to the field definition within your blueprint.

**Comment by flaviocopes** [comment]
Merged!
