### ISSUE TITLE
Page Titles with apostrophes

### ISSUE THREAD

**Issue by FrugalGeek** [getgrav/grav-plugin-admin#41]
If you set a new page title as (Jane McGonigal's Life-Extending Recovery Game) it creates it as ('Jane McGonigal''s Life-Extending Recovery Game') adding an additional apostrophe in the title field within the frontmatter.

**Comment by rhukster** [comment]
Thought I had this tested and fixed at some point.  I'll double check it again and see what can be done.  Cheers.

**Comment by FrugalGeek** [comment]
Actually, this doesn't appear to have an adverse affect on the frontend. It's just a curiosity in the admin. Maybe that extra apostrophe is necessary to separate it from the ones surrounding the title in frontmatter?

**Comment by flaviocopes** [comment]
This is actually correct, YAML escapes the single quote character by putting another single quote char before it (http://yaml.org/spec/current.html#id2534365). You could use the "real" apostrophe character (’) instead, which does not get escaped.
