### ISSUE TITLE
js error on page module with jquery-2.x.min.js-> console.log error output

### ISSUE THREAD

**Issue by githubrsys** [getgrav/grav-plugin-admin#410]
## Summary
* installed grav from cli
* installed grav-admin-panel from cli
* after login and navigation to admin/pages no js related function available in chrome on linux

### Error in JS Console

````
jquery-2.x.min.js?ea9495d53d:2 Uncaught Error: Syntax error, unrecognized expression: [href^=#]
````

### Temporary fix
Downgrade to jquery-2.14.min.js and the problem is gone.

#### Environment
* Grav version 1.0.8
* Admin Panel  v1.0.7
* Chrome 48.0.2564.82 (64-bit)

**Comment by flaviocopes** [comment]
Thanks for the detailed report! Actually already fixed in Admin develop https://github.com/getgrav/grav-plugin-admin/commit/29641a6f5b8cc21a4cbca18fe1a486c9cde8f1f2
