### ISSUE TITLE
Allow permission groups to hide/show page editor tabs

### ISSUE THREAD

**Issue by nineteeneightyeight** [getgrav/grav-plugin-admin#411]
It would be quite useful if we could lock down certain tabs from certain admin user groups. 'Advanced' tabs for example should only be visible to advanced admin users.

**Comment by flaviocopes** [comment]
We could add an access property to the tab and analyze it when rendering the tabs. 
All tabs need to be always present in the page I think to be saved correctly (need to check), but we could at least hide them.

**Comment by mahagr** [comment]
Implemented in Admin 1.10.
