### ISSUE TITLE
User can't change his profile with certain ACL

### ISSUE THREAD

**Issue by Birssan** [getgrav/grav-plugin-admin#412]
Hi,

I've tried tu use ACL for a particular user who's simply going to add pages and edit them.
I gave this user certain permissions like this:
```
admin:
    login: true
    pages: true
```

It turns out, this user can't change his profile info, permission denied...
I'm guessing this is not the expected behaviour ?

**Comment by Vivalldi** [comment]
You would also need to grant access to the users page. your updated permissions would look like
```
admin:
    login: true
    pages: true
    users: true
```

**Comment by Birssan** [comment]
Well wouldn't it me more logical that whoever can log in, should also be able to edit his own profile ?

Plus, I don't see anything about `admin.users` here http://learn.getgrav.org/admin-panel/faq#managing-acl

**Comment by flaviocopes** [comment]
Right, anyone with `admin.login` should be able to see their profile.

**Comment by flaviocopes** [comment]
Fixed by https://github.com/getgrav/grav-plugin-admin/pull/524
