### ISSUE TITLE
Selectize fields with many items are not displayed correctly 

### ISSUE THREAD

**Issue by embieone** [getgrav/grav-plugin-admin#414]
Selectize fields with many elements are displayed incorrectly due to their fixed height which is set in _form.scss in line 137.

![Backend](https://cloud.githubusercontent.com/assets/17044501/12781107/a5ee1bf4-ca72-11e5-8326-a40273ac1f64.jpg)

![Inspector](https://cloud.githubusercontent.com/assets/17044501/12781108/a5eeb104-ca72-11e5-95a9-3af2e99c782e.jpg)

**Comment by rhukster** [comment]
Perhaps you can look at this @w00fz with your JS revamp.  Might be purely CSS though.

**Comment by w00fz** [comment]
Was indeed pure CSS and it's now fixed
