### ISSUE TITLE
Newly installed themes won’t appear in Grav Admin.

### ISSUE THREAD

**Issue by dotdapple** [getgrav/grav-plugin-admin#416]
While the themes do install – I see their files in `/user/themes` – they don’t show up in Grav Admin → Themes.

**Comment by flaviocopes** [comment]
It might be a theme issue, which miss some files. Which theme is that?

**Comment by dotdapple** [comment]
Ah yeah, it seems it is a theme-specific issue.

Sidewalk and Solid State are the ones having problems.

**Comment by flaviocopes** [comment]
Yes. Opened issues: 

- Solid State https://github.com/giansi/grav-theme-solid-state/issues/4
- Sidewalk https://github.com/DarrylDias/Sidewalk/issues/4

Sidewalk actually is shown but without image
