### ISSUE TITLE
Site Title label in Admin -> Config -> Site is on 2 lines

### ISSUE THREAD

**Issue by notasausage** [getgrav/grav-plugin-admin#418]
In Safari on a Mac, the first form label in the Grav Admin's Configuration -> Site tab for `Site Title` is displayed on 2 lines instead of 1. All other form labels in the Admin look fine in Safari though.

<img width="767" alt="grav site title" src="https://cloud.githubusercontent.com/assets/447901/12852354/873f75c8-cbfc-11e5-8e52-fc8343e2e487.png">

To fix this, I manually set the `display` property of the `span` tag around form labels with hints to `inline` instead of `inline-block` which fixed the issue in Safari.

```
span.hint--bottom {
    display: inline;
}
```

**Comment by flaviocopes** [comment]
Replicated in Safari. Looks like it's fixed in the latest develop release. Will be in the next update.

**Comment by notasausage** [comment]
Look at you guys, fixing issues that we haven't even submitted yet!

**Comment by rhukster** [comment]
Actually i can replicate it.. fixing shortly...

**Comment by flaviocopes** [comment]
Not I get why I could not replicate: I had Google Fonts turned off in the Admin Plugin configuration, and it showed up fine. Replicated too now
