### ISSUE TITLE
RTE preview functionality

### ISSUE THREAD

**Issue by TommiTikall** [getgrav/grav-plugin-admin#42]
First of all, I want to say: what a nice looking admin interface. This was the tipping point for me of choosing Grav from other flat file cms :) Very nice.

Here is the issue:
When I click the "preview" button in the RTE (The eye icon button, which I'm assuming is preview) when creating a new and/or editing a page, it shows a "Not found" popup when clicked. It also sometimes shows the RTE content as empty (as can be seen in the attached image). The markdowm text is still there though if I click back on the "markup" icon button.

I have a clean install of Grav 0.9.35, and have made no changes to the code, other than adding account yaml files to /user/accounts.

![grav-preview-bug](https://cloud.githubusercontent.com/assets/2525981/9155581/7f0f34ec-3ebc-11e5-84a8-492d23638e26.jpeg)

**Comment by rhukster** [comment]
Do you happen to be running the PHP built in webserver?  If so this will not work with the admin (and other Grav plugins):

http://learn.getgrav.org/basics/installation#phps-built-in-web-server (see the warning box)

**Comment by TommiTikall** [comment]
Hello @rhukster.
Thank you for your quick reply, and you are correct, I am using the standard PHP webserver.
I tried setting up a apache web server (http://getgrav.org/blog/mac-os-x-apache-setup-multiple-php-versions), but it is not working. Do you have any recommendations for local development environment?

**Comment by rhukster** [comment]
Well I can probably help you get it working if you wish :) Just let me know what problems you have.

Otherwise MAMP is an easy solution on a mac, the free version works well enough although it's not as optimized or as fast as the apache/homebrew setup as outlined in the blog post.

**Comment by rhukster** [comment]
I'll close this issue now, but if you want help setting up your homebrew php/apache setup just hop on the Grav gitter.im and we can walk you through your issues.
