### ISSUE TITLE
I forgot the password

### ISSUE THREAD

**Issue by wildafrica** [getgrav/grav-plugin-admin#423]
Hello,

I would like to ask you if it is possible to get my password back when I forgot it? I have it only on localhost and probably I do not know login neither password. I do not have email sending ON. I did not even know it is there. I am beginner.

Thank you

**Comment by MATsxm** [comment]
Go to 
**user** -> **accounts** and edit or delete the <code>.yaml</code> file.
Go back to your site and then you will have to restart the login process...

![admin](https://cloud.githubusercontent.com/assets/1972717/13027386/e0126dc2-d223-11e5-944b-7cc863d62aed.png)

see also: http://learn.getgrav.org/admin-panel/faq

>> **NOTE:** for those kind of support questions, it's better to check the [documentation] (http://learn.getgrav.org/) or ask on the [forum](https://getgrav.org/forum) or even [Gitter](https://gitter.im/getgrav/grav-plugin-admin)

**Comment by wildafrica** [comment]
Thank you very much. I remembered my password.

**Comment by MATsxm** [comment]
@flaviocopes @rhukster  can be closed - thanks

**Comment by wildafrica** [comment]
Thank you again.
