### ISSUE TITLE
kendoDateTimePicker is not attached to datetime input that is part of a list of fields

### ISSUE THREAD

**Issue by LondonITGuys** [getgrav/grav-plugin-admin#424]
To reproduce this: create in a theme a custom blueprints file along the line of 
`    title: Events
    '@extends': default

    form:
      fields:
        tabs:
          fields:
            advanced:
              fields:
                columns:
                  fields:
                    column1:
                      fields:
                        name:
                          default: modular/events
                          @data-options: '\Grav\Common\Page\Pages::modularTypes'
                overrides:
                  fields:
                    header.template:
                      default: modular/events
                      @data-options: '\Grav\Common\Page\Pages::modularTypes'
            events:
              type: tab
              title: Events
              fields:
                header.events:
                  name: Events
                  type: list
                  label: Events
                  fields:
                    .datetime:
                      type: datetime
                      label: Date and Time
`
When you click on the "Add item" button, an input form element is shown unstyled and without the date and time selector widget attached to it.

I believe the problem comes from init.js that only attaches kendoDateTimePicker(kendoOptions) to input that are already present on first page load and not to dynamically added elements. We could do something like:

    $(document).on('DOMNodeInserted', 'li[data-collection-item]', function(e) {
        var $element = $(e.target);
        if ($element.is('[data-collection-item]')) {
            $($element, $('input[data-grav-field-datetime]').each(function () {
                ....
            }));
        }
    });

But performance wise I don't think it is ideal, another solution would be to remove the `script` tag in list.html.twig and hide the li, making the datetime input part of the DOM?

**Comment by flaviocopes** [comment]
Thanks for the detailed report, it's a known issue, it's being reworked in @w00fz https://github.com/getgrav/grav-plugin-admin/tree/feature/es6_revamp branch, it's already working there but the branch has other work currently in progress that needs to be done prior to merging.

**Comment by LondonITGuys** [comment]
OK, thank you.

**Comment by w00fz** [comment]
Yup this is all sorted now. Any fancy field we use (lists, editors, datetime-picker, arrays) gets properly initialized every time you add a new entry.
