### ISSUE TITLE
Incorrect URL for Grav JSON Pages API v0.1.4

### ISSUE THREAD

**Issue by derekchin** [getgrav/grav-plugin-admin#425]
Right now it points to this url
https://github.com/nathanpfedwards/grav-plugin-pages-json

it should point to this
https://github.com/npfedwards/grav-plugin-pages-json

I think this prevents the cms from installing the plugin.

**Comment by flaviocopes** [comment]
I can install it fine, from the command line. But the links in the blueprints.yaml file are incorrect, will raise an issue on that plugin repository.

**Comment by flaviocopes** [comment]
I installed it correctly also via Admin plugin

**Comment by krisak** [comment]
There is something wrong. I installed the plugin using the gpm, it is correctly in plugin folders but it never shows up.

**Comment by krisak** [comment]
OK so the plugin https://github.com/npfedwards/grav-plugin-pages-json does not work in current version. Also when plugin is installed its installed into pages-json folder but the initialization file is called grav-plugin-pages-json so the plugin does nothing. When the names are changed it just breaks everything. I guess it shouldnt be listed in https://getgrav.org/downloads/plugins

**Comment by rhukster** [comment]
Sounds like an issue with the **pages-json** plugin itself? Perhaps then the issue should be created there: https://github.com/npfedwards/grav-plugin-pages-json/issues

**Comment by krisak** [comment]
Sorry @rhukster you are probably right. Its strange that i found this issue using google here instead of the plugin repo.
