### ISSUE TITLE
Cannot connect to the GPM

### ISSUE THREAD

**Issue by humblehumanbeing** [getgrav/grav-plugin-admin#428]
Downloaded the very latest grav+admin package and run localhost/grav-admin in Wampserver 64-bit for Windows 10.
Browsing different sections of the admin with MS Edge I receive **'Cannot connect to the GPM'**
I had posted this issue at https://getgrav.org/forum#!/general:cannot-connect-to-the-gpm
FYI. Curl, openssl are installed and enabled in PHP
**PHP 5.6.15 (cli) (built: Nov  9 2015 13:03:20)**

**Comment by flaviocopes** [comment]
Are you behind a proxy?

**Comment by w00fz** [comment]
Does it work with Chrome / Firefox? Also have you tried reaching as 127.0.0.1 rather than localhost?

Other ideas: 
1. Try via command line a `bin/gpm index`, see if that works. 
2. And lastly, I would also make sure all is enabled as you say by looking at a `phpinfo();`. I see you pasted the php version for the cli and sometimes that does not match the one run with the web server.

// Djamil Legato // From iPhone //

**Comment by sural98** [comment]
**http://127.0.0.1/grav/admin** outputs the same error
Windows Command line for php version `C:\WINDOWS\system32>"C:\wamp\bin\php\php5.5.12\php.exe" -v` outputs **PHP 5.5.12 (cli) (built: Apr 30 2014 11:20:58)**
Cygwin output for 
$ bin/gpm index

> PHP Warning:  Invalid argument supplied for foreach() in /cygdrive/c/wamp/www/gr                                                                                                                 av/system/src/Grav/Console/Gpm/IndexCommand.php on line 110
> You can either get more informations about a package by typing:
>     bin/gpm info <package>
> Or you can install a package by typing:
>     bin/gpm install <package>
> 
@flaviocopes My computer is behind a proxy but it is a local wampserver with which I am testing Grav

**Comment by flaviocopes** [comment]
If you're behind a proxy then set https://github.com/getgrav/grav/blob/develop/system/config/system.yaml#L7

**Comment by sural98** [comment]
I have set it as
proxy_url: http://CORPORATEDOMAIN\USERNAME:PASSWORD@10.111.111.111:8080
but didn't work
FYI. When connecting we use CORPORATEDOMAIN\USERNAME as user name in proxy configuration.

**Comment by flaviocopes** [comment]
Proxy auth is not yet handled by Grav. Adding it now, will ping you a PR to test

**Comment by flaviocopes** [comment]
Can you test the edits contained in this pull request? https://github.com/getgrav/grav/pull/698 
Should 'just work' with the setting you added.

**Comment by rhukster** [comment]
@sural98 can you let us know if this sorted the problem for you???

**Comment by sural98** [comment]
https://github.com/getgrav/grav/pull/698 **and/or**
https://github.com/getgrav/grav/blob/develop/system/config/system.yaml#L7
didn't work unfortunately.

**Comment by w00fz** [comment]
What do you get if you run the following in the terminal?
```
curl -I https://getgrav.org/downloads/grav.json
```

**Comment by sural98** [comment]
Git CMD
`curl: (7) Failed to connect to getgrav.org port 443: Timed out`
Cygwin
```
$ curl -I https://getgrav.org/downloads/grav.json
curl: (28) Connection timed out after 300917 milliseconds
```

**Comment by w00fz** [comment]
Now try:

```
curl -I --proxy-user "CORPORATEDOMAIN\USERNAME:PASSWORD" --proxy "http://10.111.111.111:8080" https://getgrav.org/downloads/grav.json
```

**Comment by sural98** [comment]
HTTP/1.1 200 Connection established

**Comment by w00fz** [comment]
Well, what I asked you to do is to manually call curl the same way @flaviocopes is doing with the PR at https://github.com/getgrav/grav/pull/698 . So I'm not exactly sure why it isn't working.

**Comment by w00fz** [comment]
Can you try this. With Flavio's patch applied to your code, where it says:

```php
$options['curl'][CURLOPT_PROXYUSERPWD] = $parsed_url['user'] . ':' . $parsed_url['pass'];
```

After that line add:

```php
$options['curl'][CURLOPT_HTTPAUTH] = CURLAUTH_BASIC;
```

Then remove completely the line:
```php
$options['curl'][CURLOPT_PROXYTYPE] = 'HTTP';
```
Now try again and see if it works. If it doesn't, one other thing you can try is to (while still keeping all of the above changes) add where you removed the `PROXYTYPE` the following:

```php
$options['curl'][CURLOPT_HTTPPROXYTUNNEL] = true;
```

**Comment by sural98** [comment]
None has worked.

**Comment by rondlite** [comment]
chown your grav dir to your webuser .. that did it for me.
`chown www-data:www-data grav -R`

**Comment by dmacros** [comment]
I have the same issue. I'm on shared without SSH access. Some solution?

Thanks!
