### ISSUE TITLE
Number prefix is not updated on page copy

### ISSUE THREAD

**Issue by jjui** [getgrav/grav-plugin-admin#429]
When copying a page with number prefix, the same number is applied to the new page-folder but adds new number on end of folder. 

Worth a look!

**Comment by flaviocopes** [comment]
Linked to https://github.com/getgrav/grav-plugin-admin/issues/394

**Comment by flaviocopes** [comment]
Linked to https://github.com/getgrav/grav-plugin-admin/issues/394

**Comment by flaviocopes** [comment]
@rhukster thoughts on what's the desired behavior on this?

**Comment by flaviocopes** [comment]
On it

**Comment by flaviocopes** [comment]
Fixed by merged PR #537

**Comment by jjui** [comment]
Nice 👊

**Comment by flaviocopes** [comment]
Give it a try when you have time, just to make sure there are no issues I didn't find
