### ISSUE TITLE
theme inheritance should be default behavior 

### ISSUE THREAD

**Issue by 4evermaat** [getgrav/grav-plugin-admin#434]
After reading [this blog post on Grav theme inheritance](https://getgrav.org/blog/theme-development-with-inheritance), I thought about why the developers did not make this an option within the admin panel when or after installing a plugin or theme (pre-checked or not pre-checked).  

this way the user doesn't have to worry about messing up the core theme and can upgrade without worries about their changes being overwritten and breaking functionality.  It makes editing themes/plugins more "idiot-proof" so to speak.

**Comment by flaviocopes** [comment]
You cannot create a child plugin, only a child theme. If you want to customize a plugin, you need to clone it, rename and create a new one. Only themes can be customized by using inheritance.

I have some trouble understanding what you mean, you'd like a button "Customize this theme" that will automatically create a child theme?

**Comment by rhukster** [comment]
I don't really agree it should be the default behavior, we can't enforce that logic outside of the admin, and as the admin is 100% optional, and really not intended for the development phase, it would be very strange to enforce that there.

However, we are planning on building some 'developer tools' into the Grav that will let you create scaffolding via the CLI.  What this means is there will be a command to prompt you with a few questions (plugin name, author, email, etc) and create a base plugin for you.  Also same goes for theme, and could handle extending another theme too if you so chose.

We could bring this logic to the admin plugin also.  I think this is the way to proceed.

**Comment by rhukster** [comment]
Closing this as we have a plan :)

**Comment by 4evermaat** [comment]
Remember, i'm thinking more from an end-user perspective.  To get updates from core plugin without overwriting custom changes

**Comment by flaviocopes** [comment]
I don't think there's any plan to allow end users to edit **plugins**. Plugins are usually much more complex that themes, and if you need to edit their functionality (apart from tweaking the output, which can be done in the theme) you need to fork the plugin and install your own version, or have the original plugin include hooks and events to allow other plugins changing its default behavior.

**Comment by 4evermaat** [comment]
Ok. Then lets stick to themes.  I'm sorry if I caused confusion in my original post.  The theme inheritance would be useful if the end user didn't have to think too much about broken functionality if the theme is updated.
