### ISSUE TITLE
Problem uploading mp4 via uploader in admin

### ISSUE THREAD

**Issue by jjui** [getgrav/grav-plugin-admin#436]
As the title, 
nothing strange, the codec is H.264 with AAC but the result is `Invalid security token` every time
Worth to take a look at

**Comment by flaviocopes** [comment]
Have no issues, just tried. Tested a sample video from http://www.sample-videos.com/
Admin is latest release I assume.

**Comment by flaviocopes** [comment]
Which browser?

**Comment by jjui** [comment]
Chrome with every latest update.
And compiled the file again today with ffmpeg to same format - result was success. 
Do not know why the error occurred, but closing issue

**Comment by flaviocopes** [comment]
Maybe its format was not recognized then? If it happens again post the file that gives you the problem.
