### ISSUE TITLE
very long tab content -> tabs not switchable anymore

### ISSUE THREAD

**Issue by embieone** [getgrav/grav-plugin-admin#441]
Hi, 
if the content of a tab is very long (>9999px) the tab navigation is not clickable anymore.

I use the list element in the content tab to build a gallery. Now the list has about 50 items in it and when I switch to the next tab (advanced) I can't switch the tabs anymore. I've digged a bit and it turned out that the tabs top position is set to -9999px by default and to 0 when active. The content of the tab is now larger than 9999px so it overlaps the other tabs and makes the tab navigation unclickable. Via the browsers DevTools I've set the opacity of the inactive tab to 1 to show the problem (please see attached screenshots). 

![1](https://cloud.githubusercontent.com/assets/17044501/13576152/8a57a8ae-e48c-11e5-8e0a-ffe8e066f71e.jpg)
![2](https://cloud.githubusercontent.com/assets/17044501/13576153/8a591108-e48c-11e5-91f1-2e6355b44685.jpg)
![3](https://cloud.githubusercontent.com/assets/17044501/13576154/8a596bda-e48c-11e5-80f2-e513a6256edd.jpg)

**Comment by rhukster** [comment]
Fixed for next release.
