### ISSUE TITLE
Commented lines in headers erased in expert mode

### ISSUE THREAD

**Issue by nopicnicc** [getgrav/grav-plugin-admin#442]
Hi,

When I edit a page in expert mode any commented lines in the header gets erased on save. 

Before save:

	title: Prices
	#buttons:
	#    -
	#        text: Find Out More
	#        url: #
	icons:
	    -
	        label: Feature 1
	        icon: clock-o`
	
After save:
	
	title: Prices
	icons:
	    -
	        label: Feature 1
	        icon: clock-o

Regards,

Niklas

**Comment by flaviocopes** [comment]
That's the expected behaviour I think. The frontmatter is validated, cleaned and reformatted during saving, that removes the comments too.

**Comment by nopicnicc** [comment]
Thanks for your answer flavio. 

What use are the comments then? Why would you comment if you just want to delete the lines?

/Niklas

**Comment by rhukster** [comment]
The thing is that when the YAML is read by Grav it is converted into a PHP object.  This object is manipulated and used to set values on the forms.   Fields that the forms don't understand are stored as json that we parse and attach back.

However, the fundamental problem is that the YAML parser simply ignores comments, so Grav has no knowledge of them throughout this process.  So there's really no way to keep them.

I suggest using a `display` custom field to display text or instructions if the admin is going to be used.

**Comment by nopicnicc** [comment]
Ok thank you for your answers guys. 

/Niklas
