### ISSUE TITLE
Sub-Sub page is not visible in main menu

### ISSUE THREAD

**Issue by shadyonline** [getgrav/grav-plugin-admin#446]
I add a sublevel page, then I add another sublevel page to that one and on the frontend I just see 2nd, no one of 3rd

**Comment by flaviocopes** [comment]
The behavior of the menu in the frontend depends on the theme used, is not an Admin plugin issue.

For example on Antimatter 2nd level is shown in the dropdown (if dropdown menu is enabled) and deeper levels are shown when hovering the 2nd level option.
