### ISSUE TITLE
User Manager GUI

### ISSUE THREAD

**Issue by dfinkdd** [getgrav/grav-plugin-admin#448]
# Proposal
**Add a user manager (based on a GUI) to the Admin plugin to allow administrators to easily add, remove, modify, and perform other tasks relating to users of a Grav site.**

In regards to the definition of a user manager, this is a module that contains features which allow for the manipulation of user accounts by an administrator or other privileged user. Such an example of a user manager relevant to this feature request is the user manager found within the Wordpress CMS.

## Use Case
A prominent use case for a user manager in the Admin plugin would be for site administrators, developers, and other individuals that may need to implement Grav to create user accounts for clients or collaborators such that those users can perform the more basic site tasks (such as creating pages and posts) without requiring a site's administrator or implementor to perform those tasks for them, saving time specifically for professionals who may have several clients or collaborators.

## Functionality
1. Create New Users
2. Delete Users
3. Modify Users (Edit names, email addresses, passwords, account permissions, etc.; most likely using the same form that is used to modify the site administrator's user account)
4. Bulk Edit Users (For applying permissions, deleting multiple users, and other tasks in which multiple users need to be manipulated at one time)

**Comment by Vivalldi** [comment]
This is already being considered in the Pro version of the admin plugin

https://getgrav.org/blog/beta-admin-plugin-available
That blog post contains info from the initial release of the admin plugin and contains info about the pro version as well (yet to be launched)

**Comment by rhukster** [comment]
Actually we have already got most of this working in our pro development project.

**Comment by q2apro** [comment]
> Alternatively, you can create a user/accounts/admin.yaml file manually. This filename is actually the username that you will use to login. The contents will contain the other information for the user.

https://getgrav.org/blog/beta-admin-plugin-available

However, if you like to have a user as editor (not admin) it seems that you cannot set separate access level. Having: 

  access:
    admin:
      login: true
      super: false

will give an access denied.

Ah, found: https://learn.getgrav.org/admin-panel/faq#adding-and-managing-users

It works now with: 

	access:
	  admin:
		login: true
		super: false
		pages: true
	  site:
		login: true

However, clicking on your own profile, e.g. `admin/users/tester`, gives "Access denied", there is no access option for the profile page.

Leaving my comment here to help others.

**Comment by Globegitter** [comment]
@Vivalldi @rhukster Does this pro version now exist? Not finding anything specific on it and would be nice to have some User Management GUI.
