### ISSUE TITLE
Error with modular pages after template switch

### ISSUE THREAD

**Issue by marsien** [getgrav/grav-plugin-admin#449]
I have an error when I change the template of of modular page; for example, if i switch from "showcase" template to "about" template in antimatter. The error occur when I save the change, even if the change occurs.
After, i can not never open again this page in the admin plugin, I have always the same error.

Here, what Crikey says:
`Twig_Error_Runtime thrown with message "An exception has been thrown during the rendering of a template ("Undefined index: type") in "pages.html.twig" at line 246."

Stacktrace:
#28 Twig_Error_Runtime in /var/www/vhosts/scribavita.fr/test.scribavita.fr/vendor/twig/twig/lib/Twig/Template.php:182
#27 Whoops\Exception\ErrorException in /var/www/vhosts/scribavita.fr/test.scribavita.fr/system/src/Grav/Common/Data/Blueprint.php:335
#26 Whoops\Run:handleError in /var/www/vhosts/scribavita.fr/test.scribavita.fr/system/src/Grav/Common/Data/Blueprint.php:335
#25 Grav\Common\Data\Blueprint:parseFormFields in /var/www/vhosts/scribavita.fr/test.scribavita.fr/system/src/Grav/Common/Data/Blueprint.php:334
#24 Grav\Common\Data\Blueprint:parseFormFields in /var/www/vhosts/scribavita.fr/test.scribavita.fr/system/src/Grav/Common/Data/Blueprint.php:334
#23 Grav\Common\Data\Blueprint:parseFormFields in /var/www/vhosts/scribavita.fr/test.scribavita.fr/system/src/Grav/Common/Data/Blueprint.php:334
#22 Grav\Common\Data\Blueprint:parseFormFields in /var/www/vhosts/scribavita.fr/test.scribavita.fr/system/src/Grav/Common/Data/Blueprint.php:334
#21 Grav\Common\Data\Blueprint:parseFormFields in /var/www/vhosts/scribavita.fr/test.scribavita.fr/system/src/Grav/Common/Data/Blueprint.php:200
#20 Grav\Common\Data\Blueprint:embed in /var/www/vhosts/scribavita.fr/test.scribavita.fr/system/src/Grav/Common/Data/Blueprint.php:61
#19 Grav\Common\Data\Blueprint:fields in /var/www/vhosts/scribavita.fr/test.scribavita.fr/system/src/Grav/Common/Page/Page.php:889
#18 Grav\Common\Page\Page:blueprints in /var/www/vhosts/scribavita.fr/test.scribavita.fr/vendor/twig/twig/lib/Twig/Template.php:598
#17 call_user_func_array in /var/www/vhosts/scribavita.fr/test.scribavita.fr/vendor/twig/twig/lib/Twig/Template.php:598
#16 Twig_Template:getAttribute in /var/www/vhosts/scribavita.fr/test.scribavita.fr/cache/twig/aa/aaa203b63b844777a8142be36f9efc7686c8885f51beb9d2bf53b86face2f343.php:469
#15 __TwigTemplate_6f05f85a6fe19c32015cdc0de11e74069e783653ff6f0852f5082008c05aefdf:block_content in /var/www/vhosts/scribavita.fr/test.scribavita.fr/vendor/twig/twig/lib/Twig/Template.php:167
#14 Twig_Template:displayBlock in /var/www/vhosts/scribavita.fr/test.scribavita.fr/cache/twig/b5/b5a522504f1a9fdd2a9932cc10699d1c0aca3738d1e13487be919ff5fcac16e2.php:292
#13 __TwigTemplate_d800aa35c7bb6e47cf26ddefc448879b03c72fe7fe10ee6167edb2eacf205644:block_page in /var/www/vhosts/scribavita.fr/test.scribavita.fr/vendor/twig/twig/lib/Twig/Template.php:167
#12 Twig_Template:displayBlock in /var/www/vhosts/scribavita.fr/test.scribavita.fr/cache/twig/b5/b5a522504f1a9fdd2a9932cc10699d1c0aca3738d1e13487be919ff5fcac16e2.php:45
#11 __TwigTemplate_d800aa35c7bb6e47cf26ddefc448879b03c72fe7fe10ee6167edb2eacf205644:doDisplay in /var/www/vhosts/scribavita.fr/test.scribavita.fr/vendor/twig/twig/lib/Twig/Template.php:381
#10 Twig_Template:displayWithErrorHandling in /var/www/vhosts/scribavita.fr/test.scribavita.fr/vendor/twig/twig/lib/Twig/Template.php:355
#9 Twig_Template:display in /var/www/vhosts/scribavita.fr/test.scribavita.fr/cache/twig/aa/aaa203b63b844777a8142be36f9efc7686c8885f51beb9d2bf53b86face2f343.php:71
#8 __TwigTemplate_6f05f85a6fe19c32015cdc0de11e74069e783653ff6f0852f5082008c05aefdf:doDisplay in /var/www/vhosts/scribavita.fr/test.scribavita.fr/vendor/twig/twig/lib/Twig/Template.php:381
#7 Twig_Template:displayWithErrorHandling in /var/www/vhosts/scribavita.fr/test.scribavita.fr/vendor/twig/twig/lib/Twig/Template.php:355
#6 Twig_Template:display in /var/www/vhosts/scribavita.fr/test.scribavita.fr/vendor/twig/twig/lib/Twig/Template.php:366
#5 Twig_Template:render in /var/www/vhosts/scribavita.fr/test.scribavita.fr/vendor/twig/twig/lib/Twig/Environment.php:347
#4 Twig_Environment:render in /var/www/vhosts/scribavita.fr/test.scribavita.fr/system/src/Grav/Common/Twig/Twig.php:334
#3 Grav\Common\Twig\Twig:processSite in /var/www/vhosts/scribavita.fr/test.scribavita.fr/system/src/Grav/Common/Grav.php:186
#2 Grav\Common\Grav:Grav\Common{closure} in /var/www/vhosts/scribavita.fr/test.scribavita.fr/vendor/pimple/pimple/src/Pimple/Container.php:113
#1 Pimple\Container:offsetGet in /var/www/vhosts/scribavita.fr/test.scribavita.fr/system/src/Grav/Common/Grav.php:288
#0 Grav\Common\Grav:process in /var/www/vhosts/scribavita.fr/test.scribavita.fr/index.php:38

`

Everything works fine as long as the template selected when the modular was created is not changed.

**Comment by flaviocopes** [comment]
What is "about", a modular child page type you created?

**Comment by marsien** [comment]
Yes, it is a template I created for modular child pages. I'm sorry,
    I thought this template was in Antimatter theme. The problem is the
    same with all other modular templates (in antimatter, ie: features,
    showcase or text).
    
    
    Le 12/03/2016 18:52, Flavio Copes a
      écrit :
    
    
      What is "about", a modular child page type you created?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by marsien** [comment]
I think the problem occurs with template inheritance. Only modular files in both templates make this error.
