### ISSUE TITLE
Pagemediaselect should refresh when new media is uploaded

### ISSUE THREAD

**Issue by marcelgwerder** [getgrav/grav-plugin-admin#450]
I currently need to reload the page to be able to select uploaded media in pagemediaselect.
The list should be updated after new media files were uploaded so the user can directly select it.

**Comment by flaviocopes** [comment]
Yes currently this is by design. There's nothing that automatically refreshes that field when a new page media is added, both from Admin or via file system.

**Comment by marcelgwerder** [comment]
Hmm ok but to be honest this is a major usability flaw. Should the user really refresh the page manually each time he wants to select new media in pagemediaselect? If this is by design, the design is wrong or I just don't get it.

**Comment by flaviocopes** [comment]
That field just lists the media files found in the page folder, at the moment when the page is loaded. It's not "polling" or refreshing itself when you add a media. While it's a feature worth having at some point, now it's an expected behavior.

**Comment by flaviocopes** [comment]
I'll leave the issue open as at some point we'd like to have it

**Comment by flaviocopes** [comment]
Currently working on it https://github.com/getgrav/grav-plugin-admin/pull/750

**Comment by w00fz** [comment]
Implemented
