### ISSUE TITLE
IP Anonymization in Analytics

### ISSUE THREAD

**Issue by raum-IO** [getgrav/grav-plugin-admin#455]
Hello,

here in Germany/Europe we need to anonymizes IP addresses by privacy laws.
Please add an option to activate IP anonymization by google analytics.

Google Analytics Help: https://support.google.com/analytics/answer/2763052?hl=en

Best regards, Andi

**Comment by flaviocopes** [comment]
The analytics provided by the Admin Plugin do not use Google Analytics. 

That said, it collects IP addresses in the log, so an option should be added for that.

**Comment by mahagr** [comment]
The funny thing is that all servers automatically collect IPs from every request into system logs, so you end up having much more detailed logs with IPs regardless of what Grav does.

I've never taken these privacy laws seriously for obvious reasons. And yes, all three of us live inside EU.

I do agree, though, that having the option for this is needed.

**Comment by raum-IO** [comment]
@flaviocopes Sorry, but that's not the question...

@mahagr Yes, but unfortunately it is required by law and in Germany you get unfortunately very fast mails from lawyers.

**Comment by mahagr** [comment]
I fully agree, though Europe seems to have too many laws that everyone breaks just because of there's no way to comply on those laws. This is one example as all servers will record/track the IP information whether you want or not. So everyone already breaks the law, including me and you.

I don't think you get any calls from layers unless you are using that IP information to track down people.

**Comment by raum-IO** [comment]
@mahagr Yeah, that's what we know, that's not what the lawyers and courts think. I payed some hundreds of Euros for this, so I do not want to repeat this. ;)

It's an easy switch "Send anonymous IP Information", insert the additional Code and everyone is happy...
Manual: http://www.andilicious.com/blog/google-universal-analytics-tracking-code-anonymisieren/4445/

**Comment by flaviocopes** [comment]
As said the Admin Plugin does not use Google Analytics. If you're seeing a GA code in the site, it's not added by the Admin Plugin or Grav itself, but from a plugin or the theme.

**Comment by raum-IO** [comment]
@flaviocopes Whoopsie :dart: wrong link :D
> https://github.com/escopecz/grav-ganalytics/issues
