### ISSUE TITLE
using underscore vs dashes in page filename

### ISSUE THREAD

**Issue by 4evermaat** [getgrav/grav-plugin-admin#459]
how do I get grav to use underscore `_` instead of dashes `-` in the pages filename?  I noticed that grav uses dashes in the page name when there are spaces or on default. I prefer underline.  Is there an admin panel option for this?

I see the option to put `.html` at the end of the page.  But it seems spaces in filename default to `-` instead of `_` .  Any ideas?

**Comment by rhukster** [comment]
there is currently no way to modify this behavior.  Really there's got to be a limit on the number of configuration options we provide.  If we allow every single thing to be controllable, the configuration would be a nightmare.  At some point we have to be able to make smart decisions and keep things relatively simple :)  

Just look at the iPod!

**Comment by 4evermaat** [comment]
The ability for a webmaster to format the webpage filename is a pretty basic feature.  Do you think this is asking too much?  Wordpress had this way back when they first allowed individual pages.

Especially if there is SEO considerations?

**Comment by rhukster** [comment]
What SEO considerations?  HTTP "slugs" typically require dashes, and and underscore is much less common.  Do you have any concrete information to say that using an underscore is preferable to a dash?

**Comment by w00fz** [comment]
You can still do underscores if you like, just don't rely on the automatic slug generator and edit it to use `_` every time you want.

There is no such thing as underscores being more SEO friendly than dashes, if anything, dashes are the *de facto* URI space separators adopted by any present and past sites.

There's often the tendency to forget how far search engines have come, a dash or an underscore is not going to prevent any search engine from understanding that it means space.

I'm not arguing that underscore might be your choice of preference when it comes to URI space separation, but I hope you understand that having this as an optional setting is not going to add any real value.

**Comment by MATsxm** [comment]
If it helps

In Google’s search engine algorithm, the underscore isn’t a recognized word separator.

https://support.google.com/webmasters/answer/114016?hl=en (cf. example my-new-black-kitten.jpg)
Google's Matt Cutts: https://www.mattcutts.com/blog/dashes-vs-underscores/
https://www.youtube.com/watch?v=AQcSFsQyct8
For example:
my-new-black-kitten.jpg will be seen as 4 (key)words my new black kitten
my_new_black_kitten.jpg will be seen as 1 word mynewblackkitten

Another link with simple and clear explanation : http://searchengineland.com/9-seo-quirks-you-should-be-aware-of-146465

**Comment by flaviocopes** [comment]
Agree, in Admin we must make a decision. If you want to use underscores, you can still manually change the slug, or create the pages via file system directly.

**Comment by 4evermaat** [comment]
Yes, fair enough.  i will start to use dashes instead of underscores in the file name.
