### ISSUE TITLE
TypeError on Configuration save

### ISSUE THREAD

**Issue by butchewing** [getgrav/grav-plugin-admin#461]
When saving /admin/config/system in the Admin console, there is a type error thrown:

**TypeError**
```
Argument 1 passed to Grav\Common\Data\Blueprint::mergeArrays() must be of the type array, boolean given, called in /system/src/Grav/Common/Data/Blueprint.php on line 276
```

**Comment by flaviocopes** [comment]
Can you paste your `user/config/system.yaml` file?

**Comment by butchewing** [comment]
Whoa, super fast response! Yes, in fact, I added back the default system.yaml and the admin configuration saved perfectly. I then updated various fields and it's still good.
