### ISSUE TITLE
page editor should use ajax to save/autosave

### ISSUE THREAD

**Issue by 4evermaat** [getgrav/grav-plugin-admin#462]
page editor should use Ajax to save changes.  The current method of having to save and refresh the screen is annoying when making edits and wanting to perhaps make more quick edits.  We have to wait for the entire screen to refresh instead of using ajax to save quickly and then a floating modal `"page saved"` for a few seconds on the screen.

Another advantage of using ajax:  you don't lose your cursor position.  Imagine you write an email and every time you save the draft, the page refreshes and you have to scroll back to where you were editing.  This is what grav admin does when it saves.  Refreshes the entire page.  So I then must scroll back down and attempt to find where I was editing.   

I need to be able to save, refresh my browser window to get a full preview of changes, and then make further edits exactly where I left off.

 Another optional feature could be an auto-save option every x minutes if any changes are detected.

**Comment by BugHunter2k** [comment]
Dup of https://github.com/getgrav/grav-plugin-admin/issues/346 ?

**Comment by 4evermaat** [comment]
@BugHunter2k looks like it.  feel free to merge this OP with #346 .  The other enhancement #463 is still a separate enhancement though.
