### ISSUE TITLE
page editor needs breadcrumbs or improved navigation between pages....

### ISSUE THREAD

**Issue by 4evermaat** [getgrav/grav-plugin-admin#463]
The current page editor forces users to click on 'pages' to view a list of all the pages.  I understand doing this the first time.  But once I am in pages mode, there should be 
a) navigation tree to the left, or
b) breadcrumbs above the page editor that allows me to move to a different page.  These breadcrumbs should include dropdown for subpages/modules and contain mouseover details of the page.

The current implementation I have to constantly go back to the 'pages' homepage to view another page I may want to edit.  To get around this, I end up opening up several tabs.  But it is still a bit clunky regardless.

Would also be nice if `ajax` could be used to make switching between pages smoother.  Come to think of it, ajax with a status bar should be used to switch between all major sections of the admin panel (like themes, plugins, etc).

**Comment by mahagr** [comment]
Admin 1.10 should have pretty good navigation already.
