### ISSUE TITLE
blueprint overwrite fails to cannot save from admin panel

### ISSUE THREAD

**Issue by mrhein** [getgrav/grav-plugin-admin#464]
If you overwrite with a blueprint the default behavior so only your custom frontend view is visible it ends up in that throw of error message on save. In that specific case $parent contains nothing because in line 1204 in admin/classes/controller.php the $route contains '/.‘.

[bilder_kategorie.yaml.txt](https://github.com/getgrav/grav-plugin-admin/files/192971/bilder_kategorie.yaml.txt)

[bilder_kategorie.md.txt](https://github.com/getgrav/grav-plugin-admin/files/192972/bilder_kategorie.md.txt)

![parent_error](https://cloud.githubusercontent.com/assets/1809310/14100067/fc739e70-f58a-11e5-8e9e-d2833b3f27fc.png)

**Comment by mrhein** [comment]
my current workaround approach is to override it like this way than you can save the content...

**Comment by flaviocopes** [comment]
A page blueprint always needs to extend the default page blueprint, or you'll get this sort of issues and possibly also other side effects.
