### ISSUE TITLE
Feature Request: Adding a summary delimiter button to the editor

### ISSUE THREAD

**Issue by Kadoffe** [getgrav/grav-plugin-admin#466]
If you'r using Grav to host a blog or something similar you will allways pay attention to the length of the article summary at the beginning. Nothing importand should be cut off by the size limitation and images shouldn't be displayed when placed on top of the main text.

So it would be usefull and comfortable if there is a button to insert the summary delimeter that is defined in the site configuration [ [link](http://learn.getgrav.org/admin-panel/configuration-site#page-summary) ].
e.g. if '===' is set as delimeter the following text will be inserted:
```
<!--summary end-->
===
```
the additional comment will make it easy to read and help users that aren't used to the syntax

**Comment by w00fz** [comment]
Thanks for the suggestion, this is now implemented.
