### ISSUE TITLE
Update language strings

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#468]
Capitalize `c` in `can`.
`UNPUBLISHED_DATE_HELP: "can provide a date to automatically trigger un-publication."`

Remove `b` tag as it is escaped, thus, the text won't be bold.
` MENU_HELP: "The string to be used in a menu.  If not set, <b>Title</b> will be used."`

**Comment by flaviocopes** [comment]
Thanks, please contribute those on Crowdin (www.crowdin.com/project/grav-admin) as the translations are managed there.

**Comment by flaviocopes** [comment]
Question on the translation flow,  @rhukster: being this english, do we need to include them in the lang file directly, not on Crowdin?

**Comment by rhukster** [comment]
Actually **yes** - we should change the english version **only** in GitHub, then we upload that to Crowdin.

**Comment by flaviocopes** [comment]
Ok, then @Quy you can edit this file directly https://github.com/getgrav/grav-plugin-admin/blob/develop/languages/en.yaml and submit a Pull Request, thanks!
