### ISSUE TITLE
Use checkboxes for access levels

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#471]
Why not use checkboxes for available supported access levels instead of free form fields and the value set to `true`?

**Comment by flaviocopes** [comment]
The thing is, there is no fixed access level.

While we provide some access levels for use in the Admin (http://learn.getgrav.org/admin-panel/faq#managing-acl), a Grav site can use completely custom access levels. 

Maybe we could have checkboxes for the ones used by the Admin plugin, and then have an open-form to add other custom access levels too.

**Comment by BugHunter2k** [comment]
Is it possible to discover the used access levels somehow? Then use checkboxes for those and another input field to create new ones.

**Comment by Quy** [comment]
Related to #850
