### ISSUE TITLE
Validation failed: Invalid input in "Content"

### ISSUE THREAD

**Issue by maikschneider** [getgrav/grav-plugin-admin#472]
We get this error trying to save any page created through the admin backend. It is possible to create and save the page in first place, however writing more than one line in the content field produces this error:
![error message](https://photos-1.dropbox.com/t/2/AADoFF6E67VeVUTDZuGg6oVuptm7uf2uMH7K86VWiykB4g/12/6842173/png/32x32/3/1459429200/0/2/Screenshot%202016-03-31%2010.28.01.png/EKmLiwUYofEBIAIoAg/lKIUTzkbG3NVEfzzdZ3rTuNBPHSaEN8AqrqbGIZcwOw?size_mode=3&size=1280x960)

This seemed like a permission issue. Using a different apache user than the file system owner resolves the issue. But doing this makes it not possible to edit as file system user.
My current configuration:
![Image of folder and user permissions](https://photos-4.dropbox.com/t/2/AABsG54tcwOaoRjRJbzP7SNrjCDqqT_ykMdN44BuLH4WYA/12/6842173/png/32x32/3/1459429200/0/2/Screenshot%202016-03-31%2010.24.17.png/EKmLiwUYn_EBIAIoAg/T8nTSuznLq8_xoexggDRNMzVUvgLHzjcI8YBF0gIkm4?size_mode=3&size=1280x960)

Any ideas?

**Comment by flaviocopes** [comment]
You mention "writing more than one line in the content field" gives the error. 
So if you edit the first line and save, save is successful?

**Comment by maikschneider** [comment]
Yes.
I'm using apache installed through homebrew. Coworker gets the same error using MAMP Pro.

**Comment by flaviocopes** [comment]
Latest stable grav + admin?

**Comment by maikschneider** [comment]
Yes.

**Comment by flaviocopes** [comment]
Very strange. Cannot reproduce, which is kind of expected, as if this was an issue in Grav itself, any user would have it.

Send me your user/ folder via a Gitter PM (https://gitter.im/flaviocopes), I'll check if I can reproduce it on my MAMP Pro too.

**Comment by maikschneider** [comment]
It happens even using the default theme - no additional plugins.
I'm pretty sure it's an configuration, but we have no clue what else to try.

**Comment by maikschneider** [comment]
Problem solved! I was not using the stable version of grav - I was on the develop branch - totally missed that out. Thanks again @flaviocopes
