### ISSUE TITLE
Fonts in forms too large

### ISSUE THREAD

**Issue by tiptronic** [getgrav/grav-plugin-admin#473]
Whenever I login to admin and e.g. click 'Add page', the font-sizes and line-height (set to 3rem) are much too big (on Safari (latest), OSX 10.11.4)

see screenshot

<img width="706" alt="screenshot 2016-04-04 02 07 34" src="https://cloud.githubusercontent.com/assets/80752/14235845/187be932-fa0a-11e5-9e3c-7793bfd31228.png">

**Comment by rhukster** [comment]
I have seen this before. I bet you have the **blog-injector** plugin installed.

 Seems to be a bug with that plugin so you should create an issue on that repo.

**Comment by tiptronic** [comment]
No - no blog-injector plugin installed.

Btw... happens on both Safari, Chrome and Firefox-DeveloperEdition...

**Comment by flaviocopes** [comment]
Can you inspect the content of the textarea with the Browser Inspector tool and check in which CSS file is that color / font size being applied?

**Comment by tiptronic** [comment]
This is the base-node:
.selectize-control.single .selectize-input, .selectize-control.single 

And this the value (where it reads font-size: 3rem, line-height: 3rem;)
.form-field .require

**Comment by flaviocopes** [comment]
Which CSS file sets it? You can see on the right of that panel

**Comment by rhukster** [comment]
Flavio is asking you 'which' plugin CSS file is causing the 'red' color for exmple.  The panel on the right side in the web inspector tells you which CSS file is providing any particular rule.

I know it's a 3rd party plugin.  

Another way to find out is to disable your plugins one by one until the issue goes away.  Then that will tell you which one is at fault.

**Comment by tiptronic** [comment]
Ah... ok -  sorry I misunderstood the question.
I'm just experimenting with grav and thought I have a quite basic version... I'll see what I can find out.
Anyway - Grav looks awesome!

**Comment by tiptronic** [comment]
The culprit was the Blog plugin:

https://github.com/giansi/grav-plugin-blog

**Comment by rhukster** [comment]
Yes, figured as much.  The **blog** plugin was actually renamed to **blog-injector** that I mentioned initially because it caused too much confusion

**Comment by tiptronic** [comment]
OK... so it's recommended not to use it?
I like the functionality of it (need a separate 'section' in my site to group projects - multiple 'blogs' would be awesome ;))

**Comment by rhukster** [comment]
I think everything that it does can be done in Grav without it.  You can have multiple blogs no problem, currently the issue lies with the associated blog-type plugins, they might need to be tweaked to support multiple blogs.

it's a 3rd party library so I really don't know much about how it's working.  This is one problem that has been reported several times. It might already be fixed in **blog-injector** - maybe try that first.

**Comment by tiptronic** [comment]
Will do & Thanks for your valuable hints!

**Comment by giansi** [comment]
I do not have that issue on Ubuntu 15.10 using chrome and firefox. Anyway I just released 1.2.2 version which should fix.
