### ISSUE TITLE
Parser bug in text-field:

### ISSUE THREAD

**Issue by tiptronic** [getgrav/grav-plugin-admin#474]
If I put the text below into a page, I can't set the second headline 'Another-test' to bold (or anything) using the text-formatting tools of the text-field:

----------- (copy from the line below):
## **test** :

first:  <hello>/dolly_#/
second: message
third:  <hello>/john_#/
forth:  message
## Another-test:

oops ... the above can't be set to bold!

**Comment by rhukster** [comment]
Are you talking about the markdown editor in the page?

**Comment by rhukster** [comment]
can you put the 'raw' text you are working with in a code block?

**Comment by tiptronic** [comment]
Sorry - yes I'm talking about the markdown editor field when editing page-contents.

As far as 'raw' text part of your question is concerned - I'm not sure I understand correctly:

The problem is, that - even if I put the above inside a blockquote, I can SELECT 'Another-test', but I can't make it e.g. bold (or whatever).

**Comment by flaviocopes** [comment]
I don't understand the problem, can you make a short gif / screencast? A picture is worth a thousand words sometimes :)

I like this app to easily do quick gifs: http://recordit.co/

**Comment by tiptronic** [comment]
I'll do that later today and post a link...

**Comment by rhukster** [comment]
Still an issue???

**Comment by tiptronic** [comment]
oops... forgot about that - I'll try to check that out using the current version and leave a feedback here...
