### ISSUE TITLE
Q: How-to zoom an image on hover

### ISSUE THREAD

**Issue by Mausy5043** [getgrav/grav-plugin-admin#479]
I would like to create a page that contains a number of small graphs that will zoom when hovered over with the mouse. Typically, similar to the static image on [this page](http://bit.ly/1XeYpCA).
Is there some built-in way to achieve this or should I define a custom class?

Now, in the chapter "Image Linking" the [Grav manual](http://learn.getgrav.org/) mentions that you can use `![My Image](my-image.jpg?classes=float-left)` to add a class to an image. There is no mention, however, on how/where to define a class. At least I didn't find it.

Any help/pointers would be appreciated.

**Comment by rhukster** [comment]
This is a CSS/JS question and not related to Grav or the Admin either.

You will need to implement a JS or CSS solution that might entail using a CSS class and/or some JS added to the page.  Maybe something like this: http://www.jacklmoore.com/zoom/

**Comment by Mausy5043** [comment]
I'm sorry if I have formulated the question incorrectly. I've taken the liberty of adjusting the title of the issue. I'm not looking for a solution on how to create a CSS class. However, if I have a CSS class where should I insert it, so it can get picked up by the pages?

Do you advise to embed the CSS code somewhere in the markdown page? Or somewhere in a template?

**Comment by flaviocopes** [comment]
A class is just defined by you in that snippet. It will be outputted as-is

`![My Image](my-image.jpg?classes=something`

`![My Image](my-image.jpg?classes=something-else`

You can add CSS where you find it more convenient. In a Markdown page, in the Twig, added to the theme.. the best option is always to have it in a separate file, and tell Grav to load that file, like most themes do in the `templates/partials/base.html.twig` file.

**Comment by Mausy5043** [comment]
Ahaa! :OK: Thanks!
👍
