### ISSUE TITLE
Integration of editor with "Pen"

### ISSUE THREAD

**Issue by mattmezza** [getgrav/grav-plugin-admin#483]
Hi guys, I have just discovered the [Pen project](https://github.com/sofish/pen) and I was wondering whether if it could be useful to use it to create and edit content in the admin area of grav.

There is a demo running [here](http://sofish.github.io/pen/) that you can look at. It automatically translates live edited content into markdown.

So the feature I am proposing consists in directly enabling live editing mode for new content creation, then the switch to markdown could be possible to tweak and refine. Doing this even users not aware of markdown could create content easily.

![unbenannt](https://cloud.githubusercontent.com/assets/1915989/14353512/ac51b11a-fcd9-11e5-8210-2d0522d3841e.PNG)

**Comment by rhukster** [comment]
We are aware of Pen, and all the other WYSIWYG type editors for markdown.  The problem with all of them currently is they don't allow you to mix HTML in there.  Worse, if you have HTML or custom markdown (like grav supports) and edit it in these editors and save, your custom stuff gets stripped out.  Very scarey!

**Comment by mattmezza** [comment]
I didn't think about that! 

For the moment I decided to use Pen as an external tool just to hide the markdown layer to the user. 

He simply edits content with Pen and then the tool automatically generates the markdown to be copied into grav. 

I hope I can convince my client to adopt grav.
