### ISSUE TITLE
Don't restrict user's password

### ISSUE THREAD

**Issue by CodinCat** [getgrav/grav-plugin-admin#488]
Currently, grav restricts the password must contain at least 8 characters, 1 number 1 uppercase and 1 lowercase letter, I know you want to improve the security, but that's really not a good experience...

for example, if my password is `h$3iq!d9v`
you will agree that it's very strong, but it will not pass because there is no uppercase letter.

also in some cases, like test purpose or in dev environment, I just want to use `0000` or `1234` as my password, then the password policy becomes very inconvenient. 

Maybe just show a warning when a user trying to use a weak password, and if the user really want, just let him use.

**Comment by MADmarek** [comment]
Disagree from security point of view because this is very often forgotten ro changee afterwards in production.
Use instead the password remember functionality of the browser.

**Comment by rhukster** [comment]
I also agree this sets a bad precedent and just opens up the opportunity for people to inadvertently  leave their user accounts exposed.
