### ISSUE TITLE
Page media content not loading

### ISSUE THREAD

**Issue by pichiste** [getgrav/grav-plugin-admin#489]
Hello there,

I'm encountering a problem after uploading images to a specific page and then saving. After the refresh, the thumbnail images in the "page media" section are missing. The console shows a server error:

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://xx.xx.xx.xxx/admin/media/testimage.json/task:listmedia/admin-nonce:090ff426f7167505856aa03981aba155 
```

I had no issue with this working locally on OS X, but the problem emerged when moving the project to an Ubuntu VPS (Ubuntu 14.04, Apache 2.4.7, PHP 5.5.9). I'm on the latest versions of Grav and the Admin plugin. 

Seems to be a similar error to [#334](https://github.com/getgrav/grav-plugin-admin/issues/334)?

Thanks!

**Comment by flaviocopes** [comment]
Could be a permission issue. Check http://learn.getgrav.org/troubleshooting/internal-server-error for possible causes too

**Comment by pichiste** [comment]
Super stupid mistake on my part - had left the top-level 'images' directory out of the git repo I was using to deploy... apologies!
