### ISSUE TITLE
Description and Keywords not shown without quotation mark

### ISSUE THREAD

**Issue by K232** [getgrav/grav-plugin-admin#49]
I don't use quotation marks for my metadata description and keywords, e.g.:
>metadata:
>   description: This is a test
>   keywords: grav, test

instead of

>metadata:
>   description: 'This is a test'
>   keywords: 'grav, test'

This seems to work fine for the output, metadata is shown correct in the source of my file. But when I open the blog entry via the admin plugin, keywords and description are empty. I've added them again and saved it to check the output, and I've seen that the admin panel then saves it with quotation marks around. (Additionally strange: I only added the keywords, but the description is still available, now also with quotation marks around it).
I've checked Grav Documentation at http://learn.getgrav.org/content/headers , but there are no quotation marks around it, so it seems that both should be working?
If so, it would be nice to display description and keywords (and maybe some other fields?) also correct in admin panel if no quotation marks are used.
Thanks a lot!

**Comment by flaviocopes** [comment]
Metadata spacing was correct prior to pasting here? E.g.

```
metadata:
    description: This is a test
    keywords: grav, test
```

**Comment by K232** [comment]
Yes.
For testing I've copied the data from http://learn.getgrav.org/content/headers 

    metadata:
        description: Your page description goes here
        keywords: HTML, CSS, XML, JavaScript
        author: John Smith
        robots: noindex, nofollow

Same result, keywords and description are empty when I want to edit the page via admin-panel.

**Comment by flaviocopes** [comment]
Strange, I can see them! Do you see them in "expert mode"?

**Comment by rhukster** [comment]
I think there are some fixes I added since the last release that would explain why flavio has no problems and you do.  We'll get a new release out soon.

**Comment by K232** [comment]
I've updated Grav to 0.9.36 and adminpanel to 0.3.0, but problem still exists.

**Comment by rhukster** [comment]
Hmm. I just pasted your metadata above into frontmatter of a sample blog item, then opened that same item in Admin:

![pages grav2 2015-08-12 09-15-52](https://cloud.githubusercontent.com/assets/1084697/9227852/da54b882-40d2-11e5-87e7-c0c785a68dcf.png)

Showed up just fine. How did you add the metadata? manually or via expert in the admin?

**Comment by rhukster** [comment]
BTW, also tested by pasting into frontmatter in "Expert" view, and then switched to "Normal" view and also worked fine.

**Comment by rhukster** [comment]
I simply cannot replicate this.  Can you provide some example page and/or data I can test with?
