### ISSUE TITLE
Images with file extension in caps not recognized

### ISSUE THREAD

**Issue by ArnauBlanch** [getgrav/grav-plugin-admin#495]
Hi, I've noticed that when files with the JPG extension in capital letters (file.JPG) are uploaded in the editor they are not recognised as images, so when you insert them into a page the Markdown code is for links (not for images). I haven't tried with other file types. :S

I hope this can be fixed because there are many cameras that put the filename extension in capital letters. :)

**Comment by flaviocopes** [comment]
Hi, I added a fix to recognize uppercase file extensions back in january: https://github.com/getgrav/grav-plugin-admin/commit/80eef0a91921280e3b3543c32fdd72a7fc724d8f 

Before trying, are you using the latest release of the Admin plugin?

**Comment by ArnauBlanch** [comment]
Mmm I'm using a modified admin plugin, I didn't notice the update. Sorry.
