### ISSUE TITLE
Usability issues with the (+) button in pages list

### ISSUE THREAD

**Issue by fvsch** [getgrav/grav-plugin-admin#496]
In the current stable admin plugin (for Grav 1.0.10), the (+) button that shows a page’s children in `/admin/pages` has a few usability issues:

- On hover it uses a text cursor, rather than `cursor:pointer` or `cursor:default`, which can make user thinks it’s not a reactive element.
- On hover it shows an information tooltip that has nothing to do with showing/hiding child pages. This also sends the wrong message ("no feature here, don't click").
- It cannot be accessed with the keyboard (it’s currently a `<i class="page-icon …"></i>`, would benefit from being a `<button type="button" aria-label="Show child pages"><i class="page-icon …></i></button>`).
- The hitbox for actually clicking the button is too small: 20 by 16px. For an icon-only button, I’d say 24 by 24px is a minimum, but 30px is even better.

**Comment by rhukster** [comment]
Some legit things here. We'll take a look!

**Comment by rhukster** [comment]
Fixed in develop
