### ISSUE TITLE
Page filtering only applies to first level pages

### ISSUE THREAD

**Issue by fvsch** [getgrav/grav-plugin-admin#498]
In the `/admin/pages` view, the “Add Filters” field only applies to first level pages.

For instance I have this kind of architecture:
```
home/
    home.md
    _module1/
        somemoduletype.md
    _module2/
        othermoduletype.md
news/
    news.md
    article1/
        article.md
    article2/
        article.md
```

Problems found:

1. Filtering on "Non-modular pages" will still show `/home/_module1/` because its parent is shown.
2. Filtering on the `article` type will hide everything, because `/news/` has a different type (`news`).

Expected results:

1. When filtering on "Non-modular pages", the `/home/` page should be visible, but its modular children should be hidden. Maybe the (+) button should be affected too if all its children are filtered out.
2. When filtering on the `article` type, the `/news/` page should be shown (perhaps slightly greyed out to indicate that it’s not actually matching the filter), and its children of type `article` should be visible (or, if collapsed, the (+) button on the `/news/` line should reveal them).

**Comment by rhukster** [comment]
I know @w00fz reworked this JS for 1.1, maybe this is sorted as part of that effort?

**Comment by w00fz** [comment]
Yes this should be already fixed in the current develop branch. The whole filtering has been rewritten. Once 1.1 is out please feel free to reopen this if the issue persist, on my current local it seems to behave as you explained.

Thanks!
