### ISSUE TITLE
Button `Back to Themes` is missing. 

### ISSUE THREAD

**Issue by Vivalldi** [getgrav/grav-plugin-admin#5]
When looking to add new themes if you click on a theme to read about it there is no way out of the theme without using the back button on the browser. The plugins however have a button that says `Back to Plugins`.

![](http://i.imgur.com/fIo9upg.png)

![](http://i.imgur.com/Hed5L39.png)

**Comment by flaviocopes** [comment]
@Vivalldi thanks, should be fixed now
