### ISSUE TITLE
Add 'global' admin language setting option

### ISSUE THREAD

**Issue by RomainFallet** [getgrav/grav-plugin-admin#500]
Because Grav does not know who we are before we are logged in, it can't translate the login form or the login and logout success messages in the admin panel.

Here is a link of the dashboard, set in french but with an english success message :
[http://img15.hostingpics.net/pics/608303Screenshot1.png](http://img15.hostingpics.net/pics/608303Screenshot1.png)

**Comment by flaviocopes** [comment]
Setting the default Grav language to french, instead of english, should
work:
https://learn.getgrav.org/content/multi-language#single-language-different-than-english

Il giorno lun 18 apr 2016 alle ore 22:59 Romain Fallet <
notifications@github.com> ha scritto:

**Comment by RomainFallet** [comment]
Well, no, unfortunately.

**Comment by flaviocopes** [comment]
Should be fixed in the next 1.1 beta
