### ISSUE TITLE
List Inception - "Add Item" button adds 2 fields to the child list

### ISSUE THREAD

**Issue by Vivalldi** [getgrav/grav-plugin-admin#504]
When you click the add item button 2 fields are created in the child of the list (this only occurs if you have a list inside a list).
![](http://i.imgur.com/FJwNPyH.png)

**Comment by rhukster** [comment]
Are you using the latest `develop` branch?  This was radically revamped since 1.0.10.

**Comment by nepomuk13** [comment]
I have the same problem with 1.1.0 beta and it works fine with 1.0.10
And saving the page will duplicate each item. So if you have two elements and save three times, you will have 16 list elements created.

**Comment by Vivalldi** [comment]
Fixed in 1.1.0 Beta
