### ISSUE TITLE
Give a translation to the templates name ?

### ISSUE THREAD

**Issue by RomainFallet** [getgrav/grav-plugin-admin#506]
For now, templates list, available in the advanced tab of a page in the admin panel take the filename of the template as name.

It would be great if this names were translatable. I currently build a project for a client that is not english, I would like to put the template name in his own language so he could understand more easily which template he can applied on his pages.

**Comment by rhukster** [comment]
These directly correspond to the templates.  Having them translatable would only add to confusion  I think.  

If you want to use more understandable naming, you just need to rename the twig page templates themselves.

**Comment by RomainFallet** [comment]
For the developer maybe, even if I don't see how he can be confused by a name he set himself, but not for the non-english client that is not computer friendly (because, yes, unfortunately, there are non-computer friendly clients that want to manage their own website).

And I would love to give other names to templates, but Grav does not provide a way to do that since it forces the naming of templates (and I don't say that is a bad thing, I like this principle). If my modular templates name is not "modular", it does not work at wall, if I didn't have an "error" template, Grav trigger a beautiful error on 404 requests and the "default" template is required, as its name, by default.

But ok, it's about the core default required templates, in theory, I could create some custom templates with the name I want. But english is the only language where there are no chars accentuated. There are accentuated chars in french, spanish, italian, german…, and like I expected, Grav does not manage accentuated chars in templates filename. And in other languages, such as french, a non-accentuated char that has to be accentuated is a typo.

And that's not all, I can't use names with spaces in it, Grav does not support that too, and once more, if english can manage a lot of expression in only one word, it's only related to this language.

But yes, accentuated chars and spaces in filename is, in general, a bad practice in programmation whatever the language you speak. That's why the text in front, that are readable, should always be dissociated of the text in back, that build the thing and provide the structure and functionalities.

If Grav is multi-languages, then all must be translatable, even the login form, even the part where we can upload medias in a page and even the templates names.

I understand that the way templates are managed presently is a convenient way that works like a charm, but you cannot tell me that giving more sense to users is confusing without joking. Can't we imagine an simple optional blueprints file that maps the templates with their front names if we wan't to translate them ?

**Comment by flaviocopes** [comment]
There _could_ be a translation string of the template filename. For example `blog` or `item` are not that much explicative, I always thought they could be better presented to the user, better would be "Blog post" and "Blog posts list" for example. That would be the english translation, and we'd have one for each language.

The problem is determining how to associate a string to a page type, but it's a technical one.
