### ISSUE TITLE
Should not allow removing plugins with dependencies

### ISSUE THREAD

**Issue by flaviocopes** [getgrav/grav-plugin-admin#51]
E.g. should not allow removing Login or Email (or at least put a warning before doing so), because Admin depends on them. Maybe a more general rule could also apply to `bin/gpm`?

**Comment by rhukster** [comment]
Probably a good idea.  We can add these as a hardcoded list for now, but at some point we will probably need to add a setting to the blueprints to disable removing from admin.

**Comment by rhukster** [comment]
Actually fixed by making the enabled field hidden for email/form/login.. Will take a new release to take effect though.
