### ISSUE TITLE
Disallow page deletion if it has child pages

### ISSUE THREAD

**Issue by fvsch** [getgrav/grav-plugin-admin#510]
If an admin user deletes one "root" page and ends up deleting dozens of child and grandchild pages as a result, this can get really messy. Of course `user/pages` could be a git repo etc., and there’s the built-in backup-to-zip feature, but both solutions require manual intervention to do backups (or to set up a cron job), so it's likely that it won't happen often enough or at all.

Perhaps the `taskDelete` implementation should check if there are child pages and disallow deletions in that case? This behavior could be activated through configuration (with a true/false flag), to avoid making this a breaking change.

**Comment by flaviocopes** [comment]
Maybe we can tell that this is a parent page, and to double check, in the page removal confirmation dialog.

**Comment by rhukster** [comment]
We have a warning currently.  If you had a large nested list of pages, and you legitimately did want to delete all, it could be very painful to delete all children recursively manually.  I think we would get many more people asking to allow it if we disabled it.

**Comment by fvsch** [comment]
I was suggesting adding a config key for disabling it, not disabling it by default.

**Comment by flaviocopes** [comment]
I'm more a fan of having good defaults, instead of having the user choose what's the best option, the current flow is good imho

**Comment by fvsch** [comment]
@flaviocopes Agreed on principle. But "sure, I’ll let you delete everything by mistake" works as a good default if you also have a recovery mechanism, such as #509.

**Comment by rhukster** [comment]
Grav has built-in backup mechanism :)

I do think at some point we'll have a "Trash" system for those accidental deletes.  Maybe 1.2?
