### ISSUE TITLE
Validation error when saving site config - Grav 1.1.0-beta | admin panel v1.0.9

### ISSUE THREAD

**Issue by nepomuk13** [getgrav/grav-plugin-admin#514]
On a clean install with Grav 1.1.0beta and admin panel v1.0.9, you can't save the page in configuration>site , even when left untouched. 
Panel gives the following error message:

Validation failed: 
Invalid input in "Metadata"

I tried to empty metadata fields, or to add a few items, but nothing works.

**Comment by rhukster** [comment]
Again you have to update both at the same time.  There's many updates in the Admin.

**Comment by rhukster** [comment]
FYI, we're looking at some way to put a notice/alert on the Admin side of things with important messages about updates and such.  Of course this won't be available in Admin v1.0.9, but moving forward it could be available in 1.1.0+ to ensure we handle this situation in the future.
