### ISSUE TITLE
Permissions are handled differently on Safari, Chrome, Firefox (OS X 10.11.3)

### ISSUE THREAD

**Issue by tiptronic** [getgrav/grav-plugin-admin#515]
There are some mysterious permisson problems:

This one is especially very interesting... plz don't ask me what I did... :)
<img width="744" alt="screenshot 2016-04-24 03 01 50" src="https://cloud.githubusercontent.com/assets/80752/14764901/3dd30f24-09ca-11e6-84f7-c9383269496f.png">

This page is restritced to a certain group, and - although it seems login failed, the page is shown:
<img width="769" alt="screenshot 2016-04-24 03 05 17" src="https://cloud.githubusercontent.com/assets/80752/14764900/3dd21bb4-09ca-11e6-9957-893193279d63.png">

...btw: please note, the latter page is minimized to a small pane... (using an unmodified Antimatter-Theme)

andy

**Comment by flaviocopes** [comment]
First, you logged in through the Admin panel? Was are the user's permissions? Can he access the admin panel? If not, while the message is a misleading (and should be fixed), the user was logged in, but cannot access the admin panel, so both messages are correct.

As for the frontend issue: the page is restricted to permissions the current user has not access to? 

If so, I have fixed this in Login 2.0, which is currently available in the Grav 1.1 beta.

**Comment by tiptronic** [comment]
I had Admin-permissions; it could be there was a second window open, which was already logged in...

I'll check that out in the next beta.

thx

Andy

**Comment by flaviocopes** [comment]
Ok so the same account, with different browsers, works differently? Please provide more details. Which worked, which did not? Can you replicate if you logout from the one you're logged in now?

**Comment by tiptronic** [comment]
I'm currently out of town, but will provide more details as soon as I'm back!

Andy
