### ISSUE TITLE
Admin Form Placeholders are Indistinguishable

### ISSUE THREAD

**Issue by Algorithm518** [getgrav/grav-plugin-admin#516]
If placeholders are used in a form's blueprint, the placeholder value is indistinguishable from the actual form's input.

e.g. 
<img width="909" alt="screen shot 2016-04-24 at 11 28 53 pm" src="https://cloud.githubusercontent.com/assets/7495133/14773135/5c28dce2-0a74-11e6-834d-0c263e1ec103.png">

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-admin/commit/689a70a6584802c9583b22b561f92eba9531c8a9

Fixed now.  Thanks.
