### ISSUE TITLE
Please add support for cyrillic slug and aliases

### ISSUE THREAD

**Issue by TheRealMaN** [getgrav/grav-plugin-admin#520]
Please add support for cyrillic slug and aliases, e.g. for russian language e.g. "/о-компании", "/новости" and etc

**Comment by rhukster** [comment]
We use this definition of **Slugs** - https://en.wikipedia.org/wiki/Semantic_URL#Slug

As such they must be lowercase **english** characters.  Really the only place this is validated though is the admin.  So if you don't use the admin, you can use whatever you like.

**Comment by TheRealMaN** [comment]
If I write a cyrillic slug (e.g. slug: контакты) in a file and don't use the admin, grav returns a 404 error. Wordpress or Joomla supports it out of the box, it would be nice to have it in Grav.

**Comment by rhukster** [comment]
I don't suppose you could debug/add this and issue a pull request? :)

**Comment by TheRealMaN** [comment]
I would like to if I could)

**Comment by rhukster** [comment]
Should be sorted with this: https://github.com/getgrav/grav/commit/4573173456245f9d385ad69df10c2fd918e2fcf8

Hopefully it's not broken anything!
