### ISSUE TITLE
Sidebar not toggleable

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#523]
In Firefox 46.0 on Windows 8.1 and Safari on iOS 9.3.1, the sidebar is not toggleable. Here is the error message in the web console: `ReferenceError: event is not defined`

**Comment by rhukster** [comment]
Is this in reference to the 1.1.0-beta.1 version of the admin?

**Comment by Quy** [comment]
Yes

**Comment by rhukster** [comment]
Works in Safari 9.1 on OS X, but not Firefox 47. So we'll get that looked at.  Thanks.

**Comment by Quy** [comment]
Using beta2, it is working in Firefox, but not on iOS (iPad and iPhone) where the sidebar won't expand.

**Comment by rhukster** [comment]
I guess we have a lingering issue with iOS still @w00fz

**Comment by w00fz** [comment]
This is the same issue as in #527, Private Browsing not allowing to use localStorage, throwing an error and stopping the execution of the script.

I will add a check to make sure it doesn't fail like that so Private Browsing can be still used. I'm going to close this issue and keep #527 open as reference (and reminder).

Cheers.
