### ISSUE TITLE
 undefined index: grav-update

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav-plugin-admin#528]
I am playing with beta releases and saw that there is a new update for grav beta.

Trying to update give the error in the title and as per the picture attached.

Any ideas ? I have mangled to update the testing beta of admin and form no issues so far.
![captura de ecran din 2016 04 28 la 17 06 21](https://cloud.githubusercontent.com/assets/7076631/14892786/54daea0a-0d64-11e6-8a4f-7fad60312ccd.png)

**Comment by rhukster** [comment]
Pretty sure this is the same as: https://github.com/getgrav/grav-plugin-admin/issues/528

**Comment by JohnMica** [comment]
I have read the 526 issue - the plugins on my end have updated without any issues.
Only the grav beta has this issue when trying to update it. 
You are the expert, but I just wanted to let you know about the error on my side.

**Comment by w00fz** [comment]
Yes I don't think the two issues are related. I have now added a missing part. Can you check for updates to refresh the GPM repository on your site and try upgrading again?

**Comment by JohnMica** [comment]
i'm trying to self-upgrade -f -y (update says nothing to update) and i get Runtime error - error while trying to download
![captura de ecran din 2016 04 28 la 18 07 58](https://cloud.githubusercontent.com/assets/7076631/14894575/308dac5c-0d6c-11e6-9b61-b48708f6ba4b.png)

**Comment by JohnMica** [comment]
and I have to go to work - i guess i'll be back tomorrow (i'll try again and let you guys know what and how)

**Comment by w00fz** [comment]
Yes that is the issue and it's on our GPM repository, we were missing the `grav-update` package in the assets list for the betas. I have now fixed this so when you get the chance, try again the steps above (Check for Updates -> Try upgrading again) or via CLI like you did `self-upgrade -f -y`, and you should be good.

Sorry about that!

**Comment by JohnMica** [comment]
No worries Djamil 

I'll check tomorrow and let you know as soon as. 
It's nothing major just a possible issue :)

**Comment by JohnMica** [comment]
I've updated through CLI and all is working now.

**Comment by RojerGS** [comment]
I'm getting a very similar issue with upgrading Grav 1.6.28 to 1.6.29. 12 plugins wanted to update as well as Grav. When I hit "Update Grav Now" it gives me the "undefined index: grav-update" red notice. I could update 11 plugins individually, the only one that didn't update was the admin plugin because it says it depends on Grav being at 1.6.29.

Running `bin/gpm selfupgrade` and `bin/gpm selfupgrade -y -f` gives a similar error to the one above by JohnMica.

![Screenshot_1](https://user-images.githubusercontent.com/5621605/101108672-f847fd00-35cc-11eb-85d0-f067abbfbd5d.png)

I have been using Grav for quite some time now and been keeping it up to date with no problems whatsoever so far. This is the first time Grav doesn't update seamlessly.

**Comment by rhukster** [comment]
https://twitter.com/getgrav/status/1334626821749366785?s=21

**Comment by RojerGS** [comment]
> 
> 
> https://twitter.com/getgrav/status/1334626821749366785?s=21

Thanks, never would have thought about going to Twitter for news on Grav's status.

**Comment by rhukster** [comment]
Twitter will always be the fastest way we provide news, as it is basically a news feed... hopefully this will not take took long, but it's beyond our control at the moment.

**Comment by RojerGS** [comment]
Of course, I just never think about Twitter because I don't usually use it. Will sit tight, thanks for your diligence.

**Comment by w00fz** [comment]
Just for the records, we are good now!

**Comment by RojerGS** [comment]
@w00fz not on my end :/ From the admin plugin I get an "invalid AJAX response" and an "Error while trying to download (code: 302): https://getgrav.org/download/core/grav-update/1.6.29". Going to the link [https://getgrav.org/download/core/grav-update/1.6.29](https://getgrav.org/download/core/grav-update/1.6.29) returns a "Not Found" error.
From the CLI, using `bin/gpm`, I obviously get the same 302 error while trying to access [https://getgrav.org/download/core/grav-update/1.6.29](https://getgrav.org/download/core/grav-update/1.6.29).

**Comment by rhukster** [comment]
There was a problem with this release under PHP 7.1 and 7.2(https://github.com/getgrav/grav/issues/3089).  I've pulled the packages for now, and re-released. So just have to wait for packages to be rebuilt again (still slow).
