### ISSUE TITLE
Does not work add modular page validation

### ISSUE THREAD

**Issue by codev0** [getgrav/grav-plugin-admin#529]
Trying to add modular page from grav admin.
I fill all rows, but except for `Page *` field.
In console see this `pages:1 An invalid form control with name='route' is not focusable.`
And doesnt see validation error.
Link to user folder https://www.dropbox.com/s/ct5mc23sz62u89s/user.zip?dl=0

**Comment by rhukster** [comment]
Just for reference, this in regards to not populating the 'page' field of the new modular page modal.

**Comment by rhukster** [comment]
Fixed with this: https://github.com/getgrav/grav/commit/7463bad8dd6bfffafaed6a1ffe636c47054c91b0
