### ISSUE TITLE
Automatic Logout after Configuration Save

### ISSUE THREAD

**Issue by simmonsr** [getgrav/grav-plugin-admin#53]
Went into Configuration > Site. Changed the Site Title, hit Save. Tried to navigate elsewhere, but was automatically logged out.

**Comment by rhukster** [comment]
I can't replicate this, does it happen every time?

**Comment by simmonsr** [comment]
Yes, everytime. Change Site Title, Navigate to another part of the admin, I'm logged out.

**Comment by simmonsr** [comment]
Seems specific to changing the Site Title. Changing any other info under "Site" and then Saving and navigating elsewhere doesnt log me out.

**Comment by rhukster** [comment]
Ah yes, I can replicate that.  I know why too! The session is named based on the site title, so changing the title, causes a new session name, which effectively means you are logged out.  I can change it to use a random string rather than site name.  Will fix that issue.

**Comment by simmonsr** [comment]
Great! :) I would note that if I change the Site Title to something that I have previously used before as a site title, i also will not be logged out.
