### ISSUE TITLE
Changing language results in error

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav-plugin-admin#530]
I've updated the beta to the last one available.

Admin seems to be working fine until I decide to add a language ( ro ) disable the Include default language. at this moment upon saving the config, the error appears - 
![captura de ecran din 2016 04 29 la 03 44 02](https://cloud.githubusercontent.com/assets/7076631/14907229/874ebcba-0dbd-11e6-9faa-2afa85aff0f6.png)

array to string conversion 

I haven't touched any other files inside the system.yaml / admin, etc ...

My theme works, (based on antimatter), my .md seem to be rendered properly.

**Comment by flaviocopes** [comment]
Can you paste your `user/config/system.yaml` file?

**Comment by JohnMica** [comment]
`absolute_urls: false
timezone: ''
default_locale: null
param_sep: ':'
wrapped_site: false
reverse_proxy_setup: false
languages:
  supported: {  }
  include_default_lang: true
  translations: true
  translations_fallback: true
  session_store_active: false
  http_accept_language: false
  override_locale: false
home:
  alias: /acasa
  hide_in_urls: false
pages:
  theme: canabismedical
  order:
    by: default
    dir: asc
  list:
    count: 20
  dateformat:
    default: null
    short: 'jS M Y'
    long: 'F jS \a\t g:ia'
  publish_dates: true
  process:
    markdown: true
    twig: true
  twig_first: false
  events:
    page: true
    twig: true
  markdown:
    extra: true
    auto_line_breaks: false
    auto_url_links: false
    escape_markup: false
    special_chars:
      '>': gt
      '<': lt
  types:
    - txt
    - xml
    - html
    - htm
    - json
    - rss
    - atom
  append_url_extension: .html
  expires: 604800
  last_modified: false
  etag: false
  vary_accept_encoding: false
  redirect_default_route: false
  redirect_default_code: '301'
  redirect_trailing_slash: true
  ignore_files:
    - .DS_Store
  ignore_folders:
    - .git
    - .idea
  ignore_hidden: true
  url_taxonomy_filters: true
  frontmatter:
    process_twig: false
    ignore_fields:
      - form
  markdown_extra: true
cache:
  enabled: false
  check:
    method: file
  driver: auto
  prefix: g
  lifetime: 604800
  gzip: false
twig:
  cache: false
  debug: true
  auto_reload: true
  autoescape: false
  undefined_functions: true
  undefined_filters: true
  umask_fix: false
assets:
  css_pipeline: false
  css_pipeline_include_externals: true
  css_pipeline_before_excludes: true
  css_minify: true
  css_minify_windows: false
  css_rewrite: true
  js_pipeline: false
  js_pipeline_include_externals: true
  js_pipeline_before_excludes: true
  js_minify: true
  enable_asset_timestamp: false
  collections:
    jquery: 'system://assets/jquery/jquery-2.x.min.js'
errors:
  display: true
  log: true
debugger:
  enabled: true
  shutdown:
    close_connection: true
  twig: true
images:
  default_image_quality: 85
  cache_all: false
  cache_perms: '0755'
  debug: false
media:
  enable_media_timestamp: false
  upload_limit: 0
  unsupported_inline_types: {  }
  allowed_fallback_types: {  }
session:
  enabled: true
  timeout: 1800
  name: grav-site
  secure: false
  httponly: true
gpm:
  releases: testing
  proxy_url: null
`

**Comment by JohnMica** [comment]
```
absolute_urls: false
timezone: ''
default_locale: null
param_sep: ':'
wrapped_site: false
reverse_proxy_setup: false
languages:
  supported: {  }
  include_default_lang: true
  translations: true
  translations_fallback: true
  session_store_active: false
  http_accept_language: false
  override_locale: false
home:
  alias: /acasa
  hide_in_urls: false
pages:
  theme: canabismedical
  order:
    by: default
    dir: asc
  list:
    count: 20
  dateformat:
    default: null
    short: 'jS M Y'
    long: 'F jS \a\t g:ia'
  publish_dates: true
  process:
    markdown: true
    twig: true
  twig_first: false
  events:
    page: true
    twig: true
  markdown:
    extra: true
    auto_line_breaks: false
    auto_url_links: false
    escape_markup: false
    special_chars:
      '>': gt
      '<': lt
  types:
    - txt
    - xml
    - html
    - htm
    - json
    - rss
    - atom
  append_url_extension: .html
  expires: 604800
  last_modified: false
  etag: false
  vary_accept_encoding: false
  redirect_default_route: false
  redirect_default_code: '301'
  redirect_trailing_slash: true
  ignore_files:
    - .DS_Store
  ignore_folders:
    - .git
    - .idea
  ignore_hidden: true
  url_taxonomy_filters: true
  frontmatter:
    process_twig: false
    ignore_fields:
      - form
  markdown_extra: true
cache:
  enabled: false
  check:
    method: file
  driver: auto
  prefix: g
  lifetime: 604800
  gzip: false
twig:
  cache: false
  debug: true
  auto_reload: true
  autoescape: false
  undefined_functions: true
  undefined_filters: true
  umask_fix: false
assets:
  css_pipeline: false
  css_pipeline_include_externals: true
  css_pipeline_before_excludes: true
  css_minify: true
  css_minify_windows: false
  css_rewrite: true
  js_pipeline: false
  js_pipeline_include_externals: true
  js_pipeline_before_excludes: true
  js_minify: true
  enable_asset_timestamp: false
  collections:
    jquery: 'system://assets/jquery/jquery-2.x.min.js'
errors:
  display: true
  log: true
debugger:
  enabled: true
  shutdown:
    close_connection: true
  twig: true
images:
  default_image_quality: 85
  cache_all: false
  cache_perms: '0755'
  debug: false
media:
  enable_media_timestamp: false
  upload_limit: 0
  unsupported_inline_types: {  }
  allowed_fallback_types: {  }
session:
  enabled: true
  timeout: 1800
  name: grav-site
  secure: false
  httponly: true
gpm:
  releases: testing
  proxy_url: null
```

**Comment by JohnMica** [comment]
I find it different in that languages has the ``` supported {} ``` even if there is no language chosen. In previous versions the line of code was not present.

Or it could be a different config option as the error stars again with array to string conversion in dashboard-pages.twig.html

**Comment by flaviocopes** [comment]
I don't know what could set `supported: {  }`, never seen this property set as that.

Can't replicate the error btw, even with your system.yaml, I need the `user/` folder zipped. Send it to me via Gitter so I can try the whole thing.

**Comment by rhukster** [comment]
Change the supported to:

```
supported: []
```

I'm sure the white space between **mapping** tags `{` `}` is causing this problem.  The supported languages is expecting an array `[` `]`.  They are not the same.

**Comment by JohnMica** [comment]
I haven't put the {} to start with. They were added automatically ... Still strange that I can replicate this on my localhost all the time

**Comment by flaviocopes** [comment]
Been trying to replicate this, also on MAMP on OSX, but cannot recreate the issue
