### ISSUE TITLE
Default behavior installing plugins

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav-plugin-admin#531]
Hi guys,
not an issue per say but just a UI/UX related thing.

In the stable version, while on the plugin tab when I right click on the install button of a plugin and select open in new tab/page, the install command opens in the new tab/page and installs the particular plugin.

In the beta, right click on the install button and select open in new tab/page just opens the plugins page with no particular selection / command. 

Maybe you guys removed this ability of staying in the main plugin page and having the install run in a different tab/page ? 
hope it makes sense what I am trying to explain here.

**Comment by flaviocopes** [comment]
Yes, the installation procedure is now run inside a modal, JavaScript-based, as installation now is a bit more powerful as allows Plugins / Themes to declare dependencies. Also, packages in 1.1 can now halt the installation procedure if something is not right, and can show a message to explain what went wrong.

So, there's a lot more going on and we show the progress of the installation inside the modal.
