### ISSUE TITLE
Image gets inserted in all markdown fields

### ISSUE THREAD

**Issue by suntrop** [getgrav/grav-plugin-admin#532]
When I click the "Insert" link on an image (default "Page Media") the image is inserted in every markdown field of that page. At the very beginning of the field, not where the cursor was.

**Comment by flaviocopes** [comment]
Grav/Admin 1.1-beta or with the latest stable release?

**Comment by suntrop** [comment]
I tried an Auto-installer of my webhoster … it says it is  1.0.10

**Comment by flaviocopes** [comment]
Ok thanks! Both issues are already fixed in the next 1.1 release. Out soon!
