### ISSUE TITLE
Providing a real time page preview + autosave

### ISSUE THREAD

**Issue by q2apro** [getgrav/grav-plugin-admin#533]
I came across grav today and like the design and speed, good work. 

However, I would like to suggest to provide an alternative editor / editor preview such as http://slim-wiki.murfman.de/?edit (widescreen: left markdown, right result) - where you can see all edits updated after 1 second and where the file gets automatically saved after each edit.

**Comment by rhukster** [comment]
Thanks for your suggestion, and we did have this originally.  However, these system rely on JavaScript based markdown parsing to achieve these results.

Our preview is actually making an Ajax request to Grav to process the page.  This allows all our Grav markdown enhancements, and also potentially plugins, to be be processed properly.  The trade off is that while it's fast, it's no way near real time, and polling constantly every 1 second would be quite a lot of processing/traffic. 

One thing we are looking at is using [ProseMirror](https://prosemirror.net/) in the Pro Version of the admin plugin to provide a near WYSIYWG type editor.. although ProseMirror prefers to call it WYSIWYM (what you see is what you mean) :)

**Comment by q2apro** [comment]
ProseMirror is new to me. Interesting project, looking forward to your lovely implementation :)
