### ISSUE TITLE
Revision History for collaborative work (version history)

### ISSUE THREAD

**Issue by q2apro** [getgrav/grav-plugin-admin#534]
I would like to suggest to implement a revision history. 

I thought of using grav as a collaborative tool where multiple people can write on the same document and see the revision history of the document.

Then it would be nice to access this history either from the admin panel or even publicly.

**Comment by flaviocopes** [comment]
Admin has a revisions panel, which is enabled after you save a page twice. You can then compare page revisions and restore an older release.

I suggest to add the `user/` or `user/pages/` folder to a Git repository and use that to store the revisions of your content, if you want to show them publicly.

**Comment by rhukster** [comment]
We will endeavor to ensure the revision history is as flexible as possible in Admin PRO plugin, so it can be used in a variety of ways.  

Thanks for your suggestion!
