### ISSUE TITLE
Yes button wrong color

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#538]
Under Configuration>System, `Yes` buttons are green, except for `Display errors`. Is this intentional?

**Comment by rhukster** [comment]
That's not intentional.. it's a bug.  Will fix thanks.

**Comment by rhukster** [comment]
Actually this is not a bug.. The brighter color depicts the 'default state'.  The darker color means you have toggled the option, but this is not the default state.  So not a bug! :)
