### ISSUE TITLE
"Drop files here to upload" text not translated after changing user language.

### ISSUE THREAD

**Issue by RomainFallet** [getgrav/grav-plugin-admin#539]
Grav v1.1.0-beta.2 - Admin v1.1.0-beta.2 :
"Drop files here to upload" text not translated after changing user language.
I checked on [Crowdin](https://crowdin.com/translate/grav-admin/), there is no entry for this text.
![screenshot at mai 02 16-35-13](https://cloud.githubusercontent.com/assets/6952638/14957150/f90d233c-1083-11e6-9439-063c19b2eeaa.png)

**Comment by flaviocopes** [comment]
👍
