### ISSUE TITLE
"Publishing" text not translated after changing user language.

### ISSUE THREAD

**Issue by RomainFallet** [getgrav/grav-plugin-admin#540]
Grav v1.1.0-beta.2 - Admin v1.1.0-beta.2 :
"Publishing" text not translated after changing user language.
I checked on [Crowdin](https://crowdin.com/translate/grav-admin/), there is no entry for this text.
![screenshot at mai 02 16-43-55](https://cloud.githubusercontent.com/assets/6952638/14957368/4852831e-1085-11e6-8856-72b48f508d37.png)

**Comment by rhukster** [comment]
Fixed for 1.1b3
