### ISSUE TITLE
Placeholders barely readable in admin setup

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#542]
The placeholders against the dark background are barely readable.

Screenshot:
https://www.dropbox.com/s/wba7m7iz96gkvv5/admin-setup-placeholders.jpg?dl=0

**Comment by rhukster** [comment]
What version of Grav is this?

**Comment by Quy** [comment]
beta2

**Comment by rhukster** [comment]
Ok, I fixed placeholders most everywhere, maybe i missed this one page.

**Comment by rhukster** [comment]
![grav register admin user grav 2016-05-02 18-44-36](https://cloud.githubusercontent.com/assets/1084697/14972072/f6040748-1095-11e6-8e68-de87a3ccd7e6.png)

Should be better in next release.
