### ISSUE TITLE
Double tooltips in editor

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#544]
Hover over a button in the editor to display a standard tooltip and a custom tooltip.
Tested in Firefox and Chrome on Windows.

Screenshot:
https://www.dropbox.com/s/nm9l4g9zckpp0v2/double-tooltips.jpg?dl=0

**Comment by rhukster** [comment]
One is an "alt" tag, and one is a tooltip.. Alt tags generally don't show up unless you leave the mouse on the item for a few seconds, where as the tooltip shows up instantly.

**Comment by rhukster** [comment]
Actually it's not an alt tag, but it's displaying like one.. reopening to investigate.

**Comment by rhukster** [comment]
Should be sorted in develop branch
