### ISSUE TITLE
Pro version is very disappointing

### ISSUE THREAD

**Issue by oneleft** [getgrav/grav-plugin-admin#545]
You have created a very beautiful system here and I am disappointed that you will be handicapping an integral piece of that system unless a payment is made.  As a programmer myself, I understand the fiscal and time requirements which may require such a move.... but I think this particular move will cost you more in lower adoption rate than it will bring in revenue.  Suggestion: offer custom plugin creation services and managed installations while keeping the core and it's public plugins completely free.

Of course I am very happy with your software but limiting the admin plugin causes just enough question to allow for consideration of alternatives. .. at least for this IT manager.

**Comment by rhukster** [comment]
Well you are of course entitle to your opinion, but i'm not sure exactly what you have a problem with?    Grav core, and all it's plugins and themes are already completely free and will continue to remain so. So you must be 'disappointed' that we also want to create and charge for some commercial plugins...

We are going to continue to develop and improve plenty of "free" plugins, and the "Standard Admin Plugin" which is free is already quite powerful and flexible.  It's not in any way handicapped, in fact it has more functionality than any other open source flat-file CMS admin out there. 

We are going to add functions and features to the Pro versions that focus on the needs of professional developers delivering sites to clients.  These professionals are making money on building sites with Grav, and they can easily offset the small cost of the Pro admin if they need the features it offers.  The resounding sentiment from everyone so far has been extremely positive in this regard.  You are in a very small minority with your opinion i'm afraid.

We have been developing Grav 'gratis' for the past 2.5 years.  The development of Grav has cost hundreds of thousands of dollars in man hours.  I need for Grav to start earning it's keep, but as an open source project there are only a few payment models open to me.  I am not going to suddenly start charging for Grav, or for the 50+ plugins we have already written, nor the 20+ or so themes we have developed, all free.  Nor are we going to stop developing free plugins.  

We are merely going to develop some more complex new plugins that will cost a few dollars.  This is a standard model that is used for WordPress, Joomla, Drupal, Magento communities, basically every successful CMS.  We 'may' do some custom development in time, but that kind of work is very time intensive and will take our time away from working on the core of Grav.

**Comment by oneleft** [comment]
First, let me say thank you for your very thorough and quick response.  You have clearly thought about this decision alot more than myself.  I must say that I truly hope the future holds what you have laid out in response.  Thank you for all your hard work (you and all the grav contributors).
