### ISSUE TITLE
Styling issues Internet Explorer

### ISSUE THREAD

**Issue by dimayakovlev** [getgrav/grav-plugin-admin#55]
Tested with IE 11. Problems with dropdowns and inputs.
![Styling issues](https://cloud.githubusercontent.com/assets/8279974/9218606/72f87f48-40dc-11e5-960b-a0f218d32356.png)

**Comment by rhukster** [comment]
We've not really done any IE testing with the admin so far.  Right now I recommend using Chrome or Firefox.  We'll go through with an IE comb at some point, but later :)
