### ISSUE TITLE
"Add folder" text not translated after changing user language.

### ISSUE THREAD

**Issue by RomainFallet** [getgrav/grav-plugin-admin#550]
Grav v1.1.0-beta.2 - Admin v1.1.0-beta.2 :
On pages list, "Add folder" text is not translated after changing user language.
There is an entry for it in Crowdin : https://crowdin.com/translate/grav-admin/2/en-fr#q=Add+folder but seems to be unused.

![screenshot at mai 03 10-24-39](https://cloud.githubusercontent.com/assets/6952638/14978079/9a9005b8-1119-11e6-8977-f210e85756f2.png)

**Comment by flaviocopes** [comment]
The code looks fine, seems the translations were not pulled in the last beta 2, and that string was just recently added, so it's not in https://github.com/getgrav/grav-plugin-admin/blob/develop/languages/fr.yaml

**Comment by flaviocopes** [comment]
Thanks for reporting btw, better ask :) going through the other lang issues now
