### ISSUE TITLE
Pages are not visible by default after removing all existing pages.

### ISSUE THREAD

**Issue by RomainFallet** [getgrav/grav-plugin-admin#551]
Pages are not visible by default after removing all existing pages. It's a bit weird, even after forcing it to be visible in the Advanced tab.

Here is the video that shows the thing, I am starting from a fresh Grav installation :
https://www.youtube.com/watch?v=HzWS84FlwfY

**Comment by rhukster** [comment]
I 'think' this is related to the fact that you deleted the 'homepage', and then didn't add it back.  Perhaps after creating your test page, and then going to the system config, and setting your homepage to this, it would be visible.  Could you try that?

**Comment by RomainFallet** [comment]
When I go to the system config just after creating the test page, the "Home page" setting is already set with the test page. I tries to resave the config, but it does not change the visibility.
![screenshot at mai 03 17-00-50](https://cloud.githubusercontent.com/assets/6952638/14987699/dd26a774-1150-11e6-9226-f86525119984.png)

**Comment by rhukster** [comment]
What do the files actually look like after you recreate them?  Also when you create that new 'test' page, try setting **visible to Yes** rather than leaving it on **Auto** (in the new page modal)

**Comment by RomainFallet** [comment]
The page looks good, in admin panel and in the front (see screenshot 1 and 2), as well as my files system and in the page file (see screenshot 3 and 4). 

I deleted the test page to recreate it with the **visible setting set to Yes**. But the page is still marked as "Non-visible" (see screenshot 5).

![screenshot at mai 03 17-20-38](https://cloud.githubusercontent.com/assets/6952638/14988373/d615ff0e-1153-11e6-84f6-1bc91ef4c250.png)
![screenshot at mai 03 17-20-49](https://cloud.githubusercontent.com/assets/6952638/14988385/de1e6920-1153-11e6-851e-bc2770117f50.png)
![capture d ecran 2016-05-03 a 17 26 43](https://cloud.githubusercontent.com/assets/6952638/14988501/6720c646-1154-11e6-81f9-e1184f778777.png)
![capture d ecran 2016-05-03 a 17 27 01](https://cloud.githubusercontent.com/assets/6952638/14988505/6c0fae7e-1154-11e6-8b69-e0d2286c7a86.png)
![screenshot at mai 03 17-21-36](https://cloud.githubusercontent.com/assets/6952638/14988389/e153cc20-1153-11e6-8828-1514167d01d3.png)

**Comment by rhukster** [comment]
Ok, i've tested this, following your steps, and the page does show as visible for me if i override the visibility option, and also if i enable numeric prefix (which is the files way of doing things). 

The only minor issue I see is the modal option of visible didn't set it to visible on creation. This i'll take a look at.

**Comment by RomainFallet** [comment]
For me the biggest issue is that all new pages created on root after this are set as "non-visible" by default. Users should not have to check "visible" button for each new pages as this is not the default behavior. The auto setting should, as well as the visible setting, set pages to "visible" on creation.

**Comment by rhukster** [comment]
Should be fixed in develop
