### ISSUE TITLE
PreCache showing plugin status twice

### ISSUE THREAD

**Issue by barryanders** [getgrav/grav-plugin-admin#555]
Hey, was just checking out the Grav team's plugins and found when I installed PreCache, I had a block repeat itself. You probably already knew, but just in case, here's this. Found in Safari 9.1

![screen shot 2016-05-03 at 3 55 14 pm](https://cloud.githubusercontent.com/assets/5648875/14998068/98051864-1147-11e6-89ac-c541572fa98f.png)

**Comment by rhukster** [comment]
Turns out it's just a label bug in PreCache plugin blueprints.

**Comment by barryanders** [comment]
You're fast.
