### ISSUE TITLE
Plugin detail not displaying correctly in Safari

### ISSUE THREAD

**Issue by PSiAU** [getgrav/grav-plugin-admin#56]
The details area for plugins aren't displaying correctly in Safari 8 while they are for Chrome and Firefox.
Screenshot attached.
![voila_capture 2015-08-12_06-09-44_pm](https://cloud.githubusercontent.com/assets/2519639/9219380/e50d1080-411d-11e5-9009-f336a0809ecd.png)

**Comment by rhukster** [comment]
Pretty much untested in other browsers other than Chrome/Firefox at the moment.  I'll track this one, but please use Chrome or Firefox for now.

**Comment by PSiAU** [comment]
Will do. Thanks rhukster!
