### ISSUE TITLE
Display issues wih Plugin page

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#560]
Screenshot:
https://www.dropbox.com/s/qe6i5htmtnk8ryr/update-plugin.jpg?dl=0

`Update Plugin` button not on the same line as the `...is now available!"

Letters are close together with `test release` label in Windows Firefox.

Screenshot of the Login plugin when updating:
https://www.dropbox.com/s/6nso46wlyl4r366/login-plugin.jpg?dl=0

* Issue with styling on iPad
* no dependencies listed

**Comment by rhukster** [comment]
Pretty sure this has been fixed.  Can you test with the latest Grav Admin 1.1 beta?

**Comment by Quy** [comment]
Using beta3. I will not be able to test this until there is a plugin update.

**Comment by flaviocopes** [comment]
On it

**Comment by flaviocopes** [comment]
Fixed the presentation of the update modal. The two titles were at the same level. What it's meant to say is, the "form" dependency is already installed, but will be updated.

**Comment by rhukster** [comment]
Both of the issues here: https://www.dropbox.com/s/qe6i5htmtnk8ryr/update-plugin.jpg?dl=0

Were fixed in b2 i think, but definitely in b3.  You might of had JS/CSS cached though. Just tested and it's fine.
