### ISSUE TITLE
Sidebar should not automatically expand

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#562]
The sidebar is collapsed, however, clicking on a menu icon automatically expands the sidebar. The sidebar should remain collapsed until it is manually toggled. The opposite is happening on an iPad.

**Comment by rhukster** [comment]
What version of Grav? Please be specific as this has been revamped in 1.1

**Comment by Quy** [comment]
v1.1.0-beta.3

**Comment by rhukster** [comment]
Ok, well the sidebar is 'small' when space is limited (ie on your iPad), however, when you open the panel to perform an action, it overlays the content.  So when you perform an action and the page reloads, if it opened again, it would overlay again, forcing you to manually minimize.

Right now it goes back to minimized state just like a mobile menu would not be visible again after a page load until you needed it.  I'm not sure what the use case would be to keep the panel open, it would just get in the way.

**Comment by Quy** [comment]
OK. I understand for the iPad, but on desktop, it keeps expanding even though it should be minimized like the iPad when collapsed.

**Comment by rhukster** [comment]
on the desktop, it's expanded if there's a enough room.  You can minimize it to give yourself some more space.  You are correct, this state is not 'remembered' between page loads.  That is something that could be added.

**Comment by rhukster** [comment]
I'm just afarid t

**Comment by rhukster** [comment]
So i've added some options to the admin configuration:

![plugin admin panel grav 2016-05-06 16-44-53](https://cloud.githubusercontent.com/assets/1084697/15087826/df19d65e-13a9-11e6-84bd-cb97718a1b05.png)

This gives you more control and lets you have a small sidebar 'always' and a hover action to open it up.
