### ISSUE TITLE
saving a page deletes multilanguage versions

### ISSUE THREAD

**Issue by cord** [getgrav/grav-plugin-admin#57]
saving default.md deletes default.en.md

**Comment by flaviocopes** [comment]
Experienced the same thing.
On save from the admin it deletes the file of the language currently edited in the admin (e.g. default.en.md, or another lang file if the default lang file is another one), and saves it as default.md.

**Comment by rhukster** [comment]
FYI, multilang for admin has been under active development the last few days.  We should have pretty capable support in the next update.

**Comment by rhukster** [comment]
Great progress on this BTW, I think you will be pleased with the results :)

**Comment by rhukster** [comment]
Closing as this is fixed in develop branch.
