### ISSUE TITLE
Don't escape hint

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#570]
`<span class="hint--bottom" data-hint="Auto will use blueprint if available, if none found, it will use &amp;quot;Expert&amp;quot; mode.">Edit mode</span>`

`<span class="hint--bottom" data-hint="Show the &amp;quot;Found an issue? Please report it on GitHub.&amp;quot; message.">Show GitHub Link</span>`

**Comment by rhukster** [comment]
Can you give me examples of where these HTML based hints are showing up? I'm trying to find an example to test with and can't :(

**Comment by Quy** [comment]
Under Plugins > Admin Panel > Basics:
* Edit mode
* Show GitHub Link

**Comment by rhukster** [comment]
Fixed in develop
