### ISSUE TITLE
Don't expose email address in Send Reset Instructions

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#571]
This message is displayed with the email address. Email should not be exposed to prevent email harvesting.

`Instructions to reset your password have been sent via email to admin@test.com`

**Comment by rhukster** [comment]
I don't think this is a real security issue.  You would have to intercept the mail for it to make use of the information as you can't use email to login with.

**Comment by Quy** [comment]
But the email can be added to a spam list once exposed.

**Comment by pieplu** [comment]
Yes, maybe hide the email for robot reader would be good no?

**Comment by rhukster** [comment]
Fixing anyway!
