### ISSUE TITLE
Admin Panel UI - 'Page File' label?

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#573]
I am writing a one-sheet getting started guide for Grav, and I find the current 'Page File:' in the new page dialog requires additional explanation. In the Grav docs, etc. page template is much more often used to describe this concept.

What do you think of changing the field label 'Page File:' to 'Page Template:' in 1.1 to make things more self-explanatory?

Thanks very much,
Paul

**Comment by rhukster** [comment]
Might not be a bad idea, i'll take a look at this.

**Comment by paulhibbitts** [comment]
Thanks for considering this change Andy.

**Comment by rhukster** [comment]
Fixed in develop

**Comment by paulhibbitts** [comment]
Thank you!
