### ISSUE TITLE
Remove Plugin - Placeholders not substituted

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#574]
```
Remove the %s

Are you sure you want to delete this %s? 
```

**Comment by rhukster** [comment]
Placeholders are broken in latest beta release, should be fixed in develop.

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-admin/commit/79a49fdcbc98c2096d8319ddba8c9a77225f5d0b

**Comment by Quy** [comment]
Still broken in `develop` branch.

**Comment by rhukster** [comment]
Hmm.. where are those examples from? what page?

**Comment by Quy** [comment]
Under Plugins > Problems > Remove Plugin

**Comment by rhukster** [comment]
Ok should be fixed now
