### ISSUE TITLE
Escape username in alert of forgot password

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#577]
This may or may not be a security issue. Should the username be escaped?
`<div class="error alert">User with username <b>Test</b> does not exist</div>`

**Comment by rhukster** [comment]
escaped?

**Comment by Quy** [comment]
For the username, I can enter in <i>Test</i> for the username and it will be displayed italicized in the alert message.

**Comment by rhukster** [comment]
Fixed in repo.  Thanks.
