### ISSUE TITLE
Cannot see modular page content

### ISSUE THREAD

**Issue by wepawetmose** [getgrav/grav-plugin-admin#58]
I have a page structure like this 02.resources\_tutorials\_goodPractices. When I am on the admin area (see picture) I can see that items in the resources section can be expanded. But, by clicking to the plus sign nothing happens. Therefore I cannot edit content of those pages.
![modular](https://cloud.githubusercontent.com/assets/6286699/9224975/2165b5f0-410f-11e5-9469-6902f1739b65.PNG)

**Comment by rhukster** [comment]
can you zip up your entire `user/` folder and put it on dropbox/google/onedrive etc so i can use it for test data to reproduce/fix your issue

**Comment by rhukster** [comment]
This is probably a JS issue, so assigning to @w00fz :)

**Comment by w00fz** [comment]
Turned out to be a twig check that was preventing modular of modular to render.
This is now fixed and will be available in the next version. 

Good catch!
