### ISSUE TITLE
Invalid slug set in YAML frontmatter

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#580]
When entering a non-existent username in forgot/reset password:
`[2016-05-10 04:06:05] grav.NOTICE: Invalid slug set in YAML frontmatter:  =>  [] []`

**Comment by flaviocopes** [comment]
Cannot recreate, @rhukster can you?

**Comment by rhukster** [comment]
No This generally means that 'somewhere' you have some bad frontmatter.  However, it should output the page where this is occuring.. I'll keep this open so i can investigate that issue.

**Comment by Quy** [comment]
I did a clean install of beta4. Created the admin account. Immediately the `grav.log` file is created in the `logs` directory with this notice.

**Comment by rhukster** [comment]
Fixed with Grav core fix: https://github.com/getgrav/grav/commit/ad74446a89e4f3f428c7520abe8ef631e6e7072c
