### ISSUE TITLE
Layout: Editing a page in fullscreen is being overlapped on tablet

### ISSUE THREAD

**Issue by commodoor** [getgrav/grav-plugin-admin#586]
I got a small issue with the admin interface on the iPad. 

IOS 9.3: Safari/Chrome

When you go and edit an page on the iPad you can go fullscreen. When you do this the input field is being overlapped by the navigation view.

Added screenshot as example

![img_0119](https://cloud.githubusercontent.com/assets/224087/15183876/42ed7c98-1793-11e6-8a4c-2d719a499c03.PNG)

**Comment by w00fz** [comment]
This has been already fixed with 36412a5 (#566)
