### ISSUE TITLE
Error open plugin MediaEmbed

### ISSUE THREAD

**Issue by lauroguedes** [getgrav/grav-plugin-admin#591]
The following error appear when it open in the Admin Plugin Interface

_An exception has been thrown during the rendering of a template ("Array to string conversion") in "forms/fields/toggle/toggle.html.twig" at line 46._

**Comment by rhukster** [comment]
probably this should be opened on the MediaEmbed plugin as it's a problem with the blueprints there:

https://github.com/Sommerregen/grav-plugin-mediaembed/issues
