### ISSUE TITLE
Visual alignment of sidebar icons

### ISSUE THREAD

**Issue by Endogen** [getgrav/grav-plugin-admin#592]
I'm using Grav 1.1.0 beta 4 and i think that it looks a bit unprofessional if the sidebar is opened or closed while hovering with the mouse over the sidebar icons to show / hide the caption of the icons:
![grav sidebar](https://cloud.githubusercontent.com/assets/226475/15275130/6bc58074-1ac3-11e6-827c-d2f6c343f497.gif)
The vertical alignment of the Grav logo and the user icon is not in line. Any chance to get that changed?

**Comment by rhukster** [comment]
I've tweaked this so the avatar doesn't jump.   However, the logo is centered and will jump a little.  Doesn't look bad though.
