### ISSUE TITLE
ob_start(): output handler 'ob_gzhandler' conflicts with 'zlib output compression'

### ISSUE THREAD

**Issue by maofree** [getgrav/grav-plugin-admin#593]
Hi
after some tests I found a little bug when a enable the gzip option (going to another page I get this error). I install the grav system on my debian home server and that option can be used.

![1](https://cloud.githubusercontent.com/assets/653230/15277397/2e23d5b4-1b03-11e6-9a10-85c1dec59d8d.png)

bye

**Comment by flaviocopes** [comment]
The problem is the web server already has zlib enabled, which automatically compresses the page. 
Grav is told to use Gzip to compress it, so it would be compressed twice and this gives the error.

@rhukster could/should we detect this and just ignore compressing in such cases?

**Comment by maofree** [comment]
Hi Flavio
I use other cms like joomla and prestashop and when I enable the gzip I don't get any error
so if that is a problem when a compression is enabled like zlib the gzip couild be ignored.
Normally a site can be made on a local server than moved to the finally server so the configuration can be different, so there should be a bit of elasticity.

yesterday i got a problem when I try to install grav with composer into /mao/ folder nearly another manually installation of grav (before I've renamed its folder on /test/ from /mao/), so there were 2 installations into /test/ and /mao/ and all was ok.
when i removed the test folder I got some errors on mao's site because this system didn't find some files and I have ssen that it looked into /test/ folder. 
So I removed also mao folder, composer file, composer configuration files in the user folder,
but when I go to install a new grav with composer method I continue to get the same error about missing files, these files are present into /mao/ (I need to continue to use this name for the folder) but it looks into /test/ folder. (I made 4-5 new installations to solve these errors).
After these test the error.log of apache2 become 34GB.
At last I use again a manual installation and all is ok, I think when a site is made on a local server and then moved to the hosting server on a vps or shared solution where I can't use composer it is better to use a manual installation without composer.

what do you think?

**Comment by mahagr** [comment]
Joomla silently breaks if you have wrong settings; been fighting with it in the past.

**Comment by maofree** [comment]
I have some sites made with joomla on the same local server and if i enable gzip all is ok
bye

**Comment by flaviocopes** [comment]
I have replicated the problem on Apache when it's not using `php-fpm`. 

I have added a fix to avoid throwing such fatal error, but still run Grav when this happens. BUT currently even with that fix, gzip is not happening, the page is not compressed.

The quick solution now is to disable mod_deflate in Apache by setting `zlib.output_compression` to Off, and enable Grav's gzip.

Leaving this open as Grav should transparently handle this case.

**Comment by flaviocopes** [comment]
After a while inspecting this problem, currently the only way to solve this is (when using FastCGI or modiphp) to disable mod_deflate in apache (set `zlib.output_compression = Off` in your php.ini) and use Grav's gzip functionality.

With php-fpm, this problem does not appear.
