### ISSUE TITLE
problem with persian text in editor

### ISSUE THREAD

**Issue by alihaddadkar** [getgrav/grav-plugin-admin#594]
hello
I can't edit persian or arabic text. how to slove this problem?

**Comment by w00fz** [comment]
Although I do not speak or write any RTL language, I am able to use bidirectional text in the editor. We use CodeMirror for the editor which supports bidirectional text and RTL languages.

![edit home grav 2016-05-23 07-27-40](https://cloud.githubusercontent.com/assets/11734/15474080/f460ca70-20b7-11e6-87da-33f30f4b8d6f.png)

**Comment by alihaddadkar** [comment]
Now, i'm selected all paragraph but not highlight all text.
When i want select a word or one line, i have problem because, I can't select the word correctly.
Please use the following text in your text editor, you will understand what I mean.


لورم ایپسوم یا طرح‌نما (به انگلیسی: Lorem ipsum) به متنی آزمایشی و بی‌معنی در صنعت چاپ، صفحه‌آرایی و طراحی گرافیک گفته می‌شود. طراح گرافیک از این متن به عنوان عنصری از ترکیب بندی برای پر کردن صفحه و ارایه اولیه شکل ظاهری و کلی طرح سفارش گرفته شده استفاده می نماید، تا از نظر گرافیکی نشانگر چگونگی نوع و اندازه فونت و ظاهر متن باشد. معمولا طراحان گرافیک برای صفحه‌آرایی، نخست از متن‌های آزمایشی و بی‌معنی استفاده می‌کنند تا صرفا به مشتری یا صاحب کار خود نشان دهند که صفحه طراحی یا صفحه بندی شده بعد از اینکه متن در آن قرار گیرد چگونه به نظر می‌رسد و قلم‌ها و اندازه‌بندی‌ها چگونه در نظر گرفته شده‌است. از آنجایی که طراحان عموما نویسنده متن نیستند و وظیفه رعایت حق تکثیر متون را ندارند و در همان حال کار آنها به نوعی وابسته به متن می‌باشد آنها با استفاده از محتویات ساختگی، صفحه گرافیکی خود را صفحه‌آرایی می‌کنند تا مرحله طراحی و صفحه‌بندی را به پایان برند.


<img width="1272" alt="screen shot 2016-05-24 at 11 10 08 pm" src="https://cloud.githubusercontent.com/assets/6142279/15515840/430639dc-2205-11e6-834f-09c9ed125148.png">

**Comment by w00fz** [comment]
Yah I can see the selection is not working right. Unfortunately I am not quite sure how to deal with this, we are using [CodeMirror](https://codemirror.net/) which is said to be supporting RTL as well as bi-directional text but at a closer look at the CodeMirror repository, I can see a lot of other people struggling with it.

**Comment by alihaddadkar** [comment]
This problem has been reported too long to CodeMirror repository but unresolved.
Why don't you use another editor?
Check it out.
http://epiceditor.com/
