### ISSUE TITLE
Used fonts do not supports cyrillic characters

### ISSUE THREAD

**Issue by dimayakovlev** [getgrav/grav-plugin-admin#60]
![](https://cloud.githubusercontent.com/assets/8279974/9235236/1a7dc908-4146-11e5-81f0-2255cc9b497f.png)

**Comment by rhukster** [comment]
how should it look?

**Comment by dimayakovlev** [comment]
Cyrillic and Latin characters should look the same. As you can see they are different now.

**Comment by dimayakovlev** [comment]
There are no cyrillic characters in Montserrat and Lato fonts.

**Comment by rhukster** [comment]
Probably the best thing for now is to change this line in `admin/themes/grav/scss/template/_fonts.scss`:

```
@import url(//fonts.googleapis.com/css?family=Montserrat:400|Lato:300,400,700|Ubuntu+Mono:400,700);
```

Also you will need to update the `admin/themes/grav/scss/configuration/template/_typography.scss`:

```
$font-family-default:  			"Lato", "Helvetica", "Tahoma", "Geneva", "Arial", sans-serif;
$font-family-header:  			"Montserrat", "Helvetica", "Tahoma", "Geneva", "Arial", sans-serif;
```
And recompile the scss.  

Currently there is no easy way to dynamically change the font family as it would require recompiling the scss on-the-fly.
