### ISSUE TITLE
Custom templates not "sticking"

### ISSUE THREAD

**Issue by abelafonte** [getgrav/grav-plugin-admin#603]
I have a template that I want to assign to a few pages so I assigned the template in these pages' frontmatter.  

However, after moving around in the admin for a little bit, I notice that the template suddenly won't stay selected...even when manually assigned in the admin field.  After save, "Default" will be defaulted again.

Is there anything that would cause this to happen?

**Comment by rhukster** [comment]
This is a known issue in 1.0.10. It should be fixed in latest 1.1 beta. Can you try that?

**Comment by abelafonte** [comment]
Definitely! Is that a manual upgrade?

**Comment by rhukster** [comment]
Yes for now.  I suggest installing it in parallel and then copy your user folder over. Then update plugins via gpm or admin.

**Comment by abelafonte** [comment]
Found all the details about the beta.  I just copied my user folder over and replaced everything since this is all a test build (for now).  I locked my progress away in a Git commit. (The main reason why I'm trying out flat file CMSes!)

**Comment by rhukster** [comment]
Yah one of the man benefits of Grav is that everything you do is in `user/` so just copying over user folder is really all you need!

**Comment by abelafonte** [comment]
This works as expected now.  I notice that it's no longer a dropdown menu, but that's not a problem for me. Thanks!
