### ISSUE TITLE
Allowed memory size exhausted

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#604]
Clean local installation using XAMPP.
Installed `Bones Vanilla` theme.
Go to `Pages`.
Click `Home` page.
White screen is displayed on admin side. OK on public side.

In the php error log:
`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 8192 bytes) in C:\xampp\htdocs\grav-develop\vendor\rockettheme\toolbox\File\src\File.php on line 254`

Sorry if this is in the wrong branch/repo.

**Comment by rhukster** [comment]
Does this happen with other skeletons / default grav on this XAMPP setup, or is it only specific to Bone Vanilla ???

**Comment by Quy** [comment]
This one so far with this issue. I have installed default grav / skeletons but not all of the them yet to test.

**Comment by rhukster** [comment]
Fixed this in develop. Was a blueprint issue with bones.
