### ISSUE TITLE
Two big questions about Grav features

### ISSUE THREAD

**Issue by abelafonte** [getgrav/grav-plugin-admin#605]
Really liking Grav so far...

A few questions:
1) is it possible to use pagemediaselect in a way that gives you access to the primary assets folder (not just the document's media stack)?

2) Is it possible to create new "document types" other than pages so that you have a new section in the sidebar for other document groups? This is currently a big part of my development style, as I don't like to have tons of groups of documents buried in nested pages if I don't have to.

**Comment by flaviocopes** [comment]
Hi, 1) no that field is specific to select the media of the page. Also, the root `/assets` folder is a Grav-reserved folder, where Grav stores its own cache-generated images. You should store your assets either in the theme, or in a page. You can also have a general page, called /images for example, which you just use to store images.

2) Currently this is not possible. That's something that might be nice though, could be in the future implemented by plugins that define their own page types, and decide to exclude them from the main Pages view, and provide their own view to manage them.

**Comment by abelafonte** [comment]
Thanks for the info.  As far as the assets folders go, how would I give admin fields access to a theme-level assets folder? I tried to use the 'file upload' field, but the system tells me that it's reserved for plugins.

**Comment by rhukster** [comment]
I'm working Ina PR that greatly improves file upload feature. But a theme destination would be useful.

**Comment by rhukster** [comment]
This PR has now been merged.  We'll update the docs after 1.1 is released.

https://github.com/getgrav/grav-plugin-admin/pull/617
