### ISSUE TITLE
Add close button to the `Theme removed successfully` modal

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#609]
There isn't a `Close` button to dismiss the `Theme removed successfully` modal. You have to click outside of the modal to close it.

**Comment by Quy** [comment]
Checking to see if `Theme removed successfully` displaying twice is intentional.

**Comment by flaviocopes** [comment]
Fixed in https://github.com/getgrav/grav-plugin-admin/commit/f810199b6cbffd917baa3a2db54103ee8d359477
