### ISSUE TITLE
Problem with deleting pages via admin plugin

### ISSUE THREAD

**Issue by dawidxt** [getgrav/grav-plugin-admin#61]
Hi, like in the title. After updating admin plugin from 35 to 36 and from 36 to 37 I am having an issue with deleting pages. I can't delete pages via the "X" button on main pages ( /admin/pages ). It redirects me to blank page that I can fill and the title is "Create 'Taskdelete'.

I just found out that after going to details of each page and deleting it from there just works fine.

**Comment by rhukster** [comment]
Yup, this has already been fixed in develop.  Thanks though!
