### ISSUE TITLE
UI enhancements suggestions for editing pages in Admin plugin

### ISSUE THREAD

**Issue by corinroyal** [getgrav/grav-plugin-admin#610]
As much as I adore the Admin plugin, I'm frustrated with editing pages, mostly the YAML frontmater in Expert mode. Here's some issues:

-  Text is tiny on a desktop screen, and not adjustable
- When the frontmater box is opened wider, the bottom lines  of the text is hidden until moused over. 
-  Lots of text is grey or low-contrast which makes seeing it hard. Grey body text is a serious offence against usability. 
-  Text in the frontmatter box doesn't wrap. Horizontal scrolling in the edit boxes should not be necessary. 
-  The frontmatter edit box defaults to a very short writing area. It's resizable to see everything, but since I've already entered Expert mode, I expect not to have to. Also, every time you re-load the page it goes back to skinny. This makes editing YAML frontmatter highly annoying. 

As a developer I can just edit the files directly, but my users are having problems, and one of the draws to Grav is a comfortable editing experience for non-technical users.

**Comment by rhukster** [comment]
Have you tried the admin beta?  We totally rewrote how the YAML frontmatter looks.. It uses codemirror now.

**Comment by corinroyal** [comment]
Oooh! I haven't tried it, but I will and let you know if any of these problems remain. Thanks for all your amazing work!
