### ISSUE TITLE
Disallow uninstalling error and problems plugins

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#613]
Per this commit a79cc6e487c8b3f5dc1405276053080ba0645131, `error` and `problems` plugins should not be uninstalled. If yes, remove `Remove plugin` button from the respective plugin pages and remove `Plugin status` option.

**Comment by rhukster** [comment]
Problems is not required in general, Probably should not be in this list.

**Comment by Quy** [comment]
Per the [Problems' Readme](https://github.com/getgrav/grav-plugin-problems/blob/master/README.md), it is required.
