### ISSUE TITLE
Saving new 'Parent' page

### ISSUE THREAD

**Issue by mr910** [getgrav/grav-plugin-admin#618]
Changing or adjusting the parent page after it has been set does not seem to work. I made a child page and could not change the parent through normal methods.

**Comment by rhukster** [comment]
Which version of Grav and Admin?

**Comment by mr910** [comment]
Current Version: 1.0.10

**Comment by flaviocopes** [comment]
@mr910 do you have a chance to test this on Grav+Admin 1.1 beta (https://getgrav.org/downloads)?  

What is the problem, you select a new parent, save the page, but the page is not moved?

**Comment by mr910** [comment]
@flaviocopes : I have a chance. Ran into an issue when switching themed - Runtime Exception. Does that need fixing before I try the beta?

**Comment by flaviocopes** [comment]
Not sure if it's related. What was the full error message of that exception? Could simply be that theme not supporting a page template used?

**Comment by blurkness** [comment]
I'm posting here because maybe it's related. The Expert mode doesn't keep the parent option.

To test the issue:
1. Create new page
2. Change the parent option to become child of any page
3. Move to Expert mode
4. Now parent option is root

I'm using 1.1.0-RC.1

**Comment by rhukster** [comment]
You didn't save between changing and switching to expert?  Any changes you make while in 'normal' mode will be lost when you change to expert, because it reloads the page with no saving first.  We could add a notice to warn about this when toggling normal/expert I guess.

**Comment by blurkness** [comment]
@rhukster yes and after that saving or not in expert mode the parent option return to root

**Comment by rhukster** [comment]
I'm not able to replicate that @blurkness 

I created a new page, left parent as root as it is by default, then simply changed parent to a subfolder, hit save.  And parent was still the subfolder. Clicked expert, still the correct subfolder.  Changed it back to root. Clicked save, shows correctly as root.

**Comment by flaviocopes** [comment]
@blurkness was most probably related to using a custom slug in the page? Can you test again with the latest 1.1 RC releases? Should be solved already.

@mr910 when you get a chance to reply, also test the latest RC and reopen if you got the issue again.
