### ISSUE TITLE
Problem with deleting some plugins via admin plugin

### ISSUE THREAD

**Issue by dawidxt** [getgrav/grav-plugin-admin#62]
I am having issues while I am trying to delete plugin "Smileys v1.1.0". It says "Cannot delete non-existing folder.". Perhaps this issue still remains in few other plugins. I'm not sure from what version is appeared, but I am having this issue on the lastest one 37 with admin plugin 3.0.

**Comment by rhukster** [comment]
This is a bug we've already fixed in develop branch.  Thanks!
