### ISSUE TITLE
 Missing package name when installing a plugin

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#620]
Installing `HTTP Basic Authentication` while there is an update for `Login` .
```
The following dependencies need to be fulfilled first:

Packages not installed:

Packages already installed, and version is ok, but will be updated to keep you up to date:

    Login, from v2.0.0-beta.2 to v2.0.0-beta.3
```

**Comment by rhukster** [comment]
Not sure what Quy means here, so i'm hoping you know @flaviocopes

**Comment by Quy** [comment]
Under `Packages not installed:`, it is missing the package name.

**Comment by flaviocopes** [comment]
Should be solved already. Is this latest develop or the latest published 1.1 beta?

**Comment by Quy** [comment]
Using the latest develop.

**Comment by Quy** [comment]
It is also happening with `Gravstrap` plugin when installing from the `Plugins` list page.
```
Installing

The following dependencies need to be fulfilled first:

Packages not installed:

    shortcode-core

Packages already installed, and version is ok, but will be updated to keep you up to date:
```

**Comment by flaviocopes** [comment]
Not able to reproduce any more with the latest 1.1 RC

**Comment by Quy** [comment]
To reproduce, go to the detailed page of the `Gravstrap` plugin. Click the `Install Plugin` button.

**Comment by flaviocopes** [comment]
Been trying again to replicate, but no way
