### ISSUE TITLE
Fix a language string in French

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#621]
Under Pages > Advanced:
`Append URL extension` is displayed like this In French: `..twig".">Ajouter l'extension à l'URL`

`  APPEND_URL_EXT_HELP: |-
    Ajoutera une extension personnalisée à l'URL de la page. Remarque : cela implique que Grav va rechercher le template d'affichage "<template>.<extension>.twig".`

**Comment by rhukster** [comment]
For language fixes, please just fix directly, or propose a fix via Crowdin:  https://crowdin.com/translate/grav-admin/2/en-fr

**Comment by Quy** [comment]
On second thought, is it a language string issue?  Here is the source code. Notice `<template><extension>
```
<span class="hint--bottom" data-hint="Ajoutera une extension personnalisée à l'URL de la page. Remarque : cela implique que Grav va rechercher le template d'affichage "<template>.<extension>.twig".">Ajouter l'extension à l'URL</span>
```

**Comment by rhukster** [comment]
This is how it looks in english and this is correct:

![edit future post grav 2016-05-26 22-37-09](https://cloud.githubusercontent.com/assets/1084697/15597933/6cd65088-2392-11e6-9796-1dbda7fe0d85.png)

Like i said before, an image can really get to the heart of the matter quicker than just text.

**Comment by Quy** [comment]
Switch to `Français` language. Go to a page. Under Advanced tab, scroll to the bottom. `Append URL extension` is displayed as: `..twig".">Ajouter l'extension à l'URL`

**Comment by rhukster** [comment]
Then it might well be a translation error. The lang string is output the same for every language.

**Comment by MATsxm** [comment]
@Quy like @rhukster said, it was a t9n issue and was already fixed on Crowdin 16 days ago (will appear next time the fr file will be updated).

In fact, the issue was related to the Tooltip. We have an issue on the way to escape the double quotes (I'm testing few fixes).

Thanks for the ping ;)

**Comment by flaviocopes** [comment]
Ah I was just checking this, noticed it's already fixed in the translation, but not merged yet! 👍 @MATsxm
