### ISSUE TITLE
[ question ] Why the WYSIWYG don't have more options

### ISSUE THREAD

**Issue by dawidxt** [getgrav/grav-plugin-admin#63]
Hi, I just came by with a question... why the WYSIWYG used in admin plugin don't have for example < h1 > < h2 > < h3 >, also it doesn't have centering or floating. Are You planning to add such options into it ?

**Comment by rhukster** [comment]
We will probably add some more toolbar buttons for useful things.  Also we plan on having a mechanism for a plugin to register it's own buttons.  So you could create a plugin that adds whatever custom buttons you want

**Comment by dawidxt** [comment]
nice to hear it. Love Your CMS becasue it grows very fast. Sometimes there is no a week without update which is pretty nice.
