### ISSUE TITLE
Tab body too small. Results in overlap.

### ISSUE THREAD

**Issue by lucasdon** [getgrav/grav-plugin-admin#631]
Entering a large amount of information, (e.g. a long list of images via the gallery-plugin drag-n-drop interface) leads to an overlap of content an tab. 
This results in not selectable and unusable Tabs.

I found out that in` template.css` the `.tab-body` has a `postion-top` of `-9999px`. This is far to small when entering much information. I changed the value to `-999999px` and I don't have any issues so far. Although it seems to slow down things a bit. I think there are some animations (?) that don't look smooth with such a large position movement.
Perhaps it would be better to move the position to left or right instead of top? So a long content-form wouldn't be such a problem.

*edit* I mean the tabs on page-content editing pages. Although I think this might occur on other pages as well.

**Comment by rhukster** [comment]
Already fixed in develop branch.
