### ISSUE TITLE
pagemediaselect Issue

### ISSUE THREAD

**Issue by ChrisRiddell** [getgrav/grav-plugin-admin#636]
Hello,

When you delete an image from a page that is using said image in a pagemediaselect field it delete's all the inputed data.

Grav 1.1RC1

eg:

edit \user\themes\antimatter\blueprints\modular\features.yml adding the following to the last fields:

```markdown
.img:
    type: pagemediaselect
    label: file
```

edit user\themes\antimatter\templates\modular\features.html.twig adding the following under feature.text if statement

```html
{% if feature.img %}
  <img src="{{ page.media[feature.img].url }}">
{% endif %}
```

clear caches then in the admin edit the features page and add an image click Features tab and for the first item in the file drop down select that image you just uploaded then save, go back to the content tab and delete the image, the image is still on the file system but all the Features items will be gone.

**Comment by rhukster** [comment]
Aside from the use of `pagemedia` field which you shouldn't be using (as mentioned above), there was a legit issue that snuck into RC1 that is now fixed: https://github.com/getgrav/grav-plugin-admin/commit/719ce4331c5fb10c7b9af544da776d94ae2f617d

This is probably what you were seeing with things being wiped out.

**Comment by ChrisRiddell** [comment]
@rhukster  I followed https://learn.getgrav.org/forms/blueprints/how-to-add-file-upload

done something like 

```yml
.img:
    type: file
    label: file upload
    destination: 'user/themes/antimatter/assets'
    blueprint: 'themes.antimatter'
    accept:
        - image/*
```

I got the upload box on each item but when you upload an image then click save the page reloads and the image is not there would this be a bug or because the documentation has not been updated to reflect 1.1 yet?

**Comment by rhukster** [comment]
I've reopened this to test file in a list

**Comment by ChrisRiddell** [comment]
Not sure if this means anything but in the logs there is this

[2016-06-03 07:53:58] grav.NOTICE: Invalid slug set in YAML frontmatter: /home/_features => _features [] []

**Comment by rhukster** [comment]
Ok tested neither `pagemedia` nor `files` is going to work in a list.  This is because of the dynamic nature of lists.  I'm thinking i might be able to refactor how we process files on save to handle this, but it's a pretty big change for files, and will take some time.  Going to close this and open up  a new issue to cover that.
