### ISSUE TITLE
Minor incorrect visual cue re: pointer RC 1

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#637]
When hovering over the left side of a page that has child pages on the "Pages" panel, the cursor turns into a text insert pointer instead of a hand indicating that the circle icon can be clicked to expand/collapse child pages:
![pointer](https://cloud.githubusercontent.com/assets/1812771/15747245/bb8cd480-288e-11e6-90ff-f1e3b076f2d3.png)

I know this is minor, but I was hoping to see it fixed in 1.1.

Thanks very much,
Paul

**Comment by rhukster** [comment]
Minor Susie's are good too! They are usually very easy to fix. :)

**Comment by paulhibbitts** [comment]
Thanks :-) Also, I notice with RC1 there is no longer info on the page (visibility, etc.) when you hover - is that intentional?

That is, this seems to be no longer happening (which was very helpful):
![hover](https://cloud.githubusercontent.com/assets/1812771/15751183/0c551742-289e-11e6-8838-445bebc61a78.png)

Thanks very much,
Paul

**Comment by rhukster** [comment]
If you mouse over the "Home" it will show.. this was a usability improvement.

**Comment by paulhibbitts** [comment]
👍

**Comment by paulhibbitts** [comment]
One thing to consider though is when users are trying to figure out the meanings of the colored circles they are more likely to hover over the circle itself looking for a tooltip to help them. Just my 2 cents ☺

**Comment by rhukster** [comment]
Well that was the original idea, however, it does get a bit weird when that circle is also the open/close button.
