### ISSUE TITLE
File managment

### ISSUE THREAD

**Issue by dimayakovlev** [getgrav/grav-plugin-admin#64]
Admin plugin is very cool. But it lacks file managment feature (upload, rename, delete, move files, etc).

**Comment by dawidxt** [comment]
yep, I wrote about this in blog. Nice You put it here.

**Comment by rhukster** [comment]
There is **per-page** file upload management already.  You can drag and drop files to upload them.  You can delete them from there also. 

A more full-featured file manager is something we were thinking of adding in the pro version of the plugin as it's quite a big feature and not essential for general use.
