### ISSUE TITLE
Newly installed theme doesn't shows in Admin interface

### ISSUE THREAD

**Issue by artecnico** [getgrav/grav-plugin-admin#643]
I've a fresh install of GRAV 1.1.0-rc.1 with AdminPanel plugin v1.1.0-rc.2.
I've installed several themes without issues, but when I installed the big-picture theme it doesn't show on the list of themes. Then I tried to install it through GPM:
bin/gpm install big-picture
Then it says that the theme is already installed, so I select "Overwrite" and it finishes the install successfully. But the theme isn't show in the Admin panel (even after clearing all the cache).

**Comment by flaviocopes** [comment]
It's because of a problem in the theme. The file bigpicture.yaml should be named big-picture.yaml. Reporting to the developer.
