### ISSUE TITLE
UI broken with IE11

### ISSUE THREAD

**Issue by lepigocher** [getgrav/grav-plugin-admin#644]
Hello,

With the last beta (v1.1.0 rc1), the user interface is broken with IE11, I tried with an upgraded install and with a fresh one. Of course, all caches from GRAV and the browser have be cleanned!
Moreover, there is no error in the console. The same instance works perfectly with FF and GC.

You can have a look: 
![grav-admin](https://cloud.githubusercontent.com/assets/3307731/15782018/ebdcebd2-29a8-11e6-86ae-de69de3ea26d.PNG)

I have no idea why this do not works! :-(

**Comment by rhukster** [comment]
Ok i've replicated.  I 'might' have a possible solution. Just need to check with @w00fz on it first.

**Comment by lepigocher** [comment]
Great news, but slow down a little it's the week-end! :-)

**Comment by rhukster** [comment]
weekend is tomorrow :) fixed in develop.

**Comment by lepigocher** [comment]
Have a nice weekend! Thank you
