### ISSUE TITLE
Different scale for Statistic panel with GC and FF

### ISSUE THREAD

**Issue by lepigocher** [getgrav/grav-plugin-admin#645]
Hello,

While looking at the last beta (v1.1.0 rc1), I have found that the scale for the Statistic panel is not the same with FF and GC. That's not a big deal probably just a settings to define in the chart!?

Here a screen capture:
![adminstatsscale](https://cloud.githubusercontent.com/assets/3307731/15782496/dc16278e-29aa-11e6-9e87-ebbeec45d3bf.jpg)

**Comment by flaviocopes** [comment]
I believe this is intentional to workaround a bug in older versions of Firefox, as I saw some firefox-specific code in app/dashboard/chart.js, @w00fz confirm?

**Comment by w00fz** [comment]
Yes, the sizes of the charts are different between Firefox and everything else to work around a bug in the svg renderer of Firefox. 
That triggers Chartjs to render the scale differently and accordingly to those sizes. The scale is dynamically built, doesn't come from us.

**Comment by lepigocher** [comment]
Ok thanks, should I close the issue?

**Comment by w00fz** [comment]
Sure, thanks!
