### ISSUE TITLE
No possibility to change user avatar via admin plugin

### ISSUE THREAD

**Issue by dawidxt** [getgrav/grav-plugin-admin#65]
I guess the title says all. There is an avatar visible in the admin plugin, but I can't find a way to change it, of course there is a change to do it replacing it via ftp, but I guess that's not the point using admin plugin.

**Comment by flaviocopes** [comment]
The avatar is provided by gravatar.com, so you need to change the avatar associated with your email there.

**Comment by dawidxt** [comment]
uhum... I didn't know that. Thank You
