### ISSUE TITLE
Issue when having template name that contains uppercase letters

### ISSUE THREAD

**Issue by Kasparsu** [getgrav/grav-plugin-admin#656]
When creating a page with template that has uppercase letters it hooks in nicely to it and its blueprint, but as soon as I save it it converts it to lowercase and obviously as it can't find lowercase version it turns to default template. It seems that it has no need to do that So I tracked it down to this line. So is this tolowercase() really neccecary. I removed it and nothing uppercase templates started to work. 
[https://github.com/getgrav/grav-plugin-admin/blob/develop/classes/controller.php#L2166](https://github.com/getgrav/grav-plugin-admin/blob/develop/classes/controller.php#L2166 )

**Comment by flaviocopes** [comment]
@rhukster is this something we want to support?

**Comment by rhukster** [comment]
I think it's safer if we officially say template names should be in lower case.

**Comment by flaviocopes** [comment]
Added to the docs

**Comment by flaviocopes** [comment]
https://github.com/getgrav/grav-learn/commit/faf7b3ba6eb179212b7c52ca35fef410943ee59f
