### ISSUE TITLE
Error while updating antimatter theme

### ISSUE THREAD

**Issue by tsipos** [getgrav/grav-plugin-admin#658]
I triet to update antimatter theme and this error showed and update failed.
![graverror](https://cloud.githubusercontent.com/assets/17762107/15901177/836fb09a-2da2-11e6-9565-f187075f35fd.png)

Running Grav v1.1.0-rc.1 - Admin v1.1.0-rc.2 on localhost (wamp server with apache 2.4.9 on windows 10 machine)

**Comment by flaviocopes** [comment]
Can you open the devtools while doing so? The network panel should show a error request. (I am familiar with Chrome), should look like:

![screen shot 2016-06-09 at 12 36 43](https://cloud.githubusercontent.com/assets/11783388/15926933/e343e5bc-2e3e-11e6-903b-c9fe92784a4c.png)


What is the content of the request tab for that failed request?

![screen shot 2016-06-09 at 12 36 54](https://cloud.githubusercontent.com/assets/11783388/15926934/e5a05368-2e3e-11e6-8fef-32b9ecef2530.png)

**Comment by flaviocopes** [comment]
No issues with updating it. Can you install any new theme? Does it work?

**Comment by blurkness** [comment]
I tried both. Update antimatter and install new themes and both of them just appear the overlay modal saying "Updating" or "Installing" but with no requests in network tab and no JS error or anything in console.

I'll try to debug deeper.

**Comment by tsipos** [comment]
I got the same error while trying to update grav to rc2. Update did not finish. Screenshot:
![graverror2](https://cloud.githubusercontent.com/assets/17762107/16143774/347b27fc-346f-11e6-8a53-736d732ffb8d.png)

**Comment by tsipos** [comment]
I tried clean install of grav rc2 and problems are fixed. everything is working

**Comment by tsipos** [comment]
Error happened again :cry: Tried cleaning cache on grav rc2
![graverror3](https://cloud.githubusercontent.com/assets/17762107/16144936/67875812-3476-11e6-90d3-b7e42845e55d.png)

**Comment by tsipos** [comment]
I found that the problem only happens, when i change ```Parameter separator``` in configuration. When i change it to ```; (for apache running on win)```, i get JSON errors when cleaning cache, changing themes, saving pages, etc... When separator is set to default ``` : ```, everything is ok.

**Comment by flaviocopes** [comment]
This is weird. Apache running on Windows is not supposed to work with the colon in the request. That's why Grav tells to use a semicolon instead. BUT your specific Apache implementation might not work with `;`, and work with `:`. Need to test it out, but if it works for you, it should work also in other windows setups.

**Comment by tsipos** [comment]
Sorry for misunderstanding, i meant that when i set separator to ```:```, I am not getting JSON errors, but parameters like pagination are not working, of course. When I set separator to ```;```, parameters are working, but when i try to do anything related with javascript in admin panel, like save page content, change theme, clear cache, etc..., i get JSON errors.

**Comment by flaviocopes** [comment]
I'm on this today, I've replicated the issue and I'm looking for a fix. Keeping you posted.

**Comment by flaviocopes** [comment]
Looks like a recent issue. Part of the fix is in Grav https://github.com/getgrav/grav/commit/1bf4428752f89ec08fef8a8a093a845af9342e1a

**Comment by flaviocopes** [comment]
Took me a while to find out. Using `;` should work fine now.

**Comment by tsipos** [comment]
thank you @flaviocopes, it looks like everything is working :+1:
