### ISSUE TITLE
Clicking (x) on a page does not delete it

### ISSUE THREAD

**Issue by brettdewoody** [getgrav/grav-plugin-admin#66]
Clicking the (x) icon when on the `/pages` view brings up the confirmation dialogue. Clicking continue redirects to a 'Create Taskdelete' view, with an empty page form. 

Returning to `/pages` shows the page still there.

**Comment by simmonsr** [comment]
Hello Brett,

Thank you for reporting.

This has been fixed in the current repo:

https://github.com/getgrav/grav-plugin-admin

**Comment by brettdewoody** [comment]
Awesome, I figured someone would catch it fast.
