### ISSUE TITLE
Is that possible to add more control on Grav-Admin?

### ISSUE THREAD

**Issue by benyaminl** [getgrav/grav-plugin-admin#661]
I want make a plugins that works with grav admin, I mean only for backend, Is that possible?

**Comment by rhukster** [comment]
Yes, the admin plugin itself is an admin-only plugin.  You can just check if `$this->isAdmin()` in the plugin to ensure you are running only in the admin side.

**Comment by flaviocopes** [comment]
You can check how "Comments" and "Data manager" hook into the Admin sidebar to provide their own custom panel.

**Comment by benyaminl** [comment]
@flaviocopes anyway, where's that code? I want to see it, but I'm round and Round found nothing :cry:

**Comment by flaviocopes** [comment]
See https://github.com/getgrav/grav-plugin-comments/blob/develop/comments.php#L357-L363
