### ISSUE TITLE
Invalid Security Token when uploading a file

### ISSUE THREAD

**Issue by ebonyclock** [getgrav/grav-plugin-admin#662]
I have uploaded one zip file via page media ...bar (?) and it was ok. When I try to upload a second one ~14 Mb an error pops up at the end of uploading:
"An error occurred while trying to upload the file cig_example.zip
Invalid Security Token"

**Comment by rhukster** [comment]
I 'think' that maybe the error is related to the size of your file being to large for PHP to handle (check your php.ini for max file size), and the error is just being masked by this invalid security token  error.  Can you confirm that this doesn't happen for smaller files, or confirm what your max upload file size is?

**Comment by ebonyclock** [comment]
Yes, that was the issue. Admin set the limit to 10mb ... Sorry for my webdev illiteracy and thanks for help.

**Comment by rhukster** [comment]
I actually want to keep this open as we should report this error rather than the fallback security token message.

**Comment by ebonyclock** [comment]
Sorry then. As for the security tokens I often get the message about security tokens when I save a page after long time of doing nothing.

**Comment by rhukster** [comment]
BTW, i think this process has already been improved for Grav 1.1:

![edit home grav 2016-06-12 21-37-16](https://cloud.githubusercontent.com/assets/1084697/15993688/e2beac2c-30e5-11e6-8b48-6f99375854e9.png)

So closing after all!

**Comment by rhukster** [comment]
BTW you might need to increase your session timeout if you are getting token timeouts.  You can do this in the system configuration.

**Comment by ebonyclock** [comment]
I am not really bothered by this but I thought you might want to know since you reopened the issue.

**Comment by rhukster** [comment]
This is something else that should be addressed in Grav 1.1 with our new keep-alive ajax calls.
