### ISSUE TITLE
committing to github

### ISSUE THREAD

**Issue by srfoster** [getgrav/grav-plugin-admin#669]
After installing this plugin and creating an admin account, is it safe to push my Grav installation to a public github repo?

I noticed that there's a hashed password in one of the user/accounts/ yaml files.  Should I .gitignore that?  Does it matter?  Are there other sensitive files?

**Comment by flaviocopes** [comment]
If you post it in the public, I'd ignore the accounts/ folder, and also (most important) the `config/security.yaml` file which contains the unique site salt key used to generate the passwords.
