### ISSUE TITLE
Changing Root Folder Issue

### ISSUE THREAD

**Issue by simmonsr** [getgrav/grav-plugin-admin#67]
![screen shot 2015-08-13 at 2 51 19 pm](https://cloud.githubusercontent.com/assets/5002814/9262169/70b89432-41d8-11e5-8a54-ffe8dcacf0a0.jpg)

so ive got a 'Reggie' page under /reggiesmith34

![screen shot 2015-08-13 at 2 51 28 pm](https://cloud.githubusercontent.com/assets/5002814/9262173/75f76892-41d8-11e5-9031-12ae9264f097.jpg)

content entered here

![screen shot 2015-08-13 at 2 51 45 pm](https://cloud.githubusercontent.com/assets/5002814/9262181/83c80bf2-41d8-11e5-9abe-9a7da5e11051.jpg)

change the folder name to /reggiejoe and then Save

![screen shot 2015-08-13 at 2 51 54 pm](https://cloud.githubusercontent.com/assets/5002814/9262184/878c7dc2-41d8-11e5-8bf9-93253c4de566.jpg)

Saving sends me to a 'Reggiesmith34' page with no content.

When I back out, the folder changed correctly. But I don't think we want users to be directed to this new page after Saving.

**Comment by rhukster** [comment]
Yup, looks legit to me.  I'll take a look after i address some other bugs.  Thanks!

**Comment by simmonsr** [comment]
Ok, thanks! :+1:
