### ISSUE TITLE
Copied pages not appearing in Admin Panel.

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#670]
Trying out the just released 1.1.0-rc.3, and when I do the following the copied page does not seem to appear in the Admin Panel as expected:

1) Open default 'Home' page
2) Tap 'Copy'
3) Tap 'Save'
4) Return to pages view

I also tried this:
1) Open default 'Home' page
2) Tap 'Copy'
3) Enter new page title
4) Tap 'Save'
5) Return to pages view

However, these copied pages do appear in the actual 'Pages' folder - just not in the Admin Panel.

Please let me know if more info is required.

Thanks very much,
Paul

**Comment by rhukster** [comment]
I know that @flaviocopes was doing some updates/fixes with copy/moving/reordering pages.  This is probably related to that.  Assigning...

**Comment by flaviocopes** [comment]
Looking

**Comment by flaviocopes** [comment]
Works fine for me, tested a couple things, but I always see the copied page correctly. With cache disabled or enabled. Did you test with cache disabled? 

Do you see the page if you logout/login?

**Comment by paulhibbitts** [comment]
Hmmm... I've been trying to duplicate it again but no luck. I thought more a moment it might have to do with me first updating the Antimatter theme to beta 2 but that did not duplicate the issue too.

I will try to do some more tests and let you know if I can duplicate it. BTW, it was from a fresh install of the newest RC and I did not do any changes re: default config (except for updating Antimatter).

Thanks very much,
Paul

**Comment by paulhibbitts** [comment]
Hi @flaviocopes I've been trying to duplicate this issue but I still can't (which is a good thing!) - I am thinking it was a glitch with my local MAMP setup so I will close the issue.
