### ISSUE TITLE
Remove markup in plugins

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#671]
Remove `<p>` tag.

Under Available Plugins:
`<td class="double"><p>This plugin provides automatic header anchors via the <a href="http://bryanbraun.github.io/anchorjs">anchorjs</a> jQuery plugin.</p></td>`

Under Installed Plugins:
`<td class="double">This plugin provides automatic header anchors via the <a href="http://bryanbraun.github.io/anchorjs">anchorjs</a> jQuery plugin.</td>`

https://dl.dropboxusercontent.com/u/4284608/available-plugins.jpg

**Comment by flaviocopes** [comment]
This is on purpose, as the description is being parsed by Parsedown for markdown content.

We could tweak the initial spacing, but not really an issue
