### ISSUE TITLE
Can't confirm deletion of multiple images

### ISSUE THREAD

**Issue by flesser** [getgrav/grav-plugin-admin#672]
I is not possible to delete multiple images from the Page Media field without reloading the page, because the "Continue" button of the confirmation dialog stays disabled.

Steps to reproduce:
1. upload several images to Page Media, save the page
2. click "delete" on one of the images, confirm the warning dialog
3. click "delete" on the next image --> "Continue" button on warning dialog is disabled.

**Comment by flaviocopes** [comment]
Replicated.
