### ISSUE TITLE
Feature suggestion: allow admin login with username OR email address

### ISSUE THREAD

**Issue by a1studmuffin** [getgrav/grav-plugin-admin#674]
Just a minor feature suggestion, it would be great if the Grav admin login screen allowed you to enter your admin username OR email address. Some browsers cache the admin email and password from the initial "create an account" screen, then when you advance to the login screen for the first time, the browser will auto-fill the form with the incorrect data. It made me scratch my head for a moment before figuring out what was happening. Cheers :)

**Comment by a1studmuffin** [comment]
Wow that was quick! You guys rock, very impressed with the Grav developer community. Thanks :)

**Comment by flaviocopes** [comment]
Thanks to @gsumpster
