### ISSUE TITLE
Pages interface is completely broken

### ISSUE THREAD

**Issue by vemacs** [getgrav/grav-plugin-admin#675]
Running Grav 1.0.10 and Admin 1.0.2. Here is a call stack that I obtained from Chrome's dev tools:

![](https://i.imgur.com/APKdZ5O.png)

Here is the culprit: https://github.com/getgrav/grav-plugin-admin/blob/release/1.0.2/themes/grav/js/pages-all.js#L283

**Comment by w00fz** [comment]
Thanks, yes that needs a double quote `$('a[href]:not([href^="#"])')`

**Comment by flaviocopes** [comment]
Please use Grav 1.1RC, that bug is already fixed there, and we're going to release 1.1 stable very soon.

**Comment by flaviocopes** [comment]
Also I am sure this was fixed in Admin 1.0.x too, you're using 1.0.2  but the latest stable release is 1.0.10
