### ISSUE TITLE
Tooltip Displaying Offscreen

### ISSUE THREAD

**Issue by jacobm001** [getgrav/grav-plugin-admin#677]
I'm using the latest release client of the admin plugin, and I noticed there is a display issue with the control tooltips. When editing pages in fullscreen mode, the positioning of tooltips appears to be static, which causes the "Fullscreen" tooltip to be cut off.

![tooltip_bug](https://cloud.githubusercontent.com/assets/2245023/16428669/c15db962-3d27-11e6-991b-11684249ac39.PNG)

**Comment by flaviocopes** [comment]
Yes, replicated.
