### ISSUE TITLE
List labels too wide

### ISSUE THREAD

**Issue by fredrikekelund** [getgrav/grav-plugin-admin#679]
This issue concerns Grav v1.1.0-rc.3

With the introduction of the ability to nest lists (which is great btw), I think the width of the label column ought to be reduced. If I nest three lists, there's barely any space left for the controls. Maybe the best thing here would be to have the label column only use the space required by the label text.

I attached an image to illustrate my point:

![screenshot 2016-06-30 15 21 33](https://cloud.githubusercontent.com/assets/1101677/16489627/ae011426-3ed6-11e6-8428-c3c492c6367f.png)

**Comment by flaviocopes** [comment]
Using 
```
            type: list
            style: vertical
```
should already help

**Comment by fredrikekelund** [comment]
Ah, I didn't know that option was there - I'll try it out as soon as I get a chance! Might still be worth looking into reducing the label width in the default layout IMHO, though

**Comment by fredrikekelund** [comment]
I think that changing the default style of list fields might be worth considering, as the label column really does take up a lot of space, and with nested lists this immediately turns into a problem. But nevertheless, I submitted a PR https://github.com/getgrav/grav-learn/pull/327 that at least documents the currently available `style` property.

**Comment by flaviocopes** [comment]
Normal lists will not have issues with the default styling, but nesting lists will result in that loss of space, so adding `style: vertical` will fix it. Thanks for documenting it!
