### ISSUE TITLE
Existing pages turn invisible when saved

### ISSUE THREAD

**Issue by astfgl** [getgrav/grav-plugin-admin#68]
Grav: 0.3.97
Admin: 0.3.0

Existing pages:
All my pages have only the bare minimum of metadata - "title:" is the only thing in the md header.
When the admin GUI edits and saves the page it adds 3 extra header lines - "taxonomy" and the associated "tag" and "category".
Note that it does not add "visible", but the page is renamed not-visible when the save happens.
The only way to make the page visible again is to use the "visible" override which adds the "visible: true" header.

New pages:
A new page is created with the "taxonomy", "tag", "category" AND "visible: true" headers.

In both cases, the "taxonomy" set of headers are empty and unused, they appear to be just placeholders. On the other hand, the"visible" header should not have been added since it duplicates the site default, and the fact that that the existing page is renamed not-visible seems to be a variable initialization issue - the visibility state of the page is not being inherited from the site default if the header line does not exist, and then the save action is triggering a rename.

**Comment by rhukster** [comment]
I'm actually working on this "visible" issue already.

The blank taxonomy issue is another problem, that I'm going to look at also.

**Comment by astfgl** [comment]
No worries, I added it as a bug so you had a reference from my gitter post.

**Comment by rhukster** [comment]
both should be fixed with latest develop branch
