### ISSUE TITLE
Dashboard User Registration: Creating Directory Failed

### ISSUE THREAD

**Issue by gsumpster** [getgrav/grav-plugin-admin#682]
When attempting to create a secondary user through the Admin Dashboard (by going to /admin/users/<username> (in Grav 1.0.10) or /admin/user/<username> (in Grav 1.1.0-rc.3, Admin 1.1.0-rc.4)), the error: `Creating directory '' failed on error mkdir(): Invalid path` will appear after submitting the registration form. 

Server: Ubuntu 14.04, Apache 2.4.7, PHP 5.5.9, Zend Engine v2.5.0, both versions on AWS t2.micro servers

[GIF of process Grav 1.1.0-rc.3](http://i.imgur.com/8i3NZgT.gifv)

To reproduce:

1. Install Grav 1.0.10/1.1.0
2. Install Admin Plugin via `bin/gpm install admin`
3. Register Admin Account (works fine on both)
4. Navigate to either /admin/users/<username> or /admin/user/<username> for versions 1.0.10/1.1.0 respectively
5. Fill out required forms

Debug hasn't produced any answers on either versions, Apache's error.log has nothing in it. Spoke with @Vivalldi regarding this bug on Gitter, we couldn't find any cause for it in the Login plugin's code. I have two instances running different versions, PM me on Gitter and I can throw you the login information for the dashboard if needed.

**Comment by flaviocopes** [comment]
Thanks for reporting, even though it's a "hidden" feature, it should be fixed now.
