### ISSUE TITLE
Default template Markdown not rendering correctly

### ISSUE THREAD

**Issue by cavynmaicl** [getgrav/grav-plugin-admin#684]
When testing the system, the first page I created renders correctly in the visual editor, but does not on the actual site. Please see the screenshots attached. The "Menu Item 1" is pulling styling from the subhead line above it in the site's public output.
![screen shot 2016-07-04 at 11 11 17 am](https://cloud.githubusercontent.com/assets/2954062/16567095/2d9e6db0-41d8-11e6-8793-08db64926626.png)
![screen shot 2016-07-04 at 11 11 27 am](https://cloud.githubusercontent.com/assets/2954062/16567097/2dc0072c-41d8-11e6-8075-7d88ccdccb3b.png)
![screen shot 2016-07-04 at 11 11 30 am](https://cloud.githubusercontent.com/assets/2954062/16567096/2dbd464a-41d8-11e6-8996-c01233eeeb94.png)

**Comment by rhukster** [comment]
That's just a 'feature' of the Antimatter theme.  It's purely a CSS styling issue:

https://github.com/getgrav/grav-theme-antimatter/blob/develop/scss/template/_typography.scss#L64-L92
