### ISSUE TITLE
Renaming modular folder to non-underscore name

### ISSUE THREAD

**Issue by peto01** [getgrav/grav-plugin-admin#687]
The admin tool allows users to rename a modular page's folder to a name that does not start with an underscore. As I understand it, modular page folders need to start with an underscore, and the Admin plugin shouldn't accept names that don't start with an underscore.

**Comment by flaviocopes** [comment]
The underscore is automatically added when saving the modular child (as of Grav 1.1, didn't test on 1.0.10) - I'm talking about modular childs, not parent modular pages

**Comment by peto01** [comment]
That would solve my particular issue, thanks!
