### ISSUE TITLE
Suggestion: Modify page Preview button to render full page in a new tab with unsaved content

### ISSUE THREAD

**Issue by a1studmuffin** [getgrav/grav-plugin-admin#689]
Currently if you edit a page, then press the Preview eye button at the very top of the admin page before saving, you get the warning:

"Changes Detected
You have unsaved changes. Are you sure you want to leave without saving?"

It would be cool if Grav was smart enough to realise I was trying to preview the unsaved changes, and spawned a new tab with a full rendered preview of the unsaved changes using the appropriate template. 

I'm aware there's already the content preview button, but that only renders the markdown content section. Part of Grav's appeal is that you can use the yaml frontmatter on a page to add additional visible content via templates, but you can only see this when the page is fully rendered. As it stands there's no way to preview those yaml frontmatter changes without saving the page then browsing to the URL. Not a big deal when you're building the site, but if you're a content creator with a live site, I think you probably want a way to check this before saving.

You may already have something different planned that addresses this issue, just thought it was worth raising.

Cheers,
Michael

**Comment by w00fz** [comment]
Done 👍

**Comment by a1studmuffin** [comment]
Oh my good lord, you guys are insane. :D So that simple change will cause the preview button to show the unsaved changes to the page, including the frontmatter?
