### ISSUE TITLE
Feature Request: Better content editing.

### ISSUE THREAD

**Issue by btn0s** [getgrav/grav-plugin-admin#693]
After having used Grav + the Admin Plugin a few times for clients I have a few ideas.

**1) WYSIWYG option for the content-editor to switch off the visibility of the Markdown syntax.**

Ultimately it comes down to the fact that not all clients/end-users are going to be Markdown-savvy, and I think it'd be nice to be able to cater to them as well. More complex content such as resume or syllabus content is very difficult for the user to read and, in effect, write.

**2) Text formating control beyond "fencing" and using `<pre>` elements.**

Wordpress, for example, supports indentation and has better line-break detection. Same use-case as above a resume needs to be indented properly, and as-is the user would have to create complex nested `<ul>` elements in Markdown, and this is not something I would think any of us would want to wish on our end-users. 

These two things coupled have been a big issue in a recent project of mine, and I ended up having to use another content-editor and export from there into the Grav setup... skipping the Admin Plugin's content-editor all together.

If I knew anything about PHP I'd get in and see what I can do to help out and extent the editor's functionality, and I still may... just thought to post this here as well. Cheers!

**Comment by gsumpster** [comment]
This is a feature planned for Admin Pro, [planned for later this year](https://getgrav.org/blog/plans-for-2016). This would include a WYSIWYG editor. The indentation issue is more of a Markdown limitation, rather than an editor limitation.

**Comment by rhukster** [comment]
I think @gsumpster covered this!

**Comment by btn0s** [comment]
@gsumpster sweet! I'm excited for the Admin Pro. Thanks guys!
