### ISSUE TITLE
Section Content Disappears

### ISSUE THREAD

**Issue by jhochgreve** [getgrav/grav-plugin-admin#696]
When in the admin plugin under a custom tab using the "Section" fields after the page is saved the content that was added disappears. It does write to the front end, and appears in the page headers, but vanishes in admin.

**Comment by flaviocopes** [comment]
Can you post the page blueprint? Also, using Grav/Admin 1.1 or 1.0?

**Comment by jhochgreve** [comment]
title: Homepage
@extends:
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      fields:
        features:
          type: tab
          title: Hero
          ordering@: 1
          type: tab
          title: Sub-Heading
          ordering@: 2
          fields:
            header.homehero:
              name: Hero
              type: section
              label: Hero Copy
              
              fields:
                .title:
                  type: text
                  label: Title
                .subtitle:
                  type: text
                  label: Subtitle

**Comment by jhochgreve** [comment]
this is admin 1.1

**Comment by jhochgreve** [comment]
**Update: 
I have realized my haml was not correct; however, I have verified that this issue seems to actually be as follow: 

- When you save a standard text section via the admin plugin the first time it will write properly.
- The text disappears from the input fields after the save even though it was written
- Any further edits to the input fields do not save after saving. 

Here is my updated yaml file: 
`title: Homepage
@extends:
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      fields:
        content:
          type: ignore
        feature:
          type: tab
          title: Page Content
          ordering@: 1
          fields:
            header.homehero:
              name: Hero
              type: section
              title: Hero Section
              underline: true

              fields:
                .title:
                  type: text
                  label: Hero Title
                .subtitle:
                  type: text
                  label: Hero Sub-title

            header.subheading:
              name: Sub-Heading
              type: section
              title: Sub Heading Section
              underline: true

              fields:
                .copy:
                  type: textarea
                  label: Enter Sub-Heading Copy Below

            header.featured:
              name: Featured-Service
              type: section
              title: Featured Service/Loan
              underline: true

              fields:
                .title:
                  name: Title
                  type: text
                  label: Title
                .copy:
                  name: Copy
                  type: textarea
                  label: Copy
                .buttonText:
                  name: Button-Text
                  type: text
                  label: Button Text
                .buttonLink:
                  name: Button-URL
                  type: url
                  label: Button Link URL
`
I hope this helps!

**Comment by flaviocopes** [comment]
You need to prepend all fields with `header.`, like `header.homehero.title`instead of just `.title` for the first one.

only having `.something` is limited to `list` type fields.

**Comment by jhochgreve** [comment]
I actually did go on to do just that after this, but it still only worked with list items. I tried it just doing standard text, textarea, and even editor and none of them wrote nor retained the text I added. I will try again and post an example if I still have the issue.

**Comment by flaviocopes** [comment]
I tried prepending header. to your blueprint before writing the comment, so it should definitely work.
