### ISSUE TITLE
Latest Updates and Gravstrap

### ISSUE THREAD

**Issue by 2braincells2go** [getgrav/grav-plugin-admin#697]
Was working on new site using Gravstrap. Got notice of 8 updates and updated all.

Gravstrap theme was not one updated but, now the header / footers menus are gone, totally missing from entire site.

**Comment by 2braincells2go** [comment]
MY BAD! on mobile device and somehow ended up under the admin plugin. meant to open this under the main getgrav. Sorry, maybe you can move it?

**Comment by rhukster** [comment]
Just open a new one there, i'll close this.
