### ISSUE TITLE
Cant add page in admin plugin

### ISSUE THREAD

**Issue by jhochgreve** [getgrav/grav-plugin-admin#698]
Not sure if its just me but after the last update I can no longer add pages via the admin plugin. I am able to add pages via the file structure.

**Comment by MindlessPursuits** [comment]
I'm having the same issue.

**Comment by navarrodavid** [comment]
Same issue here, tried Safari and Chrome on a mac.

**Comment by rhukster** [comment]
what exactly is happening? errors out? add button doesn't work? Need more info please.

**Comment by jhochgreve** [comment]
No errors. When you press the button to save the page nothing happens; almost like the function is broken. Same happens when adding a folder etc.

**Comment by rhukster** [comment]
ack, i'm seeing that too... must of broken very recently.. we'll get it sorted.

**Comment by jhochgreve** [comment]
Thanks! I think it was today's update.

**Comment by w00fz** [comment]
Same as https://github.com/getgrav/grav/issues/934

**Comment by w00fz** [comment]
Fix is in place, Admin is getting re-released and it will be available in few mins. 

MS Edge is still known to cause problems when saving a Page, we will address this soon, you can subscribe to https://github.com/getgrav/grav-plugin-admin/issues/694 to follow the progress, if needed.

Sorry for the inconvenience!
