### ISSUE TITLE
Admin favicon issue

### ISSUE THREAD

**Issue by 2braincells2go** [getgrav/grav-plugin-admin#704]
No biggie but thought you may like to know issue with favicon link in head:

<link rel="icon" type="image/png" href="//user/plugins/admin/themes/grav/images/favicon.png">

Looks like the extra / b4 user/ is issue?

**Comment by gsumpster** [comment]
Hey, thanks for pointing this out, have submitted a PR to fix!

**Comment by 2braincells2go** [comment]
No problem! Away from my desktop on little chrome laptop or would have submitted PR...

**Comment by flaviocopes** [comment]
👍
