### ISSUE TITLE
Admin panel statistics count

### ISSUE THREAD

**Issue by 2braincells2go** [getgrav/grav-plugin-admin#705]
Appears (or at least on test server) that one visit is being counted as two.

I can visit site either via admin panel or load on another browser and count increases by two each time.

**Comment by gsumpster** [comment]
Wasn't able to replicate on latest version on a clean install, can you provide some more information? (plugins etc.)

[gif](http://i.imgur.com/SyP3gEL.gifv)

**Comment by 2braincells2go** [comment]
Latest version, everything including updated to latest.

http://screencast-o-matic.com/watch/cDib2biA3F

 Admin Panel  v1.1.2
 Archives  v1.5.0
 Assets  v1.2.1
 BlogInjector v1.2.2
 Bootstrapper  v1.3.2
 Breadcrumbs  v1.5.0
 Custom CSS  v0.2.0
 Editor Buttons  v1.1.1
 Email  v2.4.1
 Error  v1.5.0
 Feed  v1.5.0
 Form  v1.3.0
 Gravstrap v1.1.3
 Highlight  v1.3.1
 LangSwitcher  v1.2.1
 Login  v2.0.0
 Markdown Color  v1.0.1
 Markdown Notices  v1.0.0
 Markdown Sections v0.9.1
 Mini Code v1.1.0
 Pagination  v1.3.2
 Problems  v1.4.3
 Random  v1.5.0
 Related Pages  v1.1.3
 Shortcode Core  v2.3.1
 SimpleSearch  v1.8.0
 Taxonomy List  v1.2.7
 Text Formatter v1.0.2
 Themer v1.1.0-beta.1 test release
 YouTube  v2.0.2

**Comment by flaviocopes** [comment]
Might be that the particular plugins and theme combination triggers a double call, but never seen  this - can you PM me at gitter.im/flaviocopes your user/ folder without `user/accounts` and `user/data` so I can quickly test this?

**Comment by rhukster** [comment]
if you make a request 'through' Grav, ie a URL that is a route to a page and loads an image via Grav's fallbacks, it will be treated as a request and count as a hit.  this is a bug in the logic, and we should check to make sure you are only requesting a valid 'page'.

**Comment by 2braincells2go** [comment]
Sorry guys, I have been away and no access to files. If they are still needed can get them to you in couple of days.

Thanks for all the input.

**Comment by rhukster** [comment]
I just looked at the logic and it's already doing a bunch of checks including checking to make sure the page is valid and page has a route.  I think we're doing all we can.  This is not meant to be as accurate as say Google Analytics, it's intended to give you a general trend:

https://github.com/getgrav/grav-plugin-admin/blob/develop/classes/popularity.php#L48-L83

**Comment by 2braincells2go** [comment]
No big deal to me, just thought you guys may like to know.
