### ISSUE TITLE
PreCache plugin: Install screen says "Plugin Status" twice

### ISSUE THREAD

**Issue by gxjansen** [getgrav/grav-plugin-admin#710]
See screenshot below:
![plugin__precache___guido_jansen_](https://cloud.githubusercontent.com/assets/487722/16971157/96f66fba-4e21-11e6-945c-660cb7f7f1a0.jpg)

**Comment by rhukster** [comment]
Weird, i'm not seeing that in my 1.1.1 version.  BTW this would be  a precache issue: https://github.com/getgrav/grav-plugin-precache/issues (not a grav admin issue)

![Grav 2016-07-19 20-04-35](https://cloud.githubusercontent.com/assets/1084697/16972856/08db08c4-4dec-11e6-912b-8c85984b6446.png)

Also it looks fine in the blueprint.  Please check yours: https://github.com/getgrav/grav-plugin-precache/blob/develop/blueprints.yaml#L30
