### ISSUE TITLE
Edit user

### ISSUE THREAD

**Issue by laszlokorte** [getgrav/grav-plugin-admin#713]
(Grav v1.1.1 - Admin v1.1.2)
I created a second user with the following access:

```
access:
  admin:
    login: true
    pages: true
```

When logging in with that user I can click on the avatar in the upper left to edit the user (the one I am logged in with) but when change something an click "save" I get a permission denied error.

So that user can not change her own password. I also tried to add `user: true` and `users: true` to  the access map but it did not change anything and I did not find anything documented in this regards.

Then I tried to edit the second user (no `super` access) while being logged in as super user by manually changing the url to `/admin/user/no-super-user`. That worked but after clicking save I was no longer logged in as super user but as `no-super-user`.
I do not know if it's desired to be able to edit other user's accounts by fiddling with the url. If a super user is allowed to do that one should not be logged on saving. If it's not desired that one user edits another it should not work at all and changing the url by hand should not be possible.

**Comment by flaviocopes** [comment]
Ok, a couple issues here:

- [ ] non-`admin.super` users should be allowed to save their profile (obviously) but it's not working right now
- [ ] `admin.super` is allowed to access and save a user profile (ok), but admin should not switch to that user after saving
- [ ] non-`admin.super` (or non-`admin.users`) users should not be allowed to see any other profile. They currently have read access to other site profiles in admin.

**Comment by flaviocopes** [comment]
Fixed in the above commits
