### ISSUE TITLE
is there an API available for this plugin

### ISSUE THREAD

**Issue by rlynjb** [getgrav/grav-plugin-admin#715]
I'm writing a simple plugin that takes the current logged in username and renders it on 'created or edited' grav header page once Saved button has been clicked. I was wondering if there is an API i can use for this plugin?

Thank you

fyi, i am a newbie with writing plugins or php classes

**Comment by rhukster** [comment]
https://learn.getgrav.org/api/

These are our current rough API docs.

**Comment by rhukster** [comment]
BTW the best way to learn about writing plugins is download a bunch of them, and just look over what they do, and how they do it.  Generally speaking, they are not terribly complicated.

**Comment by rlynjb** [comment]
thank you @rhukster for the tips and resources.. will take a look at it.
