### ISSUE TITLE
Installing admin 404s entire site

### ISSUE THREAD

**Issue by le717** [getgrav/grav-plugin-admin#716]
Brand new Grav v1.1.1 Base installation, PHP 5.6.23, Ubuntu 14.04 x64 Digital Ocean droplet created using ServerPilot.

Every time I go to install the admin plugin using GPM, my entire site (every page) gets redirected to /admin, which produces a 404 error. Uninstalling admin restores the site. I even installed each dependency separately and all was well until I installed admin.

I have no idea what kind of info you need or how to get it (I am new to Grav), so any insight into that front so this can be resolved is appreciated. I am looking at using Grav to replace a WordPress site and the admin is needed for a complete replacement, so I cannot continue on without it.

**Comment by rhukster** [comment]
Ok, first, the redirect to the admin is because you don't have a user, and it's actually forwarding you to the admin plugin to create an admin user.

The 404 you are getting is because your routing is not working. Check this document for some pointers:  https://learn.getgrav.org/troubleshooting/page-not-found

**Comment by rhukster** [comment]
BTW, for ubuntu and digital ocean - you can check out this guide we have that i've tested:

https://learn.getgrav.org/hosting/vps/digitalocean

**Comment by rhukster** [comment]
Actually with serverpilot it should 'just work'.  I have not had any problem with bone-stock serverpilot setup and I use that with getgrav.org and gantry.org.

**Comment by le717** [comment]
Thanks for the help! The problem was your first guess: my routing was not working. Somehow, the Grav .htaccess was not getting installed. Manually uploading it via FTP did the trick. Thanks! 😄
