### ISSUE TITLE
Parent page listing in Admin UI

### ISSUE THREAD

**Issue by ritchiedalto** [getgrav/grav-plugin-admin#717]
The screen shot should say it all... One of my users found this right after last upgrade - The parent page field in the admin ui shows all these &nbsp; codes. So weird, and it's on literally every modular child page in the entire site!

![nbsp](https://cloud.githubusercontent.com/assets/3119016/17078377/dc0733b4-50bf-11e6-8baa-493abfdcb265.jpg)

**Comment by rhukster** [comment]
I just checked this out on my local and am not seeing that:

![edit home grav 2016-07-23 08-57-55](https://cloud.githubusercontent.com/assets/1084697/17078569/9e768952-50b3-11e6-9bca-aeca2cef83f1.png)

It looks like you have some plugin/theme updates pending.  Please try updating everything and clearing the cache.. That should help.

**Comment by ritchiedalto** [comment]
I can't globally update plugins, I have to go one by one and test, they are breaking my sh*t left and right. But I'll get to that and let you know.

**Comment by ritchiedalto** [comment]
Updated "Login" plugin. It updated the form and email dependencies with it. SO one of those fixed the problem. Thank you. Gotta check and see if anything broke now :/

**Comment by flaviocopes** [comment]
Seems the original problem is solved, right? Closing then, reopen if I'm wrong.

**Comment by Algorithm518** [comment]
For those wondering or in a similar situation as me where you cannot update your plugins at the given time, this fix was introduced in #502 4743046ceb9
