### ISSUE TITLE
Error when trying to log in into admin area.

### ISSUE THREAD

**Issue by 6fireflis** [getgrav/grav-plugin-admin#721]
When trying to access admin panel, after adding the email address:
<img width="687" alt="screen shot 2016-07-28 at 1 50 00 pm" src="https://cloud.githubusercontent.com/assets/19257654/17200606/3be0d566-54ca-11e6-8358-22d03dab0aa7.png">
I have "Undefined index: username" error:
<img width="1188" alt="screen shot 2016-07-28 at 1 50 09 pm" src="https://cloud.githubusercontent.com/assets/19257654/17200621/53fb136e-54ca-11e6-838f-3437d21ffce3.png">

The grav CMS is at latest version; the admin plugin and dependent plugins are at latest versin, so what could be the problem?

**Comment by 6fireflis** [comment]
The post data has no username field:
array:1 [▼
  "email" => "email@here.tt"
]

**Comment by rhukster** [comment]
How do you see that page? it should have a username/email + password field for the login panel:

![grav admin login grav 2016-07-27 22-30-09](https://cloud.githubusercontent.com/assets/1084697/17201216/ba4821ba-5449-11e6-98c7-0b017a815feb.png)

**Comment by 6fireflis** [comment]
Well, when I am accessing the /admin route I can only see the email field, like that screen shot uploaded:
<img width="687" alt="screen shot 2016-07-28 at 1 50 00 pm" src="https://cloud.githubusercontent.com/assets/19257654/17201941/1fa5b5d8-54d9-11e6-8504-3c5b9e9bf327.png">

So I am not asked about the password and the placeholder text is "Enter Your Email"

**Comment by flaviocopes** [comment]
Definitely strange! Did you download the Grav package recently, or did you update from an older version?

**Comment by 6fireflis** [comment]
Well, I have started working with grav about 1 month ago, so the version is max 1 month old. 

Anything specific to look for?

**Comment by rhukster** [comment]
My hunch is that you have either Grav or some plugin out of date.  From the terminal you should try:

```
# bin/gpm self-upgrade
# bin/gpm update
```

This will ensure Grav and all plugins/themes are updated to latest releases.

**Comment by 6fireflis** [comment]
# bin/gpm self-upgrade returns: 

GPM Releases Configuration: Stable
You are already running the latest version of Grav (v1.1.1) released on Sat Jul 16 17:08:34 2016

# bin/gpm update returns:

GPM Releases Configuration: Stable
Nothing to update.

It seems that I am at the latest version. Maybe is a setting somewhere?
I have also reinstalled the admin plugin: 
bin/gpm install admin

still the same problem.

**Comment by rhukster** [comment]
Hmm.. try removing the login plugin and reinstalling it.

**Comment by flaviocopes** [comment]
PM me your user/ folder to gitter.im/flaviocopes and I'll take a look at what's wrong.

**Comment by 6fireflis** [comment]
Finally I was able to figure it out; it was a conflict with another custom built plugin. 
Sorry for the trouble.
