### ISSUE TITLE
404 on Aerial theme demo link 

### ISSUE THREAD

**Issue by fluidbrush** [getgrav/grav-plugin-admin#723]
In **admin/themes/aerial**,  the demo link http://benjamin-regler.de/aerial throws a 404 error.

**Comment by flaviocopes** [comment]
@Sommerregen do you have a demo up, or should the demo link be removed?

**Comment by Sommerregen** [comment]
@flaviocopes Where is it? It is not in [the blueprints file](https://github.com/Sommerregen/grav-theme-aerial/blob/develop/blueprints.yaml#L10). Link to http://themes.benjamin-regler.de/aerial/ is working, just tested. It looks like an error on the https://getgrav.org/downloads/themes page. Cache of GPM should definitely be cleared sometimes.

**Comment by w00fz** [comment]
GPM always refer to the latest release. In your current 2.0.3 tag the link is different.

https://github.com/Sommerregen/grav-theme-aerial/blob/v2.0.3/blueprints.yaml

**Comment by Sommerregen** [comment]
@w00fz Thanks. I didn't noticed that I tagged the wrong commit. Thanks! This is fixed now with [Aerial v2.0.4](https://github.com/Sommerregen/grav-theme-aerial/blob/v2.0.4), which should be in the GPM in approx 1-2 hours.

This issue can be closed I guess.

**Comment by flaviocopes** [comment]
Mmm it's not being picked up by the GPM for some reason?

**Comment by Sommerregen** [comment]
@flaviocopes I noticed it, too. Same with [Grav Plugin MathJax v1.5.0](https://github.com/Sommerregen/grav-plugin-mathjax/tree/v1.5.0). Any mal-formatting? Or does something has changed during this year? I tagged releases as always according to the schema **vX.X.X** and in both cases the release should point to the right commit...

@w00fz Any idea?

**Comment by w00fz** [comment]
I fixed it now. Looks like one of the repository owners has renamed its user, causing our repo gen to throw since that case wasn't handled, nor taken into consideration.

Should be all good again now.

**Comment by fluidbrush** [comment]
Thanks a lot for the fix Guys..

**Comment by flaviocopes** [comment]
Thanks @w00fz 👍
