### ISSUE TITLE
Content Editor missing content and logout on save

### ISSUE THREAD

**Issue by 88kbbq** [getgrav/grav-plugin-admin#727]
Installed the latest Woo skeleton, working in the Admin. Setup is all good. I tried to edit a page Modular in the editor's 'expert' mode (Frontmatter section) but get logged out of Grav upon save. Data is saved but have to log back in with an "Invalid Security Token" error in the Dashboard. I'm not able to edit content in normal mode because content isn't even visible in Editor mode. In Preview, mode the content appears but is not editable. To show you what's going on, I made a quick SC mov. If you can figure out what's going on, please do share. I can give you access to the instance if there's an RT forum we can meet on, even let you inside the box if you're curious enough.
https://cloud.88k.com.tw/index.php/s/7k7txNgyVnlwgEz
Running LEMP on DO instance with php 5.5.9. Permissions all set and services restarted. Date/time set to my locale. Update: When disabling multilingual features, the logout on save inside the editor's 'expert' mode (Frontmatter section) is resolved, but content still not visible as shown in the clip.

**Comment by 88kbbq** [comment]
I spun up a new Digital Ocean server, all server requirements, this time on 16.04 with Nginx and php7. Same exact problems. Try yourself and let me know if you need access to the box. grav.88k.com.tw 88kbbq/Easy_Password1

**Comment by rhukster** [comment]
Features modular page has no 'content' that's why you can't see anything there.  It's entirely powered by the the frontmatter.  Just look at the raw `.md` file and you will see this is the case.

I can't get the logout on changing of language.  I added a french language to your site, and then saved the features page in "french" and "english" and i'm able to switch no problem.

**Comment by 88kbbq** [comment]
Well whatayaknow? Ok then, looks good. I had all those windows open testing Grav and maybe I was on the wrong window. My apologies. Editing the FrontMatter saves too, problem gone, but you should make a note somewhere for people like me using Grav for the first time that content will not appear on normal editing mode if the page is powered by frontmatter. I'll dive into this more tonight. Cheers!
