### ISSUE TITLE
Backend not scrollable, pages, plugins or themes cannot be added

### ISSUE THREAD

**Issue by hcubiak** [getgrav/grav-plugin-admin#734]
I just installed the new Grav v1.12 on my webspace. I succeeded in calling the backend and creating the admin account. But with win7 and firefox I do not get a scrollbar, so I cannot scroll down. I cannot create new pages, download plugins or themes. The dashboard will not update maintenance, stats, notifications,... What's wrong?

**Comment by rhukster** [comment]
Grav 1.1.2 has noting to do with the admin per say.  What version of the admin are you running?

Nothing should of changed between 1.1.2 and 1.1.3 of the admin plugin.  Were you on Grav 1.0.X and Admin 1.0.X before?

Does it work in Chrome?  I tested in Firefox 50 on my mac and it's fine.  What version of Firefox are you running?

**Comment by hcubiak** [comment]
This is my first attempt at grav, and so I am running Grav v1.1.2 with Admin v1.1.3. I tried the admin plugin on Win 7, Win 10, Linux Mint, Android and iOS. Tried with Firefox 47.0 and 48.0 and Internet explorer. I tried to clear the browser cache as you told me.

Then I set the PHP version of my web space from 7.0 to 5.6 and switched off what they call the PHP boost. And BINGO - now it works perfectly. Setting the version back to 7.0 brings back the issue.

Thanks for your help.

Experience is what you get after you needed it.

**Comment by rhukster** [comment]
Is that PHP Boost option available in PHP 7.0?  If so please turn it off.  I don't know what it is, but Grav does work 100% fine on PHP 5.6 and PHP 7.0.  In fact I run all our Grav sites on PHP 7, and it runs fine.

**Comment by hcubiak** [comment]
For a test I again started the installation right from the beginning with PHP 7.0 and Boost option on: I deleted Grav from my web space, copied it again and created an admin account. Well, what shall I say? Now the admin plugin works perfectly (even with PHP 7.0. and Boost option on). I do not have any explanation other than an issue on the web space.

Btw: The web hoster tells that with Boost option on the system runs 100% faster as it only evaluates the php.ini file of the root directory, but not those in the sub-directories.

Thank you for your support.

**Comment by nepomuk13** [comment]
I had a similar problem. It is, I think, related to permission, as it only happen on an user account with its yaml as below.
```
email: user@email.com
fullname: 'Surname Name'
title: Title
state: enabled
access:
  admin:
    login: true
    super: true
  site:
    login: true
```
Here is some more informations that might help:
The problem occured both on PHP7 and PHP 5.6 and 5.5.6.
When logged in, the dashboard refresh twice each second, backend was not scrollable. 

After login on this specific user, I see the red error strip with 'Fetch Failed: Logged out' 
user/plugins/admin/themes/grav/js/admin.min.js?71bee2b848:3:1056
user/plugins/admin/themes/grav/js/admin.min.js?71bee2b848:3:329

Grav v1.1.5 - Admin v1.2.2 

Backend with the default admin user is still working perfectly.

Hope it helps!

**Comment by flaviocopes** [comment]
@nepomuk13 I tried putting that in my user yaml, but I have no issues, not with scrolling nor with refresh / fetch errors. Must be something else

**Comment by nepomuk13** [comment]
I think it is related to cloudflare and ajax, not a plugin problem.
```
A Parser-blocking, cross-origin script, http://ajax.cloudflare.com/cdn-cgi/nexp/dok3v=0489c402f5/cloudflare.min.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
```

**Comment by flaviocopes** [comment]
Ok we had quite a few issues with Cloudflare enabled and Admin. Exclude Admin from the Cloudflare admin panel, that should do it.

**Comment by flaviocopes** [comment]
Closing as problem not directly related to Admin
