### ISSUE TITLE
Thumbnail of selected media in pagemediaselect?

### ISSUE THREAD

**Issue by maximelebreton** [getgrav/grav-plugin-admin#740]
Hi grav team, and thx for the awesome work!

Is that possible to provide a way to display a thumbnail of selected media in `pagemediaselect`?

Because it's not user friendly:

![image](https://cloud.githubusercontent.com/assets/1072425/17787690/677651a8-658a-11e6-8903-daa9ce74038c.png)

And for the list:

![image](https://cloud.githubusercontent.com/assets/1072425/17787826/20930f46-658b-11e6-917a-c2c5666528d0.png)

Thanks!

**Comment by rhukster** [comment]
**pagemediaselect** is a very specific field that is intended to be used in conjunction with the editor and nowhere else.  It looks like you have a custom field that is getting page media as a **select** field?  You can create a custom field that displays thumbnails for each image in the page, but this is not something we have currently. 

I can see a 'new' generic **imageselect** field being something useful, but that should be created as a new issue we can mark as an enhancement for a future development effort.

**Comment by rhukster** [comment]
Please open a new issue requesting an image select field.  Closing this one to avoid confusion.

**Comment by fredrikekelund** [comment]
@rhukster isn't `pagemedia` the field that's meant to be used in conjunction with the editor and nowhere else? 

The docs state this about `pagemediaselect`:
> shows a select with all the page media. Used in Pages blueprints to let the user choose a media file to be assigned to a field.

I could open another issue requesting a new type of field, but I think @maximelebreton's suggestion is a good idea (I've encountered this issue myself), and fits nicely in with the `pagemediaselect` field

**Comment by rhukster** [comment]
We're already working on a flexible file/image picker field: https://github.com/getgrav/grav-plugin-admin/pull/750

**Comment by fredrikekelund** [comment]
Ah, fantastic!
