### ISSUE TITLE
More mobile friendly layout

### ISSUE THREAD

**Issue by k1ngf15h3r** [getgrav/grav-plugin-admin#742]
Are there any plans to get a more mobile friendly layout for the admin plugin? I am often online on mobile device and like to make a quick post on my phone but still now I found no solution to get this done. 

It would also be nice to have a mobile friendly preview on writing if this is possible in any way.

Thanks a lot for the great work.

**Comment by rhukster** [comment]
It is mobile friendly already 

![edit test page grav 2016-08-18 17-23-30](https://cloud.githubusercontent.com/assets/1084697/17793944/820f068a-6568-11e6-9d82-904492bc0c4d.png)

What specifically are you having trouble with???  You can click the **Eye** icon to see a preview.

**Comment by k1ngf15h3r** [comment]
Damn after writing the issue the admin panel is displayed correct on my
phone. All the time I got on it by mobile I only got a quarter screen
filled with the control panels. Don't know what happens here.

Issue can be closed

Thanks for the quick reply

Am 19.08.2016 00:24 schrieb "Andy Miller" <notifications@github.com>:
