### ISSUE TITLE
Using 307 redirect causes "Invalid Security Token" error upon login

### ISSUE THREAD

**Issue by sekjun9878** [getgrav/grav-plugin-admin#743]
Hello,

Using 307 redirect (client Mozilla Firefox 45.2) causes the "Invalid Security Token" error notification upon first login after a logout, which goes away with a refresh.

If I refresh using F5 and select "Resend" (using the login form POST) the notification remains. If I "enter" on the URL so that a GET is used instead, then the error notification goes away.

Thanks.

**Comment by sekjun9878** [comment]
And yes, the problem does go away if I select "301" on the configuration panel. Haven't tested 303.

**Comment by rhukster** [comment]
Where is this redirect happening? redirecting to the login page? or during login?

**Comment by sekjun9878** [comment]
Sorry, that description was overly complex.

1. Enter credentials on login page, and click login.
2. The user is then redirected onto the admin panel, using either 301 or 307
3. If 307 is selected, the "Invalid Security Token" appears, which disappears after a refresh

**Comment by rhukster** [comment]
Question is how you and where are setting the 307 redirect?

**Comment by sekjun9878** [comment]
![screenshot from 2016-08-20 02 43 18](https://cloud.githubusercontent.com/assets/2097812/17817877/e8818a7e-667f-11e6-8537-d554fa3f07d0.png)

You can see the setting on the bottom right corner.

**Comment by rhukster** [comment]
Yah, seems 307 is not a good option. I'll add 302 and 304 and remove 307.  301-304 work fine.

**Comment by sekjun9878** [comment]
Sounds good. Thanks!

**Comment by riemers** [comment]
Just for reference, i was using a reverse proxy in front of grav in a docker. Admin was either giving me a "invalid token" or it redirected me to "http://unknown:8080/admin" after i changed that setting to 304 the problem seems the be fixed for me. 301 does not work.

**Comment by rhukster** [comment]
The default in the next release is `302` - https://github.com/getgrav/grav/pull/1619

**Comment by riemers** [comment]
Tried 302, didn't seems to work in my particular setup. With 304 it does work, but strangely enough i have to press enter twice on the login menu and i see "invalid token" when i'am logged into admin, but all works fine. If it works, it works ;p
