### ISSUE TITLE
Antimatter Theme Error

### ISSUE THREAD

**Issue by jundiya** [getgrav/grav-plugin-admin#744]
![2016-08-20_133840](https://cloud.githubusercontent.com/assets/21137726/17829526/90c9d78a-66db-11e6-94d4-0a3630db920a.png)

**Comment by benyaminl** [comment]
@jundiya Be more specific about your error. Have you tried reinstall the theme?

**Comment by rhukster** [comment]
Uh.. not sure what this means, or why you created in the admin plugin.  

Looks like you've made some modifications as it doesn't do that for me.

**Comment by rhukster** [comment]
Please open here: https://github.com/getgrav/grav-theme-antimatter

**Comment by jundiya** [comment]
Thanks for your help @rhukster
