### ISSUE TITLE
Error : Can't load JS on news feed load

### ISSUE THREAD

**Issue by benyaminl** [getgrav/grav-plugin-admin#745]
Error : Can't load JS on news feed load, it just error when on landing page, I disable the News feed for now, Seems the for each return nothing
![image](https://cloud.githubusercontent.com/assets/2817332/17831819/1befee5c-671e-11e6-8ed3-9d15b1a70dfa.png)

**Comment by rhukster** [comment]
we have a potential fix for this in develop - https://github.com/getgrav/grav-plugin-admin/commit/18c3b3e39f167107e3d1b2c5d459a5cec922af46

can you try this?

**Comment by benyaminl** [comment]
@rhukster Okay, seems working https://github.com/getgrav/grav-plugin-admin/commit/18c3b3e39f167107e3d1b2c5d459a5cec922af46#commitcomment-18714296. Thanks
