### ISSUE TITLE
'Unsupported file type' with every Page Media upload attempt

### ISSUE THREAD

**Issue by tomkeysers** [getgrav/grav-plugin-admin#747]
Hi all,

Just exploring the Grav cms and trying some basic things out.

So I am running a clean Grav installation with my Mamp, created a new page and now wanted to upload an image in the Page Media, but I get the following error:  

> An error occured while trying to upload the file Image.png
> Unsupported file type: png

I also tried a jpg and a pdf, but it just gives the same errors.

What could cause this? A config of my Mamp installation or something?

**Comment by flaviocopes** [comment]
Cannot replicate, with a clean Grav+Admin package. 

This error usually happens when trying to upload a file not mentioned in the media files list - what's the content of your `user/config/media.yaml` file?

**Comment by tomkeysers** [comment]
Hi there, that file is blank. However the `system/config/media.yaml` file contains al basic formats, including image types.

Also tried to copy the content of that system file to the user file, but that didn't solve anything...

**Comment by rhukster** [comment]
Try deleting the user/config/system.yaml and clear the cache.

**Comment by tomkeysers** [comment]
@rhukster Thanks for the suggestion, unfortunately no luck... (user/config/system.yaml is now blank)

**Comment by flaviocopes** [comment]
Is it possible that permissions are causing this problem? https://learn.getgrav.org/troubleshooting/permissions

If this is not the case, PM me your user/ folder at gitter.im/flaviocopes and I'll check

**Comment by flaviocopes** [comment]
Checked, apparently broke because of an old Admin plugin (1.0.9) version installed

**Comment by tomkeysers** [comment]
The issue apparently was caused by the admin plugin being outdated. 

Thanks @flaviocopes for pointing that out!
