### ISSUE TITLE
Plugin update needs php-zip

### ISSUE THREAD

**Issue by herrminni** [getgrav/grav-plugin-admin#749]
Updating plugins from the admin-interface needs the php-zip package.

In Debian/Ubuntu tha package is named "php-zip".
This should be added to the check page in the installer.

**Comment by rhukster** [comment]
You mean the problems plugin?

**Comment by herrminni** [comment]
To be honest, I do not remember the plugin which caused the problem in the first place.
I remember that after a fresh install of th grav+admin panel package one plugin needed an update, and that one caused the error.
However adding other plugins did not work, either.

After installing the package "php-zip" everything worked fine in Ubuntu 16.04.

Here are the lines with the exception from the log:

`[2016-08-25 17:04:22] grav.CRITICAL: Class 'ZipArchive' not found - Trace: 
#0 /home/minni/Work/Develop/Meisterbohne/Website/htdocs/grav/user/plugins/admin/classes/gpm.php(97): Grav\Common\GPM\Installer::install('/home/minni/Wor...', '/home
/minni/Wor...', Array) 
#1 /home/minni/Work/Develop/Meisterbohne/Website/htdocs/grav/user/plugins/admin/classes/controller.php(533): Grav\Plugin\Admin\Gpm::install(Array, Array) 
#2 [internal function]: Grav\Plugin\AdminController->taskInstallPackage() 
#3 /home/minni/Work/Develop/Meisterbohne/Website/htdocs/grav/user/plugins/admin/classes/controller.php(185): call_user_func(Array) 
#4 /home/minni/Work/Develop/Meisterbohne/Website/htdocs/grav/user/plugins/admin/admin.php(313): Grav\Plugin\AdminController->execute() 
#5 /home/minni/Work/Develop/Meisterbohne/Website/htdocs/grav/user/plugins/admin/admin.php(360): Grav\Plugin\AdminPlugin->initializeController('installPackage', Array) 
#6 [internal function]: Grav\Plugin\AdminPlugin->onPagesInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) 
#7 /home/minni/Work/Develop/Meisterbohne/Website/htdocs/grav/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(RocketTheme\Toolbox\Event\Event), 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) 
#8 /home/minni/Work/Develop/Meisterbohne/Website/htdocs/grav/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) 
#9 /home/minni/Work/Develop/Meisterbohne/Website/htdocs/grav/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) 
#10 /home/minni/Work/Develop/Meisterbohne/Website/htdocs/grav/system/src/Grav/Common/Grav.php(310): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) 
#11 /home/minni/Work/Develop/Meisterbohne/Website/htdocs/grav/system/src/Grav/Common/Processors/PagesProcessor.php(18): Grav\Common\Grav->fireEvent('onPagesInitiali...') 
#12 /home/minni/Work/Develop/Meisterbohne/Website/htdocs/grav/system/src/Grav/Common/Grav.php(121): Grav\Common\Processors\PagesProcessor->process() 
#13 /home/minni/Work/Develop/Meisterbohne/Website/htdocs/grav/system/src/Grav/Common/Grav.php(396): Grav\Common\Grav->Grav\Common\{closure}() 
#14 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('pages', 'Pages', Object(Closure)) #15 /home/minni/Work/Develop/Meisterbohne/Website/htdocs/grav/system/src/Grav/Common/Grav.php(372): call_user_func_array(Object(Closure), Array) 
#16 /home/minni/Work/Develop/Meisterbohne/Website/htdocs/grav/system/src/Grav/Common/Grav.php(122): Grav\Common\Grav->__call('measureTime', Array) 
#17 /home/minni/Work/Develop/Meisterbohne/Website/htdocs/grav/index.php(45): Grav\Common\Grav->process() #18 {main} [] []
`

**Comment by flaviocopes** [comment]
Added zip check to the Problems plugin
