### ISSUE TITLE
How to add an new page template grav

### ISSUE THREAD

**Issue by Sybrenb** [getgrav/grav-plugin-admin#752]
I want to add an new page template. Ive  made an new .twig file (\user\themes\antimatter\templates) (test.html.twig) but it won't show up at the settings/page template at the admin panel. How can I add my .test.html.twig?
![1](https://cloud.githubusercontent.com/assets/21313464/18056484/635441f4-6e0c-11e6-8369-86db3b598cff.jpg)
![2](https://cloud.githubusercontent.com/assets/21313464/18056485/635831b0-6e0c-11e6-87fe-481666cbac8b.jpg)

**Comment by rhukster** [comment]
Clear the cache and reload the page.

**Comment by Sybrenb** [comment]
Thanks a lot
