### ISSUE TITLE
"Maintanance" circles css bug on resize

### ISSUE THREAD

**Issue by maciejmatu** [getgrav/grav-plugin-admin#753]
Hey, when I open dev tools, or maximize window by clicking a button, the circles in maintanance section fall out of place. It's a small issue, but I thought that you shoul dknow about it :)

![image](https://cloud.githubusercontent.com/assets/10004167/18141040/421b7838-6fb8-11e6-9c8e-9a721c84cca1.png)

**Comment by w00fz** [comment]
I believe I already fixed this, I can resize on my local and the UI gets refreshed properly

**Comment by rhukster** [comment]
This generally works fine when resizing the browser while the admin is the active tab.  However, if you are in another tab, resize the window, and switch back to the admin tab, it will be messed up like your screenshot depicts.

**Comment by maciejmatu** [comment]
Yes. Also as I said when i open dev tools it looks just as on screenshot, yet on normal resizes if fixes itself. I have 1.1.3 version of grav, and admin panel v1.1.4

**Comment by rhukster** [comment]
True, i'll let @w00fz look at this one when he gets a chance.

**Comment by Nck927** [comment]
I have AdminPanel v1.2.2, this problem occurs whenever I minimize/maximize the side navigation menu. For my case, it is not that badly out of position like the screenshot above, which is outside of the circle, the word in the circle will go slightly to the right when the side menu is in, and slightly to the right when the menu is out again.
![menuin](https://cloud.githubusercontent.com/assets/20589923/19500718/6d8f7a42-95d2-11e6-9443-67946c933152.png)
![menuout](https://cloud.githubusercontent.com/assets/20589923/19500721/75174e0c-95d2-11e6-9254-d2374617d3f8.png)

**Comment by w00fz** [comment]
Thanks, I'm aware of the issue and was able to replicate. I'll get this sorted asap.
