### ISSUE TITLE
New plugin search - Case sensitive

### ISSUE THREAD

**Issue by fluidbrush** [getgrav/grav-plugin-admin#754]
When i search for a new plugin, 'google analytics' It doesnt show in the list.
But when i typed '**G**oogle analytics' it showed. Is this case sensitive?

<img width="956" alt="screen shot 2016-09-01 at 11 40 46 am" src="https://cloud.githubusercontent.com/assets/801984/18157328/53ecf8de-703a-11e6-857a-f6ae0bf79eef.png">

**Comment by flaviocopes** [comment]
Fixed. Worked most of the cases because the plugin slug contained the keyword (e.g. Google Maps is `googlemaps`. Google Analytics was `ganalytics`).
