### ISSUE TITLE
JS error in Admin Plugin after Update

### ISSUE THREAD

**Issue by lazzich** [getgrav/grav-plugin-admin#755]
TypeError: Cannot read property 'forEach' of undefined at t.value (.../user/plugins/admin/themes/grav/js/admin.min.js?0be547795e:4:23682) at .../user/plugins/admin/themes/grav/js/admin.min.js?0be547795e:4:22862 at .../user/plugins/admin/themes/grav/js/admin.min.js?0be547795e:4:21909

**Comment by rhukster** [comment]
This is probably due to the newsfeeds failing to be retrieved due to your server setup.  We have a potential fix that is due to be released soon.

**Comment by rhukster** [comment]
Try this: https://github.com/getgrav/grav-plugin-admin/commit/18c3b3e39f167107e3d1b2c5d459a5cec922af46

**Comment by flaviocopes** [comment]
Fix working as per https://github.com/getgrav/grav-plugin-admin/commit/18c3b3e39f167107e3d1b2c5d459a5cec922af46#commitcomment-18876763
