### ISSUE TITLE
Antimatter: The little menu icon is late appearing when shrinking the window size

### ISSUE THREAD

**Issue by Neshraghi** [getgrav/grav-plugin-admin#757]
I have quite a few menu headings that stretch across the top of the page.
When I reduce the page size, the normal menu doesn't reduce to the menu icon soon enough – the whole of the normal menu disappeared.
When reduced even further, the menu icon does appear and the normal menu disappears. this happen between the screen width of 960px and 1199px, which no menu toolbar or menu icon can be found.
How can I make it that the normal menu disappears as soon as the left most item in the normal menu bumps into the logo/site title?

**Comment by flaviocopes** [comment]
Can you please repost this on https://github.com/getgrav/grav-theme-antimatter/issues ? As this is the admin plugin repo.

Also post a couple of screenshots / screen recording because I don't "get" the problem.

**Comment by Neshraghi** [comment]
I reposted it there and attached a screenshot.
Thanks.
