### ISSUE TITLE
Videos not embedding by default

### ISSUE THREAD

**Issue by maxfrigge** [getgrav/grav-plugin-admin#759]
When I drag an image into the editor it gets placed as an embedded image with `![](placeholder.jpg)`. Dragging an uploaded video however creates a link with `[placeholder.mp4](placeholder.mp4)`. 

Wouldn't it me more consistent to embed by everything by default? 
Is there maybe a setting for this?

It would also be great to control this kind of behaviour via the uiI, because many people won't know how to deal with it in markdown.

**Comment by flaviocopes** [comment]
Currently videos are embedded as links. You can add them as a preview by adding ![](placeholder.mp4)
