### ISSUE TITLE
Very strange behavior

### ISSUE THREAD

**Issue by ArsenArsen** [getgrav/grav-plugin-admin#760]
Hello!
I have installed the latest grav with the Lingoberry skeleton, and admin plugin, and I am experiancing a few issues:

* I cannot scroll in the admin pages,
* I cannot delete pages, but I can add them,
* Installations seem to be 'loading' forever
I am running PHP 7.0.8-0ubuntu0.16.04.2 fresh install together with Apache 2 latest.

I have tried and this also happens on a clean grav + admin plugin.
I would like to note that on a local install using XAMPP which has PHP Version 7.0.8.

Thanks for all your help in advance.

EDIT: I would like to note that I am running through CloudFlare

**Comment by ArsenArsen** [comment]
I found the fix, sorry, but for futher reference, disable CloudFlare Rocket Loader. It for some reason breaks grav admins scroll bars and other features.

**Comment by flaviocopes** [comment]
👍  We already defer loading the heaviest JS files, so CloudFlare Rocket Loader should not do much more to improve performance.
