### ISSUE TITLE
How to add custom fields in admin

### ISSUE THREAD

**Issue by alexraj36** [getgrav/grav-plugin-admin#761]
I have question, how can we add custom fields in admin

**Comment by rhukster** [comment]
A custom field, is really just a twig template.  So to create and use a custom field, just requires including a custom `templates/` twig path via a plugin event, and then in there having a custom field twig, ie. `forms/fields/myfield/myfield.html.twig`

I need to document this :)

**Comment by alexraj36** [comment]
i am getting now how to create custom fields in admin with new template now i am done with blueprints.

Thanks

**Comment by Flamenco** [comment]
Also, don't forget to extend the base twig.
```twig
{% extends "forms/field.html.twig" %}
```
