### ISSUE TITLE
Can't login. Composer dependencies not met.

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-plugin-admin#762]
Today after updating my Grav from repo I can't login to admin panel. Error `Login Plugin failed to load. Composer dependencies not met.`

First tried to `bin/grav install` without success:
```
ERROR Missing .dependencies file in user/ folder
ERROR invalid YAML in .dependencies
```

Second tried to run `composer install` in login plugin folder:
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
```

How to fix?

**Comment by flaviocopes** [comment]
Mmm, the error is misleading. It's the user/plugins/admin/vendor folder not being filled, most probably your .gitignore is ignoring all vendor folders. 

Make sure you go and run composer install in the Admin plugin main folder. I'm fixing the error message.

**Comment by flaviocopes** [comment]
https://github.com/getgrav/grav-plugin-admin/commit/e7ca4691679de39900be59350078bc9c62b12f24

**Comment by Sogl** [comment]
>It's the user/plugins/admin/vendor folder not being filled

Yes, problem was in that. Fixed with `composer install` in admin folder.

>most probably your .gitignore is ignoring all vendor folders.

I have line `vendor/` in it. I don't want to save vendors in my repo.

> I'm fixing the error message.

:+1: 


So... can `bin/grav install` install vendor deps for plugins too? Why it isn't working for me?

**Comment by rhukster** [comment]
No plugins generally have their own vendor deps and should be released with everything they need.

Installing from GitHub requires a bit more 'leg work' as it's generally reserved for developers.  General users should install from GPM (either CLI or Admin) so that they don't have to deal with mundane things like vendor updates.

**Comment by Sogl** [comment]
I think that's checking `user\plugins` folder and installing missing vendor deps is a good thing for `bin/grav install` command. Spent some time with similar problems in my first Grav git repo.

**Comment by rhukster** [comment]
How about adding that as a feature request in Grav core (where bin/grav install is managed) and we'll discuss it?

https://github.com/getgrav/grav/issues

**Comment by Sogl** [comment]
Done.
https://github.com/getgrav/grav/issues/1028
