### ISSUE TITLE
Prevent MS Edge from caching the page list

### ISSUE THREAD

**Issue by maxfrigge** [getgrav/grav-plugin-admin#764]
There seems to be a caching issue with MS Edge - it's working well on Chrome. 

When you change a page name and then navigate to the page list it will still show the old name until you hit the browser refresh button. Seems that just setting `Pragma: no-cache` is not enough here. 

It also seems that the `Cache-Control` header is still having a `max-age=604800`. 

Taken from a SO post - this seems to be more reliable.

``` php
header("Cache-Control: no-cache, no-store, must-revalidate"); // HTTP 1.1.
header("Pragma: no-cache"); // HTTP 1.0.
header("Expires: 0"); // Proxies.
```

**Comment by maxfrigge** [comment]
I think I narrowed it down. It seems that my page cache settings (expires and lifetime) caused this to happen. When I set them to 0 the admin works fine and nothing gets cached. 

I think it would be good to ignore any cache settings for the admin pages and make sure that those pages never get cached.

**Comment by rhukster** [comment]
Thanks for tracking this down more.. We'll look at this soon.

**Comment by rhukster** [comment]
While we don't actually have a solution for this particular problem as yet.  What we've done is make an independent option for 'admin caching' in the next release.  It will default to false and should hopefully fix your issue (and others) where admin caching is the cause.

**Comment by rhukster** [comment]
Didn't mean to close!

**Comment by mahagr** [comment]
This has been fixed not too long time ago.
