### ISSUE TITLE
Incorrectly styled input of type="url"

### ISSUE THREAD

**Issue by fredrikekelund** [getgrav/grav-plugin-admin#767]
Setting a form field to `type: url` yields this look:

![screenshot 2016-09-08 12 06 21](https://cloud.githubusercontent.com/assets/1101677/18345697/dab24702-75bc-11e6-85b8-f510a6fe5a80.png)

Probably due to https://github.com/getgrav/grav-plugin-form/issues/87, wasn't sure whether to report it here or in the form plugin's issue tracker

**Comment by flaviocopes** [comment]
👍
