### ISSUE TITLE
When pagemediaselect set to multiple, select images don't show up in the field

### ISSUE THREAD

**Issue by YoshiJL** [getgrav/grav-plugin-admin#768]
When multiple is set to true, pagemediaselect does not show any images in the field even if images have already been entered.

**Comment by w00fz** [comment]
Are you running latest admin grav and forms?
Also could you attach a screenshot / screen cast? Not quite sure what you mean.

**Comment by YoshiJL** [comment]
I have a pagemediaselect field that is set to multiple. When I add the images in, it looks like this:
<img width="777" alt="sketch 1" src="https://cloud.githubusercontent.com/assets/6374528/18362560/0e70bb34-75bb-11e6-92ca-49309dc05930.png">

But after I save, the field becomes empty:
<img width="762" alt="sketch" src="https://cloud.githubusercontent.com/assets/6374528/18362588/30f797d6-75bb-11e6-9c88-156b4efc2412.png">

The images appear correct in the frontmatter and on the live page itself.

**Comment by w00fz** [comment]
Oh ok, you should avoid using page media select field, it's deprecated and only used for pages content. Use the new revamped file field instead. And you can also use the file picker field to list files in folders.

* https://learn.getgrav.org/forms/blueprints/fields-available#the-file-field
* https://learn.getgrav.org/forms/blueprints/how-to-add-file-upload

**Comment by YoshiJL** [comment]
Thank you!
