### ISSUE TITLE
access.admin.configuration not working

### ISSUE THREAD

**Issue by peder-lundqvist** [getgrav/grav-plugin-admin#770]
I am giving a user the property access.admin.configuration. The settings menu is showing but when clicking on the menu I only get the save location blue border and an empty box.
If the user has super everything is working

**Comment by flaviocopes** [comment]
Replied in gitter. use `access.admin.configuration_system`, `access.admin.configuration_site` and so on (uses the last URL route)

**Comment by peder-lundqvist** [comment]
Thanks
