### ISSUE TITLE
Filepicker and Pagemediaselect displaying the whole list of elements in the folder (even the .md and the subfolders)

### ISSUE THREAD

**Issue by vistamedia** [getgrav/grav-plugin-admin#778]
Since the last release of the admin panel I had to take off the pagemediaselect field from my projects because of small bug that makes it unusable.
Here are some screenshots of my problems, I can even give you an access on live projects if it can help.  
Here is the bluprint
<img width="466" alt="screen shot 2016-09-17 at 8 12 37 am" src="https://cloud.githubusercontent.com/assets/9335926/18606396/fcba4220-7cae-11e6-9208-026d4415e9f9.png">
Here is the admin screen, as you can see even the subfolders are displayed in the select...
<img width="1095" alt="screen shot 2016-09-13 at 9 30 51 am" src="https://cloud.githubusercontent.com/assets/9335926/18606401/4a5699c0-7caf-11e6-9e52-8c0797dbe5d0.png">
The most important thing is the following: you cannot close the page edition without forcing because the filepicker continuously detects changes. See the screen bellow.
<img width="1230" alt="screen shot 2016-09-13 at 9 32 34 am" src="https://cloud.githubusercontent.com/assets/9335926/18606413/98e499c0-7caf-11e6-8bba-1c67dfc16043.png">
Waiting for a fix, I temporary replaced pagemediaselect by a simple text field.
I tested locally, on live sites with MacOS Chrome, Safari and Firefox.

Cheers,
Emmanuel.

The last thing: GRAV ROCKS!!! Your CMS is really addictive, congrats to all of you.

**Comment by rhukster** [comment]
Thanks, flavio did some work on this field with last release.  Assigned to him to investigate.

**Comment by anthonygrignoux** [comment]
It might be a separate issue entirely, but it seems the filepicker behaviour depends very much on the context and luck. I have the same problem as OP when I use filepickers inside a "list" type.

Either:

                header.slider:
                  type: list
                  label: Images
                  fields:
                    .text:
                      type: text
                      label: Titre
                    .image:
                      type: filepicker
                      label: Image
                      folder: 'self@/'
                      preview_images: true
                      acccept:
                        - .png
                        - .jpg
                        - .jpeg
                        - .gif
Or:

                header.slider:
                  type: list
                  label: Images
                  fields:
                    .text:
                      type: text
                      label: Titre
                    .image:
                      type: filepicker
                      label: Image
                      folder: 'self@/'
                      preview_images: true
                      acccept:
                        - image/*

will show images and normal .md files when the select is activated.
I have other problems with the filepicker but they need their own git issue.

**Comment by flaviocopes** [comment]
In the filepicker, `accept` only allows a list of file extensions, not a mime type, as documented in https://learn.getgrav.org/forms/blueprints/fields-available#the-filepicker-field. The reason is you're not uploading a file, and so you know the mime type of the uploaded file. We could have a mapping of MIME to file extensions, but not sure it's worth it / useful.

In the first example, `acccept` is spelled wrong, maybe that's the first issue.

**Comment by vistamedia** [comment]
Thanks a lot for your help Flavio and indeed I didn't see the spelling mistake. It fixes the first issue. Now I have the list with the thumbnails if I wish.
But I still cannot leave the page without the warning "Changes Detected".
Should we close this issue and open a new one? The title is not accurate anymore.
Cheers,
Emmanuel.

**Comment by w00fz** [comment]
That I believe I fixed this weekend, you could give it a try.

**Comment by vistamedia** [comment]
Great :) I'll stay tuned.

**Comment by flaviocopes** [comment]
@vistamedia should already be working if you use the latest `develop` branch of Admin, or you can wait for the next release. Reopen if you still have the problem.
