### ISSUE TITLE
[Docs] 'ordering@' field attribute is not visible, and need an example

### ISSUE THREAD

**Issue by maximelebreton** [getgrav/grav-plugin-admin#785]
'ordering@' is not visible here: https://learn.getgrav.org/forms/blueprints/fields-available#common-fields-attributes, and there is no way to know where are the 'advanced fields'.
Same here: https://learn.getgrav.org/forms/forms/fields-available

And provide an example here, because it's not clear for beginners: https://learn.getgrav.org/forms/blueprints/advanced-features#changing-field-ordering

```
header.field_after_title:
  ordering@: 1

header.field_after_content:
  ordering@: content
```

![image](https://cloud.githubusercontent.com/assets/1072425/18636328/a99a2c3c-7e88-11e6-99dd-c69b428db95a.png)

**Comment by rhukster** [comment]
Good point, this is something we need to document better.

@FrugalGeek  can you please provide a better example of ordering: https://learn.getgrav.org/forms/blueprints/advanced-features#changing-field-ordering

**Comment by FrugalGeek** [comment]
Will do! I'll get that done this afternoon.
