### ISSUE TITLE
iPhone fails on upload image

### ISSUE THREAD

**Issue by jaimeivan** [getgrav/grav-plugin-admin#791]
Hi everyone :)

I am attaching images from the iPhone, but can not upload to the server, because when you save the post no longer appears to me that image.

![](https://cloud.githubusercontent.com/assets/3803619/18680579/05648f48-7f2a-11e6-9633-740e6e6d755a.jpg)

I've tried in safari and chrome.

thks !!!

**Comment by rhukster** [comment]
Passed this one on to @w00fz :)

**Comment by w00fz** [comment]
I can't seem to be able to replicate this issue. When I select an image, the image uploads and I get the green rounded check indicating that everything went fine.
I then either refresh or save and the image still shows there. I tried with both single and multiple at the same time.

iOS 10.0.1

**Comment by jaimeivan** [comment]
Hi, i upload a gif with the issue ;)

![](https://cloud.githubusercontent.com/assets/3803619/18770475/db5b5dd4-80fb-11e6-8ca2-99c91ea592e0.gif)
 
iOS 9.3.5

**Comment by w00fz** [comment]
Ok I think the problem might be related to a Safari issue that has been fixed already (see #772).
Please try using the develop version or replace the `admin.min.js` with the fixed https://github.com/getgrav/grav-plugin-admin/commit/0512a7f4f659d56be0320915e209a05df1c7c5ab

**Comment by jaimeivan** [comment]
I replace the file `admin.min.js` and works !!!!

thks :)
