### ISSUE TITLE
TypeError when uploading or removing media in Safari

### ISSUE THREAD

**Issue by furzewolf** [getgrav/grav-plugin-admin#794]
When I add media to a page in Safari, the media appears in the list but does not upload. Checking the error console reveals the following:

`TypeError: r["delete"] is not a function. (In 'r"delete"', 'r["delete"]' is undefined)`

Deleting a file triggers a similar error:

`TypeError: null is not an object (evaluating 't.parentNode.removeChild')`

The administration panel behaves as normal in Firefox, so this appears to be an isolated bug.

**Comment by w00fz** [comment]
This should be fixed already in the repo, see #772
