### ISSUE TITLE
Admin plugin cannot scroll down

### ISSUE THREAD

**Issue by TheMarkCP** [getgrav/grav-plugin-admin#797]
I just installed the latest and fresh version yet of 2016-09-25 Grav v1.1.5 and Admin v1.2.2, the actual website is fine however the admin panel is almost unusable. I was unable to scroll down on any pages leaving me the only choice of out zooming the page to be able to access options at the bottom of the page. I have also updated all the plugins too.

**Comment by rhukster** [comment]
What browser are you using? Can you try Chrome or Firefox?

**Comment by TheMarkCP** [comment]
I am using Chrome the latest version.

**Comment by rhukster** [comment]
I can't replicate this with my Chrome.  I need more info...  

* Operating System
* Chrome version
* ZIP of site?  That would help me try to replicate it.

**Comment by TheMarkCP** [comment]
My server is running DigitalOcean's Ubuntu Server 16.04LTS 64bit server. I am using the Chrome version of 53.0.2785.116 m (64-bit)
You can download the zip here: http://www.filedropper.com/gravzip

As a side note I followed this tutorial exactly with a fresh droplet: https://learn.getgrav.org/webservers-hosting/vps/digitalocean

**Comment by w00fz** [comment]
Please look in your chrome dev tools and see if there are any js errors.
This is most likely a client side issue but we need more details about what's causing it.

**Comment by TheMarkCP** [comment]
I got this js error from chrome's inspect. I do use cloudflare for the website, but right now I have paused cloudflare's service, this error still occurs.

Error: admin:11 A Parser-blocking, cross-origin script, https://ajax.cloudflare.com/cdn-cgi/nexp/dok3v=0489c402f5/cloudflare.min.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.

**Comment by TheMarkCP** [comment]
Update: Problem fixed, it was due to Cloudflare's JS optimization service that caused an error.

**Comment by TheMarkCP** [comment]
Thank you so much for the help guys!

**Comment by w00fz** [comment]
👍
