### ISSUE TITLE
Ugly "NOTE:" on creating new posts

### ISSUE THREAD

**Issue by sekjun9878** [getgrav/grav-plugin-admin#798]
![screenshot from 2016-09-26 19 19 32](https://cloud.githubusercontent.com/assets/2097812/18830060/345404ac-841e-11e6-8a4b-f5a2bf85003f.png)

**Comment by metadiv** [comment]
I am getting this too.

Appears upon creation of a new page (before being saved). It appears in conjunction with any media upload or selection fields on the page type blueprint.

**Comment by w00fz** [comment]
That is ugly! 
Thanks, will look into it.

**Comment by blizam** [comment]
I wasn't ugly in 1986

![d6xjac-l-610x610-shirt-vintage-80s-color block sweatshirt-90s style-hip hop 1](https://cloud.githubusercontent.com/assets/8940155/18958724/d0bf79ee-8620-11e6-8429-04925532ffae.jpg)

:D

**Comment by w00fz** [comment]
The ugliness has been defeated!

**Comment by sekjun9878** [comment]
Thanks!
