### ISSUE TITLE
problem with caching with php-7 and acpu

### ISSUE THREAD

**Issue by Enemico** [getgrav/grav-plugin-admin#799]
Hi, i am running the latest Grav on an Ubuntu 16 installation. 
These are the php related packages installed:

libapache2-mod-php7.0
php7.0
php7.0-cli
php7.0-common
php7.0-curl
php7.0-fpm
php7.0-gd
php7.0-json
php7.0-mbstring
php7.0-opcache
php7.0-readline
php7.0-xml
php7.0-zip

I have tried using "apcu" and "auto" as possible options for caching, but what happens is that if the cache is enabled, whenever i make changes to a blog post, the changes disappear as soon as i press save. The changes are in fact there, ( i can press the "eye" icon to the the page, and they have been added), but on the interface, i need to clear the entire cache to see them in the blog editing window. 
This does not happen if the cache is disabled. 

This does not happen either on our production website (this is a new version we would like to set in production soon) which  is running php5.

**Comment by rhukster** [comment]
Sounds like browser cache more than anything.  Have you tried another browser to see if that makes a difference?

**Comment by Enemico** [comment]
Yeah, i did try both firefox, chromium and opera. 
And if turn caching off on the configuration page, the problem disappears.

**Comment by Enemico** [comment]
It turned out that the problem was actually something different than expected.
I created a deployment script that rolled out our website from git, and that added a symlink under /user/pages with some content, as that content is supposed to be edited and augmented by using the admin interface only. So the problem i reported is true for all content laying under that symlink, and not the rest. Still, i have a +FollowSymlink directive in apache, so this is related to how Grav manages cache in the case of symlinks and files laying one levels under the symlink. Shall i create a new bug?
