### ISSUE TITLE
Cannot put a dot in the folder name

### ISSUE THREAD

**Issue by mikegcox** [getgrav/grav-plugin-admin#8]
I was testing the blog page from the Deliver skeleton.  I had removed the order number from the folder name of the blog page so that it was a hidden page.  Blog page was named `bit-and-bites` I tried to rename it to `09.bits-and-bites` but the UI does not allow me to add a dot in the folder name.  I was also getting an error when saving the page when not in "Expert" mode.  I will report that separately after I test a bit.

**Comment by rhukster** [comment]
Actually i'm still in the process of sorting this issue.  so stand by for an update with this resolved.

**Comment by rhukster** [comment]
Should be fully sorted now.

**Comment by muflone** [comment]
Hi

sorry for reopening an old bug but this issue still persists for me using grav v1.1.5.

I've a folder structure for various assets under /user/pages/resources/version_number/filename.zip and I'm unable to access to any resources when the folder version_number contains any dot, for example the page http://localhost/muflone/resources/0.8.5/gespeaker-0.8.5.zip raises a 404 error.

Renaming the folder 0.8.5 in 0_8_5 everything works fine.

**Comment by muflone** [comment]
changing the requested URL to http://localhost/muflone/resources/8.5/gespeaker-0.8.5.zip everything works fine, thus removing the initial 0.

I understand this is for ordering but is there a way to keep the correct version number for the folders?

**Comment by flaviocopes** [comment]
@muflone looks like a problem of Grav itself rather than the Admin plugin. Opened https://github.com/getgrav/grav/issues/1090
