### ISSUE TITLE
Videos inserted as link rather than media

### ISSUE THREAD

**Issue by metadiv** [getgrav/grav-plugin-admin#800]
I have noticed that videos inserted from page media via the 'insert' button are inserted as a link rather than media.

Insert button:
``` markdown
[alt_text](video.mp4)
```

Should be:
``` markdown
![alt_text](video.mp4)
```

The preceding `!` is not inserted as it would be with an image inserted in the same way.

Is this a bug or a deliberate choice?

**Comment by rhukster** [comment]
It's a deliberate choice.  https://github.com/getgrav/grav-plugin-admin/issues/759
