### ISSUE TITLE
admin.min.js source map?

### ISSUE THREAD

**Issue by oneoftwo** [getgrav/grav-plugin-admin#801]
Hi,

admin.min.js at the bottom specifies

`//# sourceMappingURL=admin.min.js.map`

However, no such file exists. I'm not well versed with javascript... Is this file supposed to be generated dynamically, and/or does that require some special server configuration? From what I see, though, the file is generated at compilation and thus should be included in the module?

The non-existence of the file appears to at least be contributing to the error messages I'm currently trying to work with my host to sort through.

Thanks in advance.

**Comment by w00fz** [comment]
We don't include the sourcemaps in the repository because they are too big and their only purpose is really for development. (https://github.com/getgrav/grav-plugin-admin/blob/develop/.gitignore#L8)

The browsers ignore that line if there is no developer tools open and if the file is missing. You can also disable from the browser developer tools the sourcemaps if you don't need any of that.

If you want to generate them, you can clone this repo and under `themes/grav` where there is the `package.json` (https://github.com/getgrav/grav-plugin-admin/tree/develop/themes/grav), you can run the command `npm install && npm run dev`

**Comment by oneoftwo** [comment]
Ah, thanks. I just tried to compile, but it failed with many warnings and errors along the way. npm-debug.log below. What are the requirements apart from node.js & npm?

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.3
3 info using node@v6.7.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle grav-admin@1.0.0~predev: grav-admin@1.0.0
6 silly lifecycle grav-admin@1.0.0~predev: no script for predev, continuing
7 info lifecycle grav-admin@1.0.0~dev: grav-admin@1.0.0
8 verbose lifecycle grav-admin@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle grav-admin@1.0.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\MSALUSER\Downloads\grav-plugin-admin-develop\themes\grav\node_modules\.bin;C:\Program Files\nodejs;C:\Users\MSALUSER\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\MiKTeX 2.9\miktex\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files (x86)\IVI Foundation\IVI\bin;C:\Program Files\IVI Foundation\IVI\bin;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin\;C:\Program Files\IVI Foundation\VISA\Win64\Bin\;C:\Program Files\Agilent\IO Libraries Suite\bin;C:\Program Files\IVI Foundation\VISA\Win64\agvisa;C:\Program Files (x86)\Agilent\IO Libraries Suite\bin;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\agvisa;C:\Program Files\MATLAB\R2014b\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\80\Tools\Binn\;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\National Instruments\Motion Assistant\bin\mxwplugins;C:\Program Files (x86)\LyX 2.1\Perl\bin;C:\Program Files\nodejs\;C:\Users\MSALUSER\AppData\Roaming\npm
10 verbose lifecycle grav-admin@1.0.0~dev: CWD: C:\Users\MSALUSER\Downloads\grav-plugin-admin-develop\themes\grav
11 silly lifecycle grav-admin@1.0.0~dev: Args: [ '/d /s /c',
11 silly lifecycle   'webpack --progress --colors --config webpack.conf.js' ]
12 silly lifecycle grav-admin@1.0.0~dev: Returned: code: 4294967295  signal: null
13 info lifecycle grav-admin@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: grav-admin@1.0.0 dev: `webpack --progress --colors --config webpack.conf.js`
14 verbose stack Exit status 4294967295
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid grav-admin@1.0.0
16 verbose cwd C:\Users\MSALUSER\Downloads\grav-plugin-admin-develop\themes\grav
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.7.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error grav-admin@1.0.0 dev: `webpack --progress --colors --config webpack.conf.js`
22 error Exit status 4294967295
23 error Failed at the grav-admin@1.0.0 dev script 'webpack --progress --colors --config webpack.conf.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the grav-admin package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack --progress --colors --config webpack.conf.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs grav-admin
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls grav-admin
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]`

**Comment by w00fz** [comment]
I never used it on windows so I'm not quite sure

**Comment by w00fz** [comment]
I'm not quire sure also what is the issue and why you do need the sourcemaps. I am quite positive that you could even just create an empty file called `admin.min.js.map`, put at the same location where `admin.min.js` is, and you should be good with just that.

**Comment by oneoftwo** [comment]
The empty file is not a bad idea just for getting rid of the load error that my webhost is logging, probably.

The reason the source map would still be nice is that I assume it would allow me to locate the error I'm getting in admin.min.js more accurately (as compared to the ?0495866071:1 and :4 I'm getting below) -- an error message box flashes on login with "Fetch failed: Crikey! There was an error…" and more text than it can handle below. Site inspection shows

`admin.min.js?0495866071:1   POST http://[site]/admin 500 (Internal Server Error)`

and 

`admin.min.js?0495866071:4   Crikey! There was an error...` (plus a ton of CSS and JS)

Note that the underlying error is almost certainly in my host's php configuration, but I want to track things down a little more accurately.

**Comment by w00fz** [comment]
Yeah for debugging purposes the sourcemaps are definitely more helpful.
The error indicates it's failing running webpack, have you installed it? `npm i -g webpack`

**Comment by w00fz** [comment]
Oh actually I'm getting the error with that command! The proper command to run should be `gulp js` and what you need is `npm i -g gulp-cli`.

I'm sorry I have way too many projects with different ways of compiling js and got lost for a moment there. 😄

**Comment by oneoftwo** [comment]
Excellent, that worked! Thanks again.

**Comment by w00fz** [comment]
No problem! 👍
