### ISSUE TITLE
Uploading files doesn't work

### ISSUE THREAD

**Issue by iamlinkus** [getgrav/grav-plugin-admin#803]
Hey! Just updated the plugin, and it broke the pagemedia upload. Whenever I drop or select a file using the media upload, js throws this error:

`TypeError: r["delete"] is not a function. (In 'r["delete"]("task")', 'r["delete"]' is undefined)`

Encountered this problem on MacOS Sierra Safari.

**Comment by w00fz** [comment]
Please see #772
