### ISSUE TITLE
Changes Detected on Navigating away from Content Edit Page without making any changes

### ISSUE THREAD

**Issue by fahim0173** [getgrav/grav-plugin-admin#804]
I have a content type using a custom tab to select page section specific field images(using pagemediaselect) and  text fields such as Address without requiring any validations.

Once I create a content for the page and then try to navigate to any other Admin Dashboard pages, I get a Pop Up warning stating that 
"You have unsaved changes. Are you sure you want to leave without saving?"

This message is also displayed when I try to go the content edit page and try to navigate way without making any changes. 

I am not sure that if this is a bug or something that I am doing wrong, would greatly appreciate a feedback on the issue.

Cheers

**Comment by rhukster** [comment]
Do you have any auto-complete fields getting populated?  I have noticed i have this problem sometimes, but it's a browser filling in form fields automatically.
