### ISSUE TITLE
Invalid AJAX and Filesystem Iterator Error

### ISSUE THREAD

**Issue by kalebheitzman** [getgrav/grav-plugin-admin#805]
Not sure what's causing this. I would try to debug if I knew where to look. When adding a module I get an Invalid AJAX error first.

<img width="969" alt="5f8a7cc2-8311-11e6-9260-d9d499edb016" src="https://cloud.githubusercontent.com/assets/313598/19012521/7856d9c0-8786-11e6-8ece-7622c4d7bc00.png">

After I save a new module (any new module), I get this error:

![screen shot 2016-10-01 at 3 23 23 am](https://cloud.githubusercontent.com/assets/313598/19012532/ad493506-8786-11e6-91ea-a85f6ba675ad.png)

This happens on both a development and production server.

**Comment by rhukster** [comment]
Are you all up to date with Grav + Admin?  How about Plugins?  Which plugins do you have running?

**Comment by flaviocopes** [comment]
If you can, send me the `user/` folder of your site via https://gitter.im/flaviocopes and I'll try recreating the problem locally
