### ISSUE TITLE
Scrollbar not at right border

### ISSUE THREAD

**Issue by Tamriel** [getgrav/grav-plugin-admin#810]
I often miss the scrollbar, because it is not at the right screen edge.

**Comment by flaviocopes** [comment]
Which browser are you using? Isn't the page scrolling, or simply you don't see the scrollbar?

**Comment by Tamriel** [comment]
The functionality is alright, but there is a lack of usability, because there is a small gap between the scroll bar and the right edge.
It's no bug but a design issue. It's for me in Firefox and Chromium.
![scrollbar](https://cloud.githubusercontent.com/assets/5037153/19196655/af53e622-8cb6-11e6-9666-c3f10163bdd6.png)

**Comment by flaviocopes** [comment]
I'm not sure I "get" it. What should be the behavior you expect?

**Comment by rhukster** [comment]
there is a 2px gap. It's to help with visual separation between the edge of the screen and the scrollbar.  Yes it's a design choice, but I don't think it effects usability.

**Comment by Tamriel** [comment]
I am sure it's not only me who often misses the scrollbar. Please fix this!

At university I learned the scientific explanation for this, it's called [Fitts's Law](https://www.google.de/search?q=fitts%20law%20edges): 

>   The outer edges and corners of the graphical user interface can be acquired with greater speed than anywhere else in the display, due to the pinning action of the screen.
