### ISSUE TITLE
Can not Upload Media

### ISSUE THREAD

**Issue by Klex167** [getgrav/grav-plugin-admin#811]
Hello,

everytime when i try to upload a photo grav crashes... 
![bildschirmfoto vom 2016-10-05 18-15-18](https://cloud.githubusercontent.com/assets/7307147/19121740/d235a634-8b27-11e6-8180-eac1eaeaad1d.png)

Grav shows a Thumbnail and a bar for loading.
When it finished it shows the error. 
My PHP can Upload 300MB.
My Media has < 1MB.

**Comment by flaviocopes** [comment]
Uhm... that "Unknown errors" message appears because uploading generated an error we don't expect.

Try going into this line

https://github.com/getgrav/grav-plugin-admin/blob/develop/classes/controller.php#L1190

and edit

```
'message' => $this->admin->translate('PLUGIN_ADMIN.UNKNOWN_ERRORS')
```

to

```
'message' => $this->admin->translate('PLUGIN_ADMIN.UNKNOWN_ERRORS') . $_FILES['file']['error']
```

is it giving you a more helpful message?

**Comment by Klex167** [comment]
![bildschirmfoto vom 2016-10-08 15-57-03](https://cloud.githubusercontent.com/assets/7307147/19213597/eeb5be08-8d6f-11e6-90a9-e8030562d673.png)

is this more helpful?

**Comment by flaviocopes** [comment]
Yes, that error points to 
`UPLOAD_ERR_NO_TMP_DIR Value: 6; Missing a temporary folder.`, as described in http://php.net/manual/en/features.file-upload.errors.php

Check that PHP has configured a tmp upload folder (example: https://mediatemple.net/community/products/dv/204644200/how-do-i-set-the-upload_tmp_dir)

**Comment by Klex167** [comment]
Thank You! :)

It Works fine!
