### ISSUE TITLE
Link Button in Editor Shouldn't Start the http://

### ISSUE THREAD

**Issue by FrugalGeek** [getgrav/grav-plugin-admin#813]
I noticed that if I click the link button it generates: `[Linked Text](http://)`. If I'm copying and pasting a URL from another source this creates an extra step as I have to go back and delete the placed `http://`.

Very rarely does someone writing an article or a blog post want to write the url from scratch. More often than not, they'll have a direct URL already copied and ready to be pasted.

So, I suggest having the link button instead create `[Linked Text]()` and place the cursor between the `()`.

**Comment by flaviocopes** [comment]
Same works for the image button. I tend to agree. @w00fz what you think?

**Comment by w00fz** [comment]
I'm ok changing this I just hope it won't be confusing because it does look a bit weird when it's only `[Linked Text]()` :)
