### ISSUE TITLE
Admin panel changing MD code

### ISSUE THREAD

**Issue by pdowse** [getgrav/grav-plugin-admin#82]
When saving a page within the admin panel the MD code get's changed from 
---
services:
    - icon: building
      title: Title Goes Here
      desc: "Description Goes Here"
---

to 

---
services:
    - { icon: building, title: 'Title Goes Here', desc: 'Description Goes Here' }
---

Which seems to be making the page not display properly. 
Examples of pages

[Working Page](http://www.absolutemaintenanceandcleaning.com.au/services/domestic-cleaning-services)
[Page with Issue](http://www.absolutemaintenanceandcleaning.com.au/services/carpet-cleaning-flooring-toowoomba)

MD files for both pages above are zipped and at the following location.

[domestic](http://www.absolutemaintenanceandcleaning.com.au/adminissue/domestic.zip)
[carpet](http://www.absolutemaintenanceandcleaning.com.au/adminissue/carpet.zip)

**Comment by rhukster** [comment]
I think i have a solution for changing how the YAML is saved. It should keep the longer format of YAML for 5 levels instead of 3.  Next release should have this change.  Please reopen if this doesn't resolve.

**Comment by pdowse** [comment]
Awesome....will wait for the next release.
