### ISSUE TITLE
Folder Prefixes by default.

### ISSUE THREAD

**Issue by metadiv** [getgrav/grav-plugin-admin#822]
I have noticed that even if I have my site config file set to use default ordering by default new pages are only created with a folder prefix if there is already a sibling using the prefix. Even if the parent has a prefix the first new child will be created without a folder prefix unless you manually select to add one from the advanced tab.

Whilst this isn't a major issue for me as a developer it is a frustrating extra step for users of the site's backend.

Is there a method via blueprints or settings to enforce folder prefixing either globally or specifically on a certain template type?

**Comment by flaviocopes** [comment]
There is no global setting right now. 

You can pick any blueprint in your theme and override the default values (https://learn.getgrav.org/forms/blueprints/advanced-features#replacing-fields-properties-replace).

**Comment by Maybach91** [comment]
@flaviocopes do you know, how to access it via the blueprint? i’ve tried everything, but couldnt figured it out how to set it to true all the time.
