### ISSUE TITLE
Saved page still get error "Changes Detected"

### ISSUE THREAD

**Issue by moreplavec** [getgrav/grav-plugin-admin#823]
I have new site on Grav but it's impossible to change content. Everytime i try to save, it says "Successfully saved". When i try to leave the edit page, it says: 

**Changes Detected**
You have unsaved changes. Are you sure you want to leave without saving?

I tried to check rights, no problem. Other sites works fine, just this one has such problem. Any tip where to look?

**Comment by w00fz** [comment]
I think i fixed an issue about this and it was related to the Date, it's in the develop branch, not yet released. Do you have any of the date field checked if you go in Options?
Also can you verify that this is not happening for every page? Try creating a new one and just save, see if it happens with it too.

**Comment by moreplavec** [comment]
New page works fine, it's saved fine. But i get error too:

"FilesystemIterator::__construct(user/pages/1000.test): failed to open dir: No such file or directory"

**Comment by w00fz** [comment]
That seems filesystem related, not quite sure what `1000.test` would be? Is that the name of your page?

Regarding the other pages with the Change Detector, did you check the Options tab in those pages where it happens? Is the Date checked?

**Comment by moreplavec** [comment]
I don't get 1000.test too :) I named page Test and it created directory Test as supposed.

I don't use any dates, so all dates are grey.

**Comment by w00fz** [comment]
Could you test with the develop branch if the issue continues? Goes without saying, make a backup first :)

**Comment by moreplavec** [comment]
Wich module? Please, give me download link. I don't want to switch all website to develop, because it's already live and running. Customer needs to be able to work with it.

**Comment by w00fz** [comment]
Make a copy of the site so you can freely test, then you can grab the current develop admin plugin by clicking on the green download button here https://github.com/getgrav/grav-plugin-admin
And unzip it under `user/plugins/admin` to replace the stable version.

**Comment by moreplavec** [comment]
It looks like solved. Thanks!
