### ISSUE TITLE
admin page links not working if home.hide_in_urls: true

### ISSUE THREAD

**Issue by apotropaic** [getgrav/grav-plugin-admin#824]
With this in system.yaml config: 

```
home:
  alias: /blog
  hide_in_urls: true
```

my admin links show up as this for example:

`http://grav.dev/admin/pages/blog/`

Click that tries to create a new page. If I change the url manually to this:

`http://grav.dev/admin/pages/test-post`

It works fine! Also my url http://grav.dev/test-post works too.

**Comment by flaviocopes** [comment]
Where is that link? Is this in the pages list? Can you make a screenshot?

Can't replicate with the latest stable release of Grav / Admin. 
Is all up to date?

**Comment by apotropaic** [comment]
Well, just tried to replicate it myself and was unable to. So I guess its a non-issue... I'll post more details next time if it happens to me again.
