### ISSUE TITLE
Empty page after saving new page with "Hide home route in URLs"

### ISSUE THREAD

**Issue by exoticorn** [getgrav/grav-plugin-admin#826]
When having "Hide home route in URLs" enabled, saving a new page 'foo' with parent Home redirects to /admin/pages/home/home/foo instead of /admin/pages/home/foo and displays empty content for the page.

Grav v. 1.1.5, Admin v. 1.2.2

**Comment by flaviocopes** [comment]
I fixed this over a month ago (https://github.com/getgrav/grav-plugin-admin/commit/fd8c7889d1c3329fc0363cb87b80b49307eef645) but we have not yet released an update. I tested again, it's solved on the latest Admin (`develop` branch), but not in the latest released version.

Thanks for reporting!
