### ISSUE TITLE
Can't see my installed DevTools + Invalid Security Token

### ISSUE THREAD

**Issue by Nck927** [getgrav/grav-plugin-admin#829]
After I installed DevTools, the number of plugins was updated correctly from 7 previously to 8, but then when I click on the menu to go to other page, I got a "Invalid Security Token" on every page.

Apart from that, I can see that the plugin number is inconsistent, on the page of Administrator, Dashboard, Theme, the number of plugin is correct (which is 8), but on other pages, it showed 7. And on the page of Plugins, I can't see the DevTools plugin, I have repeatedly installed the plugin, but it is still the same.

**Comment by flaviocopes** [comment]
Can't replicate any of the issue mentioned. Admin and Grav are all up to date?

**Comment by rhukster** [comment]
Also try logging out and back-in.

**Comment by Nck927** [comment]
I think the issue is not related with the DevTools.

I have tried to reinstall the latest version (Grav v1.1.8 - Admin v1.2.4), at the 1st time of login after I created my admin account, everything was fine, no "Invalid Security Token" notification at any of the pages.

Then I logout, and re-login, the "Invalid Security Token" was not showed until when I click on the menu to go to other page.

Is this the settings with my server? I am using WAMP 3.0.6 for my local server, on latest version of Win 10.

**Comment by Nck927** [comment]
Previously, I was using Microsoft Edge (38.14393.0.0).

Then I tried using Firefox (49.0.1) to login, then I tried to install the DevTools again, this time, the plugin was installed properly, the number of plugin is being showed properly on the menu no matter which page I go, and I can see the DevTools on the plugin page itself.

But now I do get a "Fetch Failed: NetworkError when attempting to fetch resource" error occasionaly when I go to configuration page or plugin page, not everytime though. What's the cause of this? Slow internet speed?

**Comment by flaviocopes** [comment]
We mainly test with Chrome / Firefox, IE and Edge get the least attention because they can't run on a Mac. Looking if I can replicate.

**Comment by Nck927** [comment]
Maybe this is related to issue #764 (caching problem in MS Edge)

**Comment by ponderboy** [comment]
I have this as well. And I have to include `{{ assets.js() }}` in the head. The devtools need jquery, don't they?
