### ISSUE TITLE
Getting "Twig_Error_Runtime" When i click on Themes or Plugins Page

### ISSUE THREAD

**Issue by spmredmi** [getgrav/grav-plugin-admin#831]
Hello,

I Just installed Grav via Softaculous and i am getting quite a few errors right away :( 

Specially on Plugins and Themes Page
http://prntscr.com/cwx9qr

Can you please tell me how can i Fix this.
Regards
Alex C.

**Comment by rhukster** [comment]
https://github.com/getgrav/grav/issues/1120#issuecomment-255164243

Is the quick fix.. We're going to push out a release tomorrow that will resolve it going forward.

**Comment by spmredmi** [comment]
@rhukster Thanks for the Quick reply :) 

I just checked the settings page in grav admin panel of my site (domain.com/admin/config/system) and there is no "Remote Verify Peer (SSL)" option in there.

Am looking at the wrong page?

**Comment by rhukster** [comment]
It should definitely be there in Grav 1.1.6 with Admin 1.2.3:

![2016-10-20 at 7 55 pm](https://cloud.githubusercontent.com/assets/1084697/19584103/3393935e-96ff-11e6-9080-94f31ff58913.png)

**Comment by spmredmi** [comment]
Mine is http://i.imgur.com/kAWf1OT.png

**Comment by spmredmi** [comment]
This worked :)
http://i.imgur.com/0ge09mc.png

**Comment by rhukster** [comment]
Is your admin version 1.1.6??

**Comment by rhukster** [comment]
Oh I see it's not. Weird. The package on getgrav.rg contains the latest version.
