### ISSUE TITLE
AdminController#taskGetFilesInFolder returns image alternatives

### ISSUE THREAD

**Issue by fredrikekelund** [getgrav/grav-plugin-admin#838]
When using the `filepicker` field, image alternatives are listed – eg. `example.jpg`, `example@2x.jpg`, `example@3x.jpg` and so on.

While the filepicker isn't more generalized than `pagemediaselect` was, I still think this is a bug, and it would definitely be confusing for people who aren't wholly familiar with how image alternatives work in Grav.

**Comment by flaviocopes** [comment]
Technically this is a file picker, so one could be allowed to also choose @2x images if there is a valid use case for it (I can't imagine one now, but might be)

**Comment by flaviocopes** [comment]
There can be an option in the field properties

**Comment by fredrikekelund** [comment]
Hmm, I don't really see any applicable use cases either. Seems like an option couldn't hurt (but the default ought to be to hide them). On the other hand, image alternatives can't even be directly accessed from the `$page` object AFAIK, so maybe we should just count them as part of the base image and always avoid listing them

**Comment by fredrikekelund** [comment]
Opened a PR for this: #848

**Comment by flaviocopes** [comment]
Thanks, merged
