### ISSUE TITLE
Missing Template: partials/users-list.html.twig

### ISSUE THREAD

**Issue by bbdstar** [getgrav/grav-plugin-admin#839]
I am looking for a list of users but if I navigate to the URL /admin/user I get the following error. 

RuntimeException (400)
Template "partials/users-list.html.twig" is not defined in "user.html.twig" at line 30.

It seems as though there is a template file missing.

Is there a better way to list/manage all users from the admin panel?

**Comment by flaviocopes** [comment]
User management is not part of Admin. We'll have a user and groups / ACL management capability in Admin Pro.
