### ISSUE TITLE
Redirection fails after saving a page

### ISSUE THREAD

**Issue by parcand** [getgrav/grav-plugin-admin#843]
This problem seems to happen when I try to save a localized page, for which multiple parts of the URL have been translated with slugs overrides. The redirection mechanism seems to replace only the first part of the URL, leaving the remaining slugs untranslated.

![capture](https://cloud.githubusercontent.com/assets/22176950/19820200/34f602ea-9d26-11e6-9c33-87c9d3d6fe7f.gif)

![localized slugs](https://cloud.githubusercontent.com/assets/22176950/19820217/44c8a56a-9d26-11e6-8900-080b03181497.png)
![slug](https://cloud.githubusercontent.com/assets/22176950/19820219/4556f52c-9d26-11e6-92e6-6984840059cf.png)

**Comment by rhukster** [comment]
Really nice write up BTW. This is something I could of sworn I fixed.  We need to be using the 'raw-route' for all these page urls for this very reason.  We'll look into it!

**Comment by parcand** [comment]
👍

**Comment by flaviocopes** [comment]
What is the actual folder path of that page? Is it in english, or in french?

**Comment by parcand** [comment]
The actual folder path is user/pages/01.antidote-9/01.utilisation-avec-vos-logiciels/03.mac/12.copier-coller/

French is the default language for this site.

**Comment by flaviocopes** [comment]
Ok took me a while to "get" it but I recreated the problem.
