### ISSUE TITLE
You have been successfully logged in

### ISSUE THREAD

**Issue by Endogen** [getgrav/grav-plugin-admin#851]
When i login, i see the message `You have been successfully logged in`. I would argue that this is a pretty clear case of "stating the obvious" and that this message is useless.

**Comment by rhukster** [comment]
Doesn't hurt though, and it's a flash message so goes away after it's been displayed once.

**Comment by Endogen** [comment]
That's true, displaying useless information doesn't hurt anybody, it's just useless ;) But that's ok. I just don't get it.
