### ISSUE TITLE
Behaviour of include_default_lang

### ISSUE THREAD

**Issue by billhemsley** [getgrav/grav-plugin-admin#858]
With include_default_lang: false the language code is not prefixed in the URL; with include_default_lang: true it is.

This is the opposite of what the documentation states at https://learn.getgrav.org/content/multi-language#default-language-prefix.

I guess the documentation is wrong, but possibly the behaviour is not what is intended.

**Comment by flaviocopes** [comment]
Right, the description is wrong but the example is ok. Fixing, thanks
