### ISSUE TITLE
Posting content (blog post) via admin results in garbled layout

### ISSUE THREAD

**Issue by reachcontent** [getgrav/grav-plugin-admin#86]
I posted an new blog post via the admin interface for the first time. It appears correctly on the home page, but when you click to read the whole post:
1. Title does not display, neither do tags nor content navigation (prev./next)
2. Breadcrumbs appear below the post
3. [Desktop] Post content takes full width and column is displayed below

The only other change I performed since posting the article is adding the Archive Plus plugin.
Otherwise my Grav install is mostly default, with Antimatter theme and 19 plugins in total.

Posted through Admin:
http://reachcontent.com/blog/reactivite-devenez-agile-scrum-projet
all previous articles were uploaded manually.

**Comment by flaviocopes** [comment]
Check the page type, seems it's not 'Item' but 'Blog'

**Comment by reachcontent** [comment]
Ok, my mistake...
I tried to modify this in the admin but I guess my hosting (varnish again) prevents me from using it properly: I get error > 503 EService Unavailable
> Varnish L7 server
whenever I try to save any changes to the content item. So I had to update the content manually.
