### ISSUE TITLE
Update plugins with rc version

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#860]
I have Grav v1.1.9-rc.1 installed, but not able to update:
```
Admin Panel, from v1.2.4 to v1.2.5-rc.1
Login, from v2.1.2 to v2.2.0-rc.1
```
because of:
`One of the packages require Grav >=1.1.9. Please update Grav to the latest release.`

I assume this should be allowed, but currently not possible from the admin.

**Comment by rhukster** [comment]
Ok, thanks for this, it seem the semantic version check doesn't consider RC's to be high enough.  A quick fix is to change the Grav version in the `system/defines.php` to `1.1.9`.  Then things will install.

**Comment by Quy** [comment]
OK. Now I am getting this error with the `Login` plugin when attempting to update:
`Cannot use Grav\Plugin\Admin as Admin because the name is already in use`

**Comment by flaviocopes** [comment]
Yes confirmed, `1.1.9-rc.1` is not considered yet `1.1.9` so it fails the check.

I can't replicate the problem you got when updating the Login plugin though.

**Comment by flaviocopes** [comment]
Fixed in the plugins repos (https://github.com/getgrav/grav-plugin-login/commit/d5aea4b15225bf900a14cd21a0819d7a89eccb3e)
