### ISSUE TITLE
1.1.9 causes errors with updating or installing plugins

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav-plugin-admin#868]
Hi guys,
As Flavio said on Gitter, by changing the define.php file to state grav version 1.1.9 instead of 1.1.9-rc1 should work to install updated plugins.

However, it seems that a fresh install of grav - update to rc1 breaks the update functions. You can go through the process and click buttons but the update doesnt occur.
With the stable release, no issues with updates or new plugins being installed through Admin interface.

**Comment by JohnMica** [comment]
it could be either the latest Admin rc or the Grav rc - not sure

**Comment by rhukster** [comment]
Hmm.. I know this was an issue with the first RC release of the login plugin as it was requiring Grav `>= 1.1.9` and the `1.1.9-rc.1` release was being considered to low a version.  However, I recently released and `rc.2` of the login plugin with a `> 1.1.8` requirement, so it should be sorted. 

So can you tell me what versions of the various Grav + plugins you have installed to cause such a problem.

**Comment by JohnMica** [comment]
Hi Andi, the versions were - Grav 1.1.9, admin - latest rc 1.2.5 and would not update any plugin (testing/stable) that were on the system - default install of admin so email, login, form, etc ...
also it seems that the CLI update is not working at all (1.1.8 stable) as per the picture in Gitter - error downloading package

**Comment by rhukster** [comment]
Ok, I will take a look to see what's causing this. Thanks.

**Comment by rhukster** [comment]
Ok just tested with CLI and it worked fine:

```
/Users/bob/workspace/grav-admin-rc-test [bob@compy] [9:04]
> cat user/config/system.yaml| grep releases:
  releases: testing

/Users/bob/workspace/grav-admin-rc-test [bob@compy] [9:04]
> bin/gpm selfupgrade

GPM Releases Configuration: Testing

Grav v1.1.9-rc.1 is now available [release date: Wed Nov  9 10:59:11 2016].
You are currently using v1.1.8.
Would you like to read the changelog before proceeding? [y|N] n
Would you like to upgrade now? [y|N] y

Preparing to upgrade to v1.1.9-rc.1..
  |- Downloading upgrade [2.43M]...   100%
  |- Installing upgrade...    ok
  '- Success!


Clearing cache

Cleared:  /Users/bob/workspace/grav-admin-rc-test/cache/*

Touched: /Users/bob/workspace/grav-admin-rc-test/user/config/system.yaml


/Users/bob/workspace/grav-admin-rc-test [bob@compy] [9:05]
> bin/gpm update

GPM Releases Configuration: Testing

Found 8 packages installed of which 3 need updating

01. Admin Panel     [v1.2.4 -> v1.2.5-rc.2]
02. Form            [v2.0.6 -> v2.0.7]
03. Login           [v2.1.2 -> v2.2.0-rc.2]

Continue with the update process? [Y|n] y

GPM Releases Configuration: Testing



Preparing to install Admin Panel [v1.2.5-rc.2]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...    ok
  '- Success!

Preparing to install Form [v2.0.7]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...    ok
  '- Success!

Preparing to install Login [v2.2.0-rc.2]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...    ok
  '- Success!


Clearing cache

Cleared:  /Users/bob/workspace/grav-admin-rc-test/cache/compiled/*

Touched: /Users/bob/workspace/grav-admin-rc-test/user/config/system.yaml
```

Also tested with admin:

1) Set `gpm: release: testing` in system config
2) Updated Grav to `1.1.9-rc.1`
3) Updated **All Plugins**:

![2016-11-20 at 9 09 am](https://cloud.githubusercontent.com/assets/1084697/20464215/2875f24a-af01-11e6-8502-bd0ffa1ccda8.png)

All success, no errors.

Try forcing a check of GPM with latest versions by clicking "Check for Updates"

**Comment by flaviocopes** [comment]
Also, since you're updating from an older version, try checking https://learn.getgrav.org/troubleshooting/common-problems#cannot-connect-to-the-gpm

**Comment by JohnMica** [comment]
i posted a link for the whole setup - now on Github - i've been using mamp since i started with Grav and it worked out of the box - I've done the steps there and i have curl and openssl by default active on the system (it is so reported by grav inside the configuration information). not sure what the bug is - maybe a mamp 4.06 issue with php 7.02 (if i remember the correct version). link it here as well - https://github.com/JohnMica/TestCanabis

**Comment by flaviocopes** [comment]
I checked the package, there are no plugins to update but I tried downgrading a plugin and running the update, it worked fine.

I tried using the CLI, not Admin. Do you have problems also with the CLI?

**Comment by JohnMica** [comment]
hy guys, like i said it was a small setting that i have missed.
Fresh install with peer-setting true - cannot install through cli (but can install through Admin).
peer-setting - false - can use the cli and Admin to install stuff. 

thanks for the prompt replies.
