### ISSUE TITLE
Add site languages to language selection for user in admin panel.

### ISSUE THREAD

**Issue by maxlysenko** [getgrav/grav-plugin-admin#87]
For now only languages of the admin plugin `languages.yaml` file are listed in the dropdown for user language in admin panel. For example I have translation of admin plugin for particular site language in `user\languages`  (and it works if this language is specified manually in `user\accounts\admin.yaml`, but this language is not available for selection in admin panel.

**Comment by flaviocopes** [comment]
We're making changes in the admin panel regarding languages and content translations, we hope to release an update very soon. In short, you'll be able to set the admin language to any of the languages in which the admin plugin is translated. We currently have english, german, italian.
Language in the admin will be independent from the "frontend" side.

**Comment by rhukster** [comment]
This duplicates functionality we already have fixed in develop :)
