### ISSUE TITLE
Admin font doesnt support cyrillic

### ISSUE THREAD

**Issue by codev0** [getgrav/grav-plugin-admin#870]
Hi.
Default font doesnt support cyrillic symbols.
![Screenshot](https://i.imgur.com/SkV6UAe.png)

**Comment by flaviocopes** [comment]
What's the problem, apart from it being rendered a bit bigger? (is that the problem?)

**Comment by rhukster** [comment]
You can turn off the Google fonts, then it will use your system fonts and support Cyrillic symbols.
