### ISSUE TITLE
Long page title breaks design

### ISSUE THREAD

**Issue by codev0** [getgrav/grav-plugin-admin#871]
![Screenshot](https://i.imgur.com/QsIKidq.png)

**Comment by flaviocopes** [comment]
A solution is to use dots at the end and cut it:

![screen shot 2016-11-25 at 21 15 26](https://cloud.githubusercontent.com/assets/11783388/20634739/59c2245c-b354-11e6-8831-7fb6ba00bfb2.png)

or put it on 2+ lines but with a better layout than this
