### ISSUE TITLE
Translation Issue

### ISSUE THREAD

**Issue by angelexevior** [getgrav/grav-plugin-admin#88]
When you disable translations in config and supported is empty, the language file is not parsed correctly or misses one. Starting from login screen buttons and throughout several parts of admin.
e.g. login button displays  LOGIN_BTN   instead of string provided in language file.

**Comment by rhukster** [comment]
Is this with the latest "develop" branch, or latest released version? Lang and translations have seem major updates since the last release.  New version is planned for early this coming week.

**Comment by flaviocopes** [comment]
@angelexevior can you confirm this happens with the latest release?

**Comment by angelexevior** [comment]
Hi, yes, this is latest release (Not Dev)
Just saw the new version released. will upgrade and report back if resolved.
Soz for delay, been out.

**Comment by angelexevior** [comment]
nop, crikey ;) , something else went completely wrong there mates.

upgraded to 0.9.39,   admin 0.3.0

This broke the whole admin side. 
…/­system/­src/­Grav/­Common/­Language/­Language.php 381
Call to a member function get() on a non-object

I am just starting to get involved in this so not sure where to get more info for you guys.
I'll try to dig in myself too, see if i figure out the mechanics behind it (Still studying your code).

**Comment by rhukster** [comment]
Current admin version is at **0.4.2**, are you sure you updated it properly?

**Comment by angelexevior** [comment]
my bad... 0.4.2 it is.  
confused 0.3.0 with another plugin just before site broke.

**Comment by angelexevior** [comment]
Care to explain this pls, i may be able to make sense or at least help figure it out.

error occurs on line 381 as above which is this:
 $this->config->getLanguages()->get($lang . '.' . $key, null);

BUT $this->config is defined in construct as:
$this->config = $grav['config'];
didn't find any other overrides of it.

getLanguages() doesn't exist....  //except as native $this function in same file.

Any ideas?

**Comment by rhukster** [comment]
```
$this->config = $grav['config'];
```

This is actually getting the Config instance from the Grav locator service. That is of type `Grav\Common\Config\Config.php`, that contains the method to `getLanguages()`

Can you clear all the cache with:

```
bin/grav clear --all
```

Really that should all work just fine..

**Comment by angelexevior** [comment]
Yeah, found that moments ago while studying the code.

cache was cleared a few times. Just tried again to no avail.

Still, printing out $this->config->getLanguages() returns null

Tried backwards assuming it's not a software bug but some erroneous setting i managed to pull through admin but none found. Best guess was empty [languages] but even after pulling an [en, fr] in there, no result.

Enabling/disabling translations does not resolve either.

**Comment by flaviocopes** [comment]
This should be fixed by https://github.com/getgrav/grav-plugin-admin/commit/ea30fcc43f0aa08b3baec88e12c6bdf3dc1127c6

**Comment by angelexevior** [comment]
Re-cloning grav (not admin) from git solved the issue. 
could not replicate error again while trying different scenarios. 
Best guess, corrupted file or installation

closing issue
