### ISSUE TITLE
Cannot Add Page

### ISSUE THREAD

**Issue by poerwiyanto** [getgrav/grav-plugin-admin#882]
Hi, I just installed grav-plugin-admin. I tried to add page, but the form did not appear (I can only see gray background). I tried using Chrome and Firefox, but still got the same issue. I checked the developer tool and there is no error. Can somebody please help me?

**Comment by flaviocopes** [comment]
Are you using the latest version of Grav / Form plugin / Admin plugin?

**Comment by poerwiyanto** [comment]
Yes, I also cannot add folder and moduler.

**Comment by flaviocopes** [comment]
Can you make a screenshot of the problem?

**Comment by poerwiyanto** [comment]
I encountered the same issue when I clicked changelog button in [Plugins](https://getgrav.org/downloads/plugins). I asked my friend to try those buttons and he said that he encountered the same issue.
![capture_1](https://cloud.githubusercontent.com/assets/12395856/20843374/f1d8acd2-b86f-11e6-8438-ee1ea932c47e.PNG)
![capture_2](https://cloud.githubusercontent.com/assets/12395856/20843376/f1e52750-b86f-11e6-8540-9844a4ebc806.PNG)
![capture_3](https://cloud.githubusercontent.com/assets/12395856/20843375/f1db5810-b86f-11e6-8181-2994ffc174f4.PNG)

**Comment by flaviocopes** [comment]
The problem on your site is one thing, but the problem on getgrav.org is completely different. Might be linked as both open a modal, but not sure why they both would not work for you, on two different browsers. Maybe it's a browser extension? Can you try in private/incognito mode, as this should disable any browser extension?

**Comment by poerwiyanto** [comment]
I tried that. Sometimes it works, other times it does not.

**Comment by mashanz** [comment]
I am new using grav just a view hours ago. And I got the same problems after installing latest admin plugin, I cannot "add or delete page".

after reading @poerwiyanto problems, I know what the problem is.

> we both have "**ads block plugin**" activated on the browser.

Just **dissable the plugin**, grav admin works well perfectly.
because grav command sometimes simmilar as ad commands I think.
