### ISSUE TITLE
50x error when login and logout to Admin

### ISSUE THREAD

**Issue by epomschar** [getgrav/grav-plugin-admin#883]
I get error message when login or logout to Admin.
```
Error while serving request

Server didn't return any web site which can be shown.
Probable cause of problem is in script which generates this web page.
```
On page refresh I get to Admin but with error message `Invalid Security Token` The same happens on logout.

**Comment by rhukster** [comment]
What webserver are you running? Also what is your webserver/vhost config looking like?

**Comment by epomschar** [comment]
It is Apache on Linux. PHP version from 5.6.28.

I have changed PHP version from 5.6.28 to 7.0.13. And that helped. On a clean Grav install from Git with Admin plugin. That fixed it. 
However the Skeleton Blog Antimatter install returns different issue:
```
Fetch Failed:
Whoops there was an error!
html, body {
height: 100%
}
body {
margin:0 3rem;
padding:0;
font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size:
...
```

**Comment by flaviocopes** [comment]
I can't see the mentioned error in your test site. Can you try clearing your browser cache / access in incognito mode?

**Comment by epomschar** [comment]
Tha is correct. All in place on incognito mode. My bad. Sorry. This can be closed. However the previous issue was real and the PHP version changed helped.

**Comment by flaviocopes** [comment]
Not seen that before, it could be some misconfiguration in the PHP 5.6 config that was cleared when switching to 7.0. 

It will stay searcheable in the issues, so if someone else stumbles on this, comment here

**Comment by epomschar** [comment]
@flaviocopes . Ok so it was not an issue with cache. In the meantime when you were trying the web admin switched version PHP from 7.0 to 5.5. And all is good. 

Obviously PHP 5.6 causes issues then I guess.
