### ISSUE TITLE
Creating a new folder during page creation

### ISSUE THREAD

**Issue by miljan-aleksic** [getgrav/grav-plugin-admin#884]
A blog I am working on has its pages organized by folders, eg. `2016/01/my-post'. By using '@self.descendants' the display remains the same. But when creating a new page only an existing folder can be chosen as parent, there is no way of creating a new folder, making it necessary to manually do that part.

The ideas is that the Author has no need to touch the files directly. Did I perhaps missed how this could be done from the Admin?

**Comment by flaviocopes** [comment]
You can create folders to organize your content (using the "Add Folder" menu). You can create a `2016` folder, a `01` folder inside it, and then create the post inside it. 

Currently that's the only way, there is no option to create a multiple levels hierarchy directly when creating a page

**Comment by miljan-aleksic** [comment]
Ah, didn't saw that option! Tks :)
