### ISSUE TITLE
Grav Admin (or plugin dependency) appears to require PHP7

### ISSUE THREAD

**Issue by bassplayer7** [getgrav/grav-plugin-admin#886]
Today, I was contacted by a client who explained that after updating all the plugins the Grav Admin Panel broke. He said he had emailed someone (not sure who) who had indicated it could be a PHP version problem. I upgraded the site to PHP 7 and the problem was immediately fixed. To be clear, the front end of the Grav site worked perfectly through this.

This is what the admin panel looked like on PHP 5.6:
![screen shot 2016-12-05 at 1 36 03 pm](https://cloud.githubusercontent.com/assets/1171147/20901497/12fbf130-baf0-11e6-907d-b00bb73b9a55.png)

There was an error in the console:
> admin:17 Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://www.sitename.com/".
> (index):1 Uncaught SyntaxError: Unexpected token <

These CSS seem to not be loaded for some reason:

> <link href="/user/plugins/admin/themes/grav/css/datepicker/kendo.common.core.min.css?4b6f576d10" type="text/css" rel="stylesheet" />
<link href="/user/plugins/admin/themes/grav/css/datepicker/kendo.flat.min.css?4b6f576d10" type="text/css" rel="stylesheet" />
<link href="/user/plugins/admin/themes/grav/css/datepicker/grav.overrides.css?4b6f576d10" type="text/css" rel="stylesheet" />

Here are the top ~20 lines of the HTML `<head>`

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Grav Admin Login</title>
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="/user/plugins/admin/themes/grav/images/favicon.png">

                                                                                            <link href="/user/plugins/admin/themes/grav/css-compiled/nucleus.css?4b6f576d10" type="text/css" rel="stylesheet" />
<link href="/user/plugins/admin/themes/grav/css-compiled/template.css?4b6f576d10" type="text/css" rel="stylesheet" />
<link href="/user/plugins/admin/themes/grav/css/font-awesome.min.css?4b6f576d10" type="text/css" rel="stylesheet" />
<link href="/user/plugins/admin/themes/grav/css/chartist.min.css?4b6f576d10" type="text/css" rel="stylesheet" />
<link href="/user/plugins/admin/themes/grav/css/selectize.min.css?4b6f576d10" type="text/css" rel="stylesheet" />
<link href="/user/plugins/admin/themes/grav/css/hint.base.min.css?4b6f576d10" type="text/css" rel="stylesheet" />
<link href="/user/plugins/admin/themes/grav/css/datepicker/kendo.common.core.min.css?4b6f576d10" type="text/css" rel="stylesheet" />
<link href="/user/plugins/admin/themes/grav/css/datepicker/kendo.flat.min.css?4b6f576d10" type="text/css" rel="stylesheet" />
<link href="/user/plugins/admin/themes/grav/css/datepicker/grav.overrides.css?4b6f576d10" type="text/css" rel="stylesheet" />
```

Here are the plugins installed on the site:

![image](https://cloud.githubusercontent.com/assets/1171147/20901659/bfaa1ace-baf0-11e6-8ed8-58992091ed2d.png)

**Comment by w00fz** [comment]
Thank you

**Comment by flaviocopes** [comment]
Never seen this issue before. I tried with a local site and it's fine. @bassplayer7 if you can post me the user/ folder (or the whole site) zipped privately at https://gitter.im/flaviocopes I can try replicating locally. Could as well be a PHP/apache/htaccess misconfiguration as the origin of

`admin:17` Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://www.sitename.com/".`

which leads to CSS not being interpreted.

**Comment by bassplayer7** [comment]
@flaviocopes thanks for looking into this. I will download the files and send them over. 

It would be interesting if it was a misconfiguration because the problem happened after upgrading some of the plugins. Perhaps one of the plugins exposed it whereas it wasn't an issue before?

**Comment by rhukster** [comment]
FYIW i'm running all of these plugins with the exception of `reCAPTCHA Contact`, on PHP 5.6 just fine.

Incidentally that one is the only one **not** a core-team plugin.

**Comment by rhukster** [comment]
BTW, have you tried clearing cache? Could be as simple as a Twig template caching issue.

**Comment by mahagr** [comment]
I'm right now testing admin in PHP 5.6 (been for a few days) and everything works without an issue.

**Comment by flaviocopes** [comment]
Tested the @bassplayer7 site locally and I got no issues with Admin, shows up fine.

**Comment by flaviocopes** [comment]
So looks like a server/configuration issue, not something linked to plugins

**Comment by bassplayer7** [comment]
Thanks guys for testing this and the feedback! Based off of your input, it would look like a server issue or something. It's hosted on Rochen and running very much stock setup, so I'm not sure what it would be. Either way, it does run well on PHP 7.

I did not clear the cache because the admin was inaccessible after the upgrade. That said, SSH (CLI) would work fine and would be a good thing to try.

Thanks again and it sounds like this would be ready to close.

**Comment by flaviocopes** [comment]
Ok, closing. Just for the records, you can clear the cache from the command line too, using `bin/grav clear-cache`
