### ISSUE TITLE
Custom admin route overwritten on Admin Panel Upgrade - Feature Request

### ISSUE THREAD

**Issue by blizam** [getgrav/grav-plugin-admin#889]
Would be nice if a custom admin route is set in admin.yaml to anything besides '/admin' that it is maintained after upgrading the Admin Panel

**Comment by rhukster** [comment]
Custom route should be maintained.  As long as you set this route in `user/config/plugins/admin.yaml` and NOT in `user/plugins/admin/admin.yaml`.

**Comment by blizam** [comment]
gotcha... it looks like the admin FAQ docs were updated with that little note too... should've checked there first. Thanks!

**Comment by rhukster** [comment]
It's the same for any plugin BTW.
