### ISSUE TITLE
z-index of checkbox is interfering with select lists

### ISSUE THREAD

**Issue by akoebbe** [getgrav/grav-plugin-admin#89]
The checkboxes (specificaly in the "Advanced" page tab) is displaying on top of the Display Template select list. Looks like the z-index of the .form-label.block is set too high and getting in the way of the select list.

<img width="600" alt="z-index-problem" src="https://cloud.githubusercontent.com/assets/1044465/9429590/103d9fb0-499b-11e5-9e17-3e81bbe18dd4.png">

**Comment by rhukster** [comment]
What browser is that?

**Comment by akoebbe** [comment]
Argh. Rookie mistake. Chrome 44.0.2403.157 Mac.

I was planning on doing a PR for this tonight, if you're ok with waiting.

**Comment by akoebbe** [comment]
Looks like the z-index was added in commit f4aa929372b6f14ad8b66ef275d0884b6577bd22 but I'm not sure what that commit was dealing with.

**Comment by rhukster** [comment]
yah i'm not seeing this in chrome 44 on mac with develop branch.  Must of fixed it already :)

![pages grav2 2015-08-23 20-45-36](https://cloud.githubusercontent.com/assets/1084697/9431971/fd2f8450-49d7-11e5-83b6-30c5f81b3fed.png)

**Comment by akoebbe** [comment]
Yep. I was looking at the release and not the dev branch. It's fixed in the dev branch. Sorry for the false alarm.
