### ISSUE TITLE
cannot update from 1.19-rc1 as an interesting error comes up

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav-plugin-admin#890]
I have a local MAMP testing platform, grav 1.1.9rc-1 and quite a few plugins (mostly by grav).
I have seen last night that there was an update to 1.1.9-rc2 and a few more updates on plugins.
I clicked the update grav and got an error (as per the attached picture)
I ignored it and updated the plugins -all smooth.
I tried to update the grav again but still the same error.
In my config file the Peer SSL is set to false/no and the gpm is testing.
and the picture attached
![captura de ecran din 2016 12 07 la 23 24 05](https://cloud.githubusercontent.com/assets/7076631/21024866/09c6bb0a-bd7e-11e6-98e7-ca09c93ead0b.png)

PS: I am known for breaking everything so I guess it could be a missing "," or even to much "  " but I'm not exactly sure. I could link a github repo if needed to see all the files.

John

**Comment by rhukster** [comment]
Hi John, so you were going from 1.1.9-rc.1 to 1.1.9-rc.3? or rc.2?

**Comment by JohnMica** [comment]
Andy, 
It was Rc2 to rc3. But I have managed to circumvent this by uploading the local dev. 
Now all seems working and even the contact form is sending emails. It must have been a weird mistake on my part but at least you have the picture ;)

**Comment by rhukster** [comment]
Ok, I was able to replicate a little with RC1, to RC3, but this was a known issue with RC1 because we switched to a composer based autoloader, and that didn't work as great as expected.  Quick fix for me was to use the **new** `direct-install` command:

```
bin/gpm directinstall https://github.com/getgrav/grav/releases/download/1.1.9-rc.3/grav-update-v1.1.9-rc.3.zip
```

To update the Grav core, then the admin plugin:

```
bin/gpm directinstall https://github.com/getgrav/grav-plugin-admin/archive/1.2.5-rc.4.zip
```

Then I was able to update `forms`, `login`, and `email` plugins from the admin just fine.

**Comment by rhukster** [comment]
BTW, this command lets you update or roll back to specific versions, either remote or local.

**Comment by JohnMica** [comment]
all plugins were updated with no issue to the latest realease only grav didnt want to do it
. thanks for the little command 👍 i'll save it on my screensaver :P

**Comment by rhukster** [comment]
Also could you do me a favor, can you install a stable Grav + Admin plugin v1.1.8, switch to testing and try updating to latest RC releases of everything???

This works fine for me, but would love some extra testing of this.

Cheers!
