### ISSUE TITLE
Certain characters in folder name cause image upload to fail

### ISSUE THREAD

**Issue by bassplayer7** [getgrav/grav-plugin-admin#891]
#### Overview
If a `?` character is added to `Advanced -> Folder Name`, it will cause errors to be thrown when uploading images. The images appear after removing the `?` from the folder name. It is possible that other characters cause issues as well.

#### Steps to Reproduce:
1. Create a modular with a folder name containing a `?` along with other alpha-numeric characters.
2. Save the page and attempt to upload images.
3. An error appears: `move_uploaded_file([path to file *without* a ?]/image.jpg): failed to open stream: No such file or directory`
4. Remove `?` from `Folder Name`
5. Images upload smoothly.

**Comment by flaviocopes** [comment]
The problem is `?` is a special character. We should disallow changing a folder name (or creating a new one) to contain `?` in the first place, as it's going to be interpreted by the browser unless urlencoded. The problem seems linked to the fact you can first save as `yourfolder?` but then saving a second time, without any other change, the folder is back to `yourfolder`.

**Comment by bassplayer7** [comment]
Obviously someone could set the folder name to include a `?` but in this case everything was done through the admin panel. It seemed to me that it shouldn't let any invalid characters be saved.

**Comment by flaviocopes** [comment]
Yes if we state `?` (as with & or other special chars reserved in URIs) are not supported, it should be denied when saving.

**Comment by bassplayer7** [comment]
Or, as a possible alternative, what about automatically swapping any unacceptable characters out for `-` to make it URL friendly. I'm thinking of something like this:

```php
$url = str_replace(' ', '-', strtolower($url));
$url = preg_replace('/[^\da-z\-]/i', '-', $url);
$url = preg_replace('/-+/', '-', $url);
$url = rtrim(ltrim($url, '-'), '-');
```

The end goal would be to turn `My(?) Folder Name!` into `my-folder-name`.
