### ISSUE TITLE
unable to install admin plugin

### ISSUE THREAD

**Issue by frankivantomp** [getgrav/grav-plugin-admin#892]
Im comming from the other room(admin-plugin) but there are no body else.
And I get the following issue. 
    1. unzip woo/skeleton
    2. Visit the site for fisrt time to Verify if the web site works. It Works
    3. run bin/gpm install admin
    4. Visit the site for fisrt time /admin to Verify it works.
    5. It should prompted to create an admin user account.
    6. But its not and I get this error again :

Not Found
The requested URL /admin was not found on this server.

7. I have re-tried with another skeleton(Ceevee Site).  
And I still get the same error ! So why ?! and why this does never happen before ? 
What's wrong ? The last update may be causing that ?

**Comment by rhukster** [comment]
Woo is a one page site, so there is no routing involved.  I think you will find you have an issue with rewriting not working.

Check this out it should contain all you need: http://learn.getgrav.org/troubleshooting/page-not-found
