### ISSUE TITLE
Popularity/Ignore - Can't add URLs

### ISSUE THREAD

**Issue by cworreschk** [getgrav/grav-plugin-admin#898]
On the configuration page in the section `Popularity` you are not able to add additional urls to the `Ignore` field.

Every time you have added some urls and click afterwards on the save button, they disapear. 
The changes are not saved to the `/user/config/plugins/admin.yaml` file.

![popularity](https://cloud.githubusercontent.com/assets/545143/21390228/1ed04bd0-c786-11e6-8a00-38b94526270a.PNG)

> Grav v1.1.9 - Admin v1.2.5

**Comment by flaviocopes** [comment]
Thanks for reporting, I fixed this in the latest `develop` branch of the Admin plugin, but not yet released https://github.com/getgrav/grav-plugin-admin/commit/d6e8f31936c5c71e5e4baa92704cd5dd2307f279

**Comment by cworreschk** [comment]
Thank you very much for this fast fix :+1:
