### ISSUE TITLE
Grav Admin 403 in Appearance 

### ISSUE THREAD

**Issue by Wferr** [getgrav/grav-plugin-admin#899]
Running latest Grav v1.1.10 and  Admin v1.2.6 . 

I cannot change any of the parameters within the appearance tab. Errors out and gives a 403 to refresh for invalid security token. Restarted server, emptier cache and hard reloaded, logged in and out. Server running on debian 8 with nginx and php7.

**Comment by rhukster** [comment]
Appearance tab?

**Comment by Wferr** [comment]
Yeah, using Helium theme.  Video of it here https://f.wferr.com/ea5_1482368751_%25pn.mp4

**Comment by w00fz** [comment]
If you have mod_security running that is known to be a problem with Gantry. Please can you check that?

**Comment by w00fz** [comment]
See https://github.com/gantry/gantry5/issues/1748 and https://github.com/gantry/gantry5/issues/1519

**Comment by Wferr** [comment]
@w00fz I do not have mod_security installed.

**Comment by rhukster** [comment]
@mahagr any ideas on this?  403 Forbidden error sounds like a server configuration thing right?

**Comment by Wferr** [comment]
Im quite new to GRAV and have learned that that appearance tab is from the gantry plugin, Im going to cross post this issue there.
