### ISSUE TITLE
Modular pages are not finding the correct blueprint

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav-plugin-admin#9]
I'm already on it!

**Comment by greasan** [comment]
Is this similar to the following error, that appears in preview mode on a modular page?

```
Template
"modular/text.html.twig" is not defined ().
```
![pages grav](https://cloud.githubusercontent.com/assets/5444765/9110750/84dc97f8-3c40-11e5-9a66-525bc07a013e.png)

**Comment by rhukster** [comment]
This is because the theme must have the blueprint.  We have updated Antimatter already, just need to get that released.
