### ISSUE TITLE
Folder Name won't accept underscore

### ISSUE THREAD

**Issue by david-bettondesign** [getgrav/grav-plugin-admin#900]
Grav v1.1.10
Admin v1.2.6

When adding a modular page in Grav admin I cannot save it because the name of the folder (with an underscore) breaks the regex validation for the input. For example, if my folder is called ```_slider```, when I try to save the page I get a message (in Chrome) of:

> Please match the format requested.

**Comment by flaviocopes** [comment]
Cannot replicate - where are you getting it? In the modal directly? Can you make a screenshot?

**Comment by david-bettondesign** [comment]
![screen](https://cloud.githubusercontent.com/assets/22169477/21428086/271ff6ee-c850-11e6-8860-7f2a2bc450c0.jpg)

**Comment by flaviocopes** [comment]
Ok replicated! Thanks for reporting

**Comment by david-bettondesign** [comment]
Fixed [https://github.com/getgrav/grav/issues/900](url) 👍
