### ISSUE TITLE
[question] Custom theme for Admin plugin

### ISSUE THREAD

**Issue by nepomuk13** [getgrav/grav-plugin-admin#903]
Hi, 

I'm currently trying to make my own theme for the Admin Plugin and I wonder what is the best way to do that.
I noticed that there is a theme folder under user/plugins/admin/themes named grav but I would like to add my own theme without overriding the default one. 

I'm aware of the plugin [Customadmin](https://github.com/numee/grav-plugin-customadmin) but I would rather use SCSS to modify everything I need.

Any help would be greatly appreciated!

**Comment by flaviocopes** [comment]
If you just want to add some compiled CSS to the page, then you could write a plugin that adds that CSS file when Grav is executing Admin, something alone the line of 

```
    public function onPluginsInitialized()
    {
        if ($this->isAdmin()) {
            $this->grav['assets']->addCss('plugin://myplugin/style.css');
        }
    }
```

There is currently no option to swap the Admin theme with another, or override the default Twig files.

**Comment by nepomuk13** [comment]
Thank you for your answer.
I guess it will be easier to just modify the preset.scss file and restoring it each time the admin plugin is updated.

Don't you think adding the possibility to switch color scheme for admin plugin would be a nice addition though? Or maybe it is planned for pro features?

**Comment by w00fz** [comment]
Yes this is planned (and already implemented) for admin PRO

**Comment by nepomuk13** [comment]
Great, thanks!
