### ISSUE TITLE
Add new menu item on sidebar

### ISSUE THREAD

**Issue by antonio9357** [getgrav/grav-plugin-admin#905]
Hi, there!

First thing first: nice work, I mean it really.

I'm developing a plugin for Grav and I need to add a menu item on sidebar without editing some core files of Grav-Admin.

Is that possible?

Thanks in advance!

**Comment by antonio9357** [comment]
Ok, I found it by myself on Shopping Cart Plugin.

If someone need it:

on base plugin class:

add this:

`protected $route = 'your_plugin_route';`

create a new function:

`public function onAdminMenu()
    {
        $this->grav['twig']->plugins_hooked_nav['YOUR_PLUGIN_TRANSLATION.STRING'] = [
            'route' => $this->route,
            'icon'  => 'fa-font-awesome-icon'
        ];
    }`

call the function:

`public function onPluginsInitialized()
    {
        // Don't proceed if we are in the admin plugin
        if ($this->isAdmin()) {
            $this->enable([
                'onAdminMenu' => ['onAdminMenu', 0]
            ]);
        }

        // Enable the main event we are interested in
        $this->enable([
            'onPageContentRaw' => ['onPageContentRaw', 0],
        ]);
    }`

Sorry for opening this. Anyway, I hope this will be useful for someone.

**Comment by flaviocopes** [comment]
👍 also the Comments and Data Manager plugins do a similar thing.

**Comment by antonio9357** [comment]
Thanks Flavio, I didn't see that because I'm working with Grav with Admin plugin only. I'll try to install Data Manager and Comments too!
