### ISSUE TITLE
Bug - Error: Insufficient permissions for Task Clear Cache

### ISSUE THREAD

**Issue by Duke3D** [getgrav/grav-plugin-admin#908]
For Admin plugin user with:
access:
.  admin:
. .     login: true
. .     pages: true
. .     maintenance: true
When viewing dashboard.  Clear Cache button renders, but
clicking the Clear Cache button produces error:
You have insufficient permissions for task clear cache.

Admin plugin release 1.2.7 installed 12/26/16

**Comment by flaviocopes** [comment]
Thanks for reporting, clear cache currently checks if `admin.cache` (or `admin.super`) is granted. It should probably also allow `admin.maintenance`.

**Comment by flaviocopes** [comment]
Fixed by https://github.com/getgrav/grav-plugin-admin/commit/92eb33493e8ac4a50e05eda5646765351e522652

**Comment by nsteinmetz** [comment]
Hi,

I would say that it does not work with `admin.cache` only ; I had to add `admin.maintenance` to make it work for a user.

Could there be a way that at list for the display, both are needed ?

**Comment by flaviocopes** [comment]
@nsteinmetz right, the button required admin.maintenance. Fixed
