### ISSUE TITLE
Bug - Stats widget not displaying for non-super users

### ISSUE THREAD

**Issue by Duke3D** [getgrav/grav-plugin-admin#909]
User with permissions:
access:
.   admin:
. .     login: true
. .     pages: true
. .     maintenance: true
should be able to see the Statistics widget but it does not render.
Only the Maintenance widget renders.
(Both widgets do render for super: true)

Admin plugin release 1.2.7 installed 12/26/16

**Comment by flaviocopes** [comment]
The statistics are not visible unless `admin.statistics` or `admin.super` is granted.

**Comment by Duke3D** [comment]
Thanks -  the docs need updating to reflect the extra granularity that has been implemented but is not yet listed as available settings.

**Comment by flaviocopes** [comment]
Fixed by https://github.com/getgrav/grav-learn/commit/6223315d1289754ee74376108c494229dcc891ed
