### ISSUE TITLE
Button "Add page" on the page edition view 

### ISSUE THREAD

**Issue by nicosomb** [getgrav/grav-plugin-admin#911]
When I'm editing / creating a new page, it will be useful to have a button on the header (near Preview, Back, etc.) to create a new page. 

For example: 

![capture d ecran 2017-01-02 a 12 46 43](https://cloud.githubusercontent.com/assets/121870/21588654/8e99a1f2-d0e9-11e6-84b8-123c2ddb7ea5.png)

**Comment by mahagr** [comment]
Already implemented, closing the issue.
