### ISSUE TITLE
Add support for Image Srcset plugin with Gantry5 into Grav admin

### ISSUE THREAD

**Issue by Getron** [getgrav/grav-plugin-admin#912]
I just try to install "Image Scrset" plugin, and the "Appearence" of Gantry5, Theme Helium is not showed properly on Grav admin.

Please, check this plugin with Gantry5, and you will see the problem in Grav admin, under "Appearence" left Menu, if the Default Theme is "g5_helium"

**Comment by flaviocopes** [comment]
Closing as it's a issue caused by that plugin. Commented on the issue https://github.com/OleVik/grav-plugin-imgsrcset/issues/5

**Comment by OleVik** [comment]
Presumed fixed with v1.0.1 of img-srcset plugin, as per [reported issue](https://github.com/OleVik/grav-plugin-imgsrcset/issues/5).
