### ISSUE TITLE
Forms on plugin's backend pages

### ISSUE THREAD

**Issue by antonio9357** [getgrav/grav-plugin-admin#913]
Hi,

on developing a plugin, I'm getting some troubles with forms.
I need to **add a form in a backend page.**

This form must submit some data, store it on yaml, and load pictures on the server.

I tried to follow the docs of Grav, with no success.
The docs refer to Frontend forms and plugin's settings forms.

Everything I tried had no success, not even an error.

Is there any way to create a form for an admin page?

Can someone give me some example of this?

Thank you!

**Comment by rhukster** [comment]
I have started a rough 'base' plugin that provides some examples of how this works via the admin.  Currently it's not a trivial thing, and you have to really provide quite a bit of functionality that the admin does. I hope to improve this plugin and turn it into something that can easily be extended and used to make creating custom admin forms much easier.

**Comment by antonio9357** [comment]
Ok, I'll wait for any news. As I wrote on Grav's Forum, I tried also "onAdminSave" with no success, looks like the events are not triggered.
If I add the function on event "onFormValidationError" it works.

I think it's something really important to develop better plugins for Grav.

What I'm doing is a Ticket system with client and admin sides within the admin panel. So different users with different capabilities, question and answers between admins and clients, invoices and so on.

Just a little preview on the screenshots
![schermata 2017-01-17 alle 10 53 27](https://cloud.githubusercontent.com/assets/10912152/22015765/a8d78460-dca3-11e6-8656-880c301e345b.png)
![schermata 2017-01-17 alle 10 56 17](https://cloud.githubusercontent.com/assets/10912152/22015764/a8d58b38-dca3-11e6-89cd-1ff39e2eb226.png)

 above.

**Comment by Flibio** [comment]
@antonio9357: Have you figured out how to achieve this yet? I'm wanting to create a plugin that needs a form as well but I can't figure it out.

**Comment by rhukster** [comment]
Check this out: https://github.com/trilbymedia/grav-plugin-flex-directory

**Comment by Flibio** [comment]
@rhukster: So I have added my custom fields, but whenever I save my data, the data saves successfully, but an error messages appears that says "Data type 'speakers/edit' doesn't exist!" `speakers/edit` is the path to my input page, if that provides any insight.

I could create a new issue if you would like.

**Comment by rhukster** [comment]
Crate an issu non the flex directory repo. I have a feeling you changed some things you shouldn't have.

**Comment by Flibio** [comment]
@rhukster: You want the issue on the flex directory repo or on the admin panel repo?

**Comment by rhukster** [comment]
Well i'm not sure what you've done.. if its' related to FlexDirectory, put it on that repo, and if admin, then as a new issue here.

**Comment by Flibio** [comment]
@rhukster: I'm sure its something I've done wrong - I didn't copy the code directly, just based mine off of it. The issue is #1021.

**Comment by rhukster** [comment]
Yah i replied, sorry but as i said in the reply to that issue, it's really a custom development issue.
