### ISSUE TITLE
Statistics Header or IP Blacklist

### ISSUE THREAD

**Issue by trst** [getgrav/grav-plugin-admin#914]
While I'm not terribly keen on keeping detailed records of my site visits I appreciate that many are. In the interest of making the dashboard page more usable could it be possible to restrict the number of counted "visits" to a Grav instance to, say, non-automated visitors? I have a current weekly visitor count of around 40k but tailing through my server log shows that 99.9% of those are indexing spiders or other random pings, both aren't very meaningful for reporting.

Being able to block certain IPs or user agents from counting on the stats widget would go a fair way to making the stats more usable. This could be a simple yaml or json file somewhere in the user folder.

Thoughts?

**Comment by rhukster** [comment]
Although I've not extensively tested this, the browser detection script we use should already be skipping any hit that is not 'human':

https://github.com/getgrav/grav-plugin-admin/blob/develop/classes/popularity.php#L50-L52

**Comment by trst** [comment]
Hm. Interesting. Perhaps, I'm just exceedingly popular.

I've checked the logs and the stats don't seem to line up. Anyway to debug what's going on?

**Comment by flaviocopes** [comment]
You can edit this file https://github.com/getgrav/grav-plugin-admin/blob/develop/classes/popularity.php#L57 and try a var_dump into your error_log with the contents of the request (`$page->url()`) and the `Grav::instance()['browser']` content:

```
ob_start();                  
var_dump($page->url());             
var_dump(Grav::instance()['browser']);             
$contents = ob_get_contents(); 
ob_end_clean();                
error_log($contents);  
```

It should return something like

```
[08-Jan-2017 21:46:48 Europe/Rome] string(8) "/it/blog"
object(Grav\Common\Browser)#223 (1) {
  ["useragent":protected]=>
  array(3) {
    ["platform"]=>
    string(9) "Macintosh"
    ["browser"]=>
    string(6) "Chrome"
    ["version"]=>
    string(12) "55.0.2883.95"
  }
}
```

in your PHP error log, and you can check what's causing such heavy logging.
