### ISSUE TITLE
admin user list 

### ISSUE THREAD

**Issue by geezer78** [getgrav/grav-plugin-admin#917]
hi there,

if you open /admin/user you will get an server error:

Sorry, something went terribly wrong!

>400 - Template "partials/users-list.html.twig" is not defined in "user.html.twig" at line 30.
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.

this is because the mentioned template file does not exist.

**Comment by flaviocopes** [comment]
This is because there is no user management functionality in Admin right now. It's going to be provided by Admin Pro soon. We should have a better error message instead.

**Comment by geezer78** [comment]
probably related to this: when a user is logged in, they can navigate to /user/otherusername and even if their account is restricted to not allow user changes. when trying to save they are disallowed, but i think it would be better to not let them navigate to other users pages.

**Comment by mahagr** [comment]
This functionality has been replaced in Admin 1.10
