### ISSUE TITLE
Expert mode shows nothing to edit

### ISSUE THREAD

**Issue by aanglere** [getgrav/grav-plugin-admin#92]
I can't edit much in normal mode and nothing at all in expert mode. Is it like this for everyone? In normal edit mode, shouldn't I be able to see the markdowns and not just the ## and ###?

![screenshot-aanglere duckdns org 2015-08-23 23-50-07](https://cloud.githubusercontent.com/assets/13938426/9433048/2253b822-49f2-11e5-86d1-5893833333db.png)
![screenshot-aanglere duckdns org 2015-08-23 23-49-09](https://cloud.githubusercontent.com/assets/13938426/9433050/26cea7ea-49f2-11e5-8da2-23168e140243.png)
![screenshot-aanglere duckdns org 2015-08-23 23-47-49](https://cloud.githubusercontent.com/assets/13938426/9433052/287ff1d4-49f2-11e5-8cf7-c62ab5b5bc6b.png)

**Comment by flaviocopes** [comment]
Is this the latest published version of Grav and the Admin plugin, or you installed them from GitHub? If the latter then make sure both Grav and Admin are from GitHub.

**Comment by rhukster** [comment]
Should be resolved in next version of the admin as these issues have already been addressed.
