### ISSUE TITLE
Type: file in blueprint fails when deleting/removing file, throws AJAX error

### ISSUE THREAD

**Issue by blancblanc** [getgrav/grav-plugin-admin#920]
Using `type: file` on a page blueprint to enable file uploads works perfectly for uploading, but on clicking the X (and confirming in the modal) to remove/delete the file, throws “Invalid AJAX Response” error. The action **will** remove the reference to the file from the page.md header, but will **not** remove the file from the server.
Users can always use `type: pagemedia`, but `type: file` offers additional parameters which are really useful.

**Comment by sthijs** [comment]
I'm having the same issue. When looking into the AJAX request, the response seems to be empty: {}.

**Comment by flaviocopes** [comment]
Fixed! Thanks for reporting
