### ISSUE TITLE
Colorpicker validate pattern

### ISSUE THREAD

**Issue by leotiger** [getgrav/grav-plugin-admin#921]
The colorpicker field in admin has a problem with rgba validation once you configure transparency on the alpha channel and reset the alpha channel to 1 using the alpha transparency slider. The colorpicker sets 1.00 and this is not covered as a valid value in the pattern.

You should change this
```
set pattern = '^#([a-fA-F0-9]{6})|(rgba\\(\\s*(0|[1-9]\\d?|1\\d\\d?|2[0-4]\\d|25[0-5])\\s*,\\s*(0|[1-9]\\d?|1\\d\\d?|2[0-4]\\d|25[0-5])\\s*,\\s*(0|[1-9]\\d?|1\\d\\d?|2[0-4]\\d|25[0-5])\\s*,\\s*((0.[0-9]+)|[01])\\s*\\))$'
```
to something like this
```
set pattern = '^#([a-fA-F0-9]{6})|(rgba\\(\\s*(0|[1-9]\\d?|1\\d\\d?|2[0-4]\\d|25[0-5])\\s*,\\s*(0|[1-9]\\d?|1\\d\\d?|2[0-4]\\d|25[0-5])\\s*,\\s*(0|[1-9]\\d?|1\\d\\d?|2[0-4]\\d|25[0-5])\\s*,\\s*((0.[0-9]+)|(1.00)|1.0|1)\\s*\\))$'
```

Regards.
uh

**Comment by flaviocopes** [comment]
Good catch!
