### ISSUE TITLE
Add 'hash' configuration option for cache check method

### ISSUE THREAD

**Issue by fredrikekelund** [getgrav/grav-plugin-admin#923]
It seems Grav supports a 'hash' cache check method, that looks at folder contents in their entirety, and generates an MD5 hash from the combined list of mtimes. See https://github.com/getgrav/grav/commit/c718b8f32a94af206be2b5b6dd02525a6b836cc9 for more details.

There should probably be an option in the admin panel for this 'hash' option.

**Comment by rhukster** [comment]
Fixed in Grav develop - https://github.com/getgrav/grav/commit/e492fbde21b6d671c7d9913ee5c155317bd49a05

**Comment by fredrikekelund** [comment]
@rhukster great! I like the fact that you added a bit more descriptive labels for the different options as well. Just a question, though – will the `file` cache check method really take media files into account? From looking at the [source code for the Folder::lastModifiedFile method](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Filesystem/Folder.php#L56), it looks like it only takes `.md` and `.yaml` files into consideration?

**Comment by rhukster** [comment]
You are correct! I misremembered. Probably should of checked first :) Will fix

**Comment by rhukster** [comment]
You are correct, fixed.
