### ISSUE TITLE
Use Admin plugin without internet connection

### ISSUE THREAD

**Issue by tranduyhung** [getgrav/grav-plugin-admin#928]
It is great if Grav simply disables anything related to GPM in Admin if there is no connection to Grav site.

My sites work well, but recently our country has a network problem, the internet has been slow and some times unstable, we can't work locally on our development computers just because Grav keeps throwing these errors:

> An exception has been thrown during the rendering of a template ("GPM not reachable. Please check your internet connection or check the Grav site is reachable") in "partials/plugins-list.html.twig" at line 20.

> An exception has been thrown during the rendering of a template ("GPM not reachable. Please check your internet connection or check the Grav site is reachable") in "partials/themes-list.html.twig" at line 21.

We don't need internet to build the sites, if we need any themes or plugins we can manually install them by copying-pasting the folders from other websites we built.

It is really great if we can use Admin plugin without internet connection. Thank you!

**Comment by w00fz** [comment]
Actually I did add an offline mode at some point, but it seems to have gotten lost for some reason!!
I'll look at this again, sorry about that.

**Comment by 4evermaat** [comment]
why would an internet connection be required to use admin panel in the first place?  If you have WAMP/LAMP installed, isn't that enough to simulate it?

**Comment by flaviocopes** [comment]
An internet connection is not required. If you turn internet off *completely*, it works fine except for the Gravatar image in the sidebar, and installing plugins/themes / checking for notifications and updates.

What happens in this case probably is that the request fails for a timeout connection problem? So the offline mode @w00fz mentions should come in handy in this case, avoiding the requests in the first place.

**Comment by rhukster** [comment]
@w00fz address this a few months back.
