### ISSUE TITLE
Gantry 5.4.3 update crashes site

### ISSUE THREAD

**Issue by swilkins71** [getgrav/grav-plugin-admin#929]
[theddra](theddra.org)
updated to 5.4.3 from 5.4.2 site crashed
error
Server Error
Sorry, something went terribly wrong!

E_COMPILE_ERROR - Cannot use Grav\Common\Page\Page as Page because the name is already in use

For further details please review your logs/ folder, or enable displaying of errors in your system configuration.

**Comment by mahagr** [comment]
Install CI build of Gantry 5 or wait a few hours for the update.

**Comment by swilkins71** [comment]
Thanks new to Gantry and Grav where do I find this build?

**Comment by mahagr** [comment]
http://gantry.org/downloads#ci-builds
