### ISSUE TITLE
Feature request: Edit custom metadata of pages in normal mode

### ISSUE THREAD

**Issue by mariosant** [getgrav/grav-plugin-admin#93]
It would be really cool if there was an easy way to edit custom metadata of pages, while in normal mode.

I wish it could be something like `Configuration/Site/Metadata`.

![download](https://cloud.githubusercontent.com/assets/1409645/9449364/c0c67202-4aaa-11e5-97c3-8201cd3775fc.jpg)

**Comment by rhukster** [comment]
Fixed for next release

**Comment by mariosant** [comment]
:+1:
