### ISSUE TITLE
cannot install admin panel manually with gravstrap skeleton.....

### ISSUE THREAD

**Issue by 4evermaat** [getgrav/grav-plugin-admin#932]
Grav v1.1.12 - Admin v1.2.7

I tried downloading gravstrap [skeleton 1.2.1](https://github.com/giansi/gravstrap-theme-skeleton/releases/download/v1.2.1/gravstrap-skeleton.zip) .  Displays fine in my browser with WAMP 3.0.6 and PHP7.  

Then I proceeded to install the grav admin plugin (admin, form, email, login) and I have this error:

    Twig_Error_Runtime thrown with message "An exception has been thrown during the rendering of a template ("Identifier "messages" is not defined.") in "partials/messages.html.twig" at line 1."
    
    Stacktrace:
    #34 Twig_Error_Runtime in C:\wamp\www\gravstrap\vendor\twig\twig\lib\Twig\Template.php:402
    #33 InvalidArgumentException in C:\wamp\www\gravstrap\vendor\pimple\pimple\src\Pimple\Container.php:96
    #32 Pimple\Container:offsetGet in C:\wamp\www\gravstrap\user\plugins\admin\classes\admin.php:287
    #31 Grav\Plugin\Admin\Admin:messages in C:\wamp\www\gravstrap\vendor\twig\twig\lib\Twig\Template.php:604
    #30 Twig_Template:getAttribute in C:\wamp\www\gravstrap\cache\twig\80\801ac55dd764466d9324ae5ed5bfb05d8dc6cd6098b4de7c6deab2587638441f.php:19
    #29 __TwigTemplate_2b7c200ace87dd278a5063455f6e6e34e8642eadde4069a78e566b9b4094bc26:doDisplay in C:\wamp\www\gravstrap\vendor\twig\twig\lib\Twig\Template.php:387
    #28 Twig_Template:displayWithErrorHandling in C:\wamp\www\gravstrap\vendor\twig\twig\lib\Twig\Template.php:355
    #27 Twig_Template:display in C:\wamp\www\gravstrap\cache\twig\40\40e80cb0c8b5a4c6b7bbbd850e9f6290689cf66cbba7c00cd2eaba4546086b38.php:48
    #26 __TwigTemplate_521d7282f7863d74ed160937593cca91daa2ff4d0521a6e82cd28803072de597:block_page in C:\wamp\www\gravstrap\vendor\twig\twig\lib\Twig\Template.php:167
    #25 Twig_Template:displayBlock in C:\wamp\www\gravstrap\cache\twig\c7\c75ab073e0d98a785ebbe95bdbe95fb9aa86a7bd9562d19ae4ab91660fb178fc.php:158
    #24 __TwigTemplate_33ff0bea4f2b01307c0a2654f793aeefc9ba7b80e4365f4bfdc52414bce40b3b:block_body in C:\wamp\www\gravstrap\vendor\twig\twig\lib\Twig\Template.php:167
    #23 Twig_Template:displayBlock in C:\wamp\www\gravstrap\cache\twig\c7\c75ab073e0d98a785ebbe95bdbe95fb9aa86a7bd9562d19ae4ab91660fb178fc.php:45
    #22 __TwigTemplate_33ff0bea4f2b01307c0a2654f793aeefc9ba7b80e4365f4bfdc52414bce40b3b:doDisplay in C:\wamp\www\gravstrap\vendor\twig\twig\lib\Twig\Template.php:387
    #21 Twig_Template:displayWithErrorHandling in C:\wamp\www\gravstrap\vendor\twig\twig\lib\Twig\Template.php:355
    #20 Twig_Template:display in C:\wamp\www\gravstrap\cache\twig\40\40e80cb0c8b5a4c6b7bbbd850e9f6290689cf66cbba7c00cd2eaba4546086b38.php:29
    #19 __TwigTemplate_521d7282f7863d74ed160937593cca91daa2ff4d0521a6e82cd28803072de597:doDisplay in C:\wamp\www\gravstrap\vendor\twig\twig\lib\Twig\Template.php:387
    #18 Twig_Template:displayWithErrorHandling in C:\wamp\www\gravstrap\vendor\twig\twig\lib\Twig\Template.php:355
    #17 Twig_Template:display in C:\wamp\www\gravstrap\cache\twig\f6\f6a9adbf9d16d8456428b52b424980e92176ba386eafe5451fa7febccf922848.php:60
    #16 __TwigTemplate_ec6f5b8c940e2d125465283323e6a6e2618915e0f1841b750da1b5180ac05115_313838479:doDisplay in C:\wamp\www\gravstrap\vendor\twig\twig\lib\Twig\Template.php:387
    #15 Twig_Template:displayWithErrorHandling in C:\wamp\www\gravstrap\vendor\twig\twig\lib\Twig\Template.php:355
    #14 Twig_Template:display in C:\wamp\www\gravstrap\cache\twig\f6\f6a9adbf9d16d8456428b52b424980e92176ba386eafe5451fa7febccf922848.php:19
    #13 __TwigTemplate_ec6f5b8c940e2d125465283323e6a6e2618915e0f1841b750da1b5180ac05115:doDisplay in C:\wamp\www\gravstrap\vendor\twig\twig\lib\Twig\Template.php:387
    #12 Twig_Template:displayWithErrorHandling in C:\wamp\www\gravstrap\vendor\twig\twig\lib\Twig\Template.php:355
    #11 Twig_Template:display in C:\wamp\www\gravstrap\vendor\twig\twig\lib\Twig\Template.php:366
    #10 Twig_Template:render in C:\wamp\www\gravstrap\vendor\twig\twig\lib\Twig\Environment.php:347
    #9 Twig_Environment:render in C:\wamp\www\gravstrap\system\src\Grav\Common\Twig\Twig.php:340
    #8 Grav\Common\Twig\Twig:processSite in C:\wamp\www\gravstrap\system\src\Grav\Common\Service\OutputServiceProvider.php:19
    #7 Grav\Common\Service\OutputServiceProvider:Grav\Common\Service\{closure} in C:\wamp\www\gravstrap\vendor\pimple\pimple\src\Pimple\Container.php:113
    #6 Pimple\Container:offsetGet in C:\wamp\www\gravstrap\system\src\Grav\Common\Processors\RenderProcessor.php:17
    #5 Grav\Common\Processors\RenderProcessor:process in C:\wamp\www\gravstrap\system\src\Grav\Common\Grav.php:121
    #4 Grav\Common\Grav:Grav\Common\{closure} in C:\wamp\www\gravstrap\system\src\Grav\Common\Grav.php:396
    #3 Grav\Common\Grav:Grav\Common\{closure} in C:\wamp\www\gravstrap\system\src\Grav\Common\Grav.php:372
    #2 call_user_func_array in C:\wamp\www\gravstrap\system\src\Grav\Common\Grav.php:372
    #1 Grav\Common\Grav:__call in C:\wamp\www\gravstrap\system\src\Grav\Common\Grav.php:122
    #0 Grav\Common\Grav:process in C:\wamp\www\gravstrap\index.php:45

Grav + admin skeleton works just fine.  Then within admin panel, I add the gravstrap theme.  And then I just copy the sample `/user/pages` and `user/config` from the gravstrap skeleton and [adjust the `user/config/systems.yaml` and `user/config/plugins/blog-injector.yaml` settings](http://diblas.net/themes/gravstrap-theme/how-to-install-gravstrap-theme#setup).  All seems to work ok.

Seems to work fine.   But aren't skeletons supposed to 'work' out of the box so to speak?

**Comment by flaviocopes** [comment]
Skeletons are supposed to be downloaded from https://getgrav.org/downloads/skeletons in the form of "complete" ready-made packages.

While you can apply a skeleton, there is no testing involved in this situation, as all can change depending on the steps you took.

I tried downloading the Gravstrap theme, and installing Admin

- `bin/gpm selfupgrade` (update Grav first, as the shipped version is old)
- `bin/gpm install admin`

I don't get the error.

I remember that error from an old Admin/Login plugins combination, so I guess that is the problem? Are all plugins at the latest version available?

**Comment by 4evermaat** [comment]
Interesting.

The plugins (admin, login, email, form) are all freshly downloaded.

with WAMP, how do you do `bin/gpm selfupgrade` and `bin/gpm install admin` .  CMD prompt? BASH?

I got it to work doing it backwards (downloaded fresh grav + admin), updated from within admin panel, and then adding gravstrap theme within admin panel.   No error, likely because everything has been updated already.

**Comment by flaviocopes** [comment]
Yes, that's likely the issue. Admin or Login were not up to date. `bin/gpm` commands are run through the command line (https://learn.getgrav.org/cli-console/grav-cli). You could also update through the Admin panel itself, but since you have this problem, it was not reachable.

**Comment by flaviocopes** [comment]
Another option is to download the package from https://getgrav.org/downloads/plugins, unzip and then upload via FTP in user/plugins/
