### ISSUE TITLE
White page on Home

### ISSUE THREAD

**Issue by swilkins71** [getgrav/grav-plugin-admin#934]
[site](http://dothansoftball.com/)

Can access backend fine but front page is white no errors.

Set memory_limit in php.ini to 256MB but no change?
![cpanel multiphp ini editor](https://cloud.githubusercontent.com/assets/24855568/22021346/5f3cf996-dc82-11e6-82a2-1124ce64a151.png)

**Comment by flaviocopes** [comment]
A white page usually is an error page, but with errors hidden. Can you try turning on `display_errors` in the PHP settings? Maybe that makes something show up

**Comment by flaviocopes** [comment]
Or check the PHP error log as well

**Comment by DamirPecnik** [comment]
Hi Suzie. The grav is still showing the 32M can you post your server info on RT forum and i will look into it...

http://www.rockettheme.com/forum/grav-theme-citadel/266511-major-site-issues?start=0#1332625

**Comment by swilkins71** [comment]
In the secure area now, thanks you.

**Comment by DamirPecnik** [comment]
Solved it can be closed!
