### ISSUE TITLE
Something funky with shortcodes

### ISSUE THREAD

**Issue by Perlkonig** [getgrav/grav-plugin-admin#936]
I have a couple of shortcode plugins. I've received bug reports for [Scheduler](https://github.com/Perlkonig/grav-plugin-scheduler) and [Table Importer](https://github.com/Perlkonig/grav-plugin-table-importer). The reason I'm pretty sure it's the Admin plugin is because I've done the following:

1. I did a clean install of Grav only (no Admin).

2. I then did `bin/gpm install table-importer`.

2. I replaced `default.md` with the following and dropped in `import.csv`.

```
---
title: test
---

[u]Testing[/u]

[ti file=import.csv /]
```

3. [It works as expected.](https://perlkonig.com/scratch/clean/)

4. I then downloaded and installed Grav+Admin and immediately did `bin/gpm install table-importer`.

5. I added some `dump()` statements to `table-importer.php`.

5. I then dropped in the exact same markdown and csv.

6. [It fails.](https://perlkonig.com/scratch/cleanadmin/)

So it appears the `onShortcodeHandlers` isn't getting called for some reason, but the `[u]` code is working. Any ideas?

**Comment by rhukster** [comment]
Please post this bug on `shortcode-core` plugin: https://github.com/getgrav/grav-plugin-shortcode-core/issues

**Comment by Perlkonig** [comment]
[Done.](https://github.com/getgrav/grav-plugin-shortcode-core/issues/26)
