### ISSUE TITLE
Custom language code breaks .md file name

### ISSUE THREAD

**Issue by liamtarpey** [getgrav/grav-plugin-admin#938]
We're looking to implement Indonesian interface language support in our app but unfortunately we can't use ‘id’ language code (various reasons, mainly because the rest of our app is using ‘ind’ on a different environment) and we would need to use ‘ind’ instead.

We've added ‘ind’ into our system config supported languages but when you save a new page in the CMS as this language, it ends up being named ‘_modular.ind.**ind**.md_’ in your grav pages and the CMS gets redirected to the login page.
Renaming the file manually to ‘_modular.ind.md_’ solves the issue and works fine from a front end perspective but isn't sustainable for us whatsoever.

Currently running grav 1.1.12

**Comment by flaviocopes** [comment]
Currently the multilanguage functionality of Grav expects 2 characters (ISO 639-1 language codes) or 5 if it's a regional dialect (`it` or `it-CH` for example). This list should be comprehensive: http://www.lingoes.net/en/translator/langcode.htm

In your case, indonesian is `id`, not `ind`.

**Comment by liamtarpey** [comment]
Thanks, we found a workaround to enable us to use 'id' in the end :)
