### ISSUE TITLE
not possible to install plugins anymore!

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#939]
Since grav 1.1.13/1.1.14 and admin-plugin 1.2.8/1.2.9 it's not possible to install plugins via admin anymore.
Uninstall work. Install fails. Though it shows success at first, if you go back to plugins it isn't listed as installed, on your server there is only an empty folder...

**Comment by rhukster** [comment]
Is there ever a failure actually displayed? If so what does it say? What server are you running on? Can you provide some details?

**Comment by rhukster** [comment]
Also is this JUST admin, or CLI via `bin/gpm` also? What about themes? Is it only plugins?  We made some changes to the `Folder::move()` function that is about only the only thing I can think of that could cause this, but the logic only has an extra failsafe if the first method fails.

**Comment by rhukster** [comment]
Also, can you try backing-up/saving the `system/src/Grav/Common/Filesystem/Folder.php` file and replacing with the one from Grav v1.1.12.  Does it allow you to install plugins again???

https://github.com/getgrav/grav/blob/1.1.12/system/src/Grav/Common/Filesystem/Folder.php

**Comment by joshnorwich** [comment]
Similarly with Grav v1.1.12 and Admin v1.2.9 I cannot seem to update plugins through the Admin Dashboard. It empties the folder (namely gantry5 in this case) but does not put anything back in it's place.

Also it keeps prompting me to upgrade to v1.1.14, which it says is successful but the version does not change.

**Comment by joshnorwich** [comment]
bin/gpm was able to perform both tasks.

**Comment by axel-rank** [comment]
think i got it.
i changed php open_basedir string setting to none --> now it's working again!
![php](https://cloud.githubusercontent.com/assets/12480617/22140881/775bbd0e-deef-11e6-9c3c-3c7f2a2df107.png)
![php2](https://cloud.githubusercontent.com/assets/12480617/22140888/7de82c48-deef-11e6-8925-ccbf3f8a28ff.png)
though it did work before with standard setting
so admin installs are working again, but cli isn't (didn't work before either):
![cli](https://cloud.githubusercontent.com/assets/12480617/22141070/70b5c7e6-def0-11e6-9e2b-f89ddb028f98.png)

**Comment by flaviocopes** [comment]
Is PHP in your CLI path? If you type `php` what happens?

**Comment by axel-rank** [comment]
![cli_](https://cloud.githubusercontent.com/assets/12480617/22144959/c137b9f4-deff-11e6-8d01-54c1445b4467.png)

**Comment by axel-rank** [comment]
going to my webroot to /etc:
![cli2](https://cloud.githubusercontent.com/assets/12480617/22145737/ec11eef8-df02-11e6-988c-f0ba65e4b5b1.png)

**Comment by flaviocopes** [comment]
1) you need `php` to be the command to use. You can create a symbolic link from php5 to php so it will work, as the bin/gpm script calls `#!/usr/bin/env php` (calls the `php` executable).

2) you need to update the PHP version available in the command line to be at least PHP 5.5.9. If you're on a hosted site, they should provide you a way to use a newer version of PHP.

**Comment by axel-rank** [comment]
ok, spoke to my hoster, told me there are diffrent php versions to use under /bin folder.
and yes, there is php 5.6.
![cli3](https://cloud.githubusercontent.com/assets/12480617/22154488/0bd13e0a-df2c-11e6-918d-62c06fc44d13.png)
But how to use in grav cli now?
How to create a symbolic link?

**Comment by flaviocopes** [comment]
For example, see https://learn.getgrav.org/webservers-hosting/shared/crucial#setup-cli-php

**Comment by axel-rank** [comment]
guess i have no permissions to do that:
![bildschirmfoto zu 2017-01-20_16-33-15](https://cloud.githubusercontent.com/assets/12480617/22155027/3b76c6c8-df2e-11e6-8f6b-1b81214d38e6.png)

**Comment by flaviocopes** [comment]
You should ask your hosting provider how to do that. Or temporary change this line https://github.com/getgrav/grav/blob/develop/bin/gpm#L1 to `#!/usr/bin/env php5.6`

**Comment by axel-rank** [comment]
i think i had a wrong path. now the symlink is created.
link is in grav/bin folder?
![bildschirmfoto zu 2017-01-20_17-32-39](https://cloud.githubusercontent.com/assets/12480617/22157108/9d0d8f22-df36-11e6-9378-9958d8d1df9d.png),
![bildschirmfoto zu 2017-01-20_17-32-58](https://cloud.githubusercontent.com/assets/12480617/22157137/b6d5f3a4-df36-11e6-9e9a-2a8fdfa13695.png)
but where is bash_profile on my host, can find only bash_history?
![bildschirmfoto zu 2017-01-20_17-36-50](https://cloud.githubusercontent.com/assets/12480617/22157217/0d8ff528-df37-11e6-9c0b-96418ec725bc.png)

**Comment by rhukster** [comment]
We've been working on the same issue reported by another user and it turned out that switching from **auto** to **fopen** in the for the **GPM Check Method** in system.yaml resolved it.  

So we need to work out why Curl is not working for some people.

**Comment by rhukster** [comment]
Was related to curl + open_basedir and a 303 redirect.  We've fixed on the GPM side, and also in Grav in case this comes up again - https://github.com/getgrav/grav/issues/1267#issuecomment-274295364

You won't need to update anything, should just work now as we return a supported 302 redirect now.

https://github.com/getgrav/grav/issues/1267#issuecomment-274295364

**Comment by axel-rank** [comment]
Yes, setting back open_basedir back to standard --> updates/installs work again. Great!
Finally found a way cli working now:
Created a symlink from php5.6 to root server php
![bildschirmfoto zu 2017-01-22_16-29-23](https://cloud.githubusercontent.com/assets/12480617/22183532/e84e5aa8-e0c0-11e6-8134-d5d9e5bced64.png),
than going to grav folder and calling: /php bin/gpm
![bildschirmfoto zu 2017-01-22_16-31-21](https://cloud.githubusercontent.com/assets/12480617/22183554/546ac82a-e0c1-11e6-85db-62ac7133fad6.png)
yep!!!
maybe something for the docs.

**Comment by beamaria** [comment]
Same problem for me yesterday! I had everything working properly with "remote Fetch method" set to "Auto", but suddenly I was unable to install new plugins and I had to switch from "Auto" to "fopen"- This solved the problem, but I can't understand why the site worked for nearly two months and then- without any change in settings or in server- I had the same error and behaviour using different browsers (Safari, Chrome)
switching to cURL doesn't solve the problem 
Grav version: 1.6.21
Admin panel: 1.7.0
php: 7.2.22
Linux server
