### ISSUE TITLE
Cannot add new page

### ISSUE THREAD

**Issue by dimayakovlev** [getgrav/grav-plugin-admin#94]
I am trying Grav 0.9.38 with the Admin plugin version 0.4.0 on Apache/2.2.29 (Win32), clean installation.

If I want to create a root page, after clicking on Continue button opens edit home page.

If I want to create a home subpage, I'm getting error message: 
``rename(D:/OpenServer/domains/grav/user/pages/01.home,D:/OpenServer/domains/grav/user/pages/01.home/01.home): The process cannot access the file because it is being used by another process. (code: 32)``

**Comment by rhukster** [comment]
Yup, stupid bug on my side.. fixed now in 0.4.1
