### ISSUE TITLE
[suggestion] Add the possibility to create a meta.yaml for each media from the admin

### ISSUE THREAD

**Issue by paulmassen** [getgrav/grav-plugin-admin#940]
Hi, 

Grav offer the possibility to add a [meta.yaml](https://learn.getgrav.org/content/media#metafiles) file that could contain details about the image. 
As for now, and as far as I know, there is no possibility for the end-user to create this file from the admin.
Do you think it would be a good addition to the plugin ?

**Comment by flaviocopes** [comment]
Hi, the option to edit the image meta, and also a full-blown Media manager, is going to be available in Admin pro.

**Comment by paulmassen** [comment]
Another great feature! thanks!

**Comment by ganar** [comment]
I suggest that the feature can go here: 

![meta_yaml](https://cloud.githubusercontent.com/assets/431185/26502932/bdde4712-420c-11e7-891d-a6b35dabf2cb.jpg)

The icon to open aviary a modify the image can go below

**Comment by rhukster** [comment]
We plan on having this in the admin pro plugin, infact its already part of the media manager.

**Comment by rhukster** [comment]
I can see us having a 'view' option here tho in the regular admin.

**Comment by ganar** [comment]
It would be great to have the chance to do this in the regular admin. It is a real pain to generate the files. (at least an option to create the files in the command line based on the images in the folder)

**Comment by tadeo** [comment]
I totally agree it would be great to have the chance to create the meta.yaml files from the regular admin.
It could be presented as an option from the modal that verses "xxxx.xxx.meta.yaml doesn't exist", as a button labeled "Create a meta.yaml file".
In case the structure of the meta.yaml file is needed to be defined beforehand, the developer could upload a meta.yaml "template" in the page folder.
What do you think?

**Comment by Razunter** [comment]
This should be in the regular admin.

**Comment by robotrick** [comment]
When will Admin Pro be available?

**Comment by rhukster** [comment]
We ended up just adding feature to the free version.  Everything else is going to go into grav2

**Comment by robotrick** [comment]
@rhukster : when will this feature be available?
