### ISSUE TITLE
text-align in editor?

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#944]
As for a basic editor there are already a lot of features available. But I think one is missing. The possibility to align (center/left/right) text. Would be very nice to add this feature...

**Comment by leotiger** [comment]
Markdown does not include text align in its definition but I too felt that text alignment is something needed and in my StackEdit implementation for Grav I added support for text alignment.

This is a code chunk to be placed inside a onPageContentProcessed function that offer a solution:

```
		$content = $page->getRawContent();
		
		if ($this->config->get('plugins.studioeditor.blockalign_active')) {

			$this->align_classes = array('l' => 'text-left', 'r' => 'text-right', 'c' => 'center', 'j' => 'text-justify');
				
			//text = text.replace(/^\<(blockquote|p|div|h[1-6]|li)([^\>]*)\>(.*?)[ ]{1,}(\|{1,1})([l|r|c|j]{1,1})[ ]*\<\/(blockquote|p|div|h[1-6]|li)\>/gm,

			$content = preg_replace_callback('/^[\t ]*\<(blockquote|p|div|h[1-6]|li|th|td|dt|dd)([^\>]*)\>[\n]*(.*?)[ ]{1,}(;{1,1})([l|r|c|j]{1,1})[\n\t ]*\<\/(blockquote|p|div|h[1-6]|li|th|td|dt|dd)\>/mu', function ($matches) {
                $align_class = $this->align_classes[$matches[5]];
				
				if ( isset($matches[2]) && !empty($matches[2]) ) {
					if (strpos($matches[2], "class=") === FALSE) {
						$matches[2] = $matches[2] . " class='" . $align_class . "'";
					} 
					else {
						$matches[2] = preg_replace('/class=([\'|"])/i', "class=$1 $align_class ", $matches[2]); 
					}
				}
				else {
					$matches[2] = " class='" . $align_class . "'";
				}
				
				return "<" . $matches[1] . $matches[2] . ">" . $matches[3] . "</" . $matches[6] . ">";
				
			}, $content);
			$page->setRawContent($content);
			
		}
```

The first if clause 'if ($this->config->get('plugins.studioeditor.blockalign_active')) {` will not work but maybe someone wants to offer a plugin for this little feature... This is a "quick and dirty" improvement and it's possible that this solution is not fail-safe in all contexts. A plugin that allows to enable/disable such a feature maybe better than introducing something into the core markdown behavior.

In the editor all you have to do is to place a space + semicolon + l, c, j, r sequence at the end of a line.
u

**Comment by flaviocopes** [comment]
The shortcode-core plugin offers the `[left]`, `[right]` and `[center]` shortcodes which you can use in the page markdown, see https://github.com/getgrav/grav-plugin-shortcode-core#left-align

**Comment by leotiger** [comment]
Thanks. So nothing needed... I feel that ;r or ;c is easier and reflects the intentions of markdown better, but [center] some text [/center] may be safer. If I publish my StackEdit implementation, still not sure, I will do some additional tests to see what's better suited.
u

**Comment by axel-rank** [comment]
yes, sure I do use shortcodes, thought it would be easier in editor.
But as I pointed out
https://github.com/getgrav/grav-plugin-shortcode-core/issues/29
somehow those shortcodes breaks my css paragraph styles.

**Comment by leotiger** [comment]
@axel-rank 

If you'd like to do a test, I can set up a repository for this and you may test the alternative solution I mentioned above.

u

**Comment by axel-rank** [comment]
@leotiger 
Thank you, but as I'm using section shortcode in most cases aligning is not as urgent to me.
Didn't know markdown doesn't include aligning in its definition. I thought maybe it was forgotten in editor :-)
