### ISSUE TITLE
Left Menu of particles don't down toghether with the page

### ISSUE THREAD

**Issue by lauroguedes** [getgrav/grav-plugin-admin#945]
A problem that I identified when you down page the left menu of particles in tab layout don't down toghether. This is bad because I lose time.

**Comment by flaviocopes** [comment]
You mean the admin sidebar, the one with your name/avatar, Configuration, Pages, etc?

**Comment by lauroguedes** [comment]
It is in the panel gantry5 on grave

**Comment by flaviocopes** [comment]
Can you make a screenshot?
