### ISSUE TITLE
Anti-matter Update 2.0 - 2.1 Bringing Error 404

### ISSUE THREAD

**Issue by Githubjunkie-Micah** [getgrav/grav-plugin-admin#946]
Used the update process in the admin panel and when upgrading the antimatter theme it poped up and 404 error.

I am on Debian 8 with php7 installed. LAMP server run with virtualmin. If you need any more info let me know.

Even though it brings up the 404 it seems to be working. The first time I did it with php5-curl pkg install it blew up the whole site. I reinstalled from backup, upgraded to php7-curl package, and this time error 404 came up but didn't blow up the whole site.

**Comment by flaviocopes** [comment]
Cannot replicate this problem. If you have a chance, can you try installing the same site locally, and try updating Antimatter? Do you get the 404?
