### ISSUE TITLE
Password cannot be changed with user rights "pages"

### ISSUE THREAD

**Issue by trendschau** [getgrav/grav-plugin-admin#947]
Not sure if this is a bug: With the access-role "pages" I can enter a new password, but I cannot save it (error: You have insufficient permissions for task save). I think the permission to change the own password should be given to all roles ?

**Comment by trendschau** [comment]
Sorry, bug was reported already...

**Comment by flaviocopes** [comment]
Thanks for "upping" the issue, on it

**Comment by flaviocopes** [comment]
Fixed in https://github.com/getgrav/grav-plugin-admin/commit/4faf0c0b9546b5efb407a788a69e432a6c807816
