### ISSUE TITLE
enhancement - Save Button in Editor Fullscreen Mode?

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#948]
Think it would be a nice feature to have a save button when you have fullscreen view in editor.
Or even better the whole menu:
![menu](https://cloud.githubusercontent.com/assets/12480617/22461860/4c0ba38e-e7ab-11e6-80fa-e8c6ba953a5d.png)

**Comment by rhukster** [comment]
![2017-03-10 at 11 49 am](https://cloud.githubusercontent.com/assets/1084697/23808619/ba83c78e-0587-11e7-82cc-b06ee00ea6fc.jpg)

Coming soon!
