### ISSUE TITLE
Content tab is hidden behind Normal | Expert buttons

### ISSUE THREAD

**Issue by TJohnson93** [getgrav/grav-plugin-admin#950]
Not sure if using this feature wrong, however, when having multiple tabs created (via blueprints) some tab(s) get hidden behind the Normal | Expert toggle.

Please see below screenshot

![screenshot](https://cloud.githubusercontent.com/assets/6167090/22499346/eb553a78-e8a9-11e6-9045-7e13a06d81e8.png)

**Comment by rhukster** [comment]
Should be sorted with new tabs coming soon
