### ISSUE TITLE
Unable to delete responsive @2x and @3x images in Page Media

### ISSUE THREAD

**Issue by vladzhigulsky** [getgrav/grav-plugin-admin#952]
Please note the issue with Page Media and responsive images (@2x or @3x) described in #111 is still present. Error `File not found: image.jpg` while trying to delete the file.

It also affects `filepicker` field with `preview_images` enabled. 

Steps:
Uploaded `image@3x.jpg` and tried to select it via `filepicker`

Result:
The preview thumbnail is broken because it's not reading `@3x`

**Comment by fredrikekelund** [comment]
I tried to address a similar issue with #814. But I believe the code will only try to remove image alternatives if it can find the "base medium", ie. the image without any `@Nx`

**Comment by vladzhigulsky** [comment]
Thanks a lot!

**Comment by flaviocopes** [comment]
Thanks for reporting 👍
