### ISSUE TITLE
Admin multiple markdown editors to yaml to html

### ISSUE THREAD

**Issue by JohannMakitrin** [getgrav/grav-plugin-admin#953]
Hello,

first of all I want to thank you for this awesome cms!

I've created a custom page blueprint where you can add multiple markdown editors.
The field values will be saved into the YAML Frontmatter as a string. Now I'm searching for a way to convert that Markdown into HTML for my template? Or is there another way to handle multiple editors?

1. Admin Editor
![2017-02-02 08_24_29-bearbeiten faq _ erotikum prostschg](https://cloud.githubusercontent.com/assets/25499744/22540551/0c83af0a-e921-11e6-8d2d-1e5f44ed2cbc.png)

2. YAML Header
![2017-02-02 08_25_18-faq de md c__mamp_htdocs_faq atom](https://cloud.githubusercontent.com/assets/25499744/22540577/289e7fda-e921-11e6-9342-901af276fb69.png)

Thanks :)

**Comment by w00fz** [comment]
You can use the `|markdown` filter for that.

/ ref. https://learn.getgrav.org/themes/twig-filters-functions#markdown

**Comment by JohannMakitrin** [comment]
Thanks for the quick response!
It works now, thank you.
