### ISSUE TITLE
Can not insert alphanumeric slugs in the admin

### ISSUE THREAD

**Issue by Sergiop79** [getgrav/grav-plugin-admin#955]
Hi I found an issue when I was setting an slug like this `/27-abril-world-design-day/`

It shows a validation error:

```
Falló la validación. 
El slug debe contener sólo caracteres alfanuméricos en minúsculas y guiones
```
In english:

```
Validation failed.
The slug should contain only alphanumeric characters in lowercase and hyphen
```

The error appears on normal and expert mode.

If I edit the markdown file directly it works well

**Comment by flaviocopes** [comment]
Are you entering `/27-abril-world-design-day/`? 

You should just enter `27-abril-world-design-day`

**Comment by Sergiop79** [comment]
I'm just entering `27-abril-world-design-day`

I have tested also in another site, and shows this error message in english:

```
Validation failed: 
A slug must contain only lowercase alphanumeric characters and dashes
```

**Comment by flaviocopes** [comment]
I'm not able to replicate, I could save successfully.

Latest Grav + Admin? Can you copy/paste from here, to exclude the case an invisible char was copy/pasted from somewhere?

**Comment by Sergiop79** [comment]
In a fresh install Grav v1.1.15 - Admin v1.2.10, when trying to change a slug starting with a number:

(Animated gif)

![peek 2017-02-04 18-00](https://cloud.githubusercontent.com/assets/3718414/22620112/8c4acb9e-eb04-11e6-8151-5009d07d8dab.gif)

**Comment by flaviocopes** [comment]
Oh wait I replicated on a fresh install too

**Comment by flaviocopes** [comment]
We have some confusion on the default page validation rules - I was testing a custom page blueprint. The default had the problem.

PR https://github.com/getgrav/grav/pull/1292 should fix the issue, you can check it out.

**Comment by Sergiop79** [comment]
Thanks @flaviocopes , by curiosity, when we have de fix update avalaible?

**Comment by rhukster** [comment]
@Sergiop79 did you test the PR? Does it work for you? When we have some confirmation that it works, we'll merge with develop.  We're trying to get releases out weekly.

**Comment by Sergiop79** [comment]
@flaviocopes @rhukster 
Sorry, I'm beginner contributing open source projects on github.

How can I test the PR?

One option could be copy the changes on the files directly of the fresh installation, but is there any better way to do that?

Thanks

**Comment by Sergiop79** [comment]
@flaviocopes @rhukster OK, After applying changes manualy on a fresh install it works well.

**Comment by dyhla** [comment]
Slug can only contain alphanumeric or "-" characters, am getting that error when trying the create slung ....kindly help

**Comment by ricardo118** [comment]
cant have numbers as the starting value, but works if the numbers are in the middle
