### ISSUE TITLE
As standard all external links target="_blank"

### ISSUE THREAD

**Issue by Kuurusch** [getgrav/grav-plugin-admin#957]
Hallo, is it possible to set somewehere the setting, that all external links will open in a new tab?

I know in [Hugo](https://gohugo.io/) it is possible, but in Grav I couldn't find this option. Would be cool to hav!!

**Comment by rhukster** [comment]
You can't set this by default but you can do it easily via markdown:

```
![your text](http://yourlink.com?target=_blank)
```

Documented here: https://learn.getgrav.org/content/linking#target-attribute

**Comment by flaviocopes** [comment]
There are JS-based solutions, like https://css-tricks.com/snippets/jquery/open-external-links-in-new-window/

**Comment by Kuurusch** [comment]
Hm, ok thanks! Yea I saw the markdown solution. But wouldn't it a nice feature to have such a general setting?

**Comment by flaviocopes** [comment]
I don't think this is such a common need to be added to the core. A plugin could easily add the JS needed.

**Comment by flaviocopes** [comment]
Actually this https://github.com/sommerregen/grav-plugin-external-links should already do that

**Comment by Kuurusch** [comment]
Ah cool, thanks, yea that was what I looked for!

**Comment by HunterDG** [comment]
it appears at first glance grav-plugin-external-links doesn't work for grav external.md templates?  Is there a method to ensure all external.md links use target="_blank"?  Or perhaps a way to specify redirects open with target="_blank"

I ask here because the (empty) external.html.twig in grav/system/templates appears to now be part of the admin plugin

**Comment by rhukster** [comment]
External pages are rendered by the theme, so the logic for the target would need to be added to the theme's twig template that outputs the links.  For example I have custom functionality in Typhoon theme to do just this (although in Typhoon this functionality happens in the PHP class that generates the menu).

The point is this is a rendering thing, so is the responsibility of the theme you are using, not core Grav, or the admin.  A theme in Grav controls 100% of the rendering, this is what gives Grav the flexibility to realize any design.
