### ISSUE TITLE
Invalid Security Token

### ISSUE THREAD

**Issue by legas1** [getgrav/grav-plugin-admin#958]
Hello devs, 

I just setup site on my web provider hosting (subdomain) and registered to admin page, but the main page was trapped in loop, so I configured custom base url to correspond with my subdomain... and it worked.
But after I reloaded the admin page and logged in, the page only says `Invalid Security Token`. [Screen here](http://prnt.sc/e4s5zy)

**Some possibly relevant Info:**
- Installed `manually` by copying via FTP
- Grav and admin version are latest (releases) prior to today (`1.1.15` and `1.2.10`)
- I am using Chrome and I also cleared sessions/cookies for my subdomain
- PHP 7.0.5
- Subdomains on my web provider hosting are handled in `subdom` folder as folders and then rewritten by `.htaccess` to act as subdomain.
- Without configuring custom base url, admin page is alright.

Thank you very much and I hope to receive your reply and possible solution soon.

**Comment by Noah1911** [comment]
Well, I am not mastered in PHP scripting and this stuff, but tried to reproduced by creating localhost subdomain and route subdirectory to subdomain.localhost, not exactly the same result as on web provider hosting, but it looks like wrong routing happening somewhere... [Screen here](http://prnt.sc/e4ybca)

Btw: default home page working properly.

**Comment by flaviocopes** [comment]
Can you try installing a Grav instance in a subfolder on your main domain, to check if it's a problem related to the subdomain configuration, or a general server config issue?

**Comment by ilCoso** [comment]
Hi everybody,

same problem here. Fresh install gives me this error:

```
Request URL:https://www.ilcoso.org/admin/notifications.json/task:processNotifications
Request Method:POST
Status Code:403 Forbidden
Remote Address:107.6.154.186:443
```

The response is:

```json
{"status":"error","message":"Token di sicurezza non valido"}
```

**Comment by Noah1911** [comment]
Sorry for the late response... yes, that works good, but still not sure if its related to the web host redirecting configuration. However I noticed that error is produced on line 148 in adminbasecontroller.php. I have also found something about using $_SERVER["REQUEST_URI"] instead of $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"] on web host wiki, because it points to the current path of subdomain directory instead of redirected path of subdomain... but it can be unrelated. Anyways thank you for looking further on this possible issue.

**Comment by Noah1911** [comment]
Ok guys, I just managed to configure it properly, it seems the issue is cookie path...
In default it looks like:
![badconfig](https://cloud.githubusercontent.com/assets/827313/22864706/bec8cf00-f156-11e6-94e1-33536e8a0034.PNG)

After I set `system.yaml`'s `session.path` property to for example local `tmp` folder and clear cookies, it works and no Invalid Security Token appears.
![goodconfig](https://cloud.githubusercontent.com/assets/827313/22864742/240a10fe-f157-11e6-9a98-26f7a896e4e1.PNG)

**Comment by flaviocopes** [comment]
Thanks @Noah1911 that's definitely something that can cause of the problem, if PHP cannot correctly access the temp folder to store the session. @ilCoso can you check if your problem is the same?

**Comment by ilCoso** [comment]
if I set tmp in `system.yaml` `session.path` the page keeps reload with this message

![selezione_344](https://cloud.githubusercontent.com/assets/1561494/22922974/f7b02db4-f29f-11e6-9f1a-e139d1c56bb1.png)

The odd thing is that if I rollback and delete tmp from `system.yaml` the admin page keeps reload...
I have also tried with `'tmp/'` and `'/tmp'`.

**Comment by ilCoso** [comment]
Ok, forget my last post. I have cleaned everything (server-side cache, client-side cache and cookies) and I have successfully rollbacked. Now my cookies looks like these, but the problem still remains.

![selezione_351](https://cloud.githubusercontent.com/assets/1561494/22925500/45b289a4-f2a9-11e6-9a19-694bcda4684f.png)

**Comment by bmuessig** [comment]
I am facing the same problem, but there does not seem to be a working solution

**Comment by AmadeusSG** [comment]
Hi, anybody managed to resolve the problem? I'm still at a loss here; I can log in to the admin panel when I use my internal IP address, but when I do that using my domain name, it gives me the `invalid security token` error. I did the `session.path = tmp` patch, but it still doesn't work. Changing `base_url` screws up the site by doing too many redirects. Currently running Grav on my OrangePi, proxied to my main server.

**Comment by Sandro094** [comment]
Hey :-)

is there already a solution available for this problem?
I've installed grav on 2 different webhosting

**Comment by Sandro094** [comment]
*sry clicked on Comment to early*

*providers. On the first one it works all fine and logging in is no problem. But on the second one i can only login with Chrome. On iPhone, Firefox or Edge it is not working there is alwasy the message "Invalid Security Token"

Thanks for any help.

Regards Sandro

**Comment by riemers** [comment]
I also have this screen, i thought i fixed it with using 304 as rewrites but it failed on me later. When checking the 'form data' post i see that it uses this:
```
task:login
redirect:http://unknown/admin
```
So i presume this is also a reason why things fail, if i play around with settings that would be the redirect of my domain. For some reason it cannot properly detect the uri.route which is used to create the redirect url (as far as i can tell from themes/grav/templates/partials/login.html.twig)

**Comment by Aisbergg** [comment]
Same thing here. I use HAProxy in front of the webserver. I am not a PHP developrt but I was able to pin the problem . In `system/src/Grav/Common/Session.php` the varible `$this->grav['uri'];` not always reports the right host like `$_SERVER[HTTP_HOST]` does. It just prints out `unknown`.

So after I changed the `$domain` variable that is used for the cockie creation to `$_SERVER[HTTP_HOST]` it magically works again.

**Comment by rhukster** [comment]
Where exactly? `$this->grav['uri']` is the URI object, it's not a string value of the uri directly.

**Comment by Aisbergg** [comment]
I observed that the *domain* part in the cookie was set wrong (`unknown`). It lead me to the `system/src/Grav/Common/Session.php` where the cookie is set.
What I noticed is that the `$uri` is set to the value of `$this->grav['uri']`. The value provided by `$this->grav['uri']` already provides the wrong host:

```php
<?php
...
    public function init()
    {
        /** @var Uri $uri */
        $uri = $this->grav['uri']; // value is: https://unknown:80/
                                   // value of $_SERVER[HTTP_HOST] is: grav.dev.local
        $config = $this->grav['config'];

        $is_admin = false;
        $base_url = $uri->rootUrl(false);
...
?>
```

The host part of the `$uri` is then used as domain in the cookie:
```php
$domain = $uri->host();
...
setcookie(session_name(), session_id(), $session_timeout ? time() + $session_timeout : 0, $session_path, $domain, $secure, $httponly);
```

This way Grav complains with *Invalid Security Token*. I don't know about the worklfow, I mean when the session is created and what comes before so I can't trace it back further.

**Comment by Aisbergg** [comment]
Ok, my fault. The issue was an invalid hostname. Apparently an underscore is not allowed in hostnames and therfore Grav will set the hostname to `unknown`

**Comment by jodumont** [comment]
_might odd and not really related but_
but I **move from prod to dev** my site and had this error;

obviously in prod I have a valid ssl
and in dev I don't have a ssl certificate

so to fix this I change to setting in my `system.yaml` which are:

```
force_ssl: false # which is at true in prod
```

```
session
  secure: false # it is at true in prod
```

I hope that help someone and/or give a least some hint like this post did to me.

**Comment by tacoen** [comment]
Hi, I upgrade to Grav 1.77 and  This problem all back again.

For my localhost

in my system.yaml
```
session:
  enabled: enable
  initialize: true
  timeout: 3600
  name: gravsite1
  secure: false
  httponly: true
  samesite: Lax
  split: true
  path: null
```

If I set path to 'tmp' I will got Invalid security token notice.

if the path is 'null' then ERR_CONNECTION_RESET

**Comment by tacoen** [comment]
:( the only thing that solve the problem is by deleting my account .yaml

**Comment by jleaders** [comment]
No matter what I tried, I had to just uninstall php7.4-fpm and get php8.0-fpm to get past this error. (nginx over caddy proxy Ubuntu 20.04)
Cookies worked fine, permissions were right, and I could even log in, but then all subsequent queries/activities would pop up Invalid Security Token (like the newsfeed etc)

**Comment by mahagr** [comment]
Both ERR_CONNECTION_RESET and changing PHP version sounds like there may be a PHP bug, which caused this.

**Comment by jleaders** [comment]
@mahagr  My thoughts as well. I'd be mildly curious if anyone else was seeing this on 7.4 fpm

**Comment by maofree** [comment]
Hi
from some days I get the same problem "Invalid Security Token", the problem happens after 1 days from the last login.
it is a bug of grav cms not from php, I use other cms each days without any problems.
on my local server all is ok in the first day but if I wait some time to do the next login I get this error.

I tried to remove all cookies from chrome

to fix this problem I need to remove the account file and recreat it to get the login or use the comand
`bin/grav clearcache`

is it possible to fix this problem?

bye

**Comment by mahagr** [comment]
It's not a bug but a security feature. Security tokens are used to prevent session hijacking and they expire after a day.
