### ISSUE TITLE
Menu Button Missing?

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#959]
Updated Site:
![nobutton](https://cloud.githubusercontent.com/assets/12480617/22627340/b4c937fa-ebc1-11e6-9b11-7f97ec8666f9.png)
Fresh Grav 1.1.15 + Admin 1.2.10 install:
![button](https://cloud.githubusercontent.com/assets/12480617/22627345/bfa15ef0-ebc1-11e6-8ee2-4c17695220e9.png)

**Comment by flaviocopes** [comment]
You might need to clear the Grav and browser cache, as it's added by javascript and you might have that file cached

**Comment by axel-rank** [comment]
Ah, my fault. Modular pages, non routable, non visible...
