### ISSUE TITLE
Cannot activate theme

### ISSUE THREAD

**Issue by dimayakovlev** [getgrav/grav-plugin-admin#96]
Admin 0.4.1
![Cannot activate theme](https://cloud.githubusercontent.com/assets/8279974/9459228/acad20b6-4b01-11e5-85c9-fa36574ba220.png)
No matter what theme using.

**Comment by flaviocopes** [comment]
Thanks for reporting @dimayakovlev. It's themes missing a blueprint field. Today we'll release theme updates to fix the issue. Actually Afterburner2 is already working if you download the latest code from GitHub directly.

**Comment by rhukster** [comment]
All **our** themes have received updates with blueprints.
