### ISSUE TITLE
Visibility issue on modular

### ISSUE THREAD

**Issue by risoul** [getgrav/grav-plugin-admin#962]
Grav v1.1.15 - Admin v1.2.10 

I have a modular homepage
One module is set to:
title: Youtube
visible: false

And the link is shown into menu, i am unable to not showing the link.
Same problem for the link to login page.

**Comment by risoul** [comment]
Sorry it was not clear for me that I have to add hidemenu: true into header.
Then what is visible option for?

**Comment by flaviocopes** [comment]
This looks a feature specific to the Landio theme. 

The navigation (menu) code iterates over the modular page modules, and if that `header.hidemenu` property is set, hides the module from the menu.

The Login link follows another logic, it is added if the Login plugin is active: https://github.com/getgrav/grav-theme-landio/blob/develop/templates/partials/navigation.html.twig#L60-L106

**Comment by risoul** [comment]
Thanks, but then what is visible option for? it looks like hidemenu and visible are the same thiing.

**Comment by flaviocopes** [comment]
See https://learn.getgrav.org/content/headers#visible

**Comment by flaviocopes** [comment]
One is a theme feature. The other is a Grav core thing, sets the page visibility.
