### ISSUE TITLE
Cannot scroll after update

### ISSUE THREAD

**Issue by ivapelc** [getgrav/grav-plugin-admin#965]
I have fresh install of Grav + Admin. After todays upgrade of both Grav and Admin Plugin, I cannot scroll in the backend (no scrollbars)...

**Comment by rhukster** [comment]
We bet you are using cloudflare? https://github.com/getgrav/grav-plugin-admin/issues/808#issuecomment-276824595

You should be able to disable an option as outlined by this other thread.

**Comment by ivapelc** [comment]
I'm not - at least don't know about it. It worked just fine before the update.

**Comment by rhukster** [comment]
Try clearing your browser cache or try another browser. Actually nothing changed in this release that would change that behavior.  

--  
Andy Miller

**Comment by rhukster** [comment]
What's the URL of your site?

**Comment by rhukster** [comment]
Also, try the latest version that was just released with a JS bundle rebuild.  Should sort it.

**Comment by ivapelc** [comment]
Reinstalled whole Grav + Admin and everything worked fined until I switched language to "Czech". Then the problem occured again (no scroll; no Maintenance status on Dashboard; error after performing Check for updates). After switching back to "English" and clearing cache, it seems to work fine again, so the problem seems to be related to Czech translation...

**Comment by flaviocopes** [comment]
@ivapelc quick fix - edit user/plugins/admin/languages/cs.yaml like in here https://github.com/getgrav/grav-plugin-admin/pull/974/files

I fixed this in the Admin plugin for the next release.
