### ISSUE TITLE
issues with translation

### ISSUE THREAD

**Issue by diomed** [getgrav/grav-plugin-admin#966]
Some of these words remain untranslated. Same goes for plugins

![grav_issue](https://cloud.githubusercontent.com/assets/72777/22854868/668501dc-f076-11e6-91cb-cadce66bf962.png)
![grav_issue2](https://cloud.githubusercontent.com/assets/72777/22854870/67cc0266-f076-11e6-99cd-da80cf929ec9.png)

Also, when displaying date, in Croatian language we need to have words in different order:

it should say
prije 2 tjedna
prije 4 **mjeseca**
prije 1 **godine**

![screenshot_6](https://cloud.githubusercontent.com/assets/72777/22854884/a9cf1a04-f076-11e6-8995-2a458683b99e.png)

**Comment by rhukster** [comment]
Please provide a suitable fix on crowdin.com: https://crowdin.com/translate/grav-admin/2/en-hr

**Comment by flaviocopes** [comment]
Actually I told @diomed to post here, because the first two are untranslated strings in Grav (as the lang file looks ok), and the latter is an issue with words ordering, needs to be fixed in the code.
