### ISSUE TITLE
admin console errors

### ISSUE THREAD

**Issue by ec1solutions** [getgrav/grav-plugin-admin#970]
I have an up to date install of grav and admin plugin. The console log for the admin plugin is showing this:

Uncaught TypeError: Cannot read property 'call' of undefined
    at t (vendor.min.js?93845f0ff0:1)
    at Object.<anonymous> (admin.min.js?93845f0ff0:1)
    at Object.<anonymous> (admin.min.js?93845f0ff0:1)
    at t (vendor.min.js?93845f0ff0:1)
    at window.webpackJsonpGrav (vendor.min.js?93845f0ff0:1)
    at admin.min.js?93845f0ff0:1
t @ vendor.min.js?93845f0ff0:1
(anonymous) @ admin.min.js?93845f0ff0:1
(anonymous) @ admin.min.js?93845f0ff0:1
t @ vendor.min.js?93845f0ff0:1
window.webpackJsonpGrav @ vendor.min.js?93845f0ff0:1
(anonymous) @ admin.min.js?93845f0ff0:1

when I try to install the editor buttons plugin, I also additionally get:

Uncaught TypeError: Cannot read property 'Forms' of undefined
    at HTMLBodyElement.<anonymous> (table.js:4)
    at HTMLBodyElement.dispatch (jquery-2.x.min.js:3)
    at HTMLBodyElement.r.handle (jquery-2.x.min.js:3)
    at Object.trigger (jquery-2.x.min.js:4)
    at HTMLBodyElement.<anonymous> (jquery-2.x.min.js:4)
    at Function.each (jquery-2.x.min.js:2)
    at n.fn.init.each (jquery-2.x.min.js:2)
    at n.fn.init.trigger (jquery-2.x.min.js:4)
    at HTMLDocument.<anonymous> (admin.min.js:5)
    at i (jquery-2.x.min.js:2)

and the buttons do not appear in the editor

as a test I uninstalled the editor buttons plugin from an older instance of grav (1.1.15), then updated everything and reinstalled the editor buttons plugin, with the same result.

Is this a bug?

**Comment by flaviocopes** [comment]
The first issue comes from Webpack code, it is a JS build issue. I did not see it on the dev setup, but I downloaded a fresh grav+admin and got it. I rebuilt the JS, and it disappeared.

Will be fixed in the next release (that file was already rebuilt in https://github.com/getgrav/grav-plugin-admin/commit/b5384a4f8de4ff1a468791769a1540bf762e31e6, so should now be fine)

I think the second problem is linked to that. 

Can you try https://github.com/getgrav/grav-plugin-admin/archive/develop.zip and unzip in `user/plugins/admin`? Make sure you clear the browser cache.

**Comment by ec1solutions** [comment]
yep, all good now, thanks!

On Sunday, February 12, 2017, Flavio Copes <notifications@github.com> wrote:
> The first issue comes from Webpack code, it is a JS build issue. I did
not see it on the dev setup, but I downloaded a fresh grav+admin and got
it. I rebuilt the JS, and it disappeared.
>
> Will be fixed in the next release (that file was already rebuilt in
b5384a4, so should now be fine)
>
> I think the second problem is linked to that.
>
> Can you try
https://github.com/getgrav/grav-plugin-admin/archive/develop.zip and unzip
in user/plugins/admin? Make sure you clear the browser cache.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/9FOPlhNBhHSf872znUNi2ZkphdfsgNzHzioIf3Wr5u16nWTOo0JJBKOUApqllHWv-FJwYSdU0VAtoYPOiJPOi53j-Bgn8ADMmlCtVZ0aBNmhkFnipDK1kr_6399w6hVWJxUVKofbKP7J77CZqt4URxRMGZjxUA=s0-d-e1-ft#https://github.com/notifications/beacon/ARWo1kPn9SSlFWJw3KqxrLDJx_cSD9URks5rbzG2gaJpZM4L-eVF.gif
>

-- 
Shawn Kimberley
EC1 Solutions Ltd,

71c Pentonville Road,
Islington, London N1 9LP.

Tel: 0207 193 9294

*Learn more about ancient caves in Spain: *
https://www.youtube.com/watch?v=1UPURILbtsA
See our rescued dogs here: https://www.youtube.com/watch?v=aH4nSTemEdU

**Comment by rhukster** [comment]
Ok, update with this fix is released
