### ISSUE TITLE
responsive hamburger menu doesn't work

### ISSUE THREAD

**Issue by mtrefzer** [getgrav/grav-plugin-admin#972]
After the update to v1.2.11 the responsive hamburger menu doesn't work.
Tested with Firefox and Chrome on Android 5 and with Firefox on Ubuntu 16.04

**Comment by rhukster** [comment]
are you using cloudflare?

**Comment by mtrefzer** [comment]
No. I have it running on a dedicated Ubuntu Server.

**Comment by rhukster** [comment]
Actually we found an issue with the JS build in this release,  we will release again today.  You can direct install this version though and see if it helps: https://github.com/getgrav/grav-plugin-admin/archive/develop.zip

**Comment by mtrefzer** [comment]
Thanks, works again.
