### ISSUE TITLE
The connection to the GPM cannot be established

### ISSUE THREAD

**Issue by staspih** [getgrav/grav-plugin-admin#976]
Faced very unpleasant problem. Just installed Grav, for a new project. When i create a new blank theme via SSH, here's what I saw when I went in the admin panel: https://muut.com/u/getgrav/s1/:getgrav:xdI5:5.png.jpg
Lost all the plugins, the theme of antimatter. Right before this action, I installed dev-tools, installed and uninstalled the Gantry framework.
At the same time that the most interesting! Using file Manager I see all files including the newly created my theme!
If you need more information, no problem. Looks like a bug in the admin panel.

**Comment by flaviocopes** [comment]
I think it's an issue in the theme that makes Admin behave this way.. 

Deleting the theme from the `user/themes` folder does bring back Antimatter and the plugins? If so, upload the theme in a zip file here, so I can try it.

**Comment by staspih** [comment]
Well, only later...

**Comment by staspih** [comment]
You want me to upload grav completely?

**Comment by flaviocopes** [comment]
No just the theme that you created

**Comment by w00fz** [comment]
You can also upload it in private on our slack chat if you prefer.

https://getgrav.org/slack

**Comment by staspih** [comment]
[business.txt](https://github.com/getgrav/grav-plugin-admin/files/775842/business.txt)
Change the extension .txt on .zip. I have no it could not download the archive with the zip extension. This is the archive created me an empty theme (name: business), I doubt that there is something interesting.

**Comment by flaviocopes** [comment]
The theme's blueprints.yaml file is encoded as `Western (Windows 1252)`, Cyrillic is not supported in that format (the editor told me) and the `author.name` field was rendering like this:

```
author:
  name:  ÐŸÑ‹Ð: ÐŸÑ‹Ñ…Ñ‚Ð¸Ð½ Ð¡.Ð.
```

and caused the issue.

Saved as UTF-8, tried

```
author:
  name: Древнерусский
```

and worked fine.

**Comment by staspih** [comment]
I understand, but the fact that I created a theme via ssh! Turns out ssh you can't use other languages besides English?
