### ISSUE TITLE
selection highlight in editor

### ISSUE THREAD

**Issue by leotiger** [getgrav/grav-plugin-admin#977]
This has been reported before but from my experience: selection highlighting still does not work correctly in the codemirror instances out of the box. This is one of the biggest issues with the current editor implementation. I suggested StackEdit, but with highlighting resolved the current editor is a valid alternative.

**Comment by leotiger** [comment]
<img width="843" alt="screen shot 2017-02-14 at 17 41 51" src="https://cloud.githubusercontent.com/assets/137951/22938817/33546b22-f2dd-11e6-8838-950a15031cc5.png">
(Selection not visible but text selected as cursor is not visible)

<img width="853" alt="screen shot 2017-02-14 at 17 42 05" src="https://cloud.githubusercontent.com/assets/137951/22938816/33502a12-f2dd-11e6-871f-8e00df4cc7b7.png">
(Nothing selected, cursor visible)

**Comment by leotiger** [comment]
I found the problem, thanks to @flaviocopes and his insistence. The problem relies in the contrast and highlight color used. Depending on color profile it's not working. I would suggest to use something closer to preview. Color profile for highlighting in preview seems to be fail-safe.

u

**Comment by flaviocopes** [comment]
Ok the problem is, when something is selected, the cursor is not visible, right?

**Comment by leotiger** [comment]
No, the problem is that the selection does not appear highlighted. It's like working blind as you don't see selected characters, words, paragraphs distinguished from the rest of the content. 

Or to put it the other way around: It's normal that you don't see the input cursor when you select content chunks.

A simple fix is to choose a color that conveys more to the standards for highlighting. I believe that codemirror uses a fixed color scheme right now and this color scheme does not work for example with the standard color scheme that comes with my monitors.

**Comment by leotiger** [comment]
@flaviocopes Thanks for looking into this. One more hint: As highlighting works for you, the screenshots work for you as well, you will see, even on my screenshots, the text chunks highlighted whereas on my monitors the screenshots do not show nearly a difference at all.

**Comment by w00fz** [comment]
This is now changed to use your OS native highlight colors.
