### ISSUE TITLE
Can't order Children of Modular Page in the admin section

### ISSUE THREAD

**Issue by OvidiuS** [getgrav/grav-plugin-admin#978]
I've created a modular page, with no custom ordering for its children - in fact no ordering whatsoever, the only things in the frontmatter of the modular page are:

```
---
title: Home
content:
    items: '@self.modular'
---
```
I've also enabled numeric prefixes for the children of the modular page, and their folders are named accordingly.

Still, when I edit one of the children in the back-end, the Ordering field says: "**Parent setting order, ordering disabled**", instead of letting me drag&drop to reorder the pages - even though the parent is clearly not specifying any ordering whatsoever.

Thinking it's a bug, but if I'm doing something wrong please let me know.

**Comment by flaviocopes** [comment]
It's not a bug, you specify the ordering of a modular page children in the modular (parent) page, using the collection ordering options: https://learn.getgrav.org/content/collections#ordering-options

We have plans for a better way to reorder them, for a future release.

**Comment by OvidiuS** [comment]
Just to be clear: I was aware of how the ordering is done through YAML frontmatter or ordering dropdowns in the modular parent. I was asking about a way to add a field that allows for manual drag-and-drop ordering in a blueprint.

Glad to hear you have plans to improve this.

**Comment by flaviocopes** [comment]
Yes, the main source of confusion is probably trying to reorder from within a modular child (that's where you see the "Parent setting order, ordering disabled" line).

But, we know this is a UX issue.
