### ISSUE TITLE
403 Forbidden on Admin notifications.json file

### ISSUE THREAD

**Issue by adamjansch** [getgrav/grav-plugin-admin#979]
Hi,

When I updated to version 1.1.15 on two Grav sites I started getting 403 errors in the Admin panel. The issue persists in 1.1.16. The error (which appears in a red box before fading away) says:

> 403
> Forbidden
> 
> Access to this resource on the server is denied!
> 
> Proudly powered by  LiteSpeed Web ServerPlease be advised that LiteSpeed Technologies Inc. is not a web hosting company and, as such, has no control over content found on this site.

More details are provided in Chrome's console:

> POST http://adamjansch.co.uk/admin/notifications.json/task:processNotifications 403 (Forbidden)

Functionality in the Admin panel does not appear impacted by the error, however a knock-on effect of this problem is the error is triggering my web host's firewall block.

Note, I'm not certain this issue was caused by updating Grav: it was the first Grav update I performed after my web host did a server switch, so I don't know how that might impact it. What I can say is I've had no issues with Grav 1.1.15 or 1.1.16 on my local server.

Any ideas how to fix?

**Comment by flaviocopes** [comment]
I can see a 403 on processNotifications mentioned in https://github.com/getgrav/grav-plugin-admin/issues/958, that issue was linked to a tmp folder path.

**Comment by adamjansch** [comment]
I saw that post, but it seemed like that issue may not have been fixed.

Other recent posts on 403s here have mentioned mod_security, and when I disabled mod_security temporarily on one of my Grav sites the issue went away. Is there a way to fix without disabling mod_security?

**Comment by rhukster** [comment]
If you provide your mod_security rules, we can probably take a look and see which rule is probably tripping this ajax call rather than disabling the whole mod_security.

**Comment by adamjansch** [comment]
Thanks, I'm on shared hosting so just finding out how to get access.

**Comment by axel-rank** [comment]
Maybe look this issue:
https://github.com/getgrav/grav-plugin-admin/issues/951

**Comment by flaviocopes** [comment]
This issue https://github.com/gantry/gantry5/issues/1137#issuecomment-202322740 contains some more mod_security related suggestions

**Comment by adamjansch** [comment]
Thanks @flaviocopes. Is `<IfModule mod_security.c> SecFilterEngine Off SecFilterScanPOST Off </IfModule>` the analogue of switching off mod_security in the cPanel?

Currently working with my web host to understand which rule(s) may be the issue. Will post back with any conclusion.

**Comment by adamjansch** [comment]
My web host was able to pinpoint the offending rule and whitelisted it, everything is working fine now. Thanks everyone for your help!

**Comment by flaviocopes** [comment]
@adamjansch what was that rule, if others stumble on the same problem?

**Comment by adamjansch** [comment]
It was rule 350147 (http://wiki.atomicorp.com/wiki/index.php/WAF_350147).

**Comment by axel-rank** [comment]
Yes, the same like #951.
