### ISSUE TITLE
Use transifex or alternative platform to manage translations

### ISSUE THREAD

**Issue by flaviocopes** [getgrav/grav-plugin-admin#98]

**Comment by rhukster** [comment]
I would like to check out the various options and make a decision.  What else is there other than transifex???

**Comment by rhukster** [comment]
List of options:

* https://weblate.org
* http://pootle.translatehouse.org/

**Comment by rhukster** [comment]
BTW seems transifex doesn't like our **single** file format `languages.yaml` for all languages in one file. 

This approach was adopted because it's just plain faster than having a single file for each translation.  Imagine with 30 plugins each with 10 translations, that's 300 individual files that have to be loaded and merged!

**Comment by sourcesoldier** [comment]
I'm implementing Zanta for a Magento project right now and I can highly recommend it, although it runs on JBOSS/Wildfly JVM ... but other then that it's a full blown, open-source solution backed by redhad. 

Can work with most of the common translation files like GETTEXT/PO, etc. and comes with a nice REST-Api as well.

**Comment by MATsxm** [comment]
Take also a look at https://crowdin.com

**Comment by rhukster** [comment]
I actually just checked out crowdin and it looks pretty good.  I've applied for an open source account, so hopefully we can get moving with that!

**Comment by MATsxm** [comment]
This tool will soon be used for Joomla! Core translations (in test) as many features are very interesting (e.g. voting for translation), it allows and makes easier the quality ctrl (a lack with Transifex) and that developers are reactive to requests for improvements.
Using soooooooo many different tools, I can say it is not perfect but is, with the TwitterTC (private system), far ahead from others.

**Comment by rhukster** [comment]
I just need to work out how best to handle the workflow... I do like merging back in with github.  Also when i 'build' it outputs the files in this format:

```
en/en.yaml
fr/en.yaml
de/en.yaml
```

Really need it to output:

```
en.yaml
fr.yaml
de.yaml
```

**Comment by MATsxm** [comment]
On Crowdin, there must be a feature to allow the files for downloading.
IMHO, this could be interesting.
![crowdin](https://cloud.githubusercontent.com/assets/1972717/11945593/eaf5d736-a827-11e5-8f01-945a062a338c.png)
Thanks

**Comment by rhukster** [comment]
There are currently two issues:

1) The translations contain all strings, translated **and** english .. We need to use approval process to stop this I think

2) The download does produce the correct yaml files, however they have a header separator at the top that breaks our YAML parsing.  This has to be removed before they will work.

**Comment by NeonTigerWeb** [comment]
@rhukster do you want to add me as assignee for this?

**Comment by flaviocopes** [comment]
Settled on https://crowdin.com/project/grav-admin

**Comment by glittergutter** [comment]
Another option to manage translations is the localization platform [POEditor](https://poeditor.com), if you're still looking.

**Comment by rhukster** [comment]
Actually we are using crowdin and really like it.  Check out the link above by @flaviocopes...
