### ISSUE TITLE
Question: Can the admin be dashboard be extended?

### ISSUE THREAD

**Issue by chriseaton** [getgrav/grav-plugin-admin#981]
Is there a good approach to adding custom widgets to the admin dashboard, short of editing the grav-plugin-admin code? Can it be done through another plugin (a plugin that affects a plugin)?

**Comment by rhukster** [comment]
Yes it is possible. Take a look at the DataManager plugin: https://github.com/getgrav/grav-plugin-data-manager

**Comment by chriseaton** [comment]
Thanks that was really helpful!

**Comment by flaviocopes** [comment]
Also Comments and Shopping Cart add a panel in Admin.
