### ISSUE TITLE
Backup File in Admin

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-admin#982]
After the backup is complete I can download the zipped backup. But if I do not download soon there's no way to download again. So I have to do a backup again. Maybe add a way to download the file again..?

**Comment by rhukster** [comment]
Check this out: https://github.com/leotiger/grav-plugin-backup-manager

Also Admin Pro is going to have some similar features

**Comment by flaviocopes** [comment]
(p.s. the backup is stored in /backup, so you can access it via FTP)

**Comment by axel-rank** [comment]
@flaviocopes 
Yes, I know. Thought for users without ftp/ssh access. (or sometimes ftp/ssh ports are blocked by Firewalls).
So I try backup-manager.
