### ISSUE TITLE
Add ability to 'direct-install' a plugin or theme

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav-plugin-admin#985]
This would provide the ability to install a plugin or theme from via file upload or a URL.

**Comment by w00fz** [comment]
Would be useful to have a toggle for secure/unsecure where in secure mode we only allow direct installs that match the getgrav domain and in insecure any. This way admins can protect their site a bit better.

**Comment by rhukster** [comment]
This is already added for next admin release:

![2017-03-06 at 10 44 am](https://cloud.githubusercontent.com/assets/1084697/23621985/1473e930-025a-11e7-8b8a-dba6c3a68778.jpg)

![2017-03-06 at 10 43 am](https://cloud.githubusercontent.com/assets/1084697/23621941/e1ffbba0-0259-11e7-9c68-ee64d0371038.jpg)
