### ISSUE TITLE
Supported language issue

### ISSUE THREAD

**Issue by defcon6** [getgrav/grav-plugin-admin#987]
Using the admin mgr I added languages "en" and "nl" saved and later I removed the added languages. I had expected it to go back to default but it gave a 404 error page. When I added "en" again and refreshed the page it worked.

**Comment by flaviocopes** [comment]
You got a 404 on a site page, in the frontend?

**Comment by ganar** [comment]
Yes: we can confirm this issue: here is the example. [Search works here](http://kristinaencasa.com/cms/es/contenidos), [but not here](http://kristinaencasa.com/cms/es/contenidos/pan-en-macetas), where it produces a 404, ( the search icon is at the top of the page)

**Comment by flaviocopes** [comment]
@ganar yours is a different issue. The OP got a 404 when editing languages in Admin. Your issue is unrelated to the Admin plugin, rather to the configuration of the `route` https://github.com/getgrav/grav-plugin-simplesearch#config-options

**Comment by ganar** [comment]
Where should I post this issue?, I followed the instructions, searched all the closed issues, but I still get 404. Here is the configuration of the route in `simplesearch.yaml`, within `user/config/plugin/simplesearch.yaml`

	enabled: true
	built_in_css: true
	display_button: true
	min_query_length: 3
	route: /search
	template: simplesearch_results
	filters:
	filter_combinator: and
	ignore_accented_characters: true
	order:
	  by: date
	  dir: desc

**Comment by flaviocopes** [comment]
It could be a theme issue with the search code, or the plugin config, best is to look at the Blog Site skeleton https://demo.getgrav.org/blog-skeleton which has a similar thing, and inspect what's different in the configuration, and in the search box generated HTML

**Comment by ganar** [comment]
@flaviocopes thanks for your prompt reply:

You are right: I switched to the _antimatter_template and the search box worked on the third level of the site.

I've searched in the places you told me and also pored over the _antimatter_ configurations files.

I did the template for the site above, and it must be that I'm missing some configuration item, but can't find it. Can you point me to an appropriate solution? (am going bonkers)

**Comment by flaviocopes** [comment]
If you are overriding the search plugin code somewhere, check that it's the same as in the plugin.

**Comment by ganar** [comment]
I did: it is a bit different, but verbatim from the cookbook in the Grav Docs. I also just deleted my code and used the one provided by the plugin, and still did not work. (weird)

**Comment by mahagr** [comment]
I believe this has been fixed in Admin 1.10
