### ISSUE TITLE
Theme install error in Admin Panel

### ISSUE THREAD

**Issue by dvisan** [getgrav/grav-plugin-admin#996]
![image](https://cloud.githubusercontent.com/assets/13108600/23258472/13b31c1e-f9d1-11e6-9c37-a5f031d8ac3b.png)

Apparently it's an Admin Panel issue because installing them by `bin/gpm install themename` works fine.

**Comment by flaviocopes** [comment]
Is this just happening on themes? Here is a list of common causes of that problem: https://learn.getgrav.org/troubleshooting/common-problems#invalid-security-token but it's not exhaustive.
