### ISSUE TITLE
Admin Editor enchancments

### ISSUE THREAD

**Issue by Sommerregen** [getgrav/grav-plugin-admin#997]
In the first round of the community request [Brainstorming: Ideas for a WYSIWYG/Markdown Admin editor](https://getgrav.org/forum#!/general:brainstorming-ideas-for-a) the overall wish is to have a drag'n'drop image upload method on the editor just like GitHub or other editors already provide. I'm pretty sure it is doable and I therefore open this ticket.

It is also an offline editing request so that the Grav editor stores its content in the local storage of the browser, but I'm unsure whether this can be implemented easily without any big refactorings.

**Comment by OleVik** [comment]
In regards to the first point: Grav already provides drag'n'drop support in the "Page Media" field of the Admin-plugin. There exist scripts which would extend this to the textarea itself, so dropping an image onto it will insert the Markdown-code at the cursor, then the image just needs to be pushing into the media-manager like Grav does currently. There are also scripts for capturing clipboard-contents, which would work the same way.

On the second point, about localStorage: Yes, it can without any interference with Grav at all. The only potential conflict would be if Grav auto-saves content and brings this into the textarea upon subsequent, "online", load. LocalStorage, by it's nature, is decoupled from HTML-tags as much as possible, and you make the content persistent only in the browser's cache. Really, you'd only need a small piece of JavaScript to every so often iterates over the relevant form-fields present in the page (which stores title, Markdown content, etc), encodes it as JSON, stores it, and then loads it back when the user re-opens the page. A [simple example](http://htmldog.com/guides/javascript/advanced/localstorage/).

Overall, it seems to me that the "only" cosmetic change needed for a pure WYSIWYG-editor is a writing-mode that hides Markdown. As mentioned many times, these exist for HTML, and I agree that converting back and forth between HTML and Markdown is messy and creates more overhead than necessary. Thus, the main missing mechanism to pull this off is a textarea where Markdown can be edited with no formatting/code *visible*, though still there behind the scenes and when saved.

**Comment by w00fz** [comment]
FWIW there is already drag and drop support, the only diff is it doesn't upload the image but rather add the markdown link.
You can drag and drop markdown files from your desktop right now and their content will be loaded in the editor.

**Comment by Sogl** [comment]
I need an option to configure path of Media Manager:
![image](https://cloud.githubusercontent.com/assets/7556290/23287524/17196400-fa92-11e6-9760-1cc3a084b73b.png)

By default it's root folder, but for example, I want to specify `root\images` folder with blueprints for my blog posts.
I can't find needed `folder` option for this type of field in documentation:
https://learn.getgrav.org/forms/blueprints/fields-available#the-pagemediaselect-field

It is only available for filepicker field:
https://learn.getgrav.org/forms/blueprints/fields-available#the-filepicker-field

**Comment by paulhibbitts** [comment]
I think it would be a pretty awesome enhancement if dragging and dropping an image onto the edit area added that media to the page _and_ created a link to that media for display. This also would streamline what takes two actions now (upload media, add Markdown image link) to one step.

**Comment by mahagr** [comment]
Closing because of WYSIWYG will be implemented in another plugin.
