### ISSUE TITLE
Conflicting template paths

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav-plugin-admin#999]
Whilst troubleshooting with @ricardo118 on Slack I stumbled upon a bit of a quandary: Plugins which add or override templates in the Admin-interface are, of course, prone to conflicts due to precedence. But it also appears difficult for plugins to utilize different templates, using the method [described here](https://getgrav.org/forum#!/plugin-development:overwrite-adminplugin-pages):

```
public static function getSubscribedEvents()
{
    return [
        'onPluginsInitialized' => ['onPluginsInitialized', 0],
        'onAdminTwigTemplatePaths' => ['onAdminTwigTemplatePaths', 0]
    ];
}

public function onAdminTwigTemplatePaths($event)
{
    $event['paths'] = [__DIR__ . '/admin/templates'];
}
```

The same result occurs when pushing this directory to `twig_paths` with `$this->grav['twig']->twig_paths[] = __DIR__ . '/admin/templates'` (see [this post](https://getgrav.org/forum#!/plugin-development:admin-plugin-elements)).

As a test case I ran a fresh, uncached installation of Grav v1.1.17, Admin v1.2.15 (equal to [current develop-branch](https://github.com/getgrav/grav-plugin-admin/commit/d02d1102871418215f5ffefc8287a313b791dce5)), Admin Identicons [v1.0.2-RC1](https://github.com/OleVik/grav-plugin-adminidenticons/releases/tag/v1.0.2-RC1), and Admin Styles [v1.0.1-RC1](https://github.com/OleVik/grav-plugin-adminstyles/releases/tag/v1.0.1-RC1) (the latter two updated to be more equal and readable). Because of AdminStyles alphabetical name it occurs later in the load-order than AdminIdenticons, thus its templates should take precedence in a conflict - but there are no conflicting templates between them.

This is most apparent in the respective settings-page of each plugin: The AdminStyles specialized radioimage-field renders, but the Identicons do not.

Is there a recommended way of adding templates that would resolve this?

Also, could it be an idea to more clearly delineate the use of priority in `getSubscribedEvents()`? That is, hint at what priority-ranges are best suited for the task the plugin's template accomplishes, or maybe even make it configurable in the plugin to avoid future conflicts.

**Comment by flaviocopes** [comment]
Priority: higher number = event will be run first.

But in this case my suggestion works only if a single plugin is overriding / providing an Admin twig template, as the last plugin that executes (lower priority), will have the final word. Which is the opposite of what we want.

Instead,

```php
public function onAdminTwigTemplatePaths($event)
{
    $event['paths'] = array_merge($event['paths'], [__DIR__ . '/admin/templates']);
    return $event;
}
```

(adding to the paths, not overwriting the paths array on every plugin event execution) will do the correct job. 

I will add a comment to that forum post to correct it.

**Comment by OleVik** [comment]
That does indeed resolve the unintended conflict. I'll make a note of this issue, as it serves as a good reference for best practices in overriding admin templates non-destructively.

What would your recommendations be for using `priority`? People typically default to 0 because it's more convenient and fail-safe (and used in examples), but it could potentially end up as an ecosystem of difficult-to-trace conflicts that are resolved by alphabetical order in `$this->grav['twig']->twig_paths`.

Say, for example, that two plugins were overhauling templates in the Admin-plugin with overlap between Admin, Plugin One, and Plugin Two:

![image](https://cloud.githubusercontent.com/assets/974717/23331753/94149d32-fb6c-11e6-95f1-0c3e05276173.png)

If both Plugin One and Plugin Two modified the Navigation-template, Plugin Two would take precedence if both used 0 as their priority for the templates. This would happen for all the templates that overlap between the two plugins, but qualitatively some templates are more important for the plugin than others - like the Avatars for AdminIdenticons, but not really the range-field as that is an added convenience.

How would the plugin's author evaluate what priority to use, taking into consideration the effect of overriding larger and smaller templates? With AdminIdenticons I could presumably assign higher priority to the important templates (avatars), and lower priority to the minor (range-field) ones, by adding several callbacks to `getSubscribedEvents()`. But assigning priority on a scale from 0 to [1000](https://github.com/getgrav/grav-plugin-admin/blob/develop/admin.php#L559), what would be appropriate?
